### ISSUE TITLE
Mekanism and Refined Storage issue as well as slight bug with Mystical Aggriculture  release 0.29

### ISSUE THREAD

**Issue by ntimpson** [AllTheMods/ATM-6#100]
I have been trying several different mods furnaces or smelters to work with the Refined Storage crafter, they all do the input just fine (some i had to configure) but I couldn't get any to work. I want to use Mekanism's smeltery factory with it. also as a side note, mystical aggriculture's pedestal recipes are showing in single player but not on my server (I have completely reloaded the mod several times to get it to work.

**Comment by Flowrider** [comment]
> I am also having an issue with Mystical Agriculture recipes not showing up in multiplayer.

Check the recipes first in the singleplayer, then they will be shown in the multiplayer.

**Comment by whatthedrunk** [comment]
We are currently on 1.16.3 so removing older issues to make way for new ones. If you want to test it out join the discord for an early beta. New update will be on Twitch / Curseforge once Mekanism pushes their update to the site.

**Comment by mtbrenner** [comment]
This is still an issue. I reported it here
https://github.com/refinedmods/refinedstorage/issues/2717
