### ISSUE TITLE
Server won't start

### ISSUE THREAD

**Issue by Artssss** [AllTheMods/ATM-6#1001]
Anytime I try to start the server I get this error after it has installed everything 
```ERROR StatusLogger log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...```

**Comment by whatthedrunk** [comment]
https://twitter.com/ForgeDevTeam/status/1356456863684943872

**Comment by whatthedrunk** [comment]
Forge has fixed the issue. Try again now.
