### ISSUE TITLE
Modular Routers Activator on Resourceful Beehive

### ISSUE THREAD

**Issue by kaoticdev** [AllTheMods/ATM-6#1004]
1.5.0
Using Modular Routers activator module on a Resourceful Beehive causes server/single player crash.

**To Reproduce**
1. Modular Router with Activator modules beside bee hive. 
2. Set Activator to use item (scraper) on beehive
3. Crash

https://pastebin.com/nK2E3p8i

**Comment by Epic428** [comment]
It’s failing on this line in Immersive Engineering according to that crash log

https://github.com/BluSunrize/ImmersiveEngineering/blob/37fe9a3b18412f9487518ccc44c199a7e744dc3d/src/main/java/blusunrize/immersiveengineering/common/EventHandler.java#L377

**Comment by Pdiddy973** [comment]
if you need any more help feel free to ask in our [discord](https://discord.gg/K5FBPYa)
