### ISSUE TITLE
Dupe bug from item stacks

### ISSUE THREAD

**Issue by kottb** [AllTheMods/ATM-6#1006]
1.5.1
you can dupe anything if you have at least 1 stack of the item plus a minimum of 1 you cant pick up.

Does NOT work in creative mode. Bug works so long as you can only pick up part of an item stack on the ground. the amount of items in the stack on the ground will not update(or something). eg you have 32 items in a stack in your inventory and there are 33 floating on the ground. the rest of your inventory is full of other things so when you walk over the 33 items on the ground you pick up 32 and leave 1 on the ground, accept you didnt leave 1 on the ground you left 33 on the ground and still picked up 32.

I haven't checked on all items but it works on most items that can stack(ender pearls too)

**Comment by ViRb3** [comment]
Are you sure this isn't just a graphical glitch? As far as I remember from the beginning of ATM6, items would not always disappear from the ground after appearing in your inventory, but you can't pick up more than there originally were.

**Comment by kottb** [comment]
It happens when you don't pick up a whole chunk of items on the ground. I've tested this in a server and in single player. if you pick up only part of a mass of combined items on the ground it will not update the number of items on the ground but still fill the stack in your inventory. if you have like 10 items combined on the ground you can stand on it and hold q and never run out of items to throw. the item your throwing and the item on the ground have to be the same if that wasn't clear. I've tested it with like 10 different stackable items and then emptied my inventory and pick up all the items on the ground and got several stacks of items in my inventory when I started with 1 stack and change every time.

**Comment by ViRb3** [comment]
Gotcha. I haven't tested this particular case so I guess it could be a problem.

**Comment by InCrIpTiOn** [comment]
Tested and replicated on my system, 1.5.1

**Comment by JuninhoBR10** [comment]
Tested and replicated, 1.5.1

**Comment by Credit-Score** [comment]
Tested and replicated as well. Originally thought it was a bug with item magnets, but nope, just some mod messing with item pickup.

**Comment by ladylexxie** [comment]
This is just a visual glitch, doesn't dupe in current versions of the modpack.
