### ISSUE TITLE
[1.5.1] Mekanism logistical sorter and ElementalCraft pure ore chunks

### ISSUE THREAD

**Issue by ben569** [AllTheMods/ATM-6#1010]
**Describe the bug**
One can only add one pure ore chunk per color.

**To Reproduce**
1. Add an itemstack filter for the ore chunk with a specific color;
2. Click save;
3. Add an itemstack filter for another ore chunk with the same color (for instance to put them in the same machine);
4. The second one won't appear.

**Screenshots**
![2021-02-04_08 38 33](https://user-images.githubusercontent.com/12788482/106861093-950a4200-66c5-11eb-9a4d-7cb3952ef234.png)
![2021-02-04_08 42 16](https://user-images.githubusercontent.com/12788482/106861104-99cef600-66c5-11eb-8546-2863aec76b6d.png)
![2021-02-04_08 42 21](https://user-images.githubusercontent.com/12788482/106861108-9b98b980-66c5-11eb-818f-f117dc0782ba.png)

**Additional context**
Having different ore chunks being sent in different colors does work.
The dictionary from Mekanism doesn't give any information about the item that could allow sorting another way.

**Logs**
It doesn't seem to add any logs to the minecraft log, as reported by multimc on archlinux.

**Comment by ben569** [comment]
Should I open an issue with Mekanism, then? If it's their problem, their github doesn't seem to have it registered.

**Comment by ladylexxie** [comment]
This is how Elementalcraft is registering the pure ores, there's nothing we can do to change this. Pure Ores are one item and all the different version just have different NBT tags.
