### ISSUE TITLE
(Suggestion) Remove Rats mod

### ISSUE THREAD

**Issue by InCrIpTiOn** [AllTheMods/ATM-6#1011]
The rats mod has continuously been the cause of various crashes, lag, and numerous bugs (including rats disappearing, dying randomly, etc). I haven't seen it be used much in servers and most of it's features are useless in the mid-end game as item pipes are much more efficient and lag/bug-free.

The only problem I can see is losing the ability to tick-warp, if anyone can suggest a mod in this thread which has a similar function I support adding it.

The [Rats mod github](https://github.com/Alex-the-666/Rats/issues) has many unresolved issues that decrease stability in modpacks using it like allthemods6.

**Comment by Natey214** [comment]
The great thing about All The Mods is that it allows you to play in whichever way you want and don't need to use everything. I for one greatly enjoy Rats as it is a very entertaining automation mod that is technologically independent and I don't like technology in Minecraft while I enjoy playing with people who do.

**Comment by Svalkur** [comment]
As a server owner i agree. It causes more crashes and issues than its worth. Removing it would make things alot more stable. and if people do for some reason want to use the mod on their own games they can add it in themselves. Instead of people running servers having to ask everyone to remove it from their packs to connect to the server.

**Comment by jpwanabe** [comment]
In the 2 servers I run, this mod crashes the server almost every other day. Please can we get it removed.

**Comment by Hermsmegerms** [comment]
I have been running an ATM 6 server for nearly a month now. This mod is not crashing my server at all.

**Comment by jpwanabe** [comment]
I can post the crash logs

**Comment by NetMasterFlex** [comment]
I have been running ATM6 rats included from version 1.1.3b to 1.5.1 and have not had an crashes from that particular mod.
