### ISSUE TITLE
[1.5.1] Mana tablet to Creative Mana Pool

### ISSUE THREAD

**Issue by gdar463** [AllTheMods/ATM-6#1012]
**Describe the bug**
You can create from a empty mana tablet a Everlasting Guilty Pool

**To Reproduce**

1. Craft a mana tablet
2. Put the mana tablet in the crafting table

**Screenshots**
![image](https://user-images.githubusercontent.com/63969957/106922359-47b1c300-670d-11eb-805a-ba2458755999.png)

**Additional context**

**Logs**

**Comment by WhitePhant0m** [comment]
Update to 1.5.1
