### ISSUE TITLE
RS Crafter-Manager can be sorted with inventory tweaks

### ISSUE THREAD

**Issue by Jay-TheAnxiousKiwi** [AllTheMods/ATM-6#1016]
All The Mods 6 - 1.5.1
When looking in the refined storage crafter manager, it is possible to middle click and sort all the recipes throughout the network. This can also void items in the network. 

**To Reproduce**
1. set up basic RS network with a few crafters and patterns set up
2. open a crafter manager and middle click to sort, sometimes you have to click twice. 

This should be blacklisted from inventory tweaks.

**Comment by ladylexxie** [comment]
Fixed in #1965
