### ISSUE TITLE
Unable to load game due to Create mod

### ISSUE THREAD

**Issue by Withinchaos** [AllTheMods/ATM-6#1020]
Version: ATM 6 1.5.1 (and 1.5.0)

Hi, I'm having an issue when trying to load up my save. I recently started playing with the Create mod and I am now unable to load my world.
It loads to a sky blue screen and then immediately saves and closes generating the report below.

It seems to be the Create Mill "ticking entity" that causes the crash. How can I fix this?

https://pastebin.com/T48L6X8R

**Comment by Trrexxik** [comment]
I'd say remove the mod from the folder and then loading the world back up and then save and quitting the game and reinstalling the mod. Yes, you will lose all progress within the mod but That's the only thing I can think of.
