### ISSUE TITLE
Consider adding useful slime

### ISSUE THREAD

**Issue by Jay-TheAnxiousKiwi** [AllTheMods/ATM-6#1022]
I feel that it would be very beneficial if you add the useful slime mod to this pack, the slimeboots and slimesling are extremely useful and i have added them to my own instance, there are no conflict issues.

I have had no issues with adding usefulslime 1.1 to this pack
(ATM 6 1.5.1)

**Comment by whatthedrunk** [comment]
https://github.com/AllTheMods/ATM-6/issues/144
