### ISSUE TITLE
ATM6 Recipe for ATM Star

### ISSUE THREAD

**Issue by BlackStone5677** [AllTheMods/ATM-6#1024]
As the ATM team is working on different packs and different stuff in each pack I wanted to commit to making a recipe for the ATM star in ATM6 as I see it will be a long time till we see it. and before I finish my playthrough in the pack. I have got plenty of ideas if you were interested DM me in discord : BlackStone5677#7877

**Comment by whatthedrunk** [comment]
Currently doing a huge overhaul with these in Dev. Let us know what you think once its out.
