### ISSUE TITLE
Ice and Fire dragons with Biomes o plenty world generation type

### ISSUE THREAD

**Issue by NorthernKantoMonkey** [AllTheMods/ATM-6#1026]
I can't seem to find any dragons using the Biomes o plenty world generation option in the latest pack version, 3.1.7

**Comment by thevortex** [comment]
You won't find them regardless of world type, they are in the other dimension

**Comment by NorthernKantoMonkey** [comment]
Thanks for telling me, I did not know that

**Comment by thevortex** [comment]
No worries, re open this issue if you don't find them there
