### ISSUE TITLE
Rats incompatibility with Mystical Agriculture

### ISSUE THREAD

**Issue by Natey214** [AllTheMods/ATM-6#1027]
Rats equipped with replanter upgrade break Mystical Agriculture Plants. Rats equipped with planter upgrade do not plant Mystical Agriculture seeds

Pack Version 1.5.1

1. Go to Tamed Rat equipped with Planter or Replanter Upgrade Near Mystical Agriculture plants that are fully grown and a container with seeds
2. Using a cheese wand right click the rat to bind it to them then right click the container
3. Right Click on Tamed Rat and select harvest
4. The rat with the replanter upgrade will break the plants on harvest and the rat with the planter upgrade will pick up a seed then do nothing

There is a post on r/feedthebeast in which others have had the same issue found here: https://www.reddit.com/r/feedthebeast/comments/jquyrv/all_the_mods_6_rats_mystical_agriculture/

**Comment by whatthedrunk** [comment]
Seems like it might not happen but you can follow more here. https://github.com/Alex-the-666/Rats/issues/475
