### ISSUE TITLE
Any chunkloader machine in modpack?

### ISSUE THREAD

**Issue by GordonHollow** [AllTheMods/ATM-6#1029]
ATM6 1.5.1

Can't find any block that can chunkload some area. 
Upgrade "anchor" from Mekanism show no crafting recipe, disabled by config in modpack?
Is there any chunkload stuff except FTBChunks that don't correct load another dimensions?

**Comment by Pdiddy973** [comment]
Just about all chunk loading methods besides FTB chunks are disabled, you should be able to use it in any dimension.

The end is blacklisted by default, you can remove that in world/serverconfig/ftb chunks.toml

**Comment by GordonHollow** [comment]
Well, so it all disabled by modpack, sad(
FTBChunks little cheaty, cause you don't need to craft any expensive blocks for chunkload.
Also by default config it's to small amount of loaded chunks, just main base empty this limits)

**Comment by Blayyke** [comment]
I also agree that it seems very cheaty that you do not require anything anywhere close to mid/endgame
