### ISSUE TITLE
Sneak click with REDIA tool from Engineer's tools doesn't cycle through farmland

### ISSUE THREAD

**Issue by desucca** [AllTheMods/ATM-6#103]
All that happens when I sneak-right-click is it cycles through path and dirt, no option for farmland.

**Comment by whatthedrunk** [comment]
We are currently on 1.16.3 so removing older issues to make way for new ones. If you want to test it out join the discord for an early beta. New update will be on Twitch / Curseforge once Mekanism pushes their update to the site.
