### ISSUE TITLE
[1.5.0] Client crashes when putting an AllTheModium pickaxe or Silent Gear tool into an anvil

### ISSUE THREAD

**Issue by TheHekBech** [AllTheMods/ATM-6#1036]
Also both were water infused when it crashed.

To reproduce the bug simply put an allthemodium pickaxe into an anvil.

Crashlog: https://pastebin.pl/view/e5fa93db

**Comment by thevortex** [comment]
Are you shift clicking the item while getting this crash

**Comment by TheHekBech** [comment]
> Are you shift clicking the item while getting this crash

i tried both shift clicking and just dropping it in. Still crashes
