### ISSUE TITLE
Refined-Storage remote netwrok 🐛 

### ISSUE THREAD

**Issue by SUPERetnad01** [AllTheMods/ATM-6#1039]
if you want to create a remote network with refined storage you need a network transmitter and a network reciever. when you want to link those 2 you use a network card and click on the reciever, but if you enter the network card in the transmitter the network reciever pop's out (as an item ) where the network reciever is men to be

**Comment by nddragoon** [comment]
You probably put a controller in your remote network. a network can only have 1 controller

**Comment by Hermsmegerms** [comment]
you only need one controller on your network. the receivers can be as far away as you like, the network card goes in the transmitter back at your main network. i have around 6 groups of players on my server all using a receiver in their base to connect back to one central network.
