### ISSUE TITLE
Problems with installing modpack through twitch

### ISSUE THREAD

**Issue by TheOwl909** [AllTheMods/ATM-6#104]
I don't know if this is an issue on the modpack's side or Twitch's, but when I got to the mod's page on Curse and click the Twitch "Install" button, twitch opens but I never get taken to the modpack's page and no downloads are starting. Do we need to wait for the modpack to be placed on the Twitch launcher or is something going wrong with the link?

**Comment by GamerXD8991** [comment]
[I'M NOT A PACK DEV]

Most probably this is an issue on your side. have you tried searching the modpack in the twitch launcher? (Mods -> Minecraft -> Browse Modpacks -> Search: ATM6 -> Install)

**Comment by coffeeordeath** [comment]
Do yourself a favor and stop using twitch launcher. GDLauncher or MultiMC are much better choices. There has been tons of issues with twitch launcher and newer packs, its just not worth the headache.

**Comment by WhitePhant0m** [comment]
I recommend doing what coffeeordeath said. Twitch is really bad now days for packs and it doesn't work like 70% of the time. Use another launcher.
