### ISSUE TITLE
Pathfinding problems with rats

### ISSUE THREAD

**Issue by Juxsta** [AllTheMods/ATM-6#1042]
Server Version 1.5.1
**Describe the bug**
The rats mod is producing entity pathfinding errors. This causes the rats to be stationary or disappear, while also crashing the server every couple of hours

This happens most frequently when rats are initially tamed.

In addition, interacting with a rat while the pathfinding error is occurring will disconnect the client from the server
**Logs**
https://gist.github.com/Juxsta/eae45776f67e805a4d5bfe6abb3f540c

**Comment by Pdiddy973** [comment]
Update to 1.5.6 and see if issue persist
