### ISSUE TITLE
[1.5.2] Blaze rod duping

### ISSUE THREAD

**Issue by nddragoon** [AllTheMods/ATM-6#1043]
A mechanical squeezer produces 5 blaze powder from a blaze rod, but an enrichment chamber makes a blaze rod with just 4 powder
![image](https://user-images.githubusercontent.com/54559451/107416089-b6aa6580-6ad9-11eb-91d2-4912d953ac76.png)
![image](https://user-images.githubusercontent.com/54559451/107416104-ba3dec80-6ad9-11eb-8a41-9e65554c2b55.png)

**Comment by starforcraft** [comment]
Fixed.

**Comment by ladylexxie** [comment]
It uses power to make everything, so doesn't really count as a dupe.
