### ISSUE TITLE
Crafting machine duplication glitch

### ISSUE THREAD

**Issue by XuaTheGrate** [AllTheMods/ATM-6#1044]
ATM6 1.5.1

**Describe the bug**
A bug that allows me to infinitely duplicate items.

**To Reproduce**
- Get a Crafting Machine from Cyclic
- Fill the inner crafting square with items you want to dupe
- Sort your inventory (I used middle mouse click)

**Screenshots**
Here is a video that showcases the glitch.
https://cdn.discordapp.com/attachments/772712123121139712/808789250245394432/ArkAZsBXIm.mp4

**Additional context**
I closed and re-opened the game, the items remained so it is not a graphical glitch.

**Logs**
N/A

**Comment by leothao612** [comment]
That dupe can only do a small set at a time only. There is another dupe that can get you 1mil quantity in 20sec if any items. :)

**Comment by ladylexxie** [comment]
Not working anymore as of the latest version.
