### ISSUE TITLE
Rats causing random crash (I think)

### ISSUE THREAD

**Issue by JayseeXD** [AllTheMods/ATM-6#1045]
Pack Version. 1.5.0
A server crash seems to happen randomly with Rats. We have eliminated the rats at the location in the crashlog... but eventually happens again. Seems to be potentially unstable mod. Maybe i'm mistaken?

Repro is very hard, just progress into the mod and eventually seems to crash similarly to this.

**Logs**
https://pastebin.com/9xuikjgs

**Comment by DemandedFanatic** [comment]
The rats mod is definitely an issue. I've found that having rats with a number of different upgrades attacking mobs can cause a crash. I have yet to see an un-upgraded rat cause a crash

**Comment by Pdiddy973** [comment]
Update to 1.5.6 and see if the issue persist, rats are known to make games crash
