### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by firestorm2039** [AllTheMods/ATM-6#1046]
when i download this it becomes a RAR file?, this has not happened with ANY mods i have downloaded before? what do i do with this?, do i extract it all to the mods folder?

**Comment by lucasvanhalst** [comment]
Download the curseforge application and download it using that -> https://curseforge.overwolf.com/

**Comment by Pdiddy973** [comment]
if you need any more help feel free to ask in our [discord](https://discord.gg/K5FBPYa)

**Comment by firestorm2039** [comment]
> Download the curseforge application and download it using that -> https://curseforge.overwolf.com/

i already have forge downloaded, this is what i use all my other mods on?

> if you need any more help feel free to ask in our [discord](https://discord.gg/K5FBPYa)

i am sorry but i do not have discord
