### ISSUE TITLE
multiple bee breading not shown in JEI

### ISSUE THREAD

**Issue by Hermsmegerms** [AllTheMods/ATM-6#1049]
go in ATM version 1.5.1 and look up unobtanium bee
There is no breeding tab for unobtanium, vibrainium, althemodium, refined obsidian, and osmium bees

Expected behavior
show how to bread the unobtanium bee

Screenshot:
Hard to show the lack of a breeding tab, but most bees have a breeding tab these few do not.

**Comment by RodrigDuarte** [comment]
I noticed that if you go to a creative world you can see the recipes just fine, and it made them come back even when I went to play on my server with my friends.

**Comment by Pdiddy973** [comment]
check all the bees listed in a new install of 1.5.1, and all show correctly. it may be an issue with your config files.

**Comment by iarspider** [comment]
It happens to me from time to time. It only happens though when I play on a server.

**Comment by Hermsmegerms** [comment]
yeah this is still not working. going back and fourth between single player and server, creative and survival. the breeding page appears in survival but is blank. the configs are completely un edited on my end.
