### ISSUE TITLE
Mod suggestion: Inventory Sorter - 1.16.2 compatible!

### ISSUE THREAD

**Issue by IanMoroney** [AllTheMods/ATM-6#105]
I noticed there doesn't seem to be a usual way to sort the inventory (usually middle mouse click, or R key) so I thought i'd suggest one.

https://www.curseforge.com/minecraft/mc-mods/inventory-sorting
1.16.2 compatible!

**Comment by WhitePhant0m** [comment]
1. 
![image](https://user-images.githubusercontent.com/33400200/91916508-003e8b00-ecc6-11ea-94c7-613b7e0f9fd8.png)
2. Suggestions go in here #1 
3. We do have an inventory sorting mod, check the keybinds.
