### ISSUE TITLE
About AE2 Meteorites

### ISSUE THREAD

**Issue by KurooNekomata** [AllTheMods/ATM-6#1050]
I'm playing in the defaut world in the latest version of the modpack (1.5.1) and I'm not founding any meteorites from ae2, not even on mining dimension, are they supose to spawn or I have to do the mystical agriculture recipe?

**Comment by NetMasterFlex** [comment]
To my knowledge the meteors only spawn in the overworld. Have you crafted a compass to see if it points you in a direction. The compass usually leads you to the nearest meteor.

**Comment by KurooNekomata** [comment]
yes, I already crafted the compass, it's only rotating slowly (meaning there's no meteor close) no matter how far I go, I even tryed "/rtp" and the compass still found nothing

**Comment by whatthedrunk** [comment]
I am seeing them fine. Are you suing default world gen or did you add or change anything?

**Comment by KurooNekomata** [comment]
I didnt change anything on the world gen neither in any mod options

**Comment by whatthedrunk** [comment]
I can't seem to replicate the issue. Try 1.5.2 that just came out and you might have better luck.

**Comment by KurooNekomata** [comment]
Ok, thank u
