### ISSUE TITLE
One specific person times out when joining 

### ISSUE THREAD

**Issue by Patrikk22** [AllTheMods/ATM-6#1051]
I am hosting an ATM6 (1.5.1) server, and 3 of us can connect without any issues, but one friend gets stuck on the encrypting screen and then proceeds to time out when connecting. Various other mod packs we have played have not had this issue and i don't know why this issue is occurring with this specific mod pack.

**Comment by whatthedrunk** [comment]
Have them add this to java to see if it helps. It helped one of our admins that had the issue. If that does not work we might need to see a log. 
`-d64 -server -XX:+AggressiveOpts -XX:ParallelGCThreads=3 -XX:+UseConcMarkSweepGC -XX:+UnlockExperimentalVMOptions -XX:+UseParNewGC -XX:+ExplicitGCInvokesConcurrent -XX:MaxGCPauseMillis=10 -XX:GCPauseIntervalMillis=50 -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:NewSize=84m -XX:+UseAdaptiveGCBoundary -XX:NewRatio=3 -Dfml.readTimeout=90 -Ddeployment.trace=true -Ddeployment.log=true -Ddeployment.trace.level=all`
