### ISSUE TITLE
Indestructible items take durability outside of player inventory

### ISSUE THREAD

**Issue by DaveJK** [AllTheMods/ATM-6#1052]
Version 1.5.0-1.5.1

I recently updated to 1.5.1 from 1.4.1 and it seems items that have the Indestructible enchant now take durability damage when not inside a players inventory. For example my Garden Scythe inside of a Cyclic Item-User. It will repair the damage taken when transferred to the player's inventory.

https://gfycat.com/spryoffensiveantlion

**Comment by DaveJK** [comment]
I've been trying an assortment of items and it seems maybe it's just Cyclic items that are the issue?

**Comment by Pdiddy973** [comment]
Update to 1.5.6 and see if issue persist
