### ISSUE TITLE
Can't create or enter world

### ISSUE THREAD

**Issue by V4kodin** [AllTheMods/ATM-6#1054]
I used 1.5.1 version. I try to play this modpack, but It was so much lagging and unstable, so I trying to change it. I read about all mods and delete useless for me (optimization) but world can't be created for some reasons, game just freeze when I try to create world or enter vanilla world. I can't understand why game did't work because the game does not crash (crash report can't be created) so the question is "What problem it can be?". I know, I moded modpack and it's not ATMTeam problem, but i haven't any idea about solution. I already tried to turn off some modes like "All The Tweaks", no result.

**Comment by whatthedrunk** [comment]
What might be easier for you is to start with our lite pack and slowly add mods till it's how you want it. https://www.curseforge.com/minecraft/modpacks/all-the-mods-slice-of-pi2-atm-slop2
