### ISSUE TITLE
Can someone please help me?

### ISSUE THREAD

**Issue by Furious1964** [AllTheMods/ATM-6#1056]
I have been running this Mod Pack for several weeks now and the game day resets itself back to Day 1 every time I sleep. I don't know why or what's causing this. Can anyone please take a look at the log and tell me what the cause is?
[latest.log](https://github.com/AllTheMods/ATM-6/files/5962642/latest.log)

**Comment by Pdiddy973** [comment]
Update to 1.5.6 and see if issue persist

**Comment by Furious1964** [comment]
Thanks, but spoken to the mod author and he thanked me for finding that problem which he fixed right away. All's working now.
