### ISSUE TITLE
Environmentaltech - Assembler Bug

### ISSUE THREAD

**Issue by krabbbbe** [AllTheMods/ATM-6#1057]
V:1.5.1
The Assembler and Items needed for Crafting it are bugy in unse with 
refined Storage, and by themselves.

1.Use refined Storage System to Build Assembler
2. Craft the items needed for the Assembler
3. have them in the System and Click/SHift Click on the Cross 
to auto fill the Crafting Grid
4. See only some of the Items appear in the crafting fiel, others need to be draged in

1. Usage of Assembler
2. Place it and power it
3. Start crafting Process for somethin e.g. litherite stuff
4. after first recepie no others will be crafted, if the Assembler isn't replaced again

**Comment by Adam-North** [comment]
this is an environmentaltech bug that was just fixed in the recent update.

**Comment by Pdiddy973** [comment]
This is semi resolved with 
https://github.com/AllTheMods/ATM-6/pull/1037
Keeping it possible to craft w/o assemblers untill they seem to work better
