### ISSUE TITLE
I cannot open chests.  The chest block opens like normal animation, but I cannot access inside.  Same with furnaces.  I'm playing on server, and my friend, who owns the server can do all these things.  

### ISSUE THREAD

**Issue by NoWonderland** [AllTheMods/ATM-6#1060]
**Describe the bug**

**To Reproduce**

**Screenshots**

**Additional context**

**Logs**
Please use a paste site for logs, instead of putting the file directly in the issue, not only is this easier but also means we can view on mobile when we are not at our computers.
Here's a list of some paste sites and their size limits:
    https://pastebin.com/ 512KB
    https://hastebin.com/ 400KB
    https://gist.github.com/ 100MB Requires member (Free)

**Comment by whatthedrunk** [comment]
Make sure you are not at spawn. Also make sure the Chuck is not claimed.

**Comment by NoWonderland** [comment]
I was not at spawn, I know that for sure. I am familiar with the space near
spawn not being like the rest of the world. As for the chunk thing, I don’t
think that was the issue because we started traveling and no matter how far
we went, I still couldn’t do those things. I am able to access a crafting
bench, a smoker, and a blasting furnace however. Also, another bug I ran
into, was that my Baubles button, the on by my characters head in the
inventory screen, does nothing. It’s there, but when I press it nothing
happens. Unlike my friend, where he can access the extra inventory where
Baubles are equipped, when he presses that button.

Also, why did you close this?  This has not been fixed.

**Comment by whatthedrunk** [comment]
We close issues after we respond if the form was filled out incorrectly. We need to know versions and we need logs or something to go on because we cannot replicate it.

**Comment by NoWonderland** [comment]
It’s on Minecraft 1.16.5 and ATM6 1.5.2. And I just learned another friend
who just started on the server is able to access chests and furnaces.

As for the logs, I can get them to you on Sunday or Monday if you still
need them. I apologize for my ignorance on this subject, just wanting to
get this fixed.
