### ISSUE TITLE
I dont Have the end in my server...pack ver 1.5.2

### ISSUE THREAD

**Issue by MrRamGoat** [AllTheMods/ATM-6#1063]
![image](https://user-images.githubusercontent.com/78942550/107722226-217cbc00-6ce7-11eb-8472-b232af88d850.png)
![image](https://user-images.githubusercontent.com/78942550/107722242-29d4f700-6ce7-11eb-8fc8-6e51fcc116f4.png)
i have been searching for the end in creative with eye of ender but i dont seems to find it and i tried to do /locate and its says that it doesnt exist so if someone can help me with that. that would be lovely
thank in advance

**Comment by Cntrldfusion** [comment]
I think in ATM6 the Minecraft structures have been replaced with Repurposed Structures.   Try using "/locate repurposed_structures:stronghold_stonebrick" instead of "/locate stronghold".

**Comment by MrRamGoat** [comment]
> I think in ATM6 the Minecraft structures have been replaced with Repurposed Structures. Try using "/locate repurposed_structures:stronghold_stonebrick" instead of "/locate stronghold".

thank man it really helped i found the end finally
