### ISSUE TITLE
Engineer's Decor : Metal Craftng Table

### ISSUE THREAD

**Issue by Tupilak** [AllTheMods/ATM-6#1066]
Item dube in multiplayer, with the Metal Craftng Table from Engineer's Decor

1. Put in meterial for recipie
2. Have a other player looking in it as well as you.
3. Have the other player pull out the item
4. The item in the crafting grid is used, but you can still pull out the same item. now both you and the other player have the item.

This in ATM6 v1.5.2 on MC 1.16.5

**Comment by ladylexxie** [comment]
No longer happening.
