### ISSUE TITLE
[Crash, 1.5.1] Putting a specific item into anvil causes crash

### ISSUE THREAD

**Issue by iarspider** [AllTheMods/ATM-6#1067]
**Describe the bug**
Client crashed when I tried to put a diamond "extra-enchantable" (i.e. with Apotheosis suffix) pickaxe

**To Reproduce**

Not sure what exactly led to a crash, so a bit long-ish process:

1. Get a pickaxe from Apotheosis named mob
2. Disenchant using Corail Tombstones
3. Enchant with Fortune I using water infusion from Elemental Craft
4. Disenchant once more using Corail Tombstones
5. Try putting (clicking or shift-clicking) into Anvil
6. Crash

**Logs**
https://gist.github.com/iarspider/08fc3d6e6d2bd9e49290c63ae5d15b58

**Comment by iarspider** [comment]
After several attempts to enchant the pickaxe, it somehow got voided...

**Comment by Sirttas** [comment]
Does it happen in the latest version (1.5.2) as it may be caused by performant (removed in 1.5.2)

**Comment by iarspider** [comment]
Yup, doesn't happen in 1.5.2 (or maybe I got lucky). Closing for now.
