### ISSUE TITLE
[1.5.2] Opening Botania book in akashic tome BREAKS SAVE

### ISSUE THREAD

**Issue by Prob1ematic** [AllTheMods/ATM-6#1069]
**Describe the bug**
Version: 1.5.2
I chose to open upgraded Botania book in akashic tome, it crashed with message: 

The game crashed whilst unexpected error
Error: java.lang.ClassCastException: net.minecraft.nbt.StringNBT cannot be cast to net.minecraft.nbt.CompoundNBT
Error code: -1

And now save is broken and cant even open it. It crashes when it finishes loading world. I even tried deleting player data folder from save, any help **how i can recover my save?**

**To Reproduce**
1. Have akashic tome with all books in game
2. Open astral sorcery book in tome
3. Close it
4. Open upgraded botania book in tome
5. Get broken save

**Logs**
https://pastebin.com/Ei3xUk9P

**Comment by DaveJK** [comment]
If this helps the devs.

Akashic tomes changed the way it handles NBT tags in 1.4-16 of the mod. Deleting your old Akashic tome and making a new one seems to help.

**Comment by Prob1ematic** [comment]
Fixed my save by removing tome from mods folder. Doesn't change that bug still exists.
