### ISSUE TITLE
Ice and Fire Dragons not spawning in the other pack version 1.5.1

### ISSUE THREAD

**Issue by FattyTuTu** [AllTheMods/ATM-6#1070]
Buddy and I have searched probably 10k x 10k area in the other and have not seen a single spawn of the dragons.

**Comment by thevortex** [comment]
issue was resolved in 1.5.2

**Comment by FattyTuTu** [comment]
I know you answered my question yesterday about them not spawning, we have them spawning now however it is only fire dragons. Is there somewhere in the config files to fix this so the other types will spawn in different biomes in the other?

Many thanks
