### ISSUE TITLE
The buttons in the main menu- 1.5.2

### ISSUE THREAD

**Issue by BlackStone5677** [AllTheMods/ATM-6#1071]
**Describe the bug**
If you tab on the main menu, the order that the buttons go in is: Quit Game>Reddit>Singleplayer>Nothing>Make A Server>Discord>Github>Mods>Multiplayer>Options>Patreon

**Expected behavior**
It should have the order : Singleplayer>Multiplayer>Patreon>Make A Server>Reddit>Discord>Mods>Github>Options>Quit Game

**To Reproduce**
1. Go to the main menu
2. Press on the tab key
3. You'll see the order
 
**Additional Context**
I think this might be a KubeJS issue but not sure if it's KubeJS that does the custom main menu or the custom main menu mod so I just put it here.

**Comment by ladylexxie** [comment]
This is not something we control, it's being added by PackMenu
