### ISSUE TITLE
Is Rose Quartz (Create) Impossible to craft or am I doing something wrong?

### ISSUE THREAD

**Issue by CrabLad** [AllTheMods/ATM-6#1073]
I'm using the 1.5.2 pack version.
The Create mod by itself lets you craft Rose quartz using 1 quartz and 8 redstone. However in the mod pack the recipe seems to be non existent, JEI doesn't say anything about crafting it. 
Whether I can find Rose Quartz or this is a bug is very unclear. Please help if possible. thank you.

**Comment by DaveJK** [comment]
It's definitely in 1.5.2 of the pack. Try reinstalling.
![javaw_79sFXzOSVW](https://user-images.githubusercontent.com/24943733/107887803-7f62fc80-6ebd-11eb-97ea-d57595d717d1.png)
