### ISSUE TITLE
[1.5.2] Random crash while moving around

### ISSUE THREAD

**Issue by Prob1ematic** [AllTheMods/ATM-6#1074]
**Describe the bug**
Version: 1.5.2
The game crashed whilst batching chunks
Error: java.util.ConcurrentModificationException: null

**To Reproduce**
Just play the game for a while and fly around.

**Logs**
https://pastebin.com/8LJzvNj6

**Comment by NoMoreStars** [comment]
I've been having a similar issue, but I had begun to assume that it was my installation of Optifine causing the problem. [Here's the issue I reported on the Optifine Github.](https://github.com/sp614x/optifine/issues/5318) However, if we're both having the same problem, then it may be something else within ATM6 causing the crash.
