### ISSUE TITLE
Ice and Fire dragons 1.5.2

### ISSUE THREAD

**Issue by FattyTuTu** [AllTheMods/ATM-6#1077]
Yesterday we updated to 1.5.2 to fix the ice and fire dragons not spawning in the other. The dragons seem to only spawn around 10k blocks out from spawn. Is there a way to have their structures spawn closer to player spawn in "the other"?

Thanks!

**Comment by jeremymarabel** [comment]
yesterday i've fixed that locally by deleting The Other (in the world/allthemods/ folder) to regenerate it. 
Keep in mind that it will reset the dimention, so if you've already built something in it i would not recommend it

**Comment by FattyTuTu** [comment]
Thank you I have done that and also did the fix that the ice a fire page recommended and deleted the biomes config for it and let it recompile. It seems like the world spawns are static though. I have deleted the old "the other" and i went to the markers where i found the old dragons and the same dragons and same caves are around it. Maybe I have to reset our whole world?

**Comment by thevortex** [comment]
If you followed their instructions you will have dragons on the overworld

**Comment by FattyTuTu** [comment]
Oh no. I could rerun the server files and get the proper config file for it.

**Comment by FattyTuTu** [comment]
I reset with the proper configs. and it still seems like the dragon spawn areas are static. I assume this is just based off the seed then.

**Comment by thevortex** [comment]
The spawn locations are biome level, not any specific coords, fire - basalt
deltas, ice - mountains and mountain edge , lightning in desert and desert
hills,

**Comment by FattyTuTu** [comment]
one last thing. is there a wat to change the biome weights to have them potentially spawn more frequently?

thanks for all the help!

**Comment by thevortex** [comment]
you can try editing the iceandfire-common.toml config file

**Comment by DesktopGamer** [comment]
In the config, should it be a whitelisted or blacklisted dimension. it currently says blacklisted in the OTHER config for ice and fire

**Comment by Knale44** [comment]
Same here... i can't find any Dragons or Dragons Nest. I just find Pixies and Cockatrices

**Comment by DesktopGamer** [comment]
I think the Other dimension should be labeled as whitelisted instead of blacklisted but, I'll do some testing

**Comment by Knale44** [comment]
I don't think this is the problem, beacause other mobs are spawning correctly. I create a new save with the original configs from Ice and Fire, the blacklisted dimension is the Overworld, and the Dragons are spawning correctly. Maybe some conflit with other configs of the Allthemod dimension

**Comment by thevortex** [comment]
Incorrect
