### ISSUE TITLE
Unable to connect to LAN server.

### ISSUE THREAD

**Issue by derpendary** [AllTheMods/ATM-6#1078]
(Pack version: 1.5.1+1.5.2)
"Failed to synchronize registry data with server, closing connection" message when playing LAN server

**To Reproduce**
1. User 1 opens world and opens to lan, gives port number to user 2
2. User 2 puts user 1 IP:port number into direct connect
3. User 2 attempts to connect

**Screenshots**
Screenshots unnecessary 

**Additional context**
Using Curseforge 2/15/2021

**Logs**
Unable to provide logs. Currently redownloading latest version to new profile. Assume issue still persists and give instructions on how to acquire logs for this particular issue if I do not add an addendum stating I solved the current issue.

Thank you.

**Comment by Sirttas** [comment]
As far as I remember open to lan has been often broken in modded. Try using a dedicated server.

**Comment by derpendary** [comment]
> 
> 
> As far as I remember open to lan has been often broken in modded. Try using a dedicated server.

I don't have the money for a dedicated server, and this is the only pack I know of that has had LAN issues.

**Comment by Sirttas** [comment]
You can run a dedicated server on your computer...

**Comment by derpendary** [comment]
> 
> 
> You can run a dedicated server on your computer...

How?

**Comment by Sirttas** [comment]
Just run it on your computer it's not hard at all.

**Comment by Kyric** [comment]
Me and my friend have the same problem after update the mod pack. You will need to go into the save and remove the block reference that is removed on the latest update. 

I use MultiMC and the fail log on connection it show the block reference that is not matching. If you follow:
https://forums.minecraftforge.net/topic/42114-command-to-clean-fmlregistry-entries-of-deinstalled-mods/
to use a NBTExplorer to remove them that show make it work again. 

For reference the follow block was removed causing the error from 1.5.1 to 1.5.2 is the following:
	resourcefulbees:bismuth_honeycomb_block: 7305
	resourcefulbees:bronze_honeycomb_block: 7284
	resourcefulbees:crystal_honeycomb_block: 7281
	resourcefulbees:electrum_honeycomb_block: 7286
	resourcefulbees:invar_honeycomb_block: 7288
	resourcefulbees:oratchalcum_honeycomb_block: 7307
	resourcefulbees:refined_glowstone_honeycomb_block: 7295
	resourcefulbees:refined_obsidian_honeycomb_block: 7296
	resourcefulbees:steel_honeycomb_block: 7298
remove them from minecraft:block should be working again. Again if it is other modpack or version you will need to refer to the MultiMC log to check which block causing the "Failed to synchronize registry data with server" issue. Hope this help
