### ISSUE TITLE
[1.5.2] Morphtool corrupts player data

### ISSUE THREAD

**Issue by zemos** [AllTheMods/ATM-6#1081]
**Describe the bug**
Client crashes when logging with morphtool in hand. Removing it from inventory fixed player data. 

**To Reproduce**
I get this error every time I try to login to server. 

**Logs**
https://pastebin.com/N05GQ2zH

**Comment by DaveJK** [comment]
Was it an old Morph-o-tool from a previous update? If it is try crafting a new one and see if it works.

**Comment by zemos** [comment]
I created it in 1.4.1 and added some tools in 1.5.1. It was then when it was last used. 
Will try the new one later today.

**Comment by zemos** [comment]
The newly created one seems to be working.
