### ISSUE TITLE
[1.5.2] Flesh block is not a valid apiary block

### ISSUE THREAD

**Issue by zemos** [AllTheMods/ATM-6#1082]
In the new update, Zombee needs flesh block but it is not a valid apiary block.

Living wood (and some of it's variations) is also not a valid. Same goes for living stone blocks (and it's variants). Can you make them valid?

**Comment by Pdiddy973** [comment]
fixed in #1072 , any reason why we should add the living rock/stone?

**Comment by zemos** [comment]
Sorry, I didn't see that.  The reason is only aesthetical. I really like them and thought that those blocks were skipped because living wood stairs are valid block.

**Comment by Pdiddy973** [comment]
Anything with the Minecraft:stair/slab tag is added, so it would make sense those were added

**Comment by zemos** [comment]
kk. Is it ok for me to add living wood/stone to the config and make PR? Feel free to close this.

**Comment by Pdiddy973** [comment]
I will add when I get time
