### ISSUE TITLE
ATM6 Mining Dimension & The Other Dimension not loading/available after update.

### ISSUE THREAD

**Issue by Kithid** [AllTheMods/ATM-6#1083]
So we just updated the pack to 1.5.2 from 1.4.1 (I think, possibly 1.4.0) and the update seemed to go fine, but after everything loaded back up again, we could no longer access the mining dimension or the "The Other" from the nether. We can't even use Waystones to teleport back into those dimensions. Everything else seems to work fine. I can for example go to Ratlantis without issue.

Have anyone else had the same issue after an update, and/or could someone suggest a possible fix to this problem in that case?

**Comment by Pdiddy973** [comment]
You need to stop the server/game after the first run of the update and once you load it again it will work.
