### ISSUE TITLE
Server appear offline

### ISSUE THREAD

**Issue by jeremymarabel** [AllTheMods/ATM-6#1086]
**Describe the bug**
The server can be join without issues, but is appearing offline in the server list. When someone hit refresh or connect, i can see this error in the console :
`[Netty Epoll Server IO #1/ERROR] [net.minecraft.network.NettyPacketEncoder/]: io.netty.handler.codec.EncoderException: String too big (was 36195 bytes encoded, max 32767)`

I think it's since the 1.5.2 update, because it worked before that. But i'm not 100% sure

**Comment by jeremiahwinsley** [comment]
Delete `world/icon.png` to fix this.

This is a known issue with worlds that were started in single player. The client creates icons that are larger than the server can use.
