### ISSUE TITLE
Player takes lava and fire damage in creative

### ISSUE THREAD

**Issue by hotdog95** [AllTheMods/ATM-6#109]
When in creative mode, the player will take lava and fire damage and die as if in survival mode. I don't believe this is ATM6 but some other mod doing this, but I do not know which one

**Comment by hotdog95** [comment]
Just testing again, this only happens for the first death, after this, the player properly enters creative mode and can no longer take damage, I believe the player is also targeted and attacked my mobs.

The world was quark-realistic

**Comment by WhitePhant0m** [comment]
![image](https://user-images.githubusercontent.com/33400200/93109768-21877a00-f6bd-11ea-9598-9661420ed3c6.png)
was an issue with MA Essentials, it's now fixed, fix will be included in the next pack update.
