### ISSUE TITLE
crazy OP duping in ATM6 1.5.2

### ISSUE THREAD

**Issue by BigGavvy** [AllTheMods/ATM-6#1092]
My first time on this site but i started modded MC last week and got hooked on ATM3 Lite, i liked it tht much i have installed ATM6 version 1.5.2 and been playing it for last few days. i found a duping method i think needs fixed as it ruins this mod pack.

how to dupe:
Get any Dank along with any Backpack, 
Place any items u want to dupe inside the Backpack (bigger the backpack the more items tht can be duped at one run)
Place ur filled Backpack into the Dank and put the Dank into construction mode and select the Backpack and open it,
Now its open just pull out the items u want Duped or Dump it all on floor to Dupe it all,
Close the backpack and open it again with ther dank all items still there and all items on the floor!

**Logs**
Please use a paste site for logs, instead of putting the file directly in the issue, not only is this easier but also means we can view on mobile when we are not at our computers.
Here's a list of some paste sites and their size limits:
    https://pastebin.com/ 512KB
    https://hastebin.com/ 400KB
    https://gist.github.com/ 100MB Requires member (Free)

**Comment by sprocketaudio** [comment]
Thias is still a problem and caused an issue on my server. I am banning backpacks.

**Comment by starforcraft** [comment]
Fixed in next Version.

**Comment by Ki-Tan2934** [comment]
Not fixed, this requires dank to patch, nothing we can do
