### ISSUE TITLE
Wrong recipe for Sulfur seeds

### ISSUE THREAD

**Issue by FoorFoxAnco** [AllTheMods/ATM-6#1095]
**Describe the bug**
Wrong recipe for Sulfur seeds.

**To Reproduce**
1. Go to JEI search for Sulfur seeds
2. Click on Sulfur seeds
3. Choose Infusin crafting as a methode of crafting.
4. See wrong recipe

**Screenshots**
![image](https://user-images.githubusercontent.com/36706652/108549307-42e43600-72ed-11eb-8d05-0dea2778ae71.png)

**Comment by Pdiddy973** [comment]
It's an issue with JEI, just put sulfur in the 4 blank corners.
