### ISSUE TITLE
pc requirment question

### ISSUE THREAD

**Issue by NyQuilD** [AllTheMods/ATM-6#1096]
just was wondering what would the pc requirment be to run this I am running amd ryzen 2700x 16 gigs ddr4 ram and gforce 1650 supper and the game lags quite a bit in the forest areas

**Comment by Lvaughan263** [comment]
it all depends on  how much ram is actually allocated to minecraft. i have 17 3770k, r7260x, and 16 gigs ddr3 1600, and it's running fine. i believe it originally allows minecraft 2 gigs, which is nowhere close to what it needs. i allocated 15G to mine, and it runs just fine. find how to allocate ram to minecraft

**Comment by NyQuilD** [comment]
> it all depends on how much ram is actually allocated to minecraft. i have 17 3770k, r7260x, and 16 gigs ddr3 1600, and it's running fine. i believe it originally allows minecraft 2 gigs, which is nowhere close to what it needs. i allocated 15G to mine, and it runs just fine. find how to allocate ram to minecraft

ty I allocated more memory and itt did not lag at all tyvm
