### ISSUE TITLE
Clashing Recipe.

### ISSUE THREAD

**Issue by JustLiam040** [AllTheMods/ATM-6#11]
Thought id chuck this here in the hopes it would help get the recipe tweaked. 

I am currently running the latest version of ATM6(0.15b), as you can see in the screenshots provided the vanilla minecraft chain and the forbidden arcanus chain both have the same recipe, attempting to craft the VM chain is impossible as there is no recipe switcher implemented in the pack. In order to fix this issue a recipe switcher would have to be implemented, or a new script would have to be created in order to alter one of the recipes.

This is not a major issue, but thought it best to report it here.

![Arcanus Chain](https://user-images.githubusercontent.com/33065753/87854794-2ffb2480-c90c-11ea-9b2f-786fba2bc868.PNG)
![minecraft chain](https://user-images.githubusercontent.com/33065753/87854796-31c4e800-c90c-11ea-894a-3024b794e0df.PNG)

**Comment by AleksiMK** [comment]
For now you could use this
![7114abd2a276d82e70b842b6953ef057](https://user-images.githubusercontent.com/33400200/87861026-fa296080-c94a-11ea-8419-4eaae06f54da.png)
It allows switching through conflicting recipes

**Comment by whatthedrunk** [comment]
Thanks this will be the recipe in tonights update. 
![image](https://user-images.githubusercontent.com/8105116/87971383-3d8ee680-ca93-11ea-937b-2f43725fafa0.png)
