### ISSUE TITLE
FTB chunk loader

### ISSUE THREAD

**Issue by Simme87** [AllTheMods/ATM-6#110]
I have a problem with the keybinding of the FTB chunkloader.
This is placed in the modpack on the letter "u".

But now I can't write on signs or something similar in which the letter "U" occurs. Because the FTB Chunkloader Map opens immediately.

Excuse my English, I used the google translater.

> Original Message in German
> Ich habe ein Problem mit dem Keybinding vom FTB Chunkloader.
> Dieser ist im Modpack auf dem Buchstarben "u" gelegt. 
> 
> Nun kann ich aber keine Schilder oder ähnliches beschrieften in dem der Buchstarbe "U" auftritt. Da denn sofort die FTB Chunkloader Map aufgeht.
> 
> Endschuldigen Sie mein Englisch, ich habe den Google Translater benutzt.
>

**Comment by WhitePhant0m** [comment]
![image](https://user-images.githubusercontent.com/33400200/92304342-cd2a1f00-ef85-11ea-8b65-1c06c47ef41b.png)
Look for this ^ and change it to something else, like a number on the numpad.
