### ISSUE TITLE
Elemental Craft+ ironfurnaces pure ore conflict vers.1.5.2

### ISSUE THREAD

**Issue by kdrag3** [AllTheMods/ATM-6#1105]
The bug i'm having atm is the interaction with pure ore's and netherite furnace i got multiple pure ore from elementcraft iron/copper/gold/etc.I put all my pure ore in a barrel then pulling into the netherite furnace  then all the ore just became iron ingot cause the pure iron when in 1st and not giving me the other ore that was in too only had 2 stack of pure ore iron came out with 9 stack of iron ingot which the other stack became iron ingot's.Now i'm think not using elementcraft at all cause of that bug.I'm trying to automation processes my ore trough elementcraft/mekanisam almost setup now scare that will only give 1 type ingot Ps. sorry no picture

**Comment by kdrag3** [comment]
i got a clip showing the bug


https://user-images.githubusercontent.com/79380768/108608852-c6f2f800-7397-11eb-8f41-bb11b505b7c7.mp4


https://user-images.githubusercontent.com/79380768/108608856-c9ede880-7397-11eb-9430-a95f4cf8acc7.mp4

**Comment by kdrag3** [comment]
https://user-images.githubusercontent.com/79380768/108608888-03265880-7398-11eb-983e-015bf2179275.mp4

**Comment by kdrag3** [comment]
that was a recreation what happen.

**Comment by Sirttas** [comment]
Please put some ponctuation in your text it's unreadable.

**Comment by whatthedrunk** [comment]
I just recreated the setup and it seems to work as expected now.
