### ISSUE TITLE
the game stops responding right before fully loading

### ISSUE THREAD

**Issue by Draeconix** [AllTheMods/ATM-6#1110]
the game completely stops responding when it gets to the phase of all mods loaded, and you have to wait for like a solid 2-3 minutes before it fully loads and you can play

i also cannot join servers at all because its either "forcibly closed" or it says it "timed out"

**Comment by Draeconix** [comment]
the not responding happens for a few seconds while "encrypting" a server to join

**Comment by Pdiddy973** [comment]
The loading is normal, for the server make sure it has space and you have the right IP
