### ISSUE TITLE
[1.5.2] Add "valid_apiary" tag to more glass types

### ISSUE THREAD

**Issue by stupex** [AllTheMods/ATM-6#1111]
ATM6 1.5.2

Resourceful bees only accepts vanilla glass types and some modded glass types. It would be nice to be able to use more glass types like the _Botania Managlass_, _Engineer's Decor Panzer Glass Block_, and especially the _Glassential Ethereal Glass_.

_Ethereal Glass_ would be the most useful for making changes to the apiary flower blocks. No need to to use doors or breaking blocks.

**Comment by DaveJK** [comment]
Like this? 
![javaw_5JYeDebn2O](https://user-images.githubusercontent.com/24943733/108649518-5a98f700-7472-11eb-94d9-0b875d803bb0.png)
![javaw_3JTPe4HoZn](https://user-images.githubusercontent.com/24943733/108649523-5cfb5100-7472-11eb-9c3a-95a132ae8bd4.png)

**Comment by Pdiddy973** [comment]
a lot of those that you mentioned are already added as @DaveJK showed, please make sure the ones you want added dont already have the tag, you can see what we added at:
https://github.com/AllTheMods/ATM-6/blob/master/kubejs/server_scripts/tags.js
starting at line 189

**Comment by stupex** [comment]
My bad I looked up _$valid_apiary_ in JEI and didn't see them on the list. I just tested it now on an apiary and they do work. Apologies for not trying all of it before posting.
