### ISSUE TITLE
Spooky Bee Not Harvesting Bone Block 1.5.2 (1.16.5)

### ISSUE THREAD

**Issue by nonconceptual** [AllTheMods/ATM-6#1112]
### 1.5.2: Spooky Bee Not Harvesting Bone Block
Spooky bee is flying around not harvesting from bone block within T4 apiary. As a result it is not producing honeycomb blocks. Observed this working previously.

**To Reproduce**
1. Catch a spooky bee
2. Construct apiary with Bone Block
3. Import spooky bee to apiary
4. Observe spooky bee flies around without harvesting bone block

**Screenshots**
N/A, just an apiary

**Additional context**
This was working at some point as I had spooky honeycomb blocks in my crafting grid.
I have tried picking up and re-placing the spooky bees (notice that the bee-jar names were updating, thought maybe that would refresh it). I have also tried picking up and re-placing the bone block.

**Logs**
No stack traces, sorry :/

**Comment by Pdiddy973** [comment]
fixed in #1072
