### ISSUE TITLE
@refinedstorage `interface` does not export to `Ultimate.*` @mekanism machines

### ISSUE THREAD

**Issue by Shantarr** [AllTheMods/ATM-6#1113]
Minecraft 1.16.6
ATM6 - 1.5.2
**Describe the bug**
@refinedstorage `interface` does not export to `Ultimate.*` **mekanism** machines
Base versions of the same machines work as expected

**To Reproduce**
1. Place **mekanism** `Ultimate Smelting Factory`
2. Correctly attach **refinedstorage** `interface` to the **mekanism** `Ultimate Smelting Factory`
3. Provide power to **mekanism** `Ultimate Smelting Factory`
4. Set correct Input/Output on **mekanism** `Ultimate Smelting Factory`
5. Enter Crimson Iron Ore into **refinedstorage** `Interface` on Export filter side
6. Observe issue in **mekanism** `Ultimate Smelting Factory` not accepting items

**Screenshots**
Available upon request

**Additional context**
In Mining Dimension, have not tested overworld

**Logs**
Available upon request

Edited: 
- Added "Smelting" to above text, where seen in the example to re-produce. 
- Removed @'s from names of mods, initially done so to emulate looking up the mod within JEI in game, apologies for pings; I am new to GitHub and did not know any better.

**Comment by djnugets** [comment]
the interface does not import/export on its own you need something else to pull from it

**Comment by Shantarr** [comment]
@djnugets Understood, it is hooked up to a complete refined storage grid. Importers and exporters work expected in this setup, however, the interface block does not on the Ultimate versions of the @mekanism machines.

Please let me know if you require any additional information or would like me to try anything to troubleshoot more.

**Comment by Pdiddy973** [comment]
not really how interfaces work, not really an issue

**Comment by Shantarr** [comment]
@Pdiddy973 

Interesting, works that way for every other machine.

Thanks for taking a look.
