### ISSUE TITLE
Banned Ender Hopper

### ISSUE THREAD

**Issue by Ankit17430** [AllTheMods/ATM-6#1114]
Version: All the Mods 6 - ATM6 - 1.16.5

Is there any replacement to the Ender hopper? I need a item that will transfer dropped items into a chest.
If I unban and use Ender Hopper, is their major crash or lag issues?

**Comment by Pdiddy973** [comment]
ender hopper was removed because it can cause alot of lag, several alternatives are item collector, modular routers, hopper hock, and several others ic ant think of right now. feel free to ask in our discord
