### ISSUE TITLE
Block distance counter. Pack Version: 1.5.2 (latest)

### ISSUE THREAD

**Issue by Ultraghoul213** [AllTheMods/ATM-6#1118]
Hi, 

I've just downloaded ATM 6 1.5.2 and I was wondering if it was possible to disable/remove the block distance counter, I find it to distracting to play with and can't seem to find which mod it is from.

I have added my own few mods (such as optifine, projecte, worldedit+" "CUI and industrial agriculture. I also removed chisel and bits from my mod list. 

Any help will be greatly appreciated.

**Comment by jeremiahwinsley** [comment]
The default install doesn't have a block distance counter, it's most likely from one of the mods you added.
