### ISSUE TITLE
Minecraft Crashing

### ISSUE THREAD

**Issue by dodo2608** [AllTheMods/ATM-6#112]
[hs_err_pid15300.log](https://github.com/AllTheMods/ATM-6/files/5178265/hs_err_pid15300.log)

**Comment by MrBackups** [comment]
I'm seeing this same error when trying to break oak vertical slabs.  I was able to go into creative and break them fine, but there appears to be an issue with breaking vertical slabs.

**Comment by whatthedrunk** [comment]
We are currently on 1.16.3 so removing older issues to make way for new ones. If you want to test it out join the discord for an early beta. New update will be on Twitch / Curseforge once Mekanism pushes their update to the site.
