### ISSUE TITLE
Important Silent Gear Update Dropped Yesterday

### ISSUE THREAD

**Issue by teknikalarkitekt** [AllTheMods/ATM-6#1120]
An important Silent Gear update dropped yesterday that is supposed to fix the broken armor values of most of the armor. Can we please get an update? My people on my server are super fixated on silent gear and since some of the gear is showing horribly inaccurate armor ratings and stuff, we need that fix from the latest update asap.

**Comment by Pdiddy973** [comment]
the updated version is in our testing version right now. feel free to update manually till then

**Comment by teknikalarkitekt** [comment]
Is there an estimated time when the testing version will be released in the official mod pack?
