### ISSUE TITLE
[Crash] [1.5.2] Integrated Dynamics Crash on Viewing Item Importer GUI

### ISSUE THREAD

**Issue by NoMoreStars** [AllTheMods/ATM-6#1123]
<1.5.2>
**Describe the bug**
Upon viewing the UI for Integrated Dynamics Item Importer block, the game has a habit of crashing suddenly. There seems to be a bit of randomness involved as it doesn't happen 100% of the time.

**To Reproduce**
1. Place down the Item Importer block from Integrated Dynamics, ideally facing an inventory and connected to a simple item network.
2. Right click on the Item Importer to view it's GUI
3. Repeat until game crash
4. If no game crash, try putting in a variable card
5. Repeat step 3

**Additional context**
Optifine_1.6.5_HD_U_G7 was also installed with no shaders present.

**Logs**
https://paste.ee/p/SQJXv

**Comment by DaveJK** [comment]
I've had the same issues in 1.5.2 recently too, seems completely random, but I don't use Optifine.

https://pastebin.com/MiEn7XCT

**Comment by Nonsanity** [comment]
I've had similar crashes when opening various Integrated Dynamics part GUIs. The crash log seems to indicate it is something in the rendering for the GUIs that causes the issue. All of my ID setups are also using the Integrated Tunnels add-on, so there's the possibility that it has a hand in the crashes too. But I haven't done any non-tunnel automations to compare the crash rate to.

Crash log: https://controlc.com/7490aaa0

I'm also reporting the issue to the base mod's github.

**Comment by Pdiddy973** [comment]
Update to 1.5.6, see if issue persist
