### ISSUE TITLE
[Missing Config] AllTheModium

### ISSUE THREAD

**Issue by SirOMGitsYOU** [AllTheMods/ATM-6#1125]
Hi I'm using the ATM 6 Pack version 1.5.2 and noticed there's no config to tweak recipes or disable items in AllTheModium is this intention if so is it potentially something that could be added to help private server owners.

I can see this was mentioned for ATM 5 - https://github.com/AllTheMods/ATM-5/issues/199 and was stated it would be added in ATM6 but so far nothing has been added.

**Comment by thevortex** [comment]
this is intentional, there is not a config file coming at present
