### ISSUE TITLE
Mana & Artifice Constructs cant't break blocks in claimed chunks.

### ISSUE THREAD

**Issue by jaket376** [AllTheMods/ATM-6#1128]
Constructs made using the Mana & Artifice mod cannot break blocks within claimed chunks. For example, if wanting to make a tree farm using the constructs, you have to unclaim the chunk in order to allow for harvesting of trees. This doesn't occur on plants such as wheat however, as I have a wheat farm which works fine with constructs, so it is only actual blocks that they cannot break.

**Comment by omnivance** [comment]
Double-check if the game added a fake player to your FTB Team permissions list. I had the sme issue with the Builder until I made it an "ally" allowed to alter my chunks.

**Comment by Pdiddy973** [comment]
Like above, make sure it is an ally
