### ISSUE TITLE
Can’t gain experience from other dimensions

### ISSUE THREAD

**Issue by koalaMiner** [AllTheMods/ATM-6#113]
I cant seem to get Xp from other dimensions. When I mine quarts in the nether, I see the Xp orb drop but it disappear suddenly and My enderman farm in the end doesn’t give me lvls. The only time I got lvl from the end is when I killed the dragon

**Comment by Akkiraus** [comment]
Same problem here. Placed spawners in the nether and seem to not properly get drops or xp.

**Comment by WhitePhant0m** [comment]
update clumps
