### ISSUE TITLE
ATM6 1.5.2 Immersive Engineering Coke Oven not working

### ISSUE THREAD

**Issue by MatrimVidz** [AllTheMods/ATM-6#1134]
**Describe the bug**

Running a server for All The Mods 6 version 1.5.2.
The Coke Oven from Immersive Engineering does not work. Placing the 26 blocks of Coke Brick in a 3x3x3 cube (no centrum block) does not turn into an oven.
Some guides suggest wacking it with a hammer/wrench, this does nothing as well.

**To Reproduce**
1. Craft at least 26 Coke Bricks
2. Place in 3x3x3 hollow cube.
3. Nothing happens.

**Screenshots**
https://ibb.co/7kN5SHg

**Additional context**

**Logs**
Please use a paste site for logs, instead of putting the file directly in the issue, not only is this easier but also means we can view on mobile when we are not at our computers.
Here's a list of some paste sites and their size limits:
    https://pastebin.com/ 512KB
    https://hastebin.com/ 400KB
    https://gist.github.com/ 100MB Requires member (Free)

**Comment by Xhirox88** [comment]
Bruh, it's not supposed to be hollow, you need 27 coke bricks, make a 3x3x3 cube (NOT HOLLOW), right click it with hammer

**Comment by MatrimVidz** [comment]
> Bruh, it's not supposed to be hollow, you need 27 coke bricks, make a 3x3x3 cube (NOT HOLLOW), right click it with hammer

Bruh, you were totally right. Which is weird beacuse I was almost sertain I tried that already. Also means there is a difference compared to previous versions of the mod. Anyway, all good.

**Comment by MatrimVidz** [comment]
Solved
