### ISSUE TITLE
Spooky Bees Not Producing Honeycomb/Pollinating

### ISSUE THREAD

**Issue by DreamyGamer** [AllTheMods/ATM-6#1138]
Hey there! So currently I have a group playing on a server running ATM6 Version 1.5.2 and we have noticed the Spooky is not pollinating even with about 8 bone blocks in the space they are trapped in. There is a tier 2 beehive in the space and they all go in at the same time, producing no honeycomb. The rest of the bees from the mod are working exactly as they should be. We noticed this after the update to the most current version of ATM6. 

I reproduced this by going into a single-player world. I created a box with a 3x3 area on the inside that is 3 tall with a tier 2 beehive with 8 bone blocks, just like the couple on the server has. I came to the same result of the spooky bee not pollinating and not producing honeycomb.

If anyone has any comments on how to help us out that would be greatly appreciated :)

**Comment by Pdiddy973** [comment]
Fixed in #1072
