### ISSUE TITLE
[1.5.3] RSInfinityBooster.jar missing

### ISSUE THREAD

**Issue by MaoamDEV** [AllTheMods/ATM-6#1140]
**Describe the bug**
Changelog includes "Added RSInfinityBooster", but there is no RSInfinityBooster.jar in the gamefiles. 
**To Reproduce**
1. Update to 1.5.3
2. Look into the mods folder.

**Logs**
https://gist.github.com/MaoamDEV/efec2a18fd5fedcb3cd1d30be10f63b8

**Comment by Werral** [comment]
You can look in the app launcher and see that the mod is not listed there either.

**Comment by MaoamDEV** [comment]
Fixed in 1.5.3b
