### ISSUE TITLE
[1.5.3]Multiplayer ReAuth keeps saying Offline

### ISSUE THREAD

**Issue by adgenanevem** [AllTheMods/ATM-6#1146]
I purchased the Minecraft Java Edition in 2021 (actually a few days ago) because I wanted to play with my friends with All The Mods 6 modpack (1.5.2-1.5.3). The problem is that when I go to Multiplayer menu, the ReAuth keeps saying I'm offline. I can't log in with Microsoft Account (Mojang account linked with Microsoft account ant because of that I own the Java Edition on Microsoft account), and I also can't log in with Twitch account. Other modpacks like Skyfactory 4 works fine, there I can connect to servers, only on ATM6 not. On ATM6 there's always a red X next to the text "Online". We tried to change the server config to offline mode but it didn't work as well. I really want to play this modpack online, so could you help me?

**Comment by CommYutzy** [comment]
Did you determine the root cause of this issue? Friend of mine is having the exact same issue trying to play ATM6. Several others in my gaming group have had no problem with either Mojang or Microsoft accounts, but his is acting up for some reason.

**Comment by mast4ng** [comment]
J'ai le même problème, toujours pas de solutions ??
