### ISSUE TITLE
[1.5.3] Terrasteel seed and essence hidden from JEI, ingot recipe removed

### ISSUE THREAD

**Issue by Zarkov2** [AllTheMods/ATM-6#1147]
**Describe the bug**
After updating to 1.5.3 the Terrasteel seed is still producing essence (botany pot), but they can no longer be used for crafting. Both the seed and essense are hidden from JEI and the recipe for creating Terrasteel seems to have been removed.

**To Reproduce**
Update directly from 1.5.1 to 1.5.3 (I haven't confirmed if this is required to reproduce or if updating from 1.5.2 is enough).

**Comment by winggndm** [comment]
Would like to add that it affect mana steel as well as many others.  Nitro, Spirited, Niotic, Blazing, Quartz Enriched and many others are mssing.

**Comment by DaveJK** [comment]
Mystical Agriculture was balanced #1115

**Comment by Pdiddy973** [comment]
This is not a bug, I couldn't think of a way to stop the seeds from working, but I removed the recipe for the seeds and essence so they functionality don't work
