### ISSUE TITLE
[1.5.3b] Using /reload removes recipes using Pure Ore Chunks and possibly others

### ISSUE THREAD

**Issue by nddragoon** [AllTheMods/ATM-6#1149]
**Describe the bug**
Using /reload removes all processing recipes from elementalcraft pure ore chunks and possibly other recipes, 

**To Reproduce**
1. Open the pack
2. Look at recipes using any pure ore chunk, they're there
3. Use the /reload command
4. Look at the recipes again, they're all gone

**Screenshots**
![image](https://user-images.githubusercontent.com/54559451/109550030-6305b900-7a94-11eb-87a5-09abfff738e3.png)

**Additional context**
Was trying to fix a bug with PNC:R by using /reload, later realized the recipes got removed until i restarted the game

**Comment by Sirttas** [comment]
Pure ore recipes are not handled in datapack I will look into it.

**Comment by LegitSoulja** [comment]
You shouldn't be reloading modded servers. If you need to reload a specific plugin, use the specific plugin reload command. Otherwise, I suggest using PlugMan.
