### ISSUE TITLE
[0.29] Crash when using Seed Reprocessor

### ISSUE THREAD

**Issue by caseirouowotm8** [AllTheMods/ATM-6#115]
In version 0.29, putting coal and seeds into a reprocessor from mystical agriculture will crash the client.
Crash report follows:
[crash-2020-09-07_16.41.33-client.txt](https://github.com/AllTheMods/ATM-6/files/5183898/crash-2020-09-07_16.41.33-client.txt)

**Comment by WhitePhant0m** [comment]
Fixed as of the latest preview versions.
