### ISSUE TITLE
[1.5.3b] Crashes on Startup

### ISSUE THREAD

**Issue by papaige** [AllTheMods/ATM-6#1150]
1.5.3b on ATM6

**Describe the bug**
Crashes on startup due to BiggerReactors

**To Reproduce**
1. Open Game
2. Crash

sorry if this is mean but yes i am on 1.5.3*b* and not 1.5.3

**Logs**
I Include the default logs and latest log below.
latest log was too big so i split it. sorry

normal log: https://pastebin.com/iKSteQzG
latest log 1: https://pastebin.com/gUy4QRe8
latest log 2: https://pastebin.com/6KiiRWni

**Comment by papaige** [comment]
Nevermind, i fixed it by re-instaling the curseforge program and evereything in it

**Comment by papaige** [comment]
And now it crashes with Immersive Engering. Still crashes on startup,
here are logs:

normal https://pastebin.com/98BuBVye
latest 1 https://pastebin.com/UcFrgmAA
latest 2 https://pastebin.com/zQYjSj6M

**Comment by DemandedFanatic** [comment]
Mine also crashes on start from bigger reactors

Crash report: https://pastebin.com/15jQh45w

**Comment by lessthanzach** [comment]
> 
> 
> And now it crashes with Immersive Engering. Still crashes on startup,
> here are logs:
> 
> normal https://pastebin.com/98BuBVye
> latest 1 https://pastebin.com/UcFrgmAA
> latest 2 https://pastebin.com/zQYjSj6M

Did you have a Faraday suit in a dispenser?  I'm no pro, it just looked like an item from IE was present in a dispenser block of sorts is what threw the error based on the crash report.  If that is the case, you could use a program like Amulet world editor or NBTexplorer to delete the offending dispenser.

**Comment by papaige** [comment]
it actually stopped crashing now, however i have reinstalled the game more times than i can count.
Also, i dont, i play on a server with my friends and i didnt have the world.
