### ISSUE TITLE
Many Mystical Agriculture seeds have been disabled

### ISSUE THREAD

**Issue by tuzoli** [AllTheMods/ATM-6#1153]
The release notes to 1.5.3b say:

"Also many Mystical Agriculture seeds have been disabled in this update. Any remaining essence will no longer be craftable."

Just like last time with the bees; some more information would be highly appreciated. Which seeds are being removed?

**Comment by DaveJK** [comment]
#1147

**Comment by jeremiahwinsley** [comment]
Here is the PR containing the latest changes, with the list of removed seeds highlighted: https://github.com/AllTheMods/ATM-6/commit/d9f857b258186d7058895a1ae7e75c3688cddb51#diff-22cc72c669fbd90a9d8b23883c9cd80a74d3c462d7aca0902f952d23441c232bR186-R187
