### ISSUE TITLE
Ice and Fire Dragon Caves not generating

### ISSUE THREAD

**Issue by Abendclyde** [AllTheMods/ATM-6#1154]
Pack Version: 1.5.3
**Describe the bug**
Our friends and I wanted to get ice and fire dragons, but didn't found any of the caves. After checking tutorials to see if we're missing something (and we weren't) we checked singleplayer worlds as well and there weren't any dragons. We flew around in spectator for literally hours to test if they spawn. We found nothing.

It wouldn't be that bad if it wasn't for the allthemodium alloy tools, for which you need to make a dragon forge, which is difficult to make if there aren't any dragons!

**To Reproduce**
Just load up ATM6 1.5.3 and fly around and check if you find dragons, i doubt we were this unlucky

**Comment by GordonHollow** [comment]
Dragons spawn only in Other dimension.
Also i try to find dragons in The Other in 1.5.3ATM6, fly 10K blocks from spawn and only found ONE DRAGON. That didn't drop what i need for craft dragon forge

**Comment by Abendclyde** [comment]
Yeah we found that out today as well, pretty weird i didn't see it anywhere said that they only spawn there.
