### ISSUE TITLE
1.5.3b server download texture glitch.

### ISSUE THREAD

**Issue by Benzz115** [AllTheMods/ATM-6#1155]
Items from "manna and artifice" have the wrong texture (on the server download off curseforge) when placed in the world but the right one in your inventory. Also "Forbidden & arcanus" items such as the cherrywood tree appears to made of cherrywood trapdoors in wold but when you break it it drops as the cherrywood log.

 I checked it out on a single player world and it was working as normal

**Comment by Pdiddy973** [comment]
Update and see if issue persist
