### ISSUE TITLE
1.5.3b PneumaticCraft ticking block entity crash

### ISSUE THREAD

**Issue by Dasfaust** [AllTheMods/ATM-6#1156]
**Describe the bug**
[PneumaticCraft 2.10.1-140 has a server-side crash due to an ArrayIndexOutOfBoundsException](https://github.com/TeamPneumatic/pnc-repressurized/issues/749). Server crashes instantly when ticking the world after updating passed ATM 6 1.5.2.

**Additional context**
This is fixed with [this commit](https://github.com/TeamPneumatic/pnc-repressurized/commit/97ba9aab515c75f21e8449d3823f12897417486d) and should be in the next release of PneumaticCraft. Just a heads up.
I was able to temporarily overcome this by compiling the mod at [this commit](https://github.com/TeamPneumatic/pnc-repressurized/commit/909201fc36a1a0e0d191c794a343a963182c464f), and changing `PROTOCOL_VERSION` to `3` in `me/desht/pneumaticcraft/common/network/NetworkHandler.java` then sticking that on the server. Will probably cause issues for clients, but the server starts now.

**Logs**
[Crash report](https://pastebin.com/raw/mawBJpvD)

**Comment by desht** [comment]
Just to note, PNC 2.10.2 is just released and should fix this (and not cause network protocol errors :P)

**Comment by jeremiahwinsley** [comment]
Pneumaticraft has been updated to 2.10.3 in 1.5.4.
