### ISSUE TITLE
Crude Oil from Thermal series does not have forge:crude_oil fluid tag

### ISSUE THREAD

**Issue by cornytrace** [AllTheMods/ATM-6#1158]
**Describe the bug**
Crude Oil from Thermal Series does not have forge:crude_oil fluid tag, so it is not interchangeable with the Crude Oil of Immersive Engineering and PneumaticCraft.

**To Reproduce**
Try to use Thermal Series Crude Oil in PneumaticCraft Machines or PneumaticCraft Crude Oil In a Fractionating Still.
See that it does not work.

**Screenshots**

**Additional context**
Crafttweaker or similar mod must be used to add the forge:crude_oil tag to Thermal Series Crude Oil so the fluid dictionary can do its thing.
CoFH has no issue tracker on github at the moment so I decided to make an issue here.

**Logs**
If you believe logs are necessary I will provide them.

**Comment by whatthedrunk** [comment]
all 3 types of crude oil should work if there was something we missed let us know
