### ISSUE TITLE
1.5.3b Modlist Crash

### ISSUE THREAD

**Issue by Virtualhel** [AllTheMods/ATM-6#1161]
**Describe the bug**
Clicking on the Compressium mod in the list of mods brings up a "Saving world" screen before crashing the game.

**To Reproduce**
1. Load game
2. Click on "Mods" in the main menu
3. Scroll down to 'Compressium'
4. Click that entry in the list

**Logs**
https://pastebin.com/AiNstHy2

**Comment by whatthedrunk** [comment]
If its still happening let them know here. https://github.com/DinnerBeef/Compressium/issues
