### ISSUE TITLE
Pure ore slurry recipes different v 1.5.3

### ISSUE THREAD

**Issue by arshiahf** [AllTheMods/ATM-6#1162]
When making slurries with pure ores, they come out to 750 dirty ore slurry per chunk instead of the listed 800, which causes a backup in automated systems with numbers of ore that aren't a multiple of 2. Is this intended, or is this an oversight?

**Comment by Sirttas** [comment]
Make sure you have the same config between your client and server.
Also because of the combiner I had to nerf it a lot.
At this point I am really thinking of disabling this feature.

**Comment by TBoshoven** [comment]
I'm pretty sure what you're describing is default Mekanism behavior, except doubled using Elemental Craft.
These are just the defaults from Mekanism (although in plain Mekanism without EC the backup would be worse to deal with).

Consider it a challenge to make it not back up :)
