### ISSUE TITLE
Dragons not spawning and other creatores from ice and fire not spawning

### ISSUE THREAD

**Issue by KratosCoragem** [AllTheMods/ATM-6#1163]
I am plating ATM6 at 1.5.3b and when i go to the other dimension no dragons on is spawn and i try to find him with de spetral amulet and still nothing. From ice and fire i just found pixies cocatrizes and 1 time ghost the rest i junt don't find so i wonder if is a bug or is just somthing rong with my world

**Comment by MaoamDEV** [comment]
They only spawn in specific biomes with a low rate.

Ice = Mountains
Fire = Delta Basalt
Lightning = Desert

Also keep in mind you need to be at least 1000 blocks away from spawn and the structures only generate with at least 3000 blocks in-between.

**Comment by KratosCoragem** [comment]
I have search like 2000 away from spawn and with all needs to them spawn and i still havan't find 1 dragon. I don't know if i am just unlucky  but if i am can you tell me where i can increse that rate pls

**Comment by MaoamDEV** [comment]
Went from my spawn straight to the north. Around 3 Ice Dragons, 1 Fire, 1 Lightning until I found a Dragon Den with a Stage 5 Female Ice Drake @ 0, 17000. Just fly over the biomes I mentioned before with a Spectral Eye Amulet and you should be fine. 

Also 2000 blocks away from spawn isn't nearly enough, as you need to be at least 1000 blocks away from spawn to get those structures generated. Then you get a 1 out of 20 chance to generate a Dragon Nest in those chunks in those specific biomes. 

In case you want to increase the spawn rates take a look at the config file of Ice and Fire, but I'd suggest to stick with the defaults made by the ATM team.

**Comment by KratosCoragem** [comment]
Thanks very much dude, i just found my first dragon after hours but i find him without change the rate so is not bug just unluckuy ahah, but really thanks
