### ISSUE TITLE
[1.5.3b] Immersive Engineering causing crash on server start 

### ISSUE THREAD

**Issue by rdxxn** [AllTheMods/ATM-6#1164]
**Describe the bug**
Immersive engineering "has failed to load correctly"

**To Reproduce**
well in my case i just updated a server from 1.5.2 to 1.5.3b and immersive engineering fails to load

**Logs**
https://pastebin.com/c5bCJHRF
https://pastebin.com/c5bCJHRF

**Comment by jeremiahwinsley** [comment]
This should be fixed in 1.5.4.
