### ISSUE TITLE
Minecolonies has bugs that have been fixed in the mod.  The pack needs updating.

### ISSUE THREAD

**Issue by tyduncanson** [AllTheMods/ATM-6#1166]
**Describe the bug**
Pack version 1.5.3 on 1.16.3.  Minecolonies builders have pathing issues that are fixed by the newer versions of the pack.  

**To Reproduce**
1. Queue a large-scale building in minecolonies
2. Assign a builder to the job
3. Eventually the builder will stop making progress and will just walk in a circle

**Screenshots**

**Additional context**
This is a know issue and was fixed in the latest version of minecolonies, so updating the minecolonies and structurize files should fix this.

**Comment by DanCarlyon** [comment]
I have this same issue on 1.5.3b although the jobs i asked the builder to do weren't exactly "large" (Level 1 town hall medieval spruce alternative)

**Comment by jeremiahwinsley** [comment]
Minecolonies has been updated in 1.5.4, assuming this issue is fixed.

**Comment by DanCarlyon** [comment]
I can confirm my issue was fixed with 1.5.4 :)
