### ISSUE TITLE
Allthemodium worldgen crash  (allthemodium-1.2.2-1.16.4-35.1.13)

### ISSUE THREAD

**Issue by Irritated-Badger** [AllTheMods/ATM-6#1167]
(There was no dedicated issue tracker attached to Allthemodium, so I do apologize for posting this here)

Mod Version: allthemodium-1.2.2-1.16.4-35.1.13.jar
Minecraft Version: 1.16.5
Forge Version: 36.0.45
BYG Version: 1.1.10
Ice and Fire Not installed

Crash when creating a new world and opening saved world with newest version  allthemodium.

Log: https://pastebin.com/Sde1Gw00

**Comment by thevortex** [comment]
resolved with https://www.curseforge.com/minecraft/mc-mods/allthemodium/files/3225893 ( files just uploaded now, should be available via the curse launcher within a few hours )
