### ISSUE TITLE
[1.5.3b] RS Infinity booster makes storage network shut down

### ISSUE THREAD

**Issue by dexis5656** [AllTheMods/ATM-6#1169]
Just updated to 1.5.3b from 1.5.2  and I'm finding that attaching the RS infinite range booster into a wireless transmitter makes the whole storage network shut down.  All connected RS blocks except the controller go dark and inventory is not accessible. 

I'm also having trouble with RS because every time i try to open my storage that's connected to my infinite storage card, my connection to my server crashes.  This doesn't seem to be a server issue because it wasn't happening before the update to 1.5.3b and I have removed plenty of items from my storage  to try and fix the issue so I must have had more items in my storage before the update and like i said, the crash wasn't happening.

I hope you can shed some light on this issue, are you hearing anyone else say they have similar problems?

Thankyou for all your hard work, besides a few bugs, this modpack has been fantastic!

**Comment by MaoamDEV** [comment]
First one is probably related to #1152. 

For the second one, just to clarify, we are talking about a storage disk and not the infinity booster card, right?
There are some known issues with NBT corruption if you got too many items in your storage which can result in crashes and worst case loosing all items on that disk. 
Happend to me a while ago with an infinite fluid disk.

Any log entries about the connection loss? Or maybe a message why you disconnected?

**Comment by dexis5656** [comment]
yes I'm referring to an infinite storage disk for the second part there.  The message when i lose connection said some action cannot go over a certain number of bytes of data, so yes i assume it has to do with the number of items in the storage.   I can access the items by putting the infinite storage disk in its own network,  I set up an auto-voiding machine to get rid of excess amounts of items, ill test whether or not that works next time i get on. Its just a pain that the infinite disk isn't really infinite.

**Comment by MaoamDEV** [comment]
Yep this message is probably that your NBT data is to large to handle. If you got backups enabled, you could try to load one of the Refined Storage backups. Files named:
- refinedstorage_disks.dat
- refinedstorage_networks.dat
- refinedstorage_nodes.dat

found in /world/data/.

**Comment by dexis5656** [comment]
okay, what would that do?  would it work for me to just remove some items from my storage?

and as far as the infinity range booster, is there an in-game work around or solution for the energy cost issue?

**Comment by dexis5656** [comment]
Ah, it seems it isnt an energy issue, my RS controller is showing that isnt using more than 20k FE/tick but it still shuts everything down the moment i try to use the range booster

**Comment by MaoamDEV** [comment]
Yeah sure, you could just remove Items from your network. Loading a backup just would revert your items on the disk to date X.

You can increase the controller capacity to get rid of the system shutting down. The option is found in "/world/serverconfig/refinedstorage-server.toml". 128k worked fine for me to place one infinity range booster in multiple dimensions.

**Comment by MrMinitwo** [comment]
So I'm having an issue similar to what @dexis5656 has described as far as my client crashing when I try to access my refined storage network and displaying this error about payload:
"
internal exception: io.netty.handler.codec.decoderexception: java.io.IOException: payload may not be larger than 1048576 bytes
"
So also I'm only using a 16 million storage disk with maybe 6 million of that being used.  Ive tried several things so far and i literally just moments ago tried downloading the world from the server and putting it in single player and it seems to be working fine now but I am having a bit of lag that I didn't have before this issue in my base. So im not sure what is going on, any help would be wonderful.

**Comment by starforcraft** [comment]
Use Creative Wireless Transmitter :)
