### ISSUE TITLE
Cannot create inscriber silicon press for the first time

### ISSUE THREAD

**Issue by lodimasq** [AllTheMods/ATM-6#1171]
Since recent patch disabling silicon seeds I do not believe it is possible to create the inscriber silicon press for a new playthrough.

![image](https://user-images.githubusercontent.com/64287471/110043082-b307a880-7d3e-11eb-9cf6-42204822d5f4.png)

The top recipe is unachievable as AE2 Silicon is disabled. I think logically this should be changed to forge:silicon and the issue is resolved. The bottom alternative recipe is also unachievable as silicon seeds have been disabled in the current patch.

Unless I am missing something, this makes it impossible to obtain the silicon press for AE2. For now, I have re-enabled silicon seeds in order to be able to progress the game. I still think that the best resolution is to enable the top recipe in the image to support forge:silicon.

Apologies in advance if I am missing some form of progression here but I cannot find it anywhere in NEI.

**Comment by jeremiahwinsley** [comment]
By default there is no recipe for the press, you locate it in a meteor. This method should still be possible in 1.5.3b. Silicon seeds are planned to be re-enabled next release, which will fix the second recipe. First recipe is from Mystical Agriculture and probably needs either disabled for the pack or fixed on their end.

**Comment by lodimasq** [comment]
Perhaps there was an issue with my world gen, but I was unable to find the meteorites (using the compass) in any dimension. I do see it enabled in the AE2 config though. In any case, re-enabling the seed next release should fix the issue. Thanks

**Comment by thevortex** [comment]
World type of biomesoplenty breaks everything including meteorite spawn
