### ISSUE TITLE
Bigger reactors failure v1.5.3b

### ISSUE THREAD

**Issue by Dumerin** [AllTheMods/ATM-6#1172]
Bigger reactors does not load properly causing the pack to crash

[Atm6 1.5.3b crash-2021-03-05_13.31.28-fml.txt](https://github.com/AllTheMods/ATM-6/files/6087406/Atm6.1.5.3b.crash-2021-03-05_13.31.28-fml.txt)

**Comment by DaveJK** [comment]
Try using Phosphophyllite 0.4.5 instead of 0.5.0

**Comment by RogueLogix** [comment]
This is a bug with the curseforge launcher, you probably have multiple instances of BiggerReactors and Phosphophyllite in your mods folder (other mods too probably), for these two delete all but BiggerReactors 0.4.3 and Phosphophyllite 0.4.5

**Comment by Dumerin** [comment]
Fixed thank you
