### ISSUE TITLE
[1.5.3b] Blocks have been randomly replaced and server/game crashing

### ISSUE THREAD

**Issue by MiLikeTurtles** [AllTheMods/ATM-6#1173]
We updated our server and when logging on we noticed a bunch of blocks being replaced with other block, and all mekanism pipes/connectors have all glitched out, as well as blocks for reactors, chests disappearing, ender chest getting turned into flux points and etc. The server would then say saving world and then the game crashes.

![Jre-legacy Screenshot 2021 03 04 - 16 36 12 40](https://user-images.githubusercontent.com/80077236/110050332-89338f00-7d08-11eb-85f0-f79251fd76ce.png)

![Jre-legacy Screenshot 2021 03 04 - 16 36 53 12](https://user-images.githubusercontent.com/80077236/110050340-905a9d00-7d08-11eb-919d-2ad0affcc792.png)

![Jre-legacy Screenshot 2021 03 04 - 16 37 13 73](https://user-images.githubusercontent.com/80077236/110050347-93ee2400-7d08-11eb-8867-af322e8dbdea.png)

![Jre-legacy Screenshot 2021 03 04 - 16 37 29 88](https://user-images.githubusercontent.com/80077236/110050354-95b7e780-7d08-11eb-9005-36cf1e460b17.png)

This was an infernium farm (would be converted anyway since mystical agriculture is getting disabled) right clicking on the rats also crashes the server for some reason since the 1.5.1 update.

![Jre-legacy Screenshot 2021 03 04 - 16 37 47 73](https://user-images.githubusercontent.com/80077236/110050360-981a4180-7d08-11eb-9128-a29226946693.png)

This is supposed to be an ender chest

![Jre-legacy Screenshot 2021 03 04 - 16 39 06 73](https://user-images.githubusercontent.com/80077236/110050375-9cdef580-7d08-11eb-9aae-e3ce70f7b93f.png)

This is the error code when the server times us out.

The game crashed whilst ticking block entity
Error: java.lang.IndexOutOfBoundsException: Index: 3, Size: 4
Exit Code: -1

**Comment by jeremiahwinsley** [comment]
This happens when your client is out of sync with the server. This is usually caused by CurseForge launcher failing to update correctly. You can resolve this by doing a fresh install of the pack, either in CurseForge or a better launcher like MultiMC or GDLauncher.
