### ISSUE TITLE
Mob Duplicator Infinite Energy (?)

### ISSUE THREAD

**Issue by Abendclyde** [AllTheMods/ATM-6#1176]
Pack Version: 1.5.3
**Describe the bug**
I'm not sure if it's ATM6s or Industrial Foregoing's Bug, but the Mob Duplicator doesn't accept, use or need energy to work

**To Reproduce**
Place a Mob Duplicator. (We placed it in the Mining Dimension)

**Additional context**
I mean it should use Energy right? It even has this energy storage bar

**Comment by jeremiahwinsley** [comment]
Cannot reproduce on 1.5.4, the Mob Duplicator requires energy. Assuming this is fixed.
