### ISSUE TITLE
Updating server to 1.5.3b causes visual bugs and wrong blocks

### ISSUE THREAD

**Issue by Rix250** [AllTheMods/ATM-6#1177]
so, i have an atm server in version 1.5.3, my friend told me that ice and fire's dragons always spawn dead, so we needed to update, I updated to 1.5.3b, copied the old world and server.config into a new folder, ran startserver.bat. Everything started normally, but when i entered the server, several blocks were bugged and they had wrong textures, for example waystones are 2 walls, wawla says that they are darkstone walls from the mod waystone, but if i right click they act like a regular waystone. Storage drive from ae2 are a waterlogged bed, if i right click on it miecraft crashes, but the server does not

log: https://gist.github.com/Rix250/def6517d7bc8aa8a66d2fc041abed56d
screenshots:
![2021-03-06_12 58 42](https://user-images.githubusercontent.com/67917020/110206156-64602880-7e7c-11eb-9b6a-27d6407c8f31.png)
![2021-03-06_12 58 32](https://user-images.githubusercontent.com/67917020/110206160-66c28280-7e7c-11eb-9590-54e01a536f38.png)
![2021-03-06_12 58 28](https://user-images.githubusercontent.com/67917020/110206171-6f1abd80-7e7c-11eb-9362-eb09b1d6e8fa.png)
![2021-03-06_12 58 47](https://user-images.githubusercontent.com/67917020/110206143-5ad6c080-7e7c-11eb-96d5-73207f62e9a1.png)
![2021-03-06_12 58 44](https://user-images.githubusercontent.com/67917020/110206148-5f02de00-7e7c-11eb-8f52-670954f165e6.png)

**Comment by thevortex** [comment]
The dragons do not "spawn dead" dragon skeletons spawn in biomes the living
dragons are not marked to spawn in. There are specific biomes for each live
dragon

**Comment by erickloss** [comment]
I had the exact same issue. I got a hint from the ATM6 discord to **reinstall the client side** of the mod pack (just delete and reinstall the modpack in curseforge with the current version). That fixed it for me. No need for any action on the server.

**Comment by Rix250** [comment]
> I had the exact same issue. I got a hint from the ATM6 discord to **reinstall the client side** of the mod pack (just delete and reinstall the modpack in curseforge with the current version). That fixed it for me. No need for any action on the server.

thx, i'll try
