### ISSUE TITLE
Game crash when i use eye of fugel or use nether portal to comeback to overworld [1.5.3b]

### ISSUE THREAD

**Issue by KratosCoragem** [AllTheMods/ATM-6#1178]
When i use nether portal to go to the nether everything is good and i do what i have to do and it's ok, but when i use the portal to comebakc my game freeze and crash, and when i re-launch the game i spawn in my spawn (not my bed) and when i use the eye of fugel to comeback the game crash again.
Idk if is just to me or if is a bug on this versions, cause in other versions that doesn't happen.
Acctualy the game crash every time i use somthing to teleport

**Comment by ladylexxie** [comment]
Not happening anymore in the current version.
