### ISSUE TITLE
Install issues - Unable to get Addon: X - changes every time

### ISSUE THREAD

**Issue by ItsmeHJB** [AllTheMods/ATM-6#1179]
Install issues - Unable to get Addon - changes every time.

Steps to reproduce the behaviour:
1. Have curseforge installed
2. Go to: https://www.curseforge.com/minecraft/modpacks/all-the-mods-6/files/2997714
3. Press install

**Screenshots**
![image](https://user-images.githubusercontent.com/33870468/110217033-d4d16e80-7ea9-11eb-9200-7455d2b09353.png)
![image](https://user-images.githubusercontent.com/33870468/110217045-e9ae0200-7ea9-11eb-98c9-5e1b8a9b1732.png)

**Additional context**
Worked earlier today, but has since stopped. I suspect it's a dependency issue, but I can't be much help past that.

**Comment by starforcraft** [comment]
Thats not a problem from ATM 6 its because of curseforge Launcher. The best is use a better Launcher for example [MultiMC](https://multimc.org/#Download) or [GD Launcher](https://gdevs.io/).

**Comment by ItsmeHJB** [comment]
Solved - Curseforge issue resolved itself
