### ISSUE TITLE
[1.5.3] Pure Infusion Not Working (Elemental Craft)

### ISSUE THREAD

**Issue by Bout17kids** [AllTheMods/ATM-6#1181]
Pack Version: 1.5.3 - (Release)
**Describe the bug**
Attempting to do a pure infusion plays the animation but does not produce a result. Furthermore, setting up the infusion without providing an elemental supply will play the animation, despite there being insufficient elemental energy to do so. I have done multiple tests to ensure my pure infusion setup is correct and that there is no user error. 

**To Reproduce**
1. Set up a pure infusion with no elemental supply
2. Set up any pure infusion recipe (ex. Pure Crystal)
3. Notice that the pure infusion animation plays, despite there being no elemental supply
4. Supply each pedestal with its respective element using Improved Element Pipes
5. Notice how the pure infusion process will never end and never produce a result 

**Screenshots**
![2021-03-06_20 53 37](https://user-images.githubusercontent.com/50220620/110228416-313e8900-7ebe-11eb-94e6-10e77a0816a0.png)
![2021-03-06_20 52 34](https://user-images.githubusercontent.com/50220620/110228417-33a0e300-7ebe-11eb-890a-9024a8dbeda6.png)

**Additional context**
FYI: You can use creative element containers instead of normal element containers in your reproduction

**Comment by Sirttas** [comment]
Your pipes are not extracting from the containers. I think the only bug is that the animation is played even though there is not progress done.

**Comment by JheregJAB** [comment]
I noticed the animation bug as well, however other than the visual bug the pure infusion works fine for me on ATM6 1.5.3b.

**Comment by Sirttas** [comment]
So there is just a render bug, it should also happen on infuser, binder etc.
I fixed it for the next elemental craft release however it's a major release and will only be available in a week or two.

**Comment by Bout17kids** [comment]
> So there is just a render bug, it should also happen on infuser, binder etc.
> I fixed it for the next elemental craft release however it's a major release and will only be available in a week or two.

Okay, thanks for clearing that up.
