### ISSUE TITLE
Digital Miner should not require unobtainium to craft

### ISSUE THREAD

**Issue by JheregJAB** [AllTheMods/ATM-6#1182]
atm6 1.5.3b

The digital miner requires unobtainium to craft. However, by design the allthemodium ores are not able to be mined by the digital miner. Having unobtainium in the recipe for the digital miner makes it appear as though the digital miner will be able to mine that ore.

After all, from a player's perspective, why would I need to find, mine, and process unobtainium in order to get the digital miner, if the digital miner was not then going to make it easier for me to get more of said ore? Once the expectation of being able to auto mine the ore is set, it is very frustrating to find that expectation is wrong.

**Comment by thevortex** [comment]
This is intentional
