### ISSUE TITLE
Aquamarine Shale from AstralSorcery don't generate?

### ISSUE THREAD

**Issue by GordonHollow** [AllTheMods/ATM-6#1183]
ATM6 1.3.9-1.5.3b (latest), all of updates has that issue for me

Create any new world
Try to find Aquamarine Shale
Can't find it fly over 10k block in creative

In AS configs that turn on, should generate that ore

Possibly modpack changes biomes\dimensions in which it spawn?

**Comment by thevortex** [comment]
Are you using default world type?

**Comment by GordonHollow** [comment]
Try different world types, mostly BoP, but default also has that issue

**Comment by jeremiahwinsley** [comment]
Tested in 1.5.4 on default world type, aquamarine shale generate correctly..
