### ISSUE TITLE
Rats Mod not going after mobs

### ISSUE THREAD

**Issue by Fido090** [AllTheMods/ATM-6#1186]
)
(V. 1.5.3b)  Tamed rats to help protect me and kill things in dungeons and such, but whenever attacks me the Rat ignores the hostile mob, same with the Hunt Mobs feature. Anyone know why and how I can fix this?

**Comment by jelliott7** [comment]
This is present for me as well. The only way I can get them to attack passive mobs even is by setting their behavior to "Hunt Animals" and then attacking a mob once that is next to the rat.

**Comment by ladylexxie** [comment]
If this is still the case, it's a mod issue, not pack issue.
