### ISSUE TITLE
Unable to create new singleplayer world

### ISSUE THREAD

**Issue by orionSquared** [AllTheMods/ATM-6#119]
Unable to create a singleplayer world. Started on version, 1.0.4, got a warning that a feature was experimental. I click proceed and it begins to build the world. Gets to 100% and just sits there. Waited 10 minutes before I just force quit. No crash log created.

Moved back to 0.29. I no longer get the experimental feature warning, but same thing happens. Single player world gets to 100% and just sits there. Waited ten minutes again to make sure it wasn't just slow before I had to force quit. No crash log created.

**Comment by orionSquared** [comment]
Updated to 1.0.5 since it released since I first downloaded the pack earlier today. Started a new world. Got the same experimental feature warning. Single Player world has been sitting at 100% for the past 45 minutes. I don't think it's going to launch...

**Comment by whatthedrunk** [comment]
We are currently on 1.16.3 so removing older issues to make way for new ones. If you want to test it out join the discord for an early beta. New update will be on Twitch / Curseforge once Mekanism pushes their update to the site.
