### ISSUE TITLE
Villagers not breeding ver. 6-1.5.3b

### ISSUE THREAD

**Issue by BossRedRanger** [AllTheMods/ATM-6#1192]
I've set up a vanilla villager breeder that has worked in previous pack versions, but now breeding fails. I looked through the vanilla forums thinking it was my world settings, but in a fresh world with no alterations, the villagers still refuse to breed. This setup most definitely works in vanilla.

Log: https://paste.ee/p/j3xPb

![2021-03-09_11 00 23](https://user-images.githubusercontent.com/6528749/110500090-d75cdf80-80c6-11eb-98c5-f176b8915fe5.png)
![2021-03-09_11 00 25](https://user-images.githubusercontent.com/6528749/110500091-d7f57600-80c6-11eb-9588-f0b03a27e655.png)
![2021-03-09_11 00 33](https://user-images.githubusercontent.com/6528749/110500170-ec397300-80c6-11eb-9622-17b7d584b841.png)

**Comment by whatthedrunk** [comment]
working fine in newest thanks
