### ISSUE TITLE
[1.5.3b] Crash when visualising apiary

### ISSUE THREAD

**Issue by iarspider** [AllTheMods/ATM-6#1193]
**Describe the bug**
Game crashed when visualizing apiray

**To Reproduce**
1. Get "Fifty shades of bees"
2. Open Apiary entry
3. Visualize, wait a bit...
4. ... crash

**Additional context**
I guess the crash happened when Myalite was used as a variant in multiblock preview

**Logs**
https://gist.github.com/iarspider/706d47d62d751e1ab04b735f49f4445c

**Comment by Pdiddy973** [comment]
fixed in latest version
