### ISSUE TITLE
Cannot install from CurseForge

### ISSUE THREAD

**Issue by quitek** [AllTheMods/ATM-6#1197]
Version: Any/Newest (I guess?)
When I click "Install" in CurseForge app it shows "Failed to create pack". I tried to use a different launcher (ATLauncher) and it also refused to install. I reinstalled Curse and it still doesn't work, so it's an issue with the Curse files/download. Other packs install no problem.

![Screenshot 2021-03-11 090946](https://user-images.githubusercontent.com/80451140/110758301-ac03fd00-824c-11eb-93b0-a85d83a13c2b.png)

**Comment by BossRedRanger** [comment]
That's an issue for Curse, not these modpack devs.

If you want you can downloand MultiMC. Create new instance. Then add using the curse link.
