### ISSUE TITLE
Shift-right click isn't working 1.5.3b

### ISSUE THREAD

**Issue by Robo013** [AllTheMods/ATM-6#1198]
After updating to version 1.5.3b Shift-right clicking a block isn't activating it but it puts a border around it (selecting it).

So since the update I can't use alot of stuff anymore for example the teleporrt pad from Allthemodium needs to be Shift-right clicked and now it only selects it by putting a purple/pink border around it.

Anyone have any idea how to fix this?

**Comment by DaveJK** [comment]
Remove your Ring of Loki
