### ISSUE TITLE
Vanilla mob spawners seem to have no spawn limit - Ver. 1.0.4

### ISSUE THREAD

**Issue by stillg0ld** [AllTheMods/ATM-6#120]
I'm assuming it has something to do with Apotheosis Mod altering spawn conditions. Vanilla spawners are spawning extremely rapidly (I would say about 3-4 every 5-10 seconds) compared to vanilla's mechanic of 1-4 every 40 seconds. Not sure if this was intentional of just default apotheosis configs that weren't noticed.

**Comment by whatthedrunk** [comment]
We are currently on 1.16.3 so removing older issues to make way for new ones. If you want to test it out join the discord for an early beta. New update will be on Twitch / Curseforge once Mekanism pushes their update to the site.
