### ISSUE TITLE
Crash when exiting mining dimension

### ISSUE THREAD

**Issue by ttttdoy** [AllTheMods/ATM-6#1200]
Version 1.5.4
When exiting the mining dimension through the portal block or using /home the game would often freeze up and then crash.

**To Reproduce**
1. Go to the mining dim
2. Exit the mining dim with /home or portal
3. Game crashes

**Screenshots**

**Additional context**
This also happened on 1.5.3b but it hasn't on versions prior to that

**Logs**
https://gist.github.com/ttttdoy/3394e38b826569a19362759dd630b465

**Comment by jeremiahwinsley** [comment]
Reported here: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/5057

**Comment by jeremiahwinsley** [comment]
Just noticed you have Optifine installed. If you can reproduce this without Optifine please reopen.
