### ISSUE TITLE
Blocks textures of many mods are all messed up

### ISSUE THREAD

**Issue by Ajhplyr** [AllTheMods/ATM-6#1201]
Hello,

I just updated my server and my client to 1.5.4 and after loading the world, many blocks are displaying wrong textures.
Exemple :
 - Waystone -> Paved Dark Scoria Wall (with water)
 - Birch Drawers 1x1 -> Polished Myalite Vertical Slab
 - Darkstone -> Orange Chimeerite Crystal
 - Sleeping Bag -> Small Travertine Brick Wall
 - many more ...

Drawers screenshot (the 4x4 are wrong too) :
![2021-03-12_14 03 32](https://user-images.githubusercontent.com/6836426/110943836-f7490900-833b-11eb-8caf-69cab466c272.png)

Some of these blocks are working as usual (waystone) and other not (drawers).

Did i wrongly update the pack or does someone else have the same problem ?

Edit : All my friends on the server have this problem.

**Comment by Arnaen** [comment]
I have figured out an intermediate solution.

I had to delete the entire modpack from my computer and reinstall it. 
After that everything was fine again...

However, it would be great if you do not have to do that.

Thanks and I hope it helps.
LG Arnaen

**Comment by Ajhplyr** [comment]
Hi,

You are right Arnaen, the actual solution is to recreate from scratch the client. Thanks for your advice.

I was focus on a world corruption as all my friends playing on it had the same problem. But the problem came from the client :/

For those who have to recreate from scratch and don't want to lose too much datas, there is some files/folders you can save from your older client :
 - in the "config/jei/" folder, you have the bookmarked and blacklisted items.
 - in the "local/ftbchunks" folder, you have your explored map datas.
 - in the "ESM" folder, you have your muffled sounds and anchors.
 - in the "options.txt" file, you have your Minecraft options (Keybinds, Graphics, ...)
 - in the "optionsof.txt" file, you have your optifine options if you use it.
 - in the "optionsshaders.txt" file, you have your shaders options (don't forget to copy your "shaderpacks" folder before)
 - and maybe others that I don't remember or don't know.
