### ISSUE TITLE
[1.5.4] biggerreactor turbine power output

### ISSUE THREAD

**Issue by acarou** [AllTheMods/ATM-6#1202]
why my turbine don't have rf sotrage and don't output power ?
![image](https://user-images.githubusercontent.com/20341579/110950560-48f59180-8344-11eb-8d1c-d6111ecf070a.png)
![image](https://user-images.githubusercontent.com/20341579/110950629-5e6abb80-8344-11eb-9523-d5e2cee94fa1.png)

**Comment by starforcraft** [comment]
Should be fixed in newest Version.
