### ISSUE TITLE
Wandering Wizards cause client crash

### ISSUE THREAD

**Issue by kelso6969** [AllTheMods/ATM-6#1203]
**Describe the bug**
right click wandering wizard, instant client crash

**To Reproduce**
right click wandering wizard, instant client crash

**Screenshots**

**Additional context**
Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/38 (SMerchantOffersPacket) was larger than I expected, found 21210 bytes extral whilst reading packet 38

**Logs**
Nothing in logs on server unfortunately.
versio 1.5.4

**Comment by QcPerreault** [comment]
Same bug for me on version 1.5.3
![wandering-wizard-bug](https://user-images.githubusercontent.com/22948647/111077305-8da93600-84c6-11eb-940d-f55d3c1924cb.PNG)

**Comment by mooproxy** [comment]
Can confirm. Same issue as above. Same error message except it found 21206 bytes rather than 21324. This was on the ATM6 allthemodium server.

**Comment by ladylexxie** [comment]
Not happening anymore in the current version.
