### ISSUE TITLE
My textures are messed up

### ISSUE THREAD

**Issue by GoiabaKun** [AllTheMods/ATM-6#1209]
I have just installed the modpack using Curse Forge.

My textures are all black and purple skins

i Just created a world and this happen

![Screenshot_2](https://user-images.githubusercontent.com/80591359/111035823-edd2a600-83fa-11eb-9ddf-9fc923ee9506.png)

This came with  the modpack too
![Screenshot_3](https://user-images.githubusercontent.com/80591359/111035846-0c38a180-83fb-11eb-9e2f-344f38c258b8.png)

Sorry for my bad english.

**Comment by GoiabaKun** [comment]
almost all vanilla textures , and some mod texture too,

Without Optfine #89

**Comment by whatthedrunk** [comment]
I will need to know what version and need to see a log. My guess is you are missing optiforge or using the wrong version of optifine which work with our packs but we dont do support for.

**Comment by GoiabaKun** [comment]
https://gist.github.com/GoiabaKun/d673da1e9f8b0608cc2f8637d707a0ab

1.5.4b

I made it right? First time here
