### ISSUE TITLE
Can't update to 1.5.4b

### ISSUE THREAD

**Issue by ElldarR** [AllTheMods/ATM-6#1215]
When updating from pack version 1.5.4 to 1.5.4b my Client (Overwolf) keeps telling me it is unable to download/access a specific mod. It is a different mod everytime. This also goes for completely wiping and reinstalling the pack to the client.

**To Reproduce:**
Try to install or update the modpack from 1.5.4 to 1.5.4b.
I am aware it could be my computer specifically (I haven't seen this reported anywhere else) but it seems odd that even when I install it from scratch it does the same thing.

Here is an example of the error message with this time Botany Pots stopping it from installing:

![Skärmklipp 2021-03-14 13 25 47](https://user-images.githubusercontent.com/80627799/111068445-0b6e4100-84c9-11eb-9143-dc2afa91fc13.png)

**Context:**
I did try both updating it to a new profile and then changed my mind when it didn't work and tried updating it to the same profile. Same problem every time.

No logs are provided by the client afaik. Especially since I am unable to install the pack itself, there is nowhere for them to be saved I assume (if there might be ones somewhere else, please let me know).

Update: It also randomly gives me obscure errors such as "Failed to create modpack" or "Failed to get manifest files"

**Comment by ElldarR** [comment]
Ok I got it to work now, simply by trying over and over again. Going to close this issue today unless anyone else comes forward with the samer problem.

**Comment by WhitePhant0m** [comment]
this has nothing to do with our pack, this is entirely on CF
