### ISSUE TITLE
"Cannot connect to server" Except that I can?

### ISSUE THREAD

**Issue by HDgamerzPC** [AllTheMods/ATM-6#1218]
Not sure if this is client-side or server-side as I don't have anyone else to test this with right now. However, even though the server shows as not being online and able to be reached, if I click on it and hit join it lets me connect to the server just fine. I host the server on a VPS which has other things of mine running just fine in addition to another MC server which shows up just fine in the server browser when it's running. Not a big deal it's just me and buddies that'll be playing but just figured I'd throw this out there as I've never seen this problem before anywhere.

https://user-images.githubusercontent.com/15985244/111074345-ea055900-84b8-11eb-9ce0-7fd3c2e57144.mp4

**Comment by Gerdathlete** [comment]
This is a known vanilla Minecraft bug.

**Comment by thevortex** [comment]
Have seen this before where a server is showing as offline due to a server
icon is perhaps the wrong size? Do you have a server icon in your world?

**Comment by HDgamerzPC** [comment]
> This is a known vanilla Minecraft bug.
Gotcha. Haven't seen it before so I figured I'd mention it.



> Have seen this before where a server is showing as offline due to a server icon is perhaps the wrong size? Do you have a server icon in your world?
I do not. This is a fresh install of the server files.

Like I mentioned before no big deal and apparently a known bug in MC. It's not like it's preventing us from having a good time
