### ISSUE TITLE
unable to get addon

### ISSUE THREAD

**Issue by psbilek** [AllTheMods/ATM-6#1219]
**Describe the bug**

**To Reproduce**

**Screenshots**

**Additional context**

**Logs**
Please use a paste site for logs, instead of putting the file directly in the issue, not only is this easier but also means we can view on mobile when we are not at our computers.
Here's a list of some paste sites and their size limits:
    https://pastebin.com/ 512KB
    https://hastebin.com/ 400KB
    https://gist.github.com/ 100MB Requires member (Free)

**Comment by RealDimi** [comment]
Unable to get Addon: Ding (231275) - File ID:3222705

**Comment by starforcraft** [comment]
use a better Launcher.

**Comment by whatthedrunk** [comment]
Yeah this happens sometimes with curseforge. Try restarting your PC and trying to get the newest update or use a different launcher.
