### ISSUE TITLE
Dust smelting has multiple recipes

### ISSUE THREAD

**Issue by BLumbye** [AllTheMods/ATM-6#122]
Dust smelting has multiple recipes with different properties. For example: Smelting gold dust in a blast furnace takes 10 seconds instead of 5 because the custom recipe is overwritten by a recipe from Pedestals. So before adding all the dust smelting recipes the other recipes should be removed (if possible). Currently the custom recipes also don't grant any experience, which some others do.

Screenshot with example: https://imgur.com/ymyCtow

**Comment by WhitePhant0m** [comment]
I'm already removing extra recipes with KubeJS but the removal doesn't work rn.

**Comment by WhitePhant0m** [comment]
It's fixed as of the latest preview versions.
