### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by NE0NIIREAPER** [AllTheMods/ATM-6#1220]
How do I actually download this into my Minecraft.
New to adding mods to my game

**Comment by Exustine12** [comment]
Well so....
i use tlauncher for my mods but u should download the curseforge launcher then click the install button (replaced with download button on normal mod download page) you will click install. IT will ask u to open curseforge launcher (as far as i know) and u will need to follow the other steps.HAVE FUN AND GOOD LUCK @NE0NIIREAPER

**Comment by NE0NIIREAPER** [comment]
Riiight nice thanks
