### ISSUE TITLE
ATM6 1.5.4b Crashing on launch

### ISSUE THREAD

**Issue by TrentRuss** [AllTheMods/ATM-6#1226]
**Describe the bug**
I launch from the launcher and it starts up then closes with error code: 0

**To Reproduce**
Not sure how as not sure the cause.

https://pastebin.com/p3GEgc34

**Comment by jeremiahwinsley** [comment]
Curseforge did not install the pack correctly, reinstall or use a working launcher like MultiMC/GDlauncher.
