### ISSUE TITLE
My textures are messed 2.0 

### ISSUE THREAD

**Issue by GoiabaKun** [AllTheMods/ATM-6#1228]
I have just installed the modpack using Curse Forge.

My textures are all black and purple skins

1 - Create a World

![Screenshot_2](https://user-images.githubusercontent.com/80591359/111180880-32417b80-858c-11eb-903c-0db1e3ca1eb6.png)

Happening with 1.5.4 and 1.5.4.b (only tested with both)

https://gist.github.com/GoiabaKun/2754d7a90338450e19ff517bd141bfc2 - Log

I'm without Optfine and Optforge, if you guys can tell me the right version i will me grateful!

**Comment by jeremiahwinsley** [comment]
Reinstall the pack, likely a CurseForge installation error.
