### ISSUE TITLE
my game keeps crashing

### ISSUE THREAD

**Issue by Jaders2** [AllTheMods/ATM-6#1229]
my game after the last update, it keeps crashing with the server log, and I've tried everything and I couldn't solve it.

log:  https://pastebin.com/WKRqduWC

**Comment by Gerdathlete** [comment]
Have you tried disabling Optifine? The problem seems to stem from Applied Energistics, but whenever I see Optifine on a client I always assume there could be some sort of problem with that.

**Comment by Jaders2** [comment]
yes i already removed the optifine, i also thought it could be. but the error continues

**Comment by Gerdathlete** [comment]
The issue likely stems from Applied Energistics' improper use of client/server references, as its classes seem to be the root of the crash. AE2 also seems to be causing other issues:
Chunks aren't saving in many unloaded chunks and it seems this is also caused by AE2.

> It is caused by appliedenergistics2:8.3.0-alpha.2, rollback to appliedenergistics2:8.3.0-alpha.1
> or wait for next version to come up
> [AppliedEnergistics/Applied-Energistics-2#5069](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/5069)

**Comment by Gerdathlete** [comment]
The version of your pack also seems to be outdated, as it uses alpha.1 instead of alpha.2.

**Comment by Pdiddy973** [comment]
Update to 1.5.6
