### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by 200ians** [AllTheMods/ATM-6#1232]
When i join a server i have 1 fps i rejoin the server not fixed deleted everything and redownloaded it nothing works. i have the rx 570.

**Comment by thevortex** [comment]
go to your video settings and disable mipmaps, i have a radeon 390 and can still get fps in the 40s

**Comment by whatthedrunk** [comment]
Yeah I would disable mipmaps. I get 200fps on a 390x with them disabled. Besides that make sure you have a decent CPU and enough ram allocated.
