### ISSUE TITLE
Server Installation Failure: Problem while installing Forge - java timeout

### ISSUE THREAD

**Issue by JayceStorm** [AllTheMods/ATM-6#1236]
Ran the startserver.bat file and it DL's the mods with no problem.  However, when it tries to DL download forge installer from http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.16.5-36.0.46/forge-1.16.5-36.0.46-installer.jar, I receive an error after 15-20 seconds, "Problem while installing Forge"

**To Reproduce**
1. run startserver.bat
2. wait for error and continual loop to Ctrl + C to close

I tried accessing the same URL in my browser and receive a timeout as well.

Any solutions?

**Comment by whatthedrunk** [comment]
This issue is on Forges end. They have been having issues all day but it seems to be resolved now.
