### ISSUE TITLE
ATM6 Ender hopper Ender tether Dark utilities 

### ISSUE THREAD

**Issue by HydraOfArgolid** [AllTheMods/ATM-6#1241]
ATM6 1.6.5

can’t find the Ender tether or Ender hopper I was wondering if I did something wrong to have those items missing on my server

**Comment by Pdiddy973** [comment]
Ender hopper was disabled due to lag, not sure what the ender teather is.

**Comment by HydraOfArgolid** [comment]
> Ender hopper was disabled due to lag, not sure what the ender teather is.

Is there any way to enable it or is it completely removed

**Comment by Pdiddy973** [comment]
You could, but plenty of other ways to pick up items that don't cause lag, feel free to join the discord and ask around
