### ISSUE TITLE
My world doesn't open.

### ISSUE THREAD

**Issue by mikezeraa** [AllTheMods/ATM-6#1244]
My world doesn't load and always stays on this screen.

Can someone help me?

*I’m Brazilian and I’m using Google Translate. Excuse me if the writing is incorrect.*
![Sem título](https://user-images.githubusercontent.com/80972201/111806456-c3786100-88b0-11eb-83c7-327005c47ab5.png)

**Comment by Jaders2** [comment]
same here

**Comment by Jaders2** [comment]
so I don't know if it's the same reason, but I only managed to enter my world after removing the apotheosis, because I looked at the crash report it seems that the error is related to the charms

Log: https://pastebin.com/iET0HNEk

**Comment by Pdiddy973** [comment]
> so I don't know if it's the same reason, but I only managed to enter my world after removing the apotheosis, because I looked at the crash report it seems that the error is related to the charms
> 
> Log: https://pastebin.com/iET0HNEk

This is likely because alex's mobs was removed, and you had a speed 3 potion.

**Comment by Pdiddy973** [comment]
> My world doesn't load and always stays on this screen.
> 
> Can someone help me?
> 
> *I’m Brazilian and I’m using Google Translate. Excuse me if the writing is incorrect.*
> ![Sem título](https://user-images.githubusercontent.com/80972201/111806456-c3786100-88b0-11eb-83c7-327005c47ab5.png)
> 

Try and update to 1.5.6, if you still have the issues please post a crash log

**Comment by Jaders2** [comment]
> > so I don't know if it's the same reason, but I only managed to enter my world after removing the apotheosis, because I looked at the crash report it seems that the error is related to the charms
> > Log: https://pastebin.com/iET0HNEk
> 
> This is likely because alex's mobs was removed, and you had a speed 3 potion.

it is in fact I had seen in the log something related to the charms, then I removed the apotheosis, and it worked, then I put the apotheosis back and it still works until the moment.

**Comment by tony84727** [comment]
One of the players on my server couldn't log in due to the charms as well. I have a patch for this issue.
https://github.com/tony84727/Apotheosis/commit/d4a7131561eccdb7ed61c5185fd6c58125dfc65b
