### ISSUE TITLE
v1.5.5 Ticking block entity - ElementalCraft

### ISSUE THREAD

**Issue by DevilzEye** [AllTheMods/ATM-6#1246]
**Describe the bug**
Improved Element Binder from ElementalCraft generates a ticking block entity exception.
Normal Element Binder does not cause this error.

**To Reproduce**
1. Place down Improved Element Binder on top of Element Container
2. Revert to 1.5.4b and delete binder
3. update back to 1.5.5 and repeat
4. see crash report

**Screenshots**
- Not needed

**Additional context**
- See notes

**Logs**
https://pastebin.com/5Gsh9CjH

### Notes:
It's the Improved Element Binder from the ElementalCraft mod.
Not sure if it's just me, but thought i'd make other server admins aware.
I reverted back to the main server under 1.5.4b and removed those blocks, then copied the world back to the 1.5.5 beta server and it fired up fine. Although placing the improved binder again crashed the server instantly so i re-copied the world again and all is well. I'm leaving my server under 1.5.4b and keeping the 1.5.5 update under our "Beta" branch until it's fixed.
Just letting the ATM team know

**Comment by Sirttas** [comment]
https://github.com/Sirttas/ElementalCraft/issues/46#issuecomment-803825630
