### ISSUE TITLE
Render Error Crash when opening Mekanism machines connected to any energy pipes

### ISSUE THREAD

**Issue by SweetestPumpkin** [AllTheMods/ATM-6#1249]
When Mekanism machines are connected to pipes that had something connected to them previously, the game crashes.
Checked with: Mekanism Basic universal cable and Energy pipes from Cyclic.

Game Version: 1.16.5
Pack Version: 1.5.5

Crash Log: https://paste.ee/p/GuuqW
Minecraft Log: https://paste.ee/p/b2JcJ

Tried with and without Optifine, both end up crashing.
Tried reinstalling the pack, still crashes.

**Comment by ladylexxie** [comment]
Not happening anymore in the current version.
