### ISSUE TITLE
FluxNetworks & Pipez Mod

### ISSUE THREAD

**Issue by Riggs1965** [AllTheMods/ATM-6#1251]
**Describe the bug**
**Pack Version**
1.5.5
**To Reproduce**
Steps to reproduce the behaviour:
1. place down a flux plug and or point
2. connect to a network
3. add the pipez mod "energy pipe" to any side
4. then the flux plugs won't connect. they also do not provide power

**Screenshots**
![image](https://user-images.githubusercontent.com/44877547/111886236-8dc49c80-89c4-11eb-8de2-467145ac5bfb.png)

**Additional context**
N/A

**Logs**
N/A

**Comment by whatthedrunk** [comment]
If you are still having this issue I would report it to the pipez mod dev but for now you can use an energy cell connected to the plug.
