### ISSUE TITLE
Glowing Chests/Beds, Setting to disable, possible bug?

### ISSUE THREAD

**Issue by S1lentN1ght** [AllTheMods/ATM-6#1252]
Using Newest Pack, 1.5.5

When looking between Northwest and Northeast my chests and bed will glow/highlight.
Is this something in options or hidden settings that I accidently enabled from button / button combo miss-click?
Or could it be a possible bug.
Included Photo
![GlowingChests](https://user-images.githubusercontent.com/59313874/111891470-c1ee8c00-89c9-11eb-8074-dc5af76f3c08.png)
![NonGlowing](https://user-images.githubusercontent.com/59313874/111891477-c74bd680-89c9-11eb-992c-168588973dd6.png)

**Comment by Gerdathlete** [comment]
Looks like a problem with the shaders, which isn't something the mod pack creator has control over.

**Comment by S1lentN1ght** [comment]
Oh I see, then I'll close this, Thankyou
