### ISSUE TITLE
Ore Generation Issues

### ISSUE THREAD

**Issue by hhhhhhhhhhhhhhhhhhhhg** [AllTheMods/ATM-6#1253]
All the ores added by Alltheores seem to spawn much less than required, as in copper seems rarer on Y= 35 than diamond at Y= 12. In addition JEI does not show what Y levels they generate

**Comment by Gerdathlete** [comment]
I haven't had any ore generation issues in my Biomes of Plenty world. What world type are you using?

**Comment by hhhhhhhhhhhhhhhhhhhhg** [comment]
Using Default world, spawns all the biomes you go and BOP terrain. Do you have the JEI issue?

**Comment by thevortex** [comment]
What are the values that you changed in the config?
