### ISSUE TITLE
Glowing Bee has no listed JEI Breeding material/catalyst

### ISSUE THREAD

**Issue by Gerdathlete** [AllTheMods/ATM-6#1254]
When viewing the "Bee Breeding" recipes for glowing bees, there is no material shown:

![image](https://user-images.githubusercontent.com/25123577/111892063-10ddf680-89b5-11eb-9674-83a33b3ddc9c.png)

(ATM Version 1.5.5)

EDIT:

This issue also affects all AllTheMod bees (Allthemodium, Vibranium, and Unobtainium bees)

**Comment by Pdiddy973** [comment]
This is an issue with JEI, join a SP world then back to MP, or use athe beepedia in 1.5.5+
