### ISSUE TITLE
Server Not launching after install on latest

### ISSUE THREAD

**Issue by NxD136** [AllTheMods/ATM-6#1255]
**Describe the bug**
I tried installing the latest server files but it crashes even though at first it says all mods are loaded correctly. View log.

**Screenshots**

**Additional context**

**Logs**
[latest.log](https://github.com/AllTheMods/ATM-6/files/6176866/latest.log)

**Comment by nequa1r** [comment]
my server also will not open on atm6 1.5.5 **IF** i move my old (1.5.1) world over

**Comment by whatthedrunk** [comment]
Updating should be working fine. If your having issues in 1.6.1 let us know.
