### ISSUE TITLE
Chunks not saving causing memory leaks *Unplayable*

### ISSUE THREAD

**Issue by futuristickirito** [AllTheMods/ATM-6#1256]
**Currently unplayable and paying money for a server to play this on with friends**
Updated from Version 1.5.4b to Version 1.5.5
**Describe the bug**
Constant failed to save chunks console spam.
Unloaded areas reloading in an old state. 

**Additional context**
Various server owners are having the same issues.
Only in areas where players built so far
I have deleted the chunks using nbtexplorer and still get same errors.

**Logs**
https://pastebin.com/E6FC8e1T

**Comment by icha-senpai** [comment]
#1247 related to this issue
