### ISSUE TITLE
How do I increase dragon spawn rates in the Other dimension?

### ISSUE THREAD

**Issue by farnoods** [AllTheMods/ATM-6#1257]
I'm currently running the 1.5.3b version of the pack and the dragon spawn rates are just so atrocious. I've spent over 7 real life hours exploring the Other dimension and I've only found 1 dragon. I understand that the dragon spawn rates were increased in version 1.5.4 but I've made too many modifications to the pack already, and upgrading it now would be a pain and not feasible. So, I want to know how I can increase the dragon spawn rates myself. I skimmed through the Ice and Fire config files in the config folder and couldn't find any options to increase dragon spawn rates. I found the spawn values for all Ice and Fire entities in the 'iceandfire-common.toml' file but not dragons.

**Comment by farnoods** [comment]
I think I got it. Need to change dragon roost chance in 'iceandfire-common.toml' to a lower number. Correct me if I'm wrong though. Thanks

**Comment by whatthedrunk** [comment]
Here is an example we did 8 days ago. https://github.com/AllTheMods/ATM-6/commit/04bcbb08bf88161592dc9fc64e4062ceaad0ab0d
