### ISSUE TITLE
Cardboard Boxes permanently delete items 

### ISSUE THREAD

**Issue by SweetestPumpkin** [AllTheMods/ATM-6#1258]
**Describe the bug**
Cardboard boxes when used on blocks or inventory based blocks, and broken, they turn back to default cardboard boxes with no data in them and delete the actual item/block.

**To Reproduce**
1. Use cardboard box on chest with items.
2. Break cardboard box with pickaxe/ any tool / or by hand. 
3. Cardboard box drops, when checked in inventory, displays no data.
4. Try to place the cardboard box back, no item is displayed.
**Screenshots**

**Additional context**

**Logs**
Game Log: https://paste.ee/p/1PWpv

**Comment by ladylexxie** [comment]
This is not an issue anymore.
