### ISSUE TITLE
Question about energy.

### ISSUE THREAD

**Issue by Funnk69** [AllTheMods/ATM-6#1259]
What is that? 
https://youtu.be/j-6omLhYcZU
https://streamable.com/2qrhd3
the cables disappear(when i am pressing RMB), the energy is blocked, nothing receives energy.
I posted this as a question because I don't know exactly if it's a bug or something.
To get everything back to normal I have to restart the game.
I don't know exactly what causes this thing ... I tried to reinstall the modpack + game, but it's the same
Version: 1.5.5

**Comment by Xplodin** [comment]
Are you logged into mojang authentication servers in the top left of minecraft server menu? Sometimes you can get logged out and the fix is to reload or log  back in

**Comment by Funnk69** [comment]
> Are you logged into mojang authentication servers in the top left of minecraft server menu? Sometimes you can get logged out and the fix is to reload or log back in

I am..
