### ISSUE TITLE
enderchests

### ISSUE THREAD

**Issue by Lassendc** [AllTheMods/ATM-6#126]
[https://www.curseforge.com/minecraft/mc-mods/enderchests](https://www.curseforge.com/minecraft/mc-mods/enderchests)
Replace DimStorage whit enderchests

the DimStorage's chest glitches out way to often ( stop accepting adding new and/or pulling items ).
I think this is a result from reloading chunks or server restarts.

Resulting in mob farms etc overflowing

**Comment by Taylor7500** [comment]
Can confirm that between server restarts I've had logistics pipes completely disconnect from a DimStorage chest and refuse to reattach without breaking and replacing everything.

**Comment by Edivad99** [comment]
I fixed the bug https://www.curseforge.com/minecraft/mc-mods/dimstorage/files/3057613

**Comment by WhitePhant0m** [comment]
Mod suggestions should go into #1 and since this bug has been fixed by the dev and the fix is in the pack, I'll close this.
