### ISSUE TITLE
Server crash(probably byg mod)

### ISSUE THREAD

**Issue by mVento3** [AllTheMods/ATM-6#1260]
Modpack version: 1.5.5
MC version: 1.16.5
Operating System: Linux (amd64) version 4.15.0-137-generic
Java Version: 11.0.10, Ubuntu
Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Ubuntu
https://pastebin.com/npV8rDGq

**Comment by thevortex** [comment]
Please use a site like pastebin to submit your crashlog

**Comment by mVento3** [comment]
Changed, sorry, did not notice

**Comment by jeremiahwinsley** [comment]
Fixed in 1.5.7+.
