### ISSUE TITLE
stutter/ micro-freeze

### ISSUE THREAD

**Issue by 11hunter22** [AllTheMods/ATM-6#1262]
(Version 1.5.5)
For some reason I get stuttering/ micro-freezes when playing this modpack. I have really no idea why this is happening as so far it only happens when playing this specific modpack.
I dont use shaders nor a texture pack. I allocated 6144mb of RAM (should be enough?).

**Comment by thevortex** [comment]
Recommend 8gb for your ram, also check on our discord for the java args to
use (type %args )

**Comment by DarkBreaker09** [comment]
I had the same Issue and did try the Java args and have 8gb assigend but still had this stutter/micro freezes.

But i was able to solve this Problem by updatinge Forge (to 36.1.0) and JEI (to 1.16.5-7.6.1.75) and also add Optifne.

I did try just to update Forge and JEI but that didnt change anything.
I also tryed just adding Optifine wich didnt also change anything.

Maybe it helps you too.

**Comment by 11hunter22** [comment]
> I had the same Issue and did try the Java args and have 8gb assigend but still had this stutter/micro freezes.
> 
> But i was able to solve this Problem by updatinge Forge (to 36.1.0) and JEI (to 1.16.5-7.6.1.75) and also add Optifne.
> 
> I did try just to update Forge and JEI but that didnt change anything.
> I also tryed just adding Optifine wich didnt also change anything.
> 
> Maybe it helps you too.

Thanks now its not lagging that much anymore.
