### ISSUE TITLE
Error joining my server - Something with SilentGear I assume

### ISSUE THREAD

**Issue by DMYLI** [AllTheMods/ATM-6#1263]
1.5.4b + 1.5.5 too
**Describe the bug**
This error message after a server crash yesterday.
I am the only one to get this error of all players on the server.
Tried reinstalling MC, Curseforge and the modpack.
Singleplayer works just fine.
https://i.imgur.com/7cnmcgh.png
**To Reproduce**
1. Try to join my server
2. After a short time get the error (https://i.imgur.com/7cnmcgh.png)

**Screenshots**
https://i.imgur.com/7cnmcgh.png
**Additional context**

**Logs**
https://gist.github.com/DMYLI/0833c87fd550d1c1417270317ddf555c
My Username is "Dimmster" if you need it to look it up in the logs.

**Comment by the1upper** [comment]
Multiple people on ATM6 servers having this same issue. Tried removing Silent Gear items from their inventories which did not resolve the issue.

**Comment by gchagan36** [comment]
I'm experiencing the same error. Any update on this?

**Comment by ladylexxie** [comment]
This bug occurred because of a version mismatch, should be fixed now.
