### ISSUE TITLE
furnace and inferium farm randomly stop working

### ISSUE THREAD

**Issue by sebastian191** [AllTheMods/ATM-6#1264]
all the mods 6 version 1.16.5
when i use a portal or go far from home on my server with about 6 friends, when i return my furnace wont smelt anything. my pulveriser and red stone furnace wont do anything if i put the ores in and all my chests in the area are silent. this all souns awful but the worst part is my inferium farm just simply completely stops working. i have no idea whats doing this. this is a legit multiplayer server im paying for and if this happens the only fix is to completely restart the server. if anyone knows how to fix this please let me know asap. thanks in advance

**Comment by Baremeg10** [comment]
Having the same problem. Made an ATM6 server yesterday and having the exact same problems that you describe. Furnace, generator and Mekanism stuff stops working if I logs out and inn. Can get them to work if I move them to a different place, but high probability of strange things happening like doubling things in machines etc. The block position (where machine were located) is having problems until server restart. All machines are working after server restart, but stops working when I log out for a while (and maybe if the chunk is unloaded, not verified).

**Comment by Pdiddy973** [comment]
Update to 1.5.6
