### ISSUE TITLE
Quarzglass uncraftable und missing recipes for diamond and platin jetpacks

### ISSUE THREAD

**Issue by Lolaa135** [AllTheMods/ATM-6#1265]
ATM6 Packversion 1.5.5 Minecraftversion 1.16.5

**Quarz glass crafting not possible**
On Minecraft server. Go to the inventory, use the JEI overlay and search for Quarz glass. Rightclick the Item in the JEI. Quarz glass is not possible to craft. Instead of Glass there is a Empty Tag appliedenergistics2:glass warnsign in the crafting recipe.

![java_pZL4LKdwD9](https://user-images.githubusercontent.com/81189158/112048316-9052fd80-8b4e-11eb-906b-b1b30f9add95.png)

**Diamond & Platinjetpack without crafting recipe**
On Minecraft server. Go to the inventory, use the JEI overlay and search for jetpack. Rightclick the Item in the JEI. The diamond & platin jetpack are without a crafting recipe. Only enchantment and dyeing is possible.

**Started Server (1.5.1 overpatched with 1.5.5)**

Got these Errors:
![java_ZmnA3BfPCE](https://user-images.githubusercontent.com/81189158/112057998-4bcd5f00-8b5a-11eb-83cc-965f2600c721.png)

Error Log from kubejs:

https://gist.github.com/Lolaa135/6c9e05f80e8b9b11a9ed91012b70a311

**Comment by Pdiddy973** [comment]
Seems like you didn't upgrade correctly with all the errors you have, I would try and make a new server then copy the world to the new server, also read the pack upgrade FAQ in the github wiki
