### ISSUE TITLE
Machines Stop Working

### ISSUE THREAD

**Issue by YeastusCrust** [AllTheMods/ATM-6#1266]
This is for version 1.5.5 of All the Mods 6, on a multiplayer server.
Certain machines such as solar powers, batteries, and furnaces simply stop functioning for no observable reason. Attempts to restart the machine by removing its items and putting them back in, or picking up the block and placing it back have not succeeded. Other machines placed in a space where a previously defunct machine was no longer work as well.
Additionally some thermal blocks seem to disappear when this happens. The aforementioned bug happened to a stirling engine and when I tried to pick it up, the engine disappeared. Relogging did not fix this issue.

**Comment by futuristickirito** [comment]
This may be related to the issue with Applied Energistics 2 try going from alpha2 to alpha1

**Comment by Baremeg10** [comment]
Having the same problem. Made an ATM6 server yesterday and having the exact same problems that you describe. Furnace, generator and Mekanism stuff stops working if I logs out and inn. Can get them to work if I move them to a different place, but high probability of strange things happening like doubling things in machines etc. The block position (where machine were located) is having problems until server restart. All machines are working after server restart, but stops working when I log out for a while (and maybe if the chunk is unloaded, not verified).

**Comment by xxDefyGravityxx** [comment]
Can confirm having the same issue on our server using 1.5.5

**Comment by Pdiddy973** [comment]
Update to 1.5.6
