### ISSUE TITLE
Machines problem, FE/RF stuck

### ISSUE THREAD

**Issue by Funnk69** [AllTheMods/ATM-6#1269]
**Describe the bug**
Stucked energy, machines stop working, furnace too...
Generators stopped making energy 
**To Reproduce**
Go to other dimension like nether or end.
Come back into normal world
See stucked energy,machines not working, furnaces too.
But, i don't know exactly if that's making the issue.This is what I suffer when I go to another dimension.

**Screenshots**
https://youtu.be/UppXfo6bZ_0
https://streamable.com/2qrhd3
https://youtu.be/j-6omLhYcZU
**Additional context**

**Logs**
https://gist.github.com/Funnk69/71a214b1f3c0e254e57c24eb6ede7b91

**Comment by Baremeg10** [comment]
Having the same problem. Made an ATM6 server yesterday and having the exact same problems that you describe. Furnace, generator and Mekanism stuff stops working if I logs out and inn. Can get them to work if I move them to a different place, but high probability of strange things happening like doubling things in machines etc. The block position (where machine were located) is having problems until server restart. All machines are working after server restart, but stops working when I log out for a while (and maybe if the chunk is unloaded, not verified).

**Comment by SweetestPumpkin** [comment]
I believe this all because of the latest update of the pack, which messed with the chunkloading. He said hes going to roll out an update for that soon in discord.

**Comment by Pdiddy973** [comment]
Update to 1.5.6 and see if the issue persist
