### ISSUE TITLE
Bluepower Project Table Dupe Bug

### ISSUE THREAD

**Issue by Taylor7500** [AllTheMods/ATM-6#127]
Still on ATM6 0.28a so apologies if this has already been fixed. However the Project Table from BluePower seems to lag behind player input to the point that rapidly putting an item into the crafting grid and removing it from that spot, or putting it into another spot can often cause the item to duplicate.

Gif of this in action attached
![m2LXHaVrlD](https://user-images.githubusercontent.com/3443198/93139724-33771600-f6d9-11ea-94ad-20b9383be42e.gif)

**Comment by WhitePhant0m** [comment]
BluePower won't be in later versions.

**Comment by Firenzeo** [comment]
Shame. Bluepower is one of the most useful ones.

**Comment by oly2o6** [comment]
it will be added in once it has more content, its currently missing alot, and is also buggy which we usually dont mind (with all mods being buggy) but we had to think about pack stability
