### ISSUE TITLE
Entangled with Black hole Tank

### ISSUE THREAD

**Issue by Mortiis87** [AllTheMods/ATM-6#1270]
All the Mods 6 Sky-1.0.4

**Describe the bug**
Using the Entangled Mod to attach it to a black hole tank from Industrial Forgoing. 
Client Crash's on MP servers and world/client on SP. 
Tested the entangled on other blocks with no issue's only happens on Black hole Tank so far.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Use the Entangled on the Black hole Tank
2. Click on the Entangled Block to attach
3. World and client crash 

**Additional context**
Originally found on a server and Currently unable to load the specific chunk the Entangled block is in without crashing client.

**Comment by Pdiddy973** [comment]
Please add the crash report in a https://pastebin.com/
