### ISSUE TITLE
AllTheOres Lead incompatible with Eidolon Mind-Shielding Plate

### ISSUE THREAD

**Issue by mooproxy** [AllTheMods/ATM-6#1271]
ATM6 1.5.5
**Describe the bug**
Eidolon mind-shielding plate cannot be crafted. Only difference between the recipe in JEI and my application is that JEI recommends Eidolon-specific lead ingots whereas I am using AllTheOres lead.

**Comment by ladylexxie** [comment]
Duplicate of #928
