### ISSUE TITLE
Allthemodium Alloy Dust Recipe missing for furnace since 1.5.2

### ISSUE THREAD

**Issue by Gogerto** [AllTheMods/ATM-6#1272]
All Allthemodium Alloy Dust Recipe missing for furnace since 1.5.2
No more Recipe for furnace in since 1.5.2.   (testet 1.5.3 / 1.5.4 / 1.5.4b and 1.5.5 all bugged)

Downgraded to 1.5.2 and it still working correct. Something after this versions misspatched.
Please fix it quickly.

Best Greeting

**Comment by thevortex** [comment]
alloys are created using the dragon forges from ice and fire in atm6, if you are using the mod in your own pack you will need to add recipes for the alloy using kube or crafttweaker if ice and fire is not also loaded

**Comment by Gogerto** [comment]
for what is the dust? Just nothing anymore? And how to find level 5 dragons? mined around 2.000.000 blocks... but no a cave with a dragon in. Integrated somthing and delete a function, before all working well? 

Thats not the good and right way.

**Comment by djnugets** [comment]
there are spefic boimes to check and its how it is intended for this pack

**Comment by djnugets** [comment]
can see the biomes in the pins of the atm6-general channel in the discord

**Comment by Pdiddy973** [comment]
Dust recipes were re added in https://github.com/AllTheMods/ATM-6/pull/1274 ,should be available next update
