### ISSUE TITLE
Server wont start

### ISSUE THREAD

**Issue by Xarano-GIT** [AllTheMods/ATM-6#1275]
OS: Debian 10
Java: openjdk version "11.0.9.1" 2020-11-04
Pack version: 1.5.6

Error: 
```
minecraft@server:~/minecraft/ATM6 - 1.16.5$ ./startserver.sh
Skipping download. Using existing serverstarter-1.2.7.jar
Unrecognized option: -d64
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by Tydesson** [comment]
Most likely related to your java version. Check if you have Java 8 installed.

**Comment by Xarano-GIT** [comment]
> Most likely related to your java version. Check if you have Java 8 installed.

Hi, Debian 10 does not support java 8 as it was depreciated due to security concerns. 

Other mod packs run correctly on java 11, so i suppose i will wait until this pack supports it.

**Comment by Tydesson** [comment]
Also check if you installed 64b version and not the 32b one.

**Comment by Xarano-GIT** [comment]
I definitely have 64bit Debian + 64bit Java 11 installed

**Comment by jeremiahwinsley** [comment]
The pack does run on Java 11, but currently you will have to replace the args in `server-setup-config.yaml` since the provided ones are only compatible with Java 8.

**Comment by Xarano-GIT** [comment]
> The pack does run on Java 11, but currently you will have to replace the args in `server-setup-config.yaml` since the provided ones are only compatible with Java 8. You may need to update the script to remove the -d64 option as well.

Heya, thank you for confirming.

I've managed to get it running on Java 11 by removing the '-d64' arg from `startserver.sh`,

And also the below args from `server-setup-config.yaml` as suggested.
```
-d64
-AggressiveOpts
-UseConcMarkSweepGC
-UseParNewGC
-UseFastAccessorMethods
```
