### ISSUE TITLE
Mending enchant stopped working in recent update

### ISSUE THREAD

**Issue by Jadziyah** [AllTheMods/ATM-6#1278]
Pack version: 1.5.6

Our server is running the current version of ATM6. Today we noticed that the vanilla enchant of Mending is not working anymore. We tested by mining and by tossing bottles of XP at our feet. The items are in our offhands. It was tested on both vanilla armor and modded armor. None of the items are being mended at all- we measured their exact durability level via advanced tooltips. We are simply collecting xp like normal. 

This enchant was definitely previously working in the pack. We're not sure if it was the most recent update or the previous one that changed it.

**Comment by Paper-28** [comment]
Same problem - previously working - after last update not working,

**Comment by KodomoLion** [comment]
Yeah,same happen to me,dont know what cause it,just about to open the issue then saw this

**Comment by djnugets** [comment]
make them indestructible?? 🤷‍♂️

**Comment by klydem11** [comment]
Same Issue here. Spent 3 weeks making a furnace xp farm so I can make big builds, now I'm getting 0 mending hp from the furnance. Although im getting xp

**Comment by KodomoLion** [comment]
I think latest update already fix this bug,at least for me

**Comment by klydem11** [comment]
oh didn't realise there was a new release. Thanks
