### ISSUE TITLE
Silent Gear Bowstring Recipe

### ISSUE THREAD

**Issue by cozmok** [AllTheMods/ATM-6#128]
I apologize for not being familiar with code, but in playing a fresh install of atm 6.0.29 on my ubuntu server, I am unable to craft the silent gear bowstring template or blueprint. I get this entry in my logs:

°14Sep2020 19:06:26.752§ °Worker-Main-5/ERROR§ °KubeJS Server/§: Parsing error loading recipe silentgear:bowstring_blueprint: Shaped recipe ingredient é"type":"silentgear:material","part_type":"silentgear:bowstring"è with key '/' is not a valid ingredient!

In searching for a solution, I only find other log dumps with this same line in it.

Any help is appreciated, thanks.

**Comment by ipryseski** [comment]
I had to update the silentgear and silentlib versions to get the boy string to appear.

**Comment by whatthedrunk** [comment]
We are currently on 1.16.3 so removing older issues to make way for new ones. If you want to test it out join the discord for an early beta. New update will be on Twitch / Curseforge once Mekanism pushes their update to the site.
