### ISSUE TITLE
ATM 6 1.5.6 server won't start

### ISSUE THREAD

**Issue by Beserkerlel** [AllTheMods/ATM-6#1280]
ATM 6 v1.5.6

After updating to 1.5.6 from 1.5.4b server will not start.
Several reinstalls, starting with forge config to delete erroring entities and tile entities, manually redownloading related mods in case corrupted etc.

Map has been through most if not all versions since v1.2.1

https://pastebin.com/djeAeKB0

Any help greatly appreciated.

**Comment by whatthedrunk** [comment]
It's been a while but first I'd try updating to 1.6.1 and if you are still having issues report it to the rats mod dev. Since editing forge.cfg is not working you can also try loading without the rats mod then adding it back or use world edit.
