### ISSUE TITLE
uping spawn rates

### ISSUE THREAD

**Issue by anarchy152** [AllTheMods/ATM-6#1281]
me and some friends are running a server and we are at the point of progression where we need to find dragons, we've gone to the other and when 3000 blocks out to their respective biomes and havent had any luck so we decided to try and increase spawn rates. some digging around in the configs i landed on iceandfire-client.toml which had spawn chancce and distance between dangerous structures so i turned everything up and when i tried to run it again it crashed every time. so i changed it back to original values, same issue. so i reinstalled the pack, basically my question is how do we increase the spawn rates of dragons ect.
ran on version 1.5.3b

**Comment by Pdiddy973** [comment]
Dragon spawn rates have changed alot since 1.5.3b, update to 1.5.6 and reset the other and see how it is

**Comment by anarchy152** [comment]
> Dragon spawn rates have changed alot since 1.5.3b, update to 1.5.6 and reset the other and see how it is

awesome sorry for asking how do we reset the other and update the pack? pretty new to this

**Comment by Pdiddy973** [comment]
Look at the git hub wiki for the update FAQ, to reset the other go to 
"world/dimensions/allthemodium/"
And delete "the_other" folder
