### ISSUE TITLE
client wont start on latest 1.5.6

### ISSUE THREAD

**Issue by bladestonez** [AllTheMods/ATM-6#1282]
**Describe the bug**
when launching the client after updating to 1.5.6 it hangs on Atlas Stitching : minecraft:textures/atlas/beds.png and will not progress into the game.

tried deleting the pack and doing a fresh new install. same result. cannot be played on 1.5.6

**To Reproduce**
open the client, wait.

**Logs**
https://gist.github.com/bladestonez/fe25837e4632fce266cf410ad0a47137

**Comment by Pdiddy973** [comment]
Still having this issue? It usually does this and can take up to 5 mins to fully load
