### ISSUE TITLE
Campfire smoke no longer goes straight up and goes through the side of buildings

### ISSUE THREAD

**Issue by DanCarlyon** [AllTheMods/ATM-6#1283]
Version: 1.5.6

Something within the new version makes campfire smoke flow sideways rather than up which looks  a little weird with the minecolonies buildings that have camp fires inside them

![image](https://user-images.githubusercontent.com/4364774/112465029-227c2100-8d5c-11eb-8647-66ec5a147456.png)
![2021-03-25_11 17 58](https://user-images.githubusercontent.com/4364774/112465054-2a3bc580-8d5c-11eb-8749-5659dff499ef.png)
![image](https://user-images.githubusercontent.com/4364774/112465142-463f6700-8d5c-11eb-8d7e-76d6fce81618.png)

**Comment by KodomoLion** [comment]
I think because the new mod added better chimney or smtg

**Comment by Flipje666** [comment]
This is because of the Advanced Chimneys mod, which makes the smoke affected by wind.
You can edit the adchimneys-client.toml, setting "disableVanillaCampfireSmoke" to false. Not sure if you need to set "emitWithoutChimney" to false as well to fix the rendering, haven't tested much.
