### ISSUE TITLE
Ice and Fire dragons mod

### ISSUE THREAD

**Issue by Camgraham62** [AllTheMods/ATM-6#1287]
I run a modded server with this mod pack, and I been having an Issuee with the Ice and Fire mod pack that nothing spawns in related to the mod pack but i can get it all in creative. Any clue on how to fix?

**Comment by thevortex** [comment]
dragons and other select mobs from the mod spawn in "the other" dimension, thats how we have it configured for this pack

**Comment by Camgraham62** [comment]
Like the nether and the end?

**Comment by rwp140** [comment]
yes its in a separate dimension. The same thing that allows you into the mining dimension, will let you into the "other" dimension, if you place the item in the right dimension.

**Comment by Camgraham62** [comment]
How do we access these other dimensions

**Comment by thevortex** [comment]
place the allthemodium teleport pad in the nether, requires both hands to be empty, sneak right click

**Comment by Camgraham62** [comment]
Thanks for the tip! But how do i get back to the overworld now 😂

**Comment by thevortex** [comment]
a pad should have generated where you appeared in the other dimension same
process to get back, there are also waystones that generate in that world
sometimes, its worth remembering if you get lost there

**Comment by tyrantzero** [comment]
> 
> 
> dragons and other select mobs from the mod spawn in "the other" dimension, thats how we have it configured for this pack

Are Underground Dragon Caves not enabled yet or why cant I seem to find any.... I've checked in Singleplayer with Spectator Mods but haven't seen a single one yet...?
