### ISSUE TITLE
Bedrock Above The End All the Mods 6-1.3.9b

### ISSUE THREAD

**Issue by Draig666** [AllTheMods/ATM-6#1289]
**Describe the bug**
There is bedrock Above the end my version is All the Mods 6-1.3.9b
![2021-03-25_22 14 47](https://user-images.githubusercontent.com/60589169/112576392-ce9f2580-8db7-11eb-84cb-a06e2f0ee2c3.png)
 the bug is.

**To Reproduce**

**Screenshots**

**Additional context**

**Logs**
Please use a paste site for logs, instead of putting the file directly in the issue, not only is this easier but also means we can view on mobile when we are not at our computers.
Here's a list of some paste sites and their size limits:
    https://pastebin.com/ 512KB
    https://hastebin.com/ 400KB
    https://gist.github.com/ 100MB Requires member (Free)

**Comment by Namoku** [comment]
I think you won't receive any response until update your version xD
