### ISSUE TITLE
I can't join my server. (received string length issue)

### ISSUE THREAD

**Issue by brysonrushing** [AllTheMods/ATM-6#129]
I am on 1.0.7 for both the server and the client. Whenever I attempt to join the server, I get the following error:

Internal Exception: io.netty.handler.codec.DecoderException: The received string length is longer than maximum allowed (131 > 128)

The server is running fine, and the client can be played in single player without issue. If someone could explain to me what this means, and what the issue is, I would greatly appreciate it.

Thanks.

**Comment by whatthedrunk** [comment]
We are currently on 1.16.3 so removing older issues to make way for new ones. If you want to test it out join the discord for an early beta. New update will be on Twitch / Curseforge once Mekanism pushes their update to the site.
