### ISSUE TITLE
[1.5.6] Pneumatic Craft causing "java.lang.StackOverflowError"

### ISSUE THREAD

**Issue by tobsa20** [AllTheMods/ATM-6#1290]
In trying to create the refinery in the mod, the blocks do not register to create the refinery and cause a "java.lang.StackOverflowError" and crashes my server.
"Exception in server tick loop"

Crash log:
https://pastebin.pl/view/ff4862a8

**Comment by ahmetkca** [comment]
i also get the same crash when i break the refinery output

**Comment by RubberEyes** [comment]
[crash-2021-04-12_00.51.04-server.txt](https://github.com/AllTheMods/ATM-6/files/6293867/crash-2021-04-12_00.51.04-server.txt)
[crash-2021-04-12_01.04.07-server.txt](https://github.com/AllTheMods/ATM-6/files/6293868/crash-2021-04-12_01.04.07-server.txt)
[crash-2021-04-12_00.40.52-server.txt](https://github.com/AllTheMods/ATM-6/files/6293869/crash-2021-04-12_00.40.52-server.txt)
Have 3 crash reports of this issue
I haven't thoroughly tested it, but using the Pneumatic Wrench to break it (shift + right click) seems to circumvent the issue

**Comment by zmaster587** [comment]
Might have been fixed here https://github.com/TeamPneumatic/pnc-repressurized/issues/777
have not tested it though.

**Comment by whatthedrunk** [comment]
Updated the pack to add the update if you are still having issues let them know in that github. Thanks!
