### ISSUE TITLE
portions of the world refuse to load and cause MASSIVE lag

### ISSUE THREAD

**Issue by InsaneInsomniac** [AllTheMods/ATM-6#1296]
in All the mods 6 v 1.5.6
certain areas of the world, presumably due to loading with glitched items, will refuse to load, and approaching them will progressively increase lag. at a distance of what I assume to be ~10 chunks I get constant waiting on server messages when trying to view blocks, closer and it intermittently loses the ability to even realize I'm looking at a block, further in and I can't interact with blocks or pick up items if they fall on the ground and new chunks near the presumed cause stop loading in entirely, closer yet and mob AI completely fails, actual movement lag begins to occur, and game becomes essentially unplayable. once I identify one of these areas, if I avoid them then the game runs fine...until I run into the next one.
playing on floating islands world, haven't tested yet if that makes a difference.

**To Reproduce**
load game
explore until the game breaks
avoid that area and explore more until the game breaks again

**Screenshots**

**Additional context**
honestly, if it was rare, I wouldn't care about one or two areas I can't go, but I played for ~1 hour and found THREE within a couple hundred blocks of each other near world spawn, and they block all land routes to travel away from world spawn in my floating islands world

**Logs**
unable to correlate my logs due to too many warnings/errors and I'm not sure which actually relate to the issue and what are from things intentionally being turned off/changed for the modpack...seriously, the last log was almost 3MB...can't pastebin that

**Comment by InsaneInsomniac** [comment]
also, I've seen about recommended 8GB memory, I'm giving it 9

**Comment by thevortex** [comment]
We don't need you to figure out the logs, we need you to provide them

**Comment by thevortex** [comment]
Use gist.github.com

**Comment by InsaneInsomniac** [comment]
https://gist.github.com/InsaneInsomniac/7974a9f32c36723389ab0e96d34b764b
there, that's the last log from the sky islands world that had the issue
as a note, I started another world with default world gen and so far no issues, but I haven't explored as much yet since I had a pretty good spawn area, got a couple towns all close together and a desert temple, I haven't finished raiding em all

**Comment by InsaneInsomniac** [comment]
well, I actually got one of the laggy areas to load by just letting the game run for ~30 minutes while I did other stuff, mobs and interactions were still broken, but I noticed a HUGE "lake" of lava, stretching both wide and far beyond the rendered distance, failing to cascade into the void, so maybe thousands of source "blocks" of lava attempting to flow endlessly into the void is the issue? not sure if that's actually the cause or just a coincidence of location, but if that is the cause, the world type should have its worldgen tweaked to prevent these lava oceans from forming at low y level? or failing that just be disabled?

**Comment by PantsWP** [comment]
I actually came across this issue before myself in the overworld and helped another player in the Discord server who had it in the mining dimension. Supplying logs are useless because they don't actually leave any hints, errors or warnings which is why the solution is so hard to narrow down.

Try removing Rats & Ratlantis and restore to a backup to before the problematic chunks were generated. It _should_ fix the issue. Also backup a version of the world that you currently have before removing those mods just in case it is not it.
