### ISSUE TITLE
Adult chicken eye height is set wrong

### ISSUE THREAD

**Issue by theosib** [AllTheMods/ATM-6#1298]
I tried to make a vanilla auto chicken farm, as in the one where you use a dispenser to fire eggs onto a slab, and then then when the chicks grow up, their heads stick into a solid block, and they suffocate. I found that this wasn't working in the atm6 modpack. When I use F3+B, I find that the eye height of adult chickens is actually LOWER than that of the chicks, which is why they don't suffocate. It appears that one of the mods has incorrectly modified the eye height of adult chickens.

(For more info, see my reddit post: https://www.reddit.com/r/allthemods/comments/meemy4/chicken_hitboxes_in_allthemods6/)

**Comment by ladylexxie** [comment]
Not happening in current versions.
