### ISSUE TITLE
Client started crashing on connecting to server 

### ISSUE THREAD

**Issue by pokermanx** [AllTheMods/ATM-6#1299]
v1.5.6
We have **included extra mods**, but everybody is fine except one person which started to crash on every login. Everything was fine for a few weeks until it just started happening. Single player works fine. 
Log: https://pastebin.com/qArxqJDW
Crash Report: https://pastebin.com/TdDreHc7

**Comment by jeremiahwinsley** [comment]
This is a JVM crash, not a pack crash. This usually indicates driver or hardware errors. You can have them test on a different computer to verify.

**Comment by pokermanx** [comment]
Gotcha dude, ty
