### ISSUE TITLE
ResourcealLocationException: Non [a-z0-9/._-] character in path of location: minecraft:ARMOR

### ISSUE THREAD

**Issue by Ahsacul** [AllTheMods/ATM-6#130]
Hey
I have big problem when i update my nitrado server from All the Mods 6 0.26a to 29 with overide the files with the new one.
i start server everthing fin then i wana join and get this error: 

ResourcealLocationException: Non [a-z0-9/._-] character in path of location: minecraft:ARMOR

Pic:
https://ibb.co/kcWRHsC

i need help i dont know which file i need to rename i dont have a ARMOR folder

**Comment by whatthedrunk** [comment]
We are currently on 1.16.3 so removing older issues to make way for new ones. If you want to test it out join the discord for an early beta. New update will be on Twitch / Curseforge once Mekanism pushes their update to the site.
