### ISSUE TITLE
Rats crash

### ISSUE THREAD

**Issue by UldisAlksnis** [AllTheMods/ATM-6#1301]
Server started throwing a lot of pathing errors, after a while it just died generating crash report. A lot of players use the rats mod so killing rats is not a permanent fix..

Server is running ATM 1.5.6 with java 11

**Logs**
crash-log
https://pastebin.com/AcTx2P41
server-log
https://pastebin.com/aWpTwEUB

**Comment by starforcraft** [comment]
Should be fixed in newest Version.
