### ISSUE TITLE
Spectral Eye Amulet not working

### ISSUE THREAD

**Issue by mythilthor20** [AllTheMods/ATM-6#1303]
ATM6 v. 1.5.6
Crafted the Spectral Eye Amulet and when I go to activate it the mobs don't show their green or red outlines at all as if nothing changed. It shows that I have the spectral vision but no effect. Only changes done to mod was add shaders but that shouldn't affect it.

**Comment by Pdiddy973** [comment]
have you tried with out shaders and optifine if you have it?

**Comment by thevortex** [comment]
Shaders definitely cause issues with some mods overlays

**Comment by mythilthor20** [comment]
welp it was indeed the shaders causing the problem optifine still fine but turned off shaders and it works
