### ISSUE TITLE
[1.5.5+] Ores don't generate well.

### ISSUE THREAD

**Issue by Namoku** [AllTheMods/ATM-6#1307]
NOTE: I noticed this bug by discord but I submitted here to have a good control of the issues.
Desc: Ores from all the ores aren't generated like they must.

Create new world in 1.5.5+ and quarry and you'll see copper, osmium, zinc, tin, etc generated like if they were diamond (even less)

Osmium comparison: 
https://i.imgur.com/JjjO32B.png
Iron comparison, same settings:
https://i.imgur.com/lgHBFah.png
Diamond comparison:
https://i.imgur.com/1M2Sg4i.png

**Comment by thevortex** [comment]
https://www.curseforge.com/minecraft/mc-mods/ato/files/3256203 update alltheores and take a look over the configs, if you had tweaked them in the past. 
issue resolved by #1312
