### ISSUE TITLE
Ice and Fire Dragon Cave

### ISSUE THREAD

**Issue by Jake-Baron** [AllTheMods/ATM-6#1308]
Dragon Caves Do not spawn in the Other

So some friends and I play on a hosted server on ATM6, and have yet to find a dragon cave after traveling about 10k blocks out in several directions. When we updated to 1.5.6 we thought the issue would disappear if we removed the other and loaded a new one, but nothing has changed other than surface dragons now spawn.

Is this just that we have been incredibly unlucky?

I have noticed that the dragon nests on the surface tend to spawn on the edge of the biome that they are supposed to spawn on (basalt delta for fire, desert for lightning, mountain for ice), so is that where we should look for them?

I had also read that this was a config issue in earlier versions, so maybe that is what is causing it?

**Comment by thevortex** [comment]
roosts are 2x as likely to spawn as a cave is, and there is a 500 block
separation being enforced for dangerous worldgen(roosts, caves, cyclops,
hydras etc. caves do generate in the proper biomes ,they are rare, but they
do generate.

**Comment by chillpup** [comment]
My friend and I found 1 underground dragon cave after exploring about 50k blocks and several of the proper biomes. They exist, just incredibly rare. Try wearing the charm that shows an outline of mobs if you aren't already.
