### ISSUE TITLE
Frequently crash [1.5.6]

### ISSUE THREAD

**Issue by alexandre-roque** [AllTheMods/ATM-6#1309]
After i updated the modpack, every time i try to enter my world, the Minecraft crashes. I used to play in the 1.5.2 modpack version and updated to the 1.5.6 (i tried the 1.5.7 but it crashed too). I don't have any knowledge about mods and about the crash.

**Logs**
https://pastebin.com/FAWNyUVL (1.5.6 version
https://pastebin.com/CW9Th6PT (1.5.7) version

**Comment by MrSirDolphin** [comment]
Same here, its so annoying

**Comment by alexandre-roque** [comment]
> Same here, its so annoying

I tried to install optifine and the 1.5.7 version worked, but i'm having other problem that the dragons are spawning dead...
