### ISSUE TITLE
Chunk loading banned in singleplayer

### ISSUE THREAD

**Issue by Pinecone53** [AllTheMods/ATM-6#1310]
I'm having an issue in my single player world where I can't chunk load anything. When I try to use the flux point or plug to chunk load i get a message that says "chunk loading is banned on the server"

**Comment by alexandre-roque** [comment]
you can use the force load in the mini map, just claim the chunk and press shift click

**Comment by Pdiddy973** [comment]
Like Alex said, use FTB chunks to chunkload
