### ISSUE TITLE
Replace the RSInfinityBoosterCard mod with Creative Wireless Transmitter

### ISSUE THREAD

**Issue by farnoods** [AllTheMods/ATM-6#1313]
**Is your feature request related to a problem? Please describe.**
The infinity booster card for Refined Storage added by the RSInfinityBoosterCard mod is too simple, it simply increases the range to max int and hence doesn't work cross-dimensionally. It's super annoying

**Describe the solution you'd like**
This mod should be replaced with this new mod called Creative Wireless Transmitter (https://www.curseforge.com/minecraft/mc-mods/creative-wireless-transmitter). I'm not the author of this mod, but I have added it to my own game and did some preliminary testing, it seems to be working pretty well. It's considerably harder to craft than the infinity booster card (based on its default recipe) but works cross-dimensionally

**Describe alternatives you've considered**
Not really any other alternative out there, not that one's needed, the Creative Wireless Transmitter works pretty well

**Additional context**

**Comment by TheNeurotox** [comment]
Take a look at Dimension Card from RSInfinityBoosterCard, I think it does exactly what you want.

**Comment by farnoods** [comment]
Oh I didn't know there was a dimension card, I'll give it a try. Thanks
