### ISSUE TITLE
Missing Cantrip Book from Mana and Artifice

### ISSUE THREAD

**Issue by DarkSage007** [AllTheMods/ATM-6#1314]
In pack version 1.5.7 the Mana and Artifice cantrip book is missing. The recipe is not in JEI or the Codex Arcana, however the Codex still mentions the cantrip book and casting cantrips are still a task to tier up.

edit: this is also present in 1.5.8

**Comment by RobinInSpring** [comment]
Still present in 1.5.10.

**Comment by echohunter221** [comment]
This isn't a pack bug. Mana and Artifice removed the cantrip book and added the functionality to the manaweaving wand and didn't change the entry in their codex. So now the wand you use to draw shapes is also the "book" that you can use with the same hotkey.

**Comment by RobinInSpring** [comment]
Thanks so much for the information. I love the mod pack !!!
Robin
