### ISSUE TITLE
SIMPLE SERVER FILES 1.5.7 JAR FOLDER MISSING

### ISSUE THREAD

**Issue by EonVaridus** [AllTheMods/ATM-6#1318]
Hi i would just like to check, I have downloaded ATM 6 and I'm planning to host a server, however when I downloaded the server pack called "SIMPLE SERVER FILES 1.5.7" the .Jar folder is missing 
Kindly advice me on this matter 

Thanks!

**Comment by Pdiddy973** [comment]
Did you run the batch file? It downloads everything

**Comment by EonVaridus** [comment]
> Did you run the batch file? It downloads everything

Hmm all I get is these files 
![Capture](https://user-images.githubusercontent.com/81774785/113343942-0df2e680-9363-11eb-8605-8dfbd6771bf2.PNG)
