### ISSUE TITLE
Pedestal crash in v1.0.7

### ISSUE THREAD

**Issue by WhiskeyJack96** [AllTheMods/ATM-6#132]
Game crashes due to an issue with pedestal energy networks T_T.

[crash-2020-09-19_16.38.50-server.txt](https://github.com/AllTheMods/ATM-6/files/5250857/crash-2020-09-19_16.38.50-server.txt)

**Comment by whatthedrunk** [comment]
We are currently on 1.16.3 so removing older issues to make way for new ones. If you want to test it out join the discord for an early beta. New update will be on Twitch / Curseforge once Mekanism pushes their update to the site.
