### ISSUE TITLE
Pink Slime wont spawn

### ISSUE THREAD

**Issue by Matt8745** [AllTheMods/ATM-6#1321]
literally haven't played for years so when I placed the bucket of pink slime nothing happened for 30 minutes, I did a bunch of google searches to see if they changed it but I found nothing, someone let me know if this might actually be a bug or it changed.

**Comment by lucasvanhalst** [comment]
you could use the mob slaughter factory, it kills any mob and produces pink slime

**Comment by tyler489** [comment]
Pink slimes no longer exist you need to put pink slime in  the dissolution chamber to get a slime ball now.
