### ISSUE TITLE
Game Crash, Client side Exit code: 0

### ISSUE THREAD

**Issue by jeddell** [AllTheMods/ATM-6#1323]
The bug is I cant load into my world. I shut down one night and the next morning when I open up the game, I walk two or three steps and the game freezes and mine craft crashes with an Exit zero code.

**To Reproduce**
Not sure you can reproduce this error. I have played mod packs for some time and usually when I get to a certain stage of the game play, this happens. I had played a little with the camera mod and I did notice that the latest update had removed this mod. I am currently playing in version 1.5.7

I did have an issue with my RAM but have since fixed the issue and have allocate 12G on the client side in an attempt to load the game. The world still crashed.

I downloaded the world and and loaded it into a single player world to see if I could get it to run without the hassle of any server side issues...Still crashed.  Same exit code zero

So, Its not the amount of RAM. I can only assume that there is something internal to the mod pack. I was just starting out with Resourceful bees Mod if that's any help. I have refined storage up and running fully.  Blood magic completed, Botania completed, Mystical agriculture fully running.

I run my own server and that has 16G RAM allocated with 12 cores.

I went to me earliest back up and that still didn't work.

So it seems that with huge modpacks, you cant get through all the mods after all without some kind of conflict or other.

**Logs**
There are no crash logs from MC Exit code zero doesn't give you any.

**Comment by Pdiddy973** [comment]
Please post the latest logs atleast, exit code 0 usually means it's a ram issue, but if you do have 12 allocated that shouldn't heppen

**Comment by jeddell** [comment]
OK, so I left the server run for a few days and just tried to log on. Here's a snippet of the login. It crashed the server this time around.

https://pastebin.com/xTUbQzS1

The server started up again and I tried logging in again, Same thing happened.

Here's to Log file on the client side:
[latest.log](https://github.com/AllTheMods/ATM-6/files/6253758/latest.log)

AS I watch the terminal load the game, I see a LOT of errors, Particularly in relation to Loot tables. I'm no coder so I'm not sure what I'm looking at.

I also get a constant stream of "Server cant keep up" messages. But get those even on a brand new vanilla server.

**Comment by Pdiddy973** [comment]
see the [Wiki](https://github.com/AllTheMods/ATM-6/wiki/Frequently-Asked-Questions) for that error

"Server cant keep up" means the server cant process fast enough, also why you got that crash
