### ISSUE TITLE
Mod Causing Unwanted Interaction with Resourceful Bees

### ISSUE THREAD

**Issue by desagas** [AllTheMods/ATM-6#1327]
**Describe the bug**
There is a mod in the pack that is causing Resourceful Bees hitboxes to extend beyond where they should, causing them not to pollinate blocks they are meant to pollinate when multiple bees occupy the same space. See image: 
This does not happen in other packs, nor does it happen in their dev environment, which means a mod in this pack and in ATM6Sky is causing this interaction. I am just trying to figure out what mod it is so I can remove it.

**To Reproduce**
Create 1 x 1 x 1 bee box as show in image above. Put in Vanilla bees, they are all confined, hitboxes and all, and can pollinate just fine. Then, remove vanilla bees and add Resourceful Bees, and, they do no pollinate and their hitboxes extend beyond their 1 x 1 x 1 area, causing them not to pollinate. 

**Screenshots**
![2021-04-02_02 27 02](https://user-images.githubusercontent.com/8404632/113428203-9d17f280-9393-11eb-8ed9-6650ac283875.png)
You can see their hitboxes on all of them extending beyond their enclosure, where with Vanilla bees, this does not happen: 
![2021-04-02_02 26 57](https://user-images.githubusercontent.com/8404632/113428682-73ab9680-9394-11eb-9207-147d54dd9dcb.png)

**Additional context**
Again, mod interaction on ATM6 packs, does not occur in some other packs.

I have reported this to Resourceful Bees, https://github.com/Resourceful-Bees/ResourcefulBees/issues/199#issuecomment-812574029, and it is seemingly just a compat issue.

Playing ATM61.5.7 and (ATM6S1.0.5) with Forge 36.1.2 and the Latest Resourceful Bees, the default for the pack version.

**Comment by starforcraft** [comment]
I think thats fixed in newest Version
