### ISSUE TITLE
[1.5.7] Thermal Series Flux Efficiency recipe missing

### ISSUE THREAD

**Issue by Flipje666** [AllTheMods/ATM-6#1328]
ATM6 1.5.7

The recipe for the Flux Efficiency augment from the Thermal Series mod is missing both from JEI and the Thermalpedia (Thermal series' guidebook).

Steps to verify:
1. Go to JEI
2. Search for Flux Efficiency
3. Click the icon in JEI and note no recipe shows up

Alternatively:
1. Craft or /give Thermalpedia
2. go to the page regarding the Flux Efficiency augment, under Augments.
3. Note the recipe isn't showing on the left-hand page, even though there is space allocated for it.

**Additional context**
Have tried this in a fresh SP world on ATM6 1.5.7 to see if it was an upgrade issue.

**Comment by Ug1uk** [comment]
Same issue in Seaopolis. Anyone know if there is a recipe that works that just isn't showing up in JEI and the book?

**Comment by MartinMuzatko** [comment]
same here. About everything else seems to work.

**Comment by ladylexxie** [comment]
It's not fully implemented yet, which is why _they_ didn't add a recipe for it yet.
