### ISSUE TITLE
6.1.0.7 Modular Storage Bug by sorting items

### ISSUE THREAD

**Issue by mod2001** [AllTheMods/ATM-6#133]
Unfortunately I have to use a translator. If you use the sort function in "Modular Storage" (middle mouse button), the "Tier 3 Storage Module" appears to be sorted into itself and disappears.
![2020-09-21_04 39 13](https://user-images.githubusercontent.com/71618713/93729418-ac3c0d80-fbc4-11ea-8021-ae76f532b488.png)
![2020-09-21_04 39 17](https://user-images.githubusercontent.com/71618713/93729420-ae9e6780-fbc4-11ea-8869-d9b9c313a781.png)

**Comment by whatthedrunk** [comment]
We are currently on 1.16.3 so removing older issues to make way for new ones. If you want to test it out join the discord for an early beta. New update will be on Twitch / Curseforge once Mekanism pushes their update to the site.
