### ISSUE TITLE
Crash W/Industrial Foregoing Generator

### ISSUE THREAD

**Issue by avidgamer5918** [AllTheMods/ATM-6#1332]
**Describe the bug**
So it seems to be the machine works fine with fireworks that are made without a firework star work just fine, but if you try to use a firework that was made with a star it crashes.

**To Reproduce**
1. Place down Rocket generator 
2. Insert firework that was made  with a firework star into the generator 
3. Game crashes
**Logs**
https://pastebin.com/BY98BCfk

**Comment by ladylexxie** [comment]
Working fine in the current versions.
