### ISSUE TITLE
Crash w/ Builder from rftools ATM6 ver. 1.5.8

### ISSUE THREAD

**Issue by Darken2k** [AllTheMods/ATM-6#1333]
ATM6 ver. 1.5.8 (i think it's the latest for now)

After utilizing my builder in the Mining dimension, my game crashed.
I went to the Mining dimension from allthemodium, created a 5x5 Reactor from BiggerReactors, it had gold blocks acting as cooling rods, and Uranium as fuel, used mekanism cables to energize the Builder, selected the area to use the Builder as a Quarry, selected all the options to nullify in the filter, got it in, and started the machine. After that, my game crashed, and my world is now unplayable :( 

**To Reproduce**

Go to the mining dimension.
Build a 5x5 reactor from BiggerReactors with gold blocks acting as cooling rods.
Use the builder as an Quarry, get an medium size area for mining, 12 chunks probably or less (can't remember how large it was :p)
Select all normal blocks to filter (stone, dirt, etc)
Start the Reactor, and then the Builder.

Logs:

https://paste.ee/p/3gbQf

**Comment by RogueLogix** [comment]
here is the actual crashing error, https://paste.ee/p/3gbQf#s=0&l=11072, its the builder crashing again, idfk

**Comment by jeremiahwinsley** [comment]
Looks like it's caused by Effortless Building, which is not in the pack by default.
