### ISSUE TITLE
Minecraft crashing+what version of optifine can i use on this modpack

### ISSUE THREAD

**Issue by TheKingOmar** [AllTheMods/ATM-6#1337]
Hey so I am in late game, and after I updated the modpack to the latest version which adds TC the game kept lagging and then the after a while the game crashed I tried relaunching the game, but it didn't work, and then I tried adding optifine, but it just crashed the game before even joining the world
so I wish i someone tells me what the version of optifine I can use without crashing the game
crash log:https://pastebin.com/bGXUQzxi

**Comment by fegkay15** [comment]
Quick fix for me was to disable terrain animations in I believe video settings > animations and then it let me join the world without crashing
