### ISSUE TITLE
Config Files Reverting back to Defaults

### ISSUE THREAD

**Issue by markbrogan13** [AllTheMods/ATM-6#134]
Ive been looking to tweak some default values in the config files server side and upon server start, the configs that I edit are reverted to the originals, Is there a workaround or is there something that I'm missing for this?

**Comment by whatthedrunk** [comment]
Try making a backup of your config changes so when you update you can copy them over before launching. 

We are currently on 1.16.3 so removing older issues to make way for new ones. If you want to test it out join the discord for an early beta. New update will be on Twitch / Curseforge once Mekanism pushes their update to the site.
