### ISSUE TITLE
Chunks dont save and 

### ISSUE THREAD

**Issue by Maiklel** [AllTheMods/ATM-6#1344]
So, we oppened an atm 6 server (hosted) in the 1.5.5 version, and the first hours of gameplay were fine, but after a day things started to work strange. For example, in the house of one of the players, some iron furnaces stopped working, if you taked them and placed again didnt work, but if you cahnged them to another place they did work. This with a server restart was fixed, but it happened again and again after some time, with more frecuency and even with vanilla furnaces.
And now today, after 2 days of oppening the server when me and a friend went to mine, and came back after we ended, some chunks where we mined hd the resources again, also happened harvesting trees and the server started to crash for no reason. This error are random and haven't found a way to provocate them so i can't propperly test.

  I'm not experienced at administrating a modded server hope you can help me.

[crash-2021-04-04_00.29.26-server.txt](https://github.com/AllTheMods/ATM-6/files/6253823/crash-2021-04-04_00.29.26-server.txt)
[crash-2021-04-04_01.19.07-server.txt](https://github.com/AllTheMods/ATM-6/files/6253824/crash-2021-04-04_01.19.07-server.txt)

**Comment by Pdiddy973** [comment]
Update to 1.5.8b, should resolve your issue
