### ISSUE TITLE
Filed to Synchronize Registry Data After Updates on existing LAN Worlds.   

### ISSUE THREAD

**Issue by SWEATYSENIOR** [AllTheMods/ATM-6#1345]
**Describe the bug**
When Playing on a LAN world when we update the pack existing saved worlds give "Failed to Synchronize Registry Data From Server".  Current Pack Version 1.5.8, but this has been happening since 1.4.1.  We have created multiple worlds that this has happened in.  We can create a new world and can connect just fine.  It is only with existing worlds.

**To Reproduce**
1. Update Pack Version
2. Boot world
3. Open to LAN
4. Second computer tries to connect through multiplayer.
5. Second Computer Receives "Failed to Synchronize Registry Data From Server" when connecting.

**Screenshots**

**Additional context**

**Logs**
[Render thread/ERROR]: Server logs don't point to much.  Client log shows the following for each failed connection:
Missing Registry Data for Network Connection
           minecraft.block:  Alexmobs.crocodile_egg
           minecraft.block:  allthemodium:otherportal_block
           minecraft.block:  allthemodium:otherportal_frame_block

**Comment by Flipje666** [comment]
Have also been experiencing the above issue trying to update past 1.5.8. 
Did manage to successfully update to 1.5.8 from 1.5.7 but any update after that gave us the "Failed to Synchronize" on LAN. Reverting also does not alleviate the problem, so we've been rolling back to a backup I make of the world before updating.

Our client-side logs :
[Render thread/ERROR]: Missing registry data for network connection:
	minecraft:block: valkyrielib:cont
	minecraft:block: valkyrielib:slave
	minecraft:block: valkyrielib:test

**Comment by foodyfoood** [comment]
It had happend to me too after I tried to update the world to 1.5.8.

here are my logs:
[latest.log](https://github.com/AllTheMods/ATM-6/files/6265674/latest.log)

**Comment by Flipje666** [comment]
I did some further testing and I did manage to resolve this issue after porting the world into a 1.5.9b server that I host on a separate pc in my LAN. It's not an ideal solution, but at least it's workable for me. 

Thought I'd put it here for those interested 👍
