### ISSUE TITLE
Pedestals mod Upgrade bug??

### ISSUE THREAD

**Issue by NovaUnknown** [AllTheMods/ATM-6#1347]
The problem I am having is using the upgrades on the pedestals from the Pedestals mod.  In the newest update of the pack (1.5.8b) I have tried using the pedestal mod for some automation, I cant get any of the upgrades to go on to the pedestals.  They just keep going into the display slot.  If this is not a bug then I would like some help.

**Comment by DanCarlyon** [comment]
Same for me!
Same version 1.5.8b

No matter what i try it just goes into the display slot, existing ones pre-upgrade still work fine

![image](https://user-images.githubusercontent.com/4364774/113509405-48b87280-954d-11eb-882a-48e3a6d239a0.png)

**Comment by avidgamer5918** [comment]
I believe you have to put the upgrade in your off hand then right click to apply upgrades

**Comment by azertui** [comment]
@avidgamer5918 is right.
Since pedestals 0.8s, the offhand is used to apply upgrades.

**Comment by DanCarlyon** [comment]
OK that worked, thankyou!

Kind of a weird way to apply updates but at least it works 😅
