### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by GWMCwing** [AllTheMods/ATM-6#1349]
Version: both 1.5.5 and 1.5.1 (Singleplayer world) (Spark report on 1.5.5) (Will update to 1.5.8 and try)
-Changed Morph-o-Tool-1.4-27 to Morph-o-Tool-1.4-26 because of crashing when using the Morph-o-Tool from old version

I am having a high FPS and CPU problem when playing in the overworld, and hope someone can help solve the issue and help me read wheat is going on in the spark profile.

World info when creating the spark profile:
- ~15 spawner with spawner agitator on.
- ~5 Botania Spark, Botania Spark is not the main problem as i have reduced the number of spark from 30 to 5 and has no effect on reducing the CPU usage and increasing fps .
- Over 100 hopper bountypot, it is assumed not the main cause of problem as the CPU and fps problem occurred before i place bountypot.
- About 96 1x1 drawers , 32 2x2 drawers, all of them have been moved to compact machine and have no effect on reducing the CPU usage and increasing fps in the overworld.
- 64 Mekanism crystalizer,washer etc. for the ore 4x line, already having issue before placing them

Spec:
CPU: i5-9400f (only Minecraft and discord are running foreground)
RAM: 16GB total (7GB assigned to Minecraft, Minecraft RAM usage below 80%, Computer RAM usage below 90%)
GPU: 1660ti (usage below 40% all the time)
Disk: WD10EZEX-08M2NA0 (usage is below 50% thus it is not the cause of problem)

Spark Profile:
https://spark.lucko.me/8gTcBcZMlU

Further info will be added if needed

**Comment by GWMCwing** [comment]
Sometimes a random crash occurred related to rendering after updating to 1.5.5, dont know if it is related.
Description: Batching chunks
https://paste.ee/p/ZdTgE

**Comment by starforcraft** [comment]
The CPU usage goes higher every hour you play. So restart to get it down again.
