### ISSUE TITLE
Tinkers' Mechworks Drawbridge not working (1.5.8b)

### ISSUE THREAD

**Issue by greggdogg** [AllTheMods/ATM-6#1352]
The "Tinker's Mechworks" Drawbridge doesn't work at all in claimed chunks. Version 1.5.8b

**Comment by avidgamer5918** [comment]
You have to add it as an ally and it will work

**Comment by greggdogg** [comment]
How do you add it as an Ally?Sent from my Galaxy

**Comment by avidgamer5918** [comment]
You go to the ftb chunks menu and then click allys and then add the tinkers mek works its going to have a weird name I don't remember what the name is

**Comment by greggdogg** [comment]
Thanks so much, appreciate itSent from my Galaxy
