### ISSUE TITLE
Ars-Nouveau Wilden Spawning in ATM Mining Dim

### ISSUE THREAD

**Issue by Domiman** [AllTheMods/ATM-6#1353]
After updating from 1.5.7 to 1.5.8b, Wilden and their variations have been spawning non stop inside the ATM mining dimension, even though they are hostile mobs.

**Comment by tyler489** [comment]
I believe this was a bug in ars nouveau as they were spawning in mushroom islands as well. an update to the mod to the newest version should fix it.

**Comment by Domiman** [comment]
I believe this may be a problem with white/blacklisting mobs that are allowed to spawn within the mining dimension, i reported this to the Ars nouveau devs and they said that the Wilden are marked as monsters, so it depends on what ATM uses for the lists.

**Comment by Hazmatik** [comment]
I would say that it has to be a bug in Ars nouveau, because they are spawning in the overworld even when I change the game to peaceful.

**Comment by thevortex** [comment]
should be resolved in next update to ars nouveau, i spoke with the dev on this
