### ISSUE TITLE
[1.5.3+]Squeezer and Drying Basin don't accept item

### ISSUE THREAD

**Issue by NanJack1998** [AllTheMods/ATM-6#1355]
**Describe the bug**
Squeezer and Drying Basin from Integrated Dynamic don't accept items,but the machanical one work fine.

**To Reproduce**
1. Making a Squeezer or a Drying Basin from Integrated Dynamic
2. Holding Menril Log or some other items in JEI recipes and rightclick it
3. Nothing happened

**Screenshots**
https://youtu.be/Fivyv6baRsU

**Additional context**
This situation appears since 1.5.3 either in singleplayer or multiplayer server,i never change any setting about Integrated Dynamic

**Comment by s3ntin3l8** [comment]
Had the same issue. Not sure if it's still there on 1.5.9b. You can go around it by using a hopper to input items into the squeezer.
