### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by giddorah** [AllTheMods/ATM-6#136]
I just got a hard crash to desktop with the following message:

# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000064c8b5dc, pid=35744, tid=58184

This in turn pointed me to a log file written on disk containing a whole lot of information I can't really decrypt.

[hs_err_pid35744.log](https://pastebin.com/Qby0FUVn)

If I'm understanding anything correctly it seems like something happened with Mekanism?

Minecraft 1.16.3 - ATM6 - 0.29

**Comment by whatthedrunk** [comment]
We are currently on 1.16.3 so removing older issues to make way for new ones. If you want to test it out join the discord for an early beta. New update will be on Twitch / Curseforge once Mekanism pushes their update to the site.
