### ISSUE TITLE
All The Mods 6 - v1.5.9b: généré ou accéder à un monde est tout simplement impossible pour la raison suivante ...

### ISSUE THREAD

**Issue by Tweedyzi** [AllTheMods/ATM-6#1362]
I created a server for the occasion with friends I them
updated and it is not possible to go back or even play solo because of this error code.

![bug](https://user-images.githubusercontent.com/30966798/113782278-3f3c2f80-9732-11eb-97ca-c4b90903f929.png)

followed by that : https://pastebin.com/L3JyiLfK

Password : Logs

here are the server logs during connection : https://pastebin.com/7mSc39s9

Password : Update

otherwise the modpack is really cool we have a lot of fun with my friends 💯 👍

**Comment by tyler489** [comment]
Try Removing Optifine

**Comment by Tweedyzi** [comment]
Duplicate of #https://github.com/AllTheMods/ATM-6/issues/1362#issuecomment-814481019
I'm coming to suck you now

**Comment by fegkay15** [comment]
Quick fix for me was to disable terrain animations in I believe video settings > animations
