### ISSUE TITLE
Crude Oil changes to lava when picked up using an Edelwood bucket.

### ISSUE THREAD

**Issue by Hazmatik** [AllTheMods/ATM-6#1365]
**Describe the bug**
When using an Edelwood bucket from Forbidden & Arcanus mod to pick up Crude Oil from Pneumaticraft found in world, you receive an Edelwood Lava Bucket.

**To Reproduce**
1. Use Edelwood bucket to pick up Crude Oil
2. Receive Edelwood Lava Bucket

Pack Version:
ATM 6 Version - 1.5.8b

**Comment by tyler489** [comment]
I'm going to guess this is on forbidden and arcanus assuming the default fluid is lava?

**Comment by ladylexxie** [comment]
This is because of how the bucket is made by the mod creator, nothing we can fix.
