### ISSUE TITLE
Thermal Series Centrifugal Separator Crashes Server When Withdrawing Honey

### ISSUE THREAD

**Issue by StrangeSoul** [AllTheMods/ATM-6#1366]
All The Mods 6 ver. 1.5.8

The title is self-explanatory. Making liquid honey using honeycombs in a centrifugal separator, and then withdrawing it by right-clicking with a glass bottle destroys the server.

1. Get a Thermal Series Centrifugal Separator
2. Feed it at least three honeycombs as bottles are usually 250MB storage and each comb makes 100MB of honey.
3. Get a glass bottle in your main hand and right-click on the separator.
4. Crash.

Logs: 
https://pastebin.com/cUHDBuSr

**Comment by ladylexxie** [comment]
N/A
