### ISSUE TITLE
This modpack will crush when open the world.

### ISSUE THREAD

**Issue by Sunny8523** [AllTheMods/ATM-6#1370]
**To Reproduce**
1. I open this modpack by The New CurseForge.
2. I open the world.
3. freeze game
4. The modpack crush itself

**Comment by chad9900247** [comment]
Hey there I’ve found the fix! All you need to do is go to the bottom left of the curse forge app and click on settings, then go to game specific at the bottom and click on Minecraft. After that, scroll down to Java settings and change the allocated memory to either 6000MB or 8000MB

**Comment by chad9900247** [comment]
If that didn’t work, then it’s probably because you might be enabling shader packs and at the moment that doesn’t allow you to play ALM 6 with shaders so you have to delete the shaderpacks.
