### ISSUE TITLE
Pneumaticcraft aphorism tile crash

### ISSUE THREAD

**Issue by pokermanx** [AllTheMods/ATM-6#1372]
v.1.5.7

Pneumatic craft aphorism tile crashes clients on color change with Alt+chr (was randomly clicking characters so can't say which one exactly. don't want to crash it again, sorry for it being a bit unclear).

crash: https://pastebin.com/QFSPLX3J

**Comment by whatthedrunk** [comment]
We have a new version on 1.6.1 if you are still having issues on that version please report here. https://github.com/TeamPneumatic/pnc-repressurized/issues?q=is%3Aissue+is%3Aclosed thanks!
