### ISSUE TITLE
Game crashes when I try to start a world.

### ISSUE THREAD

**Issue by SoftaTmig** [AllTheMods/ATM-6#1373]
Launching the game is fine. I cannot start a world though. I've played it before and it worked fine but now I create a new world or play an existing save. I get stuck in the loading screen and I'm forced to crash the game...please help

**Comment by chad9900247** [comment]
Hey there I’ve found the fix! All you need to do is go to the bottom left of the curse forge app and click on settings, then go to game specific at the bottom and click on Minecraft. After that, scroll down to Java settings and change the allocated memory to either 6000MB or 8000MB

**Comment by chad9900247** [comment]
If that didn’t work, then it’s probably because you might be enabling shader packs and at the moment that doesn’t allow you to play ALM 6 with shaders so you have to delete the shaderpacks.
