### ISSUE TITLE
[1.5.9b]Pulverizer can't accept osmium ingot

### ISSUE THREAD

**Issue by NanJack1998** [AllTheMods/ATM-6#1374]
**Describe the bug**
Can't put osmium ingot into the pulverizer from thermal,even with pipes.

**To Reproduce**
1. Open  the pulverizer's gui
2. try to put osmium ingot into the slot

**Additional context**
the jei's recipes still shows i can crush the osmium ingot into dust by pulverizer

**Comment by twreid** [comment]
Just to add a bit more info I just updated to version 1.6.0b and this is still an issue.

Looking in JEI or the Pulverizer the recipe it says it accepts is for the Mekanism version of the Osmium ingot, but my ingots are the AllTheOres Ingots

These are the Ingots I have

![Screen Shot 2021-04-16 at 6 40 27 PM](https://user-images.githubusercontent.com/82234/115094487-5c67bf80-9ee3-11eb-864c-8d7eeafe7c58.png)


These are what the pulverizer expects:

![Screen Shot 2021-04-16 at 6 40 48 PM](https://user-images.githubusercontent.com/82234/115094512-773a3400-9ee3-11eb-8e39-f5e3f5b0f860.png)
