### ISSUE TITLE
ATM6 1.5.9b "Can't connect to Server" but you can connect and play

### ISSUE THREAD

**Issue by Tequilaa92** [AllTheMods/ATM-6#1376]
Hey guys, I installed ATM6 1.5.9b on my vServer.
During the installation and at the start, no error is displayed. In the client, however, the message `"Cant connect to server"` is displayed, but you can connect and play. 
Every time you ping the server by clicking on Refresh in the server list, the following error appears in the console: 

> Netty Epoll Server `IO # 9 / ERROR] [minecraft / NettyPacketEncoder]: Error encoding packet
> io.netty.handler.codec.EncoderException: String too big (was 34727 bytes encoded, max 32767)

Rest of the message here: https://pastebin.com/UkmmByDQ 

Does anyone have any ideas how I can solve the bug or problem?

**Comment by K1LLM0NGER** [comment]
I have had this issue since the 1.5.9b release of ATM6.

Cannot confirm the console lines, but the problem has persisted into 1.5.10b. I am unaware of a solution.

**Comment by jeremiahwinsley** [comment]
Delete `world/icon.png` on the server. This is caused by the server icon being larger than 32767 bytes.

**Comment by cha0s** [comment]
This is not the solution. I have the same problem.

There is no such file as `world/icon.png`.

My `server-icon.png` is only 6251 bytes:

```
-rw-rw-r--  1 minecraft minecraft     6251 May 25 07:47 server-icon.png
```
