### ISSUE TITLE
Game crashes Trying to Start a new world

### ISSUE THREAD

**Issue by Kardz2x** [AllTheMods/ATM-6#1377]
Pack version 1.5.9b Game version 1.16.5

Whenever trying to start a new world the game crashes; or rather it just doesnt do anything and force crashes.

I have 32 gigs of ram so its not a ram issue. The world tries to load but gets stuck on a red screen there isnt much of any info 
i can give
[crash-2021-04-09_02.37.38-server.txt](https://github.com/AllTheMods/ATM-6/files/6283697/crash-2021-04-09_02.37.38-server.txt)

**Comment by Kardz2x** [comment]
Forgot to specify This IS ONLY when making a new World

So for people who cant get into a game, you should just be able to load up normal 1.16.5 create a new world then load into forge

**Comment by chad9900247** [comment]
Hey there I’ve found the fix! All you need to do is go to the bottom left of the curse forge app and click on settings, then go to game specific at the bottom and click on Minecraft. After that, scroll down to Java settings and change the allocated memory to either 6000MB or 8000MB

**Comment by chad9900247** [comment]
If that didn’t work, then it’s probably because you might be enabling shader packs and at the moment that doesn’t allow you to play ALM 6 with shaders so you have to delete the shaderpacks.
