### ISSUE TITLE
Minecolonies visual issue

### ISSUE THREAD

**Issue by sparkvantiin** [AllTheMods/ATM-6#1378]
Atm6 1.5.9b dedicated server.

Started a new world and when placing supply camps most of the blocks and building tape are invisible, clicking on an invisible block makes it appear but only to the player that clicked it.  Logging off and logging back in will fix the missing blocks for currently placed buildings but not for new ones.

Single player is fine, no invisible blocks.

Tried reinstalling server, deleted world folder and restarted server.  Also tried version 1.5.8b same thing happens.  

Not sure what's happening but any suggestions would be nice.

**Comment by sparkvantiin** [comment]
![20210409_052822](https://user-images.githubusercontent.com/82208365/114160101-8c67ff00-98f4-11eb-9980-e175fdd5137e.jpg)
Hears a picture of what I'm talking about

**Comment by Braeden101** [comment]
I have this same issue and it usually always fixes the problem when you wander outside of the render distance for the structure (so just walk really far away). A good one or two chunk reloads (F3 + A) while far away wouldn't hurt either.

**Comment by sparkvantiin** [comment]
Updated to 1.5.10b still having an issue blocks not updating when they should, only minecolony blocks seem to be affected.  
Racks wont show items on them until they are opened.  I even have a rack in my warehouse that wont show up at all no matter what I do to it.

**Comment by whatthedrunk** [comment]
Seems fixed in the latest alpha if you want to manually update it. If not post here https://github.com/ldtteam/minecolonies/issues/ thanks!
