### ISSUE TITLE
Game crashes when I try to start my world.

### ISSUE THREAD

**Issue by bruunow** [AllTheMods/ATM-6#1379]
Launching the game is fine. I cannot start a world though. I've played it before and it worked fine but now I create a new world or play an existing save. I get stuck in the loading screen and I'm forced to crash the game...please help

**Comment by Aspyro** [comment]
I have some similar issue.
I launch the game without problem.
But then I launch a world (new or not, same) and it bugs. I'm waiting some more time - more than 5 minutes - then it comes back fine and I can play in my world without problem.

How much time did you wait before crashing it ? It may be exagerated but did you wait once more than 15 min without doing anything ? maybe try that then come back to tell what happens ?

Also I must say that the game doesn't let me Alt+tab to do something else during that time without telling me "do you want to crash the game or wait more ?"

**Comment by bruunow** [comment]
it didn't work to wait the 15 min

**Comment by chad9900247** [comment]
Hey there I’ve found the fix! All you need to do is go to the bottom left of the curse forge app and click on settings, then go to game specific at the bottom and click on Minecraft. After that, scroll down to Java settings and change the allocated memory to either 6000MB or 8000MB

**Comment by chad9900247** [comment]
If that didn’t work, then it’s probably because you might be enabling shader packs and at the moment that doesn’t allow you to play ALM 6 with shaders so you have to delete the shaderpacks.

**Comment by bruunow** [comment]
I already used 10000MB

and i don't have shaders

**Comment by chad9900247** [comment]
Sorry nevermind mine stopped working as well it’s probably a bug that will get fixed soon so all we can do is wait and others also have this issue

**Comment by bruunow** [comment]
thank you anyway

**Comment by rafagp08** [comment]
I'm  with the same problem, you guys have some how fixed it ?

**Comment by whatthedrunk** [comment]
Can't help much with this issue without more info but feel free to join the discord and see if they can help. Type %args to see if those can help you. Also when you launch make sure you keep the window up and not behind everything.
