### ISSUE TITLE
Extreme fps drop when around dungeons (castles) ATM6 v 0.29

### ISSUE THREAD

**Issue by ipryseski** [AllTheMods/ATM-6#138]
When within a chunk with a dungeon we notice a sudden and significant fps drop. In some cases our fps drops to 5 fps. Outside of the dungeon chunk the fps returns. Found we are able to reproduce in single and multiplayer across multiple systems. In rare cases we can purge entities in the chunk and it will help for a moment (1-2 seconds). Other locations it does nothing.

**Comment by whatthedrunk** [comment]
We are currently on 1.16.3 so removing older issues to make way for new ones. If you want to test it out join the discord for an early beta. New update will be on Twitch / Curseforge once Mekanism pushes their update to the site.
