### ISSUE TITLE
Multiblock centrifuge

### ISSUE THREAD

**Issue by MechaMinion** [AllTheMods/ATM-6#1380]
Hi i'm not sure if this is a bug or not but i am playing version 1.5.9b and have recently gotten into bees but have noticed that the lumber honey comb does not get processed in the centrifuge multiblock tier 5

**Comment by Pdiddy973** [comment]
Make sure you have bottles

**Comment by MechaMinion** [comment]
I have the honey outputting straight into a tank which works for all my other bees

**Comment by MechaMinion** [comment]
![2021-04-09_20 00 47](https://user-images.githubusercontent.com/77158022/114228607-96c6df00-996e-11eb-9333-8bacd5970cce.png)

**Comment by Pdiddy973** [comment]
The lumber bee doesn't make honey, it makes apple juice bottles, I plan to change that

**Comment by MechaMinion** [comment]
Ahh that makes sense ok thank you sorry for the trouble
