### ISSUE TITLE
Game crash on startup

### ISSUE THREAD

**Issue by Dorren0** [AllTheMods/ATM-6#1382]
I was trying to start ATM6 and in the Mojang loading screen when it says "mod loading complete" it just freezes and then crashes. I don't even get a crash report it just says "An unexpected issue occurred and the game has crashed. We're sorry for the inconvenience."
"Exit Code: 0"

I have 8GB of RAM allocated to the game but I have tried with both 6GB and 10GB but it does not make a difference. The only additional mod I have installed is optifine.

**Comment by Ki-Tan2934** [comment]
Try a different launcher and make sure the correct java is selected

**Comment by MelanX** [comment]
latest.log would be helpful, too. Crash reports aren’t that important.

**Comment by Dorren0** [comment]
Tank you so much! I tried a different launcher and now it works flawlessly.
