### ISSUE TITLE
Server Lag

### ISSUE THREAD

**Issue by noblackthunder** [AllTheMods/ATM-6#1386]
1. Create a server
2. Rund it for a few hours with at least 2 people in it 
3. suddenly notice lag 
4. Restart the server to resolve lag for 30 minutes to a few hours at best 

**Screenshots**
If applicable, add screenshots to help explain your problem. Added ( there are no usefull logs that point to anything

**Additional context**
Unknown what the issue could be but there are som odd thinks happening when loading the server Like stoping loading while beeing stuck for hours on end on 20% cpu usage without something happening ... Though this seems to be mostly a problem with KubeJS ? 

**Logs**
Please use a paste site for logs, instead of putting the file directly in the issue, not only is this easier but also means we can view on mobile when we are not at our computers.
Here's a list of some paste sites and their size limits:
    https://pastebin.com/ 512KB
    https://hastebin.com/ 400KB
    https://gist.github.com/ 100MB Requires member (Free)
    
    
![image](https://user-images.githubusercontent.com/1668416/114281299-e0322f80-9a3d-11eb-9509-23656bd5cb9f.png)

**Comment by MatthewDVance** [comment]
https://spark.lucko.me/8OQruMuKAJ?hl=149

just profiled for a bit using spark, seems like entity ticking (movement mostly for villagers and animals) has a new twilightforest entry, even in the overworld.

mob movement is extremely jittery when the lag kicks in.

**Comment by noblackthunder** [comment]
> https://spark.lucko.me/8OQruMuKAJ?hl=149
> 
> just profiled for a bit using spark, seems like entity ticking (movement mostly for villagers and animals) has a new twilightforest entry, even in the overworld.
> 
> mob movement is extremely jittery when the lag kicks in.

This sounds correct. Both blocks come back and mobs become very jittery

**Comment by MatthewDVance** [comment]
thought it was my villager trading hall, so went through and manually merged NoAI:1 to the nbt of all villagers, and the twilight forest multi-block checks continued to run unabated.  Did the same to all animals (especially pigs) on my farm, and same result.

rebooted server, and zero issues for several hours, when the issue returned.  however, memory didn't seem to be leaking, so still a little confused, but can only assume it's TF's routines getting stuck for whatever reason.
