### ISSUE TITLE
Server is lagging 

### ISSUE THREAD

**Issue by Crunch743** [AllTheMods/ATM-6#1388]
hey, me and some friends desided that we wann buy a ATM6 server and play fore a few days or so.
my problem is that as soon as we join the server it starts lagging, the server was like 20.000ms behind and we couldn`t play at all.
we updated the server to 1.5.10 and java 11 but nothing helped.

somebody can help me?

**Comment by whatthedrunk** [comment]
You can try to run a spark profile to see what's happening. Or you can press ctrl+u and load crash utilities to see if there are maybe lots of items on the ground or excessive mobs. Without more info that's all I can really help.
