### ISSUE TITLE
java 11 doesn't work on servers.

### ISSUE THREAD

**Issue by Jordan231111** [AllTheMods/ATM-6#1389]
**Describe the bug**
Causes the world to freeze forever.
**To Reproduce**
1. Go to '...'  create a atm server and run it using java 11
2. After playing for a while the server will be non responsive and frozen.

**Screenshots**

**Additional context**

**Logs**
Please use a paste site for logs, instead of putting the file directly in the issue, not only is this easier but also means we can view on mobile when we are not at our computers.
Here's a list of some paste sites and their size limits:
    https://pastebin.com/ 512KB
    https://hastebin.com/ 400KB
    https://gist.github.com/ 100MB Requires member (Free)

**Comment by TheBossManGamer** [comment]
I just switched over to java 11 on the latest build and have not seen this behavior at all. You also did not provide logs to show anything that could help finding your issue. If you could reproduce the issue and attach a log to possibly help with your problem that would be helpful to us helping you

**Comment by s3ntin3l8** [comment]
I'm also using Java 11 on Windows and have not seen any of those problems. Seems to be running the same as with Java 8.

**Comment by Jordan231111** [comment]
Also there is no error in the log. The server just suddenly becomes non responsive. However java 8 is fine and i will just stick with that cuz i dont know what the issue is.
