### ISSUE TITLE
Richards Pickaxe disapear

### ISSUE THREAD

**Issue by Knuckels92** [AllTheMods/ATM-6#139]
Hi,
i killed the special zombie called Richard.

he dropped a special Pickaxe with the enchantment that it place a torch on rightclick at a cost of 4 durability.

So i placed a torch and the Pickaxe disapeared. 
The durability was nearly full.
version 0.29

**Comment by whatthedrunk** [comment]
We are currently on 1.16.3 so removing older issues to make way for new ones. If you want to test it out join the discord for an early beta. New update will be on Twitch / Curseforge once Mekanism pushes their update to the site.
