### ISSUE TITLE
pedestal não funciona

### ISSUE THREAD

**Issue by majormarrento** [AllTheMods/ATM-6#1391]
eu atualizei o modpack e minha geração de energia bugou, eu utilizava forma de geração por lava, e pedestal não esta mais funcionando, eu entrei numa versão antiga e la ta funcionando normal

**Comment by tyler489** [comment]
Is the Pedestal enchanted?

**Comment by majormarrento** [comment]
Sim....e gostaria de saber como consigo fazer soul lava



Em dom, 11 de abr de 2021 03:14, tyler489 ***@***.***>
escreveu:

**Comment by majormarrento** [comment]
Eu coloquei versao mais antiga do mod pedestal e me parece estar funcionando

Em dom, 11 de abr de 2021 08:40, Denis Rodrigues ***@***.***>
escreveu:

**Comment by whatthedrunk** [comment]
seems you fixed it by downgrading but if you have any more issues let the mod dev know here.  https://github.com/Mowmaster/Pedestals/issues
