### ISSUE TITLE
Including Abyss: Chapter 2

### ISSUE THREAD

**Issue by WeedTasteGood** [AllTheMods/ATM-6#1392]
I thought it would be a good mod fits into the pack. I heard that the devs of it have spent 2k hours to make this mod. Personally, I think adding a new, challenging and beautiful dimension would be quite nice for ATM6. Its weapons and armours should also be quite "compatible" with other contents like ice&fire

**Comment by tyler489** [comment]
probably should be in #144

**Comment by WeedTasteGood** [comment]
> probably should be in #144

I am sorry I didn't notice there was post for this. Thanks!
