### ISSUE TITLE
Bigger Reactor changes from 1.5.9b to 1.5.10b?

### ISSUE THREAD

**Issue by CloWnicide** [AllTheMods/ATM-6#1394]
I just updated from .1.5.9b to 10b and my reactor is producing over 20k heat units and going through an immense amount of uranium, while also not even producing nearly as much power as it was. Was there any config that was changed from these two versions? Or am I just gonna have to tear my reactor and turbine down and build them again?

**Comment by CloWnicide** [comment]
Rebuilt the turbine with nothing changes on the issue. And I was wrong on the heat units, its producing almost 50k.

![Screenshot (25)](https://user-images.githubusercontent.com/27911500/114300857-fc05f780-9a76-11eb-8e6e-2285f1fb920f.png)


![Screenshot (24)](https://user-images.githubusercontent.com/27911500/114300855-f6101680-9a76-11eb-9307-2ef2c47308ec.png)

**Comment by RogueLogix** [comment]
Yes, the default config was modified. Use more steam in your turbine and turn your reactor down as necessary

**Comment by CloWnicide** [comment]
I did bump up the flow of the turbine and it was still producing an extreme amount of heat and the efficiency of my turbine plummeted. Even with the control rods in the reactor set to 99% in on all 15 rods was still producing extreme heat and chugging through fuel like a fat kid in a cake factory.

**Comment by RogueLogix** [comment]
You will need to push 10x the steam through your turbine as in previous updates, it will also generate 10x the power as a result. Rotor fluid capacity (used to calculate the efficiency) increases with the RPM.
