### ISSUE TITLE
Resurcefull bees - Vibranium bee

### ISSUE THREAD

**Issue by 4lex0017** [AllTheMods/ATM-6#1396]
All the Mods 6 1.5.10b

Vibranium bees and honeycombs have wrong texture.
Vibranium bees use flower(vibranium block) to drop vibranium bee spawn egg when inventory in apiary is full?

**To Reproduce**
1. Build t3 apiary
2. place vibranium bee in the apiary and put down a vibranium block
3. wait
4. for me the vibranium gets destroyed and a vibraium bee spawn egg drops

**Screenshots**
Screenshot of wrong tecture
![image](https://user-images.githubusercontent.com/68736580/114304161-01446000-9ad2-11eb-8145-d114f6febd15.png)

**Additional context**
P.S. Centrifuge recepiese for ressurcefull bees are still not active?
Aditionaly I saw that there are no breeding recipice for the allthemodium ore bees? are they disabled for now?

**Comment by toast-psb** [comment]
Experiencing the same issue.

**Comment by Namoku** [comment]
Same, also allthemodium, vibranium and unobtainium bees are impossible to craft.

**Comment by s3ntin3l8** [comment]
If I saw it correctly, the recipes for breeding (from other bees, same type of bee still works) were removed and these bees now rely on mutations, although I'm not sure how this works.

**Comment by deamon13666** [comment]
Sorry for my English, Google translator.
Go to the folder in which you have installed ATM 6
Further go \ Config \ ResourceFulbees \ Bees \ Bred \ Bees_ingot
Open the "vibranium.json" file by any text editor and change ("Inputid": "Tag: Forge: Storage_Blocks / Vibranium",)
on ("Inputid": "Tag: Forge: storage_blocks / unobtainium",),
( "OutputID": "resourcefulbees: vibranium_bee_spawn_egg",) to ( "outputID": "resourcefulbees: unobtainium_bee_spawn_egg",) Also change not true test result processing Honeycomb ( "mainOutput": "allthemodium: allthemodium_nugget",) to ( "mainOutput": "Allthemodium: vibranium_nugget",)

**Comment by Pdiddy973** [comment]
Fixed in 1.6.0+
