### ISSUE TITLE
How to setup a server with the simple server file with filezilla

### ISSUE THREAD

**Issue by Crunch743** [AllTheMods/ATM-6#1397]
Im trying to set up a server on a provider where i bought a server, the problem is that when i start the server some modpacks dont work like Immersive enginering (cant place items in maschines and cant start the maschines) or Resourcefull bees (centrifuges dont work)
i don't know why that is, and hopeing that someone can help me

**Comment by Paper-28** [comment]
Hi, read #1383 and #1384 issue
