### ISSUE TITLE
Lost Jetpack craft since last update

### ISSUE THREAD

**Issue by Balula** [AllTheMods/ATM-6#1399]
The server I was playing updated to the latest version and the jetpacks are uncraftables

**Comment by golost2202** [comment]
Yes, i confirm, can't craft 80% of the jetpack available in IronJetpack

**Comment by DPXLord** [comment]
me too

**Comment by skiwi184** [comment]
Here too, cant craft Allthemodium JP, Vibranium JP, Unobtainium JP
Alltogehter with the Ressoursfull Bee Centrifuge Recieps missing

**Comment by skiwi184** [comment]
Here too, cant craft Allthemodium JP, Vibranium JP, Unobtainium JP
Alltogehter with the Ressoursfull Bee Centrifuge Recieps missing.

**Comment by skiwi184** [comment]
Here too, cant craft Allthemodium JP, Vibranium JP, Unobtainium JP
Alltogehter with the Ressoursfull Bee Centrifuge Recieps missing

**Comment by whatthedrunk** [comment]
This has been fixed in dev. 1.6.0 should be out before the weekend fixing a lot of issues due to some cross mod issues that were only found on some OS's.

**Comment by RogueLogix** [comment]
fixed in this commit https://github.com/BiggerSeries/Phosphophyllite/commit/846fdcf77e171983b41675fe48c66945a5593a6e#diff-8db46574c2c5465015251faa1f851ffd277a3992b73d87a6c697866233287f74
related to https://github.com/AllTheMods/ATM-6/issues/1384
new BiR/Phos version on curseforge

**Comment by whatthedrunk** [comment]
Fixed in 1.6.0 that just relased.
