### ISSUE TITLE
Mod Rats...

### ISSUE THREAD

**Issue by benjiben55** [AllTheMods/ATM-6#14]
Hello guys, 

i know there is not a real problem with the mod but i cant play with it.
I hate rats so much, i cant sleep.
But when i remove the mods, some script are not working anymore.
Can you fix it so i can play without the mod.

I whould be very grateful :)

And thanks for the good work .

Sincerely benjiben

**Comment by WhitePhant0m** [comment]
Go into your scripts folder and remove the rats folder, that should allow you to remove the mod.

**Comment by benjiben55** [comment]
hey i removed the mod and the script but when i close the  world nothing is saved. 
I placed some blocks and quit the game and after a loggin in nothing is saved. 
Please help me with this issue.

Thanks :)
