### ISSUE TITLE
[1.5.10b] 2 Logs to 16 Sticks Recipe Yields Only 1 Stick

### ISSUE THREAD

**Issue by SeattleBLACK** [AllTheMods/ATM-6#1400]
![image](https://user-images.githubusercontent.com/80086319/114316083-d4368400-9ab6-11eb-832d-d76072ed5590.png)
Seems like this recipe is bugged.

**Comment by Namoku** [comment]
Yeah, I opened this issue #1306.

**Comment by whatthedrunk** [comment]
Gonna close this and work on the fix soon thanks. Ill keep the other open for now.
