### ISSUE TITLE
[Server] Server hang on startup / restart

### ISSUE THREAD

**Issue by noblackthunder** [AllTheMods/ATM-6#1402]
**Describe the bug**

Server hangs always on the same place when restarting ( this seems to happen for me 95% of the time i restart a server) 

**To Reproduce**
1. Launch server via the easy server tool 
2. Wait until the server started 
3. Restart the server 
4. Always starts to hang while doing sime KubeJs stuff 

**Screenshots**
![image](https://user-images.githubusercontent.com/1668416/114328226-32597a80-9b3c-11eb-8791-5d6959bc7746.png)

**Additional context**
Latest Java 11 JDK has been used / tried for the server 

**Logs**
[debug.log](https://github.com/AllTheMods/ATM-6/files/6293206/debug.log)

**Comment by AdamF0128** [comment]
Similar issue has been occurring for me. Force Stopping server causes a crash but fixes this issue until next restart.

**Comment by starforcraft** [comment]
Java 11 wasn't working back then. Now it should work.
