### ISSUE TITLE
IronFurnaces seems to not be compatible with FastFurnace

### ISSUE THREAD

**Issue by HawaiiLife745** [AllTheMods/ATM-6#1404]
When attempting to use an IronFurnaces upgrade on a vanilla furnace, the furnace does not upgrade and a text message pops up reading: "FastFurnace Mod is loaded, will not upgrade, drop the upgrade on the floor together with one cobblestone to get your materials back."

**Comment by jeremiahwinsley** [comment]
Known issue with FastFurnace, just craft the iron furnace manually.
