### ISSUE TITLE
[1.5.10b] The Other Dimension ores don't drop when mined

### ISSUE THREAD

**Issue by Zargachi** [AllTheMods/ATM-6#1406]
modpack version 1.5.10b

**Describe the bug**
In The Other dimension, all ores that are overworld variants like copper, iron, osmium, can`t be collected, when mined with a normal, fortune or silktouch pickaxes the ore just disappears, on JEI there is none recipe for processing them too.

**To Reproduce**
1. Go to The Other dimension
2. Mine some Overworld variant ores.
3. See error

**Comment by thevortex** [comment]
what pickaxe/tool were you using?

**Comment by Zargachi** [comment]
i tried with vanilla, tinkers and silent gear, if your question is the pickaxe hasvesting level, no, this is not the problem, as i said, not even JEI recognizes those ores, they don't have recipes for processing, like furnace smelting or mekanism processing recipes.

**Comment by thevortex** [comment]
what is the pickaxe harvesting level?

**Comment by Zargachi** [comment]
Ok, my bad, i taked more attention now and tested again, all my pickaxes have miners fervor's or high mining speed, this maded the blocks insta mine or almost, and i don't noticed that the harvest level whas 6, now i changed my pickaxe head to a level 6 and the problem solved, i tested just silent gear paxel, and the ore dropped 3 vanilla ores, i never mined this ore, if this is the normal drop then everything is ok.
