### ISSUE TITLE
[1.5.10b] players kicked due to internal server error

### ISSUE THREAD

**Issue by ostylk** [AllTheMods/ATM-6#1408]
**Describe the bug**
After playing with a large group of friends for more than one week, some are not able to join the server anymore. When joining this stacktrace is thrown in the console: https://pastebin.com/mDtCNrVR
Restarting the server seems to sometimes alleviate this issues for a few hours.

This seems like a rather odd issue as a NullPointerException is thrown in the UpdateTabNamePacket class??

**To Reproduce**
I cannot offer any specific steps to reproduce as we simply played the modpack over the course of one to two weeks.
When first installed the server was on version `1.5.5`, then we upgraded to `1.5.8b` and currently it is on `1.5.10b`.

**Screenshots**
This is seen when attempting to join the server.
![2021-04-12_17_59_34-Window](https://user-images.githubusercontent.com/11543269/114426659-93c02e80-9bba-11eb-83ee-430d5e51f2c6.png)

**Additional context**
`uname -a`
> Linux ftb-atm6 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux

`java -version`

> openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-post-Debian-1deb10u2)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-post-Debian-1deb10u2, mixed mode, sharing)

**Comment by ladylexxie** [comment]
Not happening anymore in the current version. If it persists still, please reopen this.
