### ISSUE TITLE
[1.0.7] Selecting some mods in the mod menu causes a crash

### ISSUE THREAD

**Issue by caseirouowotm8** [AllTheMods/ATM-6#141]
In the mod menu, selecting certain mods will crash the game. Using a fresh modpack install, default settings.

Mods in question:
-Absent By Design Mod;
-Angel Ring;
-Ars Nouveau;
-Compressium;
-Pedestals;
-Shutup Experimental Settings!.

Steps to reproduce:
-Launch game;
-Open the mod menu;
-Select one of the mods listed above;
-Crash.

[Crash Report](https://github.com/AllTheMods/ATM-6/files/5299935/crash-2020-09-29_15.49.01-client.txt)

**Comment by whatthedrunk** [comment]
We are currently on 1.16.3 so removing older issues to make way for new ones. If you want to test it out join the discord for an early beta. New update will be on Twitch / Curseforge once Mekanism pushes their update to the site.
