### ISSUE TITLE
[1.5.9b] Smelting tin blocks in Tinkers' Construct smeltery makes a tin fluid unable to be alloyed

### ISSUE THREAD

**Issue by AzurePineapple** [AllTheMods/ATM-6#1411]
Pack version number [1.5.9b]
**Describe the bug**
Tin blocks and ingots (both Mekanism and Alltheores) create a fluid named fluid.alltheores.molten_tin instead of the corresponding Tinkers' Construct fluid, meaning that you cannot create alloys of tin in the smeltery this way.

**To Reproduce**
Steps to reproduce the behaviour:
1. Use the smeltery to produce tin blocks
2. Melt those tin blocks in the smeltery
3. Fluid created is fluid.alltheores.molten_tin
4. Said fluid does not alloy with copper to create bronze, as intended

**Screenshots**
![image](https://user-images.githubusercontent.com/55160409/114473489-41980100-9bec-11eb-98d2-a7b2ec7ec4e5.png)
![image](https://user-images.githubusercontent.com/55160409/114473512-4a88d280-9bec-11eb-9ffd-3cda75985938.png)

**Comment by tyler489** [comment]
If it can be cast into blocks you can use mekanisms converter to convert it into a different type of tin and smelt that.

**Comment by AzurePineapple** [comment]
All varieties of tin blocks (Mekanism, AllTheOres, and Thermal Series) smelt into the same fluid (fluid.alltheores.molten_tin) and not Tinkers' Construct Molten Tin.

**Comment by AzurePineapple** [comment]
All of the Tin Ores smelt into Tinkers' Construct Molten Tin, though none of the tin blocks do, nor do tin ingots.

**Comment by whatthedrunk** [comment]
Fixed in 1.6.0 that just relased.
