### ISSUE TITLE
ET Miner does not auto-build nor open its GUI

### ISSUE THREAD

**Issue by CloWnicide** [AllTheMods/ATM-6#1412]
Trying to build a tier 1 void ore miner, and it fails to build or open its GUI, and looking at the logs I get this error message. Tried to move over to creative world for testing and same issue.

[06:50:37] [Render thread/WARN]: Failed to create screen for menu type: envirotech:void_miner

Pack Version: 1.5.10b; Forge: 36.1.2; Java 11.0.10.0 64bit

Place controller, try to shift L-click

Log: https://gist.github.com/CloWnicide/b58766cddae055258882a3451fdedc19

Fair warning, log is extremely long from extended play session. Can create new logs in a few hours if needed.

**Comment by ladylexxie** [comment]
Not happening anymore in the current version.
