### ISSUE TITLE
Adding ram to bat file or where?

### ISSUE THREAD

**Issue by NotCskong** [AllTheMods/ATM-6#1416]
I'm running the simple server files (SIMPLE-SERVER-FILES-1.5.10b.zip) version 1.16.5 for ATM 6 and I am trying to figure out where or how I can add more ram to the server since I am hosting it with my PC.

**Comment by Flipje666** [comment]
There's a Discord server for these kinds of questions, and there's a file literally called "server-setup-config" which could be seen as a hint that it has to do with the configuration of your server. 

Github issues are for issues with the code, i.e. bugs, and other things the devs deem appropriate.

**Comment by NotCskong** [comment]
> There's a Discord server for these kinds of questions, and there's a file literally called "server-setup-config" which could be seen as a hint that it has to do with the configuration of your server.
> 
> Github issues are for issues with the code, i.e. bugs, and other things the devs deem appropriate.
Ah I see, still pretty new to this so didn't know what to do but thanks :|

**Comment by Flipje666** [comment]
Yeah sorry for my tone, it's just that it's one of the three files in the zip so it's the first place I'd look and thought it was a little hard to miss 😅 and yeah welcome to github, if you do run into bugs definitely report them here, but for general/gameplay help check the Discord 👍On 13 Apr 2021 20:03, NotCskong ***@***.***> wrote:

There's a Discord server for these kinds of questions, and there's a file literally called "server-setup-config" which could be seen as a hint that it has to do with the configuration of your server.
Github issues are for issues with the code, i.e. bugs, and other things the devs deem appropriate.
Ah I see, still pretty new to this so didn't know what to do but thanks :|
