### ISSUE TITLE
ATM6 server Invalid or corrupt jarfile serverstarter-2.0.1.jar

### ISSUE THREAD

**Issue by ksc4130** [AllTheMods/ATM-6#1419]
When I try to start the server I get this error "Invalid or corrupt jarfile serverstarter-2.0.1.jar". I have deleted the .jar file to allow it to download, and I have tried it on a mac and ubuntu server. Can anyone help?

**Comment by ksc4130** [comment]
Figured it out had to manually download https://github.com/AllTheMods/alltheservers/releases/download/2.0.1/serverstarter-2.0.1.jar. The shell file must of been the issue.

**Comment by josephsmendoza** [comment]
I just encountered this as well. If you have wget it works, but curl doesn't follow redirects by default. The curl command needs `-L` to fix.
