### ISSUE TITLE
Dragon Spawn 1.5.7 

### ISSUE THREAD

**Issue by TheTiltedGuy** [AllTheMods/ATM-6#1420]
I'm having  a little problem on my All The Mods Serv .
I explored like 10000 x 10000 in "The Other" Dimension and i didnt  find a single Dragon .
Do anyone know if there is an issue whis dragon spawn in this version of the modpack ?

(Sry for my terrible english)

**Comment by mikael444** [comment]
nem minerio  esta gerando

**Comment by whatthedrunk** [comment]
They work fine but we increased them even more in 1.6.0 which will be out before the weekend fixing a lot of stuff.
