### ISSUE TITLE
[1.5.10b] Immersive Engineering Crude Blast Furnace wont accept items placed inside spitting them on the ground.

### ISSUE THREAD

**Issue by WhynautTV** [AllTheMods/ATM-6#1421]
When placing iron or charcoal into a crude blast furnace it shows them in the UI but does not process them at all and when exiting the UI spits them on the ground.

**To Reproduce**
1. Make and activate crude blast furnace (bug may or may not be reliant on being in a claimed chunk, but said chunk is mine with no incoming permission requests)
2. Add to blast furnace
3. See error

**Comment by whatthedrunk** [comment]
IE issues should all be fixed in 1.6.0 if not let me know and I'll test more.
