### ISSUE TITLE
1.5.9b - Woot Plate Die is consumed in Multiservo Press

### ISSUE THREAD

**Issue by s3ntin3l8** [AllTheMods/ATM-6#1423]
Recipe for Woot Stygian Iron Plate requires Stygian Iron, Plate Die and the YA hammer. In a crafting grid, the stygian iron ingot is consumed for the iron plate, the hammer and plate die are returned.

When using the recipe in a multiservo press from Thermal, the plate die is consumed.

ATM 6 1.5.9b.

**Comment by ladylexxie** [comment]
N/A
