### ISSUE TITLE
Resourceful Bees - No recipes for processing combs

### ISSUE THREAD

**Issue by valtterilap** [AllTheMods/ATM-6#1427]
Hi,
We are unable to process any combs using a centrifuge. The recipes are missing from the search and there is not a way to make combs to ores. We are running a fresh install 1.5.10b on apex hosting service.

![image](https://user-images.githubusercontent.com/64913858/114781226-1561b900-9d81-11eb-85c3-c01fde1f747c.png)
See the missing centrifuge on the recipe window.

**Comment by thevortex** [comment]
update for Resourcefulbees coming 0.6.7a fixes this
