### ISSUE TITLE
All the Mods 6 Server doens't work

### ISSUE THREAD

**Issue by Bengel01** [AllTheMods/ATM-6#1429]
Hello,
i installed the All the Mods 6 1.16.5 Version on a Nitrado Server. But when my friend and i try to join we get the error message:incomplete set of tags received from server

**Comment by Bengel01** [comment]
[latest.log](https://github.com/AllTheMods/ATM-6/files/6316277/latest.log)

**Comment by whatthedrunk** [comment]
Make sure you are both on 1.6.0. If you are still having an issue I need to see the clients latest.log
