### ISSUE TITLE
all the mods 6-1.0.7

### ISSUE THREAD

**Issue by aliginus** [AllTheMods/ATM-6#143]
to make this version work properly , I had to remove a lot of mods , but after researching the crafting I noticed that some recipes can't be collected (Mekanism and gadgets for mining ) maybe there are more of them , transferring from the mods folder and back should it work to fix the crafting, or does the mod do it ?
and Yes, I deleted the mods (I didn't touch any configs)

**Comment by whatthedrunk** [comment]
We are currently on 1.16.3 so removing older issues to make way for new ones. If you want to test it out join the discord for an early beta. New update will be on Twitch / Curseforge once Mekanism pushes their update to the site.
