### ISSUE TITLE
[1.5.9b] Extracting essence?

### ISSUE THREAD

**Issue by Dorren0** [AllTheMods/ATM-6#1431]
I am trying to figure out how I can extract the essence that I get from the mob crusher. I am trying to get it into an enchantment applicator and right now I am using a Basic Mechanical Pipe that is set to push from the crusher and pull into the applicator. Is there any other pipe I can use or am I just doing it completely wrong?

**Comment by EnzoBenzo1** [comment]
post for help in the atm discord atm6 general
