### ISSUE TITLE
Resourceful Bee Breeding Broken

### ISSUE THREAD

**Issue by ritapia** [AllTheMods/ATM-6#1434]
Update 1.6.0 broke bee breeding.

**Comment by Mint-Lord** [comment]
Have the same problem.
The server command window notes an error, and I grabbed it from the log. It's as follows:

[15Apr2021 20:29:40.291] [Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
java.lang.NullPointerException: null

**Comment by whatthedrunk** [comment]
Downgrade Resourceful Bees and it will fix Breeding and the Centrifuge Tiers mod. Hotfix coming.
