### ISSUE TITLE
Ars Nouveau Spellbook Dyeing Bug (ATM6 Version 1.6.0)

### ISSUE THREAD

**Issue by Aosana** [AllTheMods/ATM-6#1436]
**Describe the bug**

The spellbooks from Ars Nouveau were recently updated to accept dye colors to change their design; however, it seems that a mod incompatibility or some other issue prevents any dye other than white dye from being accepted.

**To Reproduce**
1. Put an Ars Nouveau spellbook (Novice Spell Book, Mage Spell Book, or Archmage Spell Book) in a crafting grid with any dye other than white dye.

**Screenshots**
https://i.imgur.com/ORgEVZL.png

**Comment by ladylexxie** [comment]
Reported to mod devs https://github.com/baileyholl/Ars-Nouveau/issues/341
