### ISSUE TITLE
[1.6.0b] Mystical Fertilizer does not work on any crop

### ISSUE THREAD

**Issue by SeattleBLACK** [AllTheMods/ATM-6#1437]
Steps to reproduce:
Use mystical fertilizer on a crop (tested on wheat and several MA seeds)

**Comment by SeattleBLACK** [comment]
1.0.6b ATM 6 to the sky does not have this issue however the normal pack does.
I have reinstalled java, gdlauncher, atm6 several times

**Comment by PsilentKnight** [comment]
I've encountered this issue as well.  Mystical Fertilizer does not work on any crop.  It does however work to grow grass and flowers by r-clicking on an empty grass block.  Only the crop interaction appears to be broken.  I can confirm that this was a working feature previously; this is a recent break.

**Comment by tylersuggs** [comment]
Still nothing on this?

**Comment by McRibs** [comment]
I had this problem as well. When I looked into it I found out that Pam's harvestcraft is the issue thanks to this issue from their GitHub (https://github.com/BlakeBr0/MysticalAgriculture/issues/328).
A simple fix is editing the config file "pamhc2crops.toml" and set `Enable both for right-click harvesting for crops` to `false`
I tested this with the latest version of 1.6.9

**Comment by ZombieLord98** [comment]
a quick work around if you don't want to go digging through files, put the fertilizer in your off-hand then use it, that is what worked for me.
