### ISSUE TITLE
Pedestals won't break

### ISSUE THREAD

**Issue by Kahadi** [AllTheMods/ATM-6#1439]
**Describe the bug**
In version 1.6.0 of the pack, the newest one I can find, Pedestals from the Pedestal mod are completely unbreakable, even in creative, and automatically duplicate in survival when trying to destroy. Upgrades also cannot be removed from them.

**To Reproduce**
1. Open a world, old or new, creative or survival.
2. Place a Pedestal from the Pedestal mod.
3. Try breaking the Pedestal.
4. Place an upgrade on the Pedestal, then try removing the upgrade.

I have a clip of the issue if needed, but with how simple it is to do, I doubt its needed and I am surprised nobody else has reported it. Unless its just an issue with my download or something, but that would be even weirder.

**Comment by Something-AI** [comment]
yes i have the same bug, but you can remove upgrade, you just need to hold Pedestal upgrade base in your offhand and left click (because they added that or something....).

**Comment by Kipex** [comment]
Same here. 1.6.0b multiplayer. When I break a pedestal it drops one and spawns another to take its place.

**Comment by whatthedrunk** [comment]
If you update the mod he fixed the issue. We will add it to the next update thanks.

**Comment by whatthedrunk** [comment]
For some reason the dev wants you to do special stuff in creative to remove them but in the new build you can at least remove them in survival... Hotfix update out now.
