### ISSUE TITLE
It's raining Dreads

### ISSUE THREAD

**Issue by dead-lock-ed** [AllTheMods/ATM-6#1440]
Went to explore the Other, got greeted by loads of dreads
![2021-04-16_14 52 52](https://user-images.githubusercontent.com/53382462/115028181-dfc5e880-9ec4-11eb-9cdf-2c90dd19cf85.png)
![2021-04-16_14 53 28](https://user-images.githubusercontent.com/53382462/115028195-e18fac00-9ec4-11eb-84d1-ad66d570f83c.png)

**Comment by whatthedrunk** [comment]
You might need to  delete the dim and reload it.... If that does not work please let us know.
