### ISSUE TITLE
Unable to reconnect to server after disconnecting, receive NullPointerException.

### ISSUE THREAD

**Issue by Cadacious** [AllTheMods/ATM-6#1441]
**Describe the bug**
After updating to 1.6.0b, all users of our dev server are impacted by a NullPointerException (screenshow below) upon reconnecting to the server after a successful connection. This issue persist across server restarts and only resolves itself when the user restarts their client. This issue impacts all users of our dev server.

**To Reproduce**
1. Join server with 1.6.0b
2. Disconnect
3. Reconnect to server with 1.6.0b

**Screenshots**
![image](https://user-images.githubusercontent.com/32421665/115055912-fead8600-9e96-11eb-84e5-7c96b287dc86.png)

**Additional context**
Was not present on 1.5.10b or lower.

**Logs**
Server Debug:
https://gist.github.com/Cadacious/762c3e7b7ed8ddee9bce6927066a6cbe

Client log:
https://gist.github.com/Cadacious/0699459fac769303d5301573bcb93803

**Comment by Flipje666** [comment]
Can confirm I am also experiencing this issue, client restart fixes problem but is ofc not a workable long-term solution.

**Comment by DarkEyeDragon** [comment]
Can confirm this does indeed happen. Very annoying and time wasting to have to deal with this

**Comment by Cadacious** [comment]
Added client log with more information.

**Comment by whatthedrunk** [comment]
Issue was found to be Crash Utilities. We will update the mod when the update comes out. https://github.com/Darkere/CrashUtilities/commit/f854cd46e1823bd0828400580539a42d69406609

**Comment by whatthedrunk** [comment]
hotfix pushed for now removing Crash utilities.
