### ISSUE TITLE
[1.6.0b] User does not work in claimed chunks

### ISSUE THREAD

**Issue by SeattleBLACK** [AllTheMods/ATM-6#1442]
**Describe the bug**
When attempting to setup a essence farm using a cyclic user with a supremium watering can, I noticed that claiming the chunks disabled the cyclic user despite having them in my allies list. I am uncertain if this is ftbchunks issue or cyclics issue but obviously there is some sort of compatibility issue here. For now, I am working around this issue using chunky turtles.

**To Reproduce**
Claim a chunk
Setup a Cyclic User
Go to allies and accept invitation from "cyclic.fake_player.user"
Turn on Cyclic User

**Comment by starforcraft** [comment]
Intentional
