### ISSUE TITLE
Bigger Rectors Turbine Version 1.5.10b

### ISSUE THREAD

**Issue by APence-XGEN** [AllTheMods/ATM-6#1443]
**Describe the bug**
Version 1.5.10b
Bigger Reactors turbine multiblock crashes server when turned on without steam.
With steam it doesn't crash however it produces no power.

**To Reproduce**
1. Make any size Bigger Reactors Turbine.
2. Open Turbine Terminal and press the power button.

**Comment by whatthedrunk** [comment]
Is this still an issue with 1.6.0? Last update fixed crashing issues but if you still have one with the new update please post here. https://github.com/BiggerSeries/BiggerReactors/issues
