### ISSUE TITLE
[ATM 1.6.0c] rftools control processors and nodes don't receive or send Redstone signals 

### ISSUE THREAD

**Issue by APence-XGEN** [AllTheMods/ATM-6#1444]
**Describe the bug**
rftools control version 1.5.10b
when a processor is setup to read a redstone signal its never triggered and when its made to send one it doesn't tried multiple different systems looks like everything else works with the processor except redstone.

**Comment by APence-XGEN** [comment]
this also doesn't work in 1.6.0b

**Comment by ladylexxie** [comment]
N/A in the current version.

**Comment by APence-XGEN** [comment]
Just got back to Minecraft not sure why this is closed. currently in 1.8.7 and it still doesn't work.
