### ISSUE TITLE
Mahou Tsukai + chisel and bits config suggestion

### ISSUE THREAD

**Issue by stepsword** [AllTheMods/ATM-6#1445]
Recommend adding this for the durability exchange config as chisel and bits has a bunch of cheap high durability items which can be used for lots of free mana

This goes in mahoutsukai-server.toml

DURABILITY_EXCHANGE_BLACKLIST = ["chiselsandbits:bitsaw_diamond", "chiselsandbits:bitsaw_netherite", "chiselsandbits:chisel_stone", "chiselsandbits:chisel_iron",
"chiselsandbits:chisel_gold", "chiselsandbits:chisel_diamond", "chiselsandbits:chisel_netherite"]

**Comment by whatthedrunk** [comment]
Gonna close this but add it to our discord notes for a future update thanks!
