### ISSUE TITLE
All The Mods 6 1.6.0b Server Crashing During Launch

### ISSUE THREAD

**Issue by BigBroccoli** [AllTheMods/ATM-6#1446]
**Describe the bug**
When I start the server it reaches a certain point then crashes. Before this I had been having troubles logging onto the server receiving "Internal Exception"

**To Reproduce**
1. Go to ServerStarter
2. Click on ServerStarter
3. Scroll down to Just wait for it to start

**Screenshots**

**Additional context**
I have just updated Java to (build 1.8.0_281-b09) Version 8 281. (Probably not needed but) Ryzen 7 2700x 16gb ddr4 1070

**Logs**
https://pastebin.com/qz6e0Zyr

**Comment by jacobjake1** [comment]
I have this issue also, very annoying, only known way to fix is to restart your game....everytime

**Comment by starforcraft** [comment]
Should be fixed in newest Version.
