### ISSUE TITLE
Add $valid_apiary tag to Immersive Engineering Materials

### ISSUE THREAD

**Issue by s3ntin3l8** [AllTheMods/ATM-6#1447]
**Is your feature request related to a problem? Please describe.**
The immersive engineering building materials do not have the $valid_apiary tag and cannot be used to build a resourceful bees apiary. This includes the sheetmetals and the treated wood planks.

I found this out after building a nice old industrial style beekeeping house and when upgrading to an apiary, it didn't validate.
Maybe it is related to e.g. treated wood planks not being part of the vanilla $planks tag.

**Describe the solution you'd like**
Is it possible to add the $valid_apiary tag to the immersive engineering materials.

**Additional context**
Version 1.5.9b, still persists in 1.5.10c

**Comment by Pdiddy973** [comment]
do you have any  specific blocks you would like added? besides the treated wood/sheet metal?

**Comment by Pdiddy973** [comment]
https://github.com/AllTheMods/ATM-6/commit/015f437c0cdcc70c7ef2acec232565418d45e609 added here
