### ISSUE TITLE
Pedestal issue with AllTheMods 6 ..

### ISSUE THREAD

**Issue by CHRISRHODE2004** [AllTheMods/ATM-6#1449]
In the latest version of AllTheMods 6 (1.6.0c), after placing pedestal from the pedestal mod, you can no longer remove it and trying too results in duplicating the item constantly. Going into creative mode to remove it does not work - the item is stuck and cannot be removed.

**Comment by devbence** [comment]
try with the devtool, this is a new addition, to be able to get items from the pedestal (in creative), instead of just breaking it

**Comment by thevortex** [comment]
please petition the mod dev directly to get this exciting new feature rolled back to something usable ;)
