### ISSUE TITLE
AE2 - Cant create ME Crafting Terminal

### ISSUE THREAD

**Issue by gekl00** [AllTheMods/ATM-6#145]
I cant craft a ME Crafting Terminal because the receipt seems broken or something....
![image](https://user-images.githubusercontent.com/43214520/95024949-75ff9300-0686-11eb-9950-e2ab5949bc6a.png)

Im not sure what this is.
![image](https://user-images.githubusercontent.com/43214520/95024965-92033480-0686-11eb-982d-cb12f50fd86a.png)

**Comment by WhitePhant0m** [comment]
Which version, on prev3 it works fine.
If on prev3, try reinstalling the pack.

**Comment by gekl00** [comment]
Sorry missed that info.
Have same issue on both SP and MP

This is what me and 2 friends are running and all of us have same problem.

![image](https://user-images.githubusercontent.com/43214520/95025918-b8789e00-068d-11eb-9784-771d966cdc43.png)

**Comment by WhitePhant0m** [comment]
I recommend getting the preview version that we have in discord, works for 1.0.0+
and it also has more content, and that issue is definitely fixed in those versions.

**Comment by gekl00** [comment]
Oh ok thanks! 

Do we have to restart our world or you think it will work with the one we have now?
We have backups :)

**Comment by gekl00** [comment]
ahh wait now i saw you said it works with 1.0.0+  Thats great :)

**Comment by Cntrldfusion** [comment]
it's probably because the 1.0.7 version replaces the id tag for the vanilla Minecraft with FastWorkbench and that messes up the recipe

**Comment by WhitePhant0m** [comment]
no, it's not that, it was a change to tags i did, but forgot that one recipe

**Comment by WhitePhant0m** [comment]
I'll close this for now, if it is still an issue, feel free to open a new issue.
