### ISSUE TITLE
Additional flowers for draconic bee

### ISSUE THREAD

**Issue by istinkalot** [AllTheMods/ATM-6#1451]
version: atm6 1.6.0c

Request/ problem:
Draconic bees from resource bee requires a vanilla dragon egg which can only be retrieved on first ender dragon kill and the bee itself. Unless you save the first egg to be used with the bee later, there's no other way to replicate more dragon eggs. So if the egg was used before the getting the bee setup, or the egg was in another person possession, there's no other way of getting more dragon egg, hence locking further progression into resource bee.

Solutions:
Either have another way to make more dragon eggs or add another allowable flower for the draconic bee to use

Additional info: I have looked at the resource bee file and the flower is  "tag:misctags:flowers/draconic_flowers", which a quick lookup in game for the tag "draconic_flower" yielded in only the dragon egg showing up, implying that only a dragon egg will work with draconic bee. I tried chorus flower and end crystal with no avail.

**Comment by Pdiddy973** [comment]
you can make more dragon eggs with the bee, or with MA.

**Comment by istinkalot** [comment]
yeah i notice, it seems like the server i'm on is having some config issue with MA recipe, but i see it on single player
