### ISSUE TITLE
Leaving and attempting to rejoin a server causes a java error.

### ISSUE THREAD

**Issue by mooproxy** [AllTheMods/ATM-6#1452]
Version 1.6.0b

To reproduce: Simply leave a server (in this case the ATM6 patreon server) and attempt to rejoin. 

The only fix is to restart your client.

**Comment by xyloquack** [comment]
This happens to me too, so it isn't only a you problem. Hope this gets fixed.

**Comment by whatthedrunk** [comment]
This was fixed in 1.6.0c thanks!
