### ISSUE TITLE
/sethome and /back and /spawn are broken

### ISSUE THREAD

**Issue by OmegaAlpha83** [AllTheMods/ATM-6#1454]
when you try to do /sethome it says you cant add anymore homes event though the server was fresh  just started so i was like let me try and do /home and it says home not found. then / back i teleport to someone and do /back it says teleportation history is empty and when i die says the same thing. then / spawn unless this is intentional when i do / spawn it works the first time but when i do it again it says cant teleport cooldown 6 days and 23 hours. its not actually 6 days but its still weird.

**Comment by Pdiddy973** [comment]
Please look at the FAQ
https://github.com/AllTheMods/ATM-6/wiki/Frequently-Asked-Questions
