### ISSUE TITLE
[ATM6-1.6.0c] Resourceful Bees JEI Flower Info.

### ISSUE THREAD

**Issue by K1LLM0NGER** [AllTheMods/ATM-6#1455]
**Describe the bug**
For most resourceful Bees, JEI flower info is missing on multiplayer. For some reason, booting into a singleplayer world and then rejoining the server fixes the issue.

**To Reproduce**
1. Join multiplayer server
2. View JEI bee info
2b. Only certain bees will have flower info(EX: Magma bee has flower info, diamond bee does not).
3. Disconnect from server
4. Launch singleplayer world
4b. JEI flower info for all bees is correct and working in singleplayer.
5. Rejoin multiplayer server
6. JEI info for all bees is now fixed.

**Screenshots**
JEI for diamond bee when on server:
![Server - 1](https://user-images.githubusercontent.com/82349905/115126601-14997480-9f85-11eb-84e6-8d87efdc2d66.png)
JEI for diamond bee when in singleplayer:
![Singleplayer](https://user-images.githubusercontent.com/82349905/115126636-51fe0200-9f85-11eb-9277-474f755c4066.png)
JEI for diamond bee after loading singleplayer world and rejoining server:
![Server - 2](https://user-images.githubusercontent.com/82349905/115126649-6fcb6700-9f85-11eb-871f-b1ce1c01ba1d.png)

**Logs**
I assumed this was a client error and not a server error. client log:
[Paste Bin](https://pastebin.com/jHZQKKk5)

**Comment by Pdiddy973** [comment]
This is fixed in the latest RBees version
