### ISSUE TITLE
1.6.0c Villagers not turning into fletching villagers with fletching table

### ISSUE THREAD

**Issue by NoMoreStars** [AllTheMods/ATM-6#1456]
**Describe the bug**
Villagers cannot change into fletching villagers due to refusing to interact with nearby fletching tables. This doesn't happen with other work station types, including modded ones like Mana and Artifice's runeforge for example.

**To Reproduce**
1. Obtain a fletching table
2. Find a villager of any profession besides nitwits
3. Remove profession if applicable
4. Place fletching table nearby where it is easily accessible by the villager.

**Comment by Pdiddy973** [comment]
This is a known issue, waiting on apotheosis to release an update to fix it
