### ISSUE TITLE
 Unable to create Quantum Entangled Singularity

### ISSUE THREAD

**Issue by Blockerson** [AllTheMods/ATM-6#1457]
Hi!

I think the pack is 1.6.0c and I am not able to create Quantum Entangled Singularity with Ender Pearl Dust and a Singularity using a TNT explosion. I am asking a question instead of reporting a bug because I am not sure whether I am just doing the process wrong or if it is really a bug.

I have tried hundreds of blocks away from my base/spawn, in the mining dimension, etc. and nothing. Where am I going wrong???

**Comment by Pdiddy973** [comment]
Make sure you use the AE ender dust

**Comment by Blockerson** [comment]
Thanks! Didn't see that option in JEI but looks like I can make it with the Quartz Grindstone
