### ISSUE TITLE
1.16.5-AllTheMods6 - Tinkers Crafting Station UI fighting.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [AllTheMods/ATM-6#1458]
**Describe the bug**
![Pm5lRqf 1](https://user-images.githubusercontent.com/10351221/115130322-8ccb5e80-9fb4-11eb-8d91-299e3933da64.png)

**To Reproduce**
1. Make a Tinkerers Workbench
2. Place it next to a chest
3. Open Inventory
4. See GUI glitches

**Screenshots**
![Pm5lRqf 1](https://user-images.githubusercontent.com/10351221/115130394-18dd8600-9fb5-11eb-99b8-76d0d6d1d8c2.png)

**Additional context**
Should be fixable with some config modifcation.

**Comment by whatthedrunk** [comment]
Fixed in dev. Next update use the keybind.
