### ISSUE TITLE
ATM 1.6.0c Multiplayer Tinker's smeltery producing wrong metals

### ISSUE THREAD

**Issue by zhongjiedong** [AllTheMods/ATM-6#1459]
**Describe the bug**
ATM 1.6.0c

Molten metal in smeltery is outputting the wrong metals. Ingot cast produces a gold ingot and casting basin produces a bronze block no matter what the molten metal in the smeltery is

**To Reproduce**
1. Put any metal in your smeltery
2. output it to a casting table with ingot cast
3. Observe it giving you a gold ingot instead

1. Put any metal in your smeltery
2. output it to a casting basin
3. Observe it giving you a bronze block from Mekanism instead

**Screenshots**

https://giant.gfycat.com/TanSneakyAcaciarat.mp4

**Additional context**

This is a multiplayer server if that makes any difference

**Comment by lancepioch** [comment]
Interesting, just tried it out on my server with the latest (same) version and it works fine.

**Comment by zhongjiedong** [comment]
Looks like it was just an issue with the server, server admin tweaked a few things and were good now
