### ISSUE TITLE
Watering can no longer works when right clicking directly on a plant

### ISSUE THREAD

**Issue by xyloquack** [AllTheMods/ATM-6#1460]
All The Mods 6 Version 1.6.0b
Description:
This bug happens with the Mystical Agriculture watering can when using it directly on a plant. Using the watering can on an adjacent block still does its function on the surrounding plants but when using it while right clicking on the plant it doesn't work. I can not confirm if this happens with the higher tier watering cans from Infernium and up. I know that it works with the base watering can.

1. Grab a Mystical agriculture watering can (definitely the base watering can but higher tier watering cans may still work)
2. Use it directly on the plant and you will see the particles disappear and the plant will no longer quickly grow.

Screenshots
![2021-04-17_18 54 40](https://user-images.githubusercontent.com/82739955/115131640-7de1ad80-9fae-11eb-964a-812d46db28e3.png)
![2021-04-17_18 54 43](https://user-images.githubusercontent.com/82739955/115131641-80440780-9fae-11eb-8bf3-87b975d7cfeb.png)
(still right clicking) It isn't only that the particles stop appearing but the effect of it growing quicker it also gone.

I was playing the modpack the day before the update and clicking directly on plants was working. The watering can doesn't work with Mystical Agriculture plants, vanilla plants, saplings, or any other plants I have tested on.

**Comment by Number1PiratePan** [comment]
I am also having this issue on the same version, its been rough without being able to water the crops directly.  Hope this fixes soon

**Comment by bloodscon** [comment]
not just affecting Mystical water can thermal one is affect to :(

**Comment by DevilMayCryIfrit** [comment]
I don't believe it is a bug since you have a off hand. Just put the watering can in you off hand and use it that way. That is what I do but I find it is slower than I hoped just the same with it.

**Comment by BovineShaman** [comment]
Watering can works fine in offhand and also by watering nearby blocks. Right clicking the plant isn't a thing that we can fix.
