### ISSUE TITLE
Create Custom Crafting Broken - 1.0.7

### ISSUE THREAD

**Issue by Merthew** [AllTheMods/ATM-6#1461]
**Describe the bug**
Tried crafting a Create Furnace engine, got reliquary storm shot.

**To Reproduce**
![image](https://user-images.githubusercontent.com/23420800/115135643-f022b400-9fe7-11eb-80d2-cbf7b7675d99.png)
Had my setup like this since the furnace recipe is only a 3x3 but I needed the star shape for the ATM star.
Put in the ingredients for a furnace engine: 
![image](https://user-images.githubusercontent.com/23420800/115135685-3aa43080-9fe8-11eb-91d7-00f9f5709be4.png)
Then got storm shot:
![image](https://user-images.githubusercontent.com/23420800/115135692-4e4f9700-9fe8-11eb-98c7-8be106c518dd.png)

**Additional context**
Playing on 1.0.7, not had really any other big bugs so far, besides Bee mutations not working in the slightest.

**Logs**
No crash so not sure what to tell you here.

**Comment by Pdiddy973** [comment]
if you are on mod pack version 1.0.7 you need to update

**Comment by Merthew** [comment]
> if you are on mod pack version 1.0.7 you need to update

There isn't any update available?
![image](https://user-images.githubusercontent.com/23420800/115162934-53f2be80-a074-11eb-8bcd-6e014680cec4.png)

**Comment by Merthew** [comment]
I think there is supposed to be a 1.0.6c update but that isn't showing up on curseforge yet

**Comment by Pdiddy973** [comment]
oh, this is for ATM6, not ATM6 sky... that said either should work fine, they both use the same recipes

**Comment by Merthew** [comment]
> oh, this is for ATM6, not ATM6 sky... that said either should work fine, they both use the same recipes

Problem, it didn't work fine, I can't get furnace engines from create crafting and I haven't tested any others cause I don't want to waste the resources.

**Comment by whatthedrunk** [comment]
If you are still having issues on the newest post it to the correct place here. https://github.com/AllTheMods/atm6-sky
