### ISSUE TITLE
[ATM6 - 1.6.0b] Bug in JEI with redstone bees

### ISSUE THREAD

**Issue by golost2202** [AllTheMods/ATM-6#1462]
**Description :**

ATM6 1.6.0b

The recipe for breeding a redstone bee is incorrect in JEI. I don't know if there is some other bee having this issue.
Even if the recipe is incorrect you can make one by giving 3 glowstone to a glowing bee and 3 industrial hamp fiber to a stoned bee.

**To Reproduce**

1. Go to JEI and search the redstone bee
2. Left click on her and select the bee breeding tab
3. You will see the recipe is not showing correctly

**Screenshots**

![bee](https://user-images.githubusercontent.com/50000521/115142856-39a0ec80-a044-11eb-9325-17d6d9739877.png)

**Additional context**

I'm playing on my own hosted server

**Comment by Pdiddy973** [comment]
should be fixed in newest version of RBees, or join singleplayer then back to multiplayer
