### ISSUE TITLE
Problem entering server after 1.6.0c update

### ISSUE THREAD

**Issue by nenec0** [AllTheMods/ATM-6#1463]
I was playing the modpack on a local server with my friend, as soon as we updated the modpack, he was unable to enter but on the server, I backed up the maps so there would be no problem, but it was still a problem, so we changed the version, this problem
![Screenshot_1](https://user-images.githubusercontent.com/82776131/115158372-361d5d80-a064-11eb-9ff0-acbba6d128fb.png)

**Comment by whatthedrunk** [comment]
We would need to see some kind of client log and server log to be able to help. It's likely the server or client is on the wrong version or not all the files were copied over.

**Comment by nenec0** [comment]
so as i said i open the map for lan and he plays with me there in case i need to send a log of my minecraft?
