### ISSUE TITLE
 [ATM6 - 1.6.0c] Aquamarine Essence doesn't craft into aquamarines

### ISSUE THREAD

**Issue by Aneduna** [AllTheMods/ATM-6#1464]
**Describe the bug**
After crafting Aquamarine Seeds from Mystical Agriculture, you get Aquamarine Essence.
Usually with Essence, you get the possibility of using that Essence to craft some kind of material.
For example with Redstone Essence, you can craft Redstone. 8 Redstone Essence -> 12 Redstone, or  8 Iron Essence -> 6 Iron Ingot.
Aquamarine Essence doesn't have any crafting recipes to turn it into Aquamarine.

**To Reproduce**
1. Get any Amount of Aquamarine Essence
2. Check the uses for Aquamarine Essence
3. Try to use it for anything

**Screenshots**
JEI Usages of Aquamarine Essence
![javaw_2021-04-18_21-30-14](https://user-images.githubusercontent.com/9990060/115158754-4db60f80-a07f-11eb-839d-a87b4b4f58b1.png)
JEI Usages of Iron Essence for reference
![javaw_2021-04-18_21-50-55](https://user-images.githubusercontent.com/9990060/115158776-6e7e6500-a07f-11eb-9dc4-1b2451095a56.png)

**Additional context**
From my very limited knowledge of this project
Aquamarine Essence got introduced here it seems https://github.com/AllTheMods/ATM-6/pull/1190
And the crafting recipe seems to have been removed again here https://github.com/AllTheMods/ATM-6/pull/1261/

**Logs**
I don't think Logs are needed. I can provide logs of things if it's desired.

**Comment by Pdiddy973** [comment]
Fixed in
https://github.com/AllTheMods/ATM-6/pull/1523
