### ISSUE TITLE
Creative energy cube does not work- 1.5.10 and 1.6.0b

### ISSUE THREAD

**Issue by Colinas00** [AllTheMods/ATM-6#1467]
**Creative Energy Cube does not work**
when i connect it to my reactor the energy seems to desapear, there's an input, but no output.

**To Reproduce**
1. build a creative energy cube 
2. plug it on the energy generator (mine is: a 5x5x5 @BiggerReactors with gold block heat dispersion)
3. try to use @Flux Networks plug on it to power your machines

**Screenshots**
![image](https://user-images.githubusercontent.com/82792696/115179649-2fb1d480-a0aa-11eb-9b1d-f691fc17d3ce.png)
![image](https://user-images.githubusercontent.com/82792696/115179667-38a2a600-a0aa-11eb-9e9f-2f171ec142a3.png)
![image](https://user-images.githubusercontent.com/82792696/115179714-5112c080-a0aa-11eb-9bc9-0cb6979a484c.png)

**Additional context**
it is an item that costs 2 blocks of vibranium an some diamonds and it is consuming my enegy into nothing.

**Comment by Pdiddy973** [comment]
You need to craft it again to have it able to provide power, you have the first step to the creative cell.

**Comment by Colinas00** [comment]
> You need to craft it again to have it able to provide power, you have the first step to the creative cell.

it didn't work, there's no recipe and nothing happens when i try to craft it

**Comment by jombo23** [comment]
You have to energize it with an ATM star which you can clearly see in the third tab of recipies in JEI else its just an energy sink.

![image](https://user-images.githubusercontent.com/4957057/116003101-9fecb880-a5ca-11eb-9524-f7f23e4a1050.png)

**Comment by Yassine1338** [comment]
Ahh i understand now.
I wanted to use it to store my energy.
Ty for your help
