### ISSUE TITLE
Have ATM version on main menu

### ISSUE THREAD

**Issue by DarkEyeDragon** [AllTheMods/ATM-6#1468]
**Is your feature request related to a problem? Please describe.**
I've found that some people (myself included) find it can be a bit of a pain to figure out the atm version you're running. 

**Describe the solution you'd like**
An ATM6 version in the bottom left somewhere with the forge and mc version

**Describe alternatives you've considered**
You basically need to check the launcher.

**Additional context**
I use Multimc and there it's not really displayed at all outside of the game or in for that matter.

**Comment by whatthedrunk** [comment]
I'll add this to our discord notes to see if something we wanna do. Thanks for the suggestion.
