### ISSUE TITLE
Xray glitches

### ISSUE THREAD

**Issue by Jkwolf25** [AllTheMods/ATM-6#147]
For the current version available on Twitch, I have discovered a texturing issue with 2 mods that allow players to see underground caves, fortresses, and mineshafts. (Lava lakes too). The first is a small one using the Tank/null mod. Placing the docking station down will give a very small xray window through adjacent blocks. Placing the Tank/null itself into the docking station makes the window bigger. The other xray involves the RFtools builder when previewing the area that the builder will affect, it places "ghost blocks" to show where the builder will build/quarry. Looking up or down along the edge of the boundary blocks allows unobstructed views of caves and structures. 

I haven't experienced any other xray issues, and I do not know if updated mods might fix the texturing issue.

**Comment by WhitePhant0m** [comment]
https://github.com/Tfarcenim/TankNull/issues/5 placing this here track the issue.
