### ISSUE TITLE
the rf tools builder quarry crash

### ISSUE THREAD

**Issue by SideOrder** [AllTheMods/ATM-6#1471]
the rf tools builder quarry lags out and the crashes once you turn on the machine with a lever
[crash-2021-04-18_19.29.21-server.txt](https://github.com/AllTheMods/ATM-6/files/6338041/crash-2021-04-18_19.29.21-server.txt)
[crash-2021-04-18_19.36.19-server.txt](https://github.com/AllTheMods/ATM-6/files/6338042/crash-2021-04-18_19.36.19-server.txt)
[crash-2021-04-18_20.03.26-server.txt](https://github.com/AllTheMods/ATM-6/files/6338043/crash-2021-04-18_20.03.26-server.txt)

**Comment by riipeckx** [comment]
Unable to reproduce.
