### ISSUE TITLE
Missing Recipe RFTools Utility (Elevator Button Screen Module)

### ISSUE THREAD

**Issue by StrayCargo** [AllTheMods/ATM-6#1472]
There is no recipe for the elevator button module.

**To Reproduce**
Open NEI/JEI
Search Elevator Button Screen Module
Click on Item and make sure creative is not on ;)
**Screenshots**
![Elevatorbuttonmodule2](https://user-images.githubusercontent.com/8396060/115281514-b6000200-a10e-11eb-8f1a-ce21f0b5d9c2.png)
![Elevatorbuttonmodule1](https://user-images.githubusercontent.com/8396060/115281517-b6000200-a10e-11eb-9774-f673eb86c59d.png)

**Additional context**
This module is needed for making the elevators with rftools utility.

**Logs**

**Comment by BovineShaman** [comment]
Looks like it's not implemented in the mod yet.
