### ISSUE TITLE
Material Stonework Factory Crushes Sand into Silicon and not Dust ATM-6 To the Sky

### ISSUE THREAD

**Issue by TheBigBuns27** [AllTheMods/ATM-6#1475]
Version 1.0.7 Creative Items

The Material Stonework Factory should definitely crush to dust instead of silicon.

To Reproduce:
Set the machine to crushing and input sand.

This might be intended but I highly doubt it.

**Comment by whatthedrunk** [comment]
This is for atm6 please post any issues for sky here. https://github.com/AllTheMods/atm6-sky
