### ISSUE TITLE
java.lang.NullPointerException: Ticking entity

### ISSUE THREAD

**Issue by viveleroi** [AllTheMods/ATM-6#1476]
Pack version: ATM6 v1.6.0b

**Describe the bug**

Our server had several players so we unfortunately don't know what caused this. We've been running fine for days but suddenly this same crash twice within an hour of time.

**To Reproduce**
Unfortunately unknown.

**Logs**
https://pastebin.com/8dipdqnB

**Comment by viveleroi** [comment]
Ok, so the entity was a zombie and it had spawned in a dark spot under a huge tree near a player's base. The player had a rat firing a minigun as a defense, so it was blasting the area a lot. I set forge to remove error entities because the server would crash any time this player joined.

**Comment by ladylexxie** [comment]
If it happens again, you can go to `forge-server.toml` and enable `removeErroringEntities = false`.
