### ISSUE TITLE
Mekanism Diamond Dust only giving 10mb in Metallurgical Infuser pack version 1.6.1

### ISSUE THREAD

**Issue by WTFFFS** [AllTheMods/ATM-6#1477]
As of version 1.6.0, Mekanism Diamond Dust is only giving 10 mb in the Metallurgical Infuser instead of the 80 it was giving previously. Is this an intended change? If so it's a little harsh imo as each advanced alloy costs two diamonds. and many recipes use 6 of them.

**Comment by DrMrPotatoe** [comment]
Diamond dust always gave 10mb, diamond dust in the enrichment chamber will increase the output to 80

**Comment by WTFFFS** [comment]
ah shit sorry I must have used the enrichment chamber without realizing previously
