### ISSUE TITLE
Changing UUID of duplicate entity overload server

### ISSUE THREAD

**Issue by Gougou78** [AllTheMods/ATM-6#1478]
Hello,
We are having a problem with our server. Occasionally, it decides to change the UUIDs of the duplicate entities.

This generates :

- either a server crash (which was resolved by putting "-1" in server.properties for "max-tick-time"

- either a player timeout after 5 minutes of UUID change ....

We have also deactivated the change of UUIDs in the RandomPatches config but the server is still giving us timeouts.

Our map was created in 1.5.9b, I made the updates with the procedure, we are currently in 1.6.1 and we still have the bug.

I'll leave the logs to you for more information.

Thank you :)

https://gist.github.com/Gougou78/34629fbb761313dff9445b61e3dcbc9f

**Comment by derabzockerHD** [comment]
I think it has something with the mod: absent by design. I wrote to the developers of the mod: https://github.com/Lothrazar/AbsentByDesign/issues/31

**Comment by derabzockerHD** [comment]
Maybe this helps: https://github.com/AllTheMods/ATM-6/wiki/Pack-Upgrade-FAQ

**Comment by radiomike** [comment]
The UUID changes are probably not causing your problems. It's better to leave that set and ignore the log spam, it's not really an indication of anything being wrong.
As far as timeouts and overloaded server, that could be lots of things. Could be garbage collection related, lots of entities or lots of machine automation. I'd recommend using spark to do some profiling to get a better idea of what's actually going on.
