### ISSUE TITLE
the game keeps freezing

### ISSUE THREAD

**Issue by Gobslly** [AllTheMods/ATM-6#1479]
i dont know if this is technically a bug or some kind of software issue but the game keeps freezing every few seconds for like three or four seconds and its making the game unplayable, i tired boosting my cpu, redownloading the game, even removing a few mods but it doesn't stop. anything i can do to fix this?

**Comment by derabzockerHD** [comment]
I think that is a technical bug. What are you´re CPU and GPU specs?

**Comment by derabzockerHD** [comment]
The minimum requirement is:
CPU: Intel i7 9th gen or i5 10th gen
GPU: NVIDIA 1060

**Comment by Gobslly** [comment]
> How much ram do you have assigned to the pack? We recommend 8gb.

i have 16 gb of ram

Processor 2 GHz Quad-Core Intel Core i5
Memory 16 GB 3733 
Graphics Intel Iris Plus Graphics 1536 MB

**Comment by jeremiahwinsley** [comment]
Assuming you're using Curseforge Launcher, you can change the amount of memory it uses by clicking on the gear icon in the lower left, clicking on the Minecraft tab, then scrolling to the bottom. You should see a memory slider - set that to 8192mb.

**Comment by Gobslly** [comment]
> Assuming you're using Curseforge Launcher, you can change the amount of memory it uses by clicking on the gear icon in the lower left, clicking on the Minecraft tab, then scrolling to the bottom. You should see a memory slider - set that to 8192mb.

i just tried it and it works perfectly now, thank you so much, im having a ton of fun.
