### ISSUE TITLE
RFTools Dimensions: Placing a block absorber on tilled phyto-soil crashes the server.

### ISSUE THREAD

**Issue by mooproxy** [AllTheMods/ATM-6#1481]
Version 1.6.0c.

As title, however what's worse is that attempting to load in nearby crashes the server again in a way which isn't captured by usual crash-detection (or at least, crash detection used by the ATM6 Patreon Server).

MutantGumdrop tells me that the crash log generated by this bug is 1MB in size.

**Comment by ladylexxie** [comment]
N/A
