### ISSUE TITLE
Item Duping with Carboard Box

### ISSUE THREAD

**Issue by RizzoElRey** [AllTheMods/ATM-6#1482]
If you have Charged Certus Crystals, Rock Crystals, and/or Constellation Paper in a chest and then place a cardboard box from Mekanism over it, those items will spit out but stay in the chest at the same time. Those are the only items I know of so far.

1. Place said items in any chest
2. Place Cardboard Box over chest
3. ???
4. Profit

**Comment by DAmNRelentless** [comment]
https://github.com/mekanism/Mekanism/issues/7053
