### ISSUE TITLE
Problem's with graphic 

### ISSUE THREAD

**Issue by Sandrixa** [AllTheMods/ATM-6#1484]
![dd](https://user-images.githubusercontent.com/82942051/115537430-1a4fcc80-a29b-11eb-81f1-0e346c172c36.png)
![unknown](https://user-images.githubusercontent.com/82942051/115537434-1ae86300-a29b-11eb-8e0e-d67217c45b94.png)
![Capture](https://user-images.githubusercontent.com/82942051/115537436-1b80f980-a29b-11eb-8d12-bdc3194ea662.png)
![321](https://user-images.githubusercontent.com/82942051/115537438-1b80f980-a29b-11eb-877a-be294246bc6b.png)

I am sending the pictures how it should look like (and it look like that for my friend) and how it looks for me. I reinstalled already and nothing has changed. It happend when i changed ATM6 from 1.6.0c on 1.6.1

**Comment by Zeagl3** [comment]
Do you have optifine/optiforge installed?
When I installed those mods, my graphics were fucked up too. 
I uninstalled optifine and optiforge and graphics were good again.

**Comment by kasutsu** [comment]
same bug here, and i don't have optiforge neither optifine

**Comment by Pdiddy973** [comment]
Does it work without the shaders/ any resource pack. We don't officially support those

**Comment by kasutsu** [comment]
i don't use shaders, but i see that I had a resource pack on, but i never installed them neither activated one, but i have one which is activated

**Comment by Sandrixa** [comment]
It was still the same without optifine

**Comment by starforcraft** [comment]
Shaders aren't supported.
