### ISSUE TITLE
Question for Sethome/Setwarp/Back/

### ISSUE THREAD

**Issue by DerMoki** [AllTheMods/ATM-6#1486]
Hey !
All the Mods 6-1.6.1

I edited the File _>defaultconfigs>ftbessentials-server.toml_ to this:
`#Max number of times you can use /back
#Range: > 0
#maxBack = 0
#Max homes
#Range: > 0
maxHomes = 10
#/back cooldown in seconds
#Range: 0 ~ 604800
#backCooldown = 604800
#/spawn cooldown in seconds
#Range: 0 ~ 604800
#spawnCooldown = 10
#/warp cooldown in seconds
#Range: 0 ~ 604800
#warpCooldown = 604800
#/home cooldown in seconds
#Range: 0 ~ 604800
#homeCooldown = 10
#/tpa cooldown in seconds
#Range: 0 ~ 604800
#tpaCooldown = 604800
#/rtp cooldown in seconds
#Range: 0 ~ 604800
#rtpCooldown = 600
#Number of tries before /rtp gives up
#Range: 1 ~ 1000
#rtpMaxTries = 10
#/rtp min distance from spawn point
#Range: 0.0 ~ 3.0E7
#rtpMinDistance = 1000.0
#/rtp max distance from spawn point
#Range: 0.0 ~ 3.0E7
#rtpMaxDistance = 100000.0`

After a Restart the Server say "You cant add more home", but i have no homes.
Also the cooldown is still there, can someone help me here?

**Comment by Pdiddy973** [comment]
Default config is only used during world creation, to change the setting for existing world's go to world/serverconfig
