### ISSUE TITLE
My friend's game crashed when he tries connect through LAN (1.6.1)

### ISSUE THREAD

**Issue by IceDreamy** [AllTheMods/ATM-6#1487]
**Describe the bug**
After update from 1.6.0c to 1.6.1,When my friends tries to connect through LAN,his game crashed
However my game didn't crash

**To Reproduce**
(update modpack from 1.6.0c to 1.6.1)
1.My friend tries to connect through LAN
2.show "xxx join" in chat
3.he's game crash with a crashreport below

**Logs**
[https://gist.github.com/IceDreamy/203d39ec0fccb40f5964a64d66b0a28a](url)

**Comment by Mommotexx** [comment]
The problem lies in this Block: Block{mysticalagriculture:infusion_altar}

maybe it's fixed in 1.6.2? 

if not
downgrade to 1.6.0c, and remove the block from his inventory. Then update again
