### ISSUE TITLE
Boss got rid of all of my hearts

### ISSUE THREAD

**Issue by RileyOard** [AllTheMods/ATM-6#1489]
While in a cave I was attacked by some zombie boss. I was wearing Allthemodium armor, a full set other than boots. It killed me in one shot and when I respawned I got my grave and my hearts and my armor were gone. 

After re-logging, restarting my game completely and restarting my server. I still have no hearts and lost all of my armor. 

Any fix for this?

**Comment by BovineShaman** [comment]
Hearts gained by Spice of Life: Carrot Edition are reset upon death, this can be changed in your config if you wish to do so.
If I remember correctly, Apotheosis bosses can sometimes ignore armor when attacking, depending on the boss.
