### ISSUE TITLE
[ATM 1.6.1] Spectator mode?

### ISSUE THREAD

**Issue by K1LLM0NGER** [AllTheMods/ATM-6#1491]
**Describe the bug**
In version 1.6.1, players are put in spectator mode when killed(multiplayer).

**To Reproduce**
1. Join server
2. Die
3. Get put into spectator mode

**Logs**
Server Logs: https://pastebin.com/xgaqnF2A

**Comment by Zeagl3** [comment]
No problem here, sounds like your server is put into Hardcore mode.
![image](https://user-images.githubusercontent.com/83012326/115707310-e80f9f00-a36e-11eb-9824-521b814ca1b6.png)

**Comment by K1LLM0NGER** [comment]
Damn, I’m stupid as fuck

**Comment by K1LLM0NGER** [comment]
Thank you!
