### ISSUE TITLE
Mekanism cardboard box duplicates Astral Sorcery items

### ISSUE THREAD

**Issue by Zartanio** [AllTheMods/ATM-6#1493]
Version 1.6.1 

Using a Mekanism cardboard box to move a chest duplicates the Astral contents.

1. Place an Astral Sorcery rock crystal in a chest (also works with Iron Chests)
2. Click the chest with a cardboard box
3. All copy of the Astral contents of the chest pop out into the world
4. Remove the box and open the chest. Original items remain plus the duplicated items.

**Comment by ProjectGSX** [comment]
Ive seen this in my world as well.

**Comment by ladylexxie** [comment]
It's a known issue, but sadly nothing we can do apart from removing the cardboard box.
