### ISSUE TITLE
Smeltery not alloying correctly

### ISSUE THREAD

**Issue by OhNoITzLewisx** [AllTheMods/ATM-6#1494]
All the Mods 6.

Tinkers construct alloying issue with slimesteel.

Input all items required and they individually turn molten rather than alloying.

Tried replacing the controller and using different slimeballs but still face the same issue.

**Comment by incomingnerd** [comment]
Slimesteel seems to alloy fine for me on ATM6-1.6.2. It does require a skyslime ball specifically. Can you give screenshots of your exact setup and ingredients?

**Comment by thevortex** [comment]
this issue is resolve in 1.6.2+
