### ISSUE TITLE
ATM Star easy unintended way (I believe) to achieve via uncrafting table from twilight

### ISSUE THREAD

**Issue by rianradeck** [AllTheMods/ATM-6#1497]
If you put a dragon egg in a uncrafting table of twilight forest you can get a ATM star. (The craft does not appear in the uncrafting table but if you put the dragon egg and click on the middle square of the uncrafting table it will appear, I believe this is a bug from the alpha version of twilight forest)

Knowing that if you have a dragon egg entity and hit it with a sword you drop the dragon egg item itself, you can duplicate them on mob duplicator.

And now you have ATM stars from mob essence.

**Comment by rianradeck** [comment]
![bug1](https://user-images.githubusercontent.com/60761801/115790965-faed9800-a39d-11eb-9949-9691b8f80a6c.png)
![bug2](https://user-images.githubusercontent.com/60761801/115790968-fc1ec500-a39d-11eb-9496-4ba187c89c1c.PNG)

**Comment by DatRatVS** [comment]
Nofaxu be like.
