### ISSUE TITLE
ATM6 (1.6.1) Server lags when Drain Life spell is used

### ISSUE THREAD

**Issue by VortexWilliam** [AllTheMods/ATM-6#1498]
Pack Version 1.6.1 
Once a drain life spell from mahou tsukai is active my server starts to lag really bad to the point after a few hours of crashing.

**To Reproduce**
1. Setup a witch spawner in a closed chamber. Mine was 7x7 with witch spawner in center. Max upgraded, but using the max number of entities on spawner to keep from lagging.
2. Place a single life drain spell from mahou tsukai.
3. Let server run and it will start to lag.
**Screenshots**
Server starts dropping frames and render distance once just one spell is on https://prnt.sc/11w5ghi
Server stability instantly improves after turned off https://prnt.sc/11w5mso

Server has 8GB of ram

**Comment by stepsword** [comment]
@VortexWilliam can you get spark (https://www.curseforge.com/minecraft/mc-mods/spark) and do 

1. /spark profiler --thread * 
2. let it run for a bit while your server is lagging out and
3. /spark profiler --stop

and then post the link here? people have mostly told me the new update I did for boundaries was better, not worse, so it'd be helpful for me to see exactly where the lag is from

**Comment by VortexWilliam** [comment]
https://spark.lucko.me/XEReYyW6t2
https://spark.lucko.me/WxXt6xEs2P

**Comment by stepsword** [comment]
It looks like the majority of the lag is just coming from Witch AI and a tiny bit of Twilight Forest collision boxes, which is a relief for me as the Mahou dev but not so much you as someone experiencing lag... Maybe  give them more room to spawn or something? That's the only thing I can think of as a solution, but I dont know whether it'd work

**Comment by starforcraft** [comment]
The Witches are causing the lag
