### ISSUE TITLE
Codex Arcana - ATM6 - 1.16.5

### ISSUE THREAD

**Issue by tyroneey** [AllTheMods/ATM-6#1499]
Opening the Codex Arcana is causing a glitch where all my items disappear... they are still there. I can see them in my hand as I scroll, but not in the GUI. When I escape and save to the main screen the words are missing off the menu as well.
![unknown](https://user-images.githubusercontent.com/83046326/115801691-384c2880-a392-11eb-90d7-1200dfe251b1.png)

**Comment by hendrikbl** [comment]
This happens for me only when using optifine/shaders. Otherwise it works fine. Still pretty annoying since it makes me just ignore this mod.

**Comment by starforcraft** [comment]
Delete Optifine
