### ISSUE TITLE
[v1.6.1] ATM Star "easy" farm without using the correct recipe.

### ISSUE THREAD

**Issue by Zargachi** [AllTheMods/ATM-6#1500]
**Describe the bug**
I don't know if this is actually a BUG and probably a lot of people who uses this will be mad with me, but, i was watching an youtuber i follow (Nofaxu, from Brasil) and during a livestream, someone said to him to put a Dragon Egg on a Uncrafting table from Twilight Forest, in the table the recipe don't appears but if you click you actually can take the ATM Star from the Recipe, besides dragon eggs be somethin rare, you can put it on a Mob Imprisioning Tool from Industrial Foregoing and duplicate the Egg on the Mob Duplicator, plus, this same Mob Duplicator, can duplicate a Donkey with a chest and the items inside the chest, so, this can become really broken really fast as you can see... i don't if this is intended or not, but if not please fix, or not, you decide. 
Maybe changing the Uncrafting Table recipe to be much more expensive would be sufficient to counter this...?

**To Reproduce**
1. Put a Dragon Egg on a Uncrafting Table from Twilight Forest
2. Besides it not showing the recipe, it is there, just try to pick a item.
3. See error
 
Mob Duplicator
1. Put a Dragon Egg in a Mob Imprisioning Tool
2. Put it inside a Mob Duplicator and put it to work
3. Dragon Eggs should start to spawn, kill them and they will drop, Luck apparently can affect how many eggs gonna drop. 

**Screenshots**
i didn't tested it by my self so i don't have screenshots, but a youtuber i follow tryed this.
there is the link for his video: https://youtu.be/11rETK_3wVw?t=236

**Additional context**
This is a REALLY broken thing, if someone runs a server with this modpack and they trade ATM stars or something like that, it can easily broke the economy.

**Comment by Pdiddy973** [comment]
Fixed in 1.6.2
