### ISSUE TITLE
Missing tool station

### ISSUE THREAD

**Issue by robertkremer92** [AllTheMods/ATM-6#1501]
Hey guys, 
I'am playing atm 6 for a while now and i noticed that i miss a huge amout of things from tinkers construct such as tool station and purple slime balls.

Is this a bug, half mod pack or ...?

**Comment by P3rf3ctXZer0** [comment]
No so they got rid of tool stations this is not a bug @robertkremer92 you should google a 1.16.5 tinkerers construct tutorial.
