### ISSUE TITLE
Mining level problems

### ISSUE THREAD

**Issue by Aspyro** [AllTheMods/ATM-6#1503]
Pack version : 1.6.1

Some ores have a wrong mining level.
I.e on screenshots the Runestone is supposed to have a mining level Diamond, and you can still mine it with a stone pickaxe (didn't try it with wood or bare hands). Same with Dimensional shards that is supposed to have a mining level Iron. I was able to mine it with stone and get the item.

(Dimensional shards and Runestone are the only ones where I saw that error. Not sure if there are any else)
Opposed to that, some ores have the right mining level applied (like the vinteum on the 4th screenshot.

![2021-04-23_23 13 07](https://user-images.githubusercontent.com/37420016/115931236-15516f80-a48b-11eb-9db1-443567739c48.png)
![2021-04-23_23 13 17](https://user-images.githubusercontent.com/37420016/115931241-171b3300-a48b-11eb-9aba-4b12901dd81a.png)
![2021-04-23_23 13 28](https://user-images.githubusercontent.com/37420016/115931243-184c6000-a48b-11eb-870e-f1a8fe234174.png)
![2021-04-23_23 13 38](https://user-images.githubusercontent.com/37420016/115931245-18e4f680-a48b-11eb-840f-86070790392a.png)

**Comment by BovineShaman** [comment]
This is a mod issue, not a pack issue.
