### ISSUE TITLE
Problem with Create Funnels not connecting to chests/storage drawers.

### ISSUE THREAD

**Issue by Furious1964** [AllTheMods/ATM-6#1507]
ATM6 Version 1.6.1
**Describe the bug**
Create Funnels won't connect to chests or storage drawers.

**To Reproduce**
1. Chest/drawer on top of funnel
2. Funnel in middle.
3. Chest on bottom of funnel.
4. Nothing moves from top chest.

Screenshots:
https://imgur.com/n6wgRnl
https://imgur.com/U2WUyf6
https://imgur.com/2tSquyY

**Additional context**
Tried rebuilding set-up with no results.

I've checked this video and the funnels are not extended to the chest:
https://www.youtube.com/watch?v=GNtR0fGi6dY&t=852s

Also, deployers seem to not be working at all as they're not planting the oak saplings.

EDIT: Deployer problem solved as I removed the grass from the tree farm and replaced it with dirt and had to remove the ftb-chunk loading from the area, but still the funnels won't connect to the Storage Drawer.

I don't know why this is happening.

**Comment by ladylexxie** [comment]
Create changed it to work like that, it is now the Smart Chute.
