### ISSUE TITLE
Elytra not working 

### ISSUE THREAD

**Issue by Ebsation** [AllTheMods/ATM-6#151]
After updating to All the Mods 6-1.1.0 I am not able to initiate flying with elytra in mid air. Looking in third person the animation seems to start and then cancel. I have tried creating a new instance, playing in single player, creating a new world on my server, launching through MultiMC, launching through Twitch launcher.

**Comment by Stormbril** [comment]
Seconding this issue -- still happening in ATM 6-1.1.3b. Installed pack without any modifications, onto an existing vanilla 1.16.3 world.

**Comment by whatthedrunk** [comment]
This will be fixed in 1.1.5 out soon.
