### ISSUE TITLE
[ATM 6-1.6.1] Phyto-Gro Fertilizers from Thermal Series not working on crops

### ISSUE THREAD

**Issue by bjsoong** [AllTheMods/ATM-6#1510]
[ATM 6-1.6.1]
**Description**
Phyto-Gro no longer grows crops the same way bone meal does.

**Steps to reproduce:**
Just right-click-use Phyto-Gro on any Crop. Nothing happens

**Additional Context**
Right-Click-Using it on trees and grass blocks work normally.

Bone Meal works just fine.

**Comment by ladylexxie** [comment]
It is meant to be used in the Phytogenic Insolator, not right-clicked on plants. As the book mentions, it can also be used with the explosives to use it on crops.
