### ISSUE TITLE
JEI not showing crafting recipes

### ISSUE THREAD

**Issue by ItsMeWolfE** [AllTheMods/ATM-6#1511]
[ATM 6-1.6.1]
**Describe the bug**
Clicking an item in the JEI menu only brings up misc recipes for mods, and many are missing. But it never shows any crafting recipes. Most items just straight up won't show anything when clicked. When right-clicked, 90% of the items show Just Enough Resources' enchantments, or how to make a facade using the item.
**To Reproduce**
1. Open the inventory to show JEI
2. Click on any item
3. No crafting recipe shows up

**Screenshots**
Example of trying to click on wool (shows a random thing and no crafting)
![image](https://user-images.githubusercontent.com/63506643/115962968-62365400-a526-11eb-9fce-d824b9b6311a.png)

**Additional context**
The bug started after updating the modpack from 1.6.0c to 1.6.1

**Comment by Pdiddy973** [comment]
This seems like a bad update, try a fresh install
