### ISSUE TITLE
Useful Backpack mod doesn't seem to work with the graves

### ISSUE THREAD

**Issue by SpeedSlider** [AllTheMods/ATM-6#1513]
**Describe the bug**
I am playing ATM6 Version 1.6.1 and using the small backpack from Useful Backpacks mod to store a few tools and items. I was clearing a desert Rogue Like Dungeon and died. After retrieving my grave my Useful Backpack was missing, but I didn't notice it right away. I then assumed I had too much stuff and forgot to pick up the backpack when recovering my grave after a death. The second time it happened I noticed my hot bar didn't seem right but couldn't figure out why. I only had a handful of items at the time as I was using a modular storage to put all the loot in. I then needed sheers and realized the Useful Backpack was missing and then realized my Useful Backpack was missing. I looked in the RFTools modular storage and saw that it wasn't in there and then realized that the Useful Backpack is what was missing after retrieving my grave.

**To Reproduce**
1. Craft a small backpack from Useful Backpack mod.
2. Put a few items in it and then die with it.
3. Retrieve your items from your grave after dying
4. At this point you should be missing your backpack.

**Screenshots**
N/A

**Additional context**
I assume this is not an intended feature, but I am also aware that it may not be applicable to all instances and configuration. I am using Optifine, but don't see how that would impact this issue.

**Logs**
N/A
Here's a list of some paste sites and their size limits:
    https://pastebin.com/ 512KB
    https://hastebin.com/ 400KB
    https://gist.github.com/ 100MB Requires member (Free)

**Comment by Pdiddy973** [comment]
It went into your curios slot, press v or take it out
