### ISSUE TITLE
Game frozen at loading

### ISSUE THREAD

**Issue by PVPM** [AllTheMods/ATM-6#1514]
**Describe the bug**
Even with about 10GB ram game is not loading. It stops at "Atlas Stitching : minecraft:textures/atlas/mob_effects.png 
It's not crashing and closing game but i waited about an hour and nothing changed so i decided to kill process by myself. The pack version is: All the Mods 6 Sky-1.0.7
All that i can provide in this situation is just the logs file
Thanks in advance

**To Reproduce**

**Screenshots**

**Additional context**

**Logs**
https://gist.github.com/PVPM/d8f09b01d800008b778173690116f134

**Comment by starforcraft** [comment]
Should be fixed in newest Version.

**Comment by starforcraft** [comment]
And that was sky ;)
