### ISSUE TITLE
Newest version (1.6.2) has wrong version of valkyrie lib

### ISSUE THREAD

**Issue by xfl09** [AllTheMods/ATM-6#1520]
![image](https://user-images.githubusercontent.com/83176603/115999969-8d847600-a5ee-11eb-914e-1c8eb858e20d.png)

**Comment by SmokyMtnRed** [comment]
I am having a similar issue with Reliquary not loading. Didn't know if it was related or not... 

![image](https://user-images.githubusercontent.com/26696506/116002158-61ed9580-a5c6-11eb-9b8b-e324f070d8b9.png)

**Comment by Pdiddy973** [comment]
Seems to be a bad install, try to make a fresh instance
