### ISSUE TITLE
Creates regular world type not skyblock for a server

### ISSUE THREAD

**Issue by tannedcracker** [AllTheMods/ATM-6#1521]
Im using the 1.0.7 version of ATM 6 for a server but everytime I create the world it creates a regular world instead of a skyblock. The level type is already set at skyblock and I have even reset the world folder but still get the same problem please help

**Comment by derrickmehaffy** [comment]
I think you are looking for https://github.com/AllTheMods/atm6-sky

This repo isn't for the skyblock atm6
