### ISSUE TITLE
Allow dragons to be captured by the mob imprisonment tool again.

### ISSUE THREAD

**Issue by MaerkR** [AllTheMods/ATM-6#1522]
**Is your feature request related to a problem? Please describe.**
It's awful having to walk for hours in the boring samey The Other dimension just to perhaps stumble into a dragon that's not even the type or tier you want, so as a solution people stored these dragons and copied them using a mob duplicator to fight later, but now, you just can't use the mob imprisonment tool to do that anymore.

**Describe the solution you'd like**
Just make it so, by default, players are able to capture the dragons once again.

**Describe alternatives you've considered**
Since I don't know if that was a decision by the pack devs or the mod devs, another solution would be making it so the biomes in the other dimension are more diverse and the dragon biomes being more common, so you don't have to fly through thousands of the samey boring badlands biome, that's waaay more common than the other ones.

**Additional context**
I just wanted to get the lightning dragon forge, but it's so boring to find these dragons, out of 10 dragons, only 1 was the lightning one, my world file is massive because of so much world gen.

**Comment by Pdiddy973** [comment]
We removed the ability to use the mob imprisonment tool since you could dupe dragons with, no plans to re add it back any time soon.

**Comment by JustBlankXD** [comment]
@Pdiddy973 can you at least tell us how we can change that?
(Maybe in the configs or something)
