### ISSUE TITLE
Chisels and Bits blocks changed

### ISSUE THREAD

**Issue by StardustOfficial** [AllTheMods/ATM-6#1524]
**Describe the bug**
After the server I play on updated to 1.6.0c (from 1.5.10) my chisels and bits blocks changed. For exmaple, my chiseled Alfglass turned into Elementium, my chiseled Illuminant Block turned into End stone, my chiseled Iron Plate (Quark) changed into ladders. This isn't just a client side issue; I was able to take the chiseled elementium, fill up the rest of the chiseled block, and receive a block of elementium which I could then turn into elementium ingots. This has resulted in me having to redo most of the chiseled blocks in my base; I used a lot of iron plate ones so now I have ladders plastered all over my base. 

**To Reproduce**
1. Use chisels and bits on blocks on 1.5.10 (i used iron plate, alfglass, and illuminant block)
2. Update to 1.6.0c
3. Watch as your blocks magically change to crap you never had them as, and redo everything because of this bug. 

**Screenshots**
![Screenshot (1365)](https://user-images.githubusercontent.com/83199126/116102824-07fbd700-a67d-11eb-82d6-afcfedc0c057.png)
![Screenshot (1364)](https://user-images.githubusercontent.com/83199126/116102827-092d0400-a67d-11eb-8bec-ba71fa84df58.png)
![Screenshot (1363)](https://user-images.githubusercontent.com/83199126/116102828-09c59a80-a67d-11eb-8842-3535c928e8af.png)

[In the first screenshot, the correct block(iron plate) is to the left of the panel with the ladders. The ladders are the messed up chiseled blocks. 

**Additional context**
--

**Comment by tanyan-tanyan** [comment]
Can confirm this also happened after a server upgrade on our server.

![javaw_eKJ9qVM6SB](https://user-images.githubusercontent.com/68793071/116459195-6c758c80-a85d-11eb-8fb8-255ea1df39e8.png)

**Comment by lucasvanhalst** [comment]
This has been happening on my server as well, since at least november.

**Comment by starforcraft** [comment]
Issue from Chisel & Bits.
