### ISSUE TITLE
java.lang.NoClassDefFoundError: com/github/alexthe666/iceandfire/api/event/DragonFireDamageWorldEvent

### ISSUE THREAD

**Issue by viveleroi** [AllTheMods/ATM-6#1525]
**Describe the bug**

Pack 1.16.1

I spawned an ice dragon from a mob crushing util's entity spawner. I've done this a dozen times without issue. Something alt-tabbed my client and my screen froze. Next thing I knew the whole server was down. Not sure that's related. 

Looking at the crash report, it did involve the dragon. I was the only one fighting dragons.

My building was made of obsidian, and had a few iron spikes on the ground. It was in the other dimension.

**To Reproduce**
1. Spawn ice dragon from Mob Crushing Util's entity spawner.
2. ?? Alt tab your client?
3. ?? Never had this happen with around 20 previous ice dragons.

**Logs**
https://pastebin.com/kgSiSMYw

**Comment by starforcraft** [comment]
Should be fixed in newest Version.
