### ISSUE TITLE
Game crashes after I click play in client

### ISSUE THREAD

**Issue by gorkidood** [AllTheMods/ATM-6#1526]
When I click play on curse then click play from the mc launcher it loads for a couple of seconds before saying error code5 and closing down.

Game version is 1.6.2

This is what I see after it crashes
![image](https://user-images.githubusercontent.com/64323198/116117722-3c938100-a6c5-11eb-8197-6010dcf3279b.png)

**Comment by Pdiddy973** [comment]
use a better launcher like [GDLauncher](https://gdevs.io/) and make sure you have at least 6GB allocated, 8 preferred
