### ISSUE TITLE
Version 1.0.7 Mekanism Advanced logistical transporter dupes when connected to ex nihlio sequentia wooden barrel

### ISSUE THREAD

**Issue by Volairen** [AllTheMods/ATM-6#1527]
Version 1.0.7

when i connect the mekanism transporter to wooden barrels from ex nilio sequentia. Then set the transporter to pull from a container to the wooden barrels, it does not use the items in the container but still supplies the wooden barrels with what was in the container, thus essentially making the transaction free. Apologies if dupeing is not the correct term, it was the most similar term i could think of at the top of my head. 

1. connect the mekanism transporter to wooden barrels from ex nilio sequentia. 
2. set the transporter to pull from a container to the wooden barrel
3. create any recipe using this setup such as creepy dolls, clay, or slime

**Comment by BANANASGAMER1** [comment]
Itadakimasu
