### ISSUE TITLE
java.lang.RuntimeException: There is already a dimension with this descriptor: 2

### ISSUE THREAD

**Issue by viveleroi** [AllTheMods/ATM-6#1528]
**Describe the bug**

Pack 1.6.1. User was loading up a random rf tools dimension. This crashed the server.

**To Reproduce**
1. User loaded a random rftools dimension
2. Was a "basic as I could get it"

**Logs**
https://pastebin.com/3khnxTa5

**Comment by ladylexxie** [comment]
Fixed by mod creator.
