### ISSUE TITLE
Silent's Gear Repair Kit issues.

### ISSUE THREAD

**Issue by Blntswrd** [AllTheMods/ATM-6#153]
**Describe the bug**
When a repair kit is put into a crafting grid first it acts as if only one material is put into the grid with it even if there is more than one.

**To Reproduce**
1. Put a repair kit(from silent's gear) into a crafting grid, inventory or crafting table.
2. Add materials to the grid, more than one.
3. Mouse over resulting repair kit.

**Expected behavior**
The repair kit to add all materials in the grid to it's total instead of just one.

**Screenshots**
https://imgur.com/UDBKMfg

**Comment by puppydemon20** [comment]
This bug can be temporarily bypassed by putting the repair kit in last.

**Comment by DeathOfTime** [comment]
This is still present and I have found that if you put it in last you can take out all but 1 ingot it will still craft as if all the original ingots were in it.

**Comment by Namoku** [comment]
> This is still present and I have found that if you put it in last you can take out all but 1 ingot it will still craft as if all the original ingots were in it.

what do you mean?

**Comment by ViRb3** [comment]
Can you please check whether this issue still exists in ATM 1.3.2 and report to https://github.com/SilentChaos512/Silent-Gear? Reply here with a link to the issue to connect them.

**Comment by DeathOfTime** [comment]
https://github.com/SilentChaos512/Silent-Gear/issues/237

on there they believe another mod is interfering. it is also stated that this works with parts too. if you switch out the material with another material that works with that part it will still register it as the first material. such as switching out unobtanium for cobble. it will still count it as unobtanium for the recipe but will only consume the cobble
![2020-11-25_22 34 31](https://user-images.githubusercontent.com/15230368/100308672-8e957680-2f6e-11eb-8a50-c6bc0114959a.png)

**Comment by Blntswrd** [comment]
Oh it's definitely a mod conflict from something in ATM6 as it works perfectly fine alone.

**Comment by Namoku** [comment]
I don't think is a mod issue, because works cool in alone.

**Comment by FreeFull** [comment]
It seems to be a conflict with FastWorkbench.

**Comment by jeremiahwinsley** [comment]
Tracked here: https://github.com/Shadows-of-Fire/FastWorkbench/issues/58
