### ISSUE TITLE
allthetweaks

### ISSUE THREAD

**Issue by 6Daniel9** [AllTheMods/ATM-6#1530]
![image](https://user-images.githubusercontent.com/79667083/116273553-37cbdd00-a758-11eb-8721-d1b8fee1fca7.png)
my game is asking for an update of allthetweaks
Can someone help me ?

**Comment by 6Daniel9** [comment]
so this is the most updated version of the modpack, and before it was conflicting with three mods I had to download a newer version of tombstone and Aquaculture but allthetweaks has no update, I have tried almost all versions of kubejs and also it didn't work.

**Comment by thevortex** [comment]
we support the pack as we ship it, once you start updating mods on your
own, you are on your own.
 revert to a released version of the pack until we ship an update

**Comment by thevortex** [comment]
discovered the issue, a new version of allthetweaks has been pushed which will resolve that part of the loading issue, please update to https://www.curseforge.com/minecraft/mc-mods/all-the-tweaks/files/3291361
