### ISSUE TITLE
Unable to update to latest version

### ISSUE THREAD

**Issue by stevewatkins22** [AllTheMods/ATM-6#1531]
I am tying to update my self hosted server from version 1.6.0c, to the latest release, I have followed the instructions found here https://github.com/AllTheMods/ATM-6/wiki/Pack-Upgrade-FAQ, once the mods are installed it fails to install/launch forge and displays the following:

[ERROR] Problem while installing Loader

okhttp3.internal.http2.StreamResetException: stream was reset : PROTOCOL_ERROR

Error: Unable to access jarfile [filepath]\forge-NONE-NONE.jar

Thanks in advance

**Comment by winggndm** [comment]
Update Java to the latest version.  That should fix it.

**Comment by stevewatkins22** [comment]
> Update Java to the latest version. That should fix it.

Fixed it, thanks very much
