### ISSUE TITLE
AE2 Channels broken after server restart

### ISSUE THREAD

**Issue by JoeJoeTV** [AllTheMods/ATM-6#1533]
**Describe the bug**
We have connected 3 Interfaces(each with 4 Molecular Assemblers) using a smart cable followed by dense cables going to a p2p tunnel(Normally it looks like this, with 2 channels used: ![2021-04-27_21 47 10](https://user-images.githubusercontent.com/34209417/116304126-830add80-a7a2-11eb-9c27-92678a7a6633.png)).
The problem is when the server is restarted, the channels don't get assigned properly and the one pack of 3 interfaces uses 8 instead of 3 channels and the next ones in line don't get channels assigned at all and the recipes in the corresponding interfaces don't show up until the smart cables under each "pillar" of interfaces are broken and placed again.
See here:
![2021-04-27_21 46 54](https://user-images.githubusercontent.com/34209417/116304689-222fd500-a7a3-11eb-9c4a-09bb1f9ba82e.png)

Here is an overview of one "pillar": 
![2021-04-27_21 47 00](https://user-images.githubusercontent.com/34209417/116304745-2f4cc400-a7a3-11eb-85e5-fcd5f763f395.png)

**To Reproduce**
1. Build the Setup from the pictures
2. Restart the server

**Comment by ladylexxie** [comment]
Cannot reproduce in current versions.
