### ISSUE TITLE
Nether Fortress and other structures

### ISSUE THREAD

**Issue by TrVulture** [AllTheMods/ATM-6#1535]
Whenever a new world is started there are no structures spawned in the nether or the end. I've started about 20 new worlds and used the locate and tp commands to find where the nether fortresses should be but they are never spawned in.

**Comment by thevortex** [comment]
what is the worldtype you are using for the world

**Comment by Saiyko** [comment]
Yea see: https://github.com/AllTheMods/ATM-6/issues/1516
I also started multiple Worlds, used the "/locate" Command to see the nearest Fortress it shows Coordinates but when i fly there its not spawned.

Not Sure if its important but the Map shows for the Y Coordinate around 65000.

**Comment by thevortex** [comment]
please share the worldtypes used to have this happen

**Comment by TrVulture** [comment]
I am using the sky lock world type, so whatever the base map is when you load up atm6 to the sky.

**Comment by thevortex** [comment]
then you are posting to the wrong issue tracker, this is the tracker for the base pack please file your issue here https://github.com/AllTheMods/atm6-sky/issues
