### ISSUE TITLE
Minecolonies AI Error

### ISSUE THREAD

**Issue by Direct1221** [AllTheMods/ATM-6#1539]
**Describe the bug**
Minecraft Version: 1.6.5
Modpack: All The Mods 6 (1.6.2) [Twilight Forest Removed]
Minecolonies: minecolonies-0.14.115-ALPHA-universal.jar
Structurize: structurize-0.13.166-ALPHA-universal.jar

Issue with Minecolonies and task delegation with the AI in the version (fixed with newer versions... didn't get told what version though)
 -- Attached error sent to Minecolonies Dev's in Discord

**To Reproduce**
1. Start using Minecolonies
2. Get ~10 Colonists
3. Upgrade Farm to level 3
4. Randomly will error

**Logs**
https://gist.github.com/Direct1221/8b13d60a4d193264c2b0074453fb0d8a

**Comment by ladylexxie** [comment]
Cannot reproduce, even so doesn't cause any issues.
