### ISSUE TITLE
Server hangs when someone enters the Nether

### ISSUE THREAD

**Issue by TheThirdBeast** [AllTheMods/ATM-6#154]
We upgraded from ATM6 0.29 to ATM6 1.1.0 a few days ago and started with a clean world as per the upgrade instructions.

However, since then, when a player try to enter the Nether, the server start lagging increasingly until it quickly hangs.  I upgraded to the 1.1.1 version this morning and we could reproduce the issue fairly easily.

**Server specs**
CPU: | Intel Xeon E3-1245 v2 - 3.4 GHz - 4 core(s)
RAM: | 32GB - DDR3
Hard Drive(s): | 2x 480GB (SSD SATA)
16GB are allocated to the server via the server-setup-config.yaml file

**Config**
I left all the mods config as default except that I enabled the home feature in maessentials
The server is set with a view distance of 5 (if it is useful)

**Troubleshooting**
There is not CPU busy time peak nor RAM capping when it happens.
I have archived the DIM-1 folder and have the server regenerate a new one several times
I disabled any external factor such as my prometheus minecraft exporter (running in docker)
I searched all over the internet for two day. I am really out of idea and need some help to determine if it could come from the modpack itself.

**Troubleshooting document**
I have attached logs + debug + crash report of the latest occurence of the issue.
[2020-10-10-1.log](https://github.com/AllTheMods/ATM-6/files/5359108/2020-10-10-1.log)
[debug-1.log](https://github.com/AllTheMods/ATM-6/files/5359116/debug-1.log)
[crash-2020-10-10_13.18.59-server.txt](https://github.com/AllTheMods/ATM-6/files/5359117/crash-2020-10-10_13.18.59-server.txt)

**Comment by whatthedrunk** [comment]
Going from 1.16.1 to 1.16.3 is not supported but  if you update to 1.1.2 and follow the pinned issue going from 1.16.2 to 1.16.3 it might work out for you.

**Comment by TheThirdBeast** [comment]
FYI I updated to 1.1.2 and so far the issue seems fixed. Thanks a lot!
