### ISSUE TITLE
Mekanism Plastic Blocks overide one another when used on FramedBlocks

### ISSUE THREAD

**Issue by JosieGr** [AllTheMods/ATM-6#1540]
Pack Version: AllTheMods6-1.6.1

**Describe the bug**
Mekanism Plastic Blocks fail to interact correctly with blocks from FramedBlocks that allow two alternate blocks as inputs. (The FramedBlocks slopes for example that only require one input block work just fine)

**To Reproduce**
1. Place the Framed Double Slope Block (From the FramedBlocks mod)
2. Right click one section of the Double Slope Block with one coloured Mekanism Plastic (From the Mekanism: Additions mod)
3. Right click the remaining section of the Double Slope Block with different coloured Mekanism Plastic
4. See error (Former applied block visually becomes the latter)

**Screenshots**
![2021-04-29_13 03 44](https://user-images.githubusercontent.com/83405142/116548016-8e1d5500-a8eb-11eb-8e45-ffbc3eb4ad6d.png)
![2021-04-29_13 03 48](https://user-images.githubusercontent.com/83405142/116548021-8eb5eb80-a8eb-11eb-8057-39436e3b69e1.png)
![2021-04-29_13 03 51](https://user-images.githubusercontent.com/83405142/116548024-8f4e8200-a8eb-11eb-8f07-be121b43ed61.png)

**Additional context**
Have not tried with any other variants of the Mekanism Plastic blocks.
Specifically tried with the Light Blue & Pink Plastic Block(s).

~~It appears that the colour overide is based on the colour of the block not which order they're placed. So pink will always overide white but light blue will always overide both pink and white, reguardless of which is place when/where. (At first glace, the overiding colours overide those that come after in in the JEI menu)~~

EDIT:

Further investigation seems to show that whatever block is placed in the lower block slot of the FramedBlock overites the other. Not based on their colour. (as shown in the screenshot) Appologies.

Thanks.

**Comment by XFactHD** [comment]
The fix for this will be included in the next version of FramedBlocks.
Next time you encounter an issue with FramedBlocks please feel free to also report this on my repository as well.
