### ISSUE TITLE
[ATM6-1.6.2]Thermal's Sulfer & Integrated Tunnels's Fluid Importer

### ISSUE THREAD

**Issue by NanJack1998** [AllTheMods/ATM-6#1543]
**Describe the bug**
In the latest version of ATM6,sulfer dust from thermal series can no longer used as the sulfer dust from Mekanism to make sulfer dioxide ; also the fluid importer will stop working when have chunk load issues

**To Reproduce**
1. geting the sulfer from thermal series and making the sulfer dust
2. puting sulfer dust into chmical oxidizer from mekanism

1.shutdown server/'singleplayer world'
2.relog the serverr/enter the singleplayer world
3.the fluid importer won't work

**Comment by ladylexxie** [comment]
No longer happening in current version.
