### ISSUE TITLE
World gen Related

### ISSUE THREAD

**Issue by lucastmendoncaf** [AllTheMods/ATM-6#1545]
**Describe the bug**
In lost cities the emerald ore spawn rate is considerable too low being kinda too rare and in mining dimension the spawn rate is normal.
in the stronghold the portal wasnt genereted and when throwing the ender eye, it was going under the bedrock
**To Reproduce**
Generating the worl using lost cities and trying to find the end portal, and finding emerald ores using the emeraldsight.

**Additional context**
Could be that especific world generating

if there is something writed wrong, i will fix

**Comment by ladylexxie** [comment]
Not all strongholds have a portal. That is a normal vanilla feature.
