### ISSUE TITLE
unable to start ATM6,5,4,3

### ISSUE THREAD

**Issue by zwish8** [AllTheMods/ATM-6#155]
**Describe the bug**
So everytime i try to start the modpack it closes as soon as it wants to open! i've tried repairing the file, i've tried reinstalling, i've tried deleting it in the folders and installing it again, and i have even reinstalled twitch, and it still didn't fix it, and it's not only with this modpack but also all the other ATM modpacks, i have a good pc so i can run it, i even gave it like 16 gb of ram still didn't do anything.

**Screenshots**
![](https://cdn.discordapp.com/attachments/390992748330614805/764518904272781332/unknown.png)

**Comment by Dragonlordhavoc** [comment]
go to your twitch\minecraft\install\versions and delete that verision of forge. then go to forge and download that version from them. then install that version of forge to your Twitch\minecraft\install. I have found this fix most of the Twitch minecraft modpack issues.

**Comment by zwish8** [comment]
Thanks man! i managed to fixed it doing this!
