### ISSUE TITLE
Server unable to start

### ISSUE THREAD

**Issue by Kookiesz** [AllTheMods/ATM-6#1554]
1.5.10b
I try to load up my server and it says this message: [08:18:06] [INFO] Server has been stopped, it has started 11 times in 60min
It then repeats trying to restart the server and then does the same message over and over again.

**To Reproduce**
1. Go to The server files
2. Click on Start server
3. Let server run and then says the message: [08:18:06] [INFO] Server has been stopped, it has started 11 times in 60min without it actually starting

Logs:
https://pastebin.com/nm1yEyXG

**Comment by Pdiddy973** [comment]
looks like some mods did not start correctly, best thing to do is do a fresh install, should resolve this
