### ISSUE TITLE
ATM6 to the sky 1.0.8 

### ISSUE THREAD

**Issue by MythsOfConfusion** [AllTheMods/ATM-6#1555]
ATM6 to the sky 1.0.8 
I can't use lava buckets on barrels from the exnihilosequentia mod, whether it's a wooden or a stone barrel, to fill it with lava.
Also I can't use pedestal upgrades like the cobble generator upgrade on the pedestal from the pedestals mod. It just gets placed on top of the pedestal instead, like every other item

**Comment by MythsOfConfusion** [comment]
Pipe the lava in works, at least with the pipez mod pipes

**Comment by sed-and-awk** [comment]
wrong git

**Comment by sed-and-awk** [comment]
https://github.com/AllTheMods/atm6-sky
