### ISSUE TITLE
Dupe Bug using DimStorage

### ISSUE THREAD

**Issue by Stinky-c** [AllTheMods/ATM-6#1558]
1.6.2 
Dupe bug using: Storage Drawers and DimStorage
A storage drawer and a dimensional chest duping up to a stack of items at a time

1. set up a dimensional chest with collecting mode enabled
2. place a drawer on any  and insert any item
3.  Watch as items are pulled into the chest but don't leave the drawer

**Comment by TheOnlyArtz** [comment]
Doesn't work!

**Comment by Daktyl198** [comment]
Can confirm this works in 1.6.7

**Comment by starforcraft** [comment]
Fixed in 1.6.8
