### ISSUE TITLE
Crash on Loading Modpack

### ISSUE THREAD

**Issue by Sparkmaster01** [AllTheMods/ATM-6#156]
just crashes when i try to load the modpack

Launch Modpack after downloading

the modpack should load

**Latest Log**
https://pastebin.com/NK9GXwXK

**Comment by Dragonlordhavoc** [comment]
Try this go to your twitch\minecraft\install\versions and delete that verision of forge. then go to forge and download that version from them. then install that version of forge to your Twitch\minecraft\install. I have found this fix most of the Twitch minecraft modpack issues.

**Comment by Sparkmaster01** [comment]
brill it worked, thankyou
i guess it was twitch's installation of forge that was bugging out then :)
