### ISSUE TITLE
My game freeze every 5 sec, I don't know which mod is causing this

### ISSUE THREAD

**Issue by da7431** [AllTheMods/ATM-6#1560]
Every time i play the game it seem to freeze on it self every 5 to 10 second and unfreeze. I don't know what causing this do you guys have and suggests

**Comment by localzuk** [comment]
This is usually due to not having enough RAM assigned to the pack - the freezing is the Java garbage collector running to free up RAM.

Try doubling the RAM you have assigned to the pack in the launcher.

**Comment by da7431** [comment]
how do Double the Ram in my Launcher?

**Comment by localzuk** [comment]
Open the pack screen in the CurseForge launcher, click the 3 dots next to Play and then click Profile Options. Untick the "Use System Memory Settings" box and change the slider to the amount of RAM you want to assign to the pack.
