### ISSUE TITLE
Mob Utilities - Saw / Mob Grinder

### ISSUE THREAD

**Issue by arialthesiren** [AllTheMods/ATM-6#1561]
Crashes when used with modded mobs. Appears fine with piglins, but armoured withers it can't handle.

The only way I found to get back into the server after a crash with it is to turn off mobs pawning and set it to peaceful to disable the spawner.

[crash-2021-05-04_09.40.00-server.txt](https://github.com/AllTheMods/ATM-6/files/6420265/crash-2021-05-04_09.40.00-server.txt)

**Comment by BovineShaman** [comment]
Problem non-existent in current version.
