### ISSUE TITLE
Nether Structure

### ISSUE THREAD

**Issue by DancingPotatoes** [AllTheMods/ATM-6#1562]
All the Mods 6 - To the Sky-1.0.9

is it possible to find nether structures such as a "Nether Fortress" because I was searching for a long time and I crossed one I got the achievement "A Terrible Fortress" with no fortress and gone in a creative world to check if it is possible to even find one and I used the command `/locate fortress` and tped there but no structure was found.

**Comment by thevortex** [comment]
you should be looking in 'The Other' for nether fortresses, no structures should appear in the nether in this pack.

**Comment by DancingPotatoes** [comment]
oh ok thank you
