### ISSUE TITLE
Builder does not skip Allthemodium when mining and comes to a complete stop

### ISSUE THREAD

**Issue by OmegaAlpha83** [AllTheMods/ATM-6#1564]
Pack version: 1.6.2  

when using the Builder To quarry out areas in the mining dimension when it comes across Allthemodium instead of skipping over it  it's  stops and doesn't continue until that block disappears or someone brakes it  I'm using a clearing Fortune Quarry card I think this is a bug because you can't Quarry in the  mining Dimension if it stops every time it comes across an allthemodium. and I know a Quarry mining allthemodium is disabled  I was  expecting it to skip over the ore like all the other quarry's do

**Comment by Pdiddy973** [comment]
press the hour glass icon on the builder for it to continue.
