### ISSUE TITLE
Creosote compatibility ATM 6 v1.6.2

### ISSUE THREAD

**Issue by Night-Fire** [AllTheMods/ATM-6#1565]
**Is your feature request related to a problem? Please describe.**
I would like to somewhat automate creosote oil (and treated plank) creation. The Pyrolyzer (Thermal Series) produce creosote oil from Thermal Series. However, only the Immersive Engineering creosote oil (made in a coke furnace, slower) works in the Dissolution Chamber (Industrial Foregoing).

**Describe the solution you'd like**
Make the pyrolyzer produce Immersive Engineering creosote oil instead of Thermal Series creosote oil.

**Describe alternatives you've considered**
Make the Dissolution Chamber use both creosote oils to produce treated planks.

**Comment by Pdiddy973** [comment]
Fixed for next update
