### ISSUE TITLE
Bees fight over same block when others are available

### ISSUE THREAD

**Issue by AndrewR73** [AllTheMods/ATM-6#1566]
I am playing the pack Sky Bees ("Final Version 3 fixed.zip") the current version of which is using ResourcefulBees-1.16.5-0.6.5b.jar

My question is why do the bees, inside the apiary, fight over the same block "flower" when there are more blocks (or actual flowers) present?

In this screenshot here, I have 2 bees of each type, with 2 blocks of each "flower" type as well. Despite that however, the bees will fight over the same block instead of one bee going to one block and the other bee to the other block.
![2021-05-04_16 38 33](https://user-images.githubusercontent.com/8558973/117160482-c22ec500-ad86-11eb-85c0-d55d527769e1.png)
*Note the Copper and Lead bees specifically in this shot

In this screenshot, in a different Apiary, instead of separating the blocks of the same type, I placed them together thinking maybe the bees would find/see them easier... but this was not the case. Again, the fighting over the same block(s) occurs:
![2021-05-05_09 40 14](https://user-images.githubusercontent.com/8558973/117162201-328a1600-ad88-11eb-8b6f-c2d5b433975a.png)
*Note the Wither bees head-to-head, and in the upper right the Zombie, Gravel, and Cobblestone bees are all fighting for the same poppy and bouncing off each other.

I have tried using the Dropper thingy to force the bees to use a specific block/flower, but give it 5 minutes and they are all back fighting each other again.

Is there some way to prevent this bee-havior?

**Comment by Pdiddy973** [comment]
Not our pack, updating RBees mod should help
