### ISSUE TITLE
Minecolonies pirate spawn crashes MP server

### ISSUE THREAD

**Issue by localzuk** [AllTheMods/ATM-6#1567]
Multiplayer server crashes whenever pirates spawn in a Minecolony. 

**To Reproduce**
1. Have a minecolony,
2. Build it to a level large enough to get pirate attacks
3. Have pirates spawn
4. Crash

**Additional context**
Running latest release version of the pack - 1.6.2.

**Logs**

latest.log - https://pastebin.com/WLnJNRKe

For some reason, there are 2 crashlogs for the same crash, spaced 64 seconds apart. Almost like the crash, crashed?

crashlog (first one) - https://pastebin.com/tq6eH9C5
crashlog (second one) - https://pastebin.com/YZpUqSKg

**Comment by ladylexxie** [comment]
That is caused by the server watchdog. You can try setting `max-tick-time` in `server.properties` to -1 to disable the watchdog.
