### ISSUE TITLE
ATM 6 getting sadistic

### ISSUE THREAD

**Issue by JKIceman** [AllTheMods/ATM-6#1568]
I like the ATM Packs for, well ALL THE MODS but recently the Pack creators are getting more and more sadistic, starting with the random bee receipes all the way to the creative Refined Storage receipes. When it started out, is was fun, but the more mods are getting finished, the more sadistic the pack gets. Is that accidentally or do the mod creators just want to f*** players as mutch as the can?

**Comment by Pdiddy973** [comment]
This isn't really a issue, more complaining....feel free to complain in our discord if you must
https://discord.gg/K5FBPYa
