### ISSUE TITLE
Astral Sorcery dupe

### ISSUE THREAD

**Issue by BaltimoreGamingYT** [AllTheMods/ATM-6#1578]
On version 1.08 but I'd assuming this still works on 1.09

When Astral Sorcery's Rock Crystal, Celestial Crystal, or Starmetal are in a chest, and you put one of Mekanism's cardboard boxes on the chest, it dupes those 3 items

1. Place chest
2. Put Starmetal in it
3. Put cardboard box on it
4. Profit.

https://i.imgur.com/qF5cvT5h.jpg
https://i.imgur.com/BxXCy7ah.jpg
https://i.imgur.com/RZTvG7zh.jpg

**Comment by DAmNRelentless** [comment]
This issue is a problem by Mekanism, it's submitted here: https://github.com/mekanism/Mekanism/issues/7053
It is already fixed in their dev version so we are waiting for a new release.
