### ISSUE TITLE
JEI wrong Certus Quartz Seed Recipe 

### ISSUE THREAD

**Issue by Zoriot** [AllTheMods/ATM-6#1579]
**Describe the bug**
JEI show's a wrong Recipe for the Certus Quartz Seed (Mystical Agriculture).
The JEI show's that you only need 4 Terium & the Seedbase to make a Certus Quartz Seed but ofc you need 4 Certus Quartz too.

**To Reproduce**
1. Go to the JEI
2. Search for '@My Certus Quartz Seed'
3. Go to Infusion Crafting
4. Try it out

**Screenshots**
https://i.imgur.com/j1SWi0I.png
https://i.imgur.com/K0ThuW0.png
https://i.imgur.com/kyQrC6y.png

**Comment by DreamingLamb** [comment]
Assuming you're playing on a server, if you are, try loading up a single player world, then go back to the server, should sort it out.

**Comment by DAmNRelentless** [comment]
Works fine
![](https://i.imgur.com/bdaRBK6.png)
