### ISSUE TITLE
Server crash Elementalcraft - All the Mods 6-1.1.2

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [AllTheMods/ATM-6#158]
**Describe the bug**
A player mentioned he casted some kind of scroll.

**To Reproduce**
A player mentioned he casted some kind of scroll.

**Expected behavior**
Not to crash the entire server

**Screenshots**
![image](https://user-images.githubusercontent.com/7256303/95674715-526ea800-0bb2-11eb-87aa-a33e6ec65860.png)

**Additional context**
Version: All the Mods 6-1.1.2

**Added issue to approporiate mod**
https://github.com/Sirttas/ElementalCraft/issues/5

**Comment by Sirttas** [comment]
fixed in elementalcraft: https://github.com/Sirttas/ElementalCraft/issues/5

**Comment by whatthedrunk** [comment]
Updated in 1.1.3 out later today.
