### ISSUE TITLE
Code Zero randomly during Gameplay & Loading Pack

### ISSUE THREAD

**Issue by WalrusLeviathian** [AllTheMods/ATM-6#1581]
Version: ATM 6-1.6.2

The game is code zeroing at seemingly random. I've done the basics, updated to newest compatible Java(curse is using it), updated windows, driver up to date, and ram allocated is 8GB.

**To Reproduce**

Load pack and will code zero at inconsistent moments.

**Additional context**

Code Zero does not seem to be pack specific, reported to overwolf/curse as well, hoping to see if anyone has a clue as to what is happening.

**Logs**
Please use a paste site for logs, instead of putting the file directly in the issue, not only is this easier but also means we can view on mobile when we are not at our computers.
Here's a list of some paste sites and their size limits:
https://gist.github.com/WalrusLeviathian/b7e6977091c89fc385a2c53b6c14141b

**Comment by starforcraft** [comment]
Use MultiMC or GD and use Java 11.
