### ISSUE TITLE
Pam's HarvestCraft 2 - foods to Egg? ATM 6 - Version - 1.6.2

### ISSUE THREAD

**Issue by GMGKenny** [AllTheMods/ATM-6#1582]
**Describe the bug**
A few items from PHC2 Crops and PHC2 Fruit Trees can be crafted into "fried egg" with the skillet, but I'm not sure they should be able to. Avocado, Banada, and Flax from PCH2 are the items in question. They all have the "forge:egg" tag when I view them with advanced tooltips enabled. See attached .gif for details.

**To Reproduce**
N/A

**Screenshots**
https://gyazo.com/20fbc44a9dcd46364a5e41762b4dc00e

**Additional context**
None

**Comment by whatthedrunk** [comment]
This is just a conflict for other recipes for those who want to play vegan I guess.
