### ISSUE TITLE
No Nether Fortress Spawning (Version 1.0.9 ATM6 To The Sky)

### ISSUE THREAD

**Issue by SophieFox23** [AllTheMods/ATM-6#1583]
<Pack version 1.0.9 (ATM6 To The Sky Minecraft version 1.16.5>
**No Nether fortresses spawn in nether even with Nether reset. Used a command to locate the nearest fortress and as I stood there, nothing generated in after multiple attempts in different locations**

**To Reproduce**
1.Generate World
2. Go to the Nether
3. Use the command "/locate Fortress"  and travel to location
4. No fortress spawning

**Logs**
Not quite sure what Logs would be needed to help with this.

(I apologize if there is anything else I missed or is needed, this is my first bug report)

**Comment by thevortex** [comment]
expected behaviour, structures do not and should not be spawning in the void, if you are looking for a nether fortress, they can be found in 'the other' dimension
