### ISSUE TITLE
Add tconstruct books to akashic tome

### ISSUE THREAD

**Issue by lmarianski** [AllTheMods/ATM-6#1585]
**Is your feature request related to a problem? Please describe.**
At the moment you can't add books from Tinker's Construct to the Akashic Tome, which i think should be the case (esp that there's like 4 of them)

**Describe the solution you'd like**
Add `tconstruct:materials_and_you`, `tconstruct:puny_smelting`, `tconstruct:mighty_smelting`, and `tconstruct:tinkers_gadgetry` to akashic tome config

**Comment by DAmNRelentless** [comment]
All of that info is basically included in Materials and You which is part of the Tome meanwhile.
