### ISSUE TITLE
MineColonies Courier AI issue involving pickup from the Cook

### ISSUE THREAD

**Issue by EvilGrinUK** [AllTheMods/ATM-6#1586]
I am using the latest ATM version (1.6.2) on my friends MP server.

**To Reproduce**
Steps to reproduce the behaviour:
1. Have a Minecolonies colony setup with couriers and a cook
2. Place an item in the cooks building inventory that shouldn't be there. Any non food item like cobblestone should be sufficient.
3. A courier will be given a task to clear out these item(s) and take them to the warehouse.
4. The courier AI will become stuck and unable to do anything until the error is manually cleared.

**Screenshots**

Screenshot of the courier error

![image](https://user-images.githubusercontent.com/2217729/117573936-9dae5200-b0d2-11eb-89ce-0ac446deff4a.png)

Task queue of broken courier

![image](https://user-images.githubusercontent.com/2217729/117574146-a3f0fe00-b0d3-11eb-8550-09d54c9224c8.png)

**Additional context**

I am unable to report this to minecolonies directly as we are quite a few versions behind and the first thing they are likely to will tell me to do is to upgrade the mod. 

**Logs**
Here is a link to the MP server latest.log provided to my by the operator from the time.

https://gist.github.com/EvilGrinUK/8a37d6eb643dad9fd5c25543831b9a7f

**Comment by NJM1564** [comment]
Have you tried updating the mod? :P

**Comment by whatthedrunk** [comment]
I'd you are still having issues on 1.6.5 please post to the minecolonies github and link back here. Thanks!
