### ISSUE TITLE
Server Crash ATM6 1.6.2

### ISSUE THREAD

**Issue by Random-Fun** [AllTheMods/ATM-6#1588]
**Describe the bug**
Server crash using the mob duplicator
**To Reproduce**
1. Capture a phantom
2. Put the mob imprisonment tool into the duplicator
3. Wait for it to attempt to spawn it in
4. Its gonna "overflow" and crash

**Screenshots**

**Additional context**
I tried to dupe the phantoms for membranes, and I crashed a priv server between me and my friend

**Logs**
Please use a paste site for logs, instead of putting the file directly in the issue, not only is this easier but also means we can view on mobile when we are not at our computers.
Here's a list of some paste sites and their size limits:
    https://pastebin.com/ 512KB
    https://hastebin.com/ 400KB
    https://gist.github.com/ 100MB Requires member (Free)
idk if I can get it my friend runs it

**Comment by mio9** [comment]
Do you have the server log? I dont seems to have this problem on my server

**Comment by Random-Fun** [comment]
According to my server op its because 
"Single server tick took 60 should be max 0.05"
He wont send me the server log

**Comment by Random-Fun** [comment]
i cant connect due to it saying "Internal Server Error"

**Comment by ladylexxie** [comment]
> "Single server tick took 60 should be max 0.05"

That is caused by the server watchdog. You can try setting `max-tick-time` in `server.properties` to -1 to disable the watchdog.
