### ISSUE TITLE
ATM6 Server Lagging Client Side 

### ISSUE THREAD

**Issue by shifter56** [AllTheMods/ATM-6#159]
**Describe the bug**
When I joined my server its lagging about 2-3 seconds. It always drops FPS from 200 to 48.

It seems when I got in a new chunk it makes lag spikes.

If you can help me add me on DC: hestegforce#9261

Thanks :)

**Comment by Marshmalllow09** [comment]
Having the same issue, posted an issue to the Dev directly. I am getting this error
[11Oct2020 18:40:58.000] [Worker-Main-42/ERROR] [com.telepathicgrunt.repurposedstructures.world.features.DungeonOcean/]: What in the world? The Ocean Dungeon attempted to spawn in a biome not registered in both the DynamicRegistries or WorldGenRegistries.
Please tell TelepathicGrunt (RepurposedStructures dev) this and tell him your mod list you have on.
For now, Ocean Dungeons will use repurposed_structrues:dungeon_ocean_misc mobs as fallback.

**Comment by shifter56** [comment]
Generate the map with your Client then load from the server and everything will be fine. 

It solved my problem.
Ui.: Change level type to default
