### ISSUE TITLE
Dread Beasts spawning out of control in the Nether - ATM 6 1.6.2

### ISSUE THREAD

**Issue by deggy42** [AllTheMods/ATM-6#1590]
**Describe the bug**
Dread Beasts are spawning at an insane rate in the Nether. I can run a /kill command and kill 700 of them, wait 10 seconds, run it again, and get over 100.  This is on a dedicated server running All The Mods 6 version 1.6.2.

**To Reproduce**
Enter the Nether. My portal generated in The Other, but the dread beasts are happy to spawn on any terrain they can. The only spawn rule they seem to respect is light. The Ice and Fire Discord says Dread Beasts aren't even supposed to be spawning in the Nether.

**Screenshots**
![image](https://user-images.githubusercontent.com/83977834/117702795-fcd59a80-b196-11eb-9266-255df4e30e50.png)

**Additional context**
I'd be happy with the ability to completely disable Dread Beast spawns - I just want to be able to play in the Nether without stopping to ruin an op command every few seconds.

The only change I've made to config files disabled MineColonies raiders due to a crash when pirate ships show up.

**Logs**
I'm happy to upload relevant logs if they're needed, but I'm not sure which logs would help with this.

**Comment by thevortex** [comment]
1.6.3 update lowers the weight for the dread beast spawns, update and see how it goes, re-open if issue persists

**Comment by MSLcz** [comment]
Iam still having the same issue on my server running on 1.6.3c
