### ISSUE TITLE
1.6.3 update chisel and bits

### ISSUE THREAD

**Issue by HRJDragon** [AllTheMods/ATM-6#1594]
Chisel and bits versions of modded blocks mostly shifted to a different texture on updating the official second atm6 server (with some cases creating visual bugs) while retaining the same shape, while some non modded chisel n bits blocks stayed the same. Can add photo of after but I did not screenshot before but the glitched texture is there

**Comment by whatthedrunk** [comment]
Yeah it's a pain when the shift happens. Hopefully going forward it won't happen.
