### ISSUE TITLE
ATM6 1.6.3 ResourcefulBees Problems

### ISSUE THREAD

**Issue by Shadowkueken** [AllTheMods/ATM-6#1596]
**Describe the bug**
I noticed some problems with ResourcefulBees after updating to 1.6.3 , these were not present yesterday/on the previous versions:
- The Centrifuge doesn't process certain Honeycombs anymore, checking with JEI showed that the recipes are missing (Problem found with Aquamarine Bee, Draconic Bee, Withered Bee, Wither Bee)
- The Breeding Path on some Bees was removed, but the JEI Information Tab still cites these (Example would be Blazing Bee, the Information Tab still states Magma Bee x Skeleton Bee as parents, but these won't breed a Blazing Bee anymore)
- Some Bees were removed from the world, this was noticed with Beepers, Leafy Bees, Warm Bees and Zombees (all these types of Bees vanished from their enclosure in my Beefarm and during a 30 minute search in the spawn zones of said bees I couldn't find even a single one of any of them, which leads me to add this to this post)
- An actual game crash could be reliably triggered with the Beepedia

**To Reproduce**
Steps to reproduce the crash:
1. Open Beepedia
2. Look for the Aquamarine Bees entry
3. Open it and try to view the Traits section
4. The game crashes even before opening the section

While writing this I realized that I should have tested whether or not this crash would occur when I go to the trait section and try to open the trait the Aquamarine Bee probably has. Sorry for that.

**Additional context**
I should note that I noticed these problems on my own Server which I updated to 1.6.3 just today. I asked in the discord whether or not someone had noticed something similar and after getting a confirmation I decided to report this.

**Comment by AYSIK0** [comment]
The fridge which is the flower for the "KoBee Beef" needs the valid_apiary tag.

**Comment by whatthedrunk** [comment]
1.6.3b will be out any minute with just bee fixes.
