### ISSUE TITLE
Failed to sychroize registry data from server, closing connection 

### ISSUE THREAD

**Issue by gogocruz** [AllTheMods/ATM-6#1597]
I passed the map to the new version and this error started to appear, I tried to open a new map and it worked on that map. Help-me

**Comment by jbreckel** [comment]
this also happend in our 1.6.1 world.
server was running fine yesterday, and today no one can connect.
mods and config is the same (except client only).

have there been some OTA updates?

**Comment by gogocruz** [comment]
That we can detect no

**Comment by gogocruz** [comment]
> this also happend in our 1.6.1 world.
> server was running fine yesterday, and today no one can connect.
> mods and config is the same (except client only).
> 
> have there been some OTA updates?

I don't know if it is, but I changed the name and icon of the server in this version transition

**Comment by radiomike** [comment]
Try deleting the icon. That can cause issues. 

Otherwise it'll be probably be a mismatch of config files. 

If you've got a crashlog or relevant `latest.log`that you can attach, or link to that would be helpful.

**Comment by jbreckel** [comment]
the issue was solved for me by rerunning the serverstarter in a new folder, copying any extra mods and modified config and the world folder.

somehow that did the trick.
