### ISSUE TITLE
Newest version of Pneumaticcraft: Repressurized not in latest modpack

### ISSUE THREAD

**Issue by Juicebox360** [AllTheMods/ATM-6#1603]
All the Mods 6-1.6.3 contains PNC:R version 1.16.5-2.12.1-177 whereas the latest is 1.16.5-2.12.1-184

**Comment by whatthedrunk** [comment]
No need to let us know when mods update. This will make it in 1.6.4.

**Comment by Juicebox360** [comment]
Then why write "• Updated All the Mods" when you haven't even done so?!?! I was really looking forward to the new version of PNC:R because it fixed interoperability of Lubricant fluids from Immersive Engineering/Petroleum. At least take off the misleading "updated all the mods" when clearly, that wasn't the case.
