### ISSUE TITLE
Can't add Tinkers' construct book to Akashic int ATM 1.6.3

### ISSUE THREAD

**Issue by HelpImDying** [AllTheMods/ATM-6#1604]
All the Mods 6 1.6.3 

when trying to add books to he Akashic Tome non of the tinkers' construct books can be added.

when get any of the books from tinkers' construct (Materials and you, Puny smelting, Mighty Smelting, and Tinker's Gadgetry) ore place in  a crafting table with the Akashic tome it doesn't produce a product.

<img width="121" alt="Screenshot 2021-05-12 141822" src="https://user-images.githubusercontent.com/41140563/118032435-4b1ca200-b32d-11eb-9243-bf0e01616bec.png">
<img width="128" alt="Screenshot 2021-05-12 141846" src="https://user-images.githubusercontent.com/41140563/118032532-67204380-b32d-11eb-9229-fdd6b7150e45.png">
<img width="128" alt="Screenshot 2021-05-12 141907" src="https://user-images.githubusercontent.com/41140563/118032533-67204380-b32d-11eb-8fa8-fdd445aac022.png">
<img width="121" alt="Screenshot 2021-05-12 141929" src="https://user-images.githubusercontent.com/41140563/118032535-67b8da00-b32d-11eb-9db7-7e70387867a9.png">

**Comment by ladylexxie** [comment]
This isn't a bug, its how the book is made by TC. It's not compatible with Akashik Tome.
