### ISSUE TITLE
ATM 6 (1.6.3c)Twilight portal not working on latest version.

### ISSUE THREAD

**Issue by Adamadi4060** [AllTheMods/ATM-6#1608]
![2021-05-13_20 23 43](https://user-images.githubusercontent.com/47460456/118174497-2f99c000-b42f-11eb-83bc-acf690f16fe6.png)
![2021-05-13_20 23 51](https://user-images.githubusercontent.com/47460456/118174500-30325680-b42f-11eb-9cc8-4ebfdd00f3f1.png)

Worked before update.

**Comment by thevortex** [comment]
biomes o plenty worldtype?
