### ISSUE TITLE
Extreme Serverlaggs and Freezes

### ISSUE THREAD

**Issue by Cratios** [AllTheMods/ATM-6#1609]
Hello!

I have a big Problem with ATM6 Version 1.6.3 on Minecraft 1.16.5

i have the Pack installed on Minecraft EPS-Server with 26GB RAM. 
The Problem is, that the Modpack uses all the RAM and ingame we have Laggs, Freeces and „Waiting for Server“

We have nothing built yet and just one Chunk loaded

**Comment by starforcraft** [comment]
Send Spark
