### ISSUE TITLE
[Bug] Mekanism block Ultimate Smelting Factory causes crashes after update

### ISSUE THREAD

**Issue by se7envlad** [AllTheMods/ATM-6#161]
Here is the crash log, I removed the block serverside but it's still a problem if I want to use the block in the future.
https://pastebin.com/KQQNswyz

**Comment by se7envlad** [comment]
Keeps happening with the same block: mekanism:ultimate_smelting_factory and every time the effected player joins they crash

**Comment by jeremiahwinsley** [comment]
Assuming this is fixed in the current version of the pack, 1.3.9. Please reopen if you still have this issue.
