### ISSUE TITLE
Why will a server not start, getting the following error

### ISSUE THREAD

**Issue by HaHaItsAGiraffe** [AllTheMods/ATM-6#1610]
![image](https://user-images.githubusercontent.com/84156490/118190241-1299c880-b400-11eb-80cc-13067bc695ec.png)

**Comment by jeremiahwinsley** [comment]
Server install did not complete correctly, reinstall it. 
Make sure you have third party antivirus disabled as mentioned in the install guide: https://github.com/AllTheMods/ATM-6/wiki/Installing-A-Server 

Post the `serverstarter.log` file if it does it again.

**Comment by stevewatkins22** [comment]
I had the same issue, I had to update to the latest version of java to fix it
