### ISSUE TITLE
The Other

### ISSUE THREAD

**Issue by Uhbandon** [AllTheMods/ATM-6#1613]
How do you mine the majority of "The Other" ores? Such as Other Diamond Ore, Other Iron Ore. These are unable to be mined with a vibranium pickaxe, what can they be mined with?

**Comment by thevortex** [comment]
unobtainium tier will work!

**Comment by thevortex** [comment]
mining gadgets will also work, but are slower

**Comment by Uhbandon** [comment]
> mining gadgets will also work, but are slower

Thank you, I'm still a ways away from having unobtanium tools, the mining gadget is doable though. Thank you!
