### ISSUE TITLE
When trying to create stone bricks in RS crafter it gives Eidolon version

### ISSUE THREAD

**Issue by NunbearTWITCH** [AllTheMods/ATM-6#1614]
**Describe the bug**
I was trying to set auto crafting for cracked stone bricks using refined storage but the result gives the Smooth Stone Bricks instead which cannot be used for cracked stone bricks in auto crafting

**To Reproduce**
Create stone brick recipe in RS
Use recipe
Result is wrong type of brick

**Screenshots**

**Additional context**
Can show this live on stream nunbear.twitch.tv

**Logs**
Please use a paste site for logs, instead of putting the file directly in the issue, not only is this easier but also means we can view on mobile when we are not at our computers.
Here's a list of some paste sites and their size limits:
    https://pastebin.com/ 512KB
    https://hastebin.com/ 400KB
    https://gist.github.com/ 100MB Requires member (Free)

**Comment by NunbearTWITCH** [comment]
Sorgot to say ATM 6 1.6.3c version on server

**Comment by starforcraft** [comment]
Use Exact Mode
