### ISSUE TITLE
RFTool Dimension are broken

### ISSUE THREAD

**Issue by domenicop-1991** [AllTheMods/ATM-6#1616]
Pack version: All the Mods 6-1.6.3c

After upgrading from 1.6.2 to 1.6.3c all dimensions created with RFToolDimension have been deleted

![2021-05-14_18 40 47](https://user-images.githubusercontent.com/77362946/118303213-7a760f00-b4e5-11eb-9587-a0ec75c89ad8.png)

**Comment by ladylexxie** [comment]
No longer seems to be happening.
