### ISSUE TITLE
No Recipe Uses for Nitro Crystal Essence

### ISSUE THREAD

**Issue by ThomazM** [AllTheMods/ATM-6#1619]
Nitro Crystal Essence has no current use in recipes, rendering it is impossible to craft Nitro Crystal using them.
Yes, I'm using a Crux, the seed is generating essence perfectly fine. The only issue here is the lack of an actual recipe to craft the Nitro with.

Pack version: 1.6.3

Screenshot:
https://i.imgur.com/se2XFui.png

**Comment by DAmNRelentless** [comment]
Seed is no longer in the pack.
