### ISSUE TITLE
Purification chamber not accepting all ores

### ISSUE THREAD

**Issue by alextunbridge67** [AllTheMods/ATM-6#162]
**Describe the bug**
Purification chamber doesn't accept all ores.

**To Reproduce**
Use purification chamber, try adding silver, nickel, platinum, or even crimson iron ores. I may be missing some.

**Expected behavior**
It should process the ore as expected.

**Screenshots**
https://i.imgur.com/tX5HSLA.png

**Additional context**

**Comment by WhitePhant0m** [comment]
Not really a bug, we just haven't made custom fluids/gases mekanism needs to process those.

**Comment by WhitePhant0m** [comment]
We'll either add them by ourselves or wait for JAOPCA to update sine it does it automatically for almost all ores

**Comment by whatthedrunk** [comment]
We will need to work on the textures but these work now.
