### ISSUE TITLE
1.6.3c Crashes from Integrated Dynamics/Tunnels/Crafting

### ISSUE THREAD

**Issue by radiomike** [AllTheMods/ATM-6#1623]
**Describe the bug**
World crash caused by Integrated Tunnels. Can occur seemingly at random, but also when braking ID blocks/networks. 
**To Reproduce**
Upgrade to 1.6.3c with ID networks in world
Either wait, or break ID block.

**Screenshots**

**Additional context**

https://github.com/CyclopsMC/IntegratedTunnels/issues/227

Bug is fixed upstream, latest versions of mods available on curse. Just tested on server, with existing world and no crashes.

**Logs**
See ID bug report - my logs were same error.

**Comment by spdkils** [comment]
There is also deadlocks with integrated Dynamics.... I had to update my server to the newer build, the auto crafting was killing a server once an hour...

**Comment by spdkils** [comment]
https://github.com/CyclopsMC/IntegratedCrafting/issues/62
