### ISSUE TITLE
1.6.3c dedicated server crash on start

### ISSUE THREAD

**Issue by Thanolion** [AllTheMods/ATM-6#1629]
Pack version 1.6.3c
Hi there,

I've just updated my dedicated server to version 1.6.3c, running on a windows server. It crashes on startup now. I have to open up a cmd in administrator mode and run the "startserver.bat" that way in order for the game to launch. Otherwise I get the attached log output. Any reason why?
[debug-1.log](https://github.com/AllTheMods/ATM-6/files/6489294/debug-1.log)

**Comment by Scarlet-Phonavis** [comment]
The folder you're using requires administrator access do to the inbuilt permissions system in your OS.

Regardless of what you run there, it will require admin to run to access files there, or even if ran outside and accessing that location. 

In other words, move it somewhere where you don't need admin access to modify, or modify the permissions of the folder itself (google it) 

Keep in mind this permission structure is there to prevent malicious programs from accessing/overwriting files so don't unprotect more than you need to. If you just feel like moving it somewhere, a quick way to check is to see if a permissions prompt shows up (in Windows) when you attempt to create a new folder. I don't know much about Linux, but it should generally be the same.
