### ISSUE TITLE
1.16.3 loading nether takes too long

### ISSUE THREAD

**Issue by rikislief** [AllTheMods/ATM-6#163]
We played 1.16.2 before, but started a new 1.16.3 server of ATM 6 1.1.0

When we enter a nether portal, sometimes it works, but most of the time it gets stuck on "loading terrain". Before the loading is finished, the portal already tries to send us back to the overworld. Upon arriving in the overworld, we get damage or die (suffocated in a wall). 

What i wanted, was to just be sent to the nether without delay, so i could grab me some soulstone.

I believe this is another issue than the pinned one, because sometimes we are able to go to the nether.

**Comment by whatthedrunk** [comment]
I can't seem to reproduce this on current versions. If this is still an issue on a new world on the newest version let me know and I will try more to reproduce it. Thanks!
