### ISSUE TITLE
Early-game Ore Quadrupling

### ISSUE THREAD

**Issue by awebneck** [AllTheMods/ATM-6#1630]
One can easily quadruple ores in the early game via the following process:
1. 1 Metal Ore -> Elementalcraft Ore Purifier => 2 Elementalcraft Pure Ore Chunk
2. 2 Elementalcraft Pure Ore Chunk -> Mekanism Enrichment Chamber/Factory => 4 AllTheOres Metal Dust
3. 4 AllTheOres Metal Dust -> Any Smelter => 4 Metal Ingots 

I could be mistaken, but this feels OP for the stage of the game at which the required machinery can be built and powered. Obvious solution would be to prevent Mekanism Enrichment chamber from producing 2 dusts from 1 Elementalcraft pure ore chunk.

Found and reproducible on ATM6 version 1.6.3c

**Comment by Sirttas** [comment]
It's an intended feature if elemental craft
