### ISSUE TITLE
Charged Certus Quartz Duplication Glitch

### ISSUE THREAD

**Issue by fullsets** [AllTheMods/ATM-6#1631]
**Describe the bug**
Using a Cardboard box from Mekanism in a chest containing charged certus quartz will cause the charged certus quartz to duplicate

**To Reproduce**
1. Place Charged Certus Quartz in a Chest
2. Use a Cardboard box (Mekanism) in the chest
3. The same amount of Charged certus quartz that was in the chest will pop out
4. Remove the cardbox
5. Note that the charged certus quartz you placed in the chest will still be there

**Screenshots**
https://imgur.com/a/e9ZeyJj

**Additional context**
Done on latest version (1.6.3c) , same problem happens on chests from the Iron Chests mod

**Comment by Mightylight** [comment]
think it's the same as this. #1578

**Comment by DAmNRelentless** [comment]
This issue is a problem by Mekanism, it's submitted here: https://github.com/mekanism/Mekanism/issues/7053
It is already fixed in their dev version so we are waiting for a new release.
