### ISSUE TITLE
Dragonic Bee not pollinating in 6-1.6.3c

### ISSUE THREAD

**Issue by JerseyStumps** [AllTheMods/ATM-6#1633]
As stated in the title the Dragonic Bee from the Resourceful Bees mod is not pollinating in 6-1.6.3c. I tried initally with the dragon egg due to the actual flower entry being missing from JEI. I since checked the actual .json config for the bee and it claims the flower is minecraft:end_crystal. I have also tried placing one of those in the apiary but the bee just ignores it.

I suspect due to its absence from JEI that perhaps it is bugged?

**Comment by starforcraft** [comment]
Fixed in the next Version. (It will be changed to End Stone)

**Comment by Pdiddy973** [comment]
fixed in https://github.com/AllTheMods/ATM-6/pull/1627
