### ISSUE TITLE
Resourceful Bees - Centrifuge recipe for Soul Lava does not exist.

### ISSUE THREAD

**Issue by rhpeZ** [AllTheMods/ATM-6#1634]
Pack Version 1.6.3c

**Describe the bug**
When pressing U on the Soul Lava honeycomb and honeycomb block it does not show a centrifuge option to process the combs into Molten Soul Lava like in pack version 1.6.2. I have tried adding it to the centrifuge in case it was a JEI bug, but no it does not process the combs.

**To Reproduce**
Steps to reproduce the behaviour:
1. Search for Soul Lava in JEI
2. Press U or Right Click over Soul Lava Honeycomb
3. No processing recipe exists to convert into Molten Soul Lava.

**Additional context**
Nothing custom has been done, I updated my pack version and noticed that the recipe was missing. I have tried reinstalling the pack and this does not work.

**Comment by starforcraft** [comment]
Fixed in newest Version
