### ISSUE TITLE
Ancient Debee Not Obtainable

### ISSUE THREAD

**Issue by augustclear** [AllTheMods/ATM-6#1635]
Currently playing on version 6-1.6.3c and as far as I can tell there is currently no way to obtain it. It does not spawn in nature and there is no breeding recipe for it

**Comment by lazystudent3** [comment]
@augustclear  Hello, I am also playing on 1.6.3c and there is recipe for this bee in my case. It is true its hidden a little but there is a way to get it. First of all, you will get this bee from the spawn egg, and this egg you will obtain from mutation of block done by Gold Bee (Go into Gold Bee and check mutations). I highly recommed you to use beepedia.

**Comment by Eden-817** [comment]
I am also having the same issue. I have even tried placing a gold honeycomb block down for the gold bee to try and it is not interested in either netherite block or the comb block.

**Comment by lazystudent3** [comment]
@Eden-817 The problem with mutation is that they HAVE to use their flower ( in case of gold bee its block of gold ) and then when they come back to hive/apiary they are "droping" small particles of pollen they harvested from flower. When this pollen drop on block of netherite, block should disappear and leave either cobblestone (80 %) or Bee spawn egg. T
