### ISSUE TITLE
Crafting Station GUI Problem

### ISSUE THREAD

**Issue by araines716** [AllTheMods/ATM-6#1639]
When placing a crafting station, from Tinkers Construct, beside a chest the sorting buttons and the chest filter button appear out of place, preventing proper crafting. 
![2021-05-17_20 42 12](https://user-images.githubusercontent.com/84361057/118577709-887b9800-b750-11eb-97c7-ebc0d0f34e86.png)

**Comment by RavenCGN** [comment]
Same problem here. Running ATM 1.0.9.

**Comment by whatthedrunk** [comment]
Fixed in dev. After next update use the keybind.
