### ISSUE TITLE
Mahou Tsukai The Ripper /shader effect? Kills Performance

### ISSUE THREAD

**Issue by compao123** [AllTheMods/ATM-6#164]
Using the right click ability of the dagger(s) The Ripper from the mod Mahou Tsukai kills performance, dropping the frames of your client (and everyone nearby if playing on a server) to sub 1 fps for the duration of the mist it spawns. The mod and the ability itself works just fine on its own so there must be something conflicting with the shader/effect that "spawns" when using the ability

Equip either one or two (doesn't matter) of the weapon The Ripper and right-click

**Expected behaviour**
the effect goes through without much of a performance impact (would be fine if there was one but sub 1 fps is ridiculous)

**Additional context**
I've spoken to the dev/reported it on their discord and they reported it was working fine otherwise, they also downloaded ATM6 to test the issue and verified that it occurs in the modpack.

i tried a clear install / profile with only the mod (mahou tsukai) and forge installed and everything worked fine.

since I have no experience with modding I've got no idea what might be causing this

**Comment by stepsword** [comment]
Seems to be a conflict with Immersive Engineering, after some testing. On my PC fps goes from 200->90 when using the fog, but with Mahou and Immersive Engineering installed (no blocks placed or anything), it goes from 200->0.  200->90 isn't great, and I'm hoping to remedy that, but it's at least still playable.

**Comment by stepsword** [comment]
Couldn't find what's causing the extra FPS drop when IE is installed, but I pushed a fix (Mahou v1.24.1) for some unoptimized stuff on my end. At least on my PC, it no longer goes to 1 FPS and is playable now when both mods are installed

**Comment by jeremiahwinsley** [comment]
Pack version 1.3.9 includes this patch, marking this as fixed.
