### ISSUE TITLE
ATM 1.6.3c / Broken Stronghold

### ISSUE THREAD

**Issue by Messorow** [AllTheMods/ATM-6#1640]
Second stronghold, which i founded is broken and dont have end portal. Eye of Ender tracking me under the bedrock, and when i broke the bedrock (dont ask me how), there nothing down there. Its feature or bug? Please help me to understand.
![123](https://user-images.githubusercontent.com/84205322/118652471-4c4b4480-b7ef-11eb-81af-8308d08b6681.png)

**Comment by jeremiahwinsley** [comment]
Eye of Ender takes you to the stronghold, not the end portal. Sometimes strongholds are broken due to world gen. Nothing we can do about it.
