### ISSUE TITLE
Akashic Tome quest doesn't contain any books (missing NBT data).

### ISSUE THREAD

**Issue by codecnotsupported** [AllTheMods/ATM-6#1642]
**ATM6** 
Version: 1.6.3c

**Describe the bug**
The Akashic Tome given by the FTB quest doesn't contain any books.
My guess is that it doesn't contain any books by default and you have to give a book with NBT data containing all the books.
Offending lines of code: 
https://github.com/AllTheMods/ATM-6/blob/c228d4d4cd58415e4b3bc4363a4718b4dbf537c9/config/ftbquests/quests/chapters/starting_off.snbt#L122

**To Reproduce**
Complete the FTB quest for the Akashic Tome by crafting a book.
Get the reward, a Akashic Tome.
It's empty while the quest states it should be full. 
"Completing this gives you a full akashic tome. That means every book in the game, in one book"

**What did I try**
Enter into ftbquest editmode by running this command `/ftbquest editing_mode`
Search for manual books in JUI.
Hint: some of them have these words in their name:
```
        book
        tome
        lexicon
        nomicon
        manual
        knowledge
        pedia
        compendium
        guide
        codex
        journal
```
Add them to your inventory, put them into the tome by putting them together in the crafting table.
If you don't get the tome it means it's not whitelisted, see #1585. Add them to the white list.
If you have all the manuals you want select the tome and run the command `/data get entity @s SelectedItem`
Then in your minecraft log you should see this 
```[minecraft/NewChatGui]: [CHAT] Player has the following entity data: {id: "akashictome:tome", Count: 1b, tag: {"akashictome:data": {ars_nouveau: {id: "ars_nouveau:worn_notebook", Count: 1b}, astralsorcery: {id: "astralsorcery:tome", Count: 1b}, cookingforblockheads: {id: "cookingforblockheads:recipe_book", Count: 1b}, cyclic: {id: "patchouli:guide_book", Count: 1b, tag: {"patchouli:book": "cyclic:cyclic_guide_book"}}, solcarrot: {id: "solcarrot:food_book", Count: 1b}}}}```

--- 
It might not be possible to add NBT data through the FTB quest GUI. (Enter FTB quest and edit reward by right clicking on it -> edit -> Tags)
It might be possible to add it manually though. However I an not sure in what format. 
https://github.com/AllTheMods/ATM-6/blob/c228d4d4cd58415e4b3bc4363a4718b4dbf537c9/config/ftbquests/quests/chapters/starting_off.snbt#L133

This might be of use:
https://minecraft.fandom.com/wiki/Tutorials/Command_NBT_tags

**Comment by NJM1564** [comment]
You combine the The Akashic Tome with books you get in the crafting window. This is it's normal behavior. Coming with books pre loaded is a pack makers optional extra.

**Comment by codecnotsupported** [comment]
I think you missed the part where the quest says:
"Completing this gives you a full akashic tome. That means every book in the game, in one book"

**Comment by whatthedrunk** [comment]
New version doesn't have that quest but when added back will fix.
