### ISSUE TITLE
Honey Bucket Dupe

### ISSUE THREAD

**Issue by min0set** [AllTheMods/ATM-6#1643]
ATM6
Version: 1.6.3

Issue:
Converting Honey Bucket from Cyclic to Honey Bucket from Resourceful Bees dublicates bucket.

**To Reproduce**
1. Get a Honey Bucket from Honey Tank(You will get Honey Bucket from Cyclic)
2. Craft Honey Bucket from Resourceful Bees by putting Honey Bucket to crafting table.
3. Converting is successful but you get another empty Bucket.

I assume this is a bug, not a recipe

**Comment by ladylexxie** [comment]
No longer applicable
