### ISSUE TITLE
1.6.3c When updating, removed bees or bees with changed id's are stuck in hives

### ISSUE THREAD

**Issue by radiomike** [AllTheMods/ATM-6#1644]
**Describe the bug**
Updated from 1.6.1 to 1.6.3c. Noticed a lot of 
```[23:24:16] [Server thread/WARN] [minecraft/EntityType]: Skipping Entity with id resourcefulbees:leafcutter_bee```
appearing in the server logs. Seems that various bees are now stuck in hives and can't make it into the world where they'll be removed.

**To Reproduce**
1. update to 1.6.3c from earlier version - in my case 1.6.1
2. observe logs
3. See the above error.

**Screenshots**
None applicable

**Additional context**
Initially thought it was just leaf_cutter bees, so went through with nbtexplorer and removed all of those entities. Seemed to improve performance doing so. Have since noticed, from travelling the world that this also applies to other bees. 
Also applies to;

Zombie_bee
Skeleton_bee
Creeper_bee
Warm_bee

And probably more, but not observed them in my logs so far.

**Logs**

**Comment by LockedThread** [comment]
The bee entity id was changed in the bee mod, there's nothing you can really do to fix this. This is not a bug, this is a mod-related breaking change.

**Comment by whatthedrunk** [comment]
Bee fixes should all be done now so hopefully nothing in the future.
