### ISSUE TITLE
Addition of the mod "Create Crafts & Additions" to ATM 6

### ISSUE THREAD

**Issue by idkwhyievenhavegithub** [AllTheMods/ATM-6#1645]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The solution to this is the addition of the mod "Create Crafts & Additions" It adds some great features to create such as the ability to use convert normal electricity (RF and such) to Kinetic (create energy) and vice versa. so it unlocks a bunch of different possibilities for machines and power generation. The link to this mod is https://www.curseforge.com/minecraft/mc-mods/createaddition

**Comment by whatthedrunk** [comment]
Will look into it but for future reference https://github.com/AllTheMods/ATM-6/issues/144
