### ISSUE TITLE
Ebony wood stairs not craftable

### ISSUE THREAD

**Issue by xelekgamez** [AllTheMods/ATM-6#165]
**Describe the bug**

**To Reproduce**
1. Get ebony wood and planks
2. Use the wood to attempt to craft stairs
3. Question if you messed up a simple recipe, check jei
4. Notice that it requires ebony stairs to craft ebony stairs
5. Be really confused

**Screenshots**
![image](https://user-images.githubusercontent.com/72847076/95942075-46503980-0db0-11eb-8c2b-950e1bcfab19.png)

![image](https://user-images.githubusercontent.com/72847076/95942119-5ec05400-0db0-11eb-81f9-5cfc4ae00af3.png)

**Additional context**
It doesn't seem like the other stairs from byg have this issue

**Comment by Jkwolf25** [comment]
I would like to add that Redwood wood (bark on all sides) and its stripped variant from BYG is uncraftable. JEI does not offer a recipe for the BYG Redwood either. BOP Redwood has a recipe for both the redwood wood and stripped redwood wood.

**Comment by WhitePhant0m** [comment]
I've reported this to BYG dev, we'll get a fix later

**Comment by whatthedrunk** [comment]
Fixed in 1.1.4 out soon
