### ISSUE TITLE
[Minor Bug] Duplication of Chisels using the Chiseled mod

### ISSUE THREAD

**Issue by DaRandom** [AllTheMods/ATM-6#1650]
There is a duplication bug with chisels when using the Smithing Table to apply the indestructible enchantment using an Eternal Stella from _Forbidden & Arcanus_. Applying enchantments through the anvil works as expected however.

## **How to Reproduce**
1. Acquire a Chisel (from _Chiseled_) and an Eternal Stella (from _Forbidden & Arcanus_)
2. Open the Smithing Table interface and apply the Eternal Stella as you normally would with anything you want to be indestructible.
3. You're now left with a chisel that has lost 1 point of durability, as well as a chisel that inherited the durability from the one you applied the enchantment to.

## **Expected Outcome**
The chisel should not duplicate.

Bug reporting for the mod is handled on their Discord server. It can be found [here](https://discord.gg/2wQhpMkkUH). I'm making this issue report for reference.

**Comment by DaRandom** [comment]
I found another issue.

Breaking the block while a chisel is in inside deletes it.

**Comment by ladylexxie** [comment]
Current version of the pack removed Chiseled in favor of Chisel.
