### ISSUE TITLE
Flux Power in other dimensions

### ISSUE THREAD

**Issue by Eden-817** [AllTheMods/ATM-6#1652]
Working in 1.6.3c. I have tried going into the nether and use Flux wireless charging power it is not working. I thought I had to create another wireless charging station and power supply. So I did that and it does not charge any of my items. I double checked to make sure the hands and suite is highlighted and the slider to be enabled and clicked apply. I also try using a Flux Point and that does not work either. When in the nether I also tried creating a new nether network still did not work. I can take thermo power plant and move it around in the nether and it provides power.
Wireless does work in the overworld just fine.

**Comment by LockedThread** [comment]
@Eden-817 That's odd because on my smp server - albeit on version 1.6.4 - flux points work fine.

**Comment by Eden-817** [comment]
I have the power source and the wireless charging flux object chunk loaded in the map. But when I go into the flux network options and try to toggle the chunk load option it says that it was disabled. Is that the same behavior that you get? I am still a little green. Only started playing moded about a year ago. Anything else that you can think I an try? With my world when I go into the mining dimension things that I have listed to chunk load are not loaded when I am not in that world. Not sure if the issue I am having is that the power source and items are in overworld and they do not traverse to nether, end, or mining. I have not been anywhere else yet.

**Comment by whatthedrunk** [comment]
Enable chunkloading in the server and client config and it will work.
