### ISSUE TITLE
Allthemodium crash while loading the game.

### ISSUE THREAD

**Issue by ArashkInGithub** [AllTheMods/ATM-6#1655]
I'm not using the ATM modpack so I apologize. When I updated the mods on my modpack, the game would crash when it got to the "Constructing mods" section. I did a binary debug and can confirm the problem isn't with a mod conflict. So I assume the issue is with the new forge version since I updated forge too.

Forge version: forge-1.16.5-36.1.23
Mod version: allthemodium-1.4.4-1.16.5-36.1.0 AND allthemodium-1.4.5-1.16.5-36.1.0
Crash report: [crash-2021-05-20_20.03.21-client.txt](https://github.com/AllTheMods/ATM-6/files/6517984/crash-2021-05-20_20.03.21-client.txt)

**Comment by thevortex** [comment]
you have two versions of the same mod, remove the 1.4.4 version and try again :)

**Comment by ArashkInGithub** [comment]
No, the problem isn't with that. Sorry for being vague. I meant the crash can be produced with both versions.

**Comment by thevortex** [comment]
oh my bad i see what it is, you aren't using Ice and Fire in your pack, I must have missed a check to see if the mod was loaded before registering something, my B, check for an update to allthemodium later today

**Comment by ArashkInGithub** [comment]
Ah I see. So the problem is with an unchecked dependency?

**Comment by thevortex** [comment]
yup 100%

**Comment by ArashkInGithub** [comment]
Thank you. So I assume the issue is solved. Should this issue remain opened until the checks are implemented to the mod or should I close it?

**Comment by ArashkInGithub** [comment]
And yes the problem was with ice and fire. Thank you so much for the quick response!

**Comment by thevortex** [comment]
I just posted an update to Allthemodium, I added a check before registering those items to make sure its safe, file is posted at https://www.curseforge.com/minecraft/mc-mods/allthemodium/files/3316955 1.4.6 should be approved soon, you can close the issue IF its all good on your end after the update

**Comment by thevortex** [comment]
it may take a few moments for Curse to approve it, but its pending right now, so shouldnt take long

**Comment by thevortex** [comment]
no worries, appreciate the report :)

**Comment by ArashkInGithub** [comment]
It'll take just a second to check.

**Comment by ArashkInGithub** [comment]
Unfortunately it still crashes without any warnings. Or if I'm doing something wrong, I'm all ears.
[crash-2021-05-20_23.13.37-client.txt](https://github.com/AllTheMods/ATM-6/files/6518134/crash-2021-05-20_23.13.37-client.txt)

**Comment by thevortex** [comment]
yeah i rushed it, testing a new build now should be posted soon, i apologize :)

**Comment by thevortex** [comment]
https://www.curseforge.com/minecraft/mc-mods/allthemodium/files/3317080

**Comment by ArashkInGithub** [comment]
Sorry for the late response, it was midnight for me so at the time, I was asleep. Everything works as intended! Thank you so much.
