### ISSUE TITLE
1.6.4 The Other biomes spawning in the nether

### ISSUE THREAD

**Issue by rockett1** [AllTheMods/ATM-6#1656]
ATM6 version 1.6.4

**Describe the bug**
"The Other" biomes are spawning in the nether

**To Reproduce**
1. Create new world in creative mode with seed: 7117123770413860482
2. go to coordinates x:531, Z:75 Y:-1631 in the overworld
3. Create a nether portal
4. End up inside a "The Other: Eroded badlands" biome
I've repeated this and got the same results every time.

Biome in the nether:
https://i.imgur.com/8LVd1iG.png
Overworld Coords to create portal at:
https://i.imgur.com/WFb3pKc.png

**Comment by thevortex** [comment]
it *seems* to be BYG, i rolled back to version 1.1.14 BYG and created a world with the same seed and went to the same pos, created a portal and ended up in a weeping mire, which is a correct nether biome, we will push a hotfix with a corrected version as soon as possible, try this and let me know, if you do more exploring and find the other biomes again with the older version of BYG you can reopen the issue
