### ISSUE TITLE
Azure silver essence 1.6.4

### ISSUE THREAD

**Issue by HRJDragon** [AllTheMods/ATM-6#1657]
ATM6 1.6.4
**Describe the bug**
While azure silver essence is obtainable from the craftable seeds, the essence has no recipie to be made to ingots or the sort

**To Reproduce**
See error

**Screenshots**
N/a
**Logs**
N/a

**Comment by thevortex** [comment]
i have a PR in for this now, we have a hotfix coming with some other config changes sometime tomorrow, thanks!
