### ISSUE TITLE
Teleporter to Mining world does not work on server (1.1.3b)

### ISSUE THREAD

**Issue by Niklars** [AllTheMods/ATM-6#166]
**Describe the bug**
Can't teleport to mining dimension with teleporter when playing on a server.

**To Reproduce**
1. Install and then start 1.1.3b server with "startserver.bat" from SIMPLE-SERVER-FILES-1.1.3b.
2. Install fresh 1.1.3b modpack on client.
3. connect to the new server when it's online.
4. make play server operator and then change game mode to creative and place a teleporter on the ground.
5. Use teleporter with right-click empty hand and shift.
6. Nothing happens no error in server log or anything. nothing happes at all.

**Expected behavior**
Teleport to mining dimension, works on client on a singleplayer map.

**Comment by brandonjohnson21** [comment]
issue identified in #168
