### ISSUE TITLE
Aquamarine Essence has no recipe to make aquamarine

### ISSUE THREAD

**Issue by I-J-C** [AllTheMods/ATM-6#1661]
Not sure if it's only a JEI problem or not, I tried a couple of different configurations and couldn't get the essence to craft aquamarine.

**Comment by thevortex** [comment]
looks like you the server you are playing on didnt install the pack correctly
![image](https://user-images.githubusercontent.com/1524819/119210024-ff6da500-ba5e-11eb-9504-523e5263345c.png)

**Comment by thevortex** [comment]
reinstall the server files is the solution here by the way :)

**Comment by radiomike** [comment]
Are you sure? It looks like recipe is removed by the KubeJS scripts in the master branch since February.

It does seem it's returned in the staging branch, but I assume that's not released yet?

**Comment by Pdiddy973** [comment]
https://github.com/AllTheMods/ATM-6/blob/master/kubejs/server_scripts/recipes.js line 687

**Comment by radiomike** [comment]
Ah, that's my bad there. It was missing in earlier packs when my players were looking at it before (up to 1.6.2 I think). But it did provide a good reason for getting started in bees at the time.

**Comment by Pdiddy973** [comment]
bees are the way to go =)
