### ISSUE TITLE
Crafting bug - Inscriber silicon press  used with the Inscriber  ATM6 v 1.6.3c

### ISSUE THREAD

**Issue by LucienLachance89** [AllTheMods/ATM-6#1669]
ATM6 - 1.6.3c 

**To Reproduce**
Steps to r[](https://imgur.com/a/VNLoe6W) eproduce the behavior:
When trying to create the Inscriber silicon press it has you to put 8 cetrus quartz essences around 1 silicon and you will get the Inscriber silicon press which you need to be able to craft printed silicon with the Inscriber .

**Screenshots**
1. The crafting recipe on the gui  [](https://imgur.com/a/sClBHUx) 
2. Me trying to craft the recipe [](https://imgur.com/a/m2fGKAX)

**Comment by LucienLachance89** [comment]
For some reason it didn't post the pics 
1. https://imgur.com/a/VNLoe6W

2.  https://imgur.com/a/m2fGKAX

**Comment by Pdiddy973** [comment]
You supposed to use silicon essence, but that was removed, not sure why that recipe wasn't...must of forgotten it
