### ISSUE TITLE
Audio Mutes and Clicks

### ISSUE THREAD

**Issue by ColinMoulds** [AllTheMods/ATM-6#167]
**Describe the bug**
Upon playing the game client/server, music does not play even on 100% on 3 different machines tested on.
Players Audio tab unless muted creates a form of clicking sound hard to describe.

Steps to reproduce the behaviour:
1. install mod pack
2. launch game
3. walk around
4. listen

**Expected behavior**
No annoying clicking noises and working Minecraft music.

**Comment by TBrauns** [comment]
When I use the in-game Muffler and Muffle item.elytra.flying:minecraft, the clackling goes away.
![Capture](https://user-images.githubusercontent.com/65601228/96059992-4d815100-0e5d-11eb-89d2-841562210cea.PNG)

**Comment by whatthedrunk** [comment]
Added the elytra to the blacklist until we can figure out what mod is causing it. New profile does not have the clicking and music plays fine now. This will be for todays release.

**Comment by pendo324** [comment]
`item.elytra.flying:minecraft` doesn't even show up in my muffler when I search all items, and I still hear the random clicking, on a new profile. I don't think this is fixed (1.1.5)

**Comment by whatthedrunk** [comment]
I'll reopen to take a look again. Feel free to delete the config for the mod and let it generate again. This should bring back the option to mute it. Next update I'll try and ship the profile with the muffled sounds rather then the blacklist to see if that does it.. Really wish I knew what mod was causing it.

**Comment by ColinMoulds** [comment]
As @pendo324 said, i also have the clicking noise. not sure the source as the only way for me to mute it, is to mute the players sound tab on Minecraft mixer.

**Comment by Tylerun** [comment]
This is Elementalcraft causing issues. Disabled the mod server and client side and the ticking will be gone. Just spent 3 hours disabling mods 1 by 1 to get rid of it

**Comment by suchipi** [comment]
Disabling Elementalcraft removed the clicks for me, too, but the server wasn't able to save the world anymore, so I had to re-enable it.

**Comment by pendo324** [comment]
Yeah, disabling doesn’t seem like a great option for people with worlds already generated. I was looking at the ElementalCraft source code, and there were some Elytra related changes recently. I couldn’t really see anything that would cause the sound bug though.

**Comment by Tylerun** [comment]
Thats very strange i had already generated my world and have had 0 issues removing the mod from both sides. But it is elemental crafts issue

**Comment by whatthedrunk** [comment]
The issue has been fixed with the mod dev. You can manually download it now or wait till we push an update later today.
