### ISSUE TITLE
Shifting sundial in the other crash the game

### ISSUE THREAD

**Issue by iTrooz** [AllTheMods/ATM-6#1670]
When using the shifting sundial in the other (tried it to skip the night), the game crashes.

Steps to reproduce :
- Go to the other
- Place a shifting sundial, and a hand of time pointing west
- Throw a clock

Error of my client when done in solo (anything before this is normal gameplay log) : https://pastebin.com/6EYvPbCa

Modpack : ATM6 to the sky version 1.0.9

**Comment by whatthedrunk** [comment]
Will be fixed when the mod updates and sky updates.
