### ISSUE TITLE
Crafting Create's creative motor using mechanical crafter gives 6 storm shots instead

### ISSUE THREAD

**Issue by shubham21197** [AllTheMods/ATM-6#1671]
ATM 6 Version 1.6.4
**Describe the bug**
When I craft a creative motor using an ATM star in mechanical crafters, 6 storm shots from reliquary pop out instead of a creative motor.

**To Reproduce**
1. Put the creative motor recipe in the middle of the 55 grid mechanical crafter (with top middle large cogwheel being where Patrick Star is in ATM star recipe)
2. Provide a redstone signal to force start the craft as not all slot are filled
3. 6 Storm shots come out

**Screenshots**
![2021-05-22_17 25 34](https://user-images.githubusercontent.com/13437286/119225690-e9291d00-bb22-11eb-862e-a1b24b5dc58b.png)
![2021-05-22_17 25 58](https://user-images.githubusercontent.com/13437286/119225695-ee866780-bb22-11eb-9957-6231fee40174.png)

**Comment by TheNeurotox** [comment]
I'm still on 1.6.3c, here some observation... It's not a fix but hopefully that will help someone to find a fix (and could be use as a partial workaround)

I think that if you place anything in your current "crafting grid", you will almost always get Storm Shot. Try for example with wood plank. It don't need to be a working recipes.

It seems to be related to the size of the "crafting grid" and the position of the items.
The smaller the grid, the better it work. 

With big grid, depending where you place your items, you could either get the right item or a storm shot.  If you keep the same grid size, the result seems to be the same at every try, if you change the size, the "working/good" position also change.

**Comment by DAmNRelentless** [comment]
Really odd behaviour but I managed to fix it.
The recipes share no ingredients, don't have any tags in common, no IDs are matching.

It seems to be an issue by Reliquary because after disabling the Shot completely, it works as intended.
