### ISSUE TITLE
Beepedia crash

### ISSUE THREAD

**Issue by OwenBowen222** [AllTheMods/ATM-6#1677]
**Describe the bug**
The beepedia causes a client crash upon viewing the traits of certain bees. I was informed on the Resourceful Bees repository that this is an issue with an invalid beepediaItem in the pack config.

**To Reproduce**
1. Open a beepedia
2. Open the page for a cobbee (only one of many bees that cause this)
3. Click "Traits" (blaze powder)
4. Crash

**Screenshots**
http://prntscr.com/13asfyk
**Additional context**
Running latest pack version (1.6.4)
Forge Version: 36.1.23
Mod Version: 0.6.7.2b
I am not running optifine or any other mod other than what is included.

**Logs**
https://pastebin.com/Ddesh3zA
https://pastebin.com/sMX7i2UZ (latest)

**Comment by thevortex** [comment]
fixed in 1.6.5
