### ISSUE TITLE
Crash on dragon fight 

### ISSUE THREAD

**Issue by pokermanx** [AllTheMods/ATM-6#1678]
Was in a middle of a fight when server went down

Crash: https://pastebin.com/gzMrNNM0

**Comment by DreamingLamb** [comment]
I've also had this a couple of times on a server (admin's not giving me the logs though).  

First time it was a Player Damage Trap causing damage to Ice & Fire dragon, second time I was fighting one that had escaped from a RFTools barrier room (was on the outside, in the open when the server crashed).

**Comment by starforcraft** [comment]
Should be fixed in newest Version.
