### ISSUE TITLE
Modded dimensions did not appear in level.dat

### ISSUE THREAD

**Issue by godleydemon** [AllTheMods/ATM-6#168]
getting a problem with tp to the mining dimension. No one can get to it. When checking nbtdata of level.dat with a newly generated single player world and a server world that was having issues. I noticed it was missing a lot of the dimensions it should have.

1. Generate new server on Linux with 1.1.3b
2. try to go to the mining dimension
3. doesn't work

When looking at the newly generated server level.dat file, I noticed that many of the modded dimensions that should be there weren't, (when comparing them to a newly generated single-player world.) So I took the nbtdata from the single-player level.dat file and transferred those to the server's level.dat file.
![image of nbtdata](https://i.gyazo.com/9fc2effe54e0d97cafc2cf7224744b2f.png)
(Note, transferred all dimensions on the left to the right)

Once that was done I had a player on the server try and go to the mining dimension but got an error.
https://gist.github.com/godleydemon/1e6449d1a760f7bec700fcaa7154bee3

**Comment by thevortex** [comment]
this is related to the biomesoplenty worldtype, the process we went through involved removing and adding back each mod that adds a custom dimension one at a time until we realized it was happening every time, with biomesoplenty as the worldtype. 

 changing your servers worldtype to default will create all modded dimensions
