### ISSUE TITLE
[Please update] Confirmed bug in TwilightForest v. 4.0.435

### ISSUE THREAD

**Issue by SimonNitzsche** [AllTheMods/ATM-6#1680]
**Describe the bug**
Twilightforest spamming console, logs and creating config files multiple times per second because the mod is unable to correctly load configuration files.

**To Reproduce**
1. Install server pack
2. Run server pack

**Screenshots**
![image](https://user-images.githubusercontent.com/6717311/119264690-7a13fd00-bbe4-11eb-8d47-effe8f3e3431.png)
![image](https://user-images.githubusercontent.com/6717311/119264717-8b5d0980-bbe4-11eb-9016-0912f5d0af7a.png)

**Additional context**
https://github.com/TeamTwilight/twilightforest/issues/1129

**How to fix**
Update TwilightForest to [4.0.467](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest/files/3317102)

**Logs**
within screenshots

**Comment by SimonNitzsche** [comment]
ATM6 v 1.6.4

**Comment by starforcraft** [comment]
ATM 6 updates nearly every mod when they update the pack so its fixed in the pack update.
