### ISSUE TITLE
Missing mods/libs

### ISSUE THREAD

**Issue by xTheEpicGamerx** [AllTheMods/ATM-6#1683]
**Describe the bug**
When loading up the modpack I see a list of libs that are missing 
**To Reproduce**
Go on the Curseforge app, load ATM6 (1.16.4) 
then you should see it

**Screenshots**
![Screen Shot 2021-05-23 at 2 39 41 PM](https://user-images.githubusercontent.com/84683430/119274279-b7708e80-bbd4-11eb-835f-0877a8a13d88.png)
![Screen Shot 2021-05-23 at 2 40 06 PM](https://user-images.githubusercontent.com/84683430/119274292-c6efd780-bbd4-11eb-953e-9b73a88b5e33.png)
![Screen Shot 2021-05-23 at 2 40 32 PM](https://user-images.githubusercontent.com/84683430/119274303-d7a04d80-bbd4-11eb-84bd-6da60b94856a.png)
![Screen Shot 2021-05-23 at 2 40 49 PM](https://user-images.githubusercontent.com/84683430/119274314-df5ff200-bbd4-11eb-96a3-d5493dd5640e.png)
![Screen Shot 2021-05-23 at 2 40 59 PM](https://user-images.githubusercontent.com/84683430/119274319-e6870000-bbd4-11eb-83d7-bf94c32d8102.png)
![Screen Shot 2021-05-23 at 2 41 21 PM](https://user-images.githubusercontent.com/84683430/119274333-f30b5880-bbd4-11eb-9fdb-ccb1810dbc09.png)

**Additional context**
I am new to GitHub so feel free to tell me if I need to improve on something

**Logs**
I don't know how to use that program, and I don't think This issue would need logs

**Comment by starforcraft** [comment]
Use GD or MultiMC Launcher. Curse is bugged asf.

**Comment by xTheEpicGamerx** [comment]
Ok thank you
