### ISSUE TITLE
Remote storage block missing (RFTools)

### ISSUE THREAD

**Issue by Ashaelia** [AllTheMods/ATM-6#1688]
The remote storage block from RFToolsStorage mod is missing. I cannot craft it and he is not even apearing in JEI.
I am using the last update and did not find anyone talking about it from ATM6 github or the one from RfTools either.

I wonder why this one is missing while the module are still here but useless. Game even crash when i insert one in a Modular Storage. I guess it's because i cannot link it first...

**Comment by starforcraft** [comment]
ATM 6 uses newest Version of RFTools and hasn't disabled any blocks/items of that mod.
