### ISSUE TITLE
Enderman spawning infinitely - 1.1.2

### ISSUE THREAD

**Issue by faaaaq** [AllTheMods/ATM-6#169]
I have a server running ATM6 1.1.2, and we were having massive server lag for seemingly no reason.  My server specs are far beyond what is required to run Minecraft (3700x, 64g of ECC DDR4, 1gigabit up/down, NVME SSD, etc).  Someone mentioned there were a ton of Enderman by them, so I ran a command to kill all Enderman to see what would happen.  Well..it killed almost 1200 Enderman.  A few minutes later, I ran the command again and already 100 new Enderman had spawned.  We are running the basic 1.1.2 ATM6, unmodified by us.  Is this a glitch?  Is there a way to fix this?  I am very lost ha

**Comment by Thunder-Nova** [comment]
There are a few biomes that spawns Enderman, from what I can tell, someone is living in an Enchanted forest, or someone made an enderman spawner and the enderman broke out... one thing to note they will teleport if harmed but still survive so **some** grinders won't work against them.

**Comment by faaaaq** [comment]
The server isnt a public one, so I know the actions of everyone thankfully.  They I think are near an Enchanted Forest.  Is it normal for enderman to spawn infinitely tho?  I thought there was an entity cap.  If this is normal occurrence I will see if I can enforce a cap manually
