### ISSUE TITLE
Lilypad of Fertility has two recipes, one default and one custom

### ISSUE THREAD

**Issue by GreatestFool** [AllTheMods/ATM-6#1691]
Pack version: All the Mods 6-1.6.4

I'm assuming the default recipe is not meant to still be functional, so thought I might as well make a little issue for this. Could be nice to fix for 1.6.5. Both recipes work just fine.

![image](https://user-images.githubusercontent.com/3003484/119348494-3c26df80-bc9d-11eb-97ef-015b75587595.png)

**Comment by whatthedrunk** [comment]
Fixed in 1.6.5 thanks!

**Comment by GreatestFool** [comment]
Sweet! Thanks for the hard work :)
