### ISSUE TITLE
At TLauncher it does not updated for a long time and you can't play it at all

### ISSUE THREAD

**Issue by Supartutu** [AllTheMods/ATM-6#1695]
**Describe the bug**

**To Reproduce**

**Screenshots**

**Additional context**

**Logs**
Please use a paste site for logs, instead of putting the file directly in the issue, not only is this easier but also means we can view on mobile when we are not at our computers.
Here's a list of some paste sites and their size limits:
    https://pastebin.com/ 512KB
    https://hastebin.com/ 400KB
    https://gist.github.com/ 100MB Requires member (Free)

**Comment by Supartutu** [comment]
When I try to play the mod from TL mods it gives an error and doesn' open . Also it doesn't updated for a long time.

**Comment by starforcraft** [comment]
Pirate Launchers aren't supported.

**Comment by thevortex** [comment]
buy minecraft ffs
