### ISSUE TITLE
What ice and fire mobs are spawning in the latest version and what world gen is wortking?

### ISSUE THREAD

**Issue by JustAGuyBruh** [AllTheMods/ATM-6#1696]
I am currently playing a server on 1.6.0.c and there are only 5 ice and fire mobs spawning and all of them are spawning within the other.:
-DRAGONS
-DREADHOUNDS
-GHOSTS
-PIXIES
-MYRMEX HIVES
I'm trying to create a stable/zoo and would like all of the the ice and fire mobs on there and I haven't found any of the other mobs.

The thing that bugs me is that I'm going to have to gen new lands to find the mobs when they are added if they spawn in specific gen and also its worth noting that chickens haven't been laying rotten eggs on this version.

So is there any retro gern option for stuff like that and do chickens lay rotten eggs on the latest version?

**Comment by thevortex** [comment]
1.6.3+ have hippogryphs, hippocampus sea serpents, sirens, and several more of the various dread entities they would not require new generation to spawn as its mob spawns and not structure spawns, they would be located in various dimensions such as twilight forest in certain biomes, ratlantis, and the other. chickens at present do not lay rotten eggs, you can enable that via config if you like

**Comment by JustAGuyBruh** [comment]
Thanks I updated my server today to 1.6.4 I managed to find more of the dread entities and also the mountains edge biome in the other spawns lots of hydras as well (way too many). gonna have a little look for the hippocampus, hippgryphs and sirens

**Comment by JustAGuyBruh** [comment]
what dimension are the hippgryphs in its the only one i havent found
