### ISSUE TITLE
Tome of Alkahestry

### ISSUE THREAD

**Issue by wolfowo** [AllTheMods/ATM-6#170]
**Describe the bug**
Right-clicking the Tome of Alkahestry or pressing shift with the cursor over it causes the game to crash. It also will not recharge with either redstone or glowstone. I have tried reinstalling the pack and the mod itself. I'm running pack version 1.1.3b and latest java version.

**Expected Behaviour**
Supposed to open an informational screen and recharge when activated and redstone or glowstone is in the inventory.

**Screenshots**

![Screenshot_4](https://user-images.githubusercontent.com/72902639/96073941-82010700-0e75-11eb-9bb6-dc25b6471fa2.png)

**Additional context**
[crash-2020-10-14_23.24.24-client.txt](https://github.com/AllTheMods/ATM-6/files/5382281/crash-2020-10-14_23.24.24-client.txt)

**Comment by WhitePhant0m** [comment]
It's disabled so it crashes when used. Shouldn't have a recipe tho... I'll remove the recipe myself then.

**Comment by wolfowo** [comment]
why tho T-T

**Comment by WhitePhant0m** [comment]
It will be enabled later when we are able to remove recipes from it properly

**Comment by whatthedrunk** [comment]
Todays update will fix it by not making the book craftable. If you already have the book just toss it or put it away until we are able to add our custom recipes to it. If you want to use the book as is edit the config manually.
