### ISSUE TITLE
AlltheTweaks armor fix is overtuned. 

### ISSUE THREAD

**Issue by Dandas52** [AllTheMods/ATM-6#1700]
Version: AlltheTweaks 1.6.3.1 and above
An unenchanted AlltheModium chestplate, without any other armor can completely negate all damage from dragons, and probably make the wearer immortal from all other damage sources. I tested this with Tier 3-4 Ice Dragons, as well as multiple dragons attacking at the same time, and was not taking any damage.

**Comment by thevortex** [comment]
alterations have been made with the newest update, armors are buffed across the board, we've also made some changes with apotheosis boss mobs(dimension limiting to the other and adding some dangerous mobs to its own buff list, so big mobs like cyclops , hydra and dragons will all be throwing a lot more damage at you in turn if they happen to be an apotheosis variant
