### ISSUE TITLE
Cryptic Redstone Ore cannot be broken with Pedestals mod

### ISSUE THREAD

**Issue by upd0g1** [AllTheMods/ATM-6#1704]
**Describe the bug**
A biome specific variant of redstone ore--cryptic redstone ore--is not being broken by pedestals with block breaker upgrades on them. 

**To Reproduce**
Place a block of cryptic redstone ore within range of a block breaking pedestal from the Pedestals mod. 

**Screenshots**

**Additional context**
Late game resource generation through a void miner will only yield cryptic redstone ore. 

**Logs**
Please use a paste site for logs, instead of putting the file directly in the issue, not only is this easier but also means we can view on mobile when we are not at our computers.
Here's a list of some paste sites and their size limits:
    https://pastebin.com/ 512KB
    https://hastebin.com/ 400KB
    https://gist.github.com/ 100MB Requires member (Free)

**Comment by ladylexxie** [comment]
Seems like it's because the block is emitting a redstone signal.
