### ISSUE TITLE
Every 30 seconds, "string too big" error. Clean/fresh server. No one logged on.

### ISSUE THREAD

**Issue by cha0s** [AllTheMods/ATM-6#1707]
**Pack version**
1.6.4

**Describe the bug**
Every 30 seconds, I get: `[Netty Epoll Server IO #60/ERROR] [minecraft/NettyPacketEncoder]: Error encoding packet io.netty.handler.codec.EncoderException: String too big (was 33428 bytes encoded, max 32767)`

**To Reproduce**
1. Install server.
2. Run it.

**Screenshots**
N/A

**Additional context**
N/A

**Logs**
https://pastebin.com/349B4w9W

**Comment by cha0s** [comment]
I should note that I have the same result as 

https://github.com/AllTheMods/ATM-6/issues/1086

and

https://github.com/AllTheMods/ATM-6/issues/1376

The porposed solution to delete `world/icon.png` is not applicable. That file doesn't even exist, and if `server-icon.png` was the file being referred to, it is only 6251 bytes. Plus, it's "a known issue with worlds that were started in single player. The client creates icons that are larger than the server can use," but I never launched this as a client. This is a pure server install.

**Comment by cha0s** [comment]
Further notes:

I investigated the possibility that there was some other unknown file that was exactly 33428 bytes being sent, so I did:

```
$ find -size 33428c
```

No results.

**Comment by jeremiahwinsley** [comment]
This is a known issue on the current version, though we don't know yet what causes it (this is a different issue than the `world/icon.png` one). Have you made any changes to `server.properties` or any config files?

**Comment by jeremiahwinsley** [comment]
Also, can you post a full `debug.log`?

**Comment by cha0s** [comment]
Sure thing.

`server.properties`: https://pastebin.com/kEJZhiBy
`debug.log`: http://www.cha0s.io/debug.log.txt (wayyyy too big for pastebin)

**Comment by Idrakonyx** [comment]
Hi, i am receiving the same error message, but after i tried to change the default world for the server with a copy of my own single player world. this happens:

![image](https://user-images.githubusercontent.com/85325682/120737428-0c0ce700-c4bc-11eb-99dc-1febbee8c0ad.png)

Any ideas?

**Comment by ConnorJBrown** [comment]
I get the same error every time someone refreshes the server list on their client. The server appears offline but we can still connect to it. Deleting the icon did not fix this.

`[15:02:41] [Netty Epoll Server IO #2/ERROR] [minecraft/NettyPacketEncoder]: Error encoding packet
io.netty.handler.codec.EncoderException: String too big (was 35312 bytes encoded, max 32767)`

**Comment by ConnorJBrown** [comment]
> I get the same error every time someone refreshes the server list on their client. The server appears offline but we can still connect to it. Deleting the icon did not fix this.
> 
> `[15:02:41] [Netty Epoll Server IO #2/ERROR] [minecraft/NettyPacketEncoder]: Error encoding packet io.netty.handler.codec.EncoderException: String too big (was 35312 bytes encoded, max 32767)`

An update on this, the server host I was using automatically generates a server-icon.png if there isn't any. I created a 1kb server icon and I no longer get this issue.
