### ISSUE TITLE
There is no way to breed glowing bees [1.6.2]

### ISSUE THREAD

**Issue by Epicmoofish** [AllTheMods/ATM-6#1709]
**Describe the bug**
Glowing bees cannot be bred

**To Reproduce**
1. Try to breed a glowing bee with any item
2. Observe as it doesn't work

**Additional context**
The tag for the flowers that allow you to breed the glowing bee doesn't contain any items

**Comment by whatthedrunk** [comment]
in 1.6.5 its working just fine.

**Comment by mjordan67** [comment]
I am in ATM6 1.8.20 and having same problem  glowing bee can't breed and no item shows in the box under the bee.  multiple dyes show under the RGBee but nothing under glowing bee.  I tried many items with no results. (trying to get a redstone bee)
