### ISSUE TITLE
Resourceful Bees

### ISSUE THREAD

**Issue by Felskef** [AllTheMods/ATM-6#1716]
**Describe the bug**

It;s been over a day in real time of me trying to get my wither bee to mutate my dragon egg but it just isn't happening. I Moved it once after 6 hours and still nothing. I might just be impatient but just wanted to let yall know! Everything else is awesome though!

**To Reproduce**

**Screenshots**

**Additional context**

**Logs**
Please use a paste site for logs, instead of putting the file directly in the issue, not only is this easier but also means we can view on mobile when we are not at our computers.
Here's a list of some paste sites and their size limits:
    https://pastebin.com/ 512KB
    https://hastebin.com/ 400KB
    https://gist.github.com/ 100MB Requires member (Free)

**Comment by DAmNRelentless** [comment]
I've seen multiple people do it so I guess this is just outdated.
If you have problems getting this to work, feel free to join the Discord and ask other players there. This is not a bug.
