### ISSUE TITLE
1.6.4 crash 

### ISSUE THREAD

**Issue by FrostZFish** [AllTheMods/ATM-6#1718]
**Describe the bug**
My minecraft will crash accidentally. I have gave enough RAM for the MC to run.

**To Reproduce**
1. Go to 'open minecraft the play about 5-10 mins'
2. Click on 'accidentally crash'
3. See error

**Additional context**
Add any other context about the [problem](https://gist.github.com/FrostZFish/f420a36003416dbbce6b5c9c6164b4ff) here.

**Comment by starforcraft** [comment]
Show your Crash Report.

**Comment by starforcraft** [comment]
wait. 1.16.4?

**Comment by FrostZFish** [comment]
crash report is in the additional context "problem"

**Comment by FrostZFish** [comment]
sry is 1.6.4

**Comment by starforcraft** [comment]
Update to newest Version.

**Comment by FrostZFish** [comment]
but i have update to the newest. The problem still happen

**Comment by starforcraft** [comment]
1.6.4 isn’t the newest Version, 1.6.6 is.

**Comment by FrostZFish** [comment]
what i mean is in the previous version, this issue has happen a lot. And i update "the newest version" everytime, the issue still happen.

**Comment by thevortex** [comment]
provide a log

**Comment by FrostZFish** [comment]
this a another crash report. https://gist.github.com/FrostZFish/132680154edf4860afed334b405a7362
