### ISSUE TITLE
Extra Disks dupe with Refined Storage | All the Mods 6-1.6.4 |

### ISSUE THREAD

**Issue by yutoe** [AllTheMods/ATM-6#1719]
**Describe the bug**
Extra disks / Extra storage duplication bug with refined storage pattern grid

**To Reproduce**
1. Go to 'Pattern Grid'
2. 'Set the pattern to either "256 Storage part" or "1024K Storage Part" from extra disks mod'
3. 'Have the pattern in the pattern grid'
4. 'Shift click the output part of the pattern and it will go to your inventory'

**Screenshots**
https://imgur.com/a/njt46x0

**Additional context**
Im pretty sure its from whatever the mod is that lets you swap crafting recipes whenever a crafting recipe has the same recipe the little button above the output slot of the crafting table
 
**edit**
Added a picture of the recipe changer to the imgur link

**Comment by yutoe** [comment]
So whatever the mod is called that lets you change select your output when things have the same recipe does dupe items. lets say the "Stone wand" from construction wand has the same recipe as the "build tool" from structurize and if you put that recipe in the pattern grid from JEI it will let you shift click the item out for free

**Comment by xTariel89** [comment]
Verified this as well, does seem to be related to the mod to swap recipe outputs.

**Comment by DAmNRelentless** [comment]
Oh boy, that's a big one. I'll be looking into that..

**Comment by DAmNRelentless** [comment]
Mod issue by Polymorph so either that's fixed on their end or we have to invest some serious time to remove all conflicting recipe.
Let's see what the dev answers here: https://github.com/TheIllusiveC4/Polymorph/issues/78

**Comment by DAmNRelentless** [comment]
The mod author disabled the Grid integration for Polymorph as hotfix. This is not optimal but a working solution for the current problem.
The update will be in the next pack update and will fix this issue, thanks for reporting. I'll close it now.
