### ISSUE TITLE
mouseClicked event handler (Bug/Crash) (World Loading Failure)

### ISSUE THREAD

**Issue by Coraline77447** [AllTheMods/ATM-6#172]
Hello! I'm experiencing a problom when I'm trying to join my pre-existing modded 1.16.3 survival world called Coraline World 1.16.3 (Modded). By the looks if it when I click on "Play Selected World" it starts loading the world but then I instantly see my world selection screen for a split second and then it goes back to the same screen as before but then says "saving world" and then I'm back at my Tlauncher screen. Before the new update with this mod I was able to load into my world with the exception of the advice I usually get when I create a new modded world or loading into a pre-existing modded world (since custom worldgen/demensions are apparently still in experimental stages and this mod adds new custom demensions). After the update now I'm unable to join my world or possibly creating a new one. Anyways here's the crash report and the crash log: 

[crash-2020-10-15_01.29.58-client.txt](https://github.com/AllTheMods/ATM-6/files/5383464/crash-2020-10-15_01.29.58-client.txt)

[2020-10-15-10.log](https://github.com/AllTheMods/ATM-6/files/5383363/2020-10-15-10.log)

If it's not just allthemeduom that's causing this issue or if allthemeduom is not causing this issue then please help me by telling me what is causing this issue and if I do need to create a new world or anything! Thanks in advance!

P.s. I may try to load back into my world with the last version of allthemeduom and see if I can still load into the world but if not then I'll have to restart my world by recreating it or I can simply create a new world without allthemeduom installed since I'm playing with some mods that adds in modded armors, tools, and weapons (CArmoury and SimpleOres) so the only things I'll be missing is everything that's in allthemeduom but I'll be fine without the mod till the next update for allthemeduom. btw sorry for this comment being so long to read!...)

**Comment by Coraline77447** [comment]
damn... My attempt to make spoilers for the crash and the log didn't work as intended or has failed so sorry in advance for this post being extremely long!!!....

**Comment by WhitePhant0m** [comment]
Try removing Modern UI

**Comment by WhitePhant0m** [comment]
When having issues with the pack, you should remove all mods you've added yourself and see if you can still replicate those issues.

**Comment by Coraline77447** [comment]
I have just found out that it working on a new nameless world. This means that the world Coraline World 1.16.3 (Modded) (original world name: Cora World (Mod) got corrupted or is no longer loadable/playable...
