### ISSUE TITLE
Upgrading Astral Sorcery altar crashes server - ATM6 1.6.5

### ISSUE THREAD

**Issue by dylanpdx** [AllTheMods/ATM-6#1720]
**Describe the bug**
Upgrading Astral Sorcery alter results in server crash. This is in ATM6 1.6.5

**To Reproduce**
1. Attempt to upgrade Altar
2. See crashlog

**Logs**
https://pastebin.com/Z1guRBCw

**Comment by JorellAponte** [comment]
This happened on my server too

**Comment by Koltay** [comment]
the same thing happened on my server too, still finding for a solution

**Comment by DAmNRelentless** [comment]
The mod as well as the pack have been updated a lot since this issue was reported.
Please update the pack and open a new issue if it still happens.
