### ISSUE TITLE
Magnet enchantment removed from items after update from 1.6.3 to 1.6.6

### ISSUE THREAD

**Issue by xxJ6xx** [AllTheMods/ATM-6#1721]
Updated this morning, all Magnet enchants are gone from tools, armor parts, and books in storage.  Unsure if gone from game altogether or just previously created items.
EDIT: It's no longer listed in the game, see screenshots...
![missing_magnet_ench](https://user-images.githubusercontent.com/75847175/120078039-79171b80-c07b-11eb-9f55-32c84c633120.png)

**Comment by xxJ6xx** [comment]
Tried replacing new version of cyclic with previous version and loading an old save that had the enchants, no change.

**Comment by DAmNRelentless** [comment]
The enchantment has been removed from the modpack due to balancing.
