### ISSUE TITLE
Client crash when clicking "Traits" of "Salt Baee" - ATM 1.6.3c

### ISSUE THREAD

**Issue by SaltyBoi1000** [AllTheMods/ATM-6#1722]
Using the Beepedia from Resourceful Bees, clicking on the "Salt Baee" and then "Traits" crashes the client. This has happened twice so far and I don't really fancy trying it again...

**Logs**
https://pastebin.com/fFggWPVu

**Comment by thevortex** [comment]
update to 1.6.6 issue has been resolved
