### ISSUE TITLE
Disappearing Disks

### ISSUE THREAD

**Issue by jduece** [AllTheMods/ATM-6#1723]
Describe the bug:
Refined storage deletes all the disk in the drive every time i log out single player world

To Reproduce:
Start game add disks can be empty or full and log out log back in and poof.

If you still need screenshots i can get some but i figured this was good enough considering. Also everything is updated i have to run optifine or i cannot even play it. also it says there is an opengl error 1281 invalid value

**Comment by ladylexxie** [comment]
If that really is the case, although I've never heard of something like this before, it should be reported to RS.
The opengl error is caused by optifine, as it is not made for modpacks. It breaks a lot of things and causes many issues.
