### ISSUE TITLE
UI for Cyclic Block Placer malformed since update to pack 1.6.7

### ISSUE THREAD

**Issue by localzuk** [AllTheMods/ATM-6#1726]
When opening the Cyclic Block Placer UI, you don't get the UI you should. You get the below instead.

https://imgur.com/0hnAGHX

Running pack 1.6.7 server.

**Comment by DAmNRelentless** [comment]
Not reproducible in the newest version of the pack.
![](https://i.imgur.com/RcqqkjY.png)
Please upgrade the pack and feel free to open another issue if it still happens.
