### ISSUE TITLE
1.6.7 crash

### ISSUE THREAD

**Issue by FrostZFish** [AllTheMods/ATM-6#1727]
My minecraft accidentally crashed.
Here is the crash log:https://gist.github.com/FrostZFish/830df4d6264fde8dc2cb492a4ebc9502
Help please!

**Comment by thevortex** [comment]
this type of a crashdump is usually related to a damaged system file, this is happening before the game even launches based on the exception code 0xc000001d try repairing the installation of your launcher itself or failing that, windows.

**Comment by FrostZFish** [comment]
So how can i fix it?

**Comment by thevortex** [comment]
curseforge is down right now perhaps that is the issue?

**Comment by FrostZFish** [comment]
i have another crash log. https://gist.github.com/FrostZFish/297f3c18c5ba16b8f0231baa5d7a1977

**Comment by FrostZFish** [comment]
actually this may not related to the curseforge since my mc still crashing in several version

**Comment by DAmNRelentless** [comment]
Sorry but your crash is not related to our pack.
Looks like you either have a damaged Java installation or some problem with your OS. We can't help you here.
