### ISSUE TITLE
How i can change the mode from my Fluxbore?

### ISSUE THREAD

**Issue by derabzockerHD** [AllTheMods/ATM-6#1728]
When I press v then it open my inventory and nothing changes the mode from my Fluxbore.

**Comment by Parapa0** [comment]
Check keybinds, also this should be asked in their discord.

**Comment by derabzockerHD** [comment]
Which keybind is it?

**Comment by Parapa0** [comment]
it's probably a conflict, either unbind everything that uses 'v' or change the keybind for changing the fluxbore's mode to another key.

**Comment by derabzockerHD** [comment]
Where i find the keybind?

**Comment by Parapa0** [comment]
in your controls

**Comment by derabzockerHD** [comment]
Yes but where?

**Comment by Parapa0** [comment]
you can search by key, look what 'v' being used by

**Comment by derabzockerHD** [comment]
Yes there are many keybindings but nothing from Thermal

**Comment by Parapa0** [comment]
can you send a scrennshot?

**Comment by derabzockerHD** [comment]
Ok in 3 hours

**Comment by starforcraft** [comment]
> Ok in 3 hours

In 3 hours? So you are not even ingame?

**Comment by derabzockerHD** [comment]
Yes but Yesterday was in the Controls norhing from Thermal
