### ISSUE TITLE
Eternal Stella Indestructible modifier keeps going away

### ISSUE THREAD

**Issue by cwcontur** [AllTheMods/ATM-6#1729]
Pack Version: 1.6.4

Eternal Stella modifier "Indestructible" disappears from Tinker's Construct tools (A Unobtainium pickaxe in this case) after a single durability point is taken from a tool with the Luck modifier also added.

[This was also tested with other types of pickaxes and the result was the same each time]

1. Combine Eternal Stella with Tinker's Construct pickaxe in smithing table.
2. Add lapis to tool to get Luck.
3. Mine a few blocks; indestructible will disappear.

**Comment by ladylexxie** [comment]
That's something to do with Tinkers' not with ATM
