### ISSUE TITLE
Random crashes on chunk generation

### ISSUE THREAD

**Issue by godleydemon** [AllTheMods/ATM-6#173]
Seems to be that the server is crashing randomly on chunk generation. I'm using a mod called "World Pre Generator" to try and pregen the world to reduce hitching and lag for the players. If I do this in 5 chunk increments I can get away with it and I'll be able to get through it without a crash. Once everything gets done saving, I can do another 5 chunks. If I try and do 10, the server WILL crash no matter where I tell it to generate. 

Crash report: https://hastebin.com/turofiyunu.rust

The server has 20gb of ram dedicated to it, Intel Xeon E3-1230v6 - 4 c / 8 t - 3.5 GHz / 3.9 GHz, so this should be running fine. But I'm getting crashes with 0 players on, JUST doing generation.

When players are on just exploring, the server will inexplicably crash on chunk generation. If they stay within their own areas and don't explore, the server can handle it just fine and continues to purr away like nothing is happening. Not a care in the world. But as soon as chunk generation starts, it's like someone beat it over the head with a hammer and told it to do calculus. 

Here's my start.sh file as well in case you anyone needs it for anything
https://hastebin.com/quzaxadota.properties

**Comment by whatthedrunk** [comment]
detected that a single server tick took 60.01 seconds
To temporarily fix this edit your server properties and change max tick time to -1. Also make sure to update to todays update that will be out soon as it fixes some biome stuff.
