### ISSUE TITLE
1.6.3c - anvil repair XP cost wrong and eating materials

### ISSUE THREAD

**Issue by MatthewDVance** [AllTheMods/ATM-6#1730]
ATM6 1.6.3c

**Describe the bug**
1. repairs in anvil cost too much XP (64+ levels) even for just a diamond.
2. repairs eat materials instead of repairing tool

**To Reproduce**
1. put damaged pickaxe in anvil
2. insert stack of diamonds
3. take pickaxe out of anvil - entire stack of diamonds lost - pickaxe not hardly repaired
4. put pickaxe back in anvil, notice you can't repair it because it wants way too many levels

**Screenshots**
1st ever repair:
https://pasteboard.co/K4npsHy.png

2nd repair:
https://pasteboard.co/K4nqhvP.png

**Comment by DAmNRelentless** [comment]
This is not reproducible in the newest version of the pack.
Please upgrade the pack and feel free to open a new issue if it still persists.
