### ISSUE TITLE
Bee Nest Upgrades don't change the item tag.

### ISSUE THREAD

**Issue by PvPsFinest** [AllTheMods/ATM-6#1731]
Pack Version 1.6.4
**Describe the bug**
Bee Nest Upgrades don't change the item tag. 
The stats of the hive are changed, but the name and consequentially the crafting usages of the item are restricted to the previous tier.
EX. Tier 2 Hive upgraded with a Tier 3 Nest Upgrade results in a Tier 2 Hive with Tier 3 Stats.

**To Reproduce**
1. Make a Tier 2 Hive
2. Get A tier 3 nest upgrade
3. Right click the hive with the upgrade
4. Mine the hive and notice it is still tier 2.

Starting Tier 2 Hive:
![Screenshot (39)](https://user-images.githubusercontent.com/57274898/120145647-b6250000-c198-11eb-8343-245d4e00847a.png)

Intended Tier 4 Hive:
![Screenshot (34)](https://user-images.githubusercontent.com/57274898/120145776-ed93ac80-c198-11eb-8332-28b4db6d907f.png)

Bugged Tier 2/4 Hive Result:
![Screenshot (40)](https://user-images.githubusercontent.com/57274898/120145809-fab09b80-c198-11eb-8f2f-419cd2fa44d0.png)

**Comment by Parapa0** [comment]
https://github.com/Resourceful-Bees/ResourcefulBees/issues/238

**Comment by PvPsFinest** [comment]
Ahh, though it was a pack issue, thanks/
