### ISSUE TITLE
Hello，I have a question about Hydra（ice and fire）

### ISSUE THREAD

**Issue by MRailgun** [AllTheMods/ATM-6#1732]
hello。Ice and fire's Hydra will be generated in the The Nether. It has 5000hp, more than one. It makes it impossible for me to get quartz——From Baidu translation

**Comment by thevortex** [comment]
update to newest version of the pack and reset your nether :) sorry about this!

**Comment by MRailgun** [comment]
Thank you, but I'm the latest version now.（1.6.7）  The Nether will still make hydrants。——From Baidu translation
