### ISSUE TITLE
1.6.4 -> 1.6.5 Scorching heat won't apply to my new unobtanium pickaxe or my old pickaxe after a version update

### ISSUE THREAD

**Issue by queeb3** [AllTheMods/ATM-6#1733]
1.6.4[old]-1.6.5[current]
Summary of Bug - 
I had an old pickaxe [Image 1] that had a bunch of cool enchants like exp boost, fortune, efficiency, and indestructible...
All those were together with the said enchant scorching heat, and they all worked as they were supposed to, I would mine a block or ore and it would smelt and give me the fortune effect to mine straight into iron ingots from iron ore whilst also giving me more than 1 at a chance with fortune.. now I have updated the pack to 1.6.5 from 1.6.4 when I originally made the pickaxe and since I found better materials for a new pickaxe from silent gear (vibranium to unobtanium) I made a new pickaxe and tried to apply all my old enchants after using a disenchantment table from cyclic to then apply it to [Image 2] this pickaxe as you can see all the old enchants were applied just fine however I still can't apply scorching heat, after trying to get this to work for about 1 hour. I just tried to put it back on my old pick and to my surprise, it just wouldn't even apply even though there was 0 enchants on it at all

**To Reproduce**
1. use 1.6.4 to add scorching heat fortune indestructible efficiency experience boost to a vibranium pick from silent gear
2. update to 1.6.5
3. disenchant pickaxe
4. try to add scorching heat back to vibranium(after disenchanting)/ new unobtanium pickaxe(with the old picks enchants)

**Screenshots**
Image 1: https://gyazo.com/da7fa822d8c7ea5249c46fa14a36a746
Image 2: https://gyazo.com/ebd83a1498be5883773a07418b073cb9
Extras - 
https://gyazo.com/be0fbd61795d8b1b56f59a63698ee075     (New pick with scorching heat) not enchanting
https://gyazo.com/6d95db497581a1d419248388ec4ac682    (Old Pick with scorching heat) not enchanting
**Additional context**
I'm on a server for me and 1 other friend]

need anything else please ask I dont know what logs I can access since I have 0 access to the server my friend is the host

**Comment by DAmNRelentless** [comment]
The Scorching Heat has been disabled due to balancing, sorry.
