### ISSUE TITLE
Trinkers Construct Luck is gone 

### ISSUE THREAD

**Issue by Cratios** [AllTheMods/ATM-6#1740]
All the Mods 6

Minecraft 1.16.5

Version 1.6.7

Mod: Tinkers Construct

The Modifyer Luck with Lapis on Tinkers Tools are not here anymore

**Comment by seelani** [comment]
Please note there are changes to the luck modifier in the recent releases.
https://imgur.com/a/spUnQoD

**Comment by Cratios** [comment]
Thx
