### ISSUE TITLE
Why Ice and fire Dragons and structures, dont spawn?

### ISSUE THREAD

**Issue by CheezzyK** [AllTheMods/ATM-6#1741]
Why Ice and fire, Dragons and structures dont spawn?

**Comment by starforcraft** [comment]
Look in the right Biomes.

**Comment by spdkils** [comment]
They are spawning in the other (check config files).
You get there by using the teleport from ATM, in the nether (So I've heard.)

**Comment by Barrhaputh** [comment]
Excuse me, my server has the exact same issue, no mob from Ice and Fire are spawning at all, and I was wondering if you could explain what you said a bit further? My knowledge in computers and programmation is pretty poor and so I didn't understand what solution you proposed just before... I don't really know what to do to make it work. Sorry for the inconvenience and thank you if you answer!

**Comment by Parapa0** [comment]
The other is a dimension, you can go to it using a teleportation pad placed in the nether @Barrhaputh

**Comment by Barrhaputh** [comment]
Waow that was fast, I will try it out then, thank you! I'll come back if it doesn't work aha

**Comment by Parapa0** [comment]
also just make sure you are geared really well, The dragons are buffed 15k-60Khp.
These are biomes were dragon spawns:
Fire:      The Other: Basalt Deltas
Ice:       The Other: Mountains
Lightning: The Other: Desert, The Other: Desert Hills

**Comment by Barrhaputh** [comment]
I had no idea The Other existed at all!
Thank you we will, you've been super helpful and fast thanks so much!
