### ISSUE TITLE
Issue with Solar Neutron Activator in the end

### ISSUE THREAD

**Issue by Ferajka** [AllTheMods/ATM-6#1742]
I'm having a problem with the Solar Neutron Activator from Mekanism installed in the end dimension. It needs sunlight/daytime. By default it should be working fine in the end too, since its always daytime/sunny there, but it doesn't seem to work in the modpack. Some other mod may be affecting the end, but I don't for sure. I'm curious if it's intentional or a bug, and if intention, how can I disable it.

**Comment by RobuxShooters** [comment]
The End is no longer always daytime compared to how it was in 1.12 due to some code changes in vanilla and how Mekanism handles daytime verification.
