### ISSUE TITLE
Crash instantly on launch

### ISSUE THREAD

**Issue by Foxtrotty** [AllTheMods/ATM-6#175]
I have installed this modpack a few times now but every time i do it it chrashes.

**To Reproduce**
1, i click play on twitch
2. then i launch it on the MC Launcher
3. loads for about 2 seconds then takes me back to the Launcher
4. Exit Code: 0
 trying to start a server with this modpack

**Comment by JaisDK** [comment]
You are either forgetful and have forgotten to attach your logs or you think that the creators of ATM6 will release a version without trying to launch it and by following your steps of basically just launching the game they can discover what is wrong with your installation.

**Comment by Trinsdar** [comment]
Jeez dude, he probably just forgot.

**Comment by whatthedrunk** [comment]
This is most likely a Twitch launcher issue. Try MultiMC or GD launcher.
