### ISSUE TITLE
Cannot repair Copper Tinkers Tool with Copper ingots 1.16.7

### ISSUE THREAD

**Issue by Duke-Nukem-3D** [AllTheMods/ATM-6#1750]
I have made a pickaxe with Copper head, bone binding, iron tool rod (tried bone and iron ingot as well). I have tried to repair on Anvil and Station with Copper ingots from tinkers and alltheores but will not repair. I made an all copper hammer and that will also not repair. 

Making a tool which uses a different repair ingot works fine. Tested with Iron pickaxe head and Silver for hammer.

Darkosto is using same Tinkers version 1.16.5-3.0.4.17 in his Skyfactory1 remake modpack and Copper tools repair with Copper ingots ok.

So looks like ATM6 modpack issue ?!?!

**Comment by ladylexxie** [comment]
We can only assume it's something wrong with TCon as we've had multiple people test it out for us and it seemed that it doesn't even work with TCon's own copper ingot, while nuggets and blocks work correctly.
