### ISSUE TITLE
Server crashed and won`t start

### ISSUE THREAD

**Issue by pokermanx** [AllTheMods/ATM-6#1752]
v1.6.3
log: ~~https://pastebin.com/KyhEYmr5~~
full crash report: https://pastebin.com/RrhuPXEf

**Comment by NitroSvennen** [comment]
Same here v1.6.7
log: https://pastebin.com/y9GWxqDv

**Comment by thevortex** [comment]
Sven please log a separate issue for your crash

**Comment by pokermanx** [comment]
Reason - astral sorcery (duh), and it happened again, if you ever need it: 
log https://pastebin.com/b3jyaU9T

**Comment by DAmNRelentless** [comment]
The mod as well as the pack have been updated a lot since this issue was reported.
Please update the pack and open a new issue if it still happens.
