### ISSUE TITLE
Infinite items (just sticks and feathers ) from Fletching table with wilden spike

### ISSUE THREAD

**Issue by TheBadWolf124** [AllTheMods/ATM-6#1754]
![image](https://user-images.githubusercontent.com/46606838/120807449-3efcbc80-c548-11eb-8b0c-9e19fa854c38.png)

Items just start increasing instead of deacreasing after takeing the item out

If this bug is known I am sorry. I haven't checked the other bugs/issues.

I am not sure if I should post it here xD if not I will remove it

**Comment by ladylexxie** [comment]
We will take a look at this and see if it's something we can fix.
