### ISSUE TITLE
Resourceful bees: Unable to breed Blazing bee with Magma and Spooky.

### ISSUE THREAD

**Issue by Sam-Thunder** [AllTheMods/ATM-6#1755]
**Describe the bug**

When attempting to breed a Blazing bee. I realised the JEI only has Blazing + Blazing breeding. Although the description says that the parents are spooky and magma. When attempting the breed anyway even though there is no craft in the JEI, it fails. Therefore as Blazing bees are unable to be found in the wild, and unable to be bred, they are unobtainable.  I double checked this in the Beepedia and it also shows there is no breeding the blazing bee.

**To Reproduce**

**Screenshots**

https://prnt.sc/1418tvd          Blaze + Blaze reproduction

https://prnt.sc/141917e          Description

https://prnt.sc/14197or         Beepedia

**Additional context**

**Logs**
Please use a paste site for logs, instead of putting the file directly in the issue, not only is this easier but also means we can view on mobile when we are not at our computers.
Here's a list of some paste sites and their size limits:
    https://pastebin.com/ 512KB
    https://hastebin.com/ 400KB
    https://gist.github.com/ 100MB Requires member (Free)

**Comment by ladylexxie** [comment]
Same issue as #1758
