### ISSUE TITLE
Mekanism digital miner and fake player issue

### ISSUE THREAD

**Issue by cmann21** [AllTheMods/ATM-6#1759]
Version is 1.6.7 of Allthemods

We've noticed that after building digital mine, Player on server was then labeled as a fake player. He is not listed in the allied tab as a real player but instead as a fake player. Other players cannot add him as ally.

Not exactly sure on how to reproduce. Maybe building the miner and see how player changes in allied tab for FTB Chunks

I do not have any logs or screenshot. Player name in the allied tab has changed from white to yellow and listed as fake player.

**Comment by starforcraft** [comment]
The fake player is the Mekanism Digital Miner not your friend or you.
