### ISSUE TITLE
[1.6.7] IntegratedTunnels network corrupted after server restart

### ISSUE THREAD

**Issue by x13x54** [AllTheMods/ATM-6#1761]
**Describe the bug**
When using IntegratedTunnels to transport stuff (tested fluids and items so far) the network becomes inoperable after a server restart.
Reseating variable card does nothing to fix it, however breaking the fluid/item im/exporter and placing it again with the same variable card does, although expected behavior does not involve this operation.

**To Reproduce**
1. Make the simplest fluid/item im/exporter network using IntegratedTunnels
1.5. Piping something through might be required to reproduce
2. Restart server
3. Network is corrupted

**Screenshots**
![image](https://user-images.githubusercontent.com/84224121/120926884-08a57580-c6df-11eb-993a-1774835be54f.png)

**Additional context**
Both networks (pipes) from integrated* in the screenshot fail after server restart. On each chest is an item interface and on the ore purifier is both an item importer and an item exporter. This issue however is not related to the ore purifier as a fluid exporter network on an xp drain and xp solidifier from MobGrindingUtils has this same issue. IntegratedDynamics networks seem to do fine but IntegratedTunnels ones are experiencing the issue described. All of this is happening in chunkloaded chunks and neither the network or the machines cross chunk borders.
Might be related to https://github.com/CyclopsMC/IntegratedTunnels/issues/124
I haven't been able to find anything interesting in the logs when i logged in and noticed the same issue again. Also quick search of the logs show no issues with integrated* during startup.

**Logs**
~~Will be added shortly after sanitizing them of IP's and similar irrelevant information.~~
https://pastebin.com/w0Gy5Axk

**Comment by ladylexxie** [comment]
This is a mod related issue, we can't do anything about it unfortunately.

**Comment by x13x54** [comment]
How did you figure out this was an issue with the mod? It can be relevant to the issue i created with the mod.
I went through the logs myself and found nothing indicating an internal failure within the IntegratedTunnels mod
