### ISSUE TITLE
Server Install 1.6.8 - Can't download forge jar

### ISSUE THREAD

**Issue by Malexion** [AllTheMods/ATM-6#1765]
**Describe the bug**
Server Installer errors on fetching forge jar file and cycles endlessly unable to recover

**To Reproduce**
1. Run server installer
2. Wait to forge jar download
3. See error
4. See endless attempts for the server to fix itself by restarting

**Screenshot**
![image](https://user-images.githubusercontent.com/5237473/121115843-3b349880-c7db-11eb-8831-e8b1e5154efb.png)

**Logs**
https://pastebin.com/1zwA5yyX

**Comment by thevortex** [comment]
update to java 11 and try again

**Comment by Malexion** [comment]
Sort of works though a new error, likely have the wrong version of java

![image](https://user-images.githubusercontent.com/5237473/121191271-6f3aa880-c831-11eb-8361-1ec0df7cc88f.png)

**Comment by whatthedrunk** [comment]
Make sure to download 64bit java
