### ISSUE TITLE
[1.6.7] ATM Star Workaround/Skip Intended Recipe

### ISSUE THREAD

**Issue by lashfi** [AllTheMods/ATM-6#1767]
The ATM star can be obtained by putting an Ice and Fire dragon egg from a Tier 5 dragon in a Cyclic uncrafter. This allows for ATM stars to be obtained much more easily than through the intended recipe.

Tested in 1.6.7

**Comment by Parapa0** [comment]
Cyclic uncrafter is not obtainable?

**Comment by lashfi** [comment]
Ok, I haven't checked. I have an uncrafter left over from previous versions of the pack.

**Comment by whatthedrunk** [comment]
Yeah this is fixed for people who never got one before it was fixed.
