### ISSUE TITLE
No stronghold ?

### ISSUE THREAD

**Issue by Kezinator** [AllTheMods/ATM-6#1769]
uhhh there is no stronghold for some reasons, anybody know how to add one in ? i heard a youtuber done it once

**Comment by thevortex** [comment]
what worldtype did you choose for your world? and how have you been searching for the strongholds? with the pearl or with command

**Comment by thevortex** [comment]
also what version of the pack

**Comment by Kezinator** [comment]
> also what version of the pack

I used both ender eye and /locate stronghold
And the version i don't know, it now says 1.6.7 but it got updated 1 day ago, so im thinking might be the previous one so like 1.6.6 i guess.

**Comment by thevortex** [comment]
best thing i can suggest is to change your worldtype to default, and go generating new chunks in the hopes of a stronghold spawn, you will likely need to merge info in from a new level.dat to correct the issue. biomes o plenty, has caused numerous issues for worldtypes, if you can get to the other or the nether you may be able to track down a stronghold from repurposed structures but it may be that you need to start a new default world and migrate your base chunks and inventory over

**Comment by Kezinator** [comment]
> best thing i can suggest is to change your worldtype to default, and go generating new chunks in the hopes of a stronghold spawn, you will likely need to merge info in from a new level.dat to correct the issue. biomes o plenty, has caused numerous issues for worldtypes, if you can get to the other or the nether you may be able to track down a stronghold from repurposed structures but it may be that you need to start a new default world and migrate your base chunks and inventory over

How do i migrate things over ?

**Comment by thevortex** [comment]
get your base coordinates and go to this website to figure out what region files you need to copy over https://dinnerbone.com/minecraft/tools/coordinates/ you will need to copy over your playerdata from the world/playerdata/ folder
you can alternately copy the whole world/ folder in, with the EXCEPTION of the level.dat the level.dat has to be from the new world(you can set the new world to the same seed and it may make the biome edges a bit smoother the level.dat contains the chunkgenerator info that is used and it is important that you not carry over the old level.dat

**Comment by thevortex** [comment]
the files you need for the world chunks are in world/region but if you swap in the new  level.dat you should be ok. make a backup first

**Comment by Sakarias411** [comment]
If I use /locate stronhold and teleport to the location, it's juste above ground with no stronghold in sight, is this a known issue or am I doing something wrong ?

Level type = BIOMESOPLENTY

![unknownn](https://user-images.githubusercontent.com/4887819/121586500-03745d80-ca34-11eb-95a4-197ebe1548de.png)

**Comment by thevortex** [comment]
Biomesoplenty breaks worlds, default ftw

**Comment by IRONMAN-clone** [comment]
So true BoP breaks world same happend with me no stronghold i had to go to creative use command to spawn a piece of teleport object to go to end and finish my game But thanks for helping out with my 3rd play of atm6 with worldgen
