### ISSUE TITLE
Game crashes when teleporting across dimensions using the charged porter

### ISSUE THREAD

**Issue by PapaZ810** [AllTheMods/ATM-6#177]
**Describe the bug**
I have matter receivers in the overworld and in the End. The End matter receiver is powered as are the matter receivers in the overworld. When I select the End dimension matter receiver and activate my ender porter, it starts loading forever and then just crashes. When I load back into the world, I am at the same coordinates I was in the overworld, but in the end.

**Expected behavior**
The game should not crash
[crash-2020-10-15_18.06.38-server.txt](https://github.com/AllTheMods/ATM-6/files/5388495/crash-2020-10-15_18.06.38-server.txt)

**Screenshots**

**Additional context**

**Comment by whatthedrunk** [comment]
This looks to be fixed with the new McJtyLib. Let me know if its still crashing you after todays update.
