### ISSUE TITLE
Unable to access jarfile

### ISSUE THREAD

**Issue by Burninganime** [AllTheMods/ATM-6#1771]
SIMPLE-SERVER-FILES-1.6.8
Error : Unable to access jarfile C:\Users\rapha\OneDrive\Desktop\SIMPLE-SERVER-FILES-1.6.8\SIMPLE-SERVER-FILES-1.6.8\forge-1.16.5-36.1.25.jar (It has no forge file)
 

After downloading the mods into the server, it cannot launch and says this error: "Unable to access jarfile" and it goes into a restart loops. How do I solve this? I think the problem is that it has no forge jarfile.

**Screenshots**
![image](https://user-images.githubusercontent.com/85616591/121335255-00527200-c94d-11eb-941d-a569e87f90fb.png)
![image](https://user-images.githubusercontent.com/85616591/121335293-09dbda00-c94d-11eb-96a4-d789a3e7665e.png)

**Additional context**

**Logs**
https://pastebin.com/fG7LTZQ5

**Comment by ladylexxie** [comment]
Your pastebin is missing 99% of the info, try uploading it again

**Comment by Burninganime** [comment]
https://gist.github.com/Burninganime/3ecf700fbedb2fa6f85303e219f26e20 (serverstarter.log)

**Comment by DAmNRelentless** [comment]
Don't place your server inside a syncing OneDrive folder.
