### ISSUE TITLE
Crash report. Pixie ghosts crash worlds.

### ISSUE THREAD

**Issue by NJM1564** [AllTheMods/ATM-6#1772]
Pack version 1.16.5
Crash when killing pixies while using Evilcraft's vengeance ring. Not all pixies just frequently or when killing them on mass. Likely from when they are supposed to spawn vengeance ghosts.

**To Reproduce**
1. Find or spawn pixies.
2. Activate vengeance ring.
3. Kill pixies
4. Start game back up.

**Screenshots**
https://ibb.co/6YK9yRY

**Additional context**
Kinda funny evil pixies kill the world.

**Logs**
https://pastebin.com/nAtQgkmE

**Comment by NJM1564** [comment]
Forgot mod versions and it won't let me edit the original post.
Mod versions
Evil Craft 1.1.5
mana-and-artifice-1.3.0.6.jar

**Comment by NJM1564** [comment]
Update: Crash also happens with spectrial glasses. Adds evidence too it ghost's not being able to spawn from pixies.
Pixies can't be seen normal and are hidden. I think ghosts use the same mechanic. That is probably causing the issue.

**Comment by ladylexxie** [comment]
This is something that should be reported to the mod authors. It's out of our power to do anything about it.
