### ISSUE TITLE
All players unable to use or see chat pack version 1.6.8

### ISSUE THREAD

**Issue by FerrousOxide** [AllTheMods/ATM-6#1775]
Initially everything worked as normal, however after about 2 days (with the server being reset once per day) chat stopped working. This occured in the middle of the day, not near a reset of the server, near the start of the day chat was fine, and about halfway through the day the in game chat stopped working.

Players are able to open up the chat window, and type in text, however upon attempting to send the message no message is sent and no player is able to see the message, nor does it show as a message being sent in the server console. Players are still able to see server messages such as achievements, and any message from a OPed player using the /say command.

Multiple server resets did not resolve the issue

Unfortunately since the problem has been persistent since it started I do not have a way to reproduce, however looking over my server logs it seems to have happened around the time I got a particular error, which I will post below. This error was not present at all in the logs earlier in the day, but was constantly showing up in the logs after, and no messages where sent after the first time this error shows in the logs.

**Logs**
Here is a paste for the specific error that I believe may be the problem
https://hastebin.com/raw/rexenitixa
Here is a paste for the full logs of that day
https://hastebin.com/raw/jifuravule

**Comment by ladylexxie** [comment]
Duplicate issue #1734
