### ISSUE TITLE
How can I find the dragon(iceandfire mod)?

### ISSUE THREAD

**Issue by Lcy123dada** [AllTheMods/ATM-6#1776]
I am playing 1.6.7 version. I have been looking for dragons for more than 10 hours. Not only in the main world, I can't even find a Tier 3 dragon in The Other. What can I do to find the dragon?

**Comment by ladylexxie** [comment]
```
Fire:      The Other: Basalt Deltas
Ice:       The Other: Mountains
Lightning: The Other: Desert, The Other: Desert Hills
```

It's only a matter of time. make sure you use the Spectral Amulet. The spawn rate has gone up a LOT.

**Comment by Cratios** [comment]
You need to craft a Portal with 4 Allthemodiumingots and 1 Enderpearl and put this Portal in the Nether
