### ISSUE TITLE
No way to obtain Netherite bees (resourceful bees) in 1.6.8

### ISSUE THREAD

**Issue by matiejus** [AllTheMods/ATM-6#1777]
Netherite bees have no way to be bred in 1.6.8.

They don't spawn in the world naturally.

![image](https://user-images.githubusercontent.com/85673209/121491411-9682a880-c9de-11eb-8e2c-7d5ba8e391c3.png)

There are no breeding recipes in place.

![image](https://user-images.githubusercontent.com/85673209/121491965-1ad52b80-c9df-11eb-87c2-5da396445f8c.png)

Some of the bees are bred through block to item mutations, that grant spawn eggs. To see such recipes you look for the bees spawn egg equivalent. For example, allthemodium bee:

![image](https://user-images.githubusercontent.com/85673209/121493155-37259800-c9e0-11eb-9acb-0f14f5197b57.png)

Spawn eggs for netherite bees also are not present, if they're meant to be bred that way.

![image](https://user-images.githubusercontent.com/85673209/121492696-c2525e00-c9df-11eb-967d-a4ec144ffff1.png)
(that black egg is dragonic)

In older modpack versions the recipe was present, although the recipe required wither bees, in the current (1.6.8) build, wither bees are obtained through netherite bees, making the also unobtainable.

![image](https://user-images.githubusercontent.com/85673209/121494020-07c35b00-c9e1-11eb-836b-7004d3a836b6.png)
(The netherite bee is crossed out)

**Comment by ladylexxie** [comment]
The Netherite bee, like the other late bees, are obtained through mutations. This is shown in the Beepedia.
https://miro.com/app/board/o9J_lXWb-uM=/
