### ISSUE TITLE
Animal Feeder Industrial Foregoing and Cow 1.13b

### ISSUE THREAD

**Issue by Sclane1** [AllTheMods/ATM-6#179]
Hello,
i build a setup for Industrial Foregoing to Feed my Cows and select them to another enclosure to kill them for Pink Slime.

But the feeder dosnt feed my cows with Wheat.

Thanks
Byebye

**Comment by whatthedrunk** [comment]
Here is the issue for us to follow. https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues/857

**Comment by jeremiahwinsley** [comment]
Fixed in 1.3.9.
