### ISSUE TITLE
OneProbe/EnderStorage Crashing on viewing

### ISSUE THREAD

**Issue by vSwifty** [AllTheMods/ATM-6#1793]
**Describe the bug**
Pack Version - 1.6.9
Looking at ender tanks with fissile fuel from Mekanism causes the client to crash

**To Reproduce**
1. Put ender tanks down
2. Pump Mekanism Fissile fuel into it
3. Look at ender tank
4. Crash

**Screenshots**
N/A

**Additional context**
It's a privatized ender tank 

**Logs**
https://paste.ee/p/163Wu

**Comment by DAmNRelentless** [comment]
I wasn't able to reproduce this issue.
Does it only happen with the Fissile Fuel or with other fluids as well?

**Comment by vSwifty** [comment]
> I wasn't able to reproduce this issue.
> Does it only happen with the Fissile Fuel or with other fluids as well?

I went ahead and replicated the setup on a single player creative world and it was working fine there so I'm guessing something odd might be happening server-side, I'll get with my friend later and see if we can narrow down the details.

The only other issue I found similar to mines is this one 
McJtyMods/TheOneProbe#490

My guess going over the crash log is that TOP seems to act up when it displays info that's too wide/long for it's tooltip, In this case it'd be displaying the details from EnderTanks and I'm guessing the length of my friend's name is causing the rendered box to be extra long which is causing TOP to crash itself. But it's all speculation until I can confirm it.

**Comment by DAmNRelentless** [comment]
It's modded Minecraft after all. Probably just a temporary thing from the server-side. Feel free to open another issue in the future if it happens again. Thanks for the feedback.

**Comment by Speiger** [comment]
@DAmNRelentless this issue happens if server side mods & client side mods (that use one probe) are not exactly the same.
The API uses autogenerated Ids instead of a proper ID system for components that are rendered.
https://github.com/McJtyMods/TheOneProbe/issues/472

**Comment by vSwifty** [comment]
> @DAmNRelentless this issue happens if server side mods & client side mods (that use one probe) are not exactly the same.
> The API uses autogenerated Ids instead of a proper ID system for components that are rendered.
> [McJtyMods/TheOneProbe#472](https://github.com/McJtyMods/TheOneProbe/issues/472)

I see, We do use Terraforged on our server(serverside only, not on client) and I'm personally using JourneyMap on my end could that be it?

**Comment by Speiger** [comment]
@vSwifty if they have a one probe integration yes. Though JurneyMap does not have one.
Also make sure configs match on server & client. Because if a config allows to disable a one probe plugin you have the exact same issue.
