### ISSUE TITLE
1.6.9 Client crash on load due to syntax error in KubeJS startup Scripts

### ISSUE THREAD

**Issue by EvilGrinUK** [AllTheMods/ATM-6#1794]
**Describe the bug**
ATM6 1.6.9 will not load due to a syntax error in KubeJS startup scripts. This may be a specific to installing the mod with ATLauncher.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install ATM6 1.6.9 in AT Launcher
2. Run the newly installed instance
3. See error

**Screenshots**

![image](https://user-images.githubusercontent.com/2217729/121773386-923bc400-cb73-11eb-957e-90d62ee9f445.png)

**Logs**

latest.log https://gist.github.com/EvilGrinUK/209bda3c4339598ff747322e3d5fe683
crash log https://gist.github.com/EvilGrinUK/681447558a06ec3bc76329d8f7d47f2e
kubejs startup log https://gist.github.com/EvilGrinUK/31dd3cfb2dea0657f8e7e37fb680583d

**Comment by EvilGrinUK** [comment]
I have manually fixed the install so it starts up. There was a spurious kubejs config file in kubejs/startup_scripts. It was called 'custom_stuff.js' and is dated from the March. I have renamed it so KubeJS will not process it and my client loads.

deffo appears to be an ATLauncher issue as this file is not present on an ATM6 install from the curse launcher.

**Comment by EvilGrinUK** [comment]
![image](https://user-images.githubusercontent.com/2217729/121773811-6706a400-cb76-11eb-946c-2024d87e6ab3.png)

**Comment by DAmNRelentless** [comment]
Install issues can't be fixed by us and we are only recommending the official CurseForge launcher as well as the GDLauncher.
