### ISSUE TITLE
Crashing when opening world

### ISSUE THREAD

**Issue by Ferajka** [AllTheMods/ATM-6#1795]
I'm using the ATM 6 To The Sky 1.0.8 version.
So yesterday, my computer shut off while the game was saving, and now everytime when I open the world, there's only a black screen, nothing happens, and if I click once it crashes. I tried reinstalling, updating versions, didn't work, anything else is beyond my abilities, so I would like to ask for help here. Other worlds work, just this one doesn't and I don't have any backups. I included the latest log, and the crash report it creates after crashing. Please help me out.

[latest.log](https://github.com/AllTheMods/ATM-6/files/6642236/latest.log)
[crash-2021-06-12_11.09.47-server.txt](https://github.com/AllTheMods/ATM-6/files/6642237/crash-2021-06-12_11.09.47-server.txt)

**Comment by OmPatel1033** [comment]
did you try and download a new server file, start it up, and replace the world folder onto the new server file? according to the crash log the problem is a server tick loop caused by the server unable to load the config file "integratedterminals-server.toml"

**Comment by DAmNRelentless** [comment]
Please open your issue on the right modpack repository.
There also have been several updates since your report so that might be fixed already: https://github.com/AllTheMods/atm6-sky/issues
