### ISSUE TITLE
Server won't start after install of JDK 16.0.1 for windows

### ISSUE THREAD

**Issue by DefermeJoris** [AllTheMods/ATM-6#1796]
New (or old) server install gives 'java.lang.illegalaccesserror'.
This is an error that occurs when I have the java developer kit 16.0.1 installed. I had this kit installed to host a 1.17 vanilla server on the same machine. When I delete/remove the JDK everything works like normal. But I would like to still host my 1.17 vanilla server.
![ohNo](https://user-images.githubusercontent.com/32481796/121777009-39c6ef80-cb90-11eb-8fff-ecabc0fffa89.PNG)

**Comment by starforcraft** [comment]
Java 16 isn't supported from Minecraft. It will be supported in 1.17.
