### ISSUE TITLE
Crash at world load after updating to ATM6 1.6.9.

### ISSUE THREAD

**Issue by Furious1964** [AllTheMods/ATM-6#1797]
ATM6 Version: 1.6.9
MC Version: 1.16.5
Forge Version: 36.1.31

**Describe the bug**
Crashes at world load, just updated the pack today to 1.6.9.

**To Reproduce**
1. Updated from 1.6.8 to 1.6.9.
2. Started game.
3. Attempted to load world...
4. Crash.

**Screenshots**
https://imgur.com/rbGOLfO

**Logs**
https://pastebin.com/Fmu5HsCW

**Comment by radiomike** [comment]
You seem to have added valhelsia core to your pack?

**Comment by DAmNRelentless** [comment]
We don't give support if you decide to modify the pack yourself.
Sorry but you have to fix this problem yourself since it's technically not our pack anymore especially with stuff like OptiFine.
