### ISSUE TITLE
Server Lag Issue 

### ISSUE THREAD

**Issue by kk258966** [AllTheMods/ATM-6#1798]
My server is getting random lag spikes. Tried using Sparks but having troubles understanding it.
The version I'm currently using is ATM6 1.6.7
Also I'm hosting my Server on GCP with 16G Ram and 10G allocated.
And the reports from spikes are as below
For ticks>=400
https://spark.lucko.me/KXPzUei950
Just ran a profile
https://spark.lucko.me/WP46Y34IDq
![image](https://user-images.githubusercontent.com/20612483/121783341-92be7400-cbe0-11eb-8bd0-824bdbdbca89.png)

**Comment by radiomike** [comment]
Your first spark profile shows refined storage as the culprit. Mainly from internal autocrafting I think. 

The second profile is mostly zombies. Check mob farms.

**Comment by kk258966** [comment]
Thanks, found a command ／forge entity list and found 101 zombies if I'm understanding it correctly.Turned my world into peaceful and then back to hard to fix it.For some reason still getting zombies spawning large amount in that area not really seeing where.Used spectator and didn't find that large amount of zombies.Also recently found that cave illuminators also cause quite some amount of lag. Will wait a few days and update the pack to .10 to see if it helps a bit.
![unknown.png](https://user-images.githubusercontent.com/20612483/122016254-76deec00-cdf3-11eb-92bb-26598d039732.png)

**Comment by radiomike** [comment]
Have a look at crash utilities, it's in the pack. Has a very useful gui for finding and managing mobs and tile entities. You'll need to be opped and you'll probably have to assign a keybind.
You can also use `forge track start entity 10` followed 10 secs later by `forge track entity` to list 10 worst performing entities. Replace `entity` with `te` to see tileentities instead.

**Comment by kk258966** [comment]
Thanks a lot . Didn't knew that mod before , makes it easier to track and eliminate lag issue. Still need some time to learn how to use it more , but it helps to solve this problem.

**Comment by DAmNRelentless** [comment]
It's a huge modpack. You can't really do anything else than eliminating your lag sources and the most important parts: do regular restarts because of memory leaks or garbage collection issues.
