### ISSUE TITLE
Errors in currently selected datapacks...

### ISSUE THREAD

**Issue by BigAl607** [AllTheMods/ATM-6#180]
I started playing your pack last night, started a world, found a safe spot, then logged out for bed. Today when I tried to play that same world, I get the "Errors in currently selected datapacks..." error message.

![atm61](https://user-images.githubusercontent.com/13182567/96354302-27e58900-10a3-11eb-97dc-d1a8e887d3e4.png)

When I click on "Safe Mode" nothing happens.

I decided to try a new world, and the same thing happens. On the create new world screen, there's an option to view the datapacks folder. When I open it in game, it shows mods instead of datapacks, and some of the mods are listed as incompatible because they are made for an older versions of MC.

![atm62](https://user-images.githubusercontent.com/13182567/96354329-7eeb5e00-10a3-11eb-90c1-f0d97bbd639f.png)

Not really sure what to do. I only added 1 mod (I Like Wood), but removed it when I got the error, and it still happens. I have looked online for help before coming here, but any answer that actually helped described removing mods that aren't in this pack.

**Comment by Niklars** [comment]
The same happend on my sons Minecraft but not mine. I re-installed the modpack on hos computer and it worked.
