### ISSUE TITLE
Can the Fluxbore be upgraded with Vibranium and Allthemodium?

### ISSUE THREAD

**Issue by Furious1964** [AllTheMods/ATM-6#1805]
Just upgraded the Fluxbore to T4: Netherite and I would like to upgrade it to T6, but I can't as nothing is able to upgrade it. How can this be done?

**Comment by whatthedrunk** [comment]
At first glance it looks like we won't be able to add custom tiers to the fluxbore yet but we will continue looking into it for the future. Thanks for the idea.
