### ISSUE TITLE
Digital Miner and Thermal Series Silktouch Quarry Builder won't mine Unobtanium, Vibranium and Allthemodium.

### ISSUE THREAD

**Issue by Furious1964** [AllTheMods/ATM-6#1806]
What does mine this? Can his be fixed please?

**Comment by Parapa0** [comment]
No, quarry can mine atm ores. 
allthemodium: needs netherite+ pickaxe
vibranium: needs allthemodium+ pickaxe
unobtainum: needs vibranium+ pickaxe

mining gadgets and block breaker can mine them.

Asking in the discord will be better for this type of question and you will get a response faster:)
