### ISSUE TITLE
Internal Server Error when growing Nature seeds with Agricarnation and Sigil of Green Grove

### ISSUE THREAD

**Issue by Nova115** [AllTheMods/ATM-6#1808]
ATM6 1.6.8

So I am trying to grow Nature seeds for nature essence to power the dandelifeon.  I am using the inferium farmland to grow the seed. I am only using a single seed btw. I am also using the Agricarnation flower + the sigil of the green grove to speed up the growth. I can have the flower down no problem but when I activate the sigil of the green grove the game will work for about 1.5 seconds and then I will disconnect getting an internal server. The weirdest part of all of this is a mushroom tree will spawn from where I disconnected. It is completely re-creatable as I have done it twice all following the same conditions. 

1. Place the seed on farmland 
2. Place flower with mana pool 
3. Activate Sigil of green grove. 

The only way to load back into the server is to wipe my UUID from the player database forcing me to get all my items back.

**Comment by Nova115** [comment]
P.S I had my friend recreate it and the EXACT same thing happened

**Comment by Nova115** [comment]
Tried It with out the Agricarnation Flower and I still got the internal error

**Comment by ladylexxie** [comment]
Cannot recreate in the current version.
