### ISSUE TITLE
KubeJS syntax error "const ores" redeclaration 1.1.6.10 

### ISSUE THREAD

**Issue by NicholasJMES** [AllTheMods/ATM-6#1814]
**Describe the bug**
When starting the program, an error will pop up saying that KubeJS failed to load correctly and to look at the kubejs log.  Noting also that there are syntax errors.

**To Reproduce**
Simply start ATM6 and wait

**Screenshots**
![image](https://user-images.githubusercontent.com/83792311/121943963-bcc68200-cd17-11eb-80a9-d9736dfc8aae.png)

**Additional context**
Note: I cannot do a pastebin right now for my minecraft log, but the KubeJS log is 3 lines.  If you need me to post the minecraft log as well let me know and I will do so.

It appears that when "const ores" is declared in custom_items.js and "var ores" is declared in custom_stuff.js there is a redeclaration error.  I've been able to load in by either removing the var ores entry or changing const to var.  I don't know if this will have any side effects on the game.

**Logs**
[13:51:17] [INFO] Loaded script startup_scripts:custom_items.js in 0.259 s
[13:51:17] [ERR ] Error loading KubeJS script: TypeError: TypeError: redeclaration of const ores.
[13:51:17] [INFO] Loaded 1/2 KubeJS startup scripts in 0.79 s

**Comment by DAmNRelentless** [comment]
Are you by chance using the ATLauncher to launch the pack? I've seen this issue before from someone using the ATLauncher.

**Comment by DAmNRelentless** [comment]
Definitely not reproducible with the current version when installing with CF launcher or GD which are the only launchers we recommend so I will close this issue.
You can still answer if you're having this issue while using CF or GD launcher.

**Comment by NicholasJMES** [comment]
Oh it's totally the ATLauncher doing it.  Thanks.
