### ISSUE TITLE
Game Crashes 1.6.10

### ISSUE THREAD

**Issue by bobo6** [AllTheMods/ATM-6#1815]
I Play the Pack on a Server every time i put acceleration Card in to the LazierAE2 machines the game crashes on client site. I can get on the Server after the Recipe is completly done.

[latest.log](https://github.com/AllTheMods/ATM-6/files/6651517/latest.log)

Added Mods: Sophisticated Backpacks, Journey map, Tesseract, Framed Compacting Drawers

**Comment by DAmNRelentless** [comment]
Thanks for the report. This needs to be fixed by LazierAE2 which happens to be my mod.
Sorry for the inconvenience. I will look into this asap.

**Comment by DAmNRelentless** [comment]
Whoops, didn't mean to close this.

**Comment by DAmNRelentless** [comment]
Fixed in https://github.com/RLNT/minecraft_lazierae2/commit/126a0e10685cc011346d10c15662a6b986f740b3
Either you install this hotfix version yourself or you wait for the next pack update.

Thanks for reporting!

**Comment by bobo6** [comment]
thank you for Updating the Mod. works great
