### ISSUE TITLE
Alll The Mods 6 

### ISSUE THREAD

**Issue by mikeabner75** [AllTheMods/ATM-6#1816]
**Describe the bug**
Game Randomly crashes every so often ranging from 20 mins to 2 hours.

**To Reproduce**
I have no idea, It is extremely random.

**Logs**
https://gist.github.com/mikeabner75/d0d0dadad06901cbeaafe325224f7956

**Comment by DAmNRelentless** [comment]
That is an error which is caused due to a invalid Java installation or a problem with your OS.
It's not pack related. Make sure to use Java 11 to run the pack.
