### ISSUE TITLE
Spawner just spawning entities then they immediately despawn.

### ISSUE THREAD

**Issue by jacquesco07** [AllTheMods/ATM-6#1817]
**Describe the bug**
I'm on version 1.6.10. I modified a spawner with the apotheosis stuff - clocks, sugar, fermented spider eye, Allthemodium ingot ghast tears, and a redstone comparator. I also put a spawner agitator from pneumaticCraft on it. It was working fine when I just had the clocks, sugar, and Allthemodium, but after I added the fermented spider eye and ghast tears, the mobs would just spawn then immediately despawn. 

**Screenshots**

**Additional context**

![2021-06-14_19 39 39](https://user-images.githubusercontent.com/8894081/121984746-66be0280-cd48-11eb-9b03-de5d94bd85bf.png)
![2021-06-14_19 39 45](https://user-images.githubusercontent.com/8894081/121984754-6887c600-cd48-11eb-8baf-145b9cd6578e.png)
![2021-06-14_19 39 47](https://user-images.githubusercontent.com/8894081/121984758-6a518980-cd48-11eb-8845-cbe72d163628.png)
![2021-06-14_19 39 48](https://user-images.githubusercontent.com/8894081/121984762-6c1b4d00-cd48-11eb-8de7-fe4f6fceaa94.png)

**Comment by DAmNRelentless** [comment]
Please try it again by applying the following things:
![](https://i.imgur.com/OD0yYV4.png)

**Comment by jacquesco07** [comment]
So using the vanilla dragon egg on the spawner should fix this issue?

**Comment by jacquesco07** [comment]
> Please try it again by applying the following things:
> ![](https://camo.githubusercontent.com/29521ec64d131915f8de1e8ad43cbb07977d29607e947585f83168bae26e0a39/68747470733a2f2f692e696d6775722e636f6d2f4f4430795956342e706e67)

But the spawner already ignores spawn conditions since I put an Allthemodium ingot in it.

**Comment by monstro805** [comment]
ok 

Sent from Yahoo Mail on Android 
 
  On Tue, Jun 15, 2021 at 9:17 PM, ***@***.***> wrote:   


Closed #1817.
