### ISSUE TITLE
Game crashed now pc won't start

### ISSUE THREAD

**Issue by rimoldi98** [AllTheMods/ATM-6#182]
I was in the nether, the game crashed, so I went back to the overworld to reset my nether, when I exited the world the game crashed again, but now my pc restarted and it won't start.

Here is a picture of what shows up.

![IMG_20201018_100013785](https://user-images.githubusercontent.com/35239932/96368315-b69ce900-1129-11eb-82d8-295b58e1043d.jpg)

**Comment by puppydemon20** [comment]
This does not seem to be something caused by ATM6

**Comment by sanyi** [comment]
might be that cooked your video card
