### ISSUE TITLE
Soul Lava

### ISSUE THREAD

**Issue by bobo6** [AllTheMods/ATM-6#1824]
I have the Problem that my RFTools Builder doesnt mine Soul Lava. Every time  i try it the Builder asks "Are Fake Players Enabled".

Fake Players are Enabled and i have Allies with them in FTB Teams. It happens on Claimed and unclaimed Chunks

Version 1.6.10 and it was on 1.6.9 also

I hope there is a fiox for it

Best Regards

**Comment by thevortex** [comment]
soul lava needs to be bucketed by the player
