### ISSUE TITLE
allthemodium - vibranium ingot issue

### ISSUE THREAD

**Issue by Spin5123** [AllTheMods/ATM-6#1826]
Hi i made the allthemodium vibranium alloy in the dragon forge in update 1.6.8 but once i updated the server to 1.6.10 the alloy is not possible anymore how do i fix this

**Comment by thevortex** [comment]
the recipes do work, it appears to be an issue with ice and fire and their new recipe handler is not syncing in multiplayer, the recipe exists in single player and IT DOES WORK in multiplayer, however the ORDER of the ingots matters. when you are creating the alloys look at the name for a clue to the ordering, with a vibranium - allthemodium alloy(the stronger metal comes first) vibranium goes in slot 1 allthemodium in slot 2. same for unobtanium - vibranium alloy, the left most metal in the alloy image is the metal that goes on the left.

**Comment by Spin5123** [comment]
But the server is normally using the mod properly in a new world but when i copy over the world i used the recipe itself dissapears so i cannot use the forge for the alloy at all
