### ISSUE TITLE
Create (create) has failed to load correctly

### ISSUE THREAD

**Issue by ICCtrl** [AllTheMods/ATM-6#1827]
All The Mods 6 - ATM6 - 1.16.5
Version: 1.16.5-1.16.10.zip (latest as of writing this)
When i try to start up the pack i get a msg saying: Create (create) has failed to load correctly
I havent had this before playing with the pack and would like to know why this is. There are a couple of mods in there that aren't in the pack itself, but i have never had a problem with them before in older versions.

**Screenshots**
https://i.postimg.cc/zB6w0zR0/ATM6.png

**Additional context**
As said previously, there are other mods that have had no effect on starting up in other versions, if its the version breaking one of the mods, please note which mod since i would like to play on the newest version. 

**Logs**
https://pastebin.com/cTUVPU2x
https://pastebin.com/psW38QEK    (like 20 min later, dont know if theres a difference besides the time)

**Comment by Eragoneq** [comment]
That's the fault of Abnormals Core 3.2.0. I had the same problem with it. Downgrade to 3.1.1.

Link to related issue: https://github.com/team-abnormals/abnormals-core/issues/112

**Comment by whatthedrunk** [comment]
Yeah that mod is not in the pack but if you do what they say you should be good.
