### ISSUE TITLE
Allthemodium Alloy Ingots missing recipes

### ISSUE THREAD

**Issue by kjchiamu** [AllTheMods/ATM-6#1828]
Updated from 1.6.8 to 1.6.10, and the Allthemodium alloy dragon forge recipes were removed.

**Comment by DAmNRelentless** [comment]
They were removed when updating from 1.6.8 to 1.6.9 because the library for KubeJS updated and causes recipe errors.
They were added back in 1.6.10.

**Comment by DAmNRelentless** [comment]
Just tested it and it indeed works:
![](https://i.imgur.com/un5lBdB.png)

Make sure you are actually on 1.6.10 and not on 1.6.9 and maybe reinstall the pack.

**Comment by Triviuhh** [comment]
I know this issue is closed, but I don't think it's as simple as this. We have a tier 5 lightning dragon and when attempting to use the forge it gives us ash no matter the configuration of the Unobtanium/Vibranium. We were able to get allthemodium + unobtanium to work though.
