### ISSUE TITLE
Blazing bee 

### ISSUE THREAD

**Issue by DevilMayCryIfrit** [AllTheMods/ATM-6#1829]
Hi a had to blazing bees in the overworld and after 2 breeds and waited on the 3rd they disappeared. My question is do blazing bees die after so long or is this a bug?

**Comment by ladylexxie** [comment]
Bees will despawn under 2 conditions:
1. they don't have a hive/apiary to live in
2. they don't have a flower/block to pollinate
You need to fulfill both those conditions, otherwise the bee will despawn in a few minutes.
