### ISSUE TITLE
Vibranium is not spawning

### ISSUE THREAD

**Issue by faaaaq** [AllTheMods/ATM-6#183]
**Describe the bug**
Vibranium is not spawning.  Tried multiple brand new worlds in 1.1.2 and 1.1.5, both local and servers, and vibranium never spawns in the nether.  Checked using sight potions in creative, between 90 and 130 blocks high, in all biomes.  Tested by setting a digital miner to search for vibranium and it also finds none.
**To Reproduce**
Go to nether, look for vibranium.

**Expected behavior**
Find vibranium at high altitudes in the warped and crimson forests (or anywhere, really..)

**Additional context**
Issue started with my 1.1.2 server, and no amount of respawning the entire nether or starting new worlds corrects the issue.  So I started a brand new world locally, on 1.1.5, and the issue persists.  I cannot get Vibranium to spawn no matter what I try.

**Comment by puppydemon20** [comment]
I am able to replicate this behavior in 1.13b as well. It also does not spawn in any biome.

**Comment by whatthedrunk** [comment]
It's a lot more rare then it used to be. I just started up a new nether and found one.  https://i.imgur.com/lrYerV2.png

**Comment by faaaaq** [comment]
Any chance you can tell me the seed you were using?  If I load a world under that same seed I can go to the coordinates in your screenshot and verify if it is working, just stupid rare.  Ive spent 45 minutes in multiple new worlds in creative mode with vibranium sight potions and not found a single one.  Allthemodium and Unobtanium or whatever I am having no issues finding, though.

**Comment by whatthedrunk** [comment]
3930404414364956418

**Comment by faaaaq** [comment]
...very very interesting.  I see the issue now.  Thank you for the seed, that let me do some testing.  Seems to be an issue with shaders.  Having certain shaders on makes the block highlighting from the sight potion not work, but just for vibranium.  It still works for the other two ATM ores for some reason.  Apparently that plus my poor luck in organically finding the ore made it appear to not exist.  I disabled all shaders and actually found a ton of ore right above the portal in my server world, so it doesnt even seem to be especially rare

**Comment by puppydemon20** [comment]
To be noted, I was unable to find any ore in 1.1.3b on several world seeds, including the one given above. However I have found sever in 1.1.5 without issue. Guess I'll have to update my server.
