### ISSUE TITLE
Recent 1.6.10 update questions

### ISSUE THREAD

**Issue by Tyrael962** [AllTheMods/ATM-6#1830]
Recently just updated the server and my client to 1.6.10 and I'm noticing in JEI that the unobtainium/vibranium and the allthemodium/unobtainium have no crafting process when testing the forge like before it just turned to ash.  Recipies in JEI just rotate it back and forth from dust to ingot and vise versa 
halp
Thank you

**Comment by DAmNRelentless** [comment]
I've just closed an issue like this.
I am in a 1.6.10 testing instance right now and for it's working just fine:
![](https://i.imgur.com/un5lBdB.png)

**Comment by DAmNRelentless** [comment]
Related to https://github.com/AllTheMods/ATM-6/issues/1828

**Comment by DAmNRelentless** [comment]
If you are getting Ash, you are putting them in the wrong order. The order actually matters.

**Comment by DAmNRelentless** [comment]
Related to: https://github.com/AllTheMods/ATM-6/issues/1828

Please read this comment for an explanation: https://github.com/AllTheMods/ATM-6/issues/1828#issuecomment-861834451

**Comment by Tyrael962** [comment]
Perfect Thank you for the quick response!
