### ISSUE TITLE
Simple Server Modpack URL Hosted on Discord?

### ISSUE THREAD

**Issue by devmattrick** [AllTheMods/ATM-6#1832]
**Describe the bug**
Hi, I was updating to the latest version of ATM6 and noticed the new modpackUrl in the simple server files is not longer a CurseForge URL, but rather a Discord CDN URL. I'm just opening this issue because I wanted to make sure that this is intentional.

**To Reproduce**
1. Download [latest](https://www.curseforge.com/minecraft/modpacks/all-the-mods-6/files/3351391) simple server files from CurseForge
1. See modpackUrl in server-setup-config.yaml

**Screenshots**
N/A

**Additional context**
N/A

**Logs**
N/A

**Comment by DAmNRelentless** [comment]
It is but will be changed in future updates because Discord will probably start removing files after 14 days in an upcoming update.
