### ISSUE TITLE
Vibranium/Unobtainium Alloy recipe missing [1.6.10]

### ISSUE THREAD

**Issue by Triviuhh** [AllTheMods/ATM-6#1836]
After updating our server to 1.6.10 the recipe to make the Vibranium/Unobtainium alloys are missing. The dragonfire forge recipe is no longer there, and as far as I can see there is nothing to replace that recipe.

**Comment by thevortex** [comment]
each alloy requires a different forge by the way. ice is required for unobtainium/vibranium, lightning for unobtainium/allthemodium fire for vibranium/allthemodium
