### ISSUE TITLE
Hoppers turn invisible to other players on server

### ISSUE THREAD

**Issue by peanutmm** [AllTheMods/ATM-6#1837]
Modpack Version: 1.6.9

When a vanilla hopper is placed on a powered (by redstone) location (e.g. on top of a redstone torch), other players can not see it and have the client/server invisible block issue (where players get stuck floating).

**Comment by DAmNRelentless** [comment]
This seems to be a Vanilla issue which could be related to this https://bugs.mojang.com/browse/MC-194949
We were able to reproduce this on the test server but it doesn't seem to be specific to the modpack.

2 valid workarounds:
1. reloading the chunk by teleporting somewhere else and then back to the position e.g. with Waystones
2. forcing a block update by placing any block adjacent to the Hopper's position

Sorry but there is not really anything we can do about this.
This should be reported to Minecraft instead.
