### ISSUE TITLE
Recipe Missing after server update

### ISSUE THREAD

**Issue by Spin5123** [AllTheMods/ATM-6#1840]
All The Mods 6 1.6.10

I Have upgraded my server from 1.6.8 to 1.6.10 because of a chat issue where the chat wasnt functioning and now i have missing recipes only on my world. If i let the server create its own world the dragon forge can be used to make unobtanium -  vibranium alloy but when i replace the world and restart the server with my world the forge recipe dissapears it does even show up on the JEI to continue . so how can i fix this

**To Reproduce**
1. update the server from 1.6.8 to 1.6.10

**Additional context**
cannot make the ingot anymore on this server so do not know what to do and how to fix it

Logs : https://hastebin.com/ojucokocit.yaml

**Comment by kts325** [comment]
This is a bug in kubejs that we are waiting on an update to fix

**Comment by Spin5123** [comment]
ohh ohkay so just gotta wait then? 

Thank you
