### ISSUE TITLE
Creative Crafter lagging/crashing server, fixed in latest Refined Storage.

### ISSUE THREAD

**Issue by calebh514** [AllTheMods/ATM-6#1841]
Creative Crafters [pushed the limits of Refined Storage](https://github.com/starforcraft/Creative-Crafter/issues/1) so much that it exposed a flaw in how RS handled processing recipes. 

This is fixed in [Refined Storage 1.19.3](https://github.com/refinedmods/refinedstorage/pull/3001) which was released shortly after ATM 6 1.6.10. I don't know how often this pack updates or if this is the right place to report something like this, but considering this has the ability to send servers into unrecoverable boot looping depending on how big the autocrafting request was it's probably worth pushing an update to the pack.

**Comment by DAmNRelentless** [comment]
This is already done in our dev version but we are working on a lot of other things for the next update so it's not released yet.
