### ISSUE TITLE
Astral Sorcery - starlight relayed through lenses not transmuting iron ore 

### ISSUE THREAD

**Issue by flowz91** [AllTheMods/ATM-6#1846]
Current vesion - All the Mods 6-1.6.10

Using only Astral Sorcery objects/mechanics -
Directing starlight from a collector crystal with crystal or prism lenses, regardless of their quality, at iron ore to transmute it into starmetal ore does not work. Both the beam of light and the particle effect on the iron ore appear like normal, but the block never transforms.

Connecting the ore directly to a collector crystal does work as expected. Using lenses to connect other blocks such as crystal clusters to speed up growth seems to work as well, but it's hard to 100% verify.

Lenses with AFAIK ideal stats:
<img width="166" alt="Screenshot 2021-06-17 174056" src="https://user-images.githubusercontent.com/86067862/122430341-cfe58600-cf93-11eb-83e5-0a546473bd45.png">

Initial setup:
collector crystal -> two lenses -> one iron ore block each
collector crystal -> three iron ore blocks directly
<img width="1829" alt="Screenshot 2021-06-17 174424" src="https://user-images.githubusercontent.com/86067862/122430346-d07e1c80-cf93-11eb-91bc-ec769f6973f9.png">

Three directly linked blocks transform almost instantly even at noon, single blocks connected to lenses never do. 
A full ingame day later:
<img width="1916" alt="Screenshot 2021-06-17 180036" src="https://user-images.githubusercontent.com/86067862/122432827-f4426200-cf95-11eb-9bfb-5beed40e9d67.png">

**Comment by ladylexxie** [comment]
This looks like a bug with Astral Sorcery, not ATM6, this isn't added or modified by us. Nothing we can do unfortunately.
