### ISSUE TITLE
Tinkers construct issue

### ISSUE THREAD

**Issue by Spin5123** [AllTheMods/ATM-6#1850]
ATM 1.6.10
Hi I am running an all the mods 1.6.10 server and in the server i cannot craft the tool heads from the tinkers construct mod to make the moulds if i hover over the pickaxe head or broad blade head or any such tools it shows up as item.tconstruct.part.missing_info i cannot make the tool heads itself so cannot make the moulds so the smelter is pretty useless how can i fix this issue

**To Reproduce**
Had the issue since i installed the server

logs:https://hastebin.com/ojucokocit.yaml

**Comment by DAmNRelentless** [comment]
This was fixed in a newer Tinkers Construct version which will be available in the next update of ATM6.
