### ISSUE TITLE
Rats - Rat Radius Staff

### ISSUE THREAD

**Issue by Skogisplayer** [AllTheMods/ATM-6#1851]
1.6.9, 1.6.10
**Describe the bug**
Rat Radius Staff works as Cheese Staff

Click a tamed rat with Radius staff.
Press any block with Radius staff. (this is supposed to bring up a radius select menu, but brings up the UI for the cheese staff instead)

**Comment by DAmNRelentless** [comment]
That sounds like a mod issue. We do not change any behaviour of the tools in that Rats mod.
Please report this to the mod author.
