### ISSUE TITLE
Corrupted wplayer>.dat

### ISSUE THREAD

**Issue by SoonBanned** [AllTheMods/ATM-6#1854]
**Describe the bug + Additional context**

So this will be a bit difficult but to summarize it I would say that after being attacked by 2 endermites while looking into a chest, I decided to fight back but at the moment my weapon swang, the server had crashed and would not restart, we had to run server checker on it and now it's booting but here comes the fun part. Anyone can log in except me because my player.dat is corrupted and I tried to recover it but the best I managed to do was to make it openable in NBT explorer by rectifying the signature of the file. So now I've got a kinda working dat without the inventory in it  (visible by NTB explorer) and I'm trying to get back my items by calling for help here. Unfortunately, I can't give you the logs right now because I'm not the owner but I have my player.dat if you can manage to recover the items you'll know the exact enchants and maybe this will help reproduce the whole thing?

**To Reproduce**
Steps to reproduce the behavior (in theory):
1. Go to the end
2. Take endermites damages (with an armor which has a lot of random enchants)
3. Kill one endermite 
4. See error and corrupt your player.dat 

**Player.dat**
[openeable.zip](https://github.com/AllTheMods/ATM-6/files/6677067/openeable.zip)

**Comment by ladylexxie** [comment]
Why is the server owner not restoring your player data from the backups?

**Comment by SoonBanned** [comment]
He told me that the backups were only the levels and regions, not player data which surprised me but if you say so I might need to know where to find the 'backup' player.dat to indicate it to my friend

**Comment by ladylexxie** [comment]
There should be a "playerdata" folder in the parent directory of the backup

**Comment by SoonBanned** [comment]
I'll give a try with this and keep you updated ^^

**Comment by ladylexxie** [comment]
Everything is backed up. basically if you take the backup to a new server, everything should be *exactly* the same

**Comment by SoonBanned** [comment]
He said that in his config not everything is backed up but  I doubt so he will hand me a copy of the last backup and I'll try my best to search correctly x)

**Comment by ladylexxie** [comment]
So he's leaving out 50% of the game from the backup? xD
Yikes >->

**Comment by SoonBanned** [comment]
He's telling so, I'll see the backup later today I'll be able to tell you x)
