### ISSUE TITLE
Seed Pouch not working

### ISSUE THREAD

**Issue by CDChalk** [AllTheMods/ATM-6#1856]
Pack version 6-1.6.10 (1.16.5)

After crafting the pouch, right clicking on the pouch with both mod seeds and base Minecraft seeds selected will not place the seeds in the pouch. The "+" is shown on the bag, however it cannot be interacted with.

**To Reproduce**
1. Go to inventory (e)
2. Click on a seed from either base minecraft or modded
3. Right click seed on seed pouch showing "+"

**Comment by 19175** [comment]
This is most likely a conflict with MouseTweaks, changing `RMBtweak=1` to `RMBTweak=0` in line one of MouseTweaks.cfg will turn this off and fix it.

**Comment by ladylexxie** [comment]
This has been fixed in 1.8.3
