### ISSUE TITLE
Mekanism fluid tank disappears when crafting Immersive Eng treated wood

### ISSUE THREAD

**Issue by crwoody** [AllTheMods/ATM-6#186]
Mekanism Elite fluid tank had 5000 mb.  Crafted 8 treated wood and disappears
Only happens when using Elite and Ultimate fluid tanks. Basic and Advanced do not work in recipe.
Does not matter how much fluid is in tank and how many planks will only craft 8 treated wood.

**Comment by jeremiahwinsley** [comment]
Fixed in 1.3.9.
