### ISSUE TITLE
Hopper botany pots are nerfed too much

### ISSUE THREAD

**Issue by LuciusV** [AllTheMods/ATM-6#1862]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I realize how much effort is required to make hopper botany pots. At stage of the game when you can afford them you probably do not need them already. 

**Describe the solution you'd like**
Please revert to original recipe of hopper + botany pot.

**Describe alternatives you've considered**
Maybe add ender pearl to recipe if you want to nerf so much.

**Comment by DAmNRelentless** [comment]
https://github.com/AllTheMods/ATM-6/issues/1838
