### ISSUE TITLE
ATM6 - Remote Host Forcibly closed

### ISSUE THREAD

**Issue by Kpres** [AllTheMods/ATM-6#1863]
So whenever I join my friends server that I have played on for a while, I am now getting this really weird error that I never used to get. Whenever I try to connect to the server it will always eventually kick me with the classic "An existing connection was forcibly closed by the remote host". I can confirm this does not happen on other atm6 servers nor vanilla minecraft servers.
Here are the logs for every time I get kicked it looks like something to do with the void ore miner?

Here are the logs the top 2 are errors and the bottom one about the void ore miner registry is fatal.

https://paste.ee/p/Pon7N

**Comment by DAmNRelentless** [comment]
This is not a page where you should submit your crash reports or kicks. Especially if they are incomplete.
If you want help with this stuff, join the [Discord](https://discordapp.com/invite/rbSZNDQ) server instead.
