### ISSUE TITLE
F&I dragon crashes game midair 1.1.6

### ISSUE THREAD

**Issue by witherofek** [AllTheMods/ATM-6#1864]
every time i go to fight a dragon from F&I it gets stuck midair and everything crashes, i have a good enough computer so i dont understand what is going on

**Comment by radiomike** [comment]
Can you post a crashlog from when this happens?

**Comment by DAmNRelentless** [comment]
It's one thing to submit an issue on the GitHub repository for a crash but not providing logs is just resulting in the issue being closed.
If you want help with crashes, join the [Discord](https://discordapp.com/invite/rbSZNDQ) server instead.
