### ISSUE TITLE
Can I catch a level 5 wild dragon in 1.6.7?

### ISSUE THREAD

**Issue by Lcy123dada** [AllTheMods/ATM-6#1865]
Can I use Mob Imprisonment Tool to catch a level 5 wild dragon? I know a Youtuber used this to successfully capture a level 5 wild dragon. Why did I fail when I tried?

**Comment by thevortex** [comment]
The intention was originally not to have them farmable like that, the ability to capture them was removed

**Comment by JustBlankXD** [comment]
@thevortex can you please tell me how to change that?
Maybe in the configs
I am begging you :(
