### ISSUE TITLE
No dragons spawning anywhere? Or any structures at all for ice and fire?

### ISSUE THREAD

**Issue by WolfyPoe** [AllTheMods/ATM-6#1867]
My friend and I made our own server for this mod pack (ATM 1.16.5 (version 1.6.8 for the mod pack), and iceandfire-2.1.6-1.16.4), and looking closer into the files and online research, we found out that we couldn't find dragons unless we went into The Other. Well when we went in there was nothing, roamed all 4 cardinal directions for 10-20k m and nothing. Figured it might have been something to do with the mod pack so I went into a solo world and everything was fine.

**To Reproduce**
1. Download and make a server for ATM6 1.16.5 (using version 1.6.8 of mod pack)
2. Try finding dragons in said server.

**Additional context**
This may not be a bug, and be a simple edit to fix for the server, but I haven't found anyone else having this same issue where they actually don't spawn, and it's not just the dragons from the mod but almost every mob from that pack doesn't spawn and every single building from the pack doesn't spawn (except for the singing mermaids rock structure in the overworld).

**Comment by HawksAreNeat** [comment]
Dragons only spawn in the other place the teleport pad in the nether and click it
