### ISSUE TITLE
How do I get dragons to work?

### ISSUE THREAD

**Issue by WolfyPoe** [AllTheMods/ATM-6#1868]
Pack version 1.6.8 (1.16.5 minecraft)

My friend and I have a server running, everything (mostly) works, at least, what we need to work is working so far.

However

There are no dragons from the ice and fire mod. Now I know they are whitelisted/blacklisted to only be in The Other dimension, but after traveling over 10k in each cardinal direction and then some, I've seen nothing at all, yet in my solo world everything is okay and theres loads of them.

So question is, how do I fix this/change this???

**Comment by radiomike** [comment]
Is the server configured with the `default` world type?

**Comment by whatthedrunk** [comment]
Make sure you are on the newest update and reset your other dim just in case.
