### ISSUE TITLE
Defult, Bop, or Realistic world settings (1.6.10)

### ISSUE THREAD

**Issue by Dimaethoron276** [AllTheMods/ATM-6#1869]
Good Day,

If i use the "Realistic" world settings, will i encounter problems with ore generation, and will there be biomes missing from the "Biomes of Plenty" mod? Ive seen mixed posts about this on the internet and i have yet to come across any instructions from Modders, Wikis, or Developers as to which world settings to use.

I would greatly appreciate any feedback.

**Comment by radiomike** [comment]
For this pack you should use `default`. Using anything else will cause issues and leave you missing biomes and more.

**Comment by Dimaethoron276** [comment]
> 
> 
> For this pack you should use `default`. Using anything else will cause issues and leave you missing biomes and more.

Thank you for the quick response radiomike.
