### ISSUE TITLE
Crash when u jump over a pression tube and lost of world

### ISSUE THREAD

**Issue by kokoadict** [AllTheMods/ATM-6#1870]
When you try to jum over a pression tube from pneumatic craft, the game crashes and there is no way to enter again.

**Comment by radiomike** [comment]
Post your crashlog and someone may be able to help you.

**Comment by kokoadict** [comment]
[crash-2021-06-20_18.54.03-client.txt](https://github.com/AllTheMods/ATM-6/files/6683009/crash-2021-06-20_18.54.03-client.txt)

**Comment by radiomike** [comment]
Remove baritone - that's causing the issue.

**Comment by kokoadict** [comment]
Ty
