### ISSUE TITLE
Dispenser drops shears intead of using it

### ISSUE THREAD

**Issue by clgarciab** [AllTheMods/ATM-6#1871]
VERSION 1.16.10
**Describe the bug**
When using a dispenser in, for example, a wool farm, the shears are been dropped instead of shearing the sheep.

**To Reproduce**
1. Put a dispenser with a shears inside.
2. Activate the dispenser in front of a sheep
3. See error

**Comment by DAmNRelentless** [comment]
That's probably a tweak made by RandomPatches or something.
This is not an error.

ATM6 is a large modpack and there are more than enough other ways to achieve the same goal.

**Comment by Linguardium** [comment]
This should not be an issue with randompatches, however there may be an issue with Silent Gear shears as they dont seem to be compatible with dispensers https://github.com/SilentChaos512/Silent-Gear/issues/340
