### ISSUE TITLE
Nitro crystal essence have no use 

### ISSUE THREAD

**Issue by Th1med** [AllTheMods/ATM-6#1872]
Pack version: 1.6.10
curseforge launcher 
issue:
The nitro crystal (from powah) essence have no use
I expected to be a recipe using 8 essence and one nether star

**Comment by DAmNRelentless** [comment]
You aren't supposed to get the Nitro Crystal Essence.
It was hidden in JEI but the recipe has not been removed properly.

It's intended that is has no usage. That's fixed in the upcoming version of the pack.
