### ISSUE TITLE
LazierAE2 Circus Etcher useless cause kube js disable AE2 silicon

### ISSUE THREAD

**Issue by GordonHollow** [AllTheMods/ATM-6#1873]
latest ATM6 1.6.10

Circus Etcher frome LAzierAE2 can only use silicon from AE2, not from RefinedStorage, but it's craft disabled in this pack
Definitely kubejs problem, maybe need use ae2-silicon instead of RefinedStorage

**Comment by DAmNRelentless** [comment]
I don't know what you mean. LazierAE2 is using the Silicon tag for its recipes and therefor it also supports Silicon from Refined Storage.
I tested it and it works:
![](https://i.imgur.com/dHDPU85.png)

**Comment by GordonHollow** [comment]
Well, for me it doesn't have this tag and take only AE2 silicon that disabled in this modpack

**Comment by DAmNRelentless** [comment]
You are not playing 1.6.10 then.
The mod didn't use a Silicon tag in an earlier version but that's not the case for 1.6.10.

**Comment by GordonHollow** [comment]
> You are not playing 1.6.10 then.
> The mod didn't use a Silicon tag in an earlier version but that's not the case for 1.6.10.

I figured it out. It does work with silicon from RefinedStorage too

It only don't shown up in JEI correctly. Also JEI recipe doesn't show silicon tag in this recipe

So all works, but JEI recipe is broken

**Comment by DAmNRelentless** [comment]
Also works in JEI for me
![](https://i.imgur.com/IFgPb7S.png)

**Comment by GordonHollow** [comment]
Well for me it doesn't
But machine works fine, tested in creative, only JEI recipe kinda broken
No a big problem in that case

PS: checked version, it definitely latest 1.6.10

**Comment by DAmNRelentless** [comment]
That sounds like some version mismatch. If you are playing Singleplayer my guess is that the curseforge launcher didn't overwrite something properly (happens often because it's bad).
And if you are playing on a server, there is something not in sync between client and server.
