### ISSUE TITLE
AE2 Middle-click does not autocraft

### ISSUE THREAD

**Issue by lelodragneel** [AllTheMods/ATM-6#1874]
Server Version: 1.6.10
Client Version: 6-1.6.10

**Describe the bug**
AE2 middle-clicking an item in an ME Terminal does not bring up the autocrafting prompt. Occurs in both Singleplayer & Multiplayer.

**To Reproduce**
1. Open any terminal (ME Terminal, ME Crafting Terminal, ME Pattern Terminal, even a Wireless Terminal)
2. Middle-click on an item that's already set up for autocraft.
3. Notice that nothing happens.

**Comment by DAmNRelentless** [comment]
This is a mod conflict with Inventory Tweaks. Thanks for the report, it has been fixed in our dev version and will be released with the next pack update.
