### ISSUE TITLE
1.6.10 Valid Apiary Block

### ISSUE THREAD

**Issue by AggressivePear** [AllTheMods/ATM-6#1876]
**Describe the bug**
When attempting to validate an Apiary, the Mob Filter (Player) block is not being seen as valid.

**To Reproduce**
1. Make a Tier 1 apiary.
2. Replace any of the blocks with a mob filter (player) block.
3. The apiary will not work anymore.

**Screenshots**
https://imgur.com/a/FF7xyhR

**Additional context**
N/A, have not tried other Mob Filter Blocks

**Comment by starforcraft** [comment]
Use Etheral Glass

**Comment by AggressivePear** [comment]
Other mob filter blocks do not work as well, and they have the text saying they should. I want my named bee pet to be able to leave with me out of the apiary when I take him on a walk.
