### ISSUE TITLE
Netherite Bee - Missing Config Data/NEI/JEI Recipe ATM 6 V-1.16.10

### ISSUE THREAD

**Issue by hyflicker** [AllTheMods/ATM-6#1877]
**All The Mods 6 Version 1.16.10** 

After working toward the Wither Bee I looked into getting the netherite bee and JEI/NEI says it only breeds with it's self. So I looked up the config files to the server which have not been altered and has Spawn Data set to false and is missing the 2 breed parents. Below is the Netherite Default Bee Config. Location can be found All The Mods 6 1.6.10\config\resourcefulbees\bees\bred\bees_ingot\Netherite.json .

[https://pastebin.com/K5PVDkdC](url)

**Comment by radiomike** [comment]
That's because it uses mutation to give a spawn egg instead. Check JEI for more info.

**Comment by hyflicker** [comment]
@radiomike ahh I see now. Thank you.
