### ISSUE TITLE
Crash on Launch - Twitch Launcher

### ISSUE THREAD

**Issue by TADace** [AllTheMods/ATM-6#188]
Hello,

I am experiencing crashes on launch while using the Twitch launcher. My server is migrating to ATM3 from AT6. I had no issues launching and running ATM3. The cursed forge mod loader screen briefly pops up before disappearing and the game crashing. On crash I receive the following screen:

![image](https://user-images.githubusercontent.com/69564412/96529427-bcd6b680-124a-11eb-8127-bf303ce44221.png)

When I dug into the logs for ATM6, I found: "Failed to find Minecraft resource version 1.16.3-20200911.084530 at D:\Twitch Minecraft\Install\libraries\net\minecraftforge\forge\1.16.3-34.1.23\forge-1.16.3-34.1.23-client.jar"
I found similar log files for ATM4 and 5.

**Comment by whatthedrunk** [comment]
Your Twitch install is probably broken try MultiMC or GDLauncher. You can also try to delete that forge install and manually install forge into the directory you gave.

**Comment by TADace** [comment]
Update: I installed forge manually, and added a new install with Twitch's ATM6 folder as the file path. Worked.
