### ISSUE TITLE
ATM 6 - crash upon start

### ISSUE THREAD

**Issue by konvaa** [AllTheMods/ATM-6#1881]
Hey, I tried to install on laptop, where it at least was able to start, but not able to play due to low ram. So I installed it on desktop PC, where I have allocated almost 10GB to ram. But when I launch, it crashes. Tried latest version, one version older...
I pasted crash log.
https://pastebin.com/knA2AqJ3
Any ideas how to fix this?

**Comment by DAmNRelentless** [comment]
This is not a page where you should submit your crash reports.
If you want help with crashes, join the [Discord](https://discordapp.com/invite/rbSZNDQ) server instead.
