### ISSUE TITLE
Arc furnace diamond armor recycling

### ISSUE THREAD

**Issue by wrcooley** [AllTheMods/ATM-6#1884]
ATM6 1.6.10
The Immersive Engineering arc furnace recycles diamond armor into iron ingots instead of diamonds. This also makes some armors that use diamond armor as a crafting component (Crystallized obsidian, ratlantis, mystical agriculture armor) also incorrectly return iron ingots. 
![Capture1](https://user-images.githubusercontent.com/62617770/123154299-a82f6b80-d434-11eb-87f2-78aa39df2b94.PNG)
![Capture2](https://user-images.githubusercontent.com/62617770/123154311-ab2a5c00-d434-11eb-8dfb-e265d31ec634.PNG)

**Comment by ladylexxie** [comment]
Fixed in the next version of the pack.
