### ISSUE TITLE
Corail Tombstone v6.4.3 issue with enchantments

### ISSUE THREAD

**Issue by cdgamedev** [AllTheMods/ATM-6#1887]
Sorry if this is the wrong place or the team was already aware. Just wanted to bring light in case you weren't so the mod can be updated.

**Describe the bug**
A game-breaking crash when using the Tombstone enchantment "Blessing"

**To Reproduce**
1. Apply "Blessing" enchant to armour.
2. Get hit by Shulker bullet (not every bullet causes the crash)
3. Game crashes

**Screenshots**
https://youtu.be/92ydDBLqq3w

**Additional context**
Mod has been updated to v6.4.5 which fixes this bug.
https://www.curseforge.com/minecraft/mc-mods/corail-tombstone/issues/29

**Logs**
https://hastebin.com/wokazejiso.rb
https://hastebin.com/pobozakuro.properties
https://hastebin.com/kebiciqeso.properties

**Comment by DAmNRelentless** [comment]
The mod was already updated in our dev environment. The new version of the pack is already being tested and should be released within the next days.
