### ISSUE TITLE
Server updater always makes Avast Antivirus freak out

### ISSUE THREAD

**Issue by Sunconure11** [AllTheMods/ATM-6#1891]
I should've brought this up at some point, but the server installer/updater, when one tries to use it, causes Avast to see it as a virus. Is there anything you can do on your end to stop Avast from falsely flagging it?

**Comment by Linguardium** [comment]
https://www.avast.com/en-us/false-positive-file-form.php

**Comment by thevortex** [comment]
its a batch file running a well known, built-in command for downloading files in windows 10 'bitsadmin", not much we can do about that
