### ISSUE TITLE
Smeltery Controller is Uncraftable

### ISSUE THREAD

**Issue by ThatGuy1oo1** [AllTheMods/ATM-6#1893]
Pack version 1.16.11
The recipe for the smeltery controller requires Tinkers’ Construct version of molten copper and alltheore molten copper is not recognized in the recipe. The smeltery controller is craftable because of it.

1. Place a seared smelter above a seared tank filled with lava
2. Place a seared casting bin next to the seared tank and place a seared tap on the smelter above the seared casting bin
3. Fill the seared smelter with copper and put a seared heater into the seared casting bin
4. When you right-click, you won’t be able to cast the molten copper onto the seared heater. But if you remove it you can still cast a copper block which shows the recipe doesn’t work but the setup does.

![image](https://user-images.githubusercontent.com/25162600/123507276-87366880-d636-11eb-88fc-2be09183d16a.png)

**Comment by HammerV2658** [comment]
Having the Exact same issue,
![image](https://user-images.githubusercontent.com/86526309/123517357-d4244880-d6e3-11eb-8a3d-e693531621de.png)
 only after the lastest update was working fine prior to as i made one using the same one yesterday

**Comment by whatthedrunk** [comment]
Thanks we are trying to fix this but for now we added a new recipe
