### ISSUE TITLE
[1.6.11] Ice and fire overworld spawn prevention is too effective, leading to lost items

### ISSUE THREAD

**Issue by radiomike** [AllTheMods/ATM-6#1894]
**Describe the bug**
As well as preventing world spawns of ice and fire entities, the spawn prevention is also preventing spawning of tamed dragons, and other ice and fire entities. Attempting to place a dragon from a dragon horn, nothing happens and dragon stays in the horn. Also prevents the placement of dragon eggs - they actually vanish.

**To Reproduce**
Try placing a dragon from a horn, or place a dragon egg.

Dragon will remain in horn.
Egg will vanish into thin air.

**Comment by radiomike** [comment]
An additional concern would be someone updating to this version with some tamed ice and fire "pets" in world may find them disappearing.

**Comment by ButchMonkey** [comment]
Can confirm, also experiencing this. Lost 2 dragons and multiple eggs to this

**Comment by thevortex** [comment]
guess we got a bit overzealous with this. will be adjusted in next update(see the recent PR #1896  if you want to get your fix in now, this only needs to be done server-side
