### ISSUE TITLE
Crash on startup when using Java SE 16.0.1

### ISSUE THREAD

**Issue by Zorbatron** [AllTheMods/ATM-6#1895]
Using MultiMC and specifying the java version to be 16.0.1, the game will crash before the window pops up. I believe it's an issue with illegal accesses that are disallowed in 16.0.1 but were allowed in 11.0.11 and before. This may not be able to be fixed by the mod pack devs and is likely a single mods issue.

https://pastebin.com/64xTdqdy 
^For file paths, I have replaced my username for privacy reasons

**Comment by starforcraft** [comment]
You can use Java 16 for 1.17 but not for 1.16.5 or down.

**Comment by Zorbatron** [comment]
Huh, didn't know that. Thank you for responding!
