### ISSUE TITLE
Remove mod

### ISSUE THREAD

**Issue by benjiben55** [AllTheMods/ATM-6#19]
Hello again, sry for issues, but when i remove a mod i get an warning screen and the game dont save any changes.

To reproduce the issue...
remove a mod...
start the game...
and see the warning screen...
place some blocks...
disconnect and reconnect ...
nothing saved...

Please help me with this problem.

Thanks

benjiben

**Comment by whatthedrunk** [comment]
I would need to know more details. If you remove a mod make sure it's also removed from your server.

**Comment by benjiben55** [comment]
I play on a single player world "No Server"
