### ISSUE TITLE
[1.6.10] All Players on Server Crouch / Sneak When One Teleports

### ISSUE THREAD

**Issue by rekonnected** [AllTheMods/ATM-6#1901]
**Describe the bug**
On a server with pack version 1.16.10, any time a player uses one of the teleport functions (notably Waystones or the Mining Dimension Teleport Pad), all other players on the server at that time enter a crouched / sneak state, as if they are holding SHIFT. It does not seem to affect movement, but it lowers the player's viewpoint down as if they were sneaking.

**To Reproduce**
1. Start and join server with at least 2 players.
2. Use a Waystone or Teleport Pad to teleport to another location / dimension.

**Additional context**
This issue seems to be present going back a few versions. I haven't tested very far but I believe it was also present on 1.6.7.

**Logs**
Unfortunately no log entry is generated when this happens, client or server side. If there are addition debug options I can enable to generate more descriptive logs, please let me know.

**Comment by BovineShaman** [comment]
It was supposed to be fixed in 1.16.11, but also required the extra steps of this:

> If your camera is stuck in the "crouched" position after updating to 1.6.11:
>
>1. Download and install NBTExplorer from here: https://github.com/jaquadro/NBTExplorer/releases/download/v2.8.0-win/NBTExplorer-2.8.0.msi
>2. Open NBTExplorer, then find your level.dat in saves/<save name>/level.dat (or world/playerdata/<uuid>.dat file for servers) and drag it into the window. 
>3. Navigate to level.dat > Data > Player > ForgeCaps and find shrink:shrunk. Select it, click the red X in the toolbar to delete it.
>4. Ctrl + S or click the save icon in the toolbar to save your changes, then close NBTExplorer.
>
>You should now reset to default camera position when you open your world.

**Comment by rekonnected** [comment]
Should these steps be ran server-side or client-side? Having to instruct the users to do this could be... fun.

**Comment by BovineShaman** [comment]
So the crouch problem you are talking about is in 1.6.10, and is supposed to be fixed in 1.6.11.
If you update client and server, then go through those steps server-side, it should be fixed.

Newest version is 1.6.12

**Comment by rekonnected** [comment]
Ah, gotcha. I wasn't even aware 1.6.12 came out yet, it changed in the time I was gathering info for this issue. I'll run the update tonight and go through the steps you mentioned and report back. Thanks!

**Comment by aaryancanvas899** [comment]
I am facing the same problem, except I play on singleplayer. I recently updated from 1.16.10 to 1.16.12. After I logged into my world I started facing this problem. I am continuously stuck on the sneak viewpoint even if I sneak then let go of shift, the camera position does not change.

**Comment by aaryancanvas899** [comment]
> It was supposed to be fixed in 1.16.11, but also required the extra steps of this:
> 
> > If your camera is stuck in the "crouched" position after updating to 1.6.11:
> > 
> > 1. Download and install NBTExplorer from here: https://github.com/jaquadro/NBTExplorer/releases/download/v2.8.0-win/NBTExplorer-2.8.0.msi
> > 2. Open NBTExplorer, then find your level.dat in saves//level.dat (or world/playerdata/.dat file for servers) and drag it into the window.
> > 3. Navigate to level.dat > Data > Player > ForgeCaps and find shrink:shrunk. Select it, click the red X in the toolbar to delete it.
> > 4. Ctrl + S or click the save icon in the toolbar to save your changes, then close NBTExplorer.
> > 
> > You should now reset to default camera position when you open your world.

This fixed it for me.
