### ISSUE TITLE
1.6.11 Tinker's construct cant cast a Smeltery Controller

### ISSUE THREAD

**Issue by ghettogeckos** [AllTheMods/ATM-6#1902]
In 1.6.11 ATM6 I can't drain the copper into the basin in order to craft the smeltery controller. I stumbled upon this issue on my server and then I tried to see if it would work in a single player world and it didn't work there either.

**Comment by SenojLuap** [comment]
I'm getting the same result on the same version of the modpack

**Comment by whatthedrunk** [comment]
we have a hotfix right now adding a simple recipe while we look over a proper fix thanks

**Comment by whatthedrunk** [comment]
You can now cast it like normal with the new update.
