### ISSUE TITLE
1.6.12 - Error on launch, soggyguns for older version of Forge

### ISSUE THREAD

**Issue by localzuk** [AllTheMods/ATM-6#1903]
Having updated a server to 1.6.12, when you open the client you see the error "File soggyguns - 9.0.jar is for an older version of forge and cannot be loaded".

The pack works fine after this, and connects to the 1.6.12 server just fine also.

This is using the CurseForge launcher to download the pack/update from 1.6.9.

**Comment by whatthedrunk** [comment]
Thanks.. That is a weird one. I made a new export and it added its self again but I will push a fix out soon.
