### ISSUE TITLE
[1.6.12] soggyguns mod has been included by mistake - it's a 1.7.x mod

### ISSUE THREAD

**Issue by radiomike** [AllTheMods/ATM-6#1904]
**Describe the bug**
As in the title, downloads for 1.6.12 pull the soggyguns mod, which is a mod for 1.7.x. Either it's been included by mistake, or there's a typo and the script is pulling the wrong file.

**To Reproduce**
Download 1.6.12, get `soggyguns - 9.0.jar` in mods folder

**Additional context**
Doesn't seem to cause any harm, is ignored on server but throws a skippable error on clients to say that it can't be loaded.

**Comment by radiomike** [comment]
Also `CustomStartingGear-1.16.4-2.0.2.1-universal.jar` seems to have been included without any config.

**Comment by whatthedrunk** [comment]
Thanks.. That is a weird one. I made a new export and it added its self again but I will push a fix out soon. CustomStartingGear was added to remove a book people were spawning with and replacing it with the tome.
