### ISSUE TITLE
Allthemodium completely absent in the world. I believe Vibranium is too.

### ISSUE THREAD

**Issue by liveloveputin** [AllTheMods/ATM-6#1905]
1.6.5, updated to 1.6.7, updated to 1.6.11, updated to current.
As described, Allthemodium is not present in my worlds.
I don't know anything about coding, I know this is a coding website so I thought I would preface my post. I downloaded the pack properly as far as I am aware. It isn't present in any map in my first download of the pack. I even made a creative map and used the xray potion and went around underground and couldn't see it anywhere. It spoils the entire pack as pretty much everything in the endgame requires it and even a bunch of stuff before then. I downloaded new clients and made new worlds and it still doesn't work.

I'm running it on a PC if that makes a difference.

Sorry if this is a crap entry I don't understand all the technicalities. It's a shame because this has kind of taken the fun out of it.

All the best,
William

**Comment by LWmods** [comment]
are you looking in the right biome? in the overworld allthemodium ore only spawns in ocean biomes. vibranium is in the nether in warped forests and crimson forests. unobtainium is in the end in highland biomes.

**Comment by whatthedrunk** [comment]
Just loaded up a fresh world and found some in a deep ocean. If you are having a hard time try trading gold to piglins in the nether then make a allthemodium sight potion.
