### ISSUE TITLE
Resourceful Bees Centrifuge not working

### ISSUE THREAD

**Issue by jcniceguy18** [AllTheMods/ATM-6#1906]
Regular Honeycomb can be processed but Unique honeycombs only produced honey.

![image](https://user-images.githubusercontent.com/45948656/123546678-39357800-d790-11eb-9063-e9af3e84beb2.png)
![image](https://user-images.githubusercontent.com/45948656/123546694-47839400-d790-11eb-8c53-993dde98f559.png)
![image](https://user-images.githubusercontent.com/45948656/123546708-50746580-d790-11eb-9203-5d43cf48ccb9.png)
![image](https://user-images.githubusercontent.com/45948656/123546716-5407ec80-d790-11eb-8636-4e354f361eac.png)

**Comment by whatthedrunk** [comment]
Just tested and it's working fine. Those Uranium Combs are only a 2% chance so it may take a few
