### ISSUE TITLE
When Loading I get a mod warning. 

### ISSUE THREAD

**Issue by Illoradannan** [AllTheMods/ATM-6#1909]
I am running the latest version of All the Mods 6. (1.6.12) When I load I get this 
![image](https://user-images.githubusercontent.com/86568568/123553859-1e88e200-d743-11eb-93c6-9c906636cb2b.png)

I told it just to go to the Main Menu....but then my game locked up and my server disconnected me. I'm not sure the two are related.....When I went to reconnect it wouldn't do so.

**Comment by starforcraft** [comment]
Update to 1.6.13
