### ISSUE TITLE
Beheading Enchantment dropping unreasonable amounts of skulls from withers

### ISSUE THREAD

**Issue by LordGrimmauld** [AllTheMods/ATM-6#191]
**Describe the bug**
With Apotheosis in place, a sword can be enchanted with beheading of levels greater than 3 (Cyclics original cap). I now have a sword with beheading level 7. Killing a wither with that sword results in 7 wither skulls being dropped ([See the code that causes this behaviour](https://github.com/Lothrazar/Cyclic/blob/797c7892e8ffdf654ae0fafb11999388182fb7de/src/main/java/com/lothrazar/cyclic/enchant/EnchantBeheading.java#L108))
This means i can get a nether star and 4 skulls from only 4 soul sand. This is absolutely broken.

**To Reproduce**
1. Get a high level apotheosis enchanting station
2. Enchant a sword with beheading (ideally a high enchantability sword like allthemoddium alloy and similar) on a high level
3. Sommon and kill a wither
4. See more skulls dropping than needed to summon a new one

**Expected behavior**
I'd expect 3 skulls at most, as intended by cyclic. But ideal would be a cap of the beheading enchant from apotheosis enchanting.

**Screenshots**
![image](https://user-images.githubusercontent.com/49513131/96603763-9f5e2700-12f4-11eb-8c86-cbe87e0e1be3.png)

**Comment by WhitePhant0m** [comment]
I don't feel like this is an issue since you basically get a skull each time you kill a wither skeleton anyways and they are everywhere in the nether.

**Comment by WhitePhant0m** [comment]
Ideal solution to me would to disable that part of the code that makes the wither drop skulls based on the lvl, but since I can't do that, I'll leave it be
