### ISSUE TITLE
[1.6.7] Teleport Pad Duplication Glitch

### ISSUE THREAD

**Issue by VexisArcanum** [AllTheMods/ATM-6#1910]
In version 1.6.7 (haven't tested in later versions), you can duplicate a Teleport Pad by moving it after teleporting. Only tested this in the Nether, unsure if it can be done in the Mining Dimension. Replication steps are as follows:

1. Place teleport pad in the nether.
2. Teleport to Piglin Homeworld
3. Break teleport pad and move it anywhere else
4. Teleport back to the Nether and there will be a new teleport pad.
5. Teleport back to the Piglin Homeworld and there will be another teleport pad there as well.

This can be done indefinitely.

**Comment by radiomike** [comment]
It's a known issue. See https://github.com/AllTheMods/ATM-6/issues/445

**Comment by VexisArcanum** [comment]
> It's a known issue. See #445

Thank you. I swear I searched for it beforehand but it showed up nothing.
