### ISSUE TITLE
Players can't stay connected

### ISSUE THREAD

**Issue by Illoradannan** [AllTheMods/ATM-6#1911]
Running version 1.6.13 through G-Portal now. 

I updated to 1.6.13 today. Players couldn't connect or stay connected with my old world....so I restored a backup and tried again. Same thing. So I put a new world up. And we're now getting the same thing. We get that the connection was forcibly closed by the host.  The console tells me that it took too long for the player to connect. I know that each player is giving the modpack 10g of RAM to load....and run. So it's not that issue...and I've maxed out the allowed ticks in G-Portal.

**Comment by Illoradannan** [comment]
![image](https://user-images.githubusercontent.com/86568568/123559824-12614c80-d764-11eb-84d2-f93b23c00acd.png)

**Comment by Illoradannan** [comment]
Upon further digging...players started experiencing this issue at the 1.6.11 update.

**Comment by cdgamedev** [comment]
I've also had this issue with my server too. Only seems to happen to me though and not other users.

**Comment by Illoradannan** [comment]
Do you host your own server on your PC or have it externally hosted? Because I moved mine to a different Server Machine and players have been just fine for the whole night. But it could be just because it's all new data and such (We started fresh ugh!)

**Comment by cdgamedev** [comment]
> Do you host your own server on your PC or have it externally hosted? Because I moved mine to a different Server Machine and players have been just fine for the whole night. But it could be just because it's all new data and such (We started fresh ugh!)

I self host my server. Would prefer not to start fresh.

**Comment by radiomike** [comment]
Try increasing the `login_timeout_ticks = 2400` and `keep_alive_timeout_seconds = 120` in `randompatches.toml`
