### ISSUE TITLE
ATM v1.6.13 (and previous version) - World Gen unavailable with default settings

### ISSUE THREAD

**Issue by Beaukarl123** [AllTheMods/ATM-6#1913]
ATM v1.6.13, and the previous versions aren't letting worldgen spawn at all in my singleplayer world. I tried in multiple types of worlds (superflat, biomes o plenty, etc..) and its a nogo; Even past the XYZ safezone.
However, I can get silver bars through chests and I can spawn mobs via their eggs in the creative crafting.

I deleted the entire modpack and restarted it for version 1.6.12 and hoped 1.6.13 would fix it, retried, nothing.
looked for a solution online, can't find a concrete one.

thanks for reading!

**Comment by Beaukarl123** [comment]
p.s, this is for singleplayer, not server if it helps

**Comment by thevortex** [comment]
what worldgen are you talking about?  we suggest using 'default' worldtype and just leave it at that

**Comment by Beaukarl123** [comment]
sorry I might not have used the right term; I meant like, no dragon caves, no hydra lairs, no cyclops cave. I haven't seen a single I&F enemy naturally spawn, any of them; no ores, nothing; the mod is enabled and everything. I wasn't sure if I had to unlock them through the beastiary book but it didn't work.

**Comment by thevortex** [comment]
correct, when we say we 'fixed ice and fire spawning in the overworld' that means we stopped it from happening, this pack has never located the mobs from that mod in the overworld, to allow for newer players to more easily access the rest of the pack. the ice and fire mobs spawn in 'the other' dimension, use a teleport pad from @allthemodium in the nether to go there.

**Comment by Beaukarl123** [comment]
Thanks vortex; everything's good here .... btw, "the other" dimension is mostly badland, is that intended? it'll take forever to find what I need but it works either way

**Comment by thevortex** [comment]
there are a lot of badland biomes yes, the ones the dragons inhabit are a bit more rare but they do appear, best to search in grids rather than straight lines
