### ISSUE TITLE
1024k storage part only accepts Extra Storage 256k parts , which were removed

### ISSUE THREAD

**Issue by Nubidubi23** [AllTheMods/ATM-6#1916]
On version 1.6.11 , trying to autocraft an infinite storage disk prompts the crafter to say that i'm missing 256k Extra Storage parts , even though i already have a pattern for it and the 1024k part recipe says it accepts any items with the tag refinedstorage:parts/items/256k.

**Comment by BovineShaman** [comment]
Redo all of your storage patterns and try again

**Comment by pahb18** [comment]
As I've stated [here](https://github.com/AllTheMods/ATM-6/issues/1858#issuecomment-869190063), I think the issue is the mixed of Extra Storage and Extra Disks items when creating recipes.

**Comment by Nubidubi23** [comment]
> Redo all of your storage patterns and try again

Weirdly enough that worked , even though the recipe didn't change. Thanks

**Comment by BovineShaman** [comment]
Yea, the patterns may've been wrong at some step, or maybe the RS system was just confused.
Glad to here it works
