### ISSUE TITLE
[1.16.5] Seer's sigil interface overlaps with JEI when looking at blood altar

### ISSUE THREAD

**Issue by Beaukarl123** [AllTheMods/ATM-6#1917]
I have a Seer's Sigil from Blood magic and I wanted to see more info about my altar but cant because both interfaces interfere with each other (superpose). I was wondering if this was a bug or if it fixable via settings.

**To Reproduce**
1. Mak a Tier 3 Blood magic blood altar
2. Make a Seer's Sigil and hold it in your toolbar
3. hold the Seer's Sigil and look at the blood altar
4. See overlapping.

![bug](https://user-images.githubusercontent.com/86579104/123655946-74ba5b80-d7fd-11eb-93f5-4ef4a1659058.png)

**Comment by whatthedrunk** [comment]
Type /topcfg to move it around.
