### ISSUE TITLE
Creative Constructor Duping

### ISSUE THREAD

**Issue by Skogisplayer** [AllTheMods/ATM-6#1918]
1.6.13
Gamebreaking duping bug.

**To Reproduce**
Place Creative Destructor (@Cabletiers)
Connect it to a Refined storage network
Place block infront
Gives 10x the output (i dirt = 10 dirt, 1 diamond ore = 10 diamonds (even more with fortune upgrade)

**Comment by starforcraft** [comment]
Fixed in next Version.
