### ISSUE TITLE
[1.6.10/1.6.13] Quark vertical slabs in Apiary (Resourceful bees)

### ISSUE THREAD

**Issue by Dherse** [AllTheMods/ATM-6#1919]
**Version of the pack**: 1.6.10 (also present in 1.6.13)

**Describe the bug**
Quark vertical slabs are not supported in apiaries from resourceful bees.
This is due to a typo in a javascript script located at: `kubejs\server_scripts\RBees\valid_apiary.js`

**To Reproduce**
1. Go into a world
2. Build an apariry multiblock using (some) vertical slabs
3. Notice that it is invalid

**Screenshots**
Here is a screenshot of the typo inside of the code:
![verticle_slab](https://user-images.githubusercontent.com/9665250/123701682-74a07700-d862-11eb-825e-1a22824f669f.PNG)

Here is a screenshot of the in-game "error":
![apiary](https://user-images.githubusercontent.com/9665250/123701885-b7624f00-d862-11eb-92ef-fcb3e5cd98e1.png)

**Additional context**
After modifying the JS file it works as intended.

**Logs**
Not relevant

**Comment by whatthedrunk** [comment]
Thanks fixed in dev and will be in 1.6.14
