### ISSUE TITLE
server - class loading errors

### ISSUE THREAD

**Issue by ColinMoulds** [AllTheMods/ATM-6#192]
**Describe the bug**

Building Gadgets | /mods/buildinggadgets-3.7.1.jar | 20th Oct 2020 17:39 PM | Caused by: net.minecraftforge.fml.ModLoadingException: Ding has class loading errors

Ding | /mods/Ding-1.16.3-1.2.0.jar | 20th Oct 2020 17:40 PM | Caused by: net.minecraftforge.fml.ModLoadingException: Ding has class loading errors

**To Reproduce**
1. install server files
2. start server
3. watch the console.

**Expected behavior**
no issues

**Comment by ViRb3** [comment]
You're running the client-side mod Ding on your server, it fails to load `net/minecraft/client/audio/ISound`, and so the game crashes. Make sure you're using the server modpack from Curseforge as it has the mod (among others) removed.

**Comment by WhitePhant0m** [comment]
Running a client mod on server as stated above. Remove it, and it *should* work.
