### ISSUE TITLE
Applied Energistics 2 | Fluid Level Emitter

### ISSUE THREAD

**Issue by SimplyVeebs** [AllTheMods/ATM-6#1929]
**Describe the bug**
The Fluid level emitter will not allow me to place a fluid in it's GUI to specifically filter. The GUI will not even highlight (like how the regular level emitter does).

**To Reproduce**
1. Create a ME System with Fluid compatibility
2. Place a Fluid Level Emitter with (or without, really) fluid within your ME system
3. Try to place a fluid to dictate the redstone signal from the emitter in the GUI
4. Be sad.

**Screenshots**
This is the regular level emitter, notice how the leftmost GUI is highlighted
![image](https://user-images.githubusercontent.com/86689925/123869166-a535ee80-d8fe-11eb-92b3-78d2704af98b.png)

This is the fluid level emitter, the GUI will not highlight when hovered over and will not accept any fluid (via bucket, or fluid itself from JEI menu) into its slot.
![image](https://user-images.githubusercontent.com/86689925/123869265-c39bea00-d8fe-11eb-969c-0705200ed2a9.png)

**Additional context**

**Comment by ladylexxie** [comment]
The UI seems to be broken for AE2. You can add fluids, but the actual slot is in the top left of the UI. I'm assuming AE2 forgot to move the slot to the actual graphic slot.

![image](https://user-images.githubusercontent.com/30494658/125014909-6cb4b400-e066-11eb-8d4b-c95d6dc00a0d.png)
