### ISSUE TITLE
Constant sound dhst sound

### ISSUE THREAD

**Issue by Nicon4454** [AllTheMods/ATM-6#193]
**Describe the bug**

**To Reproduce**
1. Go to 'just load in game and stand there'
2. Click on 'N/A'
3. Scroll down to 'N/A'
4. See error N/A

**Expected behavior**

**Screenshots**

**Additional context**
if you want to see what i am talking about i have a very short video up on [youtube](https://youtu.be/8E-PlvC6Te8)

**Comment by bruddlee** [comment]
Any news on this yet? I'm having the same issue

**Comment by bruddlee** [comment]
Hey I figured out what the issue is coming from. It's the sound muffler. Go to inventory and disable sound muffler and the annoying sound stops. It's a temporary fix until they get the mod fixed for whatever the bug is.

**Comment by Colton-Slayden** [comment]
if you are on 1.1.5 update to 1.1.6 or newer it is fixed. Youtube video has no sound so cant be sure what you are talking about

**Comment by Nicon4454** [comment]
sorry for the late reply i tried disabling the muffler but it had no bearing on the sound. sorry about youtube having no sound not sure why will have to look at obs settings

i am on 1.1.5 so i will look for an update
