### ISSUE TITLE
server update

### ISSUE THREAD

**Issue by jus2fruit** [AllTheMods/ATM-6#1933]
hi, i want to update my atm 6 server in my pc but i don't know how. Can someone help me ?

**Comment by radiomike** [comment]
Have a look in the wiki at <https://github.com/AllTheMods/ATM-6/wiki/Pack-Upgrade-FAQ>.

Also, I'd recommend joining the discord if you need further assistance.

**Comment by jus2fruit** [comment]
ok thanks
