### ISSUE TITLE
Null Pointer Error in the Nether?

### ISSUE THREAD

**Issue by Bormac** [AllTheMods/ATM-6#1934]
**Describe the bug**
Having an issue in a hosted multiplayer server with a friend of mine.
Whenever they go exploring in the nether they will, shortly, always get an error, that boots them from the server, and then it will not let them back on the server until I mess with their data file to pull them out of the nether. It reports an "internal server error" in the chatlog.
But it doesn't generate any error logs, on my computer, theirs, or on the server so trying to figure out what it is is difficult at best.
From what I can see it looks like some sound that the game is trying to play for them doesn't exist and the game freaks out? But that's just my guess. I don't actually know.

**To Reproduce**
1. Friend enters nether
2. Walks around a bit
3. Forced disconnect
4. unable to reconnect

**Screenshots**
https://cdn.discordapp.com/attachments/134493088218349578/859918803001540648/Crash.png is around when it happened, I also have the log for it
https://cdn.discordapp.com/attachments/134493088218349578/859919015698235422/Friends_End.png is what my friend saw on their end.

**Additional context**
The error thus far has only happened to my friend, not to anyone else on the server. Though my nether explorations have been limited

**Logs**
https://pastebin.com/FQjDd1Ah
that is the point that the error occured, the file was too big for pastebin itself can send a larger log if needed.

**Comment by radiomike** [comment]
Looks like it's caused by an astral sorcery perk trying to grow a byg block/plant.

Probably the `spreading growth perk`. They could either reset the perks, or use a `sealing sigil` to disable it temporarily. To rescue your friend from the nether you can use `cu unstuck <player>`

**Comment by Bormac** [comment]
> Looks like it's caused by an astral sorcery perk trying to grow a byg block/plant.
> 
> Probably the `spreading growth perk`. They could either reset the perks, or use a `sealing sigil` to disable it temporarily. To rescue your friend from the nether you can use `cu unstuck <player>`

Thank you, we are going to try that! I appreciate it.
