### ISSUE TITLE
rat whistle causes a crash

### ISSUE THREAD

**Issue by Ultimate8wworrior** [AllTheMods/ATM-6#1937]
pack version: 6-1.6.14

**To Reproduce**
1. make a cheese staff
2. right-click on a tamed rat to bind the staff to said rat
3. right-click the ground to open the menu and choose 'set home point for rat to (block ur looking at)'
4. use the rat whistle 
5. boom. it crashes

**Additional context**
im doing this in a my claimed chunks and on a server (just saying that cause maybe its the reason but idk)

this crash will not occur if the rat is set to 'stay here' (I have the set to wander and everytime i do this the game crash)

note that my game crashes and not the server 

everytime this crash happens the home point for the rats is gone and i have to set it again
**Logs**
https://pastebin.com/EuSfnn5s

**Comment by ladylexxie** [comment]
Fixed in the next version.
