### ISSUE TITLE
incompatible fml modded server

### ISSUE THREAD

**Issue by 8bitminerman** [AllTheMods/ATM-6#1938]
Either the server pack or the regular pack has different mods.

**Comment by pahb18** [comment]
I'm having the same issue, except I can login to my server just fine anyway.

**Comment by radiomike** [comment]
The red x and error are from a recent change on forge. It doesn't necessarily mean that there is a problem between client and server. You should try connecting anyway. If that fails then there's an issue and I'd recommend you try joining the atm6 discord for help with that.

**Comment by zh4ng** [comment]
Same Issue here. 
The import from the powah Energizing Orb does not work for me. Neither with Refined Storage Importer nor with a hopper under the orb. I thought the error was due to the alleged incompatibility between server and client.
