### ISSUE TITLE
MiningGadget's blank upgrade is no longer craftable in 1.1.6

### ISSUE THREAD

**Issue by alaa13212** [AllTheMods/ATM-6#194]
**Describe the bug**
Cannot craft blank upgrade from MiningGadgets. It broke in my world after I updated to 1.1.6 today. I tried in new creative worlds and it seems like it doesn't work there as well.

**To Reproduce**
Open any crafting grid and try crafting the blank upgrade recipe. The recipe doesn't even show in JEI
![Screenshot from my creative world](https://user-images.githubusercontent.com/1864639/96626712-85ced680-1318-11eb-9fd1-f8457442cf99.png)
 _Screenshot from my creative world_

**Expected behavior**
I should be able to craft it.

**Comment by AmandaCameron** [comment]
I beleieve this affects everything rebound in ct_recipies.js,  because [this line](https://github.com/AllTheMods/ATM-6/blob/master/kubejs/server_scripts/ct_recipes.js#L65) is missing the prefixed `e.`

Loading up my server & client with that fixed to test and confirm myself.

**Comment by thevortex** [comment]
https://github.com/AllTheMods/ATM-6/pull/195 corrects this , Thanks, and good eye!

**Comment by WhitePhant0m** [comment]
:c
will fix now:tm:
