### ISSUE TITLE
Mason Bee (Resourceful Bees) has no flower/breeding item

### ISSUE THREAD

**Issue by Ryckes** [AllTheMods/ATM-6#1940]
Running:
ATM6 1.6.13
Minecraft 1.6.15
Forge 36.1.32

I noticed that the Mason Bee didn't have a flower in JEI, and no feed item for breeding. I tried using several different blocks (including clay and bricks) and it would never produce honeycombs. After some looking around, I tried modifying [this line](https://github.com/AllTheMods/ATM-6/blob/308dc4eef4ffd3453853ca3e1373e5015cfed27d/config/resourcefulbees/bees/natural/bees_misc/Mason.json#L2) and the breeding feed item, setting them to "minecraft:clay", and that seemed to do the trick. I haven't properly tested this or even used the Mason Bee itself after this change, just checked that in JEI it appears correct.

**Comment by radiomike** [comment]
Just tested this in 1.6.14 on server and single player. Clay appears in JEI in both single and multiplayer.

Try doing a fresh install of the pack and see if that fixes it. You can use https://github.com/AllTheMods/ATM-6/wiki/Pack-Upgrade-FAQ as a guide for copying your world to the new instance.

**Comment by Ryckes** [comment]
After updating the pack in CurseForge, I see that my change to the .json file is reverted and the bee still looks correct in JEI. I think it might have been caused by disabling Immersive Engineering (gave me some trouble with the shaders). Sorry for the trouble!
