### ISSUE TITLE
Wireless Charging Not Working ATM6 1.6.14

### ISSUE THREAD

**Issue by AzraelNova** [AllTheMods/ATM-6#1941]
**Describe the bug**
I have my flux controller set to wirelessly charge my hotbar, main hand, offhand and armor yet it is charging none of them. The network is adequately powered, so that's not the issue.

**To Reproduce**
1. Set up a flux network.
2. Place a flux controller.
3. Enable wireless charging.

**Screenshots**
![Minecraft 1 16 5 - Multiplayer (3rd-party Server) 6_30_2021 7_42_06 PM](https://user-images.githubusercontent.com/86833170/124266646-3c6c9300-db05-11eb-810e-783b9beac13d.png)
![Minecraft 1 16 5 - Multiplayer (3rd-party Server) 6_30_2021 6_54_32 PM](https://user-images.githubusercontent.com/86833170/124266655-40001a00-db05-11eb-9dea-c80ab94516c2.png)
Not sure if those screenshots are working.

**Additional context**

**Comment by pokermanx** [comment]
If you are on the server: check if you are a member of another flux network that is unloaded/unpowered. Happened to me

**Comment by AzraelNova** [comment]
> If you are on the server: check if you are a member of another flux network that is unloaded/unpowered. Happened to me

Thank you so much! I deleted and then readded another network that I'm a part of (the one sending power to my induction matrix) and it was fixed. I have no idea why that happens though lol.
