### ISSUE TITLE
Stan Bee and Obsidian Bee mutations broken

### ISSUE THREAD

**Issue by Ryckes** [AllTheMods/ATM-6#1942]
Running:
ATM6 1.16.13
Forge 36.1.31
Minecraft 1.16.5

Stan Bee and Obsidian Bee won't mutate their honeycomb blocks, making their respective spawn eggs unobtainable. In JEI they won't appear as having any mutation recipes. I believe this is caused by some typos in the following lines:
- [Stan Bee](https://github.com/AllTheMods/ATM-6/blob/308dc4eef4ffd3453853ca3e1373e5015cfed27d/config/resourcefulbees/bees/natural/bees_misc/Stan.json#L33-L39) -- all three IDs seem to be misspelled. I got it to work using, respectively: resourcefulbees:stan_honeycomb_block, resourcefulbees:stan_honeycomb and resourcefulbees:stan_bee_spawn_egg. That's how they appear in en_us.json.
- [Obsidian Bee](https://github.com/AllTheMods/ATM-6/blob/308dc4eef4ffd3453853ca3e1373e5015cfed27d/config/resourcefulbees/bees/bred/bees_misc/Obsidian.json#L33) just has a typo.

Great pack by the way, I'm having a lot of fun with it. Thank you for your work!

**Comment by radiomike** [comment]
Yes, can confirm that is the case. Should be fixed in next version.
