### ISSUE TITLE
[1.6.14] Ars nouveau drygmy mobs spawning in compact machine dimension

### ISSUE THREAD

**Issue by radiomike** [AllTheMods/ATM-6#1945]
**Describe the bug**
Drygmy mobs from ars nouveau are spawning in the compact machine dimension. Potentially causing tps issues.

**To Reproduce**

1. Have a compact machine, make sure it's chunkloaded.
2. Wait.
3. Drygmy mobs spawn over time. Inside and outside of the machine

**Comment by radiomike** [comment]
Also applies to the mining dimension.

**Comment by ladylexxie** [comment]
Fixed in the next version.
