### ISSUE TITLE
Twilight portal opens but doesn't work

### ISSUE THREAD

**Issue by Telejean** [AllTheMods/ATM-6#1946]
All the mods 6 1.16.4
For context I am on a multiplayer server, just me and a friend and we decided to make a portal to The Twilight Forest and succeded ( the portal blocks appeared) but we can't get trough it.

**Comment by LWmods** [comment]
im having the same issue did you find a fix?

**Comment by thevortex** [comment]
biomesoplenty worldtypes will frequently cause issues with modded
dimensions, if it's BOP worldtype, that could be the problem
