### ISSUE TITLE
ATM-6 1.6.14 server files wont launch on linux

### ISSUE THREAD

**Issue by Shadewarrior27** [AllTheMods/ATM-6#1949]
**Describe the bug*
I am currently trying to set up an ATM-6 server on my computer running lubuntu. When I try to run the server from my terminal all it will return is  "" startserver.sh: 2: set: Illegal option -o pipefail"" I made sure the serverstart.sh file was exucutable and when I ran it without the terminal it downloaded all the needed files but I could not see what else it did. After that I created the eula file and tried running the server again through the terminal but the same thing happened as before.  I have ran other servers on this machine with no problem.  Thank you in advance for any help you might be able to give me.

**To Reproduce**
I'm not sure if this can be reproduced on other Lubuntu machines but for mine
1. Go to my terminal and navigate to my servers folder.
2. run sh serverstart.sh

**Screenshots**
![serverscreen](https://user-images.githubusercontent.com/70041760/124391275-6bc20200-dcb5-11eb-8ae4-4b83efcf3c7e.jpg)

**Comment by radiomike** [comment]
Try running it as `bash serverstart.sh` instead.

**Comment by Shadewarrior27** [comment]
That worked thank you! I'll be sure to keep that in mind for the future.
