### ISSUE TITLE
'Valid apiary block' tooltip is annoying

### ISSUE THREAD

**Issue by LemonShaped** [AllTheMods/ATM-6#1950]
ATM6 1.6.14

Loads of blocks always say `Valid Apiary Block` in their tooltip.
This is kind of annoying especially since this applies to so many common blocks.

This is pretty unnecessary because you can just search for them in jei with $valid_apiary

![image](https://user-images.githubusercontent.com/64607380/123858479-7a0dc800-d91b-11eb-8af5-b41b24b9bfca.png)

(just remove this line)
https://github.com/AllTheMods/ATM-6/blob/master/kubejs/client_scripts/client_scripts.js#L371

**Comment by Pdiddy973** [comment]
Was added intentionally, feel free to remove it yourself if you don't like it.

**Comment by LemonShaped** [comment]
Ok, I understand you're not going to change it, but
I know it was intentional but it is just unnecessary, what's the point of it?
I would change it myself but that usually gets reset when updating, and surely it's not just me
