### ISSUE TITLE
Environmental Energy Solar Array doesn't produce power in Mining Dimension or The End

### ISSUE THREAD

**Issue by Thund3rBolt** [AllTheMods/ATM-6#1957]
I setup the Tier 6 Solar Array from Environmental Energy in the Overworld and started generating just shy of 1M fe/t, but would stop during the night. I set it up in the Mining Dimension, the same exact way, and it didn't produce anything at all. I tried in The End as well and got the same result. Just to check, I set it back up in the Overworld and it started working again.

**Comment by ladylexxie** [comment]
This is due to how the ET solar panels detect sunlight, nothing we can do about it, it should be reported to the mod author.
