### ISSUE TITLE
quarry deletes AlltheModium ores

### ISSUE THREAD

**Issue by TheBlacksmith1232** [AllTheMods/ATM-6#196]
**Describe the bug**
when using a quarry from quarry plus it will mine Allthemodium, vibranium and unobtainium ores but wont pick them up they are being outright deleted

**To Reproduce**
1. setup quarry as you wound normally
2. place some of the offending ore in its path and watch as it mines them
3. check chest to find a lack of the corresponding ores 

**Expected behavior**
i expected it to either pick up the ore, or ignore it and and leave it

**additional comment**
also i dont see anyway to power it other then the creative power source the mod comes with could we get the power converter mod to fix that

**Comment by davethwave** [comment]
Quarries aren't meant to pick them up. They made it so you have to mine them from hand. They also didn't have them ignore the ore since it would be too easy to find them that way.

**Comment by TheBlacksmith1232** [comment]
then why make them using unobtanium if you dont want it to pick it up

**Comment by TheBlacksmith1232** [comment]
plus there are other devices that dont need onobtainium but will mine everyblock except for the allthemoduim ores letting you mine them yourself making the quarry not just useless but a liabillity

**Comment by thevortex** [comment]
this would be a bug to submit to quarry plus mod author, his quarries do not check if they are able to get the drop before they remove the block, he needs to check the event bus and make sure nothing is requesting that in fact it does not want that block removed

**Comment by TheBlacksmith1232** [comment]
Latest version of the Quarry plus mod has been updated and the bug should be fixed also the psi mod needs to be updated to the latest as you can't access the spell programmer otherwise(It crashes you)

**Comment by whatthedrunk** [comment]
This will be fixed in 1.1.7 out later today.
