### ISSUE TITLE
void miner crashing game

### ISSUE THREAD

**Issue by panckat** [AllTheMods/ATM-6#1960]
**Describe the bug**
I set up a void miner in the end and now every time I load the save the game crashes instantly
ATM 6 version 1.6.14

**To Reproduce**
1. Set up a void miner in the end
2. Leave and rejoin

**Screenshots**
![crash](https://user-images.githubusercontent.com/87096364/124827181-95d02a00-df2a-11eb-9c7b-07aaecb50d19.png)

**Additional context**
Tested with and without Optifine 

**Logs**
https://pastebin.com/7s70FiZR

**Comment by radiomike** [comment]
They do that at the moment unfortunately. But, if you use nbtexplorer <https://github.com/jaquadro/NBTExplorer/releases/download/v2.8.0-win/NBTExplorer-2.8.0.msi> you can relocate your player and get your game working again. 
First do a backup. Then, as it's single player, you need to open the `level.dat` for your world (in windows, it's best to drag it into nbtexplorer to make sure it's the right one) then look for your player and adjust its x, y, z data - the spawn position for it should be listed so use those numbers. Also change the player dimension to `minecraft:overworld`.
That should let you restart the world, you can then either travel to the void miner and break it, or `open to lan` and use crash utils to remove it. There's a gui you can use - defaults to `ctrl-u` - but you'll need to be in the same dimension as the miner.

**Comment by sechim** [comment]
the same thing happens to me
