### ISSUE TITLE
Install Server Files

### ISSUE THREAD

**Issue by bobo6** [AllTheMods/ATM-6#1961]
**Describe the bug**

I wanted to install the server in the latest version

**To Reproduce**
1. Download Server Files for 1.6.14
2. Open the Rar File
3. Drag and drop Files in a new Folder
4. Start the startserver.bat

**Screenshots**
![image](https://user-images.githubusercontent.com/18252433/124909250-857f8400-dfea-11eb-9377-34d9547a8a83.png)

**Comment by radiomike** [comment]
Looks like it may not be able to download the file. Check your Internet connection and make sure that any firewall or antivirus is not blocking it.

If that doesn't help, you can try downloading the file directly using the link inside the `startserver.bat` file.
