### ISSUE TITLE
[1.6.14] Placing a mythic botany runeholder at z=0 crashes the client

### ISSUE THREAD

**Issue by radiomike** [AllTheMods/ATM-6#1964]
**Describe the bug**
Place a mythic botany runeholder at y=0 and the client crashes with a divide by zero error.

**To Reproduce**
1. place runeholder at z=0
2.Crash

**Logs**
See <https://github.com/noeppi-noeppi/MythicBotany/issues/69>

**Comment by ladylexxie** [comment]
Fixed [here](https://github.com/noeppi-noeppi/MythicBotany/commit/032b51b52a67e3959185335134a370c2c7e7c86b) for the next release.
