### ISSUE TITLE
/leaderboard time_played incorrect All the Mods 6-1.6.10

### ISSUE THREAD

**Issue by cyrusnth** [AllTheMods/ATM-6#1966]
After migrated the server to another computer the leaderboard not showing correctly, the username were all showed to be unknown. Is there any way to fix it?

**Comment by starforcraft** [comment]
Why aren't you just using the Minecraft statistics instead of the leaderboard?

**Comment by whatthedrunk** [comment]
Try again on 1.7.2 I believe forge fixed some leadership board stuff.
