### ISSUE TITLE
UI/Filter button bug

### ISSUE THREAD

**Issue by YumiComiusito** [AllTheMods/ATM-6#1967]
I explained it in the image but I am having an issue with AE2 and whatever mod makes the filter button appear and the customizability of JEI is there anyway to fix this or you gotta contact whatever mod author?
https://imgur.com/a/sJbjSwi

**Comment by cdgamedev** [comment]
Its to do with the Quark mod. You can change the config to hide the screen - for some reason, it isn't in this pack by default.

If you change the config file `config/quark-common.toml` you can add the ignored screens (line 21).

I have this as;
`"Ignored Screens" = ["blusunrize.immersiveengineering.client.gui.CraftingTableScreen", "com.tfar.craftingstation.client.CraftingStationScreen", "com.refinedmods.refinedstorage.screen.grid.GridScreen", "appeng.client.gui.implementations.CraftingTermScreen", "appeng.client.gui.implementations.PatternTermScreen", "com.blakebr0.extendedcrafting.client.screen.EliteTableScreen", "com.blakebr0.extendedcrafting.client.screen.EliteAutoTableScreen", "com.blakebr0.extendedcrafting.client.screen.UltimateTableScreen", "com.blakebr0.extendedcrafting.client.screen.UltimateAutoTableScreen", "me.desht.modularrouters.client.gui.filter.GuiFilterScreen", "com.resourcefulbees.resourcefulbees.client.gui.screen.CentrifugeScreen", "com.resourcefulbees.resourcefulbees.client.gui.screen.MechanicalCentrifugeScreen", "com.resourcefulbees.resourcefulbees.client.gui.screen.CentrifugeMultiblockScreen", "com.refinedmods.refinedstorage.screen.FilterScreen", "appeng.client.gui.me.items.CraftingTermScreen", "appeng.client.gui.me.items.PatternTermScreen"]`

Which also ignores the immersive engineering crafting screen.

Have also created #1992 which will make this default for all users.
