### ISSUE TITLE
OneProbe/EnderTanks Interaction Crashing Client

### ISSUE THREAD

**Issue by bigbluu722** [AllTheMods/ATM-6#1969]
ATM6 Version 1.6.14

**Describe the bug**
Looking at an EnderTank with lava inside will crash your game.

**To Reproduce**
1. Setup RangedPumps Pump in the nether pumping lava, mekanism basic mechanical pipe pulling the lava out and fluxpoint to power it.
2. Privatize an EnderTank (shift click with a diamond) and dye all 3 color codes red
3. Pump lava into the tank via basic mechanical pipe.
4.  Look at endertank and game will crash.

**Screenshots**
N/A

**Additional context**
This seems to not happen with my 3 blue colorcoded private endertank with water inside for whatever reason, though, the oneprobe tooltip doesn't show up for this one when looked at.

**Logs**
Crash Log:
[https://gist.github.com/3ed519bde0aec684c52fc077b191a4da](https://gist.github.com/3ed519bde0aec684c52fc077b191a4da)

Other maybe relevant info from latest log:
[https://gist.github.com/3b404b980092fabc8694920f952621ac](https://gist.github.com/3b404b980092fabc8694920f952621ac)

**Comment by crysallis** [comment]
I experienced an issue using Create to pipe lava into an ender tank and was setup with an importer into our Refined storage system... and whenever the ender tank was actually connected to the Refined storage system ... it would hang and we couldn't take inventory out of the system

**Comment by ladylexxie** [comment]
This is a known issue by the mod devs and should be fixed in a future update.
