### ISSUE TITLE
Game Crashes when attempting set Bigger Reactors Reactor Access Port to export mode

### ISSUE THREAD

**Issue by TheBoopleBeep** [AllTheMods/ATM-6#197]
[crash-2020-10-20_20.48.26-client.txt](https://github.com/AllTheMods/ATM-6/files/5412738/crash-2020-10-20_20.48.26-client.txt)

**Comment by TheBoopleBeep** [comment]
To reproduce, simply attempt to change the mode of the Reactor Access Port.

**Comment by WhitePhant0m** [comment]
Update the pack. That should fix it

**Comment by RogueLogix** [comment]
fixed with BiR 0.1.7 in ATM 6.1.1.6b
