### ISSUE TITLE
server crash after upgrade from 1.6.11 to 1.6.14

### ISSUE THREAD

**Issue by eternaldragonborn** [AllTheMods/ATM-6#1970]
I upgrade my server from version 1.6.11 to 1.6.14 with Upgrade FAQ in the wiki, and it's all normal when starting, but whenever my friend or I try to connect to the server, it crash.
Here is the crash log. What's wrong with it and how to fix it.
https://gist.github.com/eternaldragonborn/4ed12923031c6e5bf0c4dc23c2eaf338

**Comment by ladylexxie** [comment]
Late response, but is this still happening in the current version?
