### ISSUE TITLE
[1.6.12, 1.6.14, and probably more] AE2 Storage Bus stops functioning on a Thermal Series Vacuumulator with more than a single item

### ISSUE THREAD

**Issue by Steampunk-Wizard** [AllTheMods/ATM-6#1973]
**Describe the bug**
If a Storage Bus from AE2 is attached to a Vacuumulator from Thermal Series, the Storage Bus fails to provide the items within the Vacuumulator if there is a stack size larger than 1

**Screenshots**
![2021-07-10_23 19 56](https://user-images.githubusercontent.com/39739925/125182087-13b95d00-e1d9-11eb-8338-350bc6f2615d.png)

**To Reproduce**
1. Create the simple setup from the screenshot, or similar.
2. Ensure the exporter is correctly filtered to the test item.
3. Drop a single test item (Cobblestone), and allow the Vacuumulator to pick it up.
4. The Storage Bus will recognize the item within the Vacuumulator, and correctly exports it into the ME system. 
**( This is the expected behavior )**
5. Drop multiple test items in a stack of 2 or larger, so the Vacuumulator picks up the entire stack at once.
6. The Storage Bus will now fail to recognize the items, and the test items will be stuck within the Vacuumulator.

**Additional context**
I tested this in both 1.6.12, and the latest 1.6.14, and the behavior was the same.
This appears to be an isolated bug only involving Thermal Series and Applied Energistics 2, as the Storage Bus seems to work on any other storage block. 

**Player Workaround**
Simply piping items from the Vacuumulator into a chest with Pipez/Mekanism is a viable workaround; The Storage Bus works as expected with stacked items in a chest.

**Comment by DAmNRelentless** [comment]
This block is not meant to be a storage block. It just picks up stuff from the nearby area.
You should just import everything from it into your system and not use it as storage.
That's not the purpose of the Storage Bus.

And if you really want to do that, you need to submit it as an issue for the Applied Energistics 2 guys as this is not something we can fix. But I guess they will tell you the same. That's not something the Storage Bus is made for.
