### ISSUE TITLE
TerraSteel Essence has no recipe to make TerraSteel Ingots

### ISSUE THREAD

**Issue by Sn0wShepherd** [AllTheMods/ATM-6#1974]
Using Mystical Agriculture, Terrasteel Essence seeds may now be planted and grown, but there is no recipe to use essences for making ingots or anything else for that matter.

Also, it would be wonderful to have the little robots from mana and artifice harvest and smoke bee hives!

**Comment by BovineShaman** [comment]
What version are you on, how/when did you get the seeds?
In the current version the seeds are supposed to be unobtainable, and so is the essence, and the relevant recipes shouldn't appear in JEI.
