### ISSUE TITLE
[1.6.14] NPE Ticking entity with Ankh of Pray over Zombie Villager

### ISSUE THREAD

**Issue by leagris** [AllTheMods/ATM-6#1976]
Mod-pack version: All the Mods 6-1.6.14

**Describe the bug**

Using a Corail Tombstone's Ankh of Pray to heal a Zombie Villager into a normal Villager, causes a Null Pointer Exception Ticking Entity 100% of the time.

**To Reproduce**
1. Get a Corail Tombstone Ankh of Pray
2. Find a Zombie Villager
3. Right-click on Zombie Villager to heal it back into a normal Villager
4. After the animation; it Crash with this:
[crash-2021-07-12_00.05.51-server.txt](https://github.com/AllTheMods/ATM-6/files/6797888/crash-2021-07-12_00.05.51-server.txt)

**Comment by ladylexxie** [comment]
If it happens again, you can go to `forge-server.toml` and set `removeErroringEntities = true`.
