### ISSUE TITLE
Ender Dragon Egg not being dropped for killing after first time

### ISSUE THREAD

**Issue by tbalthaza** [AllTheMods/ATM-6#198]
**Describe the bug**
After killing dragon for the first time, where the dragon egg was normally placed on top of the portal, reviving it over and over is not dropping any eggs.

**To Reproduce**
1. Go to The End
2. Use end Crystals to revive Ender Dragon
3. Kill Ender Dragon for second, third, etc, times
4. No dragon egg dropped neither placed on top of Portal.

**Expected behavior**
Normal dragon egg drop

**Additional context**
It's occurring in the simple server. Not tested in singleplayer.

**Comment by GrimmDZ** [comment]
Im pretty sure the egg only drops the first time its killed.

**Comment by WhitePhant0m** [comment]
Vanilla behavior.
