### ISSUE TITLE
ftbchunks map not loading mapped chunk after relogging.

### ISSUE THREAD

**Issue by lukej65** [AllTheMods/ATM-6#1983]
Pack Version 1.6.13 
ftbchunks map is not loading already mapped chunks after relogging.

**To Reproduce**
travel out far in the world my base coords are x:16000+ z:-75000+ 
exit the world and rejoin.

**Screenshots**
Before logging out.
https://ibb.co/VHvCng7

After relogging.
https://ibb.co/kSgbqc0

even after waiting 10 minutes the chunks still wont load unless i move near each of the chunks again.

**Logs**
i dont think i have any error logs feel free to comment if you need any though.

**Comment by ladylexxie** [comment]
This is usually fixed by giving it some time to load, in case it doesnt load after a long time, you should report an issue [here](https://github.com/FTBTeam/FTB-Chunks/issues/new/choose)
