### ISSUE TITLE
All the Mods 6 Version 1.6.14 Cable Tiers Dupe Bug

### ISSUE THREAD

**Issue by ScoutMaester** [AllTheMods/ATM-6#1984]
**The "cable tiers" mod introduces: "Creative Constructor/Destructors". These items are meant to operate instantly when paired with refined storage systems and they do, however when paired with each other they have unintended behavior resulting in an infinite supply of any item placeable in the world that can be acted upon by the destructor.**

**To Reproduce**
1. Place a Block in the world(unnecessary but aids in setup) This block can be almost anything...
2. On on face place a "Creative Constructor" so as it is facing the block placed in step one.
3. Open the interface for the "Creative Constructor" and input a copy of the block you wish to duplicate.
4. On any other face of the block, place a "Creative Destructor".
5. When both the "constructor" and "Destructor" are hooked up to an active "Refined storage" setup, the block placed in step 1 will be broken and the constructor will immediately place the predetermined block in its place as long as there is at least 1 stored in the system.
6. The result after this will be a frame tearing amount of particles and the constructor no longer consuming the block to place it. 
7. Each time the destructor breaks a block however, it is put into the system, resulting in a net gain of 1 block per break...
8. This happens hundreds of times a second

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/36943170/125374720-32406500-e34d-11eb-9c2c-f826353e224d.png)
![Untitled](https://user-images.githubusercontent.com/36943170/125374753-471cf880-e34d-11eb-8190-bfc52e428245.png)

**Comment by starforcraft** [comment]
Fixed in next Cable Tiers Update.
