### ISSUE TITLE
Crash On Startup

### ISSUE THREAD

**Issue by WGINC** [AllTheMods/ATM-6#1985]
ATM 6 1.6.14

Crashes on startup

**To Reproduce**
1.open ATM 6 through curse forge client
2.wait a few seconds for some of it to load
3.crash
**Additional context**
I am on a MacBook Pro 2020 with an M1 chip.

**Screenshots**
<img width="1440" alt="Screen Shot 2021-07-13 at 3 03 17 PM" src="https://user-images.githubusercontent.com/77513369/125510454-211cbc0c-3923-4ba8-88f3-6c1d8ebe89b3.png">
<img width="1440" alt="Screen Shot 2021-07-13 at 3 03 31 PM" src="https://user-images.githubusercontent.com/77513369/125510478-e9a798e1-cf46-4ebb-bf8b-e8f8edbdc2e5.png">

**Logs**
https://hastebin.com/eciqedosip.properties

**Comment by cdgamedev** [comment]
On googling the error, I found [this](https://forums.minecraftforge.net/topic/94803-javalangillegalstateexception-glfw-error-before-init-0x10008cocoa-failed-to-find-service-port-for-display/).

Have you tried adding `-Dfml.earlyprogresswindow=false` to your args?

**Comment by WGINC** [comment]
Welp,
<img width="1440" alt="Screen Shot 2021-07-14 at 1 17 05 PM" src="https://user-images.githubusercontent.com/77513369/125665502-149e837d-2339-46db-9817-d84362e8aff6.png">
I have looked around on the web some more and it seems to be a core problem with how Apple silicon/Rosetta handles translation of the LWJGL libs (a graphics program that forge uses). which is to say, it doesn't. see https://github.com/MinecraftForge/MinecraftForge/issues/7558.

**Comment by Pdiddy973** [comment]
looking at your screen shot you have ~3Gb of memory allocated, you will need at least 8-10 to run ATM6, and make sure you use a good launcher like GDLauncher

**Comment by WGINC** [comment]
<img width="1440" alt="Screen Shot 2021-07-20 at 1 48 23 PM" src="https://user-images.githubusercontent.com/77513369/126371659-aa15ea39-1a28-4a72-a71b-5493125bba43.png">
hmmm
