### ISSUE TITLE
Industrial Foregoing Plant Gatherer not working at all

### ISSUE THREAD

**Issue by ptrxyz** [AllTheMods/ATM-6#1986]
**Describe the bug**
Mod pack version: 1.6.14 (latest fom curseforge)
Industrial Foregoing Plant Gatherer does not harvest crops. (see https://imgur.com/a/CIswhh3)

1. Create a new single player world
2. Place Plant gatherer and supply with power
3. Plant a vanilla wheat seed in front and bone meal it 
4. See that nothing happens.

**Screenshots**
https://imgur.com/a/CIswhh3

**Additional context**
This happens in claimed and non-claimed chunks.

**Comment by tekkitan** [comment]
It is harvesting my crops just fine, also on 1.6.14.

**Comment by BovineShaman** [comment]
Maybe there needs to be water nearby?

**Comment by tekkitan** [comment]
Water shouldn't matter, it is only a harvester. It just detects fully grown crop and harvests it.

**Comment by SerenityFire** [comment]
I had the same problem also with the cyclic harvester. On my server I found out that if you have the area chunk loaded it will not harvest the blocks. I deactivated the chunk loding in this area and then it works.

I play without OP on server 1.6.14
I also had this "bug" back on FTB Revelation, I think it has to do something with FTB Chunk loader?

**Comment by Pdiddy973** [comment]
you need to add it as an ally in FTBChunks
