### ISSUE TITLE
weird client crash probably involves psi

### ISSUE THREAD

**Issue by davethwave** [AllTheMods/ATM-6#199]
Just tried logging into the server at version 1.16b and the game crashes every time it happens. I believe that it has something to do with the psi mod that was just added.
[crash-2020-10-21_10.50.01-client.txt](https://github.com/AllTheMods/ATM-6/files/5417853/crash-2020-10-21_10.50.01-client.txt)

**Comment by davethwave** [comment]
Thinking a bit, but I believe the best way to fix it is just to update psi, though I would wait until it's at version 87 rather than updating to 86. Think version 87 is the one that fixes this particular crash.

**Comment by whatthedrunk** [comment]
This should be fixed in 1.1.7 out later today thannks.
