### ISSUE TITLE
[1.6.14] Startup Crash Due To Error Loading Mods

### ISSUE THREAD

**Issue by Thunder12345** [AllTheMods/ATM-6#1993]
Pack version: ATM6 1.6.14
**Describe the bug**
Pack crashes on startup due to errors when loading Reliquary and Sophisticated Backpacks.

**To Reproduce**
1. Install ATM6 1.6.14 on MultiMC from zip
2. Launch
3. Crashes during startup

**Screenshots**
![image](https://user-images.githubusercontent.com/5479091/125607804-ddecc2db-b3cb-452e-a35d-4ff37b9d37ca.png)

**Additional context**
Running on windows 10 20H2, using OpenJDK version jdk-8.0.282.8-openj9.

**Logs**
https://pastebin.com/4Qj9WHw5

**Comment by radiomike** [comment]
Don't use openj9, It's not compatible with forge for minecraft 1.13 and newer. You should use openjdk or oracle, Java 8 or java 11.
