### ISSUE TITLE
Lagging after 20 to 30 minutes

### ISSUE THREAD

**Issue by Rivalzey** [AllTheMods/ATM-6#1998]
Using the latest version of the modpack after half and hour the game starts to freeze and lag alot, about every 3 seconds. I normally get over 200 fps. How do I fix said issue

**Comment by radiomike** [comment]
Probably easiest to join the atm discord https://discordapp.com/invite/rbSZNDQ if you are able to.
However, you should look at how much ram you have assigned to the game (8gb recommended), which java version you have and the Java arguments you are using.

**Comment by Rivalzey** [comment]
> Probably easiest to join the atm discord https://discordapp.com/invite/rbSZNDQ if you are able to.
> However, you should look at how much ram you have assigned to the game (8gb recommended), which java version you have and the Java arguments you are using.

I'm using the default arguments 8 GB allocated java 8 / latest from the website

**Comment by radiomike** [comment]
Java 11 is recommended for this pack. And the recommended java arguments are:

    -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true

**Comment by Rivalzey** [comment]
Ok 2 things the JVM arguments don't save on the cursforge launcher and can you lini java 11?

**Comment by radiomike** [comment]
You could try a different launcher, GD launcher and multimc are both recommended.

Java link is https://adoptopenjdk.net/archive.html?variant=openjdk11&jvmVariant=hotspot 

You should choose the x64 JRE version for your operating system.

**Comment by Rivalzey** [comment]
Thanks
