### ISSUE TITLE
Internal Exception: java.lang.IllegalArgumentException: Unknow trait serializer silentgear:stellar

### ISSUE THREAD

**Issue by SaintJames-dev** [AllTheMods/ATM-6#1999]
Have an issue with a private server, just starting it. I can join client side and im locally hosting it but any other person cant without getting the above error.

Any thoughts on how to fix this?

error is: Internal Exception: java.lang.IllegalArgumentException: Unknown trait serialuizer silentgear:stellar

**Comment by radiomike** [comment]
This usually means that they have a different version of the pack to the server. Try getting them to to a fresh install of the pack.

**Comment by hyflicker** [comment]
@SaintJames-dev I can confirm a fresh install fixes the issue. I ran into the same issue and a fresh install of the server pack corrected the issue. Hope what @radiomike provided helped you like it did me.

**Comment by ladylexxie** [comment]
N/A in current version
