### ISSUE TITLE
Wont install.

### ISSUE THREAD

**Issue by EpicPandaGamer** [AllTheMods/ATM-6#2]
Basically on the twitch desktop app which is intergrated with curseforge i searched for ATM6 and it shows up once i press it it starts downloading then stops less than a second in it doesnt show up in my installed modpacks but in the instances folder it does show up like 6 times with only 1 file inside called .curseclient and the file type is curseclient

**Comment by realTIMematrix** [comment]
having the same issue, but this seems to be a twitch desktop app problem. same with other 1.16.1 modpacks. opened up a ticket at twitch...waiting for a resolution....

**Comment by whatthedrunk** [comment]
Right now you have to download it from the website and import the profile into Twitch until they fix it. You can also import into MultiMC or give GDLauncher a shot.

**Comment by EpicPandaGamer** [comment]
ok importing it works thx

**Comment by LaChimere** [comment]
I have downloaded the zip file of ATM 6, but I can't install it in twitch. Who knows how to manually install it?

**Comment by BerserkerWorM** [comment]
> I have downloaded the zip file of ATM 6, but I can't install it in twitch. Who knows how to manually install it?

use GDlauncher and not only will it download it for you but also install it.
