### ISSUE TITLE
QuestLog not working 

### ISSUE THREAD

**Issue by Cratios** [AllTheMods/ATM-6#2005]
All the Mods 6

Version: 1.7.0

Minecraft 1.16.5

Since the Update the QuestSystem does not work. You can not claim anything

**Comment by cdgamedev** [comment]
Happening to me too!

Nothing counts as being completed.

**Comment by radiomike** [comment]
All of the ftb mods have been updated and they aren't backwards compatible.

Try deleting the files in `[saves]/<world>/ftbquests`

**Comment by cdgamedev** [comment]
> All of the ftb mods have been updated and they aren't backwards compatible.
> 
> Try deleting the files in `[saves]/<world>/ftbquests`

This worked for me. Thanks Mike!

**Comment by radiomike** [comment]
No problem, it seems that they use the same file, but have moved to a different internal layout.
