### ISSUE TITLE
Crash Server 

### ISSUE THREAD

**Issue by sechim** [AllTheMods/ATM-6#2007]
227 / 5000
Resultados de tradução
When I activate the void ore miner tier 7 at the end it crashes my game, it only crashes when the beam of light that indicates that the miner has activated comes out, and I can't get in anymore when it loads the miner I have to go back to the save 

![image](https://user-images.githubusercontent.com/42104293/126016540-37ecccd8-d2fe-4049-b107-a874599df4db.png)

Using java 8
ATM 6-1.7.0 and 1.6.14
https://pastebin.com/7kkP4Esb

**Comment by radiomike** [comment]
This is a known issue with environmental tech. As it's single player, the best thing to do after the crash is to reset your player position to spawn using nbtexplorer.
