### ISSUE TITLE
Ice and Fire: Dragons not working

### ISSUE THREAD

**Issue by lhill123** [AllTheMods/ATM-6#2009]
Using All_the_Mods_6-1.6.14

The creatures from "Ice and Fire: Dragons" do not appear in worlds created with the current version of ATM6. Today I tried another modpack, Ice and fire modpack Sir_Pyromancer, which includes the same version of Ice and Fire: Dragons that is included in ATM6, iceandfire-2.1.8-1.16.5.jar. All of the creatures from Ice and Fire: Dragons were present in the world which I created with that modpack. I did a fresh download and installation of ATM6 a short while ago to make certain that I am working with the latest build and the creatures still were not present.

**Comment by Pdiddy973** [comment]
We're you looking in the overworld or in the other? We have all of the I&F mobs in the other.

**Comment by lhill123** [comment]
I was looking in the overworld in both modpacks. I'm not sure what you mean by other. 

I created 5 different worlds with ATM6 and after extensive searching in each I never located an I&F mob. In my fourth attempt I even made changes to the iceandfire-common.toml to greatly increase the spawn chance for dragons and several of the other mobs. The default values were restored when I re-installed using todays upload of ATM6 prior to creating the fifth world.

In the single world I created with the other modpack I easily located numerous fire dragons, a lightening dragon, 2 cyclops, several death worms, numerous dragon skeletons, 2 ghosts, 2 pixie villages, a gorgon, several hippocampuses, and lots of sea serpents.

**Comment by cdgamedev** [comment]
Ice & Fire (and most modded mobs) don't appear in the overworld, they appear in a separate dimension called "The Other" you can head there using the Teleport Pad in the Nether (right-click with a bare hand).

This is by design in the mod pack due to the difficulty of Ice & Fire mobs when you first start the game.

**Comment by lhill123** [comment]
Okay I'll have to figure that one out. In the past I've encountered said mobs on servers without doing anything special. I also didn't go to the nether with the other modpack which I tried today. Is that something which can be toggled?

**Comment by cdgamedev** [comment]
It's something that is unique to this modpack (and other ATM modpacks iirc) so on servers for other modpacks, you won't have to do "anything special". You can toggle this, I'm just not sure where myself.

**Comment by lhill123** [comment]
Okay, thank you very much for providing clarity on this issue.
