### ISSUE TITLE
FTB Chunks Issues on the official server2

### ISSUE THREAD

**Issue by DeathOfTime** [AllTheMods/ATM-6#201]
After one of the recent updates. can't remember if it was 1.1.5 or 1.1.6. I found that my force loaded chunk allotment had gone to 0. It was actually showing 9 of 0 force loaded. I unclaimed all the other chunks trying to fix it and now can't force load any chunks.

Also four of the fake players aren't working correctly for me. When I check allies it says waiting on them to accept my invite. Modular Routers, RFtools Builder, CarbonHUN, and Rafeal3110. I am not even sure two of those are valid fake players. Even though the show up as such. If I try to use a Modular Router in my claim to right click a botany pot it doesn't work. The rfTools builder also won't work in my claim.

**To Reproduce**
Not for sure how to reproduce this. I have read of someone else having a similar issue. They only mentioned it once in one of the ATM6 general channels though

**Expected behavior**
Should be able to ally with and use fake players in chunks I have claimed. Should have a allotment of chunks to forceload.

**Screenshots**
https://imgur.com/a/4j1RGZa
hope those help explain it a little.

**Additional context**
I was told to wait on a server admin. I have been waiting two days and never seen one on the server. I was told to try commands. I tried those and am not sure what they did, but they didn't fix the issue. I've reported the issue on FTBchunks github.

**Comment by whatthedrunk** [comment]
This was disabled to help with TPS issues.

**Comment by jmarakelian** [comment]
This is somewhat related, but started playing on a personal server hosted locally, and found that the allies button on FTB Chunks is missing, wondering what is needed to re-enable to selection of the allies tab for ftbchunks, still looking for where that setting was set. Want to be able to use my builder without issues with quarying
