### ISSUE TITLE
I am using BisectHosting to try and host a server for my friend and I yet the modlists don't match up.

### ISSUE THREAD

**Issue by miiiiiiiiiiiiiiiiiiiiiiiim** [AllTheMods/ATM-6#2010]
We're downloading the latest gamefiles via curseforge.

![image](https://user-images.githubusercontent.com/87551351/126017831-3e8a2d4a-c607-434d-8835-182f50a537ae.png)

Out of curiosity, I have tired ATM6 Sky also and I am having the same issues.
![image](https://user-images.githubusercontent.com/87551351/126018833-e70ecd4a-0015-4b97-b35f-2a3c90eb533e.png)

I keep getting these errors and it is preventing us playing, any ideas?

Thanks

**Comment by rotho98** [comment]
I am having the same issue, mine is self-hosted and setup using the Simple Server jar

**Comment by Pdiddy973** [comment]
This is likely a bad install for either the client or server, do a fresh install/profile and it should be fixed....if you use curse forged/overworld for the client try a better launcher like Gdlauncher. Curse forge is known to do bad updates

**Comment by miiiiiiiiiiiiiiiiiiiiiiiim** [comment]
> This is likely a bad install for either the client or server, do a fresh install/profile and it should be fixed....if you use curse forged/overworld for the client try a better launcher like Gdlauncher. Curse forge is known to do bad updates

Tried multiple installs on both the server and the game, no luck sadly. Will try GDLauncher and let you know, thanks for the advice.

**Comment by miiiiiiiiiiiiiiiiiiiiiiiim** [comment]
Downloaded GDLauncher and everything is working as it should! Thanks for the help @Pdiddy973 !
