### ISSUE TITLE
Void Miner multiblock building disabled?

### ISSUE THREAD

**Issue by tekkitan** [AllTheMods/ATM-6#2013]
Auto building the void miner has been disabled since 1.6.14ish. I dismantled it before the upgrade and haven't been able to build it since then as I can't really find a blueprint of the 1.16.5 version of the void miner tier 2. I saw there were some fixes for the void miner in the latest update. Is this disabled in just this modpack or did the mod creator disable it? I have been unable to build it since i cannot find a blueprint for it in the new version anywhere. Everywhere I find says to use the autobuild function lol

**Comment by radiomike** [comment]
The mod developer has disabled it. You can still use the building preview to see where the blocks need to go.

**Comment by tekkitan** [comment]
This is all I get from selecting the preview option
![javaw_M486YbvuF8](https://user-images.githubusercontent.com/6876750/126043800-e769554b-6060-4d78-a64f-56005c82ea0c.png)

**Comment by radiomike** [comment]
Try leaving the area so that it forces it to re-render. 
TPing a large distance away, or to another dimension and back again should make it visible again.
