### ISSUE TITLE
Friends GUI is missing

### ISSUE THREAD

**Issue by dandud100** [AllTheMods/ATM-6#2015]
I have updated to 1.7.1 and now the friends gui on the minimap is missing. Also my claimed chunks have been reset.
In /world/data/ftbchunks/ the configurations are still present.

**To Reproduce**
1. Go to the minimap
2. Search for the friends gui
3. See error

**Comment by radiomike** [comment]
This is because the ftb mods have been updated and they aren't backwards compatible. You will have to re-do your chunk claims.

**Comment by dandud100** [comment]
> This is because the ftb mods have been updated and they aren't backwards compatible. You will have to re-do your chunk claims.

Okay, I created a party and invited my friend, that works for now but it was so much easier with the ally GUI in the Map. Why got it removed? FTB is so shitty documented... I searched for hours for commands and all of them are outdated. I don't even find something about the party thing.

**Comment by dandud100** [comment]
It is not fixed, why closed?
