### ISSUE TITLE
Void miner not collecting Atm, Vibr, and Unob

### ISSUE THREAD

**Issue by Tannan1** [AllTheMods/ATM-6#2016]
Pack version 1.7.1

New release notes state that the void miner will now collect from the Allthemodium mod but I've tried all memory types with interdimensional modifier and it still doesn't. Was wondering if there is something else needed that I need to add into the configs.
Also I was testing with Tier 8

**Comment by radiomike** [comment]
Try putting an appropriately coloured lens in the miner for the ore you want.

**Comment by radiomike** [comment]
Actually, having double checked, it looks like there's an issue with the datapack that does this. The ores are only generating at specific miner tiers, rather than tier X and up.

**Comment by Pdiddy973** [comment]
should be fixed in the newest version of Allthemodium, you can manually update the mod, or wait for a pack update
