### ISSUE TITLE
[1.7.1] ATM ores only generate for specific ET miner tiers.

### ISSUE THREAD

**Issue by radiomike** [AllTheMods/ATM-6#2017]
**Describe the bug**
ATM ores only get generated for specific envionmental tech miner tiers. So will generate for X-tier and not X-tier and up.

Seems to be caused by datapack in allthemodium mod.

For example for allthemodium, the datapack has 

````
"tiers": [3],
````
It should read 
````
"tiers": [3,4,5,6,7,8],

**Comment by thevortex** [comment]
Oof thanks Mike, will get this fixed up this afternoon when I get home from
work

**Comment by radiomike** [comment]
No worries, tested it here and my T8 miner has all 3 ores back.

**Comment by whatthedrunk** [comment]
Fixed in 1.7.2 thanks.
