### ISSUE TITLE
Crashing while in water / looking at water

### ISSUE THREAD

**Issue by Argah** [AllTheMods/ATM-6#202]
I crash everytime im in water, might be something chunk specific, might be a mod causing it.
From looking at the crashlog it seems to mention alot of "fluid" and it also mentions "theoneprobe"
https://pastebin.com/JzmR9ywC

**Comment by DeathOfTime** [comment]
I had this problem when I turned on liquid view on the one probe. There is a keybind for it. not sure that is your problem. Might try it though

**Comment by Argah** [comment]
So removing TheOneProbe seemed to fix it. Is there a way to disable the liquid view from the config? Because im currently stuck in this endless >Get into world >crash cycle

**Comment by Argah** [comment]
FIXED IT! Thank you @DeathOfTime
Solution:
Go to your ATM6 folder
Find the folder "configs" and open it
Find the config file for TheOneProbe called "theoneprobe_client.toml"
Go to line 70 and find "showLiquids = true" change this the "true" statement to "false"
Save the file.
Fixed
