### ISSUE TITLE
Mr. Crayfish Furniture Mod recipe conflict with AbsentbyDesign1.6.13

### ISSUE THREAD

**Issue by PARAcain** [AllTheMods/ATM-6#2024]
Version 1.6.13
There are recipe conflicts between Mr.Crayfish's Furniture Mod and AbsentbyDesign's fence crafting recipes, namely, the birch fences.

1. Go to crafting table
2. Craft the normal (not stripped) fences from Mrcrayfish's Furniture Mod
3. Creates the fences from AbsentbyDesign instead.
4. Resulting in being unable to make mailboxes from MrCrayfish's Mod :(

**Comment by ladylexxie** [comment]
Crafting the fences in a vanilla crafting table enables the button above the output to select the desired output: https://i.imgur.com/WNfzFb2.png
