### ISSUE TITLE
Lag Spikes and Freezes 

### ISSUE THREAD

**Issue by Cratios** [AllTheMods/ATM-6#2025]
Hi. How does Spark Profile Mod work? And what can i do against LagSpikes and Freezes?
I Play Version 1.7.1 on a Server. The Server has 25gb and i Play with 11gb on launcher. 

Thx

**Comment by radiomike** [comment]
For Spark, they have some good documentation to look through on their website <https://spark.lucko.me/>

As for the rest, you may find it easier to join the discord <https://discordapp.com/invite/rbSZNDQ>
