### ISSUE TITLE
Modded liquids extremely bugged/not functioning at all

### ISSUE THREAD

**Issue by uyghti** [AllTheMods/ATM-6#2026]
**Pack Version**
1.6.14

**Describe the bug**
All modded liquids have no collision/physics and you are able to walk right through all of them, even the liquids that should apply negative effects.

**To Reproduce**
1. Place any modded liquid and try to move through it, nothing happens

**Screenshots**
https://i.imgur.com/oIHRGf6.png
These liquids are from Tinker's Construct and do not flow at all.

**Additional context**
Vanilla liquids remain unaffected

**Comment by BovineShaman** [comment]
Tinker's Liquids not flowing seems to be a Forge issue, based off of [SlimeKnights/TinkersConstruct/#4295](https://github.com/SlimeKnights/TinkersConstruct/issues/4295), the liquids not working right seems to be the same

**Comment by uyghti** [comment]
Ah okay that explains it, thank you.
