### ISSUE TITLE
Cant make Tinkers parts with AllTheOres

### ISSUE THREAD

**Issue by zombiebush** [AllTheMods/ATM-6#2027]
Pack version 1.7.1, Forge version 36.1.32, AllTheOres version 1.3.4, TCconstruct version 1.16.5-3.1.0.231
Cant make tool/weapon parts with ores from AllTheOres mod.  I can make ingots with the ingot cast. Minecraft ores work fine. Ive tried the melter and making a full smeltery, i have not tried the foundry.
 Make melter/smeltery and casting table. take a part cast (tool binding, pickaxe head ext) put ore or ingot from AllTheOres (i tried copper and silver) and right click faucet.

**Comment by thevortex** [comment]
update alltheores to 1.3.5 (pack update coming soon)

**Comment by zombiebush** [comment]
sweet. thank you.

**Comment by whatthedrunk** [comment]
Fixed in 1.7.2 thanks.
