### ISSUE TITLE
Certain FTBchunks permissions wont work in FTBranks config {ATM1.7.1}

### ISSUE THREAD

**Issue by KamiAso** [AllTheMods/ATM-6#2028]
FTBchunks permissions like "ftbchunks.max_force_loaded" used to work in my server on 1.6.8. Since I updated to 1.7.1 the config file changed from json to snbt and Im aware of that so I have changed to format correspondingly too.

The problem still exist even the format is correct. The "ftbchunks.max_force_loaded" still remains the same within the FTBchunks config file but not the number in FTBranks I assigned to.

Also, the number of "ftbchunks.max_force_loaded" seems to be not changing even I use the command in FTBchunks e.g. /ftbchunks admin extra_force_load_chunks. In 1.6.8 it used to change immediately and show on the bottom left corner of the map.

here is part of the config file of FTBranks:
![Screenshot 2021-07-19 143334](https://user-images.githubusercontent.com/25843512/126113490-355d18c9-7a76-4195-bc64-b183701c4b13.jpg)

**Comment by radiomike** [comment]
Looks like ftb have released a new version of ftbchunks, which may resolve most of this. 

> Also, the number of "ftbchunks.max_force_loaded" seems to be not changing even I use the command in FTBchunks e.g. /ftbchunks admin extra_force_load_chunks. In 1.6.8 it used to change immediately and show on the bottom left corner of the map.

It doesn't show that it's updated, but does seem to work behind the scenes and display will update on a restart.

**Comment by KamiAso** [comment]
> Looks like ftb have released a new version of ftbchunks, which may resolve most of this.
> 
> > Also, the number of "ftbchunks.max_force_loaded" seems to be not changing even I use the command in FTBchunks e.g. /ftbchunks admin extra_force_load_chunks. In 1.6.8 it used to change immediately and show on the bottom left corner of the map.
> 
> It doesn't show that it's updated, but does seem to work behind the scenes and display will update on a restart.

Yes youre right it dose refresh somehow when I restart the game but if youre not youre gonna stuck at the current number of max chunks which is pretty painful as you already know ATM6 takes forever to load
