### ISSUE TITLE
Crafter on Mekanism machine doesn't work if it is initially not rotated towards the machine

### ISSUE THREAD

**Issue by mtbrenner** [AllTheMods/ATM-6#203]
**Describe the bug**
Refined Storage Crafter doesn't work with Mekanism machine

**To Reproduce**
1. Place Mekanism machine
2. Place Crafter above machine and make sure it is not yet aligned downwards
3. Rotate crafter with wrench until it points downward
4. Crafter doesn't recognize the machine (label in UI still shows "Crafter", autocrafting fails with "No machine found"

**Expected behavior**
label in UI shows machine name, autocrafting works. You can avoid the issue if you initially place the crafter so that it points downward it is recognized and shows the machine name.

**Additional context**
Observed on Official ATM6 Server
Also see my report here: https://github.com/refinedmods/refinedstorage/issues/2717

**Comment by jeremiahwinsley** [comment]
Fixed in 1.3.9.
