### ISSUE TITLE
Sorry if this is unrelated, but why does my fps is at a fixed 60 fps using your modpack but when using a modpack with 200+ mods I get constant lag spike every 3 second

### ISSUE THREAD

**Issue by DNephilim** [AllTheMods/ATM-6#2032]
ATM version (1.6.14)

I am playing Valhesia III modpack but it is lagging alot. How can your modpack run so well even with 100 more mods?

**Comment by TheLittleCube** [comment]
Allocate more system ram. Personally I run 8Gigs dedicated to MC across all versions/modpacks.
Depending on what you're launching the modpack with; you will need to change your launcher settings.

**Comment by Tripp-Sautner** [comment]
In F3 if you see the ram usage percentage reach 100% (This is located in the top right) then freeze it means your going over your allocated ram and the system freezes to clean up that ram. If it happens very frequently you need to up your ram until it doesnt happen.

**Comment by whatthedrunk** [comment]
Never played that pack but it can be many things. Ram, mod selection and optimisation.
