### ISSUE TITLE
[1.7.1] Instant and permanent server crash when right clicking Moon Detector from Cyclic

### ISSUE THREAD

**Issue by Etzix** [AllTheMods/ATM-6#2034]
1.7.1
**Describe the bug**
Right clicking the block "Moon Detector" from Cyclic crashes the server instantly and permanently.

**To Reproduce**
1. Right click the block "Moon detector"
2. Crash

**Logs**
Initial crash: https://pastebin.com/ZEP4a1aR
crash loop: https://pastebin.com/UcmgJDBQ

**Comment by ladylexxie** [comment]
Cannot reproduce in latest version.
