### ISSUE TITLE
Rainbow Honey Block recipe has multiple crafting results, makes autocrafting some options impossible.

### ISSUE THREAD

**Issue by IAmCoffee** [AllTheMods/ATM-6#2037]
ATM6 1.7.1

The recipe shown below for dyes made from Rainbow Honey Blocks has three crafting results, since autocrafting defaults to the red dye I'm unable to autocraft black or orange dye using this recipe.

![2021-07-19_23 32 54](https://user-images.githubusercontent.com/87676582/126235930-4d90f26b-d717-4b69-b37e-2914acdcd131.png)

**Comment by TheLittleCube** [comment]
This is the same for Croppy/Mystical/Kobee combs and blocks.

**Comment by BovineShaman** [comment]
#2044
