### ISSUE TITLE
Mods in ATM

### ISSUE THREAD

**Issue by DNephilim** [AllTheMods/ATM-6#2040]
Version (1.6.14)

I was wondering what mod you use to make like the tool dont instantly break when it has no durability. Instead it will show the tool as "Broken". I am also wondering what minimap mod you use. It looks cool. And what kind of mod you use that makes it blocks like dirt and cobblestone drops experience?

**Comment by Pdiddy973** [comment]
the "broken" tools and xp sounds like thats a tinkers construct thing, and the map is FTBChunks
