### ISSUE TITLE
More Overlays Updated

### ISSUE THREAD

**Issue by faizjamil** [AllTheMods/ATM-6#2046]
I'm on pack version 1.7.2, but I'm wondering why More Overlays Updated was removed at some point after version 1.6.11? And why was that change not written in any of the changelogs?

**Comment by radiomike** [comment]
I believe More overlays caused the soggy guns mod to be included in the pack, which was why it was removed. It works fine, so there's nothing stopping you from replacing the lightoverlay mod with it.

**Comment by faizjamil** [comment]
I'm curious, how did including that mod cause another, seemingly unrelated mod to be removed? Even if you keep the mod out of the pack, I and probably others would have appreciated that being included in one of the changelogs, but I'm assuming that not including it was accidental rather than intentional.

**Comment by ladylexxie** [comment]
I wasn't part of it but it most likely got removed because most of the features already exist in the game.
