### ISSUE TITLE
Fire and Ice dupe

### ISSUE THREAD

**Issue by RaresKool** [AllTheMods/ATM-6#205]
**Describe the bug**
Fire and Ice gold piles drop sometimes drop 16 nuggets instead of two (without being stacked) when broken, and only require 2 to craft.

**To Reproduce**
1. Craft gold pile.
2. Break it.
3. Repeat.

**Expected behavior**
Expected to drop 2 nuggets per stacked layer.

**Comment by DerShendi** [comment]
nice but id say its inconsequentional because you get a lot of stuff in this pack pretty easy but yeah it should still get fixed

**Comment by WhitePhant0m** [comment]
I've reported it to the dev https://github.com/Alex-the-666/Ice_and_Fire/issues/3051
