### ISSUE TITLE
I can't plant unobtanium

### ISSUE THREAD

**Issue by tavimxis7** [AllTheMods/ATM-6#2053]
In the last few days I went to make unobtanium seeds and when I went to plant I didn't have any planting method, so I decided to import the modpack and my world to a minecraft host and when it starts it gives an error like:
CRUX for Unobtanium not found

and the same error happened for allthemodium and vibranium.
I do not know what to do :/

**Comment by davepatelbn2** [comment]
Magical dirt is the crux for those plants- its from the kubejs mod
