### ISSUE TITLE
Had to disable rats mod

### ISSUE THREAD

**Issue by Prossy22** [AllTheMods/ATM-6#2054]
Version 6-1.7.2

I was forced to disable the rats mod because it kept on crashing my world because it will randomly forget to render everything in the rat mod and crash and would be forced to use a back up losing hours of progress, And sometimes when i load back up from a backup the rats and trader will lost their visuals and wont work & get stuck, if i try to interact when they are like this it instantly crashes my game.

Although my game runs so much smoother when i disabled it there are recipes that rely on the rat mod and no longer can't make without going into creative mod, so if there could be a way to add alternatives components  to them when possible, thankyou

Not sure on how to reproduce it because it just happens in the backround, i set up a create area. a refined storage area and a resourceful bees area first then when i tried out minecolonies it started happening then when i got way into it, the rats trader would get stuck everywhere with his rats

crashreport here

https://gist.github.com/Prossy22/f1dc464953c7770eac0dc7a0affb7e4a

**Comment by simone-viozzi** [comment]
same issue here

**Comment by ladylexxie** [comment]
This will be "fixed" in the 1.8.0 version of the pack.
