### ISSUE TITLE
Allthemodium Alloy Paxel won't allow Looting, Indestructible, and Miner's Fervor Enchants

### ISSUE THREAD

**Issue by toxikak** [AllTheMods/ATM-6#2056]
Pack Version: 1.7.2
The Looting, Indestructible, and Miner's Fervor enchanments won't work on the Allthemodium Alloy Paxel. Other enchantments such as Fortune or Sharpness worked, but these are not working. 

To reproduce:
Create an Allthemodium Alloy Paxel and attempt to enchant with Looting, Indestructible, or Miner's Fervor. (I was trying to use Looting VI, and Miner's Fervor III.

**Screenshots**
![2021-07-23_00 58 07](https://user-images.githubusercontent.com/87845232/126739271-6bfbfe89-4ac9-4eb7-9d75-0da2291dbec3.png)
![2021-07-23_00 58 10](https://user-images.githubusercontent.com/87845232/126739276-f7ff0d03-a0e6-4189-ae46-60b41546d306.png)

I saw that there was an issue very similar to this already on github, but it was closed without any solution.

**Comment by ladylexxie** [comment]
Doesn't happen in latest versions anymore. Whatever it caused it seems to be fixed.
