### ISSUE TITLE
Cant Craft All of the Allthemodium Alloy ingots

### ISSUE THREAD

**Issue by Jan2509** [AllTheMods/ATM-6#2058]
In the last version (1.7.2 of ATM6) i dont have any recipe to craft the Allthemodium Alloy ingots.
Is this right or an issue?

**Comment by ladylexxie** [comment]
If you're trying to look it up in JEI, it's bugged and it won't show. the recipes are in the wiki [here](https://github.com/AllTheMods/ATM-6/wiki/General-Gameplay-Guides).
