### ISSUE TITLE
ATM6 - 1.1.7 - Way too many fish spawns

### ISSUE THREAD

**Issue by sssssss340** [AllTheMods/ATM-6#206]
Hundreds of fish are spawning in lakes surrounding player bases.

1. Log in to an existing 1.1.6 world after updating.

**Expected behavior**
Not all the fish.

**Screenshots**
https://imgur.com/a/F6D2Fao

**Comment by Christo6** [comment]
I can confirm that there are far too many fish. This also applies to brand new Single Player worlds.

**Screenshots**
https://imgur.com/a/wSvRr9z

### So long, and thanks for all the fish

**Comment by shalazan** [comment]
I can reconfirm there are ~more fish in my swamp than in the entire Atlantic ocean. Shrek is displeased.

**FishShots**
https://preview.redd.it/y74d7kry1qu51.png?width=960&crop=smart&auto=webp&s=00fdcb4a09def72f07552e4071a0ecaf456f14cd

**Comment by sssssss340** [comment]
Fixed with 1.1.7b Aquaculture downgrade
