### ISSUE TITLE
AtM 6 - 1.7.3: Menril logs (and any other items) can't be inserted into manual squeezer

### ISSUE THREAD

**Issue by Sakata-MC** [AllTheMods/ATM-6#2062]
**Describe the bug**
Items cannot be inserted into manual squeezer. The same items do work in mechanical squeezer.

**To Reproduce**
1. Place mechanical squeezer.
2. Attempt to use it.
3. Report bug because it doesn't work.

**Screenshots**
![image](https://user-images.githubusercontent.com/3158362/126857533-1e0bbd80-6bcb-43f8-b54a-f41cb080d32e.png)

**Additional context**
Kinda need the Menril recipe working to get into the mod at all.

**Logs**
N/A

**Comment by BovineShaman** [comment]
Tested it in 1.7.4, works fine. See if updating helps?

**Comment by Linguardium** [comment]
issue occurs when dank is set to pick up items. this also affects the dryer
