### ISSUE TITLE
SIMPLE-SERVER-FILES-1.7.3 Not working 

### ISSUE THREAD

**Issue by Maxderwahnsinige** [AllTheMods/ATM-6#2063]
the pack is ATM6-1.7.3 version 

I tryed to create a ATM 6 Server with the SIMPLE-SERVER-FILES-1.7.3 and pressed on the Startserver.bat
the cmd opened and than displayed this:

INFO: Checking java installation...
INFO: Found Java.
serverstarter binary not found, downloading serverstarter...

than nothing happened for 3 hours i waited that long while checking online for resons or problems 

**To Reproduce**
1.download the SIMPLE-SERVER-FILES-1.7.3.rar
2.place it in an extra folder 
3.start the startserver.bat 

**Screenshots**
![grafik](https://user-images.githubusercontent.com/87911920/126878164-ec77c9de-f22c-4723-97cb-abf029bf0a89.png)

**Additional context**
I have a Win 10 operating system in an i7 processor with 64 gb of ram

**Comment by ladylexxie** [comment]
Does this still happen in the current version of the pack?
