### ISSUE TITLE
Botania book trade makes Akashic tome disappear.

### ISSUE THREAD

**Issue by SimplyAzgoth** [AllTheMods/ATM-6#2064]
ATM 6 Version 1.7.1

This is a minor bug which can be circumvented:
The Akashic tomb that you spawn with and that can be crafted with 1 stick contains a lexica botania, but when thrown into the elven portal for the upgraded version, it disappears.  This can be circumvented by creating a normal botania book and trading with that. This unlocks the elven portal 'age' and you can get your akashic tome again and use the book inside the tome.

Steps to reproduce:
1. Get the Akashic tome either by entering world or crafting with stick
2. transform it into the botania book
3. build elven portal
4. throw it in the portal
5. book disappears

**Comment by BovineShaman** [comment]
Throwing any non-tradeable item ends up deleting the item from existence.
If you crouch-drop while having a certain book selected in the tome, it will drop the book out of the tome and give you the rest of the tome back. You can then toss the lexica in the portal, pick it back up, and add it back to the tome.

**Comment by SimplyAzgoth** [comment]
Ah okay then just a misunderstanding on my part and not a bug. Have a good day.

**Comment by BovineShaman** [comment]
Testing it, the pre-portal lexica (the one without gold trim) while in an akashic tome still works, whereas if it has already gone through, it gets destroyed when put in again.
