### ISSUE TITLE
Immersive Engineering Feedthrough Insulator

### ISSUE THREAD

**Issue by CommonConDog** [AllTheMods/ATM-6#2065]
ATM 6 - 1.7.4
I tried to remove a feedthrough insulator from Immersive Engineering, this then causes the game to crash.

Steps to reproduce the behaviour:
1. Use LV connectors on a solid block (in my case a dark oak log) and put them on opposite sides.
2. While using the engineer's hammer, right-click on any of the LV connectors.
3. Attempt to destroy the new multiblock.
4. Error will occur shortly after.

Note: This happens in survival, and doesn't occur in creative mode. I have tested this on multiple blocks and the error continues to occur. 

Error message:
The game crashed whilst tesselating block model
Error: java.lang.NullPointerException: Tesselating block model
Exit Code: -1

**Comment by iarspider** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/4879
