### ISSUE TITLE
FTBTeams is persistent, but not at the same time?

### ISSUE THREAD

**Issue by dewman45** [AllTheMods/ATM-6#2066]
So since the modpack switched to FTBTeams instead of what we were using before, we have had issues with having to recreate teams every time we play.

To recreate the issue:
1. Make a party/team and invite some people.
2. Do your normal stuff checking claims and making sure you have access.
3. Everyone log off for a bit.
4. Log back on. It'll show you are still on said team, but it will say allies: 0, even with allies logged on. You will lose access to anything that isn't directly in your personal claim, and is in the team claim, except the team claim is still there and shows on the map.
5. Delete the team and recreate it, and reinvite people, redo claims, and it's working until everyone logs off again.

**Comment by dewman45** [comment]
Additional note, it may be due to players being viewed as separate teams(which can be viewed in /ftbteams list,) since individual players show up. Only issue is you can't invite unless you have a party created, so it doesn't help much.

**Comment by ladylexxie** [comment]
If this issue is still happening, it should be reported [here](https://github.com/FTBTeam/FTB-Teams/issues/new/choose).
