### ISSUE TITLE
1.7.5 Issue with FTB Chunks and Water placement

### ISSUE THREAD

**Issue by Diomendos** [AllTheMods/ATM-6#2067]
Hi, 

I'm facing a strange issue with FTB Chuncks in 1.7.5, after I recently updated the pack.

I'm playing single player and claimed my base and loaded the chucks, via FTB Chuncks. (9 claimes and 9 loaded at all).

When I try to place a bucket of water in a claimed chunck (for a farm) the water get removed from the bucket, but not placed in world (or at least it looks like it get placed for 1 tick and removed directly).
When I unclaim the chunck, I can place the water fine.

Also a permanent water source in claimed chunckes don't get updatet corretly, the water block gets removed when using a bucket, but the water don't flow. So it don't get renewed. It stays air.

Tried both in unclaimd chuncks, than it works fine.
Tried in not loaded, but claimed chuncks, same issue as above.

If you need anything I should test or add as info, please let me know. 

Gerrtings

**Comment by ladylexxie** [comment]
If this issue is still happening, it should be reported [here](https://github.com/FTBTeam/FTB-Chunks/issues/new/choose).
