### ISSUE TITLE
1.7.5 Can't install AT Launcher or MultiMC

### ISSUE THREAD

**Issue by JavelinD** [AllTheMods/ATM-6#2068]
Can't install from the 1.7.5 zip released on curseforge

**Logs**
MultiMC
https://pastebin.com/Lz5CKvPr

ATLauncher
https://pastebin.com/MJnmrLia

**Comment by Pdiddy973** [comment]
Current version of MultiMC (develop-2241) does not work with the latest version of Forge. For ATM6 1.7.3, you will need to use GDLauncher or Curseforge Launcher until this bug is fixed. https://github.com/MultiMC/MultiMC5/issues/3953
