### ISSUE TITLE
ATM 6 v. 1.1.5 (And 1.1.7b)

### ISSUE THREAD

**Issue by EnderDarkeoj** [AllTheMods/ATM-6#207]
**Describe the bug**
Recipe for Magenta Alabaster is disabled.

**To Reproduce**
1. Go to jei
2. Search Magenta Alabaster
3. Click on it

**Expected behavior**
Should be 8 of any alabaster surrounding 1 magenta dye/dye plate

**Comment by jeremiahwinsley** [comment]
Tracked here: https://github.com/ValkyrieofNight/EnvironmentalMaterials/issues/4

**Comment by whatthedrunk** [comment]
This was added a couple updates ago
