### ISSUE TITLE
Cyclic Disenchanter does not work

### ISSUE THREAD

**Issue by dandud100** [AllTheMods/ATM-6#2071]
In 1.7.4 the cyclic disenchanter does not work anymore
It have a Tank now, but for what?

![image](https://user-images.githubusercontent.com/43549788/126962719-dcceca51-66d4-444b-8c0a-65cac791c5f5.png)

**Comment by dandud100** [comment]
Nvm, since last update in consumes experience fluid

**Comment by lilimil1** [comment]
> Nvm, since last update in consumes experience fluid

can you explain how it works? I've been trying for a long time and I didn't understand...
