### ISSUE TITLE
ATM6 1.7.5 - The Mighty Architect crashes game when saving schematic

### ISSUE THREAD

**Issue by MyndPhreak** [AllTheMods/ATM-6#2075]
**Describe the bug**
The Mighty Architect was added to ATM6 version 1.7.5. This is a really cool mod, but when saving a schematic, it will always crash my game, even in single player.

**To Reproduce**
1. Open The Mighty Architect GUI
2. Create a building
3. Save Schematic
4. Game crashes

**Logs**
https://h.ppo.gg/NzmmN - Self Hosted Hastebin
https://pastebin.com/svG13evR - Same logs but for those weary of selfhosted stuff.

**Comment by MyndPhreak** [comment]
I have also filed a bug report on The Mighty Architect github just in case.

**Comment by jebjordan** [comment]
Same on newest pack version.

**Comment by ladylexxie** [comment]
This is/was an issue caused by the mod devs, nothing we can do about it.
