### ISSUE TITLE
Rendering error

### ISSUE THREAD

**Issue by Flayvers** [AllTheMods/ATM-6#2079]
The game crash when you put a back pack from sophisticatedbackpacks in a tinker table

**To Reproduce**
Place a tinkers' construct crafting station
put a sophisticatedbackpacks in it

Log :
 https://pastebin.com/ZuC9fF5a

**Comment by seguraf16** [comment]
Having the same issues here with the game client crash, anyone going into the chunk will disconnect
Crash log #1: https://pastebin.com/3ZnaSe4b
Crash Log #2: https://pastebin.com/SWiJ2LAh

**Comment by Lordfirespeed** [comment]
Can confirm this is happening as of SB3.0 ending 289, forge 36.2.0, on MC 1.16.5

**Comment by nmorgus** [comment]
this is also happening for me, i just posted a ticket of my own

**Comment by ladylexxie** [comment]
Cannot reproduce in current version, please open an issue with the devs of the backpack if it still happens.
