### ISSUE TITLE
Server missing recipes

### ISSUE THREAD

**Issue by Colton-Slayden** [AllTheMods/ATM-6#208]
**Describe the bug**
Server ran on my host does not have any recipes for magical soil and maybe other items.
**Additional context**
If my server log i have many [dev.latvian.kubejs.event.EventsJS:postToHandlers:88]: <eval>:16 ReferenceError: "block" is not defined erros for items, ingredients

**Comment by cornholio84** [comment]
I have a similar issue with my server, after an update some recipes stopped working.
in singleplayer it works fine but not on our server.
among those items are from rf-tools, extra disks and entangled

**Comment by Colton-Slayden** [comment]
Can you by chance get the debug log from the server. I have found the issue. For some reason kubejs does not like java 1.8.0_111 and does not load recipes there may be other versions of java that cause issues but so far I know java 1.8.0_51, 1.8.0_261, 1.8.0_271 do not cause this issue

**Comment by cornholio84** [comment]
here we go, i'm quite new to this so chances are i'm missing something

[debug.log](https://github.com/AllTheMods/ATM-6/files/5447050/debug.log)

**Comment by Colton-Slayden** [comment]
You seem to be having a different issue, what version are you on?

**Comment by Colton-Slayden** [comment]
I am gonna guess you are on 1.1.6 updating to 1.1.6b should fix your issues or to the latest 1.1.8

**Comment by cornholio84** [comment]
started the server at 1.1.3 updated regulary so i'm on the newest 1.1.8
I'm using APEX as a host so to update all i did was remove the ATM6.jar and it should update the server automaticly

**Comment by Colton-Slayden** [comment]
Well 1.1.8 added quark and in your log it has nothing about quark. I would download the server files again and then on the host delete everything but the world file and have it reinstall

**Comment by Colton-Slayden** [comment]
The main thing you need to make sure gets update on the kubejs files for recipes

**Comment by cornholio84** [comment]
I will give it a go and get back to ya

**Comment by cornholio84** [comment]
now it works fine!
Thank you for the help

**Comment by Colton-Slayden** [comment]
Np glad your issue could be fixed

**Comment by Colton-Slayden** [comment]
So I found the issue its with Kubejs anyone that has same issues and is on java 1.8.0_111 it does not work on this java. Update to fix the issue
