### ISSUE TITLE
Cyclic disenchanter doesn't work in lattest update

### ISSUE THREAD

**Issue by weareminers** [AllTheMods/ATM-6#2082]
All the mods 6, 1.7.6

I have tried every thing to get it to work it has power and redstone signal. But the tank is empty I tried putting cyclic exp liquid and doesn't go in and I tried other liquids as well. I am on a fresh world.

**Comment by Pdiddy973** [comment]
seems to be a bug with cyclic, TOP shows the fluid in the disenchanter, but the UI doesnt. it still works tho
