### ISSUE TITLE
Waystones not properly suppressing right click functionality.

### ISSUE THREAD

**Issue by RainTheHatellc** [AllTheMods/ATM-6#2083]
Just what the titles says, clicking on a Waystone with a block in your hand will place the block and open the waystone. Right clicking the waystone with a non-block entity that has right click functionally (portable inventory, trident, etc.) cause that item to perform it's right click functionality. Waystone is not acting like a chest or other item that can be opened with a right click and suppress auxiliary right lick functionality.

**Comment by Linguardium** [comment]
known issue, fixed in development but not yet in a release.

https://github.com/ModdingForBlockheads/Waystones/issues/398
