### ISSUE TITLE
Create - problem with crafting bee nest

### ISSUE THREAD

**Issue by MrSwordCZE** [AllTheMods/ATM-6#2086]
Hey, I'm playing AllTheMods6 and I'm trying to craft vanilla bee nest with this recipe that requies 8000mB of honey but the basin from Create can only fit 1000mB of single liquid, how do I craft this or how do I fit more honey in it? Thanks.

![question](https://user-images.githubusercontent.com/44101520/127514847-9a22db8c-38ca-4b98-bf25-4076a86c632f.png)

**Comment by ladylexxie** [comment]
Fixed in the next version to require 1000 instead of 8000.
