### ISSUE TITLE
[ATM6 1.7.6] Thermal Series Crop Crates

### ISSUE THREAD

**Issue by ZilophosGH** [AllTheMods/ATM-6#2087]
Crates from the Thermal Series, such as the crate of onions, have inconvienent recipes if you have the same type of crop (like onions) from Pam's Harvestcraft. To make a crate you need either 8 Thermal crops and 1 of Pam's, or 9 Thermal crops. The recipe should be either 9 crops from Pam's, or 9 crops from Thermal.
![unknown](https://user-images.githubusercontent.com/88152241/127517005-22e85034-bc1d-4270-855b-cc85aee23005.png)

**Comment by ladylexxie** [comment]
Fixed in the next version
