### ISSUE TITLE
v 6-1.7.6 FPS drop

### ISSUE THREAD

**Issue by blicake** [AllTheMods/ATM-6#2088]
I loaded a new world, lowered all my graphic settings, but FPS wasnt just low all the time, it went 60 - 15 - 0 then back to 60. every cycle is about 2 seconds, so it constantly goes 60-15-0-60-15-0 etc

**To Reproduce**
load a new world -> watch fps

**Additional context**
limiting fps didnt help, lowering graphic settings also

**Logs**
pt 1 https://pastebin.com/KjVTwaDR
pt 2 https://pastebin.com/wAJsJnjm
pt 3 https://pastebin.com/10yZfHTN
[latest.log](https://github.com/AllTheMods/ATM-6/files/6901602/latest.log)

**Comment by LilHaramBae** [comment]
By any chance, have you allocated more ram to the launcher and/or server?

**Comment by blicake** [comment]
that fixed the FPS drop, but my game crushed when i was exploring very soon. my pc is probably too bad, tnx for helping though
