### ISSUE TITLE
Game crashes when the Layout Guide block from Woot is near you (Client only)

### ISSUE THREAD

**Issue by GrimmDZ** [AllTheMods/ATM-6#209]
**Describe the bug**
I am on the 2nd official server. Bwarf placed down the Layout Guide from Woot in his base. We both have a waystone between our bases, I went to use it to go to his base and I got the "Saving World" screen. Then the Minecraft crash screen popped up. I had him also use my waystone to see if he crashes him too and it did. When he got rid of the block, everything was fine, didnt crash. I also could be wrong of what the issue is, I tried to provide as much information I can on my own to help you guys out. 
Heres the crash report: https://pastebin.com/ndBQnTD0
I also crashed other time relating to the block, Bwarf was showing me ingame what the block was, when he broke the block I crashed the same way and got the same report. He did not crash when he picked it up, it was just me.

**To Reproduce**

1. Place down the Layout Guide block anywhere in the overworld.
2. Get a waystone and connect it with another decently away. (bwarfs and I's waystones are about 200 blocks away)
3. Use said waystone to come back to the area with the block in.
4. You should see the screen "Saving world" and it should soon crash.

**Expected behavior**
I expect to not crash within the block "Layout Guide".

**Comment by GrimmDZ** [comment]
Ive thought about it more, and its probably an issue with the mod only, but ill wait to see what you guys say before I make a post on their github.

**Comment by jeremiahwinsley** [comment]
Fixed in 1.3.9.
