### ISSUE TITLE
No recipe for Mystical Agriculture Marble Seeds?

### ISSUE THREAD

**Issue by Furious1964** [AllTheMods/ATM-6#2090]
Tried to make them, but was only able to make the Aquamarine Seeds. Are they disabled or something?

**Comment by BovineShaman** [comment]
You should be able to use pedestal's cobble generator upgrade to generate marble, very quickly too.

**Comment by Furious1964** [comment]
HOW!!!

**Comment by AllanonBrooks** [comment]
I think you have to apply the cobble generator upgrade  and place a marble block under the pedestrial.

**Comment by Furious1964** [comment]
Did that and it didn't work.

**Comment by radiomike** [comment]
Stan bee combs and honeycomb blocks are the way to do this at the moment.

**Comment by ladylexxie** [comment]
Fixed in the next version.
