### ISSUE TITLE
[ATM6 v1.7.6] Environmental Tech Void Miners not working as intended

### ISSUE THREAD

**Issue by bigbluu722** [AllTheMods/ATM-6#2091]
**Describe the bug**
Tier 6 & 7 Void ore miners produce no nanorite, tier 7 void miners also produce no xerotheum

**To Reproduce**
1. Place down tier 6 or 7 environmental tech void miner
2. Build structure shown as in the preview
3. 3 put in crystal miner memory card so it mines crystal
4. wait
5. receive no xerotheum or nanorite crystals, but every other crystal

**Screenshots**
![Crystal Miner Gains](https://i.imgur.com/6eGVtf0.png)

**Additional context**
The screenshot above is roughly about 35 minutes of running my Tier 7 Miner I spawned in to test on my server. The tier 6 miner I ran for about 8 hours over night and gained 0 nanorite crystals.

**Comment by Pdiddy973** [comment]
are you putting them in the nether/end? or leaving them in the OW?

**Comment by bigbluu722** [comment]
I've left them in the overworld, do you need them to be in the nether and end for the tier 7 and 8 crystals?

**Comment by Pdiddy973** [comment]
t7/8 need to be in the end, forget what tiers off hand that need to be in the nether for better results, i put all of mine in the end tho and that works well
