### ISSUE TITLE
Backpack in Tinker's crafting station breaks the world.

### ISSUE THREAD

**Issue by JackRHainsworth** [AllTheMods/ATM-6#2093]
Placing a backpack from the sophisticated backpacks mod in a tinker's crafting station crashes the world, and makes it impossible to re-open the world without loading a backup.

**Comment by FragsAreUs** [comment]
I cant +1 on this works fine in the original minecraft workbench but when using it with the tinkers it crashes giving a entity render issue

**Comment by blinkinglight** [comment]
https://pastebin.com/RLCy4jmX same problem, wanted to craft iron tier backpack in tinkers crafting station

**Comment by BovineShaman** [comment]
@blinkinglight @JackRHainsworth try updating sophisticated backpacks and let us know if that fixes the problem.

**Comment by blinkinglight** [comment]
yes, update mod fixes issue

**Comment by blinkinglight** [comment]
also that happens than you try to upgrade basic backpack to iron tier in tinkers table.  ( maybe because it renders items on the tables and problem was with backpack mod itsefl)

**Comment by ladylexxie** [comment]
Duplicate of #2079
