### ISSUE TITLE
Filling Bottles with Magma Crucible crashes the server

### ISSUE THREAD

**Issue by F4bric** [AllTheMods/ATM-6#2100]
**Describe the bug**
Trying to fill up a Glass Bottle with honey from the Magma Crucible crashed the entire server and insta kicks everyone.

**To Reproduce**
Have a Magma Crucible from Thermal Series
Fill it up with Honey
Try to fill up an empty bottle by right clicking the Magma Crucible with a empty Glass Bottle in your hand

**Additional context**
It might not be exclusive to honey, But honey is the only thing I tried, that's what someone in my server tried to do and it just insta crashed everyone out of the server as well as killing the server.

**Logs**
https://hastebin.com/coqerufabe.pl

**Comment by ladylexxie** [comment]
Cannot reproduce in the current version.
