### ISSUE TITLE
Ice and fire question on version 1.7.2

### ISSUE THREAD

**Issue by TheImpurity** [AllTheMods/ATM-6#2101]
I went into the other dimension, and I could only find Myrmex and dragons. No deathworm, no gorgon temple or any other ice and fire mobs. Is this because of the biomes mostly consists of nether biomes? The only way to find cockatrice now is to spawn it through rotten eggs, which is found in village/dungeon chest?

**Comment by ladylexxie** [comment]
We are controlling the spawning of I&F mobs through AllTheModium mod. That's where most of the configs are.
