### ISSUE TITLE
Rat's Psionic/or/ Bee Rat causing Crash loop

### ISSUE THREAD

**Issue by Roasaelion** [AllTheMods/ATM-6#2102]
The attack from the either the Psionic/Bee Rat from the Rat's mod . It is causing a server crash after a recent update to the latest version of AllTheMods6
As I'm not the server owner I'm unable to provide a crash log, but the crash happened after the Rat opened it's portal to attack a Mob in a loaded chunk - though as stated, the issue may have been the Bee Rat instead.

It was attacking a (Possibly?)Mana and Artifice mob whilst within a Minecolonies border - I am unsure if the guards were hit, it was the combined hits of the Rat and Guards on the mob itself. 
As it was the first time experimenting with the upgraded Psionic Rat and Bee Rat, i am unable to confirm which it was.

This was following the random deaths by falling for the Iron Golem Rat and Plague best Rat after leaving the chunk and returning to it.

The issue happened at night as i went to investigate what my new "rat guards" were doing. We are now stuck in a server crash loop.

Hoepfully this helps

**Comment by ladylexxie** [comment]
This is No longer applicable in the next version of the pack.
