### ISSUE TITLE
rftools builder break was canceled ATM1.7.6

### ISSUE THREAD

**Issue by xNoVoSx** [AllTheMods/ATM-6#2103]
**Describe the bug**
When the Builder tries to mine allthemodium it stops and displays break was canceled.

**To Reproduce**
tries to mine allthemodium ore with the RFtools Builder
then it will show break was canceled

**Comment by radiomike** [comment]
This is expected behavior for allthemodium, vibranium, unobtanium and "the_other" ores. 
You should set the builder to skip and then, when it has cleared everything, you manually mine those ores with a suitable pickaxe.

**Comment by xNoVoSx** [comment]
how do i set the builder to skip?

**Comment by Floppa-8765** [comment]
> how do i set the builder to skip?
> 
> 

hourglass icon on the left side of the UI

**Comment by xNoVoSx** [comment]
thx mate
