### ISSUE TITLE
Rendering Block Entity : smeltery_controller

### ISSUE THREAD

**Issue by Krosnoz** [AllTheMods/ATM-6#2105]
Hello, my friend had a bug with the foundry, he missclicked and put a backpack in it, and since then as soon as we connect the server crashes, its the backpack from sophisticated backpacks.

I managed to debug using the /fill command.

LogFile : https://pastebin.com/B62J1tsR

Cheers.

**Comment by FragsAreUs** [comment]
try seeing if updating sophisticated backpacks will fix your issue

https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks/files/3404306

**Comment by Krosnoz** [comment]
Hello, thank you for your answer.

I'm just a casual gamer, I don't know much about mods, if I want the update, I have to replace the sophisticatedbackpacks-1.16.4-3.0.0.289.jar by the new version in the \mods folder ? For the server and the client or just for the server ?

**Comment by FragsAreUs** [comment]
you would have to replace the mod on both server and client yes delete the old one and replace it with the new updated and see if that fixes your crash issue

**Comment by Krosnoz** [comment]
I just tried it and yes, it doesn't crash anymore! 
Thank you for the reactivity!
