### ISSUE TITLE
invisible blocks on Server when using create ore Builders wand

### ISSUE THREAD

**Issue by xNoVoSx** [AllTheMods/ATM-6#2109]
**Describe the bug**
hay we have this weird problem on our server when we are using builder wand ore move blocks with create the blocks go invisible it goes back to normal after rejoin.

**To Reproduce**
1. join server 
2. use the builders wand 
ore
1. build a door using create and Mechanical Gearbox
2. Activate the door

**Screenshots**
before:
![2021-08-03_23 13 30](https://user-images.githubusercontent.com/88331908/128087167-4a9ae372-196c-4220-9e08-d2d1070b754f.png)

After:
![2021-08-03_23 13 51](https://user-images.githubusercontent.com/88331908/128087187-71baf9f2-a138-4227-a16b-c43ea5d51a89.png)

**Additional context**

**Logs**
https://pastebin.com/q2Nbz4kK

**Comment by xNoVoSx** [comment]
ATM 1.7.6 btw

**Comment by ladylexxie** [comment]
If the issue still persists in the latest pack version, it should be reported to the devs of the builder wands.
