### ISSUE TITLE
Potion master sight potions still on when going from single player to multiplayer

### ISSUE THREAD

**Issue by chadica** [AllTheMods/ATM-6#211]
**Describe the bug**
So When you use a sight potion from potion masters in singleplayer and having a ore down in the single player then leave and go to a mutiplayer server it keeps the sight

**To Reproduce**
Go to single player use any sight potion from potion masters and place a ore down then once you see the ore you leave the single player and go to a multiplayer server the effect stays on indefinite

**Expected behavior**
The expected behavior is that the sight potion doesn't come over from single player to multiplayer

.

**Comment by thevortex** [comment]
https://www.curseforge.com/minecraft/mc-mods/potionsmaster/files/3092911 should resolve this issue :) thanks!
