### ISSUE TITLE
crafting alloys ? 

### ISSUE THREAD

**Issue by Flayvers** [AllTheMods/ATM-6#2113]
I got a server using the 1.7.5 version of ATM6.
BUT, why do there is no craft for the allthemodium/vibranium/unobtainium alloys ?
I heard that it was in the dragon forge, but, its just giving me ash... Do you have any answer ?

**Comment by Skogisplayer** [comment]
ATM+Vibranium alloy = Fire Dragon Forge
ATM+Unobtanium alloy = Lightning Dragon Forge
Vibranium+Unobtanium alloy = Ice Dragon Forge
