### ISSUE TITLE
when put backpack in crafting station game will crash and connot rejoin that world that world is broken

### ISSUE THREAD

**Issue by Jetsu0** [AllTheMods/ATM-6#2116]
my world broken so many time i waste my time to play this mod but still crash its make me annoying

**Comment by McKitten** [comment]
You need to update the Sophisticated Backpacks mod on the server and make sure any clients update that mod also.

I had this issue and the author had patched it in a little over a day later.

**Comment by Pdiddy973** [comment]
should be fixed in newest pack version
