### ISSUE TITLE
Constant Crashing with the Mage light Sconce from the Ars Nouveau mod when/where ever you try to place it

### ISSUE THREAD

**Issue by Metal4Claws** [AllTheMods/ATM-6#2117]
I was looking for light sources for my world, then I made a few mage lights to see if they would work, I first placed a stone brick wall next to my Refine storage controller and place it. Instantly my game crashed, and I repeated it twice to see if I could replicate it, and it did. I even tried placing it somewhere else and got the same result ever time. Please fix, or remove that item so noone will accidentally crash or ruin their PC because of it.

**Comment by ladylexxie** [comment]
Cannot reproduce in the current version. Please reopen an issue if it still persists or report it to the Ars Nouveu developer.
