### ISSUE TITLE
Two types of nether quartz

### ISSUE THREAD

**Issue by jonalange** [AllTheMods/ATM-6#2118]
**Describe the bug**
I have two types of nether quartz in my AE2 ME system that also if I put them in my inventory don't stack.
When I hold shift and hover over them one has `NBT: { }` and the other has none

**To Reproduce**
I don't know how to reproduce, but the only way I got nether quartz (and what I did with it) is the following:
- farmed in the nether
- had it in my inventory
- had some in a "Dank" from Dank Storage
- autocrafted them with a "Crafter Tier 3" from RFToolsUtility from mystical agriculture essence

**Screenshots**
https://preview.redd.it/2xlrqu07bsf71.png?width=931&format=png&auto=webp&s=6ff93270c273da5fe38a91a2c4ebfa10495ac4a8

https://preview.redd.it/w9jcaei5bsf71.png?width=905&format=png&auto=webp&s=62a41697a8b588ba6f3c4648fe6fb684b47eb0d1

**Additional context**
I first noticed this bug after I removed all nether quartz from my ME to put it in a black hole unit and connected that with storage bus. Now after a while I noticed two big stacks in my ME

Pack Version (also on server): 1.7.6

**Comment by Pdiddy973** [comment]
do you have a quartz bee making quartz?

**Comment by jonalange** [comment]
No, just mystical agriculture. And I just noticed that it's also happening with certus quartz

**Comment by jonalange** [comment]
Also ender pearls. 
Every item that is affected is in a black hole unit connected with a storage bus with the ME. But _not every_ item that I autocraft with mystical agriculture that is stored in a black hole unit has this problem. For example diamonds, emeralds, lapis are fine

**Comment by ladylexxie** [comment]
This is fixed by Resourcefulbees.
