### ISSUE TITLE
I can't activate nether portal

### ISSUE THREAD

**Issue by Khwyk** [AllTheMods/ATM-6#2119]
All the mods 6 1.7.6

I can't activate nether portal 
I try solo and multiplayer and i have the same issue

![image](https://user-images.githubusercontent.com/88558887/128563229-a05959b6-08aa-4363-879c-16f2992cd305.png)

**Comment by ladylexxie** [comment]
Does this still happen on the latest version? And are you on singleplayer or multiplayer?
