### ISSUE TITLE
I can't type in server console

### ISSUE THREAD

**Issue by Znuffles** [AllTheMods/ATM-6#212]
**Describe the bug**

**To Reproduce**

open startserver.bat
me and friends can join server
I try to type in console to give myself op
can't type in consolde

**Expected behavior**
open startserver.bat
me and friends can join server
I try to type in console to give myself op
i can give myself op and i can type in server console

**Screenshots**

**Additional context**

**Comment by WhitePhant0m** [comment]
restart the server, it will work fine after that.

**Comment by Electr0smith** [comment]
I am having the same issue.

How can I restart the server without being able to type?

I can't type "stop", so the startserver.lock file remains and there is no startserver.bat
