### ISSUE TITLE
server crashing constantly 

### ISSUE THREAD

**Issue by JCG1090** [AllTheMods/ATM-6#2124]
a few days ago one of the players on my server notified me that my server was being slow so i tried joining it and it crashes instantly with the error jave.io.IOEexception

i was wondering if someone could help me out i would appreciate it

here is a pastebin of the crash
https://pastebin.com/CmDceCGb

https://pastebin.com/k5cBWssv 

version 1.7.6

**Comment by xNoVoSx** [comment]
Hay its watchdog go into your server.properties and set max-tick-time to -1 (max-tick-time=-1)

**Comment by radiomike** [comment]
You need to deal with the 38000+ items that you have in the world. They are what is causing the watchdog timeout.
From the server console you can try `cu entity remove byType minecraft:item force` to remove them. You do need to find the cause of the spill and fix it, otherwise it will continue to cause issues.
You can also configure crash utilities to automatically remove dropped items. See it's config in `<world>/serverconfig/crashutilities-server.toml`
I'd also not recommend setting `max-tick-time` to -1 permanently. It would be better just to add a 0 to make it a 10min timeout rather than a 1 minute one.

**Comment by JCG1090** [comment]
> 
> 
> You need to deal with the 38000+ items that you have in the world. They are what is causing the watchdog timeout.
> From the server console you can try `cu entity remove byType minecraft:item force` to remove them. You do need to find the cause of the spill and fix it, otherwise it will continue to cause issues.
> You can also configure crash utilities to automatically remove dropped items. See it's config in `<world>/serverconfig/crashutilities-server.toml`
> I'd also not recommend setting `max-tick-time` to -1 permanently. It would be better just to add a 0 to make it a 10min timeout rather than a 1 minute one.

Thanks, i think i already know the problem as well someone left their auto farm going when i get near their house ill lag then crash

**Comment by JCG1090** [comment]
> You need to deal with the 38000+ items that you have in the world. They are what is causing the watchdog timeout.
> From the server console you can try `cu entity remove byType minecraft:item force` to remove them. You do need to find the cause of the spill and fix it, otherwise it will continue to cause issues.
> You can also configure crash utilities to automatically remove dropped items. See it's config in `<world>/serverconfig/crashutilities-server.toml`
> I'd also not recommend setting `max-tick-time` to -1 permanently. It would be better just to add a 0 to make it a 10min timeout rather than a 1 minute one.

**Comment by JCG1090** [comment]
> You need to deal with the 38000+ items that you have in the world. They are what is causing the watchdog timeout.
> From the server console you can try `cu entity remove byType minecraft:item force` to remove them. You do need to find the cause of the spill and fix it, otherwise it will continue to cause issues.
> You can also configure crash utilities to automatically remove dropped items. See it's config in `<world>/serverconfig/crashutilities-server.toml`
> I'd also not recommend setting `max-tick-time` to -1 permanently. It would be better just to add a 0 to make it a 10min timeout rather than a 1 minute one.

Thank you that worked, just out of curiosity what type of settings would you use in serverconfig/crashutilities-server.toml?
it seems a bit confusing

**Comment by radiomike** [comment]
In the item clear section, set `enabled = true` to turn it on.
Change `timer = 30` to your preference. It's 30mins by default.
The rest, you can probably leave as is.
