### ISSUE TITLE
The Other RFToolsDimensions

### ISSUE THREAD

**Issue by jebjordan** [AllTheMods/ATM-6#2128]
ModPack Version: 1.7.6 (apparently not latest anymore but still mostly recent)

So, basically: 
RFToolsDimensions researcher won't properly research a biome absorbed which absorbed the biome "The Other" from the other dimension. 

It takes the absorbed block and gives nothing from it. 

Was trying to make an other dim with only the other biome to hopefully find a darn Gordon faster or at all. 

Another thing is that there seems to be no research for any of The Other biomes at all.

**Comment by ladylexxie** [comment]
The biomes will soon be added to the pack.
