### ISSUE TITLE
Simple Server Version 1.7.7 not working for me. 

### ISSUE THREAD

**Issue by Icerlfame** [AllTheMods/ATM-6#2129]
When I attempted to update my simple server for ATM6 to the latest version the code says that an error has occurred while installing the pack the terminal then says Error: Invalid or corrupt jarfile C:\Users\dbara\OneDrive\Desktop\Simple-Server-files-1.7.7 (6)\ installer.jar. next it asks me to accept the EULA and  when responding with TRUE it says unable to access jarfile C:\Users\dbara\OneDrive\Desktop\Simple-Server-files-1.7.7 (6)\ installer.jar and proceeds to restart the server multiple times in failure. I dont know if this problem is originating from my computer or the files themselves but when I took a look in the server-setup-config from a previous version (1.7.6) the only thing that seemed to be different is this part of the code that said https://media.forgecdn.net/files/3401/923/All+the+Mods+6-1.7.6.zip which was now https://www.curseforge.com/minecraft/modpacks/all-the-mods-6/download/3418716. I then procced to change https://www.curseforge.com/minecraft/modpacks/all-the-mods-6/download/3418716 to https://media.forgecdn.net/files/3401/923/All+the+Mods+6-1.7.6.zip in the latest version and the server started to work. The only bad thing about it was that it was not in the correct version since this is the previous version. I believe this is where the problem is. please help :(

**Comment by abslon** [comment]
Change the modpackUrl of the server-setup-config.yaml 
https://media.forgecdn.net/files/3418/716/All+the+Mods+6+-+ATM6+-+1.16.5-1.7.7.zip

**Comment by Icerlfame** [comment]
gs abslon thank you for the help and quick response time
