### ISSUE TITLE
Locked storage drawers don't remember their contents 1.1.7b

### ISSUE THREAD

**Issue by DeathOfTime** [AllTheMods/ATM-6#213]
If all the items are drawn out of a locked storage drawer it will forget what went in it. Might have to reload the chunk for it to fully forget

**To Reproduce**
1. place down some storage drawers and a controller
2. put stuff in them
3. lock them
4. draw the stuff out through the controller (might not need the controller)
not sure after this. might just need to unload and reload the chunk. not sure. i just notice it has happened after i come back to them a little later

**Expected behavior**
locked drawers remember what they had in them

**Comment by Okimo** [comment]
Long time issue in Storage Drawers

https://github.com/jaquadro/StorageDrawers/issues/704

**Comment by DeathOfTime** [comment]
Hasn't seemed to be a issue for a few updates. just wasn't sure so didn't update this, and forgot i put this here. drawers seem to be remembering what should go into them no. even when emptied
