### ISSUE TITLE
Internal Server error on logon after updating to 1.7.7

### ISSUE THREAD

**Issue by SparkyLLK** [AllTheMods/ATM-6#2130]
When trying to login after updating to 1.7.7 disconnected with the reason "Internal Server Error"

Logs - https://pastebin.com/cK8QSAp5

**Comment by Cratios** [comment]
Same here

**Comment by Zoidey** [comment]
Me Two!!!

**Comment by Cratios** [comment]
> When trying to login after updating to 1.7.7 disconnected with the reason "Internal Server Error"
> 
> Logs - https://pastebin.com/cK8QSAp5

Unistall JER (Just enough Resources) on Server. That worked for me

**Comment by Paul0sss** [comment]
> > When trying to login after updating to 1.7.7 disconnected with the reason "Internal Server Error"
> > Logs - https://pastebin.com/cK8QSAp5
> 
> Unistall JER (Just enough Resources) on Server. That worked for me

Worked for me too, thank you very much^^

**Comment by JBar2K** [comment]
> > When trying to login after updating to 1.7.7 disconnected with the reason "Internal Server Error"
> > Logs - https://pastebin.com/cK8QSAp5
> 
> Unistall JER (Just enough Resources) on Server. That worked for me

Thank you. Easier than downgrading.

**Comment by whatthedrunk** [comment]
Thanks. I just submitted new server files that remove JER. They should be approved any minute or you can just manually delete.
