### ISSUE TITLE
Error parsing recipe ... is not a valid ingredient! 1.7.7

### ISSUE THREAD

**Issue by klownz0r** [AllTheMods/ATM-6#2131]
Current version of pack = 1.7.7
Just update from 1.7.6, and when I try to load a save file - game tell me to start in a 'save mode'
Attach the server.log
[server.txt](https://github.com/AllTheMods/ATM-6/files/6950928/server.txt)

kubeJS folder with recipes
[folder.txt](https://github.com/AllTheMods/ATM-6/files/6950935/folder.txt)

**Comment by ladylexxie** [comment]
There is nothing wrong in those logs that is caused by us. Those recipe failures are caused by mod datapacks.
