### ISSUE TITLE
Issue with @Pedestals advanced enchantment

### ISSUE THREAD

**Issue by taubin17** [AllTheMods/ATM-6#2133]
After speaking with the mod developer, I have gotten the advanced enchantment from the Pedestals enchanter. However, when I enchant it on any upgrade from the Pedestals mod, it does not change anything about the upgrade. By default, any upgrade that can receive the "Advanced" enchant has a blurb in red text when you hover over it in your inventory. When enchanted with the Pedestal Advanced enchantment though, the blurb remains, and no stats about the pedestal are changed. I have pictures that can help explain what I mean, but alas I don't know how to share them on here.

**Comment by ladylexxie** [comment]
We don't change anything related to the pedestal or any of the enchants/upgrades. If it still persists, you should report it to Mowmaster.
