### ISSUE TITLE
Error parsing recipe ... is not a valid ingredient! 1.7.7 [PART 2]

### ISSUE THREAD

**Issue by klownz0r** [AllTheMods/ATM-6#2136]
After update from 1.7.6 to 1.7.7 getting error about mod pack when trying load save. Warning give me option to start on safe mode,
I try to repair mod pack with curse forge app, but no luck

**To Reproduce**
1. Go to 'Singleplayer'
2. Click on 'Load game'
3. See error

**Screenshots**
![изображение](https://user-images.githubusercontent.com/77306026/128648910-e30d4eb9-9c4b-47a0-9c5a-2b987e4e7784.png)

**Additional context**
The KubeJS team(?) says what thats not error from them
https://github.com/AllTheMods/ATM-6/issues/2131#issuecomment-894868147

**Logs**
lastest.log
https://gist.github.com/klownz0r/1afafa3040b880999d869542f3a9bfed
server.txt
https://pastebin.com/zWQqTckM

**Comment by Pdiddy973** [comment]
try a fresh install on curse, or use a better launcher like[ GDLauncher](https://gdevs.io/)

**Comment by klownz0r** [comment]
Reinstal with GDLauncher - all works
