### ISSUE TITLE
Rotary Condensator and liquid sulfuric acid

### ISSUE THREAD

**Issue by Quantumpixxel** [AllTheMods/ATM-6#2138]
Version: AllTheMods 6 - 1.7.7
The Rotary Condensator from Mekanism is able to condensate sulfuric acid into a liquid. The problem is that it is also called sulfuric acid and I cannot make a gas out of the liquid sulfuric acid. So every sulfuric acid I liquify cannot be made into gas again and I can't use it anymore.

If you want to reproduce this:
1. Put sulfuric acid from a chemical tank into a Rotary Condensator (Condensentrating Mode).
2. Give it energy and let it liquify it.
3. Try to make a gas again out of the liquified sulfuric acid (Rotary Condensator (Decondensentrating Mode).
4. It will not make a gas again that you can put into a chemical tank or a pressurized tube. It will exactly do nothing and your sulfuric acid liquid can be wasted.

**Screenshots**
![Bild_2021-08-09_132333](https://user-images.githubusercontent.com/88660912/128698991-485d8d73-e631-49a6-a3ac-8f55e4ce984e.png)

**Additional context**
I build a RFTools dimension with sulfuric acid liquid and pumped them with dimensional tanks and the quarry pump modul of the rftools builder into my rs liquid storage system. Then into a mekanism fluid tank and wanted to use the sulfuric acid so i filled my rotary condensator with it but I can't use it, because nothing happened in the rotary condensator. Tried it with every mode of it and most of the input and output configurations. Sadly no other result.

**Logs**
Please use a paste site for logs, instead of putting the file directly in the issue, not only is this easier but also means we can view on mobile when we are not at our computers.
Here's a list of some paste sites and their size limits:
    https://pastebin.com/ 512KB
    https://hastebin.com/ 400KB
    https://gist.github.com/ 100MB Requires member (Free)

**Comment by radiomike** [comment]
Just tested the first part of this and it seems to work fine.

1. take sulphuric acid gas in chemical tank
2. feed into decondensentrator set to condensentrating
3. feed into fluid tank
4. have tank of `liquid:sulfuric acid`
4. take fluid tank and feed into decondensentrator set to decondensentrating
5. feed into chemical tank
6. Have chemical tank of `gas:sulphuric acid`
