### ISSUE TITLE
Rebalance custom Mekanism solar panel recipe

### ISSUE THREAD

**Issue by andrewsf** [AllTheMods/ATM-6#214]
The following [recipe modification](https://github.com/AllTheMods/ATM-6/blob/master/kubejs/server_scripts/modify_recipes.js#L112):

```
modifyShaped('mekanismgenerators:solar_panel', 1,[
    'PPP',
    'RIR',
    'OOO'
    ],{
      P: 'powah:solar_panel_starter',
      R: '#forge:dusts/redstone',
      I: 'mekanism:alloy_infused',
      O: '#forge:ingots/osmium'
    })
```

... is _extremely_ punishing.

It looks like it was an attempt to make Mekanism's `solar_panel` similar to Powah!'s `solar_panel_basic`. But:

* `powah:solar_panel_basic` generates 17 FE/t
* `mekanismgenerators:solar_panel` can only be used (3x) to make `mekanismgenerators:solar_generator`
* `mekanismgenerators:solar_generator` generates 24 FE/t

Thinking in terms of their common ingredient (which is a _pain_ to craft):

* Powah yields **5.6 FE/t** per `powah:solar_panel_starter`
* Mekanism yields **0.9 FE/t** per `powah:solar_panel_starter`

Please either:

* dramatically reduce the crafting cost of `mekanismgenerators:solar_panel` to the same order of magnitude as `powah:solar_panel_starter`
* remove `mekanismgenerators:solar_panel` and change the `mekanismgenerators:solar_generator` recipe to something closer to `powah:solar_panel_basic`.

**Comment by WhitePhant0m** [comment]
It was more so that people wouldn't spam mekanism solars and instead looked at other possible solutions, we kept it so you can use it the recipes and maybe other stuff you'd like to use it for, but mekanism solars are bad for power.

**Comment by andrewsf** [comment]
The logic makes some sense, but *6 times worse* than Powah solar is really harsh. My aim was to stay in the Mekanism realm as long as possible to keep the mod's balance, but I didn't expect the balance to be altered dramatically like that.

I never would have figured it out if I didn't spend ~10 hours acquiring resources and crafting the Mekanism panels to troubleshoot power issues.

Thanks for letting me know it's deliberate. Some sort of in-game or out-of-game guide explaining this would go a long way.

**Comment by faaaaq** [comment]
> Thanks for letting me know it's deliberate. Some sort of in-game or out-of-game guide explaining this and pushing players toward other mods would go a long way.

Searching in JEI for "solar" you can see all tiers of all solar panels, their performance, and their build requirements.  Is that not enough?

**Comment by alaa13212** [comment]
Mekanism advance solar generators are not just for generating power. They are used as a crafting component as well. They are used for Thermal Evaporator and needed for Solar Recharging Unit for the MekaSuit

Upgrading the MekaSuit with solar recharging costs 3456 Lapis and 5328 Dielectric instead of 288 glass pane
By the time I got to the MekaSuit these resources are not much but it still seems too unbalanced
