### ISSUE TITLE
Several quests broken in Creative tab [1.7.7]

### ISSUE THREAD

**Issue by IcewaveGaming** [AllTheMods/ATM-6#2140]
**Describe the bug**
In ATM6 1.7.7, there are four quests in the Creative tab that are broken. The two creative tinkers construct items have no recipe, and the AIOT quests display a purple square with a question mark. Clicking on the question mark, or the Alfsteel AIOT in the quest for it, will cause a popup to display in the corner saying "Item not found, report this bug to the modpack author."

**To Reproduce**
1. Go to the Creative Tab
2. Click on the Tinkers Construct creative items and the Botania AIOT quests
3. See error

**Screenshots**
N/A

**Additional context**
Clicking on the AIOTs multiple times will cause a crash.

**Logs**
N/A

**Comment by ladylexxie** [comment]
This is a known issue and is already fixed in dev version. The update will come when Centrifuges can be fixed as well.
