### ISSUE TITLE
Crash on teleport

### ISSUE THREAD

**Issue by FoamToaster** [AllTheMods/ATM-6#2141]
**Describe the bug**
Intermittent crash on teleport (either with waystone) or with /home
Freezes, then quits MC
On latest version 1.7.7

**To Reproduce**
Intermittent crash on teleport (either with waystone) or with /home

**Logs**
https://pastebin.com/GP6CF3xT
https://pastebin.com/hkxHZanE

**Comment by jetwest2000** [comment]
Ive been having this problem too, I thought it was just me.

**Comment by pbean8** [comment]
If I am correct, I had the same issue and talked to a mod about it. Its a Flywheel issue with rendering. Just update your flywheel to this version https://www.curseforge.com/minecraft/mc-mods/flywheel/download/3413670

**Comment by Pdiddy973** [comment]
updating to the current pack version should resolve this
