### ISSUE TITLE
Request for clone of Allthemodium for ATM 6 1.7.7

### ISSUE THREAD

**Issue by officialnerdfire** [AllTheMods/ATM-6#2143]
I would like to change the fake player check in the allthemodium mod in the ATM 6 pack for personal use in my ATM 6 play through with me and my bud. I quite enjoy using the digital miner to auto collect ores and while I can understand it being intended on your end, it would be nice to have it be configurable. Since I already saw a question asking for this where I'm fairly sure a config for it won't be made, at least not anytime soon as you guys have more pressing issues, I'd be more than happy to just do it myself. Thanks for your consideration.

**Comment by thevortex** [comment]
feel free to use cursemaven and make yourself a mixin to change the necessary bits, and share that with your bud, forking and creating your own distribution of the mod itself wont be happening tho, sorry
