### ISSUE TITLE
How to make server files call Java 8? 1.7.7

### ISSUE THREAD

**Issue by Icerith** [AllTheMods/ATM-6#2145]
I want to run a server for ATM 6 1.7.7, but I also run a vanilla server for 1.17 on the same rig. 1.17 needs Java 16 to work and I use Java 8 to play modded. MultiMC lets me switch between the two fairly easily, so that was never an issue, but now it is when I try to run the startserver.bat as it keeps trying to call Java 16.

Removing Java 16 isn't really an option as most of my players play on the vanilla server, but about half of them want to play modded. Is there any way to make startserver.bat call for a specific version of Java on my PC? Maybe an edit to the .bat file that I'm just unaware of? If not, I appreciate the help anyway. 👍

**Comment by radiomike** [comment]
You can have multiple java versions installed, then set a path to the required java in the `server-setup-config.yaml` file.
