### ISSUE TITLE
Problem with Environmental Tech Solar Array.

### ISSUE THREAD

**Issue by Furious1964** [AllTheMods/ATM-6#2148]
Made a complete Tier 2 Array and it doesn't work. Have all Erodium parts. Is this a known problem?

**Comment by radiomike** [comment]
Where did you make it? I don't think they work in some dimensions.

**Comment by radiomike** [comment]
They should work in the overworld, but only generate during the day. They don't work in the mining dimension.
Did the multi-block form?
