### ISSUE TITLE
Downgrade FTBChunks

### ISSUE THREAD

**Issue by th2m1** [AllTheMods/ATM-6#2149]
Hi,
current FTBChunks ver. completely breaks previous worlds for servers - people lost their claims etc,
also there is no way to add friends to the claim (ftbteams still too buggy).
May be downgrade to 2.x ver?

**Comment by ladylexxie** [comment]
We cannot downgrade, losing claims was mentioned in the changelogs for ATM along with quest resets.
You can add people to your team by using the `ftbchunks` command, and then ally party.
