### ISSUE TITLE
Totem of undying recipe

### ISSUE THREAD

**Issue by DerShendi** [AllTheMods/ATM-6#215]
Id wish for a recipe to be added for totems of undying bec some servers have this pack on easy which makes it impossible to get the totem of undying without lagging the server to oblivion by looking for a mansion

IMO the recipe should be like this 
![totem recipe](https://user-images.githubusercontent.com/51245094/97047639-992cac80-1579-11eb-93c9-9bf16c7c83d0.png)
The spawn egg is a villager spawn eggand the emerald block is 3x compressed which makes it a (not so) viable (but still easy achievable) way to get totems if the server is on easy mode without crashing the server by looking for hours for it
And since the uncrafting grinder is disabled theres no real way to abuse that

**Comment by WhitePhant0m** [comment]
added
