### ISSUE TITLE
Crash when creating a world

### ISSUE THREAD

**Issue by WooTech13** [AllTheMods/ATM-6#2151]
My game crash when I try to create a superflat world in creative and it doesn't when I create a default world.
Here is the crash log :
[crash-2021-08-12_15.28.55-client.txt](https://github.com/AllTheMods/ATM-6/files/6975880/crash-2021-08-12_15.28.55-client.txt)
Also, the game freeze when I try to create a Floating Islands world but I don't have a crash log.

**Comment by NakedGranny** [comment]
This is happening to me, as well. Attempting to generate a new world, no matter what settings, it will begin to generate the world and then at some point it will simply halt. Always before 50% and never will progress no matter how long you let it sit. It's not doing anything, it isn't just taking a long time to complete. It's just sitting idle and will never complete.

**Comment by ladylexxie** [comment]
Cannot reproduce, seems to have something to do with authentication. let us know if it still happens in the latest version.

**Comment by NakedGranny** [comment]
Seems to still be happening.

I'm not sure what you mean by authentication.
