### ISSUE TITLE
My game is really slow

### ISSUE THREAD

**Issue by Sunlord330** [AllTheMods/ATM-6#2153]
When ever I turn/walk (basically anything) the game freezes for a solid 30 seconds

**Comment by TheLittleCube** [comment]
Lets hit a few things first. 

Has your pc had issues with large modpacks before? 
if so downgrade your settings.. Render/loaded chunks.

Did you remember to allocate enough ram?
Your pc slowing down is a normal symptom of garbage collection running in the background.

**Comment by Sunlord330** [comment]
sorry for not responding to u fast enough, but to answer your questions I have played crazy craft 4 and it never froze and I put everything on the minimal.I don’t have my specs memorized right now

**Comment by ladylexxie** [comment]
- Do you have the minimum 8GB recommended ram allocated?
- Are you using the correct Java Args?
- Do you have your mipmaps set to 0 and vsync off?
