### ISSUE TITLE
CRASH: Rendering Block Entity

### ISSUE THREAD

**Issue by nmorgus** [AllTheMods/ATM-6#2154]
**Describe the bug**
I was disconnected from the server when i picked up my backpack.

This is the error code that appeared when I returned to the launcher:
```
The game crashed whilst rendering block entity
Error: java.lang.NullPointerException: Rendering Block Entity
Exit Code: -1
```

**To Reproduce**
Every time I sign into the server, I get a save game message, and then the game crashes.

**Additional context**
Other members of the server are able to sign in but when they go into the area on the map where I was disconnected, they are also disconnected.  In order to remedy, I have to delete the player file from the server files.

Please feel free to reach out to me for any additional information needed.

Attached is the Crash Report
https://pastebin.com/tM3C0TFc

**Comment by radiomike** [comment]
This is a known issue with sophisticated backpacks and tinkers construct.
It's fixed in the latest version of that mod, so you should either update the modpack, or the sophisticated backpacks mod.

**Comment by nmorgus** [comment]
@radiomike thanks for letting me know!
