### ISSUE TITLE
[Bug][1.7.7]Ars Nouveau: Grow Spell on Overgrown Stone Causes Server Crash

### ISSUE THREAD

**Issue by Xeavior** [AllTheMods/ATM-6#2157]
I have been able to repeatably cause my ATM6 Server to crash by using an Ars Nouveau projectile grow spell on Overgrown Stone.

Edit: The issue was occurring through the sapling and on overgrown stone, corrected the title to reflect the issue.

**Comment by radiomike** [comment]
See <https://github.com/baileyholl/Ars-Nouveau/issues/329>
