### ISSUE TITLE
End Dragon and associated portal did not spawn.

### ISSUE THREAD

**Issue by Sakata-MC** [AllTheMods/ATM-6#2159]
Downloaded ATM6-1.7.7, installed, and created a new world. Went to End and there was no ender dragon, nor was the bedrock portal frame generated.

Noted in NBTExplorer that the level.dat\Data\DragonFight key had DragonKilled and PreviouslyKilled values set to 1.  
Changed them to 0, deleted the DIM1 folder, and tried to enter the End again.
This time the Dragon's HP bar acame up (no portal frame spawned though). Dragon seemed to have spawned very far away as it took several minutes before it actually showed up and started it's normal attack patterns.
Figured it'd just generate the frame after killing it, which it did, though with some blocks ghosted.
Hopped in the portal entity that did render correctly, and then came back to the End to make sure it generated correctly, which it had.

I'm not sure if perhaps Ice and Fire had something to do with it, as that seems to be the common find in Google.
Haven't been able to replicate it since, though.

**Comment by Xplodin** [comment]
Also have this issue, Im gonna try to reset the end via the old fix and see if that fixes it
