### ISSUE TITLE
Performance stuff

### ISSUE THREAD

**Issue by DerShendi** [AllTheMods/ATM-6#216]
Me and a lot of players are having this issue that Minecraft goes to "not responding" mode for a few seconds and it then times us out 
And for me specifically I have to restart the game every time i time out or i cant join the server again (please don't say ReAuth i know how it works its not that)
so if possible please can you do smth about it??
I even added optifine and turned everything down to minimum just so it happens less but with every update it keeps happening more frequent
Dunno what to say maybe its just Ram or smth but I'm not sure what the fault may be here (ive put 6gb ram on it even thou MC says its only 5.5 but ok)

**Comment by CornInMyLife** [comment]
I have same problem too even i gave the game 6.5GB out of 8GB i know people have 16GB and gave the game 8GB and 10GB but same too

**Comment by faaaaq** [comment]
My crew has no such issues, and I let my client run with 5.9gb and the server itself runs on 10.  You can't expect anyone to do anything when you have given them no real information to go off of.  Post a specific error, or your logs, or the server console output, anything.  Literally anything other than it says "not responding" ha.

**Comment by ViRb3** [comment]
Server is overloaded from bug in MoreRed mod, fixed in new version. #259
