### ISSUE TITLE
Environmental Tech Miner - Not Gathering like it should, ATM Metals

### ISSUE THREAD

**Issue by taz1009** [AllTheMods/ATM-6#2164]
I've got a tier 8 void miner and it doesn't seem to be getting any Allthemodium Vibranium or Unobtainium. As well as that it doesn't seem to be getting any ancient debris either, I've also noticed a lack of the Crystals of the top tier.

I've got the interdimensional modifier on it as well but doesn't seem to be gathering any, I also have it set to full multiminer mode

This is my setup of the miner, see image : [http://prntscr.com/1pnta1z](url)

**Comment by radiomike** [comment]
Have you put in the correct colour lenses?

**Comment by taz1009** [comment]
I'm guessing there has been an update, as nothing mentions the lenses or what they do.

**Comment by radiomike** [comment]
It was implemented in atm6-1.7.1, although the I don't think the changelog included everything.
For Gameplay related questions I'd recommend asking in the atm-6 discord <https://discord.gg/K5FBPYa>

**Comment by Calvinishere3** [comment]
Im pretty sure its an intentional gameplay thing to not let miners automate mining ATM ores as the same thing happens with digital miner, builder quarry, and quarry plus

**Comment by Pdiddy973** [comment]
the void miners can mine the ATM ores witht he lenses and starting at tier 3
