### ISSUE TITLE
Can't install, child addons missing.

### ISSUE THREAD

**Issue by req-not-available** [AllTheMods/ATM-6#2167]
There's really not much explain, it doesn't allow me to install and says these mods are missing:
309674 Item Filters
368293 Repurposed Structures

**Comment by Vynessia** [comment]
I'm having the same issue as well. The modpack always fails to install after it cannot find child addon file: 3407458

**Comment by Ashawyn** [comment]
Same exact issue. 

"Cannot find child addon file: 3407458"

I have uninstalled both Curseforge, Overwolf, AND Minecraft. I even went in and deleted all temporary files, appdata files, and restarted my computer. Still getting the same error.

**Comment by ChungoHuncho** [comment]
having same problem

**Comment by jeremiahwinsley** [comment]
I have tested in another launcher (MultiMC), and it installed successfully. This seems to be a Curseforge problem, which we cannot fix - you'll have to wait for them to fix it.

**Comment by IAmSkidd7** [comment]
Having the same issue, anyone know the cause?

**Comment by Ashawyn** [comment]
> Having the same issue, anyone know the cause?

Jeremiah is right. It's a Curseforge problem. MultiMC works just fine.
