### ISSUE TITLE
Exit Code: 0 after trying to run the game

### ISSUE THREAD

**Issue by FuzzyM0nst3r** [AllTheMods/ATM-6#217]
When I try to run the pack i get this screen seconds after it crashes, it doesn't get to the loading screen.

![code 0](https://user-images.githubusercontent.com/46351054/97084113-9e870700-160c-11eb-902a-6a4f00e54047.png)

this is a copy of the debug report: 

15:23:33.459
Preparing to launch minecraft client for forge-34.1.25
15:23:33.958
Couldn't fetch SHA1 checksum for https://s3.amazonaws.com/Minecraft.Download/versions/1.16.3/1.16.3.jar
15:23:33.959
Have local file C:\Users\Fuzzy M0nst3r\Twitch\Minecraft\Install\versions\1.16.3\1.16.3.jar but don't know what size or hash it should be. Have to assume it's good.
15:23:33.960
Checking installations.
15:23:33.961
Minecraft client forge-34.1.25 is ready to start.
15:23:33.961
Starting!
15:23:34.504
Using default game log configuration client-1.12.xml (outputs XML)
15:23:35.184
ModLauncher running: args [--username, FuzzyM0nst3r, --version, forge-34.1.25, --gameDir, C:\Users\Fuzzy M0nst3r\Twitch\Minecraft\Instances\All the Mods 6 - ATM6 - 1.16.3, --assetsDir, C:\Users\Fuzzy M0nst3r\Twitch\Minecraft\Install\assets, --assetIndex, 1.16, --uuid, {TOEKN DELETED}, --accessToken, ❄❄❄❄❄❄❄❄, --userType, mojang, --versionType, release, --width, 1024, --height, 768, --launchTarget, fmlclient, --fml.forgeVersion, 34.1.25, --fml.mcVersion, 1.16.3, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200911.084530]
15:23:35.188
ModLauncher 7.0.1+78+master.e9771d8 starting: java version 1.8.0_51 by Oracle Corporation
15:23:35.614
Added Lets Encrypt root certificates as additional trust
15:23:35.669
SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/Fuzzy%20M0nst3r/Twitch/Minecraft/Install/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=CLIENT
15:23:36.791
Failed to find Minecraft resource version 1.16.3-20200911.084530 at C:\Users\Fuzzy M0nst3r\Twitch\Minecraft\Install\libraries\net\minecraftforge\forge\1.16.3-34.1.25\forge-1.16.3-34.1.25-client.jar

Any help to get the pack running would be great as i want to play this on stream :)

**Comment by WhitePhant0m** [comment]
use a different launcher or change file path to one with no spaces in it

**Comment by FuzzyM0nst3r** [comment]
> use a different launcher or change file path to one with no spaces in it

How do I use a different launcher? and what other launchers are out there?

Also all my other mod packs run even with a space in the file path

**Comment by DrunkTaank** [comment]
My gut says that this is a bug in the twitch launcher, as it happens with several other 1.16.x packs.  I've tried reporting it there, but to no avail.  I have since moved over to MultiMC.  You don't have to use that one, but if you do, you just need to download the pack zip file, then import it into the MultiMC launcher.
