### ISSUE TITLE
Unable to open worlds

### ISSUE THREAD

**Issue by Coiled355** [AllTheMods/ATM-6#2171]
Pretty decent pc but the game won’t open any worlds. It gets stuck after “Reading World Data”

**Comment by radiomike** [comment]
How much ram did you assign to the game in your launcher?

**Comment by Coiled355** [comment]
Xmx8G and Xms4G

**Comment by radiomike** [comment]
That should be fine. When you say it's stuck, how long are you leaving it?

**Comment by Paddingtonnn** [comment]
Also happening to me. I've had no issues running the pack normally, but it crashed to desktop suddenly yesterday and now I can't load that save. Will spend several minutes on "Reading world data", get to 100% loading, and then crash to desktop. launcher just gives me exit code 0. 
I just tested creating a new world and that does work however.

**Comment by ladylexxie** [comment]
upload your `latest.log` to pastebin or github gist and put it here. There should be an indicator there.

**Comment by Paddingtonnn** [comment]
here you go
[latest.log](https://github.com/AllTheMods/ATM-6/files/7010883/latest.log)

**Comment by Paddingtonnn** [comment]
sorry, didn't read properly. here's the actual link
<script src="https://gist.github.com/Paddingtonnn/8b18d1782353a50e3da272581760a24f.js"></script>
