### ISSUE TITLE
There is a Trojan in the 1.7.8 update?

### ISSUE THREAD

**Issue by Dr-Tarantula** [AllTheMods/ATM-6#2179]
The file was downloaded with the newest update. Please tell me this isn't intentional. If it isn't actually intentional please get rid of it. The file is Trojan:Script/Wacatac.B!ml. If I am getting a false positive then sorry.
![Trojan Info](https://user-images.githubusercontent.com/89165217/129975115-065fb348-7c38-4b1d-bc51-386147dfbf29.PNG)

**Comment by Paper-28** [comment]
Same problem, can´t upgrade from 1.7.7 to 1.7.8 via curseforge client

**Comment by Sakata-MC** [comment]
Before submitting a potentially erroneous virus report, it would be much more productive for you, the devs, and other users if you'd submit the potentially 'infected' file to virustotal.com and provide the resultant link.

This screenshot points to a temporary file, which provides no actionable information to anyone.

Additionally, I have just downloaded and scanned the release as distributed via curseforge and no detections are listed:
https://www.virustotal.com/gui/file/f24efcb0c906ceae0c0ff187c386c1dc81344a5b56e4a439b5c5ad1a1f3ebcd6/detection

**Comment by Dr-Tarantula** [comment]
> Before submitting a potentially erroneous virus report, it would be much more productive for you, the devs, and other users if you'd submit the potentially 'infected' file to virustotal.com and provide the resultant link.
> 
> This screenshot points to a temporary file, which provides no actionable information to anyone.
> 
> Additionally, I have just downloaded and scanned the release as distributed via curseforge and no detections are listed:
> https://www.virustotal.com/gui/file/f24efcb0c906ceae0c0ff187c386c1dc81344a5b56e4a439b5c5ad1a1f3ebcd6/detection

I would like to clarify that my antivirus is the thing that flags it. I am not the most tech-literate person. How do I get the temp file and submit it. I had to click quickly to look at the info before the file was deleted. I don't know what I am doing so further clarification would be awesome.

**Comment by Sakata-MC** [comment]
It is possible that the curseforge launcher or the platform itself is doing something to the file and causing the issue. It could even be that the Curse platform itself has been infected. If you're not confident of your technical aptitude to isolate the file and send it to virustotal, I'd advise that you either: hold off on updating (there are a few recipe bugs that will break progression in Mekanism, possibly others), or download an alternative Minecraft launcher.

I personally recommend MultiMC, but some people prefer the ATLauncher.

**Comment by ladylexxie** [comment]
I find it hard to believe that there's something wrong with the file, we are looking into it, but CF also does manual approval of every single file uploaded.

**Comment by ladylexxie** [comment]
It is confirmed to be a false positive.
