### ISSUE TITLE
Server crash with error Entity being ticked ars_nouveau:whelp

### ISSUE THREAD

**Issue by TheThirdBeast** [AllTheMods/ATM-6#218]
**Describe the bug**
The server crashes when a whelp is running with the spell touch-> interact and then adding ender hopper anywhere in his workable area (We suspect, but really hard to pinpoint)

**To Reproduce**
1. Have a whelp running with the spell touch-> interact 
2. add ender hopper anywhere in his workable area 

**Expected behavior**
Not a hard crash
[crash-2020-10-24_15.49.56-server.txt](https://github.com/AllTheMods/ATM-6/files/5433177/crash-2020-10-24_15.49.56-server.txt)

I have included the latest crash report. I started seeing this behavior since ATM6 1.1.7b but it might just be that the conditions were not met before.

**Comment by Pdiddy973** [comment]
ender hopper was disabled
