### ISSUE TITLE
AE2 Inscriber Silicon Press impossible to make?

### ISSUE THREAD

**Issue by Calvinishere3** [AllTheMods/ATM-6#2185]
For the inscriber silicon press the recipe needs AE2 silicon and only AE2 silicon which the recipe for is missing as far as im aware there's no way to make it without AE2 silicon, I think the recipe is just missing the proper forge tag.
Edit: forgot to mention im on game version 6-1.7.6

**Comment by radiomike** [comment]
Tested in 1.7.9 and the inscriber works with refined storage silicon.

**Comment by Calvinishere3** [comment]
I checked the latest version and saw that they changed the recipe to something more functional (and painful to get) so apologies for not knowing that
