### ISSUE TITLE
mismatched mod channel list

### ISSUE THREAD

**Issue by Snackm1x** [AllTheMods/ATM-6#2188]
Hello,

I installed the newest version 1.7.9 on my server, and locally. When I try to join the server I get the message "mismatched mod channel list".

I have attached the logs from both server and client, was curious how I could resolve these so my friends and I could play.

Client:
[latest.log](https://github.com/AllTheMods/ATM-6/files/7015911/latest.log)

Server:
[latest.log](https://github.com/AllTheMods/ATM-6/files/7015920/latest.log)

**Comment by radiomike** [comment]
Looks like your server hasn't got any mods on it. You should reinstall the server pack, or make sure you are running it correctly.

See <https://github.com/AllTheMods/ATM-6/wiki/Pack-Upgrade-FAQ> for a guide

**Comment by Snackm1x** [comment]
Oh wow that's silly. I must have borked something on the install. I did roll back to 1.7.7 and got that to successfully run. So I'll give the newest version a shot again. Thanks!
