### ISSUE TITLE
Iron Furnace mod causing heavy lag

### ISSUE THREAD

**Issue by twothe** [AllTheMods/ATM-6#2189]
The Iron Furnace mod has a bug that causes it to run through all recipes on every tick for every furnace, which causes heavy lag. 

A fix is in progress, please watch: https://github.com/Qelifern/IronFurnaces/issues/58

**Comment by Qelifern** [comment]
ironfurnaces-1.16.5-2.7.0 has been tested and is now up on curseforge. 👏

**Comment by ladylexxie** [comment]
It is now added in 1.7.10 version of the pack. Will be released tonight.
