### ISSUE TITLE
Autoplaced blocks are invisible

### ISSUE THREAD

**Issue by wakallll** [AllTheMods/ATM-6#2198]
pack version: 1.7.8

Blocks that are auto placed into the world via a wand or other such tool appear invisible. The blocks are there, you cant walk through them, but you also cant interact with them. Restarting the world, relogging into the server, or in some cases placing a block where the invisible block is will have them reappear. 

**To Reproduce**
The easiest way to reproduce this is with mine colonies
place any building core down, town hall, house, builders hut, anything, it can even be the supply camp
With the building cores, the cores or the construction tape wont appear
with the supply camp, a random assortment of building parts will appear

The builders placing the block have no issues, only the initial set down.

**Screenshots**
the blocks are invisible and dont show up with jei when you look at them so there's no real point in screens

**Additional context**
Im not sure if this works with any other supported mod, but I added a mod called immersive railroading and its dependencies, and it has the same issue where placing the tracks using the auto placer has them refusing to render, so i can only assume other mods that have auto placing does the same.

**Logs**
No logs generated as far as im aware, if theres a place that log every block placement and their statuses, or any log in general that you need I will get.

Im using an Nvidia Gforce 2080
Driver version 471.68

**Comment by ladylexxie** [comment]
If the issue is still persisting, it should be reported to the devs of the wand or the mod you're using to place them.
