### ISSUE TITLE
[request] Disable the Enchantment Applicator Limit

### ISSUE THREAD

**Issue by jebjordan** [AllTheMods/ATM-6#2199]
Basically, limited enchantments are just silly. Let's go back to how it was previously with the enchantment applicator, if you wouldn't mind!

If at all possible, I'd like the enchantment applicator enchant limit to be disabled. In other words, to go back to how it was previously, where if you had enough of the liquid, the sky was the limit. It wasn't a problem, so yeah. Any way you could do it? It's just a config change.

Solution: disable the limit in the Industral Foregoing enchantment applicator config.

--
The previous behaviour was absolutely fine, honestly.

**Comment by ladylexxie** [comment]
Fixed in #2206

**Comment by jebjordan** [comment]
Oh right. Forgot I made this pr.
Thanks by the way!
