### ISSUE TITLE
Fluid extractor breaks block texture

### ISSUE THREAD

**Issue by daniel124356** [AllTheMods/ATM-6#22]
How to recreate: if you place a Fluid extractor from Industrial Forgoing next to a block, when it starts to extract "fluid" and the texture changes to like when you're breaking a block if you destroy the block while its extracting the fluid and then remove the fluid extractor, If you place a block when the block you were extracting, the texture is still the same when it was breaking, Photo has been attached for reference

Edit: Is on server

![2020-07-25_16 00 33](https://user-images.githubusercontent.com/29456479/88452353-90e8a680-ce90-11ea-826d-6848b1714048.png)

**Comment by oly2o6** [comment]
if this issue has not been fixed in the recent update, please foward this issue to the industrial foregoing github
