### ISSUE TITLE
Allthemodium cannot be processed in crusher?

### ISSUE THREAD

**Issue by demethan** [AllTheMods/ATM-6#220]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Crusher recipe for the ore Allthemodium.

**Describe alternatives you've considered**

**Additional context**

**Comment by puppydemon20** [comment]
If you are referring to the Crusher from Mekanism, that is the incorrect block, you have to use the enrichment chamber.

**Comment by WhitePhant0m** [comment]
^

**Comment by demethan** [comment]
I am referring to the Immersive Engineering Crusher. It voids the ore instead of doubling it.

**Comment by WhitePhant0m** [comment]
oh, hmm... i heard that IE was voiding stuff instead of actually giving drops, does it work for any other ores or items?

**Comment by WhitePhant0m** [comment]
ah, i see, i haven't added those recipes, thought jaopca would handle it, apparently not. I'll add them soon:tm:
