### ISSUE TITLE
Many "Structurize" Items disappeared from JEI. ATM6 v.1.7.9

### ISSUE THREAD

**Issue by RaxtusPrime** [AllTheMods/ATM-6#2200]
Version 1.7.9
With the latest update from 1.7.8 to 1.7.9
Many of the blocks from the Structurize mod have disappeared from JEI search function.
(Eg. Oak Paper Wall Timber Frame, Oak Cobble Timber Frames, etc.)
Many of these building blocks are used in the Minecolonies build plans and have become impossible to find. The recipes still exist in JEI, but cannot be found with the search bar.

**Comment by ladylexxie** [comment]
They were hidden to reduce clutter, but a version of each block still shows up to show people how to make them.
