### ISSUE TITLE
World tool tips displayed in the middle of the screen

### ISSUE THREAD

**Issue by TozTW** [AllTheMods/ATM-6#2201]
Version 1.7.9 - once it was updated from 1.7.8 to .9, the tooltip is now centered in the middle of the screen rather than at the top, for some reason.

I can't figure out what mod does this, as I thought it was WAILA but shortcuts for it don't work. Any tips/fixes?

![image](https://user-images.githubusercontent.com/89275620/130283846-b4096f7a-a9c7-4fcc-88e5-2d302ffd4600.png)
![image](https://user-images.githubusercontent.com/89275620/130284098-ce5e5ba1-fb1f-4115-a1cf-3672ec3f66cb.png)

**Comment by ladylexxie** [comment]
You can do `/top config` to change it. There will be a hotfix for some other changes as well soon.
