### ISSUE TITLE
[1.7.10] Tojan script

### ISSUE THREAD

**Issue by BefuddledSloth** [AllTheMods/ATM-6#2205]
Attempted to update from 1.7.9 in the Curse launcher and received a trojan.

Trojan:Script/Wacatac.B!ml

in file: C:\Users\<user>\AppData\Local\Temp\CF\YVZ9HcuP6EViAd7R6u9qA\1.zip

This may be a false positive, but the update should be taken down until fixed.

**Comment by Hadoukanen** [comment]
Downloaded it through CurseForge app. Windows Defender went berserk on it. Tried through MultiMC, same thing. Truned off Defender and downloaded manually and then uploaded it to VirusTotal and it found nothing on any of the scanners not even on the MS one. No idea whats up with Windows Defender. But should probably wait to use it until pack creators have had a peek at it.

**Comment by Megaprr** [comment]
I am also having this issue. Haven't tried it without Defender enabled, but I want to avoid that until its verified.

**Comment by Pdiddy973** [comment]
This is a false positive, see the other issues that have been closed.

**Comment by Megaprr** [comment]
Okay, thank you.
