### ISSUE TITLE
1.7.9 and 1.7.10 - Void Miner tier 1 using insane amounts of power

### ISSUE THREAD

**Issue by koekwau5** [AllTheMods/ATM-6#2208]
Since 1.7.9 the Void Miner tier 1 running the Multi Miner - Crystal Miner program uses insane amount of power, 18K RF/t.
More information here on the All The Mods reddit: https://www.reddit.com/r/allthemods/comments/p7si2t/179_void_miner_power_usage_increase/

**Comment by ladylexxie** [comment]
This will be fixed soon, it is an unintended effect of a change we made for Allthemodium.
