### ISSUE TITLE
1.7.9 and 1.7.10 - Recipes Structure Frames for Void Miners are gone and possibly more

### ISSUE THREAD

**Issue by koekwau5** [AllTheMods/ATM-6#2209]
Beside the power issue you can't craft the Structure Frames for all tiers anymore.
Possibly more recipes are missing but don't know for shure, ain't that far in ATM6 yet.

**Comment by radiomike** [comment]
The recipes are there, they are just hidden in JEI at the moment.
Looks like the script that's hiding them hid a bit more than was intended.

**Comment by koekwau5** [comment]
Ahh thanks for the information.
Is there any way to unhide them for the time being?

**Comment by radiomike** [comment]
Sure, you can edit `kubejs/client_scripts/jei_removals.js` to comment out some lines so they look like.

```  //enviroStonesCore.forEach(stone => {
  //  e.hide(`/envirocore:${stone}_.*/`)
  //})
  //enviroStonesMats.forEach(stone => {
  //  e.hide(`/enviromats:${stone}_.*/`)
  //})```

**Comment by koekwau5** [comment]
Sweet that there is a fix, thank you!
One question tho, I'm running a multiplayer server and I'm joining as client.
Do I have to do the server side as well? Don't want to kill my server by my wrong doing ghehe.
Thanks again!

**Comment by radiomike** [comment]
I don't think you have to change the server too, as that's a client script. But, it's not a bad thing to do both, at least you end up with a backup of it just in case.

**Comment by koekwau5** [comment]
> 
> 
> Sure, you can edit `kubejs/client_scripts/jei_removals.js` to comment out some lines so they look like.
> 
> ```
>   //  e.hide(`/envirocore:${stone}_.*/`)
>   //})
>   //enviroStonesMats.forEach(stone => {
>   //  e.hide(`/enviromats:${stone}_.*/`)
>   //})
> ```
> 
> Then restart the game.

Tested the above and is working like a charm!
Thanks alot!

**Comment by koekwau5** [comment]
Fixed in .11 so this can be closed. Do note: power issue still there!
