### ISSUE TITLE
1.1.8 Can't pull items from Energizing Orb

### ISSUE THREAD

**Issue by Kurokujo** [AllTheMods/ATM-6#221]
Since updating to 1.1.8, items can't be pulled from the Energizing Orb. Items can still be pushed or clicked into the Orb, but can only be removed with a right click (empty hand).

Tested all sides with various transport methods including modular routers, hoppers, logistical transporters, etc.

**Comment by WhitePhant0m** [comment]
I can't seem to replicate this
https://i.gyazo.com/3bb29fcb08b2a314a93c0c11d0d8a593.mp4

**Comment by zh4ng** [comment]
Hello all,
I have the following problem:
I want to import items from an Energizing Orb with an Importer from Refined Storage. The importer sits under the orb.

In a new world (ATM6 1.6.14) the import does not work!
I have copied an old ATM6 world onto the server and the import works there.

I have also placed a hopper under the orb, unfortunately this does not work either. 

It looks like this is a very rare bug.
