### ISSUE TITLE
V1.7.10 Pure Ore Chunks wont process in enrichment chamber

### ISSUE THREAD

**Issue by fusionbolt18** [AllTheMods/ATM-6#2210]
**Describe the bug**
Pure ore chunks no longer work in the enrichment chamber despite JEI saying that they do.

**To Reproduce**
1. get pure ore chunk
2. put inside of an enrichment chamber
3. watch it not process

**Screenshots**
![image](https://user-images.githubusercontent.com/59746107/130330713-2238554f-1c1d-4b32-b08f-8effc7cb5ad1.png)
![image](https://user-images.githubusercontent.com/59746107/130330729-22c59473-663d-4322-bbdc-1f1efbc2aecf.png)

**Additional context**
It worked in version 1.7.9

**Comment by ladylexxie** [comment]
I have spoken with the EC mod author and he will have this fixed in a future version.
