### ISSUE TITLE
All Pipes are to slow (ATM6 Skyblock)

### ISSUE THREAD

**Issue by XiNaru** [AllTheMods/ATM-6#2211]
I wanted to automate the sieving.

But regardless of whether I take the Xnet pipes or the Mekanism Transporter, it's too slow. The Auto-Heavy Sieve overflows very quickly and the excess drops onto the floor.

**Comment by kkjdroid** [comment]
Which tier of Logistical Transporters are you using? The Ultimate ones are very fast, but they require several different resources and several different machines. Xnet pipes are pretty slow by comparison, "only" two stacks per second. You might have success with pipes from Cyclic if you can't get the higher-tier Mekanism ones.

**Comment by XiNaru** [comment]
> Which tier of Logistical Transporters are you using? The Ultimate ones are very fast, but they require several different resources and several different machines. Xnet pipes are pretty slow by comparison, "only" two stacks per second. You might have success with pipes from Cyclic if you can't get the higher-tier Mekanism ones.

sorry no
i tried the ultiomate in creative but it doesn't work. nevertheless it only sucks 1 stack per second (which xnet can also do) and that is too slow for sieving.

**Comment by ladylexxie** [comment]
Please report this on [ATM6 Sky github](https://github.com/AllTheMods/atm6-sky/issues)
