### ISSUE TITLE
Cannot find child addon: 399558

### ISSUE THREAD

**Issue by Shyrshadi** [AllTheMods/ATM-6#2212]
I am trying to download ATM6 version 6-1.7.10 released 8/20/2021 but the download ends with 

![image](https://user-images.githubusercontent.com/25585037/130332529-5b465552-9ee2-456d-9fde-3a7cbdead528.png)

I'm trying to download through CurseForge if that matters.

Looking forward to a fix <3

[edit] the previous version is also having an issue with the missing addon.
[edit2] The issue appears at mod number 156. It completes 155 and then can't continue.

**Comment by compulshun** [comment]
Having the same issue.

**Comment by ArchitectBlasen** [comment]
Add 2 more people to this list - I'm trying to get my group set up, and 2 of us are getting this error

**Comment by killnme** [comment]
Also having this issue. Cant download ATM6 or most other mods.

**Comment by Enzos22** [comment]
Same problem on ATM6

**Comment by Shyrshadi** [comment]
> Also having this issue. Cant download ATM6 or most other mods.

**Comment by Shyrshadi** [comment]
> > Also having this issue. Cant download ATM6 or most other mods.

idk how i closed that, started to reply and changed my mind.

Was going to ask what other mods you couldn't open because if its a larger issue than just a mod pack it might make things easier to fix.

**Comment by killnme** [comment]
> > > Also having this issue. Cant download ATM6 or most other mods.
> 
> idk how i closed that, started to reply and changed my mind.
> 
> Was going to ask what other mods you couldn't open because if its a larger issue than just a mod pack it might make things easier to fix.

I tried to download enigmatic 6 and All Of Fabric 2. Both came up with a similar error. I was able to download a smaller pixelmon modpack

**Comment by killnme** [comment]
For some reason im now able to download ATM6. I havent changed anything so idk what the problem was.

**Comment by Shyrshadi** [comment]
> For some reason im now able to download ATM6. I havent changed anything so idk what the problem was.

Yeah its letting me download as well. Weird.

**Comment by websitegenii** [comment]
I can't download it either. Was trying to test it out and setup a server, server files downloaded, though can't download it in curseforge to join the server

**Comment by ladylexxie** [comment]
This error is either caused by using CurseForge launcher or because of the outages from CF's website.
Mostly you can fix this by changing launchers, we recommend GDL.
