### ISSUE TITLE
[ATM6 - 1.7.10] Thermal Series Manual  Click for Recipe Client Crash

### ISSUE THREAD

**Issue by r007ed** [AllTheMods/ATM-6#2215]
**Describe the bug**
Thermal Series manual instructs you to "Shift-Click for Recipe"
Upon doing this for the "Cured Rubber" recipe it causes the client to crash

**To Reproduce**
1. Go to Thermal Series manual (Akashic Tome tested)
2. Click on 'Technology'
3. Click on 'Tinker's Workbench'
4. Go to next page.
5. Click on 'Expanded Tank Construction'
6. Shift click on "Cured Rubber"

**Screenshots**
https://i.imgur.com/sqduxna.png

**Comment by ladylexxie** [comment]
This bug should be reported to the devs of Thermal Series as it's not something we can fix.
