### ISSUE TITLE
Missing Recipes (Cable Tiers)

### ISSUE THREAD

**Issue by Matthew-Garvey** [AllTheMods/ATM-6#2216]
The recipes for Elite, Ultra, and Creative Disk Manipulators do not function. No recipes show in JEI either, and manual crafting by referencing the json for the recipes yielded no results either.

`{
  "type": "minecraft:crafting_shaped",
  "pattern": [
    "DMD",
    "MAM",
    "DMD"
  ],
  "key": {
    "A": { "item": "refinedstorage:advanced_processor" },
    "D": { "item": "minecraft:diamond_block" },
    "M": { "item": "cabletiers:elite_disk_manipulator" }
  },
  "result": {
    "item": "cabletiers:ultra_disk_manipulator",
    "count": 1
  }
}`

`{
  "type": "minecraft:crafting_shaped",
  "pattern": [
    "IMI",
    "MAM",
    "IMI"
  ],
  "key": {
    "A": { "item": "refinedstorage:advanced_processor" },
    "I": { "item": "minecraft:iron_block" },
    "M": { "item": "refinedstorage:disk_manipulator" }
  },
  "result": {
    "item": "cabletiers:elite_disk_manipulator",
    "count": 1
  }
}`

`{
  "type": "minecraft:crafting_shaped",
  "pattern": [
    "IMI",
    "MAM",
    "IMI"
  ],
  "key": {
    "A": { "item": "minecraft:dragon_head" },
    "I": { "item": "minecraft:netherite_block" },
    "M": { "item": "cabletiers:ultra_disk_manipulator" }
  },
  "result": {
    "item": "cabletiers:creative_disk_manipulator",
    "count": 1
  }
}`

**Comment by starforcraft** [comment]
Are you maybe on an old Version? >.<
