### ISSUE TITLE
[1.7.10] Crash when open FTB-Chunks settings screen

### ISSUE THREAD

**Issue by shouta65** [AllTheMods/ATM-6#2217]
**Describe the bug**
Crash when open FTB-Chunks settings screen on version 1.7.10.

**To Reproduce**
1. Open FTB-Chunks large map
2. Click the Settings button such as gear at the bottom left
3. crash

**Additional context**
It seems there is a bug in FTB-Chunks due to the update of FTB-Library. https://github.com/FTBTeam/FTB-Chunks/issues/184
I think downgrading the FTB-Library to 1605.3.1 (build 58) will recover it.

**Logs**
https://gist.github.com/shouta65/9b57f200c47de5e4807141f6842b1cce

**Comment by InQuognito** [comment]
yup, i am having this issue as well, it's what just caused my crash. super annoying because I wanted to turn off all of the red dots in flower fields.

**Comment by radiomike** [comment]
Looks like there's an updated ftbchunks, so you can try that and probably expect a new pack version soon.

**Comment by ladylexxie** [comment]
FTBchunks fixed this issue, we have it in 1.7.11
