### ISSUE TITLE
Pattern terminal freezing the client scanning recipes

### ISSUE THREAD

**Issue by Nidaelie** [AllTheMods/ATM-6#2219]
**Describe the bug**
Opening ae2 pattern terminal freezes the client, if playing in  a server the link remains, like chat things and mobs agroing etc (console view) but client is still frozen.

IF i have luck to put a log in the recipe configurator to show planks the client works normally but next time i need to put a recipe freezes again scanning the modpacks recipes 

**To Reproduce**
opening pattern terminal

**Screenshots**
screenshot of a frozen client?

**Additional context**

**Logs**
I dont have any log or crash cause the client continues working but frozen

everal people has the same issue, reported this thing months ago here and in ae2 github.... got ignored

**Comment by radiomike** [comment]
Have had a look at this and currently unable to replicate it in 1.7.10. 
Admittedly my ae system is only a creative powercell, an ME controller and 1 pattern terminal.

Are there any changes you've made to the pack?

**Comment by Nidaelie** [comment]
PAck is currently 1,7,7, server running it... a a lot of people having same issue, reported this thing in other atm6 versions months ago and the thing was ignored

**Comment by ladylexxie** [comment]
Sorry to say but that sounds like an issue caused by AE2, not much we can do about it except recommending the use of RS
