### ISSUE TITLE
Shift + Scroll up in RS Crafting Grid crashes game

### ISSUE THREAD

**Issue by Revvilo** [AllTheMods/ATM-6#222]
**Describe the bug**
Shift + Scroll down in the Refined Storage crafting grid will pull single items. Doing the opposite, scrolling up, with shift held, crashes the server and causes it to apparently hang on "preparing crash report" thus requiring a force-kill to reboot.

**To Reproduce**
1. Open Crafting Grid
2. Ensure item stack is both in your inventory and in the storage
3. Shift + Scroll up on said item _**in the grid**_
4. Go to buggy jail _BONK_

**Expected behavior**
Either nothing, or for a single item to be pulled back into the system.

**Additional context**
Server log w/ stack trace: https://pastebin.com/WnBp8pUG

**Comment by WhitePhant0m** [comment]
Seems to be fixed with [this](https://www.curseforge.com/minecraft/mc-mods/refined-storage/files/3091433) RS update.
Will be in the next pack update
