### ISSUE TITLE
missing shingles recipes from structurize in jei .I.E all types of shingles excluding clay shingles

### ISSUE THREAD

**Issue by HammerV2658** [AllTheMods/ATM-6#2220]
1.7.10 hi the shingles recipes aren't coming up in JEI 
i also cannot double click the search bar in jei to highlight items in chests

**Comment by ladylexxie** [comment]
They are not missing, they're hidden to reduce clutter. The clay ones are there to show you how to make all the rest, without having 10 pages of shingles.

The JEI bug is sadly nothing we can do about.
