### ISSUE TITLE
Centrifuges get clogged up with mana combs

### ISSUE THREAD

**Issue by Tsuyurin** [AllTheMods/ATM-6#2221]
Pack version 1.7.10

Steps to reproduce:
1. Make a centrifuge and power it
2. Put a single mana comb or block of mana combs in it
3. Observe that processing doesn't start
4. Add mana combs/blocks until there's 9 in the centrifuge
5. Observe that they now process.

Most likely we're missing recipes for single comb/block processing (can't see them in JEI either). End result is my centrifuges get clogged up with leftover mana combs that can't be processed.

**Comment by radiomike** [comment]
You could use Integrated dynamics to make sure the combs only go into one slot, or that they go in in blocks of 9.

**Comment by Tsuyurin** [comment]
Not saying we don't have mods that could potentially solve the issue, but seeing how mana combs are the only type with this problem I've encountered, it sees a bug rather than some extra complication I'm supposed to build a contraption to solve.

**Comment by radiomike** [comment]
It's not the only one that has multiple input to output, the "allthe" ores have a 4 input requirement.
Consider it a challenge, or a motivation to try other mods/solutions.

**Comment by starforcraft** [comment]
Centrifuges will get Auto Sort like Mek in Resourceful Bees 1.0.0

**Comment by Tsuyurin** [comment]
I guess that's one more reason this should probably be fixed for all combs that don't have a 1x processing recipe. I likely never noticed the ATM metal combs because my apiaries produce them in multiples of 4 so they get processed with no lefterovers if I don't backlog.
