### ISSUE TITLE
[1.7.10] Crash when viewing Allthemodium ingots Pedestals recipes

### ISSUE THREAD

**Issue by riipeckx** [AllTheMods/ATM-6#2224]
**Describe the bug**
When I try to view the recipes for Allthemodium ingots for Pedestals, the game crashes.

**To Reproduce**
1. Search for "allthemodium ingot" in JEI
2. Right Click on the AllTheModium Ingot
3. Go to the 3rd page on top of recipes
4. Click on "Crusher Upgrade Recipe" - *Pedestals*

**Logs**
https://pastebin.com/f1DQk8gu

**Comment by radiomike** [comment]
Try without optifine.

**Comment by riipeckx** [comment]
> 
> 
> Try without optifine.

That was the problem. Thanks :)
