### ISSUE TITLE
[1.7.8] Issue when creating Chemial Oxidizer

### ISSUE THREAD

**Issue by TuckerBoy619** [AllTheMods/ATM-6#2225]
**Describe the bug**
Chemical Oxidizer recipe not working correctly, nor are other mekanism recipes with the personal chest (i.e Robit)

**To Reproduce**
1. Search for "Chemial Oxidizer" or "Robit" in JEI
2. View the recipe for either
3. Where the personal chest should be it has "Empty Tag: forge: chests/personal

**Screenshots**
![RDT_20210823_0421065011410091226848210](https://user-images.githubusercontent.com/89356114/130366776-f90e01fb-e33a-4ab5-8fd2-254ed0a30e45.jpg)

**Comment by radiomike** [comment]
Update the pack, This is fixed in more recent versions
