### ISSUE TITLE
[1.7.10] edelwood lava buckets from Forbidden become Iron buckets when used on fluid cell from thermal

### ISSUE THREAD

**Issue by Gmoney2123** [AllTheMods/ATM-6#2226]
**Describe the bug**
When an edelwood lava bucket is right-clicked on a fluid cell from thermal expansion it becomes an iron lava bucket.

**To Reproduce**
1. get edelwood lava bucket
2. right-click on a thermal expansion fluid cell with lava in it
3. get iron lava bucket

https://user-images.githubusercontent.com/18722745/130370636-5e056856-7bff-4bdc-b5d2-c72875e668df.mp4

**Comment by ladylexxie** [comment]
This is a known issue with the Edelwood buckets to cause such things because of how it's coded. Nothing we can do about it sadly.
