### ISSUE TITLE
Fix for "Failed to install modpack 381671"

### ISSUE THREAD

**Issue by whylock** [AllTheMods/ATM-6#2227]
I'm this this modpack install error. I'm trying to install in latest version of the modpack (1.7.10) using the curseforge launcher. Can't find anything about this anywhere else online.

**Comment by IronPrince2001** [comment]
I'm having the same issue as well and the download stops at the mod Angel Ring. Then it cancels the update.

**Comment by Pdiddy973** [comment]
this is a curseforge issue, the site is having issues. we cant do much about it

**Comment by IronPrince2001** [comment]
Then how do we use the most recent version?

**Comment by Pdiddy973** [comment]
wait for curseforge to fix the site/outage
