### ISSUE TITLE
[1.7.10] Cannot find child addon: 333396

### ISSUE THREAD

**Issue by Jerbear0** [AllTheMods/ATM-6#2229]
All the Mods pack version 1.7.10 from 2 days ago

i can't install the latest version since its missing this child addon

**Comment by Pdiddy973** [comment]
#2227
try looking for more than 5 seconds next time

**Comment by Jerbear0** [comment]
> #2227
> try looking for more than 5 seconds next time

or not, what's your problem?

**Comment by Verlancia** [comment]
I bet you guys eat popcorn without swallowing.

**Comment by Jerbear0** [comment]
i dont eat when i chew
