### ISSUE TITLE
[ATM7] Can't Connect to server

### ISSUE THREAD

**Issue by flameskateboard** [AllTheMods/ATM-6#2230]
pack version is 0.0.2 of All the mods 7, my father is trying to connect to the public server, and its just giving the same error over and over. attached is the log file, please send help ;-; -LilyTheFox
[latest.log](https://github.com/AllTheMods/ATM-6/files/7028344/latest.log)

**Comment by flameskateboard** [comment]
btw i'm sorry for putting it in atm6 instead of atm7, i've barely used github at all lol

**Comment by ladylexxie** [comment]
You can put the issue [here](https://github.com/AllTheMods/ATM-7/issues/new/choose).

**Comment by flameskateboard** [comment]
though it was resolved luckily
