### ISSUE TITLE
[AtM6-1.7.10] After some time, unable to rejoin server.

### ISSUE THREAD

**Issue by Sakata-MC** [AllTheMods/ATM-6#2231]
After some time, unable to rejoin server.

Indeterminate reproduction of the error -- Seems to occur after a random period of time, sometimes after hours, sometimes after just a few minutes.
Will disconnect (or be disconnected with error) from the server, and when attempting to rejoin the server this error is displayed:
Internal Exception: java.io.IOException: An existing connection was forcibly closed by the remote host.

Client Console:
https://gist.github.com/Sakata-MC/486b7297cef18d57c7fe65b9a04484c7

Server Console:
https://gist.github.com/Sakata-MC/afae2e5feffb44e45b04bb7f31d72ac3

Appears to be related to FTBEssentials/FTBChunks - Could be related to inability to open the settings dialogue from map.

We're updating to see if issue persists and will update here if we find issue resolved.

**Comment by ladylexxie** [comment]
Progress on this issue will be tracked in #2407
