### ISSUE TITLE
Please consider removing "Oh The Biomes You'll Go"

### ISSUE THREAD

**Issue by twothe** [AllTheMods/ATM-6#2232]
Pack version: 6-1.7.11

Please consider removing Byg aka "Oh The Biomes You'll Go" with the next major update: It causes heavy world generation lag on both client and servers, and the mod provides nothing but questionable visual change. 

Removing that mod would drastically improve chunk generation/loading times and therefore make the pack playable on a much larger range of hardware.

**Comment by AR-E** [comment]
1.7.11 has come out recently, why don't you see if it has a fix to your issue. If it does not, you should wait until 1.8.0 (which will be released soon™) as it will be a fairly large update. Otherwise, kindly un-suggest this change :)

**Comment by abc123454321cba** [comment]
On behalf of @AR-E, from #atm6-general: "You're mom"

**Comment by thevortex** [comment]
if you want to remove it from your own instance, go for it, we won't be removing it from the pack
