### ISSUE TITLE
Seed Reprocessor stops working 1.1.6b (Bugged for 1.1.8 as well)

### ISSUE THREAD

**Issue by puppydemon20** [AllTheMods/ATM-6#224]
I found a bug that causes the Seed Reprocessor to stop working in a specific situation. It will continue to burn coal fine, but will not process seeds.

1. Have seeds inserted into the top of the Seed Reprocessor via Mekanism pipes
2. Have an extract out the bottom for essence (in my case, a refined storage importer)
3. Fill with Coal
4. Break and Replace the Seed Reprocessor while it is running.
5. Examine it's inoperability to process seeds.

**Expected behavior**
The block should continue working as intended.

Here's a screenshot of the setup I used to reproduce this in Single Player
![image](https://user-images.githubusercontent.com/13732804/97098836-ecb4fe00-163e-11eb-9e6f-ea23bd3d9d69.png)

**Additional context**
Exiting and rejoining the world fixes the problem, for server's it requires a restart (I think)
Probably unnecessary to note, but in 1.1.6b I was able to recreate it easily several times, in 1.1.8 it took a few tries.

**Comment by jeremiahwinsley** [comment]
Cannot reproduce in 1.3.9, assuming it's fixed. If you can still reproduce this, please reopen the issue.
