### ISSUE TITLE
Wireless Heat Transmitter Dupe

### ISSUE THREAD

**Issue by AustyLF** [AllTheMods/ATM-6#2240]
Pack Version 1.7.11 

**To Reproduce**
Break a heat transmitter (Attempted with both Silent Gems tools and tinkers)

https://user-images.githubusercontent.com/89428737/130534890-d60eb003-cb1c-4a31-9b25-56f653cbcd53.mp4

**Comment by AustyLF** [comment]
Just adding an addition, even though it's a dupe. They're unbreakable, even in creative.

**Comment by jebjordan** [comment]
wtf, why is this working.

**Comment by jebjordan** [comment]
@AustyLF FYI if you need to remove it, use a block breaker from Cyclic. Successfully gets rid of the block.

really wanna know why the hek they arent breaking normally tho lol

**Comment by Ki-Tan2934** [comment]
you can use a cardboard box from Mekanism, update the mod or wait for the pack update. In future, you should use the correct GitHub for posting mod related problems
