### ISSUE TITLE
No recipe for breeding Netherite Bees

### ISSUE THREAD

**Issue by Brunodps** [AllTheMods/ATM-6#2244]
Pack version: 1.7.11

There is currently no recipe to breed Netherite bees. I tried looking on JEI and on the Beepedia and found nothing. I also tried googling it and found that it could be Diamon and Wither bee but that also did not work.

**Comment by IcewaveGaming** [comment]
Netherite bees are mutated, not bred.

**Comment by IcewaveGaming** [comment]
There should bee a recipe for gold bees mutating a netherite block.

**Comment by Brunodps** [comment]
Oh I see, Thank you.
