### ISSUE TITLE
ATM 1.7.11 Sticks only go in lower right of 2x2 storage drawer

### ISSUE THREAD

**Issue by Bwibs** [AllTheMods/ATM-6#2251]
ATM 6 1.7.11

If you try to put standard minecraft wooden sticks in any spot other than the lower right of a 2x2 storage drawer it goes in the lower right.  If the lower right is not available it won't go in the drawer at all.  

I have only run into this bug with sticks, everything else I've used has acted as expected with Storage Drawers

**Comment by ladylexxie** [comment]
This is something that should be reported to the Storage Drawers' devs.
