### ISSUE TITLE
Tinkers parts not avalible to client when jointed to a LAN game 1.7.6

### ISSUE THREAD

**Issue by shaddaz1** [AllTheMods/ATM-6#2257]
When joining a LAN game tinkers construct tool parts are not available to the client  in the stencil table also can not be found in the GUI however the host still has full access to them

**Comment by ladylexxie** [comment]
This should be reported to the Tinkers' devs, we don't alter the visibility of those items in any way.

**Comment by shaddaz1** [comment]
Might be worth checking for a mod conflict I don't have issues with tinkers in other packs 

As I said the host can see and use all the items the joining client can not see or use the tool parts or the parts table but can use the tools once they have been created
