### ISSUE TITLE
Server won't start [1.16.5]

### ISSUE THREAD

**Issue by rosellil** [AllTheMods/ATM-6#2258]
This might be a complicated issue because of my use case. Regardless, I have a linux machine that is already running a 1.17 vanilla server. On this same machine I would like to run a ATM6 1.16.5 server. When I try to launch the server I get a java error (attached). I am forcing the startserver.sh file to run the server on java 11 because 1.16.5 won't run on java 16 that 1.17 requires. Java 16 is the machine's default java version. But the log file mentions how MODLAUNCHER is trying to run java 16. How do I change this behavior? I have also tried forcing it to run on java 8 to no avail. 
[debug.log](https://github.com/AllTheMods/ATM-6/files/7071542/debug.log)
[latest.log](https://github.com/AllTheMods/ATM-6/files/7071543/latest.log)
![Screenshot 2021-08-28 145056](https://user-images.githubusercontent.com/75292572/131231892-a597a1a9-1fe4-4cca-b138-7012a7cbee62.png)
![Screenshot 2021-08-28 145140](https://user-images.githubusercontent.com/75292572/131231919-a9ef1ffa-8c27-4741-8730-4f068d977769.png)

**Comment by RaVenInTheDark** [comment]
Forge does not work with java 16 by default. Either force java 8 or use the below arguments: 
`    - "--add-opens=java.base/sun.security.util=ALL-UNNAMED"
    - "--add-opens=java.base/java.util.jar=ALL-UNNAMED"`

**Comment by radiomike** [comment]
To force the pack to use java 11 or 8 you need to set the path for the relevant java version in the `server-setup-config.yaml` file.

**Comment by Sakata-MC** [comment]
Also, it'd be a good thing to adjust the title of the post to reflect the version of AtM6 you're on... since all AtM uses 1.16.x builds...
