### ISSUE TITLE
Trading with piglins on 1.16.3 all the mods 1.1.8 causes game to stutter then crash.

### ISSUE THREAD

**Issue by Flexinparadise** [AllTheMods/ATM-6#226]
**Trading with piglins on 1.16.3 all the mods 1.1.8 causes game to stutter then crash.**
if you trade with piglins in both the nether and overworld, after too many subsequent trades, your CPU usage builds up and then the game stutters and crashes.

**To Reproduce**
For us, we play on a multiplayer server. We just get gold, and trade with the piglins. After some trades the cpu usage spikes. This has been replicated many times by all of us. (like 8 people on the server)

**Expected behavior**
trade with piglin and no game crash

**Comment by waybaker** [comment]
I came here to post this as well.  It is present in 1.3.3.

**Comment by NetMasterFlex** [comment]
I’m able to trade with Piglins on 1.3.3 no issue based on my own experience.
