### ISSUE TITLE
Remove Cyclic pipes since they're tick hogs and not recommended even by devs.

### ISSUE THREAD

**Issue by Sakata-MC** [AllTheMods/ATM-6#2260]
Over several versions I've been manually removing the recipe for cyclic pipes from the server.
It would be nice if this was the default, as I've forgotten a time or 3.

**Comment by jebjordan** [comment]
The devs? Who exactly 

Devs of cyclic? If so is there a source for that, would love to view it

**Comment by ladylexxie** [comment]
The pipes are already removed from the pack in the next version.
