### ISSUE TITLE
Fluorite Seeds in incorrect place in Quest book [ATM6 1.7.11]

### ISSUE THREAD

**Issue by voidei** [AllTheMods/ATM-6#2261]
**Describe the bug**
I was recently going through and crafting all the Mystical Aggriculture seeds and noticed that the Fluorite Seeds are located with the other Tier 3 (Tertium) seeds in the quest book despite being Tier 4 (Imperium) seeds. Not sure if they're in the wrong spot in the book or if they're supposed to be Tier 3 seeds and the recipe is wrong.

**To Reproduce**
1. Open Quest book
2. Go to Mystical Aggriculture
3. Click on Fluorite Seeds (above Tertium Farmland quest)
4. Click in them to bring up recipe and notice they're Tier 4 and require Imperium Essence

**Screenshots**
![2021-08-28_21_19_14-Window](https://user-images.githubusercontent.com/8062954/131234470-8a1eb7c2-bfda-4048-baa4-a57188547647.png)
![2021-08-28_21_20_11-Window](https://user-images.githubusercontent.com/8062954/131234471-8856ac8d-3197-4fdc-894a-8e104028de6b.png)
![2021-08-28_21_19_53-Window](https://user-images.githubusercontent.com/8062954/131234472-e6328a1c-cb90-4bdd-a1a8-2b051b6049b4.png)

**Comment by ladylexxie** [comment]
Fixed in the next version of the pack.
