### ISSUE TITLE
[ATM6 1.7.11] Refined Storage's External Storages on Drawer Controllers are not recognized by the RS-system on server restart.

### ISSUE THREAD

**Issue by hhking7** [AllTheMods/ATM-6#2262]
**Describe the bug**
After a server restart, Refined Storage systems no longer recognize External Storage extending Drawer Controllers from Storage Drawers. A player has to manually refresh it by interacting with the External Storage (breaking and replacing or changing settings) in order for the system to recognize the items in the drawers.

**To Reproduce**
1. Set up a Refined Storage system and connect an External Storage to a Drawer Controller. (On a Server)
2. Restart the server.
3. Open any grid and see that the items in the drawers are no longer there.

**Additional context**
I have been able to reproduce this problem placing the External Storage on all sides of the Drawer Controller with the exception of the front which i have not tested.

**Comment by radiomike** [comment]
Set an external storage at a convenient location on your network to be redstone controlled. Then give it a redstone pulse/use a lever to turn it off and on again whenever you restart the world. This should force the network to resync and let you see the contents of all inventories attached to external storages on the network.
There's also a couple of ways to do the redstone pulse remotely or automatically.
