### ISSUE TITLE
[1.7.11] No recipe for allthemodium, vibranium, and unobtanium bees in JEI

### ISSUE THREAD

**Issue by faizjamil** [AllTheMods/ATM-6#2263]
I'm looking into making farms for certain bees such as allthemodium, vibranium, and unobtanium (the latter two waay later on ofc). Soo for all three, they do not spawn in world and apparently you can't get them through breeding.

Is this one of those bees that need to be mutated from another bee?
How does mutation work and if this is the case, is it possible to add info on this somewhere in JEI (or in a book, just somewhere)?

**Comment by YarlinPoe** [comment]
Took me a bit to find also but the BeePedia helped along with JEI but it starts with the Wither then Draconic Bee and it's Pollination effects after that. BeePedia thing should have the info under one of those 2 bees to get it started in that direction.

**Comment by voidei** [comment]
You can also check the General Gameplay Guide section on Resource Bees, as these bees are created through Mutation (not crafting/breeding) which is on the left part of the guide.

**Comment by faizjamil** [comment]
Hmm, is there anyway to check how to get a particular bee without knowing the bee that you need to start with before a mutation?

**Comment by ladylexxie** [comment]
> Hmm, is there anyway to check how to get a particular bee without knowing the bee that you need to start with before a mutation?

By either checking Beepedia or the bee breeding guide I made in the wiki.
