### ISSUE TITLE
Compacting Drawers compressing to the wrong mod

### ISSUE THREAD

**Issue by TheMinecraftian772** [AllTheMods/ATM-6#2264]
<--Pack Version 1.1.8-->
In trying to automate some sieves, I was trying to use the Compacting Drawer to turn the cobblestone into compressed so it could be automatically hammered by a compressed hammer, and I noticed it was compressing to the wrong cobblestone.  Going to AllTheCompressed rather than Compressium.  This wouldn't be anything more than a visual issue (I like the compressium textures better) if it weren't for the fact that you can't hammer the compressed blocks from AllTheCompressed with the compressed hammer.
(I haven't tried manually hammering it yet, but considering I'm at the point where resources are being automated, I shouldn't need to.)  I'm using the compressed netherite hammer in a pedestal with the block breaking upgrade.  It works just fine for the Compressium 1X cobblestone, but not ATC cobble.  
Is there a way to configure which the drawer prioritizes or a way to get it to the right compressed cobble?  Trying to put in a compressium cobble puts it in the bottom slot rather than the top where I click, making it impossible to get the cobblestone to Compressium cobble in the compacting drawer.

**Comment by ladylexxie** [comment]
Is this ATM6 related or ATM6Sky?

**Comment by TheMinecraftian772** [comment]
Woops sorry, It's ATM6 Sky.  I thought I had put that in there. aww heck, there's a whole different repository for it, my bad.  Should I just copy this over to there?  Or is there a way to move this as is?
