### ISSUE TITLE
ATM6 1.7.11 stuck in the twilight forest

### ISSUE THREAD

**Issue by Sehrank8** [AllTheMods/ATM-6#2265]
I am stuck in the twilight forest there is amazing lag and /home doesn't work, nothing I type in chat gets registered. I tried changing my location to the overworld with a nbt editor but I am still in the twilight forest and can't do anything please help.

**Screenshots**
![2021-08-30_12 53 25](https://user-images.githubusercontent.com/64368795/131321828-b8d20383-f522-4d9f-8d22-9866e80cae01.png)
![2021-08-30_12 53 31](https://user-images.githubusercontent.com/64368795/131321849-ab3e724c-c6ab-4b34-9701-c2b178094270.png)

**Additional context**
I can't paste the logs into pastebin its over 1000kb sorry for that.
I usually play on LAN with my friend 

**Logs**
Please use a paste site for logs, instead of putting the file directly in the issue, not only is this easier but also means we can view on mobile when we are not at our computers.
[latest.log](https://github.com/AllTheMods/ATM-6/files/7075859/latest.log)
[2021-08-24-2.log](https://github.com/AllTheMods/ATM-6/files/7075885/2021-08-24-2.log) (this is when it first happened)

**Comment by ladylexxie** [comment]
Try doing `/tpx minecraft:overworld`, you should have OP for that

**Comment by Sehrank8** [comment]
Didn't work. The command turns red when I type it and the chat didn't even respond with "unknown command"

**Comment by SlackerNet** [comment]
/cu unstuck [name] in console will move the player to the spawn on next login

**Comment by ladylexxie** [comment]
> Didn't work. The command turns red when I type it and the chat didn't even respond with "unknown command"

Are you sure you had OP? If that turned red, it means you didn't.

**Comment by Sehrank8** [comment]
I have OP, I created the world with cheats on and even opened to LAN to with cheats on to make sure I have OP.

**Comment by ladylexxie** [comment]
There is no difference, singleplayer also uses an internal server since 1.3.
When you said you modified the tags to be in the overworld, did you also modify the `_old` file? If not, it will override any changes you've made.

**Comment by Sehrank8** [comment]
I didn't modify `_old` file because it is in overworld. I recently modified the `level.dat` file and it solved the problem. But I am scared and won't enter the twilight forest now. Should I delete the dimension? Is the twilight forest essential to the modpack or optional?

**Comment by ladylexxie** [comment]
Luckily TF isn't essential for anything, it's safe to remove it, you might even see an increase in performance after removing it.
