### ISSUE TITLE
Minecraft crashing Random version 1.7.11

### ISSUE THREAD

**Issue by DavidieHD** [AllTheMods/ATM-6#2266]
Minecraft is crashing randomly (but most when i try to fly with the jetpack)
im playing on my own  server with friends, iam the only ne that crashes
i tried to put particals to minimal that doesnt help.

**Logs**
Please use a paste site for logs, instead of putting the file directly in the issue, not only is this easier but also means we can view on mobile when we are not at our computers.
Here's a list of some paste sites and their size limits:
    https://pastebin.com/cURJiGWC

**Comment by radiomike** [comment]
It's a known issue with the framed blocks mod. See https://github.com/XFactHD/FramedBlocks/issues/49

**Comment by XFactHD** [comment]
A new version (2.10.0) with the fix for this crash is now available on CurseForge.
