### ISSUE TITLE
Ice and fire dragons and skeletons not spawning at all.

### ISSUE THREAD

**Issue by TakeyaSaito** [AllTheMods/ATM-6#2267]
So me and a friend have been checking this literally all day, there are no dragons spawning at all, we even used specter eye amulets to make sure we were not just missing them but even the skeletons aren't spawning so im guessing ice and fire worldgen is not working at all. any idea how to fix this?

**Comment by TakeyaSaito** [comment]
to clarify we picked clean any Basal Delta, Desert and mountain biomes in "The other" dimension

**Comment by ladylexxie** [comment]
![image](https://user-images.githubusercontent.com/30494658/131390535-b425113e-3d9a-4859-90f7-9f3f8b7a44e1.png)
This was an image taken 2 days ago on 1.7.11, make sure you have everything updated and you're not playing on peaceful.

**Comment by TakeyaSaito** [comment]
Are you playing single player or a server? Single player works fine

**Comment by TakeyaSaito** [comment]
> ![image](https://user-images.githubusercontent.com/30494658/131390535-b425113e-3d9a-4859-90f7-9f3f8b7a44e1.png)
> This was an image taken 2 days ago on 1.7.11, make sure you have everything updated and you're not playing on peaceful.

Are you testing this on a server or single player?
