### ISSUE TITLE
Wireless heat transfer from iron furnaces duplicating when broken

### ISSUE THREAD

**Issue by Monkeyboy10000** [AllTheMods/ATM-6#2269]
I am on 1.7.11 and i was remodeling my refined storage area and when i went to pick up the wireless heat transfer it just started duplicating but not breaking. 

I tried replicating it by placing one of the copies down and it did the same thing even with other pickaxes

Screenshot here:
![2021-08-30_17 13 50](https://user-images.githubusercontent.com/89813366/131413120-36444973-4717-4e8c-a52a-89941afb99aa.png)

(My world was made in the 1.5 version or around that if that does anything)

**Comment by ladylexxie** [comment]
This is fixed in the next version of the modpack.
