### ISSUE TITLE
Overworld biome mismatch?

### ISSUE THREAD

**Issue by alextunbridge67** [AllTheMods/ATM-6#227]
I'm not exactly sure what happened. After updating to 1.1.6 (fire and ice update) my ATM mining dimension was set to "The Other" biome making it a very dangerous place. I decided to delete the dimensions in the save folder to have them regenerate. After doing that I had updated to 1.1.8. Now when I log back in all the biomes in the overworld are incorrect and even made my home biome "The Other". I've tried using my two most recent backups but even then the biomes go back to being mismatched.

https://imgur.com/a/HRMtYMd

**Comment by GamerXD8991** [comment]
I have almost the same problem. It started with "turning" the nether into Ocean, and upon leaving the overworld as well. tried regenerating the nether. with the result that a few of the new nether chunks are normal (except that they are diffent biomes than before) and the rest is ocean.

Main differerence is that I already played in 1.1.8 (and visited the nether, where everthing was normal)

**Comment by GamerXD8991** [comment]
Found the problem (at least for me)!
It was Optifine causing the missmatch. try removing it and regen the chunks

**Comment by alextunbridge67** [comment]
> Found the problem (at least for me)!
> It was Optifine causing the missmatch. try removing it and regen the chunks

It works! Thank you so much. I thought I had totally lost my world. I had started a new save and everything.
