### ISSUE TITLE
ATM6 V1.7.11 desert Myrex staff crash

### ISSUE THREAD

**Issue by Earth-To-Luna** [AllTheMods/ATM-6#2272]
All the mods 6 version: 1.7.11
**Describe the bug**
Right-clicking with the desert Myrmex staff causes the game to crash

**To Reproduce**
1. obtain a desert Myrex staff
2. Right Click in the air
3. game proceeds to freeze and crash

**Additional context**
 Both times I repeated this bug I was in the dimension: The Other. I also had an extendo grip in my off-hand I'm not sure if either of these affects it. I also have sodium reforged installed which may be the cause as well.
**Logs**
https://pastebin.com/nPZzbp2b

**Comment by riipeckx** [comment]
Is OptiFine installed ? Might be a problem as well.

**Comment by Earth-To-Luna** [comment]
> Is OptiFine installed ? Might be a problem as well.

no, as I said in the post but it might be a complication with sodium reforged. I only use that specific mod because optifine gives a warning when launching with it and sodium does not so I assume it is fully compatible and if not then sodium should have a warning just like optifine has

**Comment by ladylexxie** [comment]
This sadly is just an issue caused by I&F and there's nothing we can do short of removing the item. Should be reported to the mod developer.
