### ISSUE TITLE
Polished Marble missing from All the Mods 6-1.7.11

### ISSUE THREAD

**Issue by Sulhir** [AllTheMods/ATM-6#2273]
**Describe the bug**
Polished Marble can not longer be crafted with Quark Marble.

**To Reproduce**
Place Quark Marble 2x2 in the crafting grid
No output is shown
Polished Marble in JEI shows no recipe when left clicked

**Screenshots**
![image](https://user-images.githubusercontent.com/2348081/131547561-afced8cc-3ce6-4a17-9aa8-dc06905909fe.png)
![image](https://user-images.githubusercontent.com/2348081/131547679-01dd50c2-f9fb-47b0-bb02-070923eccac6.png)

**Comment by radiomike** [comment]
See https://github.com/AllTheMods/ATM-6/issues/2237#issuecomment-905939366

**Comment by ladylexxie** [comment]
Fixed in the next update.

**Comment by Sulhir** [comment]
Just as a note for everyone if they are also looking for a little more detail than the comment mentioned above to fix it before the next update (or without updating)
The file you need to edit is somewhere along these lines 
`C:\Users\<username>\curseforge\minecraft\Instances\All the Mods 6 - ATM6 - 1.16.5\config\quark-common.toml`
and you need to edit line 1164 and line 1165 to read true instead of false.
You can edit the file in any word or notepad but notepad++ provides line numbers.  It's about halfway down the document without line numbers.  It is the in the first instance of world.new if you want to use Control+F to find it.
