### ISSUE TITLE
KubeJS failed to load

### ISSUE THREAD

**Issue by Strike333** [AllTheMods/ATM-6#2274]
When I open up the game, it gives me to the error message that says KubeJS has failed to load correctly. It says that there was a startup script syntax errors. What should I do? This is on the version of All the mods 6 Sky v1.1.8.

**Comment by ladylexxie** [comment]
This should be reported to the [Sky issue tracker](https://github.com/AllTheMods/atm6-sky/issues/new/choose), not the ATM6 issue tracker.
