### ISSUE TITLE
Constant Crash Bug 

### ISSUE THREAD

**Issue by Kinetic-Potato** [AllTheMods/ATM-6#2276]
Version 1.7.11
Upon trying to load my single-player world, while attempting to join the world the game crashes. This occurs every time I try to load/join the world. I can load/create a new world without problems.

While experimenting with mods I placed down a bucket of "Fluid Xp Bucket" from "Mod Grinding units". I moved to stand in the liquid XP and started to slowly gain XP. After standing there for around 7 seconds my game froze and crashed. I re-loaded the world and was able to join. I instantly picked up the bucket of Fluid Xp in hopes that that was the issue. The game very quickly froze and crashed again. The fluid drained to the point of were im not standing in it anymore but it not all gone yet. I am not able to open the world anymore. 

I tried to fix the issue by removing the "Mob grinding units" mod folder bit it did not resolve the issue. 
   
**To Reproduce**
1. Go to ATM 6 menu while in the game 
2. Click on Single player and load my world
3.  Wait for it to load
4. Game crashes and I'm prompted with "The game crashed whilst unexpected error
Error: java.lang.ArrayIndexOutOfBoundsException: -4
Exit Code: -1 " crash report. 

**Additional context**
The pack was downloaded and used over CurseForge. Attempts to report the bug on CurseForge failed in an error message. "Unable to send issue report: or somethin like that. The game had only ever crashed one time before while loading warm Ocean Biome.

**Comment by ladylexxie** [comment]
Can't help crash reports without the actual crash reports. Please follow the template and provide all information.

**Comment by Kinetic-Potato** [comment]
Will re-upload with crash logs
