### ISSUE TITLE
Twilight Forest missing block Leaf pile or twilightforest:fallen_leaves

### ISSUE THREAD

**Issue by DraTrav** [AllTheMods/ATM-6#2277]
**Describe the bug**
Twilight forest achievement is impossible to obtain due to a block that is only missing in atm6 but not a vanilla install of the twilight forest, That block being Twilightforest:fallen_leaves or Leaf Pile

**To Reproduce**
1. Play atm6
2. Go for maniacal dendrologist achievement
3. Notice block is missing
4. Achievement impossible

**Additional context**
Several people in the discord assumed it is a problem with Kubejs

**Comment by ladylexxie** [comment]
Where is the item missing? Do you mean it doesn't spawn?
It is in my JEI and I havent messed around with it at all.
![image](https://user-images.githubusercontent.com/30494658/131950528-673fd13f-420e-4c19-88db-ec507abf07cc.png)

**Comment by DraTrav** [comment]
It doesnt seem to spawn, however it did not appear in my JEI until after two full reinstalls oddly

**Comment by ladylexxie** [comment]
Regarding the spawns, it is not something we control. We don't really change anything twilight forest related except the uncrafting table.
