### ISSUE TITLE
Rebalance Mekanism nuclear waste

### ISSUE THREAD

**Issue by Steampunk-Wizard** [AllTheMods/ATM-6#2279]
**The Problem:**
Mekanism fission reactors make almost no practical sense when it comes to power production. They aren't sustainable within reasonable means all because of one thing: Nuclear Waste.

This has absolutely nothing to do with any other part of the nuclear process. Uranium processing, heat transfer, power generation and all the structures required to do so competently are perfectly feasible, scalable, and customizable. But this all comes to a halt once you consider the waste.

**For a quick refresher on the numbers:**
-A fission reactor can burn a max amount of fissile fuel equal to **1mb per tick per 1 Fission Fuel assembly**, and is adjustable from 0 to max in 0.1mb/t increments. This produces an equal amount of nuclear waste as a byproduct. Failing to handle this throughput of waste results in fatal consequences for both the reactor and any nearby inhabitants.
-The reactor produces roughly **34,000 FE/t for every 1mb** of burn rate
-You can process nuclear waste into either polonium or plutonium, both at **a ratio of 10mb to 1mb**. This process is effectively free and has decent throughput, so you can assume the actual waste production is 1/10th of the input fissile fuel.
-After obtaining either gas, you can turn them into pellets using fluorite dust, producing a corresponding pellet, as well as spent nuclear waste. This final product has no uses, and must be contained or disposed of. It's produced at **a 1:1 ratio** of either polonium or plutonium gas.
-The only correct way to dispose of this spent waste (_ignoring some cheeky AE2 shenanigans with deleting spatial storage cells_) is to dump them into radioactive waste barrels. These barrels will dispose of the waste at a rate of **1mb every minute**

**Now it's math time.**
-Using the smallest possible reactor as an example, max burn will use 1mb per tick. That's 20 a second, and 1200 a minute. Divide by 10 for processing into spent waste, and you get a result of 120mb per minute. **That's 120 waste barrels, for the smallest possible reactor** making 34kfe/t. Quoting the Mekanism wiki for a reference point, "That's roughly 2.5 times less power than a Gas-Burning Generator burning Ethylene."
-Another interesting metric, is dividing the 34k power output by the 120 barrels, resulting in **an astoundingly low power throughput of 283fe/t** for each barrel added. 
-Using this metric and comparing it to Bigger reactors, you need to make a solid cube of waste barrels and tubes to fill them, 1-4+ (_depending on whether or not you use BR turbines_)  times the volume of the Bigger Reactor in order to achieve a similar power throughput. That's before you even build the Mekanism reactor, and well before you consider the chain of production, processing, and potential fallout if you mess it up. 

I don't know exactly how much server lag a single pipe and barrel could cause, but I can't imagine it goes well when you have a single network of thousands of barrels and pipes, just to eek out that 1 million fe/t

To add further insult to injury, there is a rare Mekanism bug where pipe networks (pipes, cables, tubes, etc) stop functioning correctly without a block update on server restart. From my own experience and the posts on that issue, it appears this bug happens more often with increasingly larger networks of pipes.  It's gonna be a bad time when you suddenly start backing up waste...

**The easiest solution**
Change the config. According to a post on the Mekanism github, there's just a config for the processing rate of radioactive waste barrels. 
In my opinion, a factor of ten _might_ be a start. This would mean 1 million fe/t would require hundreds of barrels instead of thousands to sustain. 
A factor of 100 would mean each Fission Fuel Assembly would require 1.2 barrels. That could be too far. My best guess would be somewhere in the 10-30 range

**The other convoluted solutions**
**1:** If you are familiar with late-game Mekanism, you will know that I didn't mention the SPS (Supercritical Phase Shifter) This machine uses vast amounts of power to turn polonium into antimatter, yielding absolutely zero radioactive byproducts! My initial thought was that Mekanism was balanced around needing to make a suboptimal reactor first, (_you need polonium and plutonium to make the SPS_) before reaching easy waste processing with the SPS. **I was really wrong.** When I say vast amounts of power, I mean VAST. So much in fact, that a fission reactor doesn't make enough power to cleanly process it's own waste products. And its not even close. 

This presents a few possible alternatives. Drastically reducing the power requirements for the SPS to within the amount a reactor can supply. This would make it so clean reactors can exist, but produce much less power than one that uses a giant pile of waste barrels. However, this brings up the question about whether it's worth it to just run a very small reactor and deal with the barrels, depending on the overhead costs of running this theoretical SPS.
You can mess with this in another way too. Instead of reducing power, you could increase the cost of polonium to make antimatter. This would simultaneously make antimatter more expensive to get, but make automating it a bit easier. 

**2:** Fiddle with ratios somewhere in the processing chain. You have fissile fuel into waste, waste into polonium/plutonium, and those into spent waste. Each of these steps could have their recipe changed in order to reduce the amount of waste produced. Putting it at the end of the chain means players have just as much polonium and plutonium, but less waste to deal with, while putting it at either stage before means players will get less of those resources in exchange for an easier time, if you think that sort of balance is necessary. 

**3:** Increase the reactor's power output. This would probably need to either be done at the turbine level, or the heating level within the reactor. Both options are kind of gross and have side effects (such as increasing the power of other mekanism things that use the turbine, or requiring much beefier cooling solutions). But, this in effect increases the throughput of any barrel, as well as the SPS. I don't like this idea. but its there.

**4:** Make radioactive waste barrels BIG.  This is a dumb not-solution, but I'll mention it. Waste barrels hold 64 buckets of gas, which is the same amount as a basic chemical tank. An Ultimate tank holds 512 buckets in the same amount of space. Why hold so little? I don't know, but if someone is really adamant about fission reactors being an "auxiliary power source", effectively rendering the reactor as a big expensive reverse battery (It's a really BAD battery too. each barrel holds about 18 million FE), this not-solution would improve the amount of time you could run the reactor before admitting the futility of it all and jumping to Bigger Reactors or making a fusion reactor. 

**5:** Create a brand new use for spent nuclear waste, or a recipe that doesn't make it as a byproduct. This is the coolest solution, but also the most effort and time consuming. The process could be as simple or complex as you want. Could require vast amounts of non-power resources too, if that's to your liking. This suggestion could take the form of anything from a recipe for some sort of depleted uranium, to a multiblock that dumps our nuclear waste into another dimension.

**Additional context**
At the end of the day, in its current state, the fission reactor is either a massively bulky mess of pipes and barrels that makes less power than my potato farm, or a massive complex and dangerous part of an immense power-sucking antimatter production plant. It's not a large scale mass-power-producing plant, like a nuclear reactor should be. at least not without incredible amounts of infrastructure that isn't worth the drop in server performance it could cause. 

As a final closing statement to add one last bit of perspective. A relatively modest 7x7x5 reactor (much less than the max of 18 cubed), uses 26 fuel assemblies and would need over 3,000 waste barrels in order to be maintained. And it still only makes about 880kfe/t

**Comment by Pdiddy973** [comment]
nuclear waste is supposed to be annoying to deal with...you shouldn't really be using mek fission long term anyway you should be using it as a stepping stone to mek fusion anyway
