### ISSUE TITLE
Very low tps when forceloading a chunk in the nether

### ISSUE THREAD

**Issue by firex20** [AllTheMods/ATM-6#228]
When I try to forceload a chunk with FTB Chunks in the nether and come back to the overworld the tps starts to drop until it reach 2, I tested in with the end too and it works fine there, and it works fine if you go to the nether while you have load chunks in the overworld. I have a lot of ram allocated to minecraft (12gb) and a pretty decent pc so I asume this is a bug (?). P.D: Im playing single player.

**Comment by DrunkTaank** [comment]
Just a heads up Firex, this looks like it was fixed in the latest update.  I was getting ready to report this myself, but then noticed there was an update to the pack.

**Comment by firex20** [comment]
> 
> 
> Just a heads up Firex, this looks like it was fixed in the latest update. I was getting ready to report this myself, but then noticed there was an update to the pack.

Oh okay, ill try again then :3

**Comment by firex20** [comment]
> 
> 
> > Just a heads up Firex, this looks like it was fixed in the latest update. I was getting ready to report this myself, but then noticed there was an update to the pack.
> 
> Oh okay, ill try again then :3

Nope, just tryed again and is still causing a lot of lag :(

**Comment by DrunkTaank** [comment]
What version?  I'm running ATM 6 1.1.9b and it works fine

**Comment by firex20** [comment]
It works fine now with the new update from today :D
