### ISSUE TITLE
1.7.11 Crash on prayed plague doctor's death

### ISSUE THREAD

**Issue by AntidermisMC** [AllTheMods/ATM-6#2282]
v1.7.11

**Describe the bug**
Corail tombstone adds the ankh of pray, which, when you have good alignment (just kill pillagers until you get to the first bar in the tombstone compendium (not a book, see keybindings)) allows you to right click a villager (3h cooldown, no commands to shorten it) to "protect" them. Works on Rats' Plague Doctors but on death they will crash the game.

**To Reproduce**
1. Get good alignment
2. Use ankh of pray on a plague doctor
3. Kill him somehow
4. Crash

**Logs**
https://pastebin.com/WEF1VJ0N

Note: a disposal method is to use a plague tome to turn the doctor into the Black Death, which removes the effect without killing him.

**Comment by ladylexxie** [comment]
Seems like Tombstone has some issues with the AI for the Plague Doctor. Thankfully this won't ne a problem in 1.8.0 anymore.
