### ISSUE TITLE
Iron bees use lead comb for block-to-item mutations

### ISSUE THREAD

**Issue by EnderShadow** [AllTheMods/ATM-6#2284]
**Describe the bug**
Iron bees use lead comb as their mutation block instead of iron comb

**To Reproduce**
1. Look at the block-to-item mutations for the iron bee. It says it uses lead comb

**Screenshots**

**Additional context**

**Logs**
Please use a paste site for logs, instead of putting the file directly in the issue, not only is this easier but also means we can view on mobile when we are not at our computers.
Here's a list of some paste sites and their size limits:
    https://pastebin.com/ 512KB
    https://hastebin.com/ 400KB
    https://gist.github.com/ 100MB Requires member (Free)

**Comment by Pdiddy973** [comment]
will be fixed in 1.8.0

**Comment by Pdiddy973** [comment]
8009348c0e9a881060291a4ccabc24a015833da0
