### ISSUE TITLE
[1.7.11] Server crashes when loading chunks in one player's base

### ISSUE THREAD

**Issue by EnderShadow** [AllTheMods/ATM-6#2286]
**Describe the bug**
Whenever entering one player's base, the server freezes and crashes from a tick timeout. I already tried increasing the max tick time to 10 minutes, but that didn't resolve it. According to that friend, it MIGHT be an issue with loaded and unloaded chunks. There was also a large amount of framerate lag for 30 seconds or so when leaving and coming back to those chunks.

**To Reproduce**

**Screenshots**

**Additional context**

**Logs**
[https://pastebin.com/cjqMVGtz](https://pastebin.com/cjqMVGtz)

**Comment by ladylexxie** [comment]
What you could try is to go to `/world/serverconfig/forge-server.toml` and temporarily set `removeErroringEntities` and `removeErroringTileEntities` to `true`. That should remove any entity or block that might cause the error.

**Comment by EnderShadow** [comment]
I managed to solve it by setting a repeating command block to kill all clumps:xp_orb_big entities and slowly entered their chunks. It appears to be caused by the cyclic miner breaking blocks when in unloaded chunks adjacent to loaded chunks while connected to an AE2 system that is loaded there.
