### ISSUE TITLE
Ice and Fire Structures not generating

### ISSUE THREAD

**Issue by LilFuze9** [AllTheMods/ATM-6#229]
**Describe the bug**
Structures from the Ice and Fire mod are not generating in newly created worlds. Also, although I am unsure if this is indented  structures and content from the Rats and Waypoints mods are not generating in villages, but this content can be gotten without generation so it is less of an issue.

**To Reproduce**
1. Create a new world
2. Try to locate a structure like the Gorgon Temple using the /locate command
3. A message comes back and says "Could not find this structure nearby"

**Expected behavior**
These structures generating in newly created worlds.

**Screenshots**
![Can't Locate](https://user-images.githubusercontent.com/73490855/97204826-f9e00300-178c-11eb-911a-d1e3e12136f5.PNG)

**Comment by LilFuze9** [comment]
After looking closer I also couldn't find any of the biomes from Biomes o' Plenty or the biomes that are created with the mod pack. The mod Biomes You Go(BYG) seems to be the only thing generating. Is this intentional?

**Comment by LilFuze9** [comment]
After looking even closer I realize that I am indeed missing something and this is a feature.

**Comment by Thunder-Nova** [comment]
> After looking even closer I realize that I am indeed missing something and this is a feature.

@LilFuze9 
Yea it's a feature, and you really really don't want them in the overworld. The I&F mobs got highly boosted. 

They do spawn in The Other dimension, a nether version of the Mining dimension (No End version yet).
