### ISSUE TITLE
Mod-based metal nugget/ingot/block incompatibilities (ore dict-ish issue)

### ISSUE THREAD

**Issue by xenoflot** [AllTheMods/ATM-6#2290]
PackVer ATM6 1.7.11

**Describe the bug**
Some crafting processes (notably the smeltery) are / may be producing ingots and blocks that are from different mods than the ones created through workbench crafting. This causes a problem with having ingots and blocks from different mods, and quirky behaviour when using Compacting Drawers.

e.g. Bronze alloyed in a Smeltery produces a Mekanism block or ingot of bronze. If the Mek block is placed into a Compacting drawer, the drawer does not offer ingots or nuggets. If broken in the player 2x2, it will split into Thermal bronze ingots. If those are placed into a Compacting Drawer, it offers back Thermal ingots, Thermal blocks and AlltheCompressed 1x and 2x blocks, but not nuggets. In order to have the drawer offer nuggets, ingots and blocks (IMO the most common requirement), one needs to manually split the ingots into nuggets and put them into the drawer.

The problem is then that the drawer does not accept the Mekanism ingots or blocks from the Smeltery! Consequently, if a RefStor or ME system is using a Drawer Controller for bulk storage, ingots put into the terminal/grid will stored locally as the drawer network can't find a place for the Mekanism ingots.

I tested with Bronze but I've noticed this behaviour with several metals. I've not tested other methods of ingot/block production to know which mod's metals they output.

Sadly the Conversion Upgrade from storage drawers seems to have no effect. There's a bug report on the SD github that suggests functionality has been disabled for some time. Is suggest the ideal solution would be to tell the smeltery to produce Thermal Series metals rather than Mekanism metals. 

edit: I don't mind editing the scripts on my server config but I have no idea where to start. If someone can provide me with a template and a place to put it, I'm happy to do that myself.

**Comment by ladylexxie** [comment]
Thank you for the report, I fixed it and it will be available in 1.8
