### ISSUE TITLE
Requesters are not craftable

### ISSUE THREAD

**Issue by MrSwordCZE** [AllTheMods/ATM-6#2292]
Installed version: All the Mods 6 - 1.7.11

Elite, Ultra and Creative requesters (from the mods Cable Tiers) doesn't have recipe in JEI even tho there is an achievement in the Refined Storage tab to obtain them.

Recipe in Cable Tiers Curse web also doesn't work [link](https://www.curseforge.com/minecraft/mc-mods/cable-tiers)

**Comment by ladylexxie** [comment]
Something must be wrong with your installation. We tested it with multiple people and it worked just fine.
