### ISSUE TITLE
1.7.11 ver of modpack, duplication glitch using eternal stella

### ISSUE THREAD

**Issue by Ozyrys500** [AllTheMods/ATM-6#2294]
so I have found a duplication glitch when using an eternal stella on any item with durability, basically if you just shift click the item that is supposed to be enchanted by it in smithing table for it to go to your inventory it creates a copy of said item, both with indestructible enchant.

1. get an item on which eternal stella can be applied to
2. go to smithing table to apply it
3. when you want to get the end product instead of just clicking on it with a mouse shift click it so it goes into your inventory
4. get a copy of that item

Now I haven't tested it yet in single player, only on multi, so it might be just a lag issue with the server, but I still wanted it reported

**Comment by Ozyrys500** [comment]
so I have found a duplication glitch when using an eternal stella on any item with durability, basically if you just shift click the item that is supposed to be enchanted by it in smithing table for it to go to your inventory it creates a copy of said item, both with indestructible enchant.
1. get an item on which eternal stella can be applied to
2. go to smithing table to apply it
3. when you want to get the end product instead of just clicking on it with a mouse shift click it so it goes into your inventory
4. get a copy of that item
Now I haven't tested it yet in single player, only on multi, so it might be just a lag issue with the server, but I still wanted it reported

**Comment by ladylexxie** [comment]
Might just be something wrong with the server you're on, we cannot reproduce this in any way.
