### ISSUE TITLE
Generation of new chunks sometimes causing sudden biome & land switches 

### ISSUE THREAD

**Issue by Odey555** [AllTheMods/ATM-6#2295]
**Describe the bug**
New chunk generation & land switches suddenly at chunk borders. In the last version I played (1.6.12) this was rarer but now it seems to happen more often. 

**Screenshots**
![2021-09-06_15 14 46](https://user-images.githubusercontent.com/1361563/132251874-796d415f-493f-4db8-b4c5-d31c2184bc7e.png)
![2021-09-06_15 14 52](https://user-images.githubusercontent.com/1361563/132251878-2856deeb-90b8-4ad1-9c6b-5b6bfa190727.png)

**Logs**
    https://gist.github.com/Odey555/e58f65bc9b572ec33c6286b29ce027b6

**Comment by ladylexxie** [comment]
That is either through a sudden version update or because of the conflict between BYG and BOP. Next version of the pack should remove this occurrence.
