### ISSUE TITLE
Mystical Bee not pollinating

### ISSUE THREAD

**Issue by sharpskull2** [AllTheMods/ATM-6#2296]
Pack version 1.7.11
**Describe the bug**
Resourceful Bees mystical bee does not recognize livingrock block as its' flower and will not pollinate from it, JEI shows that it's flower is livingrock

**To Reproduce**
Get Mystical bee and place a living rock block for it to pollinate

**Screenshots**
![image](https://user-images.githubusercontent.com/31316990/132253607-25acf5ad-44bf-4306-836d-c2d4cf3e2725.png)

![image](https://user-images.githubusercontent.com/31316990/132253655-1d964e20-2b12-4ac4-a543-f27974450cb4.png)

![image](https://user-images.githubusercontent.com/31316990/132253693-2349d10d-aadf-4e15-9f81-fb08519cb182.png)
No mystical combs in top right drawer which is reserved for mystical combs, even though the bee has been flying around in the apiary for around 20 minutes

**Comment by sharpskull2** [comment]
![image](https://user-images.githubusercontent.com/31316990/132253851-67749ace-f52d-4d20-827f-79e4c34c6c46.png)
In the server config, livingrock is labeled as the bee's flower

**Comment by EnzoBenzo1** [comment]
Make a honey dipper and set the block to that bees flower.

**Comment by sharpskull2** [comment]
I've already used a honey dipper, it did nothing, it was the first thing I did

**Comment by ladylexxie** [comment]
Cannot reproduce, it is pollinating normally
![image](https://user-images.githubusercontent.com/30494658/132792736-176a8307-aec1-4278-b1d3-2b7308fedf6b.png)

**Comment by ladylexxie** [comment]
If you used a honey dipper, did you also select the apiary? Otherwise the bee considers itself without one and it will not go inside it.
