### ISSUE TITLE
teleport pad not working

### ISSUE THREAD

**Issue by KingofInferis** [AllTheMods/ATM-6#2297]
here sa log file the teleport pad isn't working I did everything 
[bug.txt](https://github.com/AllTheMods/ATM-6/files/7117589/bug.txt)

**Comment by KingofInferis** [comment]
https://drive.google.com/file/d/1IZF1PcZvhsMPQZMPnx4VF3wZr33KQ41V/view?usp=sharing here the g drive for the latest.log cause it wont fit in a paste bin

**Comment by notFalkon** [comment]
mining dimension is disabled so it's only use is to go to the Other (teleport pad in nether). and both hands need to be empty
