### ISSUE TITLE
Mekanism crusher can't process Sulfur from Thermal Expensions

### ISSUE THREAD

**Issue by koekwau5** [AllTheMods/ATM-6#2298]
Looking at previous reports it's been mentioned earlier and don't know if it actually got resolved.
If so then I think it's broken again, can only process the sulfur from Thermal Expensions with a Pulverizer which is insanely slow.
Does the Crushing Factory actually used to process them or is this normal?

**Comment by ladylexxie** [comment]
Added it for the release of 1.8

**Comment by LeadAssimilator** [comment]
This is still broken in 1.8.  The crusher takes thermal:sulfur and outputs thermal:sulfur - it should output thermal:sulfur_dust.
