### ISSUE TITLE
Explain Please

### ISSUE THREAD

**Issue by CanBoy67** [AllTheMods/ATM-6#2299]
**Describe the bug**
I'm having trouble with the 1.7.11 server pack, I've downloaded all of the files ran the server install file, and uploaded all the files to the server but for some unknown reason the server crashes saying that i'm missing files when all of the files have been downloaded and uploaded to sever.

**To Reproduce**
1. Downoad server pack and files
2. Start up server
3. see crashlog saying there are multiple missing files that aren't missing at all

**Screenshots**

**Additional context**

**Logs**
Crashlog: https://pastebin.com/0UWN1Hd1

**Comment by ladylexxie** [comment]
Seems like mods didn't upload correctly or have failed. This is pretty common with FTP transfers to servers.
