### ISSUE TITLE
Animal Feeder from Industrial Foregoing not feeding the animals

### ISSUE THREAD

**Issue by AnnIeNoaIm** [AllTheMods/ATM-6#230]
**Describe the bug**
The Animal feeder does not feed the animals. The progress-bar runs.. but my cows still do not get any wheat :)

**To Reproduce**
1. Set up a small animal-farm
2. place and power the feeder
3. insert animal food

**Expected behavior**
Expect to see the cows breed

I tried to place it on ground level and also 1 above ground level.. Does not make a difference. Tried to change out the range-upgrade too.. no difference.

**Comment by mtbrenner** [comment]
I can confirm this. See https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues/857
