### ISSUE TITLE
crashes after building a voidminer Tier 2

### ISSUE THREAD

**Issue by TrashMagpie** [AllTheMods/ATM-6#2300]
Hi, I have been playing all the mods 6 using version  1.6.14, I recently built a tier 2 void miner in the end dimension, I was powering it with 3 nitro thermo generators, with water being transferred to them with mekanism mechanical pipes and sinks. I left the dimension to set up the flash memory card to get it going and when I came back the pipes and sinks had all gone, I replaced these but was getting no power to the miner so reloaded the game, now every time I try to reload the game It crashes as soon as I load in with the crash report attached - https://pastebin.com/CVL132Ez

**To Reproduce**
1. go to the nether
2. build a Tier 2 void miner
3. leave the nether and return and items will be missing
4. 4 replace the items and re-launch the game from launcher
5. no access to the game with constant crash reports

**Screenshots**
![image](https://user-images.githubusercontent.com/90269560/132370969-0ff508a7-d1b4-4357-9773-deaa79ca6d08.png)

**Additional context**
I had had previous issues with using the Tier 1 void miner in the ATM mining dimension but these stabilised after relaunching the game from launcher

**Logs**
https://pastebin.com/CVL132Ez

**Comment by ladylexxie** [comment]
1.6.14 is a very old version, we don't support it and any issues you may have are most likely fixed in newer versions. The current version if 1.8.0.

**Comment by TrashMagpie** [comment]
Thanks the latest version showing on curse forge is 1.7.11 may I ask where I can find 1.8.0?

**Comment by ladylexxie** [comment]
> Thanks the latest version showing on curse forge is 1.7.11 may I ask where I can find 1.8.0?

It is currently only available on our public server. The download is available on our discord server.

**Comment by ladylexxie** [comment]
It will be released on CurseForge in a few days

**Comment by TrashMagpie** [comment]
thanks
