### ISSUE TITLE
Mekanism ores generating in 1.8

### ISSUE THREAD

**Issue by nddragoon** [AllTheMods/ATM-6#2301]
**Describe the bug**
Mekanism ores are generating along with All The Ores ores

**To Reproduce**
Generate a world in 1.8 and dig a bit

**Screenshots**
![2021-09-07_11 45 09](https://user-images.githubusercontent.com/54559451/132381835-44236dd4-476a-4d68-9df8-f85e83990b7b.png)

**Comment by ladylexxie** [comment]
This is fixed in dev.
