### ISSUE TITLE
All The Modium Teleport Pad just glows instead of teleport

### ISSUE THREAD

**Issue by icon942** [AllTheMods/ATM-6#2302]
V 1.1.8
**Describe the bug**
The pad does only glows when crouch right click and does not teleport

1.Place into nether or in overworld
2. Crouch right click 
3. See glowing

![2021-09-07_18 57 21](https://user-images.githubusercontent.com/40743790/132420841-2cf556c0-1229-4c04-84b1-471b1991d764.png)
![2021-09-07_18 57 27](https://user-images.githubusercontent.com/40743790/132420847-962bc729-5a99-4bb5-838b-435005f81340.png)

**Comment by icon942** [comment]
server was restarted multiple times and even deleted the OTHER

**Comment by ladylexxie** [comment]
1.1.8 is not a valid ATM-6 version. If you are playing Sky, I suggest reporting it to the Sky team [here](https://github.com/AllTheMods/atm6-sky/issues/new/choose).
