### ISSUE TITLE
How do I get Netherite Bee if it do not spawn in the world and do not have breeding?

### ISSUE THREAD

**Issue by PedrinhoLXD** [AllTheMods/ATM-6#2303]
I am doing the ATM STAR and I have to craft the wither compass, but i need the netherite bee to do it. 

Modpack version: 1.7.11

**Comment by ladylexxie** [comment]
Look at the uses for the Gold Bee, or the Beepedia. It's a Gold Bee mutation using a Block of Netherite.

**Comment by PedrinhoLXD** [comment]
TY
