### ISSUE TITLE
Which configs affect the generation of prismarine bee nests?

### ISSUE THREAD

**Issue by tanyan-tanyan** [AllTheMods/ATM-6#2304]
Modpack version: 1.7.11 / 1.8.0

Please help me with figuring out what configs to change in order to nerf the prismarine bee nest generation, I have tried the only 2 places that might be relevant and it has not affected the generation so far. I do not want to see more than 1 prismarine bee nest in the render distance of 20 chunks.

![image](https://user-images.githubusercontent.com/68793071/132603735-64b2f990-3ab7-4951-972e-e080aa8b4c28.png)

So far, I have tried the following:

**1. Nerfed the ocean mineshaft weight as the nests seemed to generate mostly above those**
`config > repurposed_structures-forge > mineshafts.toml`

Changed the ocean mineshaft weight to 10 (default 40)

**2. Nerfed the overworld bee nest generation**
`config > resourcefulbees > common.toml`

Changed the overworld nest generation weight to 70 (default was 40 or something like that)

**Comment by ladylexxie** [comment]
The file is not in configs, it's directly in the bees' files.
you can find it at `/config/resourcefulbees/bees/natural/bees_mob/Guardian.json`, and then you have `SpawnData`. If you want to make it rarer. decrease the `spawnWeight`. I will consider this for the public 1.8 release.
