### ISSUE TITLE
Rf tools builder bug 

### ISSUE THREAD

**Issue by Wakanlolz** [AllTheMods/ATM-6#2305]
Modpack version: 1.7.11

when i using Rf tools builder and start pumping using (shape card: pump), the build is pumping liquid without replacing dirt.

![image](https://user-images.githubusercontent.com/42348395/132614951-fc717dc6-a696-4387-bee7-5b4714cbad03.png)
On Wikipedia, this shape card should be replaced dirt after pump any liquid.

**Comment by EnzoBenzo1** [comment]
The wiki that you linked says "quarry card", the card you're referring to is pump which is not supposed to replace pumped liquid with dirt.

**Comment by Wakanlolz** [comment]
Sry my bad, i was just reading through the desc of the page.
![image](https://user-images.githubusercontent.com/42348395/132665183-4fd82766-8f07-4e5f-94c3-7c85aadc2366.png)
should be this page but ftb wiki don't have this page.
