### ISSUE TITLE
Caliburn Limit Break

### ISSUE THREAD

**Issue by F4LK5** [AllTheMods/ATM-6#2306]
Mod pack v1.7.0
When throwing Vibranium-Allthemodium alloy into the Power Consolidation lake from Mahou Tsukai before throwing in a Caliburn with smite, while having 23k mana available, the sword transforms as normal, ignoring the Alloy which should increase its limit.

Make a Power Consolidation Lake.
Enchant a sword with Smite.
Have more than 5k mana available.
Throw said sword into lake with up to four Allthemodium-Vibranium Alloy to increase innate limit.
Should return Caliburn with an innate limit greater than 10k (which is default)

It doesnt.

I first asked about this in the Mahou Tsukai curseforge comments Re; netherstars where i was informed it is vibranium-allthemodium.

**Comment by F4LK5** [comment]
Update; problem reproduced in creative in V1.7.9
Attempted using all 3 different alloy combinations in case of a misunderstanding from the person who informed me it was that.

**Comment by stepsword** [comment]
did you try the vibranium alloy block as well? I may have given you bad info on the curseforge page

**Comment by F4LK5** [comment]
I did not, I will try that next.

**Comment by F4LK5** [comment]
We got there in the end, thank you for your help.
I can confirm that it is in fact Allthemodium-Vibranium Blocks, and it is functional in 1.7.0.

Are we able to get that added to the Gameplay Guides? https://github.com/AllTheMods/ATM-6/wiki/General-Gameplay-Guides

**Comment by ladylexxie** [comment]
I will add it as a tooltip on the two swords. You should also update.. You're severely behind. Game is on 1.8 now

**Comment by F4LK5** [comment]
I am aware. I have been attempting to convince the host to update for a while now. Thanks.

**Comment by F4LK5** [comment]
Was this changed? I am on the latest version. 1.8.4. and the same process by which i confirmed it worked above, no longer works. The sword accepted the sword with smite but the blocks remained. Also there is no tooltip anywhere regarding the limit break ritual.

**Comment by ladylexxie** [comment]
> Was this changed? I am on the latest version. 1.8.4. and the same process by which i confirmed it worked above, no longer works. The sword accepted the sword with smite but the blocks remained. Also there is no tooltip anywhere regarding the limit break ritual.

The alloy changed to the ATM Star quite a while ago, yours probably worked because it was on 1.7.0.
I now added that to the tooltip as well. it will be in 1.8.6 on both Morgan and Caliburn.

**Comment by F4LK5** [comment]
> The alloy changed to the ATM Star quite a while ago, yours probably worked because it was on 1.7.0. I now added that to the tooltip as well. it will be in 1.8.6 on both Morgan and Caliburn.

Except it was also confirmed to work in 1.7.9 despite the fact the server I was on was stuck so far behind. But thanks for the update. Is there a reason its not mentioned in any of the changelogs from 1.8.0 (the oldest version that change could have occured) to now? Im not sure how anyone is expected to have this information even if it did change "quite a while ago"

**Comment by ladylexxie** [comment]
It changed much earlier than that. But it's a server config. Which means existing worlds have to manually do the change if they want to have that change. It's just how minecraft works.
