### ISSUE TITLE
Cant Put Items in my Pattern Terminal (AE2) form JEI

### ISSUE THREAD

**Issue by EinfachDave** [AllTheMods/ATM-6#2308]
https://gyazo.com/e477ff42f0ec64c799d94aa7f6fc93b4

I Used Mekanism For anexample but everyting els (Even AE2 Recepies) wont work. 
I Try to open the Recepies to Shift klic on the + Button to insert the Recepie (And Pressing R on the items wont work ether)

**Comment by EinfachDave** [comment]
Okay--- So items i Saved on my Left Side by JEI (With the O Button) are Working only The Right side is buggy

**Comment by radiomike** [comment]
This is normal behaviour for jei now. Use the `r` key to add recipes to patterns.
