### ISSUE TITLE
Mystical Agriculture not rendering properly and throwing errors

### ISSUE THREAD

**Issue by josephoaks** [AllTheMods/ATM-6#2310]
Ver 1.7.7
**Describe the bug**
Mystical Agriculture is not rendering properly, it shows growth rates but the plants are not being represented and are either fully grown or stuck in some state of the growth process.

**To Reproduce**
1. have an 11x11 farmland with center block a water source and water source surrounding the 11x11 
2. pedestals with fertility upgrades and lily pad of fertilization
3. using cyclic harvester and collector 

Error being report is 
"[Render thread/FATAL]: Error executing task on Client java.lang.NullPointerException: null"

**Comment by ladylexxie** [comment]
You are playing on a very old version of the modpack. Update to 1.7.11 or 1.8.0 and re-open if it happens.

**Comment by koekwau5** [comment]
> 
> 
> You are playing on a very old version of the modpack. Update to 1.7.11 or 1.8.0 and re-open if it happens.

Sorry to re-open this but version 1.8.0?
I can't find it on the Curseforge website and client, since I'm really looking into an update for the Void miner drawing insane amonts of power causing our progress to halt.
Can you tell me how to update to 1.8.0?

**Comment by ladylexxie** [comment]
It was on our discord to test before it went live on Curseforge around half an hour ago.
