### ISSUE TITLE
ATM6 server Invalid or corrupt jarfile serverstarter-2.0.1.jar

### ISSUE THREAD

**Issue by sh4ni** [AllTheMods/ATM-6#2311]
#1419 was closed by the Author, but it is still an issue.

You can download the jar file by hand and it will work, but it should not be necessary.

The script uses curl and I am on MacOS.

https://github.com/AllTheMods/ATM-6/issues/1419#issuecomment-857173310

Just add the -L option mentioned in this comment and this will be fixed.

**Comment by ladylexxie** [comment]
But if the original issue has been answered, why reopen it?

**Comment by sh4ni** [comment]
It has answered but it is still a bug within the server files and I have to fix it every time I set up a new Server.
It's also an issue for many others that may stumble on this too.

You need to add the -L option to the curl command in the startserver.sh file. That's all. Super simple fix.
I would create a pullrequest but haven't managed to find the startserver.sh file on the repositorys.

**Comment by radiomike** [comment]
You can also try installing `wget` too/instead.

**Comment by sh4ni** [comment]
...yes you could do that, but why then bother to include a curl section in the script in the first place? Makes no sense to leave it broken. This is literarily a two character fix.

Also, MacOS has curl pre installed, but not wget, which you need to install homebrew first so that makes it extra tedious.

**Comment by ladylexxie** [comment]
Apologies for the long delay on this matter, it will be fixed from 1.8.6 onwards.
