### ISSUE TITLE
weird error during initial setup

### ISSUE THREAD

**Issue by Dishcleanser** [AllTheMods/ATM-6#2312]
when i tried to run the 1.7.11 simple server files on my laptop everything went fine and the mods installed with every single setting i wanted, however, when i tried to do the same on my desktop, it failed, even when copy my completed install to the desktop it still won't work. i get the following error message after the loader tries to start java
![image](https://user-images.githubusercontent.com/87912628/132930551-eae6eae7-520d-4743-bb64-89ff738a5159.png)
how do i fix this, is this even something i can fix myself?

**Comment by ladylexxie** [comment]
You are using Java 16 which is not compatible with Minecraft 1.16. 
You can download a compatible Java version [here](https://github.com/AllTheMods/ATM-6/wiki/Java-Versions).
