### ISSUE TITLE
[Sugggestion, Nerf?] Diversity of ATM6 Weapon Meta

### ISSUE THREAD

**Issue by Notawallplan** [AllTheMods/ATM-6#2313]
**Is your feature request related to a problem? Please describe.**
Weapon and mod diversity in the meta (specifically weapons, but can apply to other things)

Morgans (and Caliburns) dominate the endgame meta right now due to their insane scaling. This leaves things like SGear in the dust comparatively.

**Describe the solution you'd like**

I feel that there should be a mod with ATM alloys (or Uru) that mimics their abilities to match.

**Describe alternatives you've considered**
Reducing/Introducing a penultimate cap on Caliburn-likes can help this too by adding a ceiling to their power.
Draconic Evolution (a mod recently added in the packver 1.8.0 pre-alpha) does help this as well by introducing a new power level before Caliburn-likes are on par/exceed them.
There can be a new alloy, based on Mahou, that you can coat/tip an SGear weapon with that applies the scaling as well, made from Caliburn-likes.

**Comment by derrickmehaffy** [comment]
I'll be that guy that says "please leave my morgan the f alone"
:rofl:

**Comment by ladylexxie** [comment]
I have now added more endgame materials for SGear and also a massive buff to Mjollnir.
