### ISSUE TITLE
Cannot make CC: Tweaked Wired Modem (partially solved)

### ISSUE THREAD

**Issue by bjmn55** [AllTheMods/ATM-6#2316]
**Describe the bug**
I am using pack version 1.7.11 on my local system, single player.
The recipe for the "Wired Modem" from "CC: Tweaked" is the same as "Futura (Uber Wavy)" from "Chisel".
When I attempt to make the aforementioned wired modem in a crafting station, it makes 8 futura from chisel.

**To Reproduce**
1. Go to a crafting station in game
2. Add a redstone dust in the center and surround that completely with 8 stone (regular minecraft stone)
3. When I add this recipe to the crafting station, which shows in JEI for the CC: Tweaked wired modem, it doesn't give me a wired modem :(

***Edit***
*The modem using this recipe can be made in a regular crafting table, but not in the Tinkers Crafting Station or any Applied Energistics crafting (I haven't tried any other crafting options). I like using Applied Energistics to craft everything and would like to be able to add this.*

**Screenshots**
The CC: Tweaked Wired Modem recipe in JEI
![wired modem recipe in jei](https://user-images.githubusercontent.com/217493/132936269-65dff368-0ab4-41f8-817a-bc358147cd04.png)

That same recipe added to a crafting station
![wired modem recipe added to crafting table](https://user-images.githubusercontent.com/217493/132936273-15d37db0-dc7e-411f-a21e-2c6bf46de0de.png)

**Comment by PopLamina** [comment]
Just use a crafting table, crafting terminal,etc. Polymorph (The mod that allows diffent items to use the same recipe) is not compatable with the tinkers crafting station.

**Comment by bjmn55** [comment]
Looks like it works in a regular crafting table as suggested, but not in any AE2 crafting, including the pattern terminal. I guess I can't automate it, but I only need a few so a crafting table works.

Not sure if I should close this as solved or rename it to reflect the AE2 issue...?
