### ISSUE TITLE
New SP world with Allow Cheats set to enabled doesn't have permissions for cheats or other commands

### ISSUE THREAD

**Issue by drysdan** [AllTheMods/ATM-6#232]
**Describe the bug**
When I go to start a new SP game for testing, and click the Allow Cheats button (default world style worldgen option), it loads me into a world, but I don't have permissions to use /give or /gamemode or enable cheatmode in JEI. 

**To Reproduce**
1. Go to 'Create New World'
2. Click on 'Allow Cheats'
3. Create and enter world
4. Attempt to use /give or /gamemode, or enable JEI cheatmode

**Expected behavior**
Ability to use /give or /gamemode commands, along with enabling cheatmode in JEI

**Additional context**
Have tried full deletion and reinstall via GD Launcher.  It worked properly the very first time I installed ATM6 and started an SP world, but every subsequent world does not work

**Comment by Poojawa** [comment]
Did you try the local lan -> cheat mode trick?

and if it's already enabled, try op -ing yourself. or just restarting the map. I had this issue trying to debug a server crash, and at some point restarting after enabling that gave me op powers and the like.
