### ISSUE TITLE
[1.8.0] Various problems / questions about the Creative Apiary and Draconic, Awakened and Chaotic bees.

### ISSUE THREAD

**Issue by iFalcon720** [AllTheMods/ATM-6#2324]
So problems:
- Draconium bee has wyvern fusion crafting injector both as its bee flower and the block it mutates to create an awakened bee. So occasionally the flower gets mutated and disappears.
- Awakened bee also mutates the wyvern fusion crafting injector to create a chaotic bee. 
- The creative apiary has the same gui issue that was in 1.7.10, but fixed in 1.7.11; The lock buttons affect other bees and importing doesnt always work.
And questions:
- Awakened bee in a creative apiary makes 10 combs, not 10 comb blocks (I think this is the same for chaotic bee). Not sure if thats intentional though.
- The creative apiary in 1.7.11 had a capacity of 100 bees and made 100 honeycomb blocks each time, but the one in 1.8.0 has 18 bees / 10 blocks. I assume that the 1.8 one is right, but was curious.

Sorry if any of this was fixed / changed for 1.8.1, haven't updated to it yet since its currently waiting on CF approval.

**Comment by EnzoBenzo1** [comment]
As to your question about the apiary, yes the one in 1.8.0 is correct.

**Comment by EnzoBenzo1** [comment]
The creative apiary gui issue should be reported to the mods git.

**Comment by EnzoBenzo1** [comment]
And the draconium bees using the same flower as the mutation is known and should be fixed.

**Comment by starforcraft** [comment]
> The creative apiary gui issue should be reported to the mods git.

What GUI Issue

**Comment by iFalcon720** [comment]
> > The creative apiary gui issue should be reported to the mods git.
> 
> What GUI Issue

https://i.gyazo.com/872873fd77e878fb335fa37dcd7f7d59.mp4
Looks like hitting the top lock affects the bottom and vice versa.

**Comment by ladylexxie** [comment]
> * Draconium bee has wyvern fusion crafting injector both as its bee flower and the block it mutates to create an awakened bee. So occasionally the flower gets mutated and disappears.
This is fixed in 1.8.2
> * Awakened bee also mutates the wyvern fusion crafting injector to create a chaotic bee.
Also fixed in 1.8.2
> * The creative apiary has the same gui issue that was in 1.7.10, but fixed in 1.7.11; The lock buttons affect other bees and importing doesnt always work.
This is for @starforcraft 
>   And questions:
> * Awakened bee in a creative apiary makes 10 combs, not 10 comb blocks (I think this is the same for chaotic bee). Not sure if thats intentional though.
This is intentional, draconic makes 10 blocks, awakened 10 combs and chaotic 1 comb
> * The creative apiary in 1.7.11 had a capacity of 100 bees and made 100 honeycomb blocks each time, but the one in 1.8.0 has 18 bees / 10 blocks. I assume that the 1.8 one is right, but was curious.
The previous 100 capacity and x100 multiplier was an unintentional bug

**Comment by starforcraft** [comment]
> > > The creative apiary gui issue should be reported to the mods git.
> > 
> > 
> > What GUI Issue
> 
> https://i.gyazo.com/872873fd77e878fb335fa37dcd7f7d59.mp4
> Looks like hitting the top lock affects the bottom and vice versa.

Oh that bug… I really don’t know why its happening..
