### ISSUE TITLE
Applied Energistics + Pneumatic Craft issue, Village meets Meteor. Version 1.1.6b 

### ISSUE THREAD

**Issue by DemgelZalvine** [AllTheMods/ATM-6#233]
[crash-2020-10-26_20.25.17-server.txt](https://github.com/AllTheMods/ATM-6/files/5443041/crash-2020-10-26_20.25.17-server.txt)

Not entirely sure how common this is. Yet here you go, pneumatic craft really doesn't like having a meteor slam into it. Winds up causing the crash you see up there, figured you all would like to know about this. Can't quite say how to repeat, so figured you could have the logs at least.

**Comment by jeremiahwinsley** [comment]
[crash-2021-01-15_23.54.11-server.txt](https://github.com/AllTheMods/ATM-6/files/5823471/crash-2021-01-15_23.54.11-server.txt)

replicated on the Allthemodium server with an Elementalcraft feature.
