### ISSUE TITLE
ATM6 1.8.x - Mek Crusher has broken thermal:sulfur recipe

### ISSUE THREAD

**Issue by LeadAssimilator** [AllTheMods/ATM-6#2331]
Mekanism Crusher in 1.8.x has a broken recipe output for thermal:sulfur.  

The crusher takes thermal:sulfur but outputs thermal:sulfur, where it should be outputting thermal:sulfur_dust instead.

_Originally posted by @LeadAssimilator in https://github.com/AllTheMods/ATM-6/issues/2298#issuecomment-917560328_

**Comment by EnzoBenzo1** [comment]
Known and should be fixed soon

**Comment by ladylexxie** [comment]
Will be fixed in 1.8.3
