### ISSUE TITLE
ATM6 1.8.2 server can't generate world

### ISSUE THREAD

**Issue by LeadAssimilator** [AllTheMods/ATM-6#2332]
**Describe the bug**
New download/install of ATM6 1.8.2 server files fails to generate world with exception:
`java.lang.RuntimeException: No key seed in MapLike[{"type":"mythicbotany:alfheim_generator","biome_source":{"type":"mythicbotany:alfheim_biomes"}}]; No key seed in MapLike[{"type":"mythicbotany:alfheim_biomes"}]`

This exception appears to be caused by a ~~datapack issue https://bugs.mojang.com/browse/MC-195717 or~~ bug in mythic botany.

This issue does not appear to affect the client/integrated server.

**To Reproduce**
1. Download SIMPLE-SERVER-FILES-1.8.2.zip
2. Extract
3. Run startserver
4. Accept EULA
5. Observe crash

**Comment by noeppi-noeppi** [comment]
See https://github.com/noeppi-noeppi/MythicBotany/issues/79

**Comment by ladylexxie** [comment]
This is a known issue, it is fixed in the next version of the pack. It will be out a bit later today.
