### ISSUE TITLE
1.8.x simple server files not compressed with subdir

### ISSUE THREAD

**Issue by LeadAssimilator** [AllTheMods/ATM-6#2334]
**Describe the bug**
The simple server files zip lacks a subdirectory.

Usually the server files are zipped inside a subdirectory `SIMPLE-SERVER-FILES-{VERSION}` but the 1.8.x files are not, and some other random releases are not.  The majority however follow the above pattern with a subdir.  All releases should follow the same paradigm, either subdired or not.

I'm guessing this comes down to who builds the releases.  I prefer the subdir'ed paradigm personally as it keeps things cleaner in case one forgets to create/change to an empty dir or specify a dest dir when extracting, which is easy to miss when doing everything from the commandline.

Whichever paradigm is agreed upon though, it should be scripted so all releases are consistent regardless of who builds it.

**To Reproduce**
1. Download the server files zip for a 1.8.x release
2. Observe the files are in the root of the zip
3. Download the server files zip for 1.7.11 release
4. Observe the files are in a subdir in the zip

**Comment by ladylexxie** [comment]
We changed maintainers for the pack, I will make it with a subdir from now on :)

**Comment by LeadAssimilator** [comment]
And 1.8.7.
