### ISSUE TITLE
Sophisticated backpacks

### ISSUE THREAD

**Issue by sicusmaximus** [AllTheMods/ATM-6#2338]
All the mods 6 1.8.0
Item compacter upgrade doesnt work
it simply doesnt compact the items when i put them in the backpack and ive tried filtering the item and also not and basically every combination of settings

**To Reproduce**
1. Open sophisticated backpack
2. Put in the compacting upgrade
3. filter item
4. put the item in the backpack

**Screenshots**
https://gyazo.com/ebf97afae77dd6fde9496ff81d2669f3

**Comment by radiomike** [comment]
Looks like you only have the basic compacting upgrade. That only does 2x2 compressing recipes. You need the advanced upgrade to do 3x3 recipes.
