### ISSUE TITLE
Impossible to Add Tinkers Book to Akashic Tome

### ISSUE THREAD

**Issue by pauloelr** [AllTheMods/ATM-6#2339]
If you craft an Akashic Tome it will come with the "Materials and You" book pre-loaded, but since now tinkers have other books, when trying to include it in the Akashic tome it simply doesn't work, the same happens if you remove "Materials and You" and try to merge it again

**Comment by ladylexxie** [comment]
That is because the Akashic Tome allows for 1 book per mod to be added, nothing we can do about it. Would require a full mod rewrite for that to work.
