### ISSUE TITLE
Ice and Fire dragon forge recipes do not show in JEI

### ISSUE THREAD

**Issue by sharpskull2** [AllTheMods/ATM-6#2340]
Version 1.7.11

Ice and Fire dragon forge recipes do not show up in JEI

Open Jei and try and find the recipes that are made in the Ice and Fire dragon forge

I was trying to find the recipes to make the allthemodium, vibranium, and unobtanium alloys, and then happened to remember that they were made in the dragon forge after not seeing any way to make them in jei

**Comment by Pdiddy973** [comment]
This is a I&F Bug and only applies on servers, SP should show the recipes just fine
