### ISSUE TITLE
Mining dimension portal not working

### ISSUE THREAD

**Issue by jaduvethan** [AllTheMods/ATM-6#2341]
im trying to get into the mining dimension, but cant get it to work? i dont have anything in my off hand or normal hotbar, i sneak right click and doesnt work. i tried doing the command /forge dimensions and it doesnt say its loading the mining dimension or the other, what should i do?

**Comment by radiomike** [comment]
Do you have any curios on you? It's possible that one of those is blocking you from using the portal.

**Comment by jaduvethan** [comment]
I dont really know what that is? But i dont think i do

**Comment by jaduvethan** [comment]
> Do you have any curios on you? It's possible that one of those is blocking you from using the portal.

I dont really know what that is? But i dont think i do

**Comment by Ranniv-M** [comment]
Bug 2348 is describing a similar issue, teleport pad doesn't work and other dimensions don't seem to be generating on world creation.

**Comment by ladylexxie** [comment]
This is being documented in #2348
