### ISSUE TITLE
[v1.8.2] Resourceful Bees - Problem with JEI and Beepedia

### ISSUE THREAD

**Issue by t4ggno** [AllTheMods/ATM-6#2342]
**Describe the bug**
Problems with bees. Open Bee-Receipes are not working (nothing happens within JEI) and opening the Beepedia will crash the client (see screenshots).

**To Reproduce**
1. Open JEI
2. Search for a bee
3. Try to check avaiable receipes
4. _(Nothing happens)_
5. Open Beepedia
6. **(Crash)**

**Screenshots**
![image](https://user-images.githubusercontent.com/14984216/133002891-4b02e520-a34e-4eea-a04b-db1dd8518150.png)

**Additional context**
With version 1.8.0 the JEI and Beepedia worked fine, but breeding had some problems. Today, with Version 1.8.2, I can breed some new bees, but I am unable to check receipes.

Additional: The receipe on V1.8.0 told me to use a flower on a Ender-Bee, but nothing happened.

**Comment by ladylexxie** [comment]
Please provide logs.

**Comment by Ash00182** [comment]
I'm not OP but also experiencing this issue. Note that the only individual crashing from this interacted with bees/beepedia in 1.8.0 whereas a user who opened the beepadia for the first time in 1.8.2 is perfectly fine. Here is the crash-report for said issue. I believe that when the user is interacting with the beepedia it is trying to reference registries that are no longer present as default bees were disabled and the files remove client/server side. 

[crash-2021-09-12_22.38.48-client.txt](https://github.com/AllTheMods/ATM-6/files/7161583/crash-2021-09-12_22.38.48-client.txt)

**Comment by ladylexxie** [comment]
The problem is either the server or their client didn't update properly and still has the default RBees bees generated, which should be deleted.
The files are in `/config/resourcefulbees/bees/` and delete all the `.json` files and leave only the folders.
