### ISSUE TITLE
cant start server

### ISSUE THREAD

**Issue by Creepdasheep** [AllTheMods/ATM-6#2343]
**Hi, I'm getting this error when I try to start up the server.**

Error: https://pastebin.com/neSKQ9yi
Full server log: https://easyupload.io/9ik55p

**Comment by EnzoBenzo1** [comment]
Will be fixed in next version

**Comment by Creepdasheep** [comment]
Okay how long until the next version

**Comment by Glitched94** [comment]
According to [this message 12 hours ago](https://github.com/AllTheMods/ATM-6/issues/2332#issuecomment-917624636), "later today"

**Comment by FireBladeYT** [comment]
1.8.3 will be released today?

**Comment by Cinicus** [comment]
Download the newest version of MythicBotany from curse forge. Install the new version to your server and remove the old version. Should fix the issue until they release the update for the pack.
