### ISSUE TITLE
Server failing to Upgrade from 1.7.11

### ISSUE THREAD

**Issue by AlexHailstone** [AllTheMods/ATM-6#2345]
**Describe the bug**

**To Reproduce**

1. Backup All The Mods 6 1.7.11
2. Remove all files except the world folder and start the 1.8.2 server file.
3. Crashes on loading resourceful bees mod.

**Screenshots**

**Additional context**
I have read the notes about 'recommended for new worlds' just wanted to upgrade instead of starting over. I JUST made it to end game and crafted 1 ATM star.

**Logs**
https://pastebin.com/YgzYyQRC

**Comment by ladylexxie** [comment]
Check [this](https://github.com/AllTheMods/ATM-6/blob/Staging/config/resourcefulbees/biome_dictionary/lake.json) file in your server, make sure they are the same as we have it on GitHub. That should fix the issue.
