### ISSUE TITLE
Compact Machines aren't Enterable

### ISSUE THREAD

**Issue by AlexHailstone** [AllTheMods/ATM-6#2347]
**Describe the bug**
The Personal Shrinking Device doesn't allow the player to enter any compact machine.

**To Reproduce**

1. Start a new SP game
2. Creative mode create the shrink device and 1 compact machine
3. Switch back to Survival
4. Place the compact machine down and try using the shrinking device on it

**Screenshots**
![image](https://user-images.githubusercontent.com/76534423/133021235-8cfecdcc-9e0e-4e28-b0d8-e130b027d54d.png)

**Additional context**
Might just be a bug, as this was working just fine on my MP 1.7.11 server.

Minecraft: 1.16.5
ATM 6: 1.8.2
Forge: 36.2.4

**Logs**

**Comment by mattbone71** [comment]
I also just posted about this also same thing but also teleporter pad not working

**Comment by ladylexxie** [comment]
Will be investigated and hopefully fixed in the 1.8.3 hotfix.

**Comment by ladylexxie** [comment]
This is being documented in #2348
