### ISSUE TITLE
[V1.8.2] Teleport pad not working and Compact Machines not working

### ISSUE THREAD

**Issue by mattbone71** [AllTheMods/ATM-6#2348]
**Describe the bug**
1.when shift clicking on the teleport pad does not teleport to mining dimension or other dimension.
2. when right clicking on compact machine does not teleport inside compact machine

**To Reproduce**
1. Place Teleport pad
2. Shift right click it nothing in hand or offhand 
3. Does not send you to mining dimensions or anything
4. Does not crash but in log a error appears

1.Place compact machine 
2. Right click with personal shrinking device from compact machines
3. Does not do anything like Teleport pad
4. Does not crash but in log a error appears

**Screenshots**
<img width="902" alt="dimensions of worlds" src="https://user-images.githubusercontent.com/10275260/133020886-b477e8c3-2809-41b6-945e-29ceb85d0ae2.PNG">

**Additional context**
I dug a bit and noticed when it generated my worlds i tested this multiple times it didn't generate any other dimensions I only figured this out because I was comparing it to atm6 to the sky since it worked there. Left of screenshot is the dimensions atm6 to the sky loaded for my world. right of screenshot is dimensions loaded on just atm6. screenshot in screenshots

**Logs**
https://gist.github.com/mattbone71/d24e2d3d9a758c839d3dc2cb2b2936b3

**Comment by ladylexxie** [comment]
Are you on singleplayer or server?

**Comment by Ranniv-M** [comment]
Single player worlds don't seem to generating other dimensions. I used creative mode to get teleporter pad on fresh world and tried to use it. Shift (to crouch) on pad, shift + right clicked, right clicked, all fail. No other dimensions are getting generated.

I haven't confirmed if the server files/multiplayer worlds are having the same issue.

**Comment by mattbone71** [comment]
ladylexxie im on singleplayer

**Comment by thevortex** [comment]
what is the worldtype you are using ?

**Comment by mattbone71** [comment]
I tried on multiple world types specific ones are : Realistic L. biomes, TerraForged, Default

**Comment by ladylexxie** [comment]
We are just having a hard time trying to recreate it... Tried TerraForged, Biomes O Plenty, server, singleplayer... nothing was able to recreate this. Both Teleport Pad and Compact Machine worked.

**Comment by mattbone71** [comment]
I had a feeling it would be hard to recreate it as when I searched it did not seem like an issue anywhere. and it also worked on atm6 to the sky so that's also odd

**Comment by mattbone71** [comment]
Alright so downgrading to 1.8.1 fixed it and the world is now generating all the dimensions its supposed to.
but when I updated back to 1.8.2 fresh install it did not generate them on world creation.

**Comment by Crookfuture** [comment]
> Single player worlds don't seem to generating other dimensions. I used creative mode to get teleporter pad on fresh world and tried to use it. Shift (to crouch) on pad, shift + right clicked, right clicked, all fail. No other dimensions are getting generated.
> 
> I haven't confirmed if the server files/multiplayer worlds are having the same issue.

im having the same issue but on a 1.8.2 multiplayer server. downloaded the server files off the CurseForge launcher

**Comment by 00danx** [comment]
I just created a world in 1.8.2. Could not load (using /tpx) in any dimension other than overworld, nether, the end, and AE2 space storage.
Used twilight forest, along with Compact Machines to test as it was not working as well.

I brought the save file back into 1.8.1 and it allowed me to go into the twilight forest and Compact Machines.

I then Brought the save to 1.8.2, to see if the twilight forest and Compact Machines still work. And the mine dimension also worked even though it did not work in 1.8.2 and did not try it in 1.8.1. 

Hope this helps in finding the bug.

**Comment by mattbone71** [comment]
00danx I just figured this out also did some testing found out you can re-create the 1.8.1 world in 1.8.2 and get a 1.8.2 world with working mining dimension and compact machines. you can also change the seed of the re-created world but not world type.

**Comment by ChemInventory** [comment]
It seems Mythic Botany broke the world gen, hence why dimensions you haven't visited yet and new servers don't work right as of 1.8.2. Updating Mythic Botany from 1.4.9 to the latest (1.4.10) fixed this for me.

**Comment by Dorrivix** [comment]
the fix above works for me as well. all dimensions generate properly.

**Comment by cpatton333** [comment]
I think this may be an issue with terraforge, the ATM 6 preset has include other dimensions set to no by default.

**Comment by ladylexxie** [comment]
The issue is caused by Mythic Botany. That Terraforged option is for terrain generation is custom dimensions.

**Comment by mattbone71** [comment]
updating to 1.8.3 fixed it for me
