### ISSUE TITLE
[RELEASE 1.1.8 - Current] Shift-clicking into regular furnace only works in top slot

### ISSUE THREAD

**Issue by Tman7077** [AllTheMods/ATM-6#235]
**Bug Description**
When in the inventory of a regular furnace (not a blast furnace or smoker, or modded interfaces), holding shift and clicking coal, which would normally be inserted into the bottom slot of the inventory, inserts it into the top slot. Even if I shift-click an item into the top slot first, and then the coal, the coal still does not go into its correct position. Small, but a slight annoyance, especially early-game with a manual furnace array.

**To Reproduce**
1. Right-click on a furnace to enter its interface
2. Shift-click a piece/stack of fuel, such as coal
3. Watch as it enters the "to be smelted" slot, not the "fuel" slot.

**Expected behavior**
As in Vanilla, I expected the coal to enter the bottom slot of the furnace, It does not.

**Additional context**
I have not added any mods, nor removed any, and the only configs I have changed are FTB Ultimine (set saturation use on ultimine to 0) and Quark (disable foxhounds). Everything else should be normal.

**Comment by LilFuze9** [comment]
I am not a member of the team, but I also have this problem. I'm assuming one of the the mods makes coal a smeltable item, which is likely why shift-clicking the coal puts it into the top slot. Hope this helps.

**Comment by WhitePhant0m** [comment]
Not a bug, as LilFuze9 stated, a mod makes coal a smeltable item, so it goes into to slot
https://gyazo.com/5bc98d16fbcfee2ec142657481b828e5
