### ISSUE TITLE
[1.7.11 & 1.8.2] Mystical Agriculture Recipies Using Soul Jars

### ISSUE THREAD

**Issue by Paddingtonnn** [AllTheMods/ATM-6#2350]
**Describe the bug**

Tested in 1.7.11 and 1.8.2
Mystical Agriculture recipes using soul/experience jars do not function correctly. 
Exp jars - will create the appropriate seeds even when empty 
Soul jars - jars do not seems to care if there's anything in them, and will create only one recipe from that tier (eg: both empty jars and pig jars create chicken seeds)

jei for these recipes also shows empty jars
![image](https://user-images.githubusercontent.com/66644394/133046232-a6aa7562-6523-45f5-a820-90ae43f2e65c.png)

**To Reproduce**
1. Set up an alter with the ingredients for a recipe involving soul jars (either empty or full)
2. Activate alter
3. Collect seeds

**Screenshots**
![image](https://user-images.githubusercontent.com/66644394/133045520-b2f92fa9-2255-4a4a-94af-9f96e9f00258.png)
*recipe for exp seeds running with empty jars*

![image](https://user-images.githubusercontent.com/66644394/133045719-9c78a955-f2f7-42f2-801b-8069190ffd45.png)
*recipe for pig seeds*
![image](https://user-images.githubusercontent.com/66644394/133045796-a11adf8c-fa9e-42ec-b68a-e707d9a029de.png)
*resulting chicken seeds*

**Comment by ladylexxie** [comment]
This is a known bug with the mod, the dev is working to fix it.
