### ISSUE TITLE
Failed sync

### ISSUE THREAD

**Issue by mjordan67** [AllTheMods/ATM-6#2356]
1.8.2
13.09 19:47:56 [Server] Netty Epoll Server IO #9/INFO [co.li.co.ConfigSyncManager/]: Skipping config sync, No mods have registered a syncable config.
13.09 19:47:56 [Server] Netty Epoll Server IO #9/WARN [co.co.Connectivity/]: Login payload for Registry minecraft:item is using 101.2636% of max allowed vanilla size and will cause errors during login if connectivity is not present on client side.
13.09 19:47:56 [Server] Netty Epoll Server IO #9/WARN [co.co.Connectivity/]: Login payload for Registry minecraft:block is using 76.2507% of max allowed vanilla size
13.09 19:47:58 [Server] User Authenticator #7/INFO [minecraft/ServerLoginNetHandler]: UUID of player Evilitis is 2e159e9f-7ac3-49c5-9f67-108c29ccb8d7
13.09 19:48:02 [Disconnect] User [minecraft/ServerLoginNetHandler]: com.mojang.authlib.GameProfile@655ff0d9[id=2e159e9f-7ac3-49c5-9f67-108c29ccb8d7,name=Evilitis,properties={textures=[com.mojang.authlib.properties.Property@416eb96e]},legacy=false] (/23.159.64.185:49709) has disconnected, reason: Disconnected
13.09 19:48:04 [Server] Server thread/INFO [tombstone/]: All players have been successfully backed up

**Comment by ScottSmudger** [comment]
Ive been getting this error recently.. any fix? ATM6 minecraft 1.16.5
