### ISSUE TITLE
1.8.2 Powah FE Requirments

### ISSUE THREAD

**Issue by cpatton333** [AllTheMods/ATM-6#2357]
ATM 6 1.8.2 Powah
When putting full blocks in the energizing orb (blaze mesh, diamond block, emerald block) it only takes 1 FE to change it to its powah version.

![2021-09-13_21 24 58](https://user-images.githubusercontent.com/3654318/133190040-d152f265-23dd-481e-ae2f-700f8585e2f9.png)
![2021-09-13_21 25 06](https://user-images.githubusercontent.com/3654318/133190041-d2c54445-bc8d-44e4-85b0-4346e0c07a8d.png)
![2021-09-13_21 25 13](https://user-images.githubusercontent.com/3654318/133190043-b4e5678b-158c-498d-a7ba-8d8a72d21311.png)

**Additional context**

**Logs**

**Comment by ladylexxie** [comment]
I fixed this in 1.8.3, thank you for reporting it.
