### ISSUE TITLE
No Unobtainum in End

### ISSUE THREAD

**Issue by gbusrt** [AllTheMods/ATM-6#236]
**Describe the bug**
All the Mods 6 - ATM6 - 1.16.3 
All the Mods 6-1.1.8
no Unobtainum found in End
2 releases earlier i had the same problem, i though it was just me so waited for a new release, got to the End today same thing 
i use the texture pack PureBDcraft 128x MC116 only thing i added
only way i could get the ore was to spawn it in , i spawned one in to check i was not missing it with just textures 
no luck
 drop texture pack no luck 
is this a known issue or just me
what file would be needed to see my current game 
not even sure were to start, do i just need to add the end dimension for other to see my issue

**Comment by gbusrt** [comment]
Just had a though 
how rare is it like one block per island 
or one block in 10 islands

**Comment by faaaaq** [comment]
It is extremely rare.  If you are confident it isnt spawning and need assurance, spawn in some unobtanium sight potions, pop into creative mode, and fly near the surface of the islands.  Youll find some.  Some islands youll find one, some youll find a ton (well, 3-5 or so).  It seems far more rare now than previously, but not terrible, especially when you can 3x the ore in an enrichment chamber.

**Comment by gbusrt** [comment]
humm 3 hours with potion and nothing found, my game hates me
i suspect its been made to rare

**Comment by ConnorTron110** [comment]
> and fly near the surface of the islands

This is not true, Unobtanium is normally located at the **bottom** of the floating islands. Its extremely rare and i can only find them by using sight and flying low with elytra under the islands. and i can only find 1-3 with one potion.

**Comment by alaa13212** [comment]
I got my first unobtanium searching the surface of floating islands only. I recommend getting a high tier jetpack

**Comment by rikislief** [comment]
I made a builder, and mine a complete outer island with an end city on it. it gave me 5 allthemodium (which were the only blocks not mined). I flew in and mined those with a mining gadget.

**Comment by demethan** [comment]
I used the RFtools builder and mined out 15y from the bottom 512x512. I got 8 blocks of unobtainium of it.  FYI!.

**Comment by WhitePhant0m** [comment]
As others said, Unobtainium generates, closing.
