### ISSUE TITLE
Game crashes not long after startup. ATM6-1.16.5/1.8.3

### ISSUE THREAD

**Issue by TheRocketier** [AllTheMods/ATM-6#2363]
**Describe the bug**
Everytime i open up ATM6 it crashes after loading for a short while, i'm not too sure why as i don't really understand the logs. 

**Screenshots**
![Capture](https://user-images.githubusercontent.com/90633094/133341797-bf67b888-6aaa-489e-80f7-5fcd41e55e56.JPG)

**Additional context**
I had this issue with the 1.8.2 version, i figured the 1.8.3 version would have fixed it but sadly not.

**Logs**
[2021-09-14-1(crash log).log](https://github.com/AllTheMods/ATM-6/files/7165443/2021-09-14-1.crash.log.log)

(Apologies for the raw log file, it was too big for pastebin.)

**Tower Specs**
![image](https://user-images.githubusercontent.com/90633094/133404511-65307e03-f94a-4b19-b7d4-490bfabff70f.png)
(Don't mind my motherboard temp, it's not correct i figured that out a long time ago.)

**Comment by fusionbolt18** [comment]
Same thing happening to me

https://pastebin.com/euPJ1At0

**Comment by radiomike** [comment]
@fusionbolt18 your issue is not the same, please open a new issue for it.

**Comment by radiomike** [comment]
@TheRocketier have you tried doing a fresh install into a new profile or instance?

**Comment by TheRocketier** [comment]
> @TheRocketier have you tried doing a fresh install into a new profile or instance?

I have indeed yeah, could try it again but I've had the issue with two separate installs.

**Comment by radiomike** [comment]
Looks like the curse launcher hasn't done a great job of installing the forge libraries, you could try repairing the install or look at using a different launcher. GD launcher or multimc are reccomended.

**Comment by TheRocketier** [comment]
Oh okay i'll try and do that, thanks for the heads up, I've not liked the new curse much just with the forced over wolf thing too so.

**Comment by Pdiddy973** [comment]
this should be resolved
