### ISSUE TITLE
Mystical Agriculture Seed recipes are messed up with new update

### ISSUE THREAD

**Issue by TheRevengersgirl** [AllTheMods/ATM-6#2365]
After updating to latest update, the recipes for the seeds that require filled soul jars are messed up. The recipes are showing empty soul jars instead. Which makes making seeds very hard. I tried to make fish seeds, which needs four jars full of fish souls and I ended up with rabbit seeds. HELP Please!

**Comment by dfrood** [comment]
To add to this, same thing happened with me but using creeper soul jars.

**Comment by radiomike** [comment]
This is a mod issue see <https://github.com/BlakeBr0/MysticalAgriculture/issues/447>

Try rolling back to mystical agriculture 4.2.1 as suggested
