### ISSUE TITLE
Missing structurize recipes after update

### ISSUE THREAD

**Issue by Jly4** [AllTheMods/ATM-6#2367]
All the Mods 6-1.8.2 

After update to 6-1.8.2, missing recipes for roofs and other blocks from different materials in structurize, there is only one oak roof left

If you run the game with only minecolonies, jei and structurize, the recipes are present
only with minecolonies, jei and structurize:
https://dropmefiles.com/SjUAD

After Update:
![2021-09-15_17 41 40](https://user-images.githubusercontent.com/65804380/133419352-4a9f92e5-73d9-4f8a-988f-df5be6d9a0f8.png)

**Comment by tanyan-tanyan** [comment]
IIRC that's intended because there was way too many recipes with them enabled. Did you check if you can craft a variant that's not in JEI?

**Comment by Jly4** [comment]
Могу, но я не помню всех рецептов

**Comment by ladylexxie** [comment]
All the recipes are still there, the only things that were removed were the pages from JEI to reduce clutter. The items were left there to give an indication to know you can use them to make other variants.
