### ISSUE TITLE
Soul Lava bee not working

### ISSUE THREAD

**Issue by TakeyaSaito** [AllTheMods/ATM-6#2368]
There seems to be something wrong with the soul lava bee, according to JEI it should just require soul lava to produce honeycombs however it seems to ignore the soul lava and do nothing. all the other bees seem to be working fine but not the soul lava bee.

**Comment by radiomike** [comment]
That sounds like normal behaviour for that bee. They are angry by default and angry bees don't pollinate or produce combs. Look for red eyes. 
You just need to find a way to calm it down.

**Comment by TakeyaSaito** [comment]
I also tried this, with soul campfire under the apiary and inside the apiary itself, no difference =/
