### ISSUE TITLE
Server lagging

### ISSUE THREAD

**Issue by FiNal-Here** [AllTheMods/ATM-6#2369]
So, yesterday I created a server running from my computer so I could play SLOP2 with my gf and I keep getting around 20 fps? I run on a machine with 32 gb of ram providing the pack with 12. How can I be lagging? And is there a way to change the values of ram in the serverstart.bat?

**Comment by ladylexxie** [comment]
There are so many problems with this ticket...

1. This is ATM6, not SLOP2
2. 12 GB is so overkill that I'm amazed it works with 20fps at all. Use 4-5GB. And yes, the more RAM you allocate, the laggier it becomes.
3. For changing the server's RAM, go to `server-setup-config.yaml` and you will need to edit `maxRam: 5G` to whatever you need. SLOP2 doesn't require a lot of RAM, so keeping it at like 3-5, is more than enough for the server.
4. To avoid lag in the longrun, use Java 11 (you can find it on our wiki) and use Java 11 args:
`-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true`
