### ISSUE TITLE
Not getting any Travelling merchants except for the first day. All other merchants walking in are Plague doctors.

### ISSUE THREAD

**Issue by rynarok** [AllTheMods/ATM-6#237]
**Describe the bug**
Travelling merchants came on the first 'week' of minecraft to my base. Afterwards when travelling merchant is supposed to visit, only plague doctors are visiting carring 2 rats on leads. Unsure whether its Rats mod overwriting the normal travelling merchant behavior. I would like to get my merchants back please.
**To Reproduce**
1. Just play for an extended amount of time. Had this reproduced on 3 saves already. Tried installing and reinstalling pack still happens. 
**Expected behavior**
Travelling merchants to show up. Thats all. Or if there are plague doctors that show up is ok as well, but not all the time.
**Screenshots**

**Additional context**

**Comment by WhitePhant0m** [comment]
Plague doc seems to just come more often, but the wandering trader still spawns

**Comment by GordonHollow** [comment]
have the same issue, no wandering trader at all, just plenty of plague doc.
2 saves, different version of ATM6, no wandering trader

**Comment by 06000208** [comment]
Same issue. Never seen a wandering trader, seen 10+ plague doctors over 100+ hours. Not sure if this is a real issue or just the perception of rare wandering traders vs. common plague doctors.
