### ISSUE TITLE
[1.16.5] [V1.8.3] My game will crash during the startup process.

### ISSUE THREAD

**Issue by fusionbolt18** [AllTheMods/ATM-6#2370]
**Describe the bug**
Whenever I launch the modpack the game will begin to startup. After a minute or two the game will crash. I also tried with a completely fresh install and the same thing happened. It also still happened after I restarted my computer.

**To Reproduce**
1. Launch the modpack (V1.8.3)
2. Wait a bit.
3. Crash.

**Additional context**
I use MultiMC.

**Logs**
https://pastebin.com/euPJ1At0

**Comment by radiomike** [comment]
Try with java 11 instead. That's the recommended version for this pack.

**Comment by rs3guy** [comment]
I had the same issue. Using Java 16 and multimc. Last month it worked fine, this update crashed on launch. 

Took radiomike's advice and downloaded Java 11. Seems to works a charm, cheers :)
