### ISSUE TITLE
Allthemodium Alloy Recipes Gone

### ISSUE THREAD

**Issue by ThePhantomOTO** [AllTheMods/ATM-6#2371]
There are no recipes for the combines alloys for Allthemodium, Vibranium or Unobtanium. If you just put the items into the dragon forge to make it based on previous version's recipes, you get Ash.

This is in ATM6 v1.7.11

I haven't tested this in the latest versions as my server is on 1.7.11. The newer versions needs a fresh world install which would cause me to lose everything I have in this version. Does anyone have a way to modify config files and get this working again on my server for this version?

**Comment by SlackerNet** [comment]
you dont need a new word for ver 1.8........as long as you reuse server properties and the world the update will go fine. We did our server yesterday. You wont have the ore gen for the draconic mod so resetting the mining, nether and end dims will allow the new ores to generate in those dims. as far as i know the dragon forge was working fine in 1.7.11

**Comment by ThePhantomOTO** [comment]
Thank you for letting me know a successful world update is possible. Right now, updating isn't going to work for me as the removal of More Red and Rats will affect a lot of people. Right now, I am just looking for a solution to the Allthemodium different Alloy smelting as that part of the Dragon Forge is what isn't working. I cannot make the combination of Allthemodium with Vibranium or Unobtanium and so on currently. They just get turned to Ash within the forge. 

Has anyone else figured out how to fix this in version 1.7.11?

**Comment by Pdiddy973** [comment]
It's a server only issue, all I&F dragon forge recipes don't show. But they still do work.

**Comment by ThePhantomOTO** [comment]
I am not able to make any of the Allthemodium alloys in the Dragon Forge. As I mentioned, putting an ingot of each items into the correct forge and placing the Dragon in place, only makes the item frozen or ash. It doesn't make the Alloy. I tried with the dust too and same thing.

**Comment by Pdiddy973** [comment]
the ingots need to be in the correct order, and in the correct forge, if you load into SP you can see them or check the gameplay guide in the wiki

**Comment by ThePhantomOTO** [comment]
As far as I know, I am putting them in the correct order and forge. This is what happened in the Ice Dragon forge with one ingot of each Vibranium and Unobtanium.

I cannot get into single player mode to check the recipes as the game keeps crashing when even attempting a brand new world. Where is the Wiki that shows this information if I have the receipts wrong.

 Ice Dragon Forge - Vibranium and Unbotanium
 Fire Dragon Forge - Vibranium and Allthemodium
 Lightning Dragon Forge - Unobtanium and Allthemodium
 
![Ice Dragon Forge 01](https://user-images.githubusercontent.com/73863326/133687367-ef247d7a-6e53-4602-b44b-85dfaae09156.png)
![Ice Dragon Forge 02](https://user-images.githubusercontent.com/73863326/133687370-75b25650-51ad-4432-bafa-3d60a2789b0b.png)

**Comment by radiomike** [comment]
>Where is the Wiki that shows this information if I have the receipts wrong.

Look up, between `projects` and `security`? 

There's a direct link here <https://github.com/AllTheMods/ATM-6/wiki/General-Gameplay-Guides>

**Comment by Pdiddy973** [comment]
Also you can use AllTheCompressed blocks to bulk craft, those have both recipes too so order doesn't matter
