### ISSUE TITLE
Ars nouveau and tome of blood version not compatible

### ISSUE THREAD

**Issue by YashTFEM** [AllTheMods/ATM-6#2373]
When I tried using a second tier tome of blood to cast a projectile harm spell, it crashed my game. When I looked at the logs I felt version incompatibility. I made no changes, note did I add anything to ATM6

LOGS
https://gist.github.com/YashTFEM/a6d91e2acd5332df87c18db804c62edd/raw/14b7650ad2a8fd3cb8e9796eb539521e224034ee/Log

**Comment by ladylexxie** [comment]
That's not a crashlog, you should report it to the devs of the Tome [here](https://github.com/MintTeaTx/Tome-of-Blood/issues/new/choose).
