### ISSUE TITLE
Allthemodium, vibranium, unobtainium doesnt seem to give proper armor bonuses.

### ISSUE THREAD

**Issue by Mesmam** [AllTheMods/ATM-6#2374]
When I put on this armor in all the mods 6 its doesnt seem to give extra armor and armor toughness bonuses my friend hits me with an iron sword or his fists and deals 2 damage when i have a full set of unobtainium. Just very confused would like to know why this is happening or if there is a mod conflict.

**Comment by Mekenzie** [comment]
having the same issue in my own server and single player

**Comment by ladylexxie** [comment]
This is due to how Minecraft's armor reduces damage. We are still trying to come up with a way to get around this issue, but until Mojang fixes it, it's not a lot we can do.
