### ISSUE TITLE
There seems to be something wrong with the soul lava bee, according to JEI it should just require soul lava to produce honeycombs however it seems to ignore the soul lava and do nothing. all the other bees seem to be working fine but not the soul lava bee.

### ISSUE THREAD

**Issue by mattbo123** [AllTheMods/ATM-6#2375]
**Describe the bug**

**To Reproduce**

**Screenshots**

**Additional context**

**Logs**
Please use a paste site for logs, instead of putting the file directly in the issue, not only is this easier but also means we can view on mobile when we are not at our computers.
Here's a list of some paste sites and their size limits:
    https://pastebin.com/ 512KB
    https://hastebin.com/ 400KB
    https://gist.github.com/ 100MB Requires member (Free)

**Comment by Pdiddy973** [comment]
the bee needs a calming effect via potions or beecon... bees cant pollinate when angry/red eyes
