### ISSUE TITLE
Mod Mismatch error.

### ISSUE THREAD

**Issue by Yamanipanuchi** [AllTheMods/ATM-6#2379]
I am using SIMPLE-SERVER-FILES-1.8.3.zip to deploy a docker for this server. I have the client updated to the reported correct version but I have getting the following error when I try to enter the server.

![image](https://user-images.githubusercontent.com/4724631/133673702-45186630-ff3e-435c-97d0-1e00f5c47f2c.png)

**Comment by radiomike** [comment]
Looks like you have different versions of at least silent gear on your client and server.
Which launcher are you using for the client?

**Comment by Yamanipanuchi** [comment]
Were using Curseforge/Overwolf? We've tried on multiple systems.

**Comment by Yamanipanuchi** [comment]
I tried manually downgrading Silent gear on the clients and we get a further error regarding a Dependency. I stopped there as I didnt want to get to far into modifying the pack files.

**Comment by Pdiddy973** [comment]
Try and use Gdlauncher, it's generally better at downloads/updates then curseforge

**Comment by radiomike** [comment]
Apologies, on mobile, but just been able to double check. The version you have on the server is wrong, try re-doing the server install following https://github.com/AllTheMods/ATM-6/wiki/Pack-Upgrade-FAQ

**Comment by Yamanipanuchi** [comment]
The server is using a docker image, It downloads the manifest file and then installs the mods accordingly. I am going to guess there's a chance the manifest file is incorrect for the server.

The file SIMPLE-SERVER-FILES-1.8.3 has a file named "server-setup-config.yaml" that instructs the docker to download "https://media.forgecdn.net/files/3459/526/All+the+Mods+6-1.8.3.zip" which has a manifest of all the mods needed.

Unless the docker isn't replacing the file correctly. Ill check that part.

**Comment by Yamanipanuchi** [comment]
I tried to manually copy the mod into the Mods folder, But being a docker its going to run that script at start up and Re-sync all the mods again effectively putting that .30 version of silent gear back in.

**Comment by Yamanipanuchi** [comment]
Ya, It didnt work. It gives an error on the manifest because the mod list is different.

![image](https://user-images.githubusercontent.com/4724631/133694359-94dbf857-de47-4aa2-8ec7-b4aaf12b4b0c.png)

**Comment by radiomike** [comment]
If that mod is wrong, then it's likely the wrong Manifest/server files - should be forge 36.2.4 for i instance. Something that may be catching you out is that the latest server download returned to having contents in a subfolder, not the root of the zip file.

**Comment by Yamanipanuchi** [comment]
Ya, I placed Silent Gear .31 back in to the folder and the server starts up with no issues. Silent Gear .31 is a Beta, .30 is Release. Dont know if this is a Mistake, or the Manifest just has the wrong Mod listed?

**Comment by Yamanipanuchi** [comment]
Ill see about fully downgrading Silent gear on the Client side for now. Ill just need to figure out the dependencies.

**Comment by radiomike** [comment]
Pretty sure you are using the old Manifest. Because of the change in file structure for the server download, it's probably not overwriting the Manifest or yaml file as you are expecting.

**Comment by Yamanipanuchi** [comment]
So you probably are correct, I copied my world folder over and wiped the entire build away and Re-build it. Then copied my world BACK in and its working. Guess upgrading a docker works different than I thought it would.

Thanks to all who helped.
