### ISSUE TITLE
Cyclic missing recipes for various cables/tubes

### ISSUE THREAD

**Issue by Gibblesnatchz** [AllTheMods/ATM-6#2380]
Hello,
I'm currently running the most recent version of ATM 6, Version 1.8.3, and it appears as though I am missing recipes and the ability to craft Cyclic specific fluid, energy, & item cables for hooking various machines together. For instance, I need to craft several "Crystalized Amber" for various recipes, so I crafted the Solidification & Melting Chambers and hit a dead end as I have no way of hooking them together...I went as far as to craft other mod pack's cables, tubes, and the like in an attempt to see if any would work. No dice... Anyways, any help would be super appreciated and I'm really hoping that I'm just overlooking something, but I've researched and looked into this a lot before making this post and all videos, and info I found on this, people were making everything work using recipes I flat out don't see! Please help, Thanks!

**Comment by Pdiddy973** [comment]
Cyclic pipEs were disabled since they are very laggy. Other mod pipes do work fine. Make sure you use the right side.

**Comment by Gibblesnatchz** [comment]
Awesome, thank you for the quick response! Which pipes do you recommend? I tried the “Pipez” fluid pipe (turquoise in color) and those did not seem to work, same with the “Create” fluid pipes. All of the Mekanism stuff was too involved and I needed too much from that mod to try those out…I’d love any suggestions/recommendations.

**Comment by Pdiddy973** [comment]
Pipez should work, melanism ones should too.
