### ISSUE TITLE
Uncrafting table(The Twilight Forest) bug

### ISSUE THREAD

**Issue by D8D9** [AllTheMods/ATM-6#2381]
Put a equipment parts(Silent Gear) into the uncrafting table(The Twilight Forest) to get Allthemodium.

1. craft an iron pickaxe parts
2. put it into the uncrafting table
3. clicking on "next page" 
4. put another pickaxe-blueprint into the uncrafting table
5. get a allthemodium pickaxe parts
6. put it into Salvager(Silent Gear)
![atm1](https://user-images.githubusercontent.com/90909599/133783697-ba14a630-5bfd-41eb-8bb7-eb2c9356c082.png)
![atm2](https://user-images.githubusercontent.com/90909599/133783706-9d3bb508-ed34-4b88-9096-6c8c7ed7ea1e.png)
![atm3](https://user-images.githubusercontent.com/90909599/133783725-f9df2b0c-9555-46ed-b489-b778bc284812.png)

**Comment by ladylexxie** [comment]
What version are you on? The Uncrafting table was disabled months ago.

**Comment by D8D9** [comment]
1.8.3

**Comment by D8D9** [comment]
> What version are you on? The Uncrafting table was disabled months ago.



> What version are you on? The Uncrafting table was disabled months ago.

1.8.3

**Comment by ladylexxie** [comment]
This was either cheated in, or left from a very long time ago. It is no longer reproduceable.
