### ISSUE TITLE
Minecolonies minimum stock feature crashes game

### ISSUE THREAD

**Issue by Psychicbear** [AllTheMods/ATM-6#2382]
Pack version: 1.8.0
**Describe the bug**
Attempting to add to minimum stock in minecolonies buildings causes game to crash

**To Reproduce**
1. Open any minecolonies building block that can set minimum stock (eg. restaurant)
2. Click on minimum stock tab
3. Click add button
4. Game hangs with "saving world" on screen before crashing

**Screenshots**
![image](https://user-images.githubusercontent.com/50544746/133862541-e2c73332-f622-40eb-8378-f370d19b57c4.png)

**Additional context**
From brief searches, (see https://www.reddit.com/r/Minecolonies/comments/powugh/my_game_keeps_crashing_whenever_i_try_to_set_the/) the bug can supposedly be fixed by updating to a newer version of minecolonies. I am happy to do this manually for myself but I run a server where getting everyone to do this is difficult.

**Logs**
https://pastebin.com/xsR54ieU

**Comment by ladylexxie** [comment]
This should be reported to the mod author.

**Comment by AbdulmajeedAlOmari** [comment]
@Psychicbear I have created an issue for this bug in the Minecolonies repository in here https://github.com/ldtteam/minecolonies/issues/7606

We're still struggling this this issue even after we updated to the latest ALPHA version of the mod.
