### ISSUE TITLE
Disk Drives aren't getting power from the controller (Refined Storage)

### ISSUE THREAD

**Issue by eddybash** [AllTheMods/ATM-6#2389]
Yo, so I'm playing on 1.16.5, been playing on it for the last 3-4 months, and never had a problem.  But all of a sudden, my rs stopped working.  When I checked my controller, it says it's not giving any power to any of my Disk Drives.  I've tried breaking it down to the Controller, Disk Drive, and Grid, but it still doesn't give any power.  I even moved it to another chunk but it didn't do anything.  It only just started today when I started up the game.  

If anyone knows how to help, please let me know, it would suck to lose all my progress.  
Thanks

**Comment by ladylexxie** [comment]
What version are you playing on?
