### ISSUE TITLE
Plant Gatherer chops leaves of fir trees not it working area

### ISSUE THREAD

**Issue by SjioGG** [AllTheMods/ATM-6#239]
Hi,

Encountered this weird bug

![2020-10-28_10 42 20](https://user-images.githubusercontent.com/72309168/97420039-15711800-190b-11eb-91ce-6733e5441688.png)
![2020-10-28_10 42 37](https://user-images.githubusercontent.com/72309168/97420048-16a24500-190b-11eb-8822-08896de06e4d.png)
![2020-10-28_10 42 02](https://user-images.githubusercontent.com/72309168/97420060-1ace6280-190b-11eb-9ba5-c662bb185ebd.png)

**Comment by Pdiddy973** [comment]
seems resolved in 1.3.9
