### ISSUE TITLE
The Twilight Forest Portal doest work

### ISSUE THREAD

**Issue by simonlkch** [AllTheMods/ATM-6#2391]
I am using the version All The Mods 6-1.8.3

Test on Online server and single player, the portal is does't work.
When i jump into the portal entry, 
player does't transfter to forest map.
Here is the screencap.
![image](https://user-images.githubusercontent.com/3492546/133891935-6e631fe3-56ed-47b9-9dac-8fc22ac07ed6.png)

**Comment by xstarlin** [comment]
What dimension are you in

**Comment by Dorrivix** [comment]
This looks like the mining dimension, try making the portal in the overworld dimension instead.

**Comment by ladylexxie** [comment]
Is this still an issue?

**Comment by simonlkch** [comment]
> What dimension are you in

The Twilight Forest dimension

**Comment by simonlkch** [comment]
> This looks like the mining dimension, try making the portal in the overworld dimension instead.
> 
> edit: on second thought, this looks like a flat world. I don't think flat worlds generate dimensions other than the vanilla nether and end.

In my case is overworld  to The Twilight Forest dimension,
for your 2nd point, i try in the overworld  not, flat world

**Comment by simonlkch** [comment]
> Is this still an issue?

Yes, Still happen, any information or log should i provide for further investigate?

**Comment by ladylexxie** [comment]
If you go to `/saves/world/dimensions/` do you see the `twilightforest` folder? If so, do you have 2 folders inside that?

**Comment by simonlkch** [comment]
> If you go to `/saves/world/dimensions/` do you see the `twilightforest` folder? If so, do you have 2 folders inside that?

no, don't have twilightforest folder

**Comment by ladylexxie** [comment]
In that case, try making a new save and copy over the `twilightforest` folder. Let me know if that worked :)

**Comment by simonlkch** [comment]
umm.. can put this new world of twilightforest folder on Server??

**Comment by Gravel789** [comment]
I found that updating the modpack version to version 1.8.4 fixed the twilight forest portal glitch as I had the exact same problem as you said you had (portal would open but would not transport to twilight forest), I do not know if this will work on a server but it does in fact keep your old save (I used 1.8.2 before updating to 1.8.4) so do create a copy of your world save just in case.
