### ISSUE TITLE
world loading getting stuck in 100% after update

### ISSUE THREAD

**Issue by Kreitin** [AllTheMods/ATM-6#2392]
version: 1.8.3
i just updated the pack from 1.7.11 to 1.8.3, and when i try to enter my world in the new version, it just gets stuck at 100% and never loads, the cpu usage goes down to less than 1% just freezes at 100% loading of the world. it doesn't crash, only closes when i terminate it in task manager

**this update removed some mods(rats, chiseled, morered and reauth).I tried to remove and trash most of the itens i had from them, so i don't think it must be much of a problem**

**Logs**
https://gist.github.com/Kreitin/3b8826c21767afd13a82e309ed9bc2db

**Comment by radiomike** [comment]
Try without sodium and see if that helps.

**Comment by Kreitin** [comment]
it worked, thanks, i didn't evem remember i had added sodium
