### ISSUE TITLE
Silent Gear Elytra in bauble "back slot"

### ISSUE THREAD

**Issue by kryldost** [AllTheMods/ATM-6#2393]
Pack version 1.8.3
**Describe the bug**
Disconection loops

**To Reproduce**
1. Go to 'inventory'
2. Click on 'baubles'
3. Scroll down to 'armor slot and put silent gear elytra in.'
4. Unable to locate field fallFlyTicks (fallFlyTicks) on type net.minecraft.entity.LivingEntity

**Screenshots**
No screenshots available

**Additional context**
The elytra I made is a silent gear elytra, it is made of 4 phantom membrane and I used a string as the binder. It also only happens when equiped in the armor slot of the baubles. When equiped as a chestplate it does not throw me in a disconection loop.

**Logs**
The error only appears in server side logs, my launcher shows no logs related to the disconnect.

"Unable to locate field fallFlyTicks (fallFlyTicks) on type net.minecraft.entity.LivingEntity"

**Comment by Dorrivix** [comment]
this happens in single player too, however, it crashes the game instead of a disconnect. though I can notice a 'ticking player' error in the crash log.

**Comment by ladylexxie** [comment]
This is a mod issue and has been reported to the devs.
https://github.com/SilentChaos512/Silent-Gear/issues/432
