### ISSUE TITLE
Mending Enchant  Unobtainable through Normal Means

### ISSUE THREAD

**Issue by pelhamk** [AllTheMods/ATM-6#2395]
Pack Version 1.8.3

Obtaining the mending enchant by directly enchanting an item or book is impossible. 

After having spent an entire day in a single player world enchanting various items and using various enchantment table set ups, I can confirm to not have gotten mending 1 time out of thousands of items enchanted. 

My assumption is, after loads of testing, that the Natures Auras mod replaces any enchanted instance of mending with Nature’s Mending. 
Which is, in my mind, useless. 

Mending can be obtained through luck if it is found on an already generated item. In my main world, I obtained it twice. Once through a villager that sold me a highly enchanted sword. An another through a pick I found in a chest. 

The enchantment works and is still in the game. It just cannot be obtained through enchanting.

**Comment by 19175** [comment]
This is working as expected.
Even in Vanilla Mending is only obtainable as a 'treasure' enchantment, so either looting it from mobs or chests, villager trading or fishing.

You can find more information on [its wiki page, here](https://minecraft.fandom.com/wiki/Mending)
