### ISSUE TITLE
Server NotStarting/Crashing/Lagging

### ISSUE THREAD

**Issue by GoMini-01** [AllTheMods/ATM-6#240]
So far we where not able to run this Pack on a multiplayer Server. The Includet Java Arguments are only useable running Java8. On up to date versions of linux/debian/ubuntu the nativ version would be Java11 wher different arguments are needet.

 Specs of the Server:
Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
Vm Running on 6 Cores
16 Gig RAM
400 Gig SSD
400Mbit/s up-/downlink

Pack version: All the Mods 6 - ATM6 - 1.16.3   V: 1.1.8

I was only able to get the server running at all with 3 different setups:
1) delete all java arguments in the includet installer running Java11
    --> Server running pooly at 100% cpu usage on one core with TPS around 13.
          After one crash the server wouldn start at all.

2) Running Java8 with original java args:
    --> Same as before but after exploring a bit the server was running so many ticks behind at some point it crashed do to taking over 60s per tick.

3) Using custom start script (see atachment) (includet one uses to much inconsistend and useles stuff not controlable in an sinple way) with optimized Java11 arguments.
    --> Same as befor including some times it wont start at all without crashreport or log.

Tried exporting the mods an greating seperate Forge server without anny luk geting it to run at all.

[Start.txt](https://github.com/AllTheMods/ATM-6/files/5452156/Start.txt)

**Comment by godleydemon** [comment]
set tick length in server.properties file to -1. It means your getting a tick that's getting stuck abnormally long and the server is shutting down/crashing in order to free it up. Alot of times, if given just a little more time it'd be fine. Alot of times, you wouldn't even notice the tick being stuck lol. But setting max-tick-time to -1 makes it to where it'll never crash on tick timeouts. Conversely you need to keep a better eye on it, so that it doesn't freeze and do nothing at all for hours on end. I do an auto restart every 6 hours.

**Comment by GoMini-01** [comment]
> 
> 
> set tick length in server.properties file to -1. It means your getting a tick that's getting stuck abnormally long and the server is shutting down/crashing in order to free it up. Alot of times, if given just a little more time it'd be fine. Alot of times, you wouldn't even notice the tick being stuck lol. But setting max-tick-time to -1 makes it to where it'll never crash on tick timeouts. Conversely you need to keep a better eye on it, so that it doesn't freeze and do nothing at all for hours on end. I do an auto restart every 6 hours.

Ok thx, i'm going to try that. But what would you recomend for start options as using Java 11 proabably would be best do to some good improvments in performance. Are ther any other hints on how to get the pack running with higer tps?
Regards Malte

**Comment by godleydemon** [comment]
> > set tick length in server.properties file to -1. It means your getting a tick that's getting stuck abnormally long and the server is shutting down/crashing in order to free it up. Alot of times, if given just a little more time it'd be fine. Alot of times, you wouldn't even notice the tick being stuck lol. But setting max-tick-time to -1 makes it to where it'll never crash on tick timeouts. Conversely you need to keep a better eye on it, so that it doesn't freeze and do nothing at all for hours on end. I do an auto restart every 6 hours.
> 
> Ok thx, i'm going to try that. But what would you recomend for start options as using Java 11 proabably would be best do to some good improvments in performance. Are ther any other hints on how to get the pack running with higer tps?
> Regards Malte

Well your main problem here in trying to run any of this on java 11, is that nothing is written for it. Everything for minecraft runs natively on java 8, it's weird, everyone agrees it's weird, but it's to weird now to change it. The default flags that atm6 provides in there server launcher is actually pretty good. Most of what your limited on though is cpu I think, as the ram amounts aren't as much as you'd think. That's where I'm bottle necking currently, CPU speeds.
