### ISSUE TITLE
Harvestcraft 2 Food Extended has a couple dishes with missing textures

### ISSUE THREAD

**Issue by Odey555** [AllTheMods/ATM-6#2400]
Pack version 1.8.3 
There's a couple recipes in the harvestcraft 2 food extended mod that seem to have missing textures. Then again they have plates so I'm not sure what to make of it, reporting anyway just in case. 
![image](https://user-images.githubusercontent.com/1361563/133944144-8fafc8bb-0329-46a8-8f3e-3137a4c8d91a.png)

**Comment by EnabledEnzo** [comment]
This would be an issue for the mods direct issues thread https://github.com/MatrexsVigil/phc2foodextended/issues
