### ISSUE TITLE
Crashing when loading world after updating to 1.8.3

### ISSUE THREAD

**Issue by Kreitin** [AllTheMods/ATM-6#2401]
version: 1.8.3
**i just updated the pack from 1.7.11 to 1.8.3, and when i try to enter my world in the new version, it just gets stuck at 100% for a little while and then crashes.**

this update removed some mods(rats, chiseled, morered and reauth).I tried to remove and trash most of the itens i had from them, so i don't think it must be much of a problem

https://gist.github.com/Kreitin/ac2be0b903aef11aa202ba5ca82b238d

**Comment by EnabledEnzo** [comment]
It's strongly advised to start a new save if updating to 1.8.0 or above.
