### ISSUE TITLE
Transferring buildings to new Update

### ISSUE THREAD

**Issue by AcelZeroX** [AllTheMods/ATM-6#2408]
Hey, so in Pack Version 1.8.1 it say u should start a new wolrd but i dont want to lose my progress from my world on the 1.7.11 Version. 
Is there a way to transferr my buildings from the old world to a new world? I already tryd amulett but it fucked up my buildings a bit. Do u guys know another way?

**Comment by ladylexxie** [comment]
If you use your base's X and Z coordinates in "Block Information" here: https://dinnerbone.com/minecraft/tools/coordinates/
It will give you the file name for that region, and you can copy that region over to your new world.
