### ISSUE TITLE
Interaction between corail tombstone and astral sorcery seems to cause significant CPU usage

### ISSUE THREAD

**Issue by JoshuaRowePhantom** [AllTheMods/ATM-6#2411]
ATM 1.16.5

I reported this issue to corail tombstone.  The response was... unfortunate.

https://github.com/Corail31/tombstone_lite/issues/17

Essentially, using an unnerfed shadow step results in about ~10% of server CPU spent checking enchantment levels.  I will also be following up directly with astral sorcery.

See spark profile here:

https://spark.lucko.me/gx0oUElePI

**Comment by ladylexxie** [comment]
Sadly this is not something we can do anything about, will have to wait for the devs to fix it in their mods.

**Comment by JoshuaRowePhantom** [comment]
Just FYI, setting this by default might or might not be a good idea:

```
nerf_shadow_step = true
```
