### ISSUE TITLE
Server Crash after update to ATM6 v1.1.9b

### ISSUE THREAD

**Issue by MSandro** [AllTheMods/ATM-6#242]
**Describe the bug**
The server crashes after loading the world, because an Elementalcraft Entity.

**To Reproduce**
1. not sure, maybe not everyone has this problem, maybe its an specific entity in my world on my server.

**Solution**
I've updated Elementalcraft to elementalcraft-1.16.3-2.3.16.jar

**Comment by Sirttas** [comment]
This is caused because some mods try to summon entities. the entity in question is part of an unfinished feature and so shouldn't be summoned.

**Comment by V2LenKagamine** [comment]
Can you post the crash log? Maybe I can give you some steps to fix it? Im not a dev, but I can kind of read code.
