### ISSUE TITLE
[1.16.5][1.8.3] Project Red Gemstones Integration for Silent Gear

### ISSUE THREAD

**Issue by cavy8** [AllTheMods/ATM-6#2422]
**Is your feature request related to a problem? Please describe.**
Currently, Project Red gemstones (Ruby, Sapphire, etc.) are limited in utility due to lack of integration with Silent Gear. It's less practical to use these gems when compared to alternatives.

**Describe the solution you'd like**
Basic Silent Gear integration - doesn't really need to be fancy, just usable with the mod.

Thank you! I don't use tinker's construct so I'm not sure if it's integrated there / if that's possible.

**Comment by ladylexxie** [comment]
I'm working on it now, it will be in 1.8.4 if everything goes well :)
