### ISSUE TITLE
Neutral Mob Seeds [Mystical Agriculture ATM 1.8.3]

### ISSUE THREAD

**Issue by Sunburntdruid** [AllTheMods/ATM-6#2424]
In the current version of ATM6, all the neutral mods create chicken seeds. I made sure this wasn't just in the public server by attempting the same effect in a creative world. Cows, sheep, and pigs with all items needed create chicken seeds.

**Comment by FinityKing** [comment]
> In the current version of ATM6, all the neutral mods create chicken seeds. I made sure this wasn't just in the public server by attempting the same effect in a creative world. Cows, sheep, and pigs with all items needed create chicken seeds. 

https://github.com/AllTheMods/ATM-6/issues/2365
