### ISSUE TITLE
digital miner can destroy territory(FTBteamchunk)

### ISSUE THREAD

**Issue by BluerDR** [AllTheMods/ATM-6#2425]
**Describe the bug**
digital_miner can destroy territory

my English is bad :(

**To Reproduce**
1. have a digital_miner(mekanism)
2. Go to someone else's territorial edge(FTBteam chunk)
3. Start the digital_miner
4. See someone else's territory(FTBteamchunk) will be destruction

**Comment by ladylexxie** [comment]
I have spoken to the FTB Chunks mod dev about it, there is no global config to disable fake players, but he said it will come in a future update. Sadly nothing we can do about it until that happens.
