### ISSUE TITLE
Bees don't work

### ISSUE THREAD

**Issue by Sajdix** [AllTheMods/ATM-6#2426]
I made tier 3 beehive and "cage" 7x6x3 (inside)/9x8x4 (outside). Its smoked (smoked: true) and using dispenser with scrapper and cyclic clock. As soon i put them out of bee jars they insantly went into the hive and won't come out and work. Any ideas?
![2021-09-22_20 47 19](https://user-images.githubusercontent.com/91031548/134403878-8ad65e86-f107-4562-9fd5-797768a6d956.png)
![2021-09-22_20 47 25](https://user-images.githubusercontent.com/91031548/134403882-bcfb1dbe-ba34-4460-b44d-e338926cb6f4.png)

**Comment by ladylexxie** [comment]
Your hive is facing the wall. They cannot come out of it, turn the hive around with the exit facing the middle of the room.
