### ISSUE TITLE
[1.8.3]I encountered two server bug

### ISSUE THREAD

**Issue by BluerDR** [AllTheMods/ATM-6#2431]
**Describe the bug**
My English is bad...

1.When I die outside the main world(like:hell,end,atm mining...),I will return to the rebirth point, but I can't move and type in the chat bar, including command.So I can only exit the server, but when I connect again, I will not be able to connect until the server restarts. Fortunately, the server I play restarts once a day :(

This problem occurs to everyone on the server.I don't know what happened, and there's nothing the administrator can do (he's busy)

2.When I created a void miner(2 Level) at end(dimension), I forgot to keep chunk load. So when I returned there, void miner didn't work (there was no light column)（Maybe it's just a server delay. Wait for a while it will be fine ）. I tried to rebuild after demolition, but it was useless, and the server crashed the second time. After restarting, I tried to remove it automatically again, and it crashed again. When it was restarted, the world broke down. Can enter the world, but there is no drop after all entity(Including block and mobs) are destroyed.

This problem causes no one to play on this server at all.It may be caused by the Environmental Tech

**Comment by ladylexxie** [comment]
That sounds like a lot of server-side issues, never heard of either of those problems. My best recommendation is that the server admin reinstalls the server and keeps the world, if that doesn't work, he has to check if creating a new world on a new server will have the same effect.
