### ISSUE TITLE
Uru does not have color or name assigned in Silent Gear

### ISSUE THREAD

**Issue by SamDDBS** [AllTheMods/ATM-6#2435]
Pack Version All The Mods 6-1.8.3

See here:
![image](https://user-images.githubusercontent.com/72839318/134603761-3246b20f-f416-49ce-847d-8b2b1e6613cb.png)

**Comment by ladylexxie** [comment]
I know of this, the name is fixed in 1.8.4, trying to figure out the color now ^^
