### ISSUE TITLE
[1.8.3]Beepedia crashes client when playing on server

### ISSUE THREAD

**Issue by Egzekiel** [AllTheMods/ATM-6#2437]
**Describe the bug**
After updating the server to version 1.8.3, the Beepedia from Resourceful Bees crashes the person using it, me and my friend have the same bug.

**To Reproduce**
1. Get the Beepedia
2. Use it (Right Click)

**Screenshots**
![image](https://user-images.githubusercontent.com/66809139/134625930-ddefcf5d-70fd-4140-89d7-074d469a41ce.png)

**Additional context**
I tried removing Optifine and try again but have the same problem.
I tried using it in singleplayer and it works fine.
I don't know if this is related or not but JEI does not show any information about bees.

**Logs**
https://pastebin.com/fNm52qGm

**Comment by notFalkon** [comment]
Bad install

**Comment by ladylexxie** [comment]
Reinstall your pack, if that doesn't work, the server should do it instead. The Creeper Bee should not exist.
