### ISSUE TITLE
Almost no Chisel recipes are available and almost no block is chiselable 

### ISSUE THREAD

**Issue by ShadedPL** [AllTheMods/ATM-6#2438]
Version 1.8.3
Only a handful of recipes for Chisel-mod specific blocks are currently available. At the moment available are only Tyrian, Factory, Antiblocks, Futura, Laboratory but there should be a lot more. It would be enough, that just the basic block is showing, like it is currently with the factory block, so JEI isn't too much cluttered.
![image](https://user-images.githubusercontent.com/4216212/134673077-7c6348e8-bda5-4c9a-bcc0-b8cc80d1ce77.png)

Also most vanilla blocks are non-chiselable, like Glass, compressed blocks, like Iron Blocks, Lapis etc.
Working right now, from what I've tested are Stone, Cobblestone, Andesite, Marble, so it's not entirely broken, but definitely a lot is missing.

Thank you for looking into it!

Shaded

**Comment by ladylexxie** [comment]
Discussed on Discord.
