### ISSUE TITLE
Automated mining is not mining ATM ores. 

### ISSUE THREAD

**Issue by demethan** [AllTheMods/ATM-6#244]
Hi, 

I am unsure if this is a bug or a feature.  Merkanism Digital miner or the RFtools builder cannot mine the ATM (mining level 5) ore blocks. 

if it's a bug, the fix would be nice.

if it's a feature, you people are monsters. 😋

**Comment by WhitePhant0m** [comment]
It's intended. :)

**Comment by thevortex** [comment]
![tenor (5)](https://user-images.githubusercontent.com/1524819/97640553-9e20ae80-1a06-11eb-9b7e-ad0d8993a540.gif)
