### ISSUE TITLE
Pack Version 1.8.3: Item Transfer Node destroyed when mined.

### ISSUE THREAD

**Issue by ndma-ucsc** [AllTheMods/ATM-6#2445]
**Expected**
Mining an `Item Transfer Node [Cylic]` will drop both the `Item Transfer Node [Cylic]` and any items stored inside (`GPS Data Card` and pending item to be sent).

**Live Result**
Mining an `Item Transfer Node [Cylic]` causes said item to be destroyed, despite the HUD stating that it can be mined with `pickaxe (wood T0)`. All items stored inside the `Item Transfer Node [Cylic]` are subsequently destroyed as well. `Silk Touch` does not affect results.

**To Reproduce**
1. Create and place an `Item Transfer Node [Cylic]`
2. Mine `Item Transfer Node [Cylic]` with `pickaxe (wood T0)`+

**Comment by ladylexxie** [comment]
This would be an issue with Cyclic, but as Cyclic pipes are very buggy, I disabled them from JEI and their recipes for this reason.
