### ISSUE TITLE
Cant join my friends that are in my town but people from other states or countries can

### ISSUE THREAD

**Issue by Kewons** [AllTheMods/ATM-6#2451]
so this is a better Minecraft v36 for forge 1.16.5 and me or another friend that are in the same town as my friend who is hosting the server on his computer, we cant join the server its just stuck on encrypting then after a while just times us out. other friends in different states or countries can join just fine (note : its not a firewall thing we have already tried ) does anyone have any ideas of how to fix

**Comment by ladylexxie** [comment]
Try getting the server logs so we can see what happens. If you can get that, let me know your username as well.

**Comment by Kewons** [comment]
![Screenshot 2021-09-28 232600](https://user-images.githubusercontent.com/91396939/135198085-c8219fdd-71b8-4861-a488-978a5347a9ba.png)
this is what pops up in  the command prompt when my friend tries joining
