### ISSUE TITLE
ATM6 1.8.4 Unable to use Cobblestone to make Stone Axe

### ISSUE THREAD

**Issue by AerosAtar** [AllTheMods/ATM-6#2452]
**Describe the bug**
Using the 1.8.4 version of the modpack, I am unable to use **cobblestone** to make a _stone axe_. Other stone tools accept **cobblestone** as normal.

**To Reproduce**
1. Attempt to make a stone axe using the vanilla recipe/the recipe showing in JEI with cobblestone.

**Comment by ladylexxie** [comment]
This will be fixed in the next version.
