### ISSUE TITLE
Recipe request for uncraftable creative item: @Apotheosis apotheotic boss spawner

### ISSUE THREAD

**Issue by BrettMoan** [AllTheMods/ATM-6#2453]
**Describe the solution you'd like**

Apotheosis includes a creative item called the "apotheotic boss spawner".  This is a creative only item since it has no recipe, and doesn't spawn in game. 

Since ATM6 has creative items for other mods, I think it would be really cool to be able to craft the boss spawner.

**Describe alternatives you've considered**

The only "efficient" way of spawning the bosses is to clear out a large (multiple chunk) area of land down to bed rock and spawn mobs at 0 light level at just above bedrock using _natural_ spawns. in my experience quarrying large chunks of the world like this is normally discouraged on servers (_not sure if this is cosmetic or performance reasons, or some of both_)

**Additional context**

discussion with mod author where he describes how to maximize boss spawns
https://discord.com/channels/613010559532531713/613011704456019968/891533241734025216

The reason I would like this is the Apotheosis affix's much like enchants but as they are separate and random, but still extractable, it adds a further level of weapon/tool progression. the random ness and farming of these enchants is fun as its one of the the last things you and do to further progress weapons and armor once you've "reached endgame stuff".

**Comment by Pdiddy973** [comment]
looking into it

**Comment by ladylexxie** [comment]
Added in next version.
