### ISSUE TITLE
[Bug]: Bug? UI element to the right, no idea how to make it go away or what it is

### ISSUE THREAD

**Issue by Odey555** [AllTheMods/ATM-6#2457]
### Possible Fixes

Yes

### Modpack Version

1.8.4

### What happened?

There's this weird UI element to the right above my minimap that won't go away, that says "**Allthemodium Ingot 100%**". 
What is this? Can I make it go away? Already tried restarting game (multiple times), killing myself, crafting ATM ingots, smelting ATM ore (while looking at smelter), taking off and putting back on my ATM armor set, looking in the quests, a lot. I _think_ it started around the time I put on my allthemodium helmet, completing the set.  
Any help appreciated. The element is... annoying. 

![2021-09-26_20 51 55](https://user-images.githubusercontent.com/1361563/134828601-7fab8b7f-0ef4-4881-8f17-eede8d7f7d7c.png)

### latest.log

https://gist.github.com/Odey555/db4a36d303b2bc694f3c5a9a09eaf7b3

**Comment by Apexii** [comment]
You can unpin the quests in the Quest Screen. See if that works.
![ftbqs](https://user-images.githubusercontent.com/20236502/134830392-bf43971a-e8fd-48d7-9201-0e4182faa9d0.png)

**Comment by Odey555** [comment]
> You can unpin the quests in the Quest Screen. See if that works.
> ![ftbqs](https://user-images.githubusercontent.com/20236502/134830392-bf43971a-e8fd-48d7-9201-0e4182faa9d0.png)

You are my hero. and im an idiot, thanks a lot!
