### ISSUE TITLE
[Question]: server.properties not mentioned in the Pack Upgrade FAQ Wiki

### ISSUE THREAD

**Issue by NiciusB** [AllTheMods/ATM-6#2458]
### What would you like to know?

Not really a question, bug a suggestion to update the Pack Upgrade FAQ Wiki article.

server.properties is not mentioned, so if you forget to copy it when upgrading the server, some things can be messed up.
It could be added as step 2 or 3 of "If you are hosting the pack yourself"
You could argue that it's included in step 3, but an explicit reminder would be great, since I'm guessing lots of people do change that file

**Comment by Ki-Tan2934** [comment]
why would you ever need to move it, just leave it in one place. There is no reason to touch it again after first editing the file.

**Comment by jeremiahwinsley** [comment]
Added that in step 3, thanks for the suggestion!
