### ISSUE TITLE
[Feature]: void miner help

### ISSUE THREAD

**Issue by TrashMagpie** [AllTheMods/ATM-6#2459]
### Feature Details

I have been using Environmental energy's void miners, but as far as I can see there is nowhere saying what resources each level of ore miner can obtain and which type of memory you need for each, if possible would there be a way to put in a book to list these, possibly along with  descriptions as to how to build each tier as the one you get by clicking on the machine is buggy 

Thanks

**Comment by TrashMagpie** [comment]
sorry forgot to mention am using all the mods 6 version 1.8.3 currently

**Comment by eshedso** [comment]
how did you even get it to work, i cant seem to make my miner function in any way...

**Comment by Pdiddy973** [comment]
you can see what each program does in our wiki
https://github.com/AllTheMods/ATM-6/wiki/General-Gameplay-Guides
