### ISSUE TITLE
[Bug]: Stackable bees!

### ISSUE THREAD

**Issue by xenoflot** [AllTheMods/ATM-6#2460]
### Possible Fixes

No

### Modpack Version

1.7.11

### What happened?

Player created two Dragonic bees using the mutation method. The jars were picked up with an absorption hopper and piped to a chest. They stack within the chest! He didn't realise that was unusual and so took out the stack of two then right-clicked to release as usual but released only one bee (and two empty jars).

I then spawned in two spawn eggs and caught them with jars. Those ones behave normally and do not stack. 

He then tested with a few other bees in his collection and they do not stack. However we found that his two Allthemodium bees also stack. Screenshot: https://i.imgur.com/HUPGcNN.png

The only thing that I can suggest may be a factor is that the Dragonic and ATM bees were created via mutation rather than spawning or breeding.

--

We're playing an unaltered ATM6 1.7.11. Upgrading to the latest version is not an option for us due to the mod removals/additions.

### latest.log

n/a

**Comment by ladylexxie** [comment]
That is normal behavior. The jars will stack if they are the same, aka the same nbt. You just have to separate them when spawning.
