### ISSUE TITLE
[Question]: [ATM 6] [1.8.4] Stone tools recipes changed?

### ISSUE THREAD

**Issue by ForbiddenSabre** [AllTheMods/ATM-6#2464]
### What would you like to know?

After updating ATM 6 from 1.8.3 to 1.8.4, the recipes for stone tools bar the pick axe no longer use cobblestone and instead require Stone. Is this intended?

**Comment by ladylexxie** [comment]
No it's a bug that's already been fixed for 1.8.5 ^^
