### ISSUE TITLE
[Bug]: Levels do not drain on enchanting or death

### ISSUE THREAD

**Issue by crowsnose** [AllTheMods/ATM-6#2465]
### Possible Fixes

Yes

### Modpack Version

1.8.4

### What happened?

Levels do not drain when dying or enchanting. Results in massive level accumulation and unlimited enchanting.

### latest.log

https://gist.github.com/crowsnose/0be4ec2242309b9abdf92c32d5e05fac

**Comment by ladylexxie** [comment]
This doesn't seem to be reproduceable in our single player test worlds or our public server.
I can only assume there's something wrong with your instance or world.
