### ISSUE TITLE
[Bug]: Thermal Series metal plates can only be crafted with a brand new engineers hammer

### ISSUE THREAD

**Issue by F4LK5** [AllTheMods/ATM-6#2468]
### Possible Fixes

Yes

### Modpack Version

1.8.4

### What happened?

I placed the engineers hammer and a metal ingot in the crafting bench. It had no output. I made a new engineers  hammer (immersive engineering), now it has an output. As soon as I craft one plate and the hammer takes durability it can no longer be used for this recipe

From the logs it appears to be an issue with Chisel?

### latest.log

https://gist.github.com/F4LK5/f265629f9cbcb9c8adb933c127a33118

**Comment by ladylexxie** [comment]
Duplicate of #2456
