### ISSUE TITLE
Server Crashes due to max tick time 

### ISSUE THREAD

**Issue by Camrais** [AllTheMods/ATM-6#2469]
Hi,

I'm new to servers in minecraft. I really love playing ATM6 alone. Recently I was able to convince some of my friends to play it with me so we decided to set up a server. We used ATM6 1.8.4 for it.
Sadly the server feels kind of laggy despite being really strong (20gb RAM, and having 40 Threads available). Also it crashs quite often. I can't figure out what exactly causes the crash tho, except that something has a way too long tick time.

I already set the max tick time to 10 minutes but it still kept crashing. I also swapped the java version from Java 8 to Java 11 and it still persisted. Apart from that we didn't modify anything.

Here are the logs (oldest to newest):

[crash-2021-09-27_04.20.41-server.txt](https://github.com/AllTheMods/ATM-6/files/7258064/crash-2021-09-27_04.20.41-server.txt)
[crash-2021-09-27_14.37.00-server.txt](https://github.com/AllTheMods/ATM-6/files/7258065/crash-2021-09-27_14.37.00-server.txt)
[crash-2021-09-27_18.41.12-server.txt](https://github.com/AllTheMods/ATM-6/files/7258066/crash-2021-09-27_18.41.12-server.txt)
[crash-2021-09-28_22.11.11-server.txt](https://github.com/AllTheMods/ATM-6/files/7258067/crash-2021-09-28_22.11.11-server.txt)

Would be awesome if someone can help me figure it out!

Thanks in advance

**Comment by ladylexxie** [comment]
Firstly, you should've filled out the Crash form.
Secondly, 20GB is a fuckton of memory and it WILL cause a lot of lag. That's just how Java works. if you have 5 people, you really don't need more than 8gb and even that might be too much.
Lastly, you might be able to fix the crash by going into your world folder, serverconfig, and finding `forge-server.toml` and enable `removeErroringEntities` and `removeErroringTileEntities`. Just don't forget to turn them back off later.

**Comment by Camrais** [comment]
Hi,

sadly i can't find the said template. There seems to be no post or file in the repo that has a template for that and is named something like "template".

Anyway: I used the settings for forge to remove the entities you mentioned and at first it seemed to work. I played for some time, then manually disconnected. So far so good everything was buttersmooth as it is supposed to be. Later I wanted to join back in, but it was just impossible. I could connect perfectly fine, but when it came down to being ingame it completely froze on me. It said all the time waiting for server to respond... Nothing happened tho, even restarting with the settings for forge on didn't bring salvation. This time I didn't even get a crash log. It seems the server application used so much computing power that the hoster shut it down. I can manually restart it, but it still doesn't work. Here is the latest log:
[latest.log](https://github.com/AllTheMods/ATM-6/files/7270241/latest.log)

Also if it might help the debug log:
[debug.log](https://github.com/AllTheMods/ATM-6/files/7270243/debug.log)

Thanks for your help!

**Comment by Camrais** [comment]
Update: I deleted the world and started a new one. It still happens.

**Comment by ladylexxie** [comment]
For future reference, the template is [here](https://github.com/AllTheMods/ATM-6/issues/new?assignees=&labels=Crash&template=crash.yaml&title=%5BCrash%5D%3A+).

Regarding the crashes, please use the template and upload the new crash logs.

**Comment by Camrais** [comment]
thank you for showing me :) i opened a new issue.
