### ISSUE TITLE
[Bug]: Immersive Engineering Recipes Require an Unused Hammer/Wire Cutter etc.

### ISSUE THREAD

**Issue by briyoon** [AllTheMods/ATM-6#2473]
### Possible Fixes

Yes

### Modpack Version

1.8.4

### What happened?

Copper wire and copper plates require undamaged tools to make.

### latest.log

no

**Comment by briyoon** [comment]
I see that it is a duplicate now. Don't know why the issue is closed if its not fixed...

**Comment by tanyan-tanyan** [comment]
It's closed because nothing can be done about that issue anymore.

**Comment by ladylexxie** [comment]
duplicate of #2456
