### ISSUE TITLE
[Bug]: Failed to synchronize registry data from server after backup, crash, backup

### ISSUE THREAD

**Issue by Julia404S** [AllTheMods/ATM-6#2479]
### Possible Fixes

Yes

### Modpack Version

1.8.4

### What happened?

When the server crashes after you installed a backup you can't use the same backup again, provided a player has been online before/while the server crashed because otherwise the player will encounter the error "Failed to synchronize registry data from server" upon trying to connect. The backup itself still works, other players can join and play normally, however affected players can't connect - reinstalling and normal fixes(as found via google or reddit(this includes the known jer issue)) won't solve this issue either, you have to either go back to a previous backup (which isn't always possible since some backups just crash on startup, like in my case: the 3rd backup I tried worked, then crashed and now I can't connect, the other backups all crash on startup) or start a new world. Reinstalling the server(same world) made no difference either. As you can see in the latest.log the client gets "Unidentified mapping from registry minecraft:item" instead of the normal mappings (ex: instead of "minecraft:item: resourcefulbees:creeper_bee_spawn_egg" it gets "resourcefulbees:creeper_bee_spawn_egg: 12986"). This issue happens with and without optifine installed, so disregard the warnings.

### latest.log

https://gist.github.com/Julia404S/7b0fd93b2aa62063346fd068206e6ea2

**Comment by Julia404S** [comment]
The provided log

**Comment by Julia404S** [comment]
Whoops. Meant to leave a comment saying that in order to see the entire log you need to look at the raw log.

**Comment by ladylexxie** [comment]
Trust me I know how to look at a gist :PP

Apologies for the delay.

The problem you're having is that either the client or the server has extra bees installed. This was a mistake quickly fixed in 1.8.1.

If you go to `/config/resourcefulbees/bees/` you should delete any `.json` files you see and have only folders like such:
![image](https://user-images.githubusercontent.com/30494658/136022513-4294d09d-8f63-4219-b4e5-24323da2a07b.png)
