### ISSUE TITLE
Botania Floral Fertalizer recipies removed

### ISSUE THREAD

**Issue by barcharcraz** [AllTheMods/ATM-6#248]
**Describe the bug**
In the latest version of botania the floral fertilizer can be crafted with any dye, in atm6 you can only use white dye. I can't find any mention of this in the ATM6 configs or js, so I figure this may be an unintentional side effect from something. If it is than that's a bug, if it's not then an explication for how and why the recipes were removed would be helpful for the next guy.

**Comment by WhitePhant0m** [comment]
Not a bug, or at least anything on our side, botania only has one recipe for it by default.
which is this one: https://github.com/Vazkii/Botania/blob/master/src/generated/resources/data/botania/recipes/fertilizer_dye.json

**Comment by WhitePhant0m** [comment]
wait, only white dye? my eyes seem to have skipped over that part
I'll check this really quick, if true, I'll re-open this.

**Comment by WhitePhant0m** [comment]
I'll get it fixed for the next update

**Comment by WhitePhant0m** [comment]
I've pushed the fix onto github, will be in the next one.

**Comment by barcharcraz** [comment]
thanks! do you know why this was removed in the first place? I'm curious...

**Comment by WhitePhant0m** [comment]
i'm guessing one of my scripts somehow broke it

**Comment by barcharcraz** [comment]
this is still broken in the latest update.....

**Comment by barcharcraz** [comment]
latest being 1.2.1

**Comment by WhitePhant0m** [comment]
hmm... when i tested it, it worked fine... i'll take a look at it again
