### ISSUE TITLE
[Question]: [Applied Energistics 2] P2P Tunel

### ISSUE THREAD

**Issue by felipesfeliciano** [AllTheMods/ATM-6#2480]
### What would you like to know?

Hi, I'm trying to use a P2P tunnel, but the memory card won't work when I use it (Left shift+right mouse button), the card just clean even I point to front of P2P tunnel. There is a reported issue about that or its an user problem? kk (if so, what is the right combination?)

![Captura de tela 2021-10-02 094854](https://user-images.githubusercontent.com/85955577/135716895-7a6b15a4-c523-4f0b-9522-edf157aae556.png)

![Captura de tela 2021-10-02 095006](https://user-images.githubusercontent.com/85955577/135716949-b50f1236-7434-48b8-b16d-64e7b92ad268.png)

tks guys

the modpack is amazing!

**Comment by DavidieHD** [comment]
watch a video how to use the p2p tunnel, (you cant connect an p2p with an normal glass cable it has to be an smart cable)

**Comment by felipesfeliciano** [comment]
I don't believe that its the problem, even when I try to use a smart cable (under or out of p2p tunnel) I can't link interfaces, always says "memory card clear" like when you point for the air.

![image](https://user-images.githubusercontent.com/85955577/135763023-213e132a-7e1c-48f5-af86-622c97c3abcd.png)

https://youtu.be/zCn6nRFoRfY

**Comment by DavidieHD** [comment]
oh i had the same issue a while ago you had to take that shield out of you offhand

**Comment by felipesfeliciano** [comment]
kkkkkk, man, you are an angel!
tks <3

**Comment by DavidieHD** [comment]
no problem
