### ISSUE TITLE
[Bug]: Creative Apiary has inverted lock buttons

### ISSUE THREAD

**Issue by ShadedPL** [AllTheMods/ATM-6#2481]
### Possible Fixes

Yes

### Modpack Version

1.8.4

### What happened?

Creative apiary has inverted controls with the bee-locking mechanics, please see below video to understand the issue better:

https://streamable.com/rolwtd

Regular apiaries work just fine.

### latest.log

https://gist.github.com/ShadedPL/f697401feffc70d859c416119922db39

**Comment by ladylexxie** [comment]
Discussed on Discord.
