### ISSUE TITLE
I have a problem with freezing[Question]: 

### ISSUE THREAD

**Issue by Strom9** [AllTheMods/ATM-6#2483]
### What would you like to know?

Hello!
I have problem in game on 1.8.4 version my game work normaly 30 minutes and start freezing.
Like Memory go on 100% 9000/9000..
https://prnt.sc/1uiyzhj
Can anyone help me fix this problem?

**Comment by ladylexxie** [comment]
Make sure you are using Java 11 and our recommended Java args.
java download here: https://github.com/AllTheMods/ATM-6/wiki/Java-Versions
And with these args:

`-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true`
