### ISSUE TITLE
[Bug]: ProjectRed Lamps Cannot Be Mined Back After Being Placed

### ISSUE THREAD

**Issue by EthericSoul** [AllTheMods/ATM-6#2488]
### Possible Fixes

Yes

### Modpack Version

1.8.4

### What happened?

ProjectRed Lamps cannot be taken again after being placed.

Expected Behavior: Block drops upon mining.
Actual Behavior: Block drops nothing upon being mined, as if mined without appropriate tool.

### latest.log

N/A

**Comment by ladylexxie** [comment]
I'll look at it in a bit. Normally I'd leave this up to the mod since it's a mod issue, but I could have a workaround if needed.
