### ISSUE TITLE
[Bug]: Reinforced Stone recipes not correct

### ISSUE THREAD

**Issue by waybaker** [AllTheMods/ATM-6#2496]
### Possible Fixes

Yes

### Modpack Version

1.8.4

### What happened?

The recipes for the Reinforced Stone only give you back regular stone. 

After crafting reinforced stone using any stone block and reinforced iron, you DO get reinforced stone, but using that stone to make brickes in the crafting grid or on the Bench Saw, only gives you back regular stone.

![2021-10-03_16 03 29](https://user-images.githubusercontent.com/25492475/135769763-6f05361e-328a-44ca-b9be-09c85da0793e.png)
![2021-10-03_16 03 43](https://user-images.githubusercontent.com/25492475/135769774-2a1f3a5a-c797-4a72-b757-85a9b5b5d758.png)

### latest.log

https://gist.github.com/waybaker/d3deb612c74f4166a5d37dc85792b664

**Comment by ladylexxie** [comment]
![image](https://user-images.githubusercontent.com/30494658/135770362-d2a62580-d50a-4eb9-952d-1f7c229e7c7b.png)
I can't really reproduce this.
