### ISSUE TITLE
indestructible enchant doesnt work on armor 

### ISSUE THREAD

**Issue by Pridgen** [AllTheMods/ATM-6#25]
i dont know why but it doesnt work, pls fix 💯 lost my allthemodium boost bc of this 👎

**Comment by thevortex** [comment]
> i dont know why but it doesnt work, pls fix  lost my allthemodium boost bc of this

were these boots that were crafted like normal vanilla recipe for boots but with allthemodium ingots or are these silent gear boots made from allthemodium ingots with the blueprint?

**Comment by Farza07** [comment]
U have to hold them in your hand for it to heal :/
