### ISSUE TITLE
ATM6 1.1.9b Mekanism Mechanical Pipe not working properly

### ISSUE THREAD

**Issue by NetMasterFlex** [AllTheMods/ATM-6#250]
Since ATM6 version 1.1.9 the mechanical pipe doesn't attach to machines or chests.  When placed a small framed cube floats and doesn't connect to adjacent machines or chests.  When I attempt adjustment with the configurator tool, I can see the wording "Push", "Pull" etc, but nothing else.  The pipe is useless in this state.

Thanks

NMF

**Comment by WhitePhant0m** [comment]
Pipe is used to transfer fluids, logistical one is for items, you sure you didn't mix them up?

**Comment by NetMasterFlex** [comment]
I mixed the two up! Thanks for responding so quickly to address a problem that doesn't exist with the modpack, only in my head.  I crafted the logical transporter and it works.  Closing post.
Thanks
NMF

**Comment by NetMasterFlex** [comment]
See 2nd response.  No issue exists for the subject of this posting.

NMF
