### ISSUE TITLE
[Bug]: Apiary is impossible to craft

### ISSUE THREAD

**Issue by MathiasMelk** [AllTheMods/ATM-6#2502]
### Possible Fixes

Yes

### Modpack Version

1.8.5

### What happened?

Apiary is impossible to craft

### latest.log

https://gist.github.com/MathiasMelk/3498ddbc510f2ffddb04d99ad40b1c28

**Comment by radiomike** [comment]
Looks like a bug in the included version of resourceful bees. You could try reverting it to previous mod version, or wait as it looks like it's fixed indev, so likely to be on curse soon.

**Comment by DavidieHD** [comment]
well i think its an JEI problem you can craft just with tier 4 beehives, anything under 4 doesnt work but you can see it in JEI

**Comment by radiomike** [comment]
See https://github.com/Resourceful-Bees/ResourcefulBees/issues/289

**Comment by ladylexxie** [comment]
Will have a hotfix as soon as Resourceful Bees posts a fix.
