### ISSUE TITLE
[Bug]: Immersive Engineering machines and devices don't interact properly with Project Red wires.

### ISSUE THREAD

**Issue by dan96kid** [AllTheMods/ATM-6#2504]
### Possible Fixes

No

### Modpack Version

1.8.5

### What happened?

Immersive Engineering things that can be controlled with a redstone signal, such as the external heater and redstone breaker, don't seem to work properly with signals from Project Red's wires. As Project Red wires carry redstone signals, I expect them to work with anything in Immersive Engineering that is controllable with redstone.
What's happening is that when a red allow wire on or directly next to a redstone controllable thing from Immersive Engineering switches to either a powered or unpowered state, the Immersive Engineering thing does not update to reflect the change, such as a redstone breaker not switching off when the red alloy wire pointed at it is powered.

### latest.log

https://gist.github.com/dan96kid/992e2db108f47479454ee2ca396c9a3c

**Comment by ladylexxie** [comment]
I am pretty sure this is an issue with IE, I cannot get a Lever or Redstone to interact with those two blocks no matter how I try it.

**Comment by ladylexxie** [comment]
Actually scratch that, I managed to get the cable working by adding a framed wire like such:
![image](https://user-images.githubusercontent.com/30494658/136045812-c9227372-7c92-40eb-94ab-a5b9830d8d35.png)

**Comment by ladylexxie** [comment]
Although the External Heater doesn't seem to react to any kind of redstone.

**Comment by dan96kid** [comment]
I'll try the framed wire thing. As for the External Heater, I know it works with vanilla redstone stuff. From my experience, the External Heater needs rf and be directly next to a vanilla furnace to work. Regarding this being an IE problem, I did some testing in a Minecraft instance with only IE and Project Red installed. IE's redstone things worked perfectly fine with Project Red's wires in that instance. That test's results are why I consider the problem to be with this modpack.

**Comment by ladylexxie** [comment]
Reading the IE manual in-game for External Heater, it says Redstone disables the use of more RF to boost the furnace speed, which in my testing world, putting a Lever on the Heater, on or off, the furnace ran at the same increased speed.

**Comment by dan96kid** [comment]
Without a redstone signal, the External Heater won't turn on if there's no items in the furnace. That's intended behavior according to the in-game IE manual. Applying a redstone signal makes the External Heater run even when there's nothing to smelt in the furnace.
