### ISSUE TITLE
[Question]: keeping the same world after updating

### ISSUE THREAD

**Issue by Kreitin** [AllTheMods/ATM-6#2505]
### What would you like to know?

is there any way that i can update the pack from version 1.7.11 to 1.8.0 and keep playing the same world?

**Comment by DavidieHD** [comment]
just try it, i did it and there was no problem with it

**Comment by Kreitin** [comment]
i tried with my world and it didn't work, it just crashes during the loading

**Comment by ladylexxie** [comment]
One of the most important things when trying to keep your world is to make sure you remove **all the items that are from the removed mods**.
