### ISSUE TITLE
[Bug]: Cant shift items in wireless crafting terminal

### ISSUE THREAD

**Issue by DavidieHD** [AllTheMods/ATM-6#2506]
### Possible Fixes

Yes

### Modpack Version

1.8.5

### What happened?

when i try to shift + click an crafting rezipt into the wireless crafting terminal from ae2 wireless terminal nothing happen, also when i press the x to put the items from the crafting field into the system nothing happens
 

### latest.log

https://gist.github.com/DavidieHD/b9eadad78ba4d10108a9440dbb371e8d

**Comment by ladylexxie** [comment]
Will be fixed in the next version by removing the mod as it's not working and has many issues.
