### ISSUE TITLE
[Question]: cant add an mod

### ISSUE THREAD

**Issue by DavidieHD** [AllTheMods/ATM-6#2509]
### What would you like to know?

i just want to install this mod: https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2-wireless-terminals/files
because i think this will maybe work better than: https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2-wireless-terminals-forge 
when i install the mod and launch the game it says its fabric mod and cannot be loaded. what does this mean? and can i somehow install the mod anyways
![Screenshot_1](https://user-images.githubusercontent.com/73746874/136033127-3923476b-21a5-4145-989a-cbc9de6c3be8.png)
?

**Comment by ladylexxie** [comment]
It is the same mod, but it's for Fabric. ATM6 uses Forge.

Comparing Fabric and Forge is the same as comparing Windows and MacOS. They're not compatible.

**Comment by DavidieHD** [comment]
Ah ok, didn't hear about fabric before
