### ISSUE TITLE
[Question]: KubeJS errors after disabling MineColonies

### ISSUE THREAD

**Issue by Odey555** [AllTheMods/ATM-6#2511]
### What would you like to know?

So I disabled MineColonies from the pack. When I do though I get this kubejs error when I join my world save. Is it safe to ignore the error?  
Everything else seems to work just fine (at least as far as I've gotten with the pack), but best to be sure 
KubeJS server.txt log:
https://gist.github.com/Odey555/e85b7915e282f34e72f10d4402dd0352

**Comment by ladylexxie** [comment]
Go to `/kubejs/server_scripts/mod_specific/` and delete the `minecolonies` folder.
