### ISSUE TITLE
Items Randomly Refuse to Stack

### ISSUE THREAD

**Issue by TBrauns** [AllTheMods/ATM-6#252]
**Describe the bug**
Sometimes, items will refuse to stack properly. I have seen this with Torches and Spruce Saplings. 

**To Reproduce**
1. Place a torch on a wall
2. Have a stack of torches in your inventory or hotbar
3. Break the torch
4. Item may or may not stack, and even when trying to move one item onto the stack, it will not.

**Expected behavior**
Items should fold into like stacks.

**Additional context**
I have not tested if this is a bug related to chunks. I have claimed my base and I chunkload it with the map's features.

**Comment by blisterfingers** [comment]
Can confirm. Happening with torches, coal and inferium essence.
Pack Version 1.1.9b,
Dropping the items on the floor they will merge into a stack just fine.

**Comment by blisterfingers** [comment]
Appears to be fixed in 1.2.0+

**Comment by TBrauns** [comment]
After updating, I still see the issue.

**Comment by blisterfingers** [comment]
Stacks that wouldn't stack before are still broken but any new stuff is fine for me.
