### ISSUE TITLE
[Question]: ATM STAR SHARD

### ISSUE THREAD

**Issue by unddasnoch** [AllTheMods/ATM-6#2529]
### What would you like to know?

How the Heck should someone make the atm star without an atm star shard because you need an atm star to make them thats redicolous. Explain me how i could make now the atm star for that i need an void tier 8 miner that needs atm star shards and these you only could make with a structure and an atm star that doesnt even makes sense????

**Comment by thevortex** [comment]
JEI explains the recipes, if you need further help understanding, join the discord
