### ISSUE TITLE
[Question]: Why mess with the pipez mod upgrades?

### ISSUE THREAD

**Issue by josephoaks** [AllTheMods/ATM-6#2541]
### What would you like to know?

Honestly, why? Why make the infinite upgrade require an ATM star that already is insanely difficult to make, by the time you make a single ATM star you are now going to waste it to make an upgrade filter? Sorry but this has got to be the dumbest thing ever, you just made the pipez mod useless, may as well go back to mekanism pipes instead. The pipez mod was well balanced and you had to go and mess it up...

**Comment by jebjordan** [comment]
...bruh

**Comment by thevortex** [comment]
> Leave the original recipe, even if it only gives you 1, is still better than trying to do this with an ATM Shard, if not it will never be an item I will use nor do I think many will, I will go back to using mekanism pipes instead. This is an easy fix for servers though, since Lexxie likes to be famous and signs her name to every recipe she touches, server admins/owners can simply search her name and fix these messed up recipes.

this has been corrected 1.8.6 or 1.8.7, as well as names being removed from the recipes
