### ISSUE TITLE
Garden Cloche Missing seed's

### ISSUE THREAD

**Issue by cauanmendonca** [AllTheMods/ATM-6#255]
Good afternoon, I look to see if can I could find someone commenting and as I didn't find anything about it, I opened a issue here.

While I was automating my garden clouches I noticed that 3 seed's (Nether Star, Manasteel, Terrasteel and Elementium) were missing from the compatibility list.

I don't know if this is on purpose or not to use BotanyPots.

I'm sorry if I said something wrong or malicious, I'm not very skilled in English Language.

**Comment by WhitePhant0m** [comment]
Intentional.
