### ISSUE TITLE
[Crash]: Ritual of the Martyr crashes client/server

### ISSUE THREAD

**Issue by sebbun123** [AllTheMods/ATM-6#2554]
### Possible Fixes

Yes

### Modpack Version

1.8.4

### What happened?

Activating Ritual of the Martyr (Woot!) causes the server and Client to Crash. Once crashed, cannot get back on world until offending ritual is destroyed.

Youtube of the behavior: https://youtu.be/bpv5yfpIhU0

### Crash Log

https://gist.github.com/sebbun123/658a7333fe022e1c42041739cb45ed20

**Comment by Thristhart** [comment]
looks like Woot 1.0.8.1 has been released with a fix for this
