### ISSUE TITLE
ATM 6- Mekanism Bug

### ISSUE THREAD

**Issue by Arexoa** [AllTheMods/ATM-6#256]
Hi, I have a Bug where evry time I rightclick on an Mekansim machine, I get thrown of the Server.

Error Code: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOExcepition; Payload may not be lager than 1048576 bytes.

Thanks

**Comment by WhitePhant0m** [comment]
Clear your inv, you have too much NBT on you.
