### ISSUE TITLE
[1.2.0] Dirty dusts from base Mek cannot be processed

### ISSUE THREAD

**Issue by Revvilo** [AllTheMods/ATM-6#257]
**Describe the bug**
After updating to 1.2.0, dirty dust from base Mekanism no longer goes into the enrichment chamber.
Dirty dust from JAOCPA remains working as normal.

**To Reproduce**
- Attempt to place dirty dust from base Mekanism into the enrichment chamber
- Attempt to show JEI usage for the dust. Has no uses anymore.

**Expected behavior**
For the dust to be processable in the enrichment chamber

**Comment by Revvilo** [comment]
I noticed this while trauling around in the configs because I was bored.
Is this intended to be 'intput'? There are a few lines in the same spot like this.
https://github.com/AllTheMods/ATM-6/blob/6d0101035ac37a2383a4a438db59bf2b03c60ac6/kubejs/server_scripts/unify.js#L8

**Comment by Revvilo** [comment]
Oh yep, fixing the typo fixes the issue 😂

**Comment by WhitePhant0m** [comment]
i see, i'm a fucking retard, and also blind, thank you, seriusly, will be fixed in the next build
