### ISSUE TITLE
[Bug]: Immersive Petrolium: Block of Steel recipe missing

### ISSUE THREAD

**Issue by Mezzomick** [AllTheMods/ATM-6#2570]
### Possible Fixes

Yes

### Modpack Version

1.8.5

### What happened?

I cant craft the Immersive Engineering "Block of Steel" and fot that reason i cant set up the Pumpjack. The Mekanism Steel Block doesnt work.

### latest.log

https://gist.github.com/Mezzomick/0f4fa09e8f9d9a6ba4cbc4017c8180b0

**Comment by Pdiddy973** [comment]
![image](https://user-images.githubusercontent.com/68764896/137061933-4166f1bb-5582-4bc7-9ed4-466f0d872d7d.png)
![image](https://user-images.githubusercontent.com/68764896/137061943-369db957-6170-458e-8c23-9063c0b195b9.png)
was able to make using mek steel block
