### ISSUE TITLE
[Crash]: On startup.

### ISSUE THREAD

**Issue by RatrixGlory** [AllTheMods/ATM-6#2573]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

It gets to the Mojang Logo and crashes.

### Crash Log

https://gist.github.com/RatrixGlory/b46b88dc59cf5c8118debc653afcb61f

**Comment by jeremiahwinsley** [comment]
You can update MmmMmmMmmMmm to this version: https://www.curseforge.com/minecraft/mc-mods/mmmmmmmmmmmm/files/3473005 or update the pack to 1.8.6 to fix this.
