### ISSUE TITLE
[SERVER ONLY] Unable to access The Other and the Mining Dimension using the teleport pad

### ISSUE THREAD

**Issue by igqy** [AllTheMods/ATM-6#258]
ATM VERSION: 1.1.9b

This bug only appears when playing on a server. I can't seem to access The Other dimension and the Mining Dimension using the teleport pad. 

This error comes up: 
![Screenshot_251](https://user-images.githubusercontent.com/21244092/97950060-7b660100-1d4a-11eb-88f8-f9b9ca41febf.png)

I've dissected that the dimensions are not generating alongside the world in the initial world creation. However when generating a world in singleplayer, everything works.

Also, I tried to copy over the singleplayer generated world that had dimensions in them on to the server, but it still would not access those dimensions. Even with the corresponding dimension files and the proper level.dat, running a perfectly working world on a server will not allow you to access the dimensions.

I've also tried reinstalling the server files by downloading them from the curseforge page and running the setup script, and even a fresh server install does not work.

**Comment by LWmods** [comment]
this is an issue on quark's realistic world type as well. it works fine on the vanilla generation and Biomes o plenty.

**Comment by igqy** [comment]
> this is an issue on quark's realistic world type as well. it works fine on Biomes o plenty.

I tried generating a world using the default world type on the server and it still wouldn't work.

**Comment by ViRb3** [comment]
The issue seems to be **with** Biomes o' Plenty. Here's a cross-ref: https://github.com/Glitchfiend/BiomesOPlenty/issues/1718. No custom dimensions are generated in my ATM 1.2.1 world, not even Ratlantis. But if you restart the server, they appear again. If I remove BOP, everything works from the first start as expected.

**Comment by igqy** [comment]
> The issue seems to be **with** Biomes o' Plenty. Here's a cross-ref: [Glitchfiend/BiomesOPlenty#1718](https://github.com/Glitchfiend/BiomesOPlenty/issues/1718). No custom dimensions are generated in my ATM 1.2.1 world, not even Ratlantis. But if you restart the server, they appear again.
> 
> EDIT: The issue seems not to be exclusive to Biomes o' Plenty, as removing the mod completely and re-creating the world still causes the same problem. Again, restarting the server fixes it.

I've restart my server several times and the dimension has never been generated.

**Comment by igqy** [comment]
> > The issue seems to be **with** Biomes o' Plenty. Here's a cross-ref: [Glitchfiend/BiomesOPlenty#1718](https://github.com/Glitchfiend/BiomesOPlenty/issues/1718). No custom dimensions are generated in my ATM 1.2.1 world, not even Ratlantis. But if you restart the server, they appear again.
> > EDIT: The issue seems not to be exclusive to Biomes o' Plenty, as removing the mod completely and re-creating the world still causes the same problem. Again, restarting the server fixes it.
> 
> I've restart my server several times and the dimension has never been generated.

**Comment by igqy** [comment]
Update: I managed to remedy the problem by:

1. Generating the realistic world type
2. Shutting down the server and changing the world type to default.
3. Letting it load and and shutting it down once again.
4. Starting it up to find that the dimensions are now recognized.

Since the world type in the level.dat is still using the realistic world type, it still generates Quark Realistic biomes. But since the dimensions are seeing the default level type specified in the server.properties, the dimensions are being registered and generated. Hopefully this will be fixed soon so that others don't need to jump through many loopholes :D

**Comment by ViRb3** [comment]
Glad you managed to work it around. I would keep this issue open as the problem still remains, and it shouldn't be necessary to go through such hoops to make it work.

**Comment by ViRb3** [comment]
This should have been fixed in ATM 1.3.2 via Forge's update: MinecraftForge/MinecraftForge#7445. Please comment here if still experiencing it.

**Comment by Colton-Slayden** [comment]
I am on 1.3.3 and still getting this error using quark realistic type

**Comment by ViRb3** [comment]
Please check #437.
