### ISSUE TITLE
[Crash]: 1.8.6 Rendering screen crash with supplementaries safe tooltip

### ISSUE THREAD

**Issue by TheInfamousAlk** [AllTheMods/ATM-6#2587]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

I made a safe from the mod supplementaries. When I hover over it after crafting, it says "unbound". When I place it, break it, then hover over it again, my client crashes while rendering the tooltip. 

I installed supplementaries to a blank forge installation and could not replicate the issue, so I'm posting here instead of the mod's github. (however I tried it in a singleplayer world, and the crash happened in a multiplayer server. I do not have a blank server to test this on.) I can place the item again just fine, as long as I don't hover over it. I have confirmed with other users of my server that the same exact thing happens to them. This is the first time I have tried to use this item, so I do not know how long the issue has existed.

I have linked the crash log.  

edit: to be clear, this is a client crash. 

### Crash Log

https://gist.github.com/TheInfamousAlk/e75b024c2b3da006768579c8df00a4c6#file-crash-2021-10-15_14-56-53-client-txt

**Comment by jeremiahwinsley** [comment]
Reported here: https://github.com/MehVahdJukaar/Supplementaries/issues/125
