### ISSUE TITLE
[Crash]: 1.8.7 java.lang.IllegalStateException: Tag elementalcraft:pipe_cover_hiding used before it was bound.

### ISSUE THREAD

**Issue by iwubaldrin** [AllTheMods/ATM-6#2590]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

I was playing at my friends server, before the version was 1.8.6 and we both decided to play at the latest version of ATM6 which is 1.8.7. At first there was no crashes but the game lags for some reason and then after like an hour of playing, my game got disconnected. then I restarted my Minecraft then reconnect to the server. After it goes "Loading Terrain" it suddenly goes "Saving world" then it shows the Game crashed and the error message. We haven't started using ElementalCraft before especially the pipe thing. We only used Mekanisim and Pipez for Item/Liquid/Gas transfer in my friend's world.

### Crash Log

https://gist.github.com/iwubaldrin/f7f4b1d82dc3ec6e7b40eb008d8d4009

**Comment by jeremiahwinsley** [comment]
Can you temporarily add `-Dforge.logging.mojang.level=debug` to the args in your launcher, and then send me the resulting `debug.log` after it crashes? 

Not sure if this is the same issue, but a similar issue in earlier versions could be worked around by joining a single player world first, and then the server world.
