### ISSUE TITLE
[Bug]: Mekanism machine recipes can't be put into AE2 patterns

### ISSUE THREAD

**Issue by CodeMastr3** [AllTheMods/ATM-6#2591]
### Possible Fixes

No

### Modpack Version

1.8.5

### What happened?

![image](https://user-images.githubusercontent.com/18755358/137603126-3db46907-f85d-4e53-b420-a9f756170af9.png)
![image](https://user-images.githubusercontent.com/18755358/137603129-9f44ef62-1f5e-45bd-959c-d6eb2d3c30ad.png)

### latest.log

https://gist.github.com/CodeMastr3/5cf72f0d62c0081dee65b3f57e30e726

**Comment by Pdiddy973** [comment]
This isn't really a bug, just they don't interact with each other well.you can put in the inputs/outputs manually and it will work fine
