### ISSUE TITLE
[Bug]: Xp dupe bug

### ISSUE THREAD

**Issue by wulfie1987** [AllTheMods/ATM-6#2595]
### Possible Fixes

Yes

### Modpack Version

1.8.7

### What happened?

![2021-10-17_11 17 27](https://user-images.githubusercontent.com/92671350/137623257-d08b48b3-349a-473a-b821-8a1da0998e52.png)
 Absorption hopper and character collecting xp at the same time, hopper drains to singularity tank to be output by an xp tap and its creating an infinite amount of xp.

It's been set up for a while but only noticed after the update to 1.8.7, could have been doing it before.

### latest.log

https://gist.github.com/wulfie1987/44825a5619c38b1fd2af0212f9b019d4

**Comment by MechanicalDragon0687** [comment]
this is an interaction with Clumps mod. https://github.com/vadis365/Mob-Grinding-Utils/issues/164
should be fixed in Mob Grinding Utilities 0.4.30

**Comment by jeremiahwinsley** [comment]
Mod has been updated to 0.4.30 in 1.8.9
