### ISSUE TITLE
[Bug]: Can't pickup AE2 machines with any Wrench

### ISSUE THREAD

**Issue by costelush41** [AllTheMods/ATM-6#2596]
### Possible Fixes

Yes

### Modpack Version

1.8.7

### What happened?

I am unable to pickup AE2 machines with the AE2 Wrench, even with the crescent hammer.

I am trying to pickup a charged Energy Cell, breaking it with a pickaxe will lose the stored energy, however Shift + Right Click while holding the wrench will not pickup any AE2 machines. 

### latest.log

https://gist.github.com/costelush41/7123f681e052d26305f1e510ab521939

**Comment by jeremiahwinsley** [comment]
The wrench works on cables, but not on blocks. The network tool works on cables and blocks. So this seems to be intended by AE2.
