### ISSUE TITLE
[Crash]: Failed to Load Mod on Mac OS X

### ISSUE THREAD

**Issue by Hawk2811** [AllTheMods/ATM-6#2597]
### Possible Fixes

No

### Modpack Version

other

### What happened?

Minecraft Not Starting on macOS big sur

I was trying to start ATM6 on my Hackintosh but it crashes

Modpack Version: 1.8.7

Screenshot

![image](https://user-images.githubusercontent.com/55853571/137643228-df643dc8-b312-4076-8626-79eb17b7e531.png)

### Crash Log

https://gist.github.com/Hawk2811/25823dcf2405dbd4963c5a2395c6399e

**Comment by radiomike** [comment]
Looks like you're trying to run the pack with java 17. This is incompatible, use java 11 instead. There are links here on the wiki for this.
