### ISSUE TITLE
[Bug]: Structurize Recipes not showing in JEI making Minecolonies building unable to be done to continue from tier 1 - 5 in certain builds.

### ISSUE THREAD

**Issue by Firemixer** [AllTheMods/ATM-6#2599]
### Possible Fixes

Yes

### Modpack Version

1.8.7

### What happened?

Steps to repeat:
1. Load into a new world in either Creative or Survival.
2. Open inventory to show JEI and search @Structurize 
![image](https://user-images.githubusercontent.com/92699247/137652295-0e4928c2-064d-4a30-bfc5-a7eef854b1f5.png)
Pictured above ^
3. Recipes for only Oak timber frame show, no other recipes are showing and FAQ on JEI and Minecolonies suggests checking if another mod is conflicting with the recipes. Even pressing the "show Recipe" button doesnt work and searching for the block comes up as red text.
In creative you can pull the blocks out of the respective tab, 
![image](https://user-images.githubusercontent.com/92699247/137652340-d0e5a262-e577-47e2-91a7-f7bf8ff606cb.png)
But it makes it impossible to show the recipes in survival when needed to craft/build with them. and alot of minecolony structures use the recipes.

### latest.log

https://gist.github.com/Firemixer/ee757b478bafb4c4a2022673c5789df2

**Comment by Pdiddy973** [comment]
they were just hidden from JEI, recipes are still working as intended
![image](https://user-images.githubusercontent.com/68764896/137677600-089329d2-cb20-48b2-b6bc-389c9cf6f951.png)
![image](https://user-images.githubusercontent.com/68764896/137677636-8131c189-89aa-4864-9398-a2bb6fe9dc91.png)
