### ISSUE TITLE
ATM6 1.8.5-1.8.7 AE2 Network Tool Not in Modpack

### ISSUE THREAD

**Issue by VengefulZephyr** [AllTheMods/ATM-6#2606]
The Network Tool for AE2 simply does not exist in the modpack. It is not in JEI, nor does the standard crafting recipe for the tool work. It simply cannot be obtained. However, the tool still makes in an appearance in one of the AE2 quests, more specifically the "Other Tools" quest.

**Comment by benjiben55** [comment]
Hey,  i have the issue too.

I check creative mode and it's ingame but not available for some reason.
Maybe disabled from the mod team.
