### ISSUE TITLE
Enriched Carbon/Redstone/Diamond/etc uncraftable after updating pack

### ISSUE THREAD

**Issue by RicardoLuis0** [AllTheMods/ATM-6#261]
**Describe the bug**
After updating the pack it seems that the enrichment chamber can now only proccess ores/flowers/dirty dusts and not Carbon/Redstone/Diamond/etc

**To Reproduce**
1. Get Enrichment Chamber
2. Attempt to Enrich Carbon/Redstone/Diamond/etc

**Expected behavior**
 Carbon/Redstone/Diamond/etc become Enriched Carbon/Redstone/Diamond/etc, but they don't

**Comment by whatthedrunk** [comment]
This was fixed in 1.2.1
