### ISSUE TITLE
botany pots 

### ISSUE THREAD

**Issue by xtriilliionaire** [AllTheMods/ATM-6#262]
Please correct me if I'm wrong. but the Botany Pots mod should allow you to craft a Botany Hopper pot using a Botany pot and a Hopper. However, the only crafting recipe I see when trying to make the botany hopper pot is through the Botania mod and not the Botany pot mod.

**Comment by DeathOfTime** [comment]
it was gated by a custom recipe

**Comment by xtriilliionaire** [comment]
> it was gated by a custom recipe

Is there a way to get it back to the original recipe?

**Comment by WhitePhant0m** [comment]
no
