### ISSUE TITLE
[Crash]: Living Armor

### ISSUE THREAD

**Issue by SyCoUni** [AllTheMods/ATM-6#2628]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

Game crashed right after putting on the last piece of living armor and it also crashes everyone on the same chunk as me.

### Crash Log

https://gist.github.com/SyCoUni/687c4da4b3740c26ea4bc27e71310d19

**Comment by jeremiahwinsley** [comment]
This should be fixed in 1.8.15.
