### ISSUE TITLE
[Bug]: CBMultipart Torches Do Not Produce Light

### ISSUE THREAD

**Issue by ZilophosGH** [AllTheMods/ATM-6#2629]
### Possible Fixes

Yes

### Modpack Version

1.8.7

### What happened?

The doubled up torches from CBMultipart have a glowmap, but do not produce light.
![image](https://user-images.githubusercontent.com/88152241/138581044-bc02b3dc-f112-4fa3-b9bc-483229a1adac.png)

### latest.log

https://gist.github.com/ZilophosGH/df85939b0cae0bccb656caced600413b

**Comment by jeremiahwinsley** [comment]
Not sure which update, but this seems to be fixed now.
