### ISSUE TITLE
Switching Ice & Fire back to default overworld config?

### ISSUE THREAD

**Issue by Odey555** [AllTheMods/ATM-6#263]
Me and a friend have our own server and don't find the Other dimension any fun. Its simply mob spam over there and causes the server to lag big time if we're in separate dimensions.  
Is there any way to just get the default config so that all the Ice & Fire stuff spawns in the Overworld? Preferably _without_ breaking something?

**Comment by WhitePhant0m** [comment]
change the config for ice and fire located in the config folder
