### ISSUE TITLE
[Crash]: [1.8.7] ghost bow crash

### ISSUE THREAD

**Issue by EliiasG** [AllTheMods/ATM-6#2632]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

when shooting a ghost (from ice and fire) (spawning in the other: soul sand valley) with my bow the game crashes 

i tried it 2 times, the first time the game just stopped responding, the second time everything around me froze but i could still move ( like when loosing connection to a server)

here is a screenshot of the enchants on my bow
![image](https://user-images.githubusercontent.com/91526308/138608648-7faf388d-de35-4da5-bc5d-2ddb9d017de0.png)

### Crash Log

"error code: 0" or something like that

**Comment by JWAOSTAR** [comment]
Just want to note the same issue is also happening to me.

**Comment by jeremiahwinsley** [comment]
Ghost spawns have been disabled in 1.8.21.
