### ISSUE TITLE
[Bug]: Using Cyclic Sleeping Bag while in the Mining Dimension causes player to be stuck sleeping

### ISSUE THREAD

**Issue by CailanVR** [AllTheMods/ATM-6#2635]
### Possible Fixes

Yes

### Modpack Version

1.8.7

### What happened?

Using the Cyclic Sleeping Bag while in the Mining Dimension will cause the player to sleep as normal, however, night will not pass and the "Leave Bed" button does not function, effectively softlocking the client and forcing the player to restart, teleport to another dimension through commands, or get kicked from the server.

### latest.log

https://gist.github.com/CailanVR/c9382998edfa043218a9ce135c4cc8a1

**Comment by jeremiahwinsley** [comment]
This should be fixed as of 1.8.9.
