### ISSUE TITLE
ATM6 1.2.0 Mekanism Purification Chamber not processing ores

### ISSUE THREAD

**Issue by NetMasterFlex** [AllTheMods/ATM-6#264]
I updated from 1.1.9b to 1.2.0.  I had auto production of ores to X3.  The machines no longer output to adjacent machines.  The purification chamber doesn't process ores even when oxygen is supplied.  Ore prod was working fine before updating to 1.2.0.  Is this issue fixed in 1.2.1?

**Comment by DeathOfTime** [comment]
yeah. it was pretty much the reason for the 1.2.1 update. it might have been good to check on that before reporting. in case it was fixed

**Comment by NetMasterFlex** [comment]
Thanks  I thought I did check, but I may have overlooked it somehow.
