### ISSUE TITLE
[Bug]: Solar Panel VI original Recipe is craftable

### ISSUE THREAD

**Issue by fabrossmann** [AllTheMods/ATM-6#2649]
### Possible Fixes

Yes

### Modpack Version

1.8.8

### What happened?

The original Solar Panels are still craftable, so there is no reason to take the more expensive AllTheModium Route
![image](https://user-images.githubusercontent.com/6189957/139527843-c15e9404-1eb2-405a-8280-52c355d59eec.png)

### latest.log

None needed

**Comment by jeremiahwinsley** [comment]
Fixed in 1.8.9
