### ISSUE TITLE
ATM6 1.2.0 Enrichment chamber not accepting ore dusts

### ISSUE THREAD

**Issue by NetMasterFlex** [AllTheMods/ATM-6#265]
**Describe the bug**
In Mechanism ver 1.1.0b I had auto ore x3 processing setup.  Processing worked fine.  After updating to 1.2.0 3x ore processing stopped working.  Specifically the Enrichment chamber does not accept ore dusts which gets processed into ore dusts.

**To Reproduce**
1. Place any ore dust into the enrichment chamber  "top" square.  The item is not accepted.  

**Expected behavior**
The enrichment chamber changes dirty dusts to dusts which are then sent to the furnace to be made into ingots

**Screenshots**

**Additional context**

**Comment by DeathOfTime** [comment]
update to 1.2.1

**Comment by NetMasterFlex** [comment]
Will do.

Thanks
