### ISSUE TITLE
[Question]: Draconic Evolution incomplete armor set

### ISSUE THREAD

**Issue by Sinneqs** [AllTheMods/ATM-6#2650]
### What would you like to know?

I'm on Minecraft 1.16.5 with ATM6 version 1.8.7.
I noticed Draconic Evolution was added since my last playing of ATM, and wanted to go for the armor in the long run, but I see that only the chestpiece is available in JEI. Is there a reason why the helmet, leggings and boots are disabled or is this unintentional?
The changelog of ATM6-1.8.8 doesn't say anything about Draconic Evolution, so I assume the same issue would be present in that next version.

**Comment by radiomike** [comment]
All this and more is answered on the mods curse page https://www.curseforge.com/minecraft/mc-mods/draconic-evolution

**Comment by Sinneqs** [comment]
Oh. Must've missed that then. Thanks for the help!
