### ISSUE TITLE
Connecting Pipez Universal Pipe to Powah Basic Cable crashes the game

### ISSUE THREAD

**Issue by BubbaVB** [AllTheMods/ATM-6#2652]
I right clicked on the Pipez Universal pipe attempting to connect it to Powah's Basic Cable and it caused the game to crash.  I tried relaunching and it crashed again on load.  Attached are both crash logs
[crash-2021-10-31_09.24.58-server.txt](https://github.com/AllTheMods/ATM-6/files/7448943/crash-2021-10-31_09.24.58-server.txt)
[crash-2021-10-31_09.34.51-server.txt](https://github.com/AllTheMods/ATM-6/files/7448944/crash-2021-10-31_09.34.51-server.txt)
.

**Comment by jeremiahwinsley** [comment]
https://github.com/AllTheMods/ATM-6/issues/2186 Known issue but waiting on Powah to fix it.
