### ISSUE TITLE
each Compact Machine requires 8 Allthemodium Blocks

### ISSUE THREAD

**Issue by MechanicalDragon0687** [AllTheMods/ATM-6#2658]
It appears that the recipe was significantly gated in the "reversion" of the in-world crafting. This does not correlate with either previous or in-world recipes. Perhaps this is an expert mode recipe creeping in?

https://github.com/AllTheMods/ATM-6/blob/6582e17e537dc89947aef2defbe0021a365adfdd/kubejs/server_scripts/mod_specific/compact_machines/compct_machines.js

**Comment by jeremiahwinsley** [comment]
The AllTheModium block was an intentional change to gate them, due to the way they chunkload. For the in-world crafting, this made large machines cost 6.2 blocks, and small machines cost 1.7 blocks. 8 blocks is a bit more than intended though, we'll look at changing that.

**Comment by Pdiddy973** [comment]
recipe is staying as is for now
