### ISSUE TITLE
[Bug]: Can only cast certain metal plates (from thermal series) from a smeltery using tinkers molten metal.

### ISSUE THREAD

**Issue by TheInfamousAlk** [AllTheMods/ATM-6#2659]
### Possible Fixes

Yes

### Modpack Version

1.8.8

### What happened?

When you melt most modded metals (copper or nickel for example) in a tinkers smeltery, you get molten metal from alltheores mod, as expected. However, when attempting to cast that metal into a plate cast, it does nothing. This is because the recipe requires molten metal from tinkers construct, which you cannot get by melting ores, ingots, etc. The fix is to update the recipe so metal plates use alltheores molten metal in addition to tinkers molten metal.

I noticed the same issue in https://github.com/AllTheMods/ATM-6/issues/2107 , but that was august 30 and "fixed in the next version" so I can only assume it was fixed and has reappeared since. 
![2021-11-01_15 06 24](https://user-images.githubusercontent.com/29339124/139727102-7dfc3981-60b5-4e84-af3d-c1f540619090.png)
![2021-11-01_15 06 51](https://user-images.githubusercontent.com/29339124/139727105-ba42fe68-ca87-4c63-b463-212fd2de50de.png)
 

### latest.log

https://gist.github.com/TheInfamousAlk/7b1af9c92435a4bfc1acbe67509e9049

**Comment by jeremiahwinsley** [comment]
Fixed in 1.8.9
