### ISSUE TITLE
[1.2.1]Automate Stygian Iron Plate

### ISSUE THREAD

**Issue by galfalek** [AllTheMods/ATM-6#266]
**Describe the bug**
Stygian Iron Plate from Woot can be automated with thermal series in the Multiservo Press, but the Plate Die is consumed during the process which shouldn't.

**To Reproduce**
1. Multiservo press (from thermal)
2. Plate die and stygian iron ingot from woot
3. Put them in the press
4. Plate die is consumed

**Expected behavior**
When you do it manually the plate die is not consumed so it should be the same with the press

**Screenshot**
![error](https://user-images.githubusercontent.com/2273236/98097520-6b0a6f00-1e8d-11eb-9fd2-26c152a0abbe.png)

**Comment by ViRb3** [comment]
For a workaround, I use the RFTools Crafter and add the recipes there, which allows me to specify in Refined Storage/AE2 crafter that the crafting is a "process" which returns the hammer. Or another workaround, make 64 hammers.

**Comment by jeremiahwinsley** [comment]
This recipe is added by Thermal. Reported on CoFH Discord.

**Comment by ViRb3** [comment]
Thanks for reporting!
