### ISSUE TITLE
[Bug]: ProjectRed Inverted Lamps don't drop after break

### ISSUE THREAD

**Issue by costelush41** [AllTheMods/ATM-6#2663]
### Possible Fixes

Yes

### Modpack Version

1.8.8

### What happened?

ProjectRed Inverted Lamps or Lamps don't drop after breaking them with any pickaxe. Not even with Silk touch

### latest.log

-

**Comment by jeremiahwinsley** [comment]
Tracked here: https://github.com/MrTJP/ProjectRed/issues/1680

**Comment by jeremiahwinsley** [comment]
Fixed in 1.8.12.
