### ISSUE TITLE
Immersive Engineering tools work only once

### ISSUE THREAD

**Issue by bobothehobo2** [AllTheMods/ATM-6#2668]
So I was really excited to start IE but when the tools like wire cutters or hammer are used in the crafting grid it does exactly 1 wire or 1 plate and becomes unusable because it has damage.  Thanks!

Version -  1.8.4 

![immers1](https://user-images.githubusercontent.com/25537033/140593863-6978c47d-b0a7-4c85-91b6-79472dd3635a.PNG)
![immers2](https://user-images.githubusercontent.com/25537033/140593866-4450ee74-7f5c-4659-b745-85a09b6de22c.PNG)

**Comment by rois2coeurs** [comment]
This issue has already been fixed in the following updates

**Comment by Pdiddy973** [comment]
Update to 1.8.9, it is fixed

**Comment by bobothehobo2** [comment]
thanks!
