### ISSUE TITLE
[Bug]: Spark doesnt work on the Mana Infuser (Botania)

### ISSUE THREAD

**Issue by Gronkelx** [AllTheMods/ATM-6#2669]
### Possible Fixes

Yes

### Modpack Version

1.8.9

### What happened?

I wanted to make alfsteel and then I also built the Mana infuser. However, when I placed the Spark it didn't work.

### latest.log

https://gist.github.com/Gronkelx/ae9c958778e371bc1cdde430f0a9e327

**Comment by FroggieNL** [comment]
You will need to use the Spark Augment: Dominant

Link for more info about the spark upgrade: https://ftb.fandom.com/wiki/Spark_Augment:_Dominant
