### ISSUE TITLE
World fails to load after 1.2.1 update

### ISSUE THREAD

**Issue by PapaZ810** [AllTheMods/ATM-6#267]
World fails to load after 1.2.1 update

1. Open Minecraft from Twitch App
2. Try to load World
3. Minecraft crashes and launcher gives me an error saying that it had a no such method error.

![image](https://user-images.githubusercontent.com/43076672/98114086-f79f3800-1e61-11eb-99ec-5d7318e14e6c.png)

[2020-10-12-1.log.gz](https://github.com/AllTheMods/ATM-6/files/5487878/2020-10-12-1.log.gz)

**Comment by jpedda** [comment]
I have the same problem. Starting a new world works just fine, but loading my main world crashes the game and i get the same error.

**Comment by AccordNoir** [comment]
I had the same error, I disabled Optifine and it worked perfectly, don't know if you have it added or not, but it fixed mine.

**Comment by PapaZ810** [comment]
> I had the same error, I disabled Optifine and it worked perfectly, don't know if you have it added or not, but it fixed mine.

This did work, but I still want to have optifine.

**Comment by WhitePhant0m** [comment]
@AccordNoir @PapaZ810 do you have optiforge? if not, try installing it alongside with optifine

**Comment by VTArxelus** [comment]
Having the same issue on a new world. Have a link to the log [here](https://paste.ee/p/xPgz8). Not entirely sure what the problem is.
