### ISSUE TITLE
Downloading Problem

### ISSUE THREAD

**Issue by Biggysad** [AllTheMods/ATM-6#2671]
I recently found this mod pack and have been waiting for quite a while for it to download and have no issues other than both times I've tried to download it'll get all the way up to saying twilight forest mod is downloading then crash and I have had no problems with any other mod packs.

**Comment by jeremiahwinsley** [comment]
That all goes through Curseforge, we can't do anything about it. You'll have to wait until they fix whatever issue is going on.
