### ISSUE TITLE
[Suggestion] Make the Resourceful Bees Hive quest accept hive upgrades

### ISSUE THREAD

**Issue by ixanza** [AllTheMods/ATM-6#2673]
The Beehive quests (Tier 1-4) only get completed if you're crafting up beehives. Resourceful Bees allows for crafting hive upgrade (same recipe) that you can right click on the hives to tier them up. This is easier but unfortunately doesn't count towards the quest. Would suggest making it check for either the hive upgrade or the hive itself.

would also consider an apiary recipe that can make use of these hives as I just found out they're not valid for the recipe. Major resource loss if not

**Comment by Pdiddy973** [comment]
The apiary recipe is fixed, and its not super practical to add each hive, for each tier for the quests.
