### ISSUE TITLE
[Bug]: Projection render error

### ISSUE THREAD

**Issue by binglingyao** [AllTheMods/ATM-6#2675]
### Possible Fixes

Yes

### Modpack Version

1.8.9

### What happened?

Rendering errors!
include list(As far as I know):
- Botania
- Building Gadgets
- Blood Magic
- Create
...
All mods with projections
I had this problem, along with several other players who played with me (installing packs in various ways).  
Create even has a mechanical dislocation problem!

After testing, I installed Chinese and JEI pinyin search has no effect on this problem (compared to the original package)  

Use the original package log here!

![QQ截图20211108224912](https://user-images.githubusercontent.com/60381869/140765216-922e2555-28db-4dd7-b90a-a68e757a8e01.png)
![QQ截图20211108224958](https://user-images.githubusercontent.com/60381869/140765237-30342dfd-f7ca-4ff0-a2ff-695308ea0c17.png)
![QQ截图20211108225159](https://user-images.githubusercontent.com/60381869/140765251-ee5bd7fe-90b2-4cf7-b3d2-f89186e7034d.png)

### latest.log

https://gist.github.com/binglingyao/7f46ec10af77c447fc9c46d6e8472254

**Comment by binglingyao** [comment]
If this is an installation error, please let me know!
The installation package is from the Curseforge & MultiMC 5 & HMCL launcher

**Comment by jeremiahwinsley** [comment]
Does this happen in single player? If all the players are experiencing it, it might be caused by the server. I see that the server is running BungeeCord/Mohist, which is not supported and is known to cause issues with ATM6.

**Comment by binglingyao** [comment]
Yes! Single player games don't have this problem! It's a server problem, too bad.
So I switched to Minecraft Forge Server.
Thank you very much!
