### ISSUE TITLE
[Question]: Draconic evolved information tablet no craftable ?

### ISSUE THREAD

**Issue by Sleepless-Norbert** [AllTheMods/ATM-6#2679]
### What would you like to know?

Hello, so I'm on ATM6 Version 1.8.8, and Im unable to see a recipe for the Draconic Evolved Information Table. Is there a way to craft it or is Draconic not meant to be used. Many thanks.

**Comment by jeremiahwinsley** [comment]
The tablet itself is not implemented yet, but the rest of the mod should work fine.
