### ISSUE TITLE
[1.2.1] Lagspikes caused by memory usage

### ISSUE THREAD

**Issue by emniss** [AllTheMods/ATM-6#268]
**Description:**
The game freezes for a few seconds and then unfreezes for about 5 seconds and repeats untill the game is restarted. I have tried to wait it out but it does not go away on its own.
From the F3 memory counter the cause is the game using more memory than the allocated amount, freezes while it clears a few GB:s and then quickly ramps up the memory usage again until it uses more again and repeats.

**Steps to reproduce the behavior:**
1. Enter a world
2. Play for about 10-30 minutes on singleplayer or 1-3-hours in multiplayer. Being in the nether makes it come sooner. Exporing in creative makes it occur much sooner.
3. Repeated freezing occurs.

**Additional context:**
- Allocated memory: 8192MB through the twitch launcher.
- Higher end, modern GPU and CPU. 16GB total RAM
- Friend with similar setup experiences the same problem.
- The server hosting the game keeps ut fine with no tps lag.

**Comment by ViRb3** [comment]
This is most probably a memory leak. I am tracking a major memory leak myself, so far it seems like something is retaining copies of the JEI "ItemFilter" object, which is 300-400MB each. I don't know if that's the same issue as you, and I don't know exactly how to reproduce it. I will post here or in a new issue depending on my findings.

**Comment by emniss** [comment]
Ok, I'll do the same if I see more patterns in the lag spikes.

**Comment by ViRb3** [comment]
I discovered at least one memory leak affecting this modpack: https://github.com/Alex-the-666/Citadel/issues/12

**Comment by ViRb3** [comment]
Workaround for the bug linked above, thanks to the mod author - on your **server**, edit the file `config/citadel-common.toml`, and set `"Track Entities" = false`. This will prevent the event that uses up RAM from happening in the first place.

**Comment by ViRb3** [comment]
I can confirm the initial memory leak related to JEI. For reference, I am tracking it here: https://github.com/mezz/JustEnoughItems/issues/2148

**Comment by ViRb3** [comment]
I have submitted a bunch of patches to JEI that fix all significant memory leaks I could come across during my testing. They will be out in the next JEI update, and hopefully in the next ATM6 release.

**Comment by ViRb3** [comment]
All mentioned fixes have been merged in for a while. Some more JEI leaks remain, which I will be looking at soon :tm:.
