### ISSUE TITLE
[Bug]: Allthemodium, unobtanium, vibranium dupe

### ISSUE THREAD

**Issue by PORTB** [AllTheMods/ATM-6#2681]
### Possible Fixes

Yes

### Modpack Version

1.8.9

### What happened?

![image](https://user-images.githubusercontent.com/34615701/141193146-bbf88f10-bbac-43ab-b9d3-2ae5f3fe5e0f.png)
This recipe is incorrect, I am assuming the atm ingot is supposed to be ore? 
It allows for infinite duplication of atm.
Same issue exists for vibranium and unobtanium 

### latest.log

https://gist.github.com/PORTB/30ef07c0caa2ddbc7f22d68f9de70696

**Comment by Pdiddy973** [comment]
this will be fixed next update

**Comment by Pdiddy973** [comment]
Fixed in 1.8.10
