### ISSUE TITLE
[Feature]: Permanent Removal of Mekanism requirement from the ATM star recipe.

### ISSUE THREAD

**Issue by zookeper** [AllTheMods/ATM-6#2682]
### Feature Details

I would like to see that broken mod removed from such a vital part of this mod pack. I love playing all these mods! So much that I have played almost every day for the last 10 days. I have played minecraft on and off for years. I love how far it's progressed. I remember IC2 and when redstone and basalt got added.

With that being said. over these last few years of playing Modded packs it appears that Mekanism is in quite a lot of them. There are a plethora of issues that I have with that pack and that pack SPECIFICALLY. The multiblocks are so buggy they never properly load and anything attached to them needs to be reset constantly. This is prevalent as you can search on gitbhub multiple different mods have hundreds of posted bugs that relate specifically to mekanism multiblocks.

The main issue is that the reactors are turning on, on restart and while that may seem like a server owner issue it is indeed not. This responsibility of a mod exhibiting certain affects is not taken by any server host.

A host may need to change things to get everything to work as they intended. Regardless of that. 

Do you think it is any feasible accomplishment to cause your multiblocks to have an intentional failure to troll people?

Listen here. I literally came on to get the atm star, because yay atm star! can you get it?! and i cant get it because this one single mod has so many issues. I am building a cool building with some creative items for enhanced decoration for fun and then leaving. Why is this one single mod causing so many issues and preventing me from having fun. I had considered just quitting this pack alltogether because of the bs frustration the pack is actually giving me. Mind you, how many modpacks are here? and I am using most of them? and the only one is giving grief. REAL GRIEF.

Why is it that when i go to their github and see a plethora of issues with their multiblocks breaking and request a feature to have the reactors and multiblocks manually start when they are open by a player (because they are breaking when the player who built them is not online and loading chunks when they start up) this is causing reactors to explode. pipes needing to be reconfigured constantly. and this isn't just exhibited by me and the server  I play on.

When I posted a featured request on mekanism for them to fix it (because I think a few years of reactors blowing up not due to what you do) is more than just a flaw the mod member, not even the dev. just directly replied with "no" and closed my request. 

This is alarming because that means he was admitting that this feature is coded if you look close enough in their source code as it's all online you can see it.

They offer no resolution and I think it's incredibly harsh that I even have to go this far just to enjoy a game.

Should people be getting griefed by this mod and this mod alone for how long has this been going on for? 

Please please please just remove anitmatter from the atm star recipe. Their multiblocks are so buggy a server owner could need to change a few things and then they are broken and it's blamed on other people by mekanisms commuunity and they dont even offer any resolutions to it. just. "Is there logic to turn it off?" "it's your server owners fault"

look at their github page and see who has closed requests and what the requests where about you will soon realize the intentions of mekanism and their small small community.

It's mind boggling that through all these mods all of them work almost flawlessly with each other BUT mekanism and ONLY mekanism. This isn't just a new issue and im sure you guys know this!

The reason IO am requesting this here is because of the negligence that I have personally experienced with mekanism mod and their associated members. I want to save everyone grief. there's no reason why anyone including me would quit this pack because of one mod. Several people have quit my server and others because of this and there is enough evidence on the github to suggest its intentional. I have several mod developers on githib acknowledge this issue and confirming its mekanism but when this situation is addressed to mekanism community the response is "NO" and that is literally it.

**Comment by jeremiahwinsley** [comment]
There is an option to turn meltdowns off, in `config/Mekanism/generators.toml`.

The issues with inconsistent startup are basically due to chunk loading - if the reactor is chunkloaded but not the water supply for example, you'll have issues. That can also cause the pipe disconnects, etc. Typically, if the reactor and all inputs/outputs are fully chunkloaded, you won't have issues with this. Obviously there are scenarios where this breaks down, like servers with chunkloading disabled, but for most of our players this works fine.

Manual or automatic redstone control should still work when chunkloading is disabled, as long as they are in the same chunk as the reactor itself, so they'd be loaded whenever the reactor is loaded.

**Comment by zookeper** [comment]
AFAIK, regardless of chunks loading it appears that these multiblocks are causing a plethora of errors, in the past 3 years I have come back on and off of playing modded minecraft and my experience on multiple servers regardless of what the hosts have done results in an enormous amounts of bugs. Mostly all with just mekanism alone. 

I am hesitant to build something that causes this many issues for all I know this single multiblock is the reason the few servers I play on have crashed.

I requested a feature on mekanism to turn the multiblocks off unless opened by the player that owns it. so in the future there wouldn't be any load time issues nor will there be unexpected chunks not loading (all of mine are force loaded btw and this still occurs)  WE use pipez mod because even mekanisms pipes lag and crash servers if people hook them up (outside of a chunk so its not loaded) if the pipes alone from mekanism cause this then imagine what damage the reactors are actually doing every time the multiblock fails to load.

**Comment by zookeper** [comment]
AFAIK I have redstone coming from the reactor. set from both over heat and over damage, into a redstone torch and it still will melt down. all Vanilla redstone logic... which doesn't even require to be chunk loaded.

Whatever these server hosts in the past have done is irrelevant meaning to the fact that more than a hundred posts on their github of closed reports suggest that they either coded a brake intentionally or just don't know how to and never have known how to fix it.

There aren't that many ATM 6 public servers. To be perfectly honest people say oh these packs have too many mods public servers are unstable...

Well. Between Environmental tech deleting its own void miners and not returning crafted blocks. 

And Mekanisms flawed mutliblocks and pipes... 

Every other mod works flawlessly.......

**Comment by zookeper** [comment]
I am playing the most recent pack btw. 1.16.5

**Comment by zookeper** [comment]
And fyi turning off reactor meltdowns is not acceptable. Some people like the risk but really being grief by bad coding is just unacceptable. 

I am at the point in the game where I have all the items for ATM star ready to go and im literally being told i have to ask the server owner to turn off reactor meltdowns?

**Comment by zookeper** [comment]
May as well load creative and throw legitimacy out the window.

Hey maybe they can spawn me an atm star too. :/

**Comment by zookeper** [comment]
My issue mainly is mekanisms attitude about the matter. Just review their github. all the issues and how the members handled the responses.

**Comment by Pdiddy973** [comment]
I can safely say I have no plans to remove melanism from the star, and I don't think anyone else in the dev team does either, I personally have never had an issue with any of the melanism multiblock...but doesn't mean they don't have issues. That said, mekanism is staying

**Comment by zookeper** [comment]
Alright but this is a pretty big cavate because you small amount of contributors seem to have no issues but the thousands of people playing it do. :(

**Comment by zookeper** [comment]
You should probably just make them fix the issue rather than say that you got it to work that could be 1% of the working order is you and a few others.

**Comment by zookeper** [comment]
I did mention ive played these packs for years and I did mention this happened on multiple servers.
