### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by MsAudible** [AllTheMods/ATM-6#2683]
### Possible Fixes

Yes

### Modpack Version

1.8.5

### What happened?

mod pack isnt supporting block updates, im trying to run redstone through a tree from a tree farm but it wont go through due to the fact that its not recognizing the signal going through.
![unknown](https://user-images.githubusercontent.com/94139839/141359590-459e47a7-8e8d-488e-af08-5fcd113de702.png)
![unknown (1)](https://user-images.githubusercontent.com/94139839/141359601-8d872a34-f139-4a3e-8d92-d7c47b075f1e.png)

### latest.log

https://gist.github.com/MsAudible/2616fc6b64704922b7166b8c99ae09b4

**Comment by jeremiahwinsley** [comment]
You don't have the redstone connected to the tree on the other side.

**Comment by MsAudible** [comment]
> You don't have the redstone connected to the tree on the other side.

Ive tried the setup in numerous different ways, repeater pulling from the tree, Redstone being placed differently like you mentioned  nothing works, like i said, ATM 6 struggles with blockupdates, multiple people have looked at the setup, this setup is even from a youtuber and it worked for him.

**Comment by jeremiahwinsley** [comment]
![2021-11-11_16 39 24](https://user-images.githubusercontent.com/7946299/141372794-2de2dd01-5bd6-48d6-9ab2-9319a2965f85.png)

this seems to work the same way it does in vanilla

**Comment by MsAudible** [comment]
I have no idea, no matter what i do, it refuses to work once the tree is grown, the block says its receiving a signal but it doesnt go further than that

**Comment by jeremiahwinsley** [comment]
What kind of tree is it? Perhaps that specific type does not support it. Alternately, you could just use an observer.

**Comment by MsAudible** [comment]
Just a regular oak tree
