### ISSUE TITLE
[Bug]: Can't Imprison Dragons 

### ISSUE THREAD

**Issue by JustBlankXD** [AllTheMods/ATM-6#2684]
### Possible Fixes

Yes

### Modpack Version

1.8.9

### What happened?

I saw on YouTube how YouTuber used the imprison Tool from industrial foregoing to catch dragons from ice and fire and i tested it on a custom pack and it worked there. but on the ATM6 modpack it doesnt work 
And if it's on purpose can u just tell us how to turn that off in configs :(

### latest.log

I don't know what u mean with log file

**Comment by Pdiddy973** [comment]
Intended change

**Comment by lyssar** [comment]
@Pdiddy973 so this means that there is no way to automize dragon farming for blood, bones and scales anymore?
