### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by Tasenova99** [AllTheMods/ATM-6#2687]
### Possible Fixes

Yes

### Modpack Version

1.8.9

### What happened?

My server has stopped working ever since a power outtage, I don't know how to fix it, I need help. I was just using the simple server setup. 

### Crash Log

EDITED: NEW LOG

https://gist.github.com/Tasenova99/f609657bc6122bace1bd233c4f429134

**Comment by Tanyrus** [comment]
Your crash log shows that is failed to bind the port. Why not try to use a different port and see if it starts?

**Comment by Tasenova99** [comment]
what about now?
