### ISSUE TITLE
[Bug]: No Generation of end dragon

### ISSUE THREAD

**Issue by Aguni-Ignis** [AllTheMods/ATM-6#2688]
### Possible Fixes

Yes

### Modpack Version

1.8.9

### What happened?

I reseted the dimentions when i updated the pack and the portal that can make new end dragons is missing is this because of the update of the pack or something else
![image](https://user-images.githubusercontent.com/94395686/141833769-0af18503-56ee-4476-9b98-83d2fab38ed9.png)

The latest log looks funky i opened with notepad++

### latest.log

https://gist.github.com/Aguni-Ignis/5537155769e872f2073da052830e7fa9

**Comment by jeremiahwinsley** [comment]
This happens when you reset the end, you can just manually rebuild the portal in creative and it will work again. The center of the portal goes at 0,0. Y level should be on or slightly under the surface - you may need to try a couple times to get the Y level correct.
