### ISSUE TITLE
[Crash]: I can't start the game

### ISSUE THREAD

**Issue by lm4mine** [AllTheMods/ATM-6#2690]
### Possible Fixes

Yes

### Modpack Version

1.8.9

### What happened?

I try to install the modpack, and this keep happening

"Error loading mods
2 Error have occured during loading

Failed to load mod

Failed to load mod"

I already try to re-install the modpack, i'um using multi-mc for the modpack, try to install it with the .rar on curse and by the system of download in multi-mc
![Capture d’écran 2021-11-15 213305](https://user-images.githubusercontent.com/63981223/141849930-7a300444-9cb9-4471-ab7e-e22d8e3a6cad.png)

Thank you

### Crash Log

https://gist.github.com/lm4mine/fa429261106973df750d26de880cf655

**Comment by Pdiddy973** [comment]
this is usually due to bad downloads, i would try to install again, or your antivirus may be picking up false positives during the download.

**Comment by lm4mine** [comment]
I already desinstall it and install it again multiple time without result :/ I will try with my antivirus off ( by curseforge the modpack work so if the solution doesn't work, i will just play on curse) thank you for your response

**Comment by Pdiddy973** [comment]
also try with the built in way to install the pack, instead of downloading the zip then importing the zip. it may help....I've uninstalled and reinstalled 1.8.9 several times w/o issue
