### ISSUE TITLE
[Bug]: Missing Yellow cake uranium recipe

### ISSUE THREAD

**Issue by EnabledEnzo** [AllTheMods/ATM-6#2691]
### Possible Fixes

Yes

### Modpack Version

1.8.9

### What happened?

Yellow cake uranium block has no recipe.
https://imgur.com/a/zv3E32N

### latest.log

https://gist.github.com/EnabledEnzo/5ba3bf481fde0de56ad5bb8ed407aeec

**Comment by Pdiddy973** [comment]
Fixed in 1.8.10
