### ISSUE TITLE
[Question]: Fire & Ice Structures, mobs

### ISSUE THREAD

**Issue by Talooli** [AllTheMods/ATM-6#2706]
### What would you like to know?

So would I be able to get an answer on where to find the following structures and mobs?

Mausoleum
Graveyard
Gorgon Temple
Trolls
Cyclops
Hydra
Amphitheatre 
Hippogryphs
Hippocampi 
Pixies
Death Worm
Sea Serpents

**Comment by Aavar6802** [comment]
I have been able to find dragons, hydra, and cyclops in the other. Nothing else so far.

**Comment by jeremiahwinsley** [comment]
Sea serpents spawn in Twilight forest lakes, pixies should spawn in The Other. The rest do not spawn.
