### ISSUE TITLE
[Crash]: Cant keep up!

### ISSUE THREAD

**Issue by Janvier123** [AllTheMods/ATM-6#2708]
### Possible Fixes

Yes

### Modpack Version

1.8.9

### What happened?

We started the server a few days ago, running on a Win7 SP1 old gaming PC

- i7 4770 CPU @ 3,4Ghz
- 16 GB DDR 4 Ram
- 60GB SSD
- all latest drivers

However we keep getting lagg spikes and overall slowness, Its says in the console (We use the CMD file)

=> [19Nov2021 14:49:18.223] [Server thread/WARN] [net.minecraft.server.MinecraftServer/]: Can't keep up! Is the server overloaded? Running 22867ms or 457 ticks behind

Eventually the server is so far behind its just restarts, we changed the ram options, more ram, less ram, ... it does not matter.
This is happening with only 1 player, it gets worse the more play

We need a fix asp!
![cant_keep_up](https://user-images.githubusercontent.com/1528455/142636892-ee1885ba-8c53-4530-a053-d2b26671ab01.png)

### Crash Log

https://gist.github.com/Janvier123/97993c54b3c3015395bc8585a9c1cdcf

**Comment by Pdiddy973** [comment]
This is not really a bug, but just server performance, please run a spark profile and see where the laggy is coming from. Asking about this in our [Discord](https://discord.gg/K5FBPYa) would likely be better aswell
