### ISSUE TITLE
[Bug]: 1.8.10 - Resourceful Bees Beehive

### ISSUE THREAD

**Issue by BlackWolf101** [AllTheMods/ATM-6#2712]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

In v1.8.9, the bees inside my Tier 1 beehive always left through the front of the block (where the honey drips). When I updated to 1.8.10, the bees now leave from all sides of the block, including into occupied spaces such as stone walls, which results in suffocation.

### latest.log

<script src="https://gist.github.com/BlackWolf101/88549c8fc7490d438057f2ed97fb2328.js"></script>

**Comment by ben569** [comment]
Your log doesn't seem readable (broken link?), also, has anyone been able to reproduce this? I've delayed updating my server because of this.

**Comment by BlackWolf101** [comment]
> https://gist.github.com/BlackWolf101/88549c8fc7490d438057f2ed97fb2328.js

I'm not used to posting logs, so maybe the link doesn't work as it should, but I copy and pasted it into a fresh tab, and it brought up a wall of text that looks like a log to me. I'm not really sure, let me know if that doesn't work for you and I'll try to repost it.

I wasn't sure how to really test this bug, but I have a pretty big bee setup and noticed a bee got out of my setup almost immediately when I updated. Then I caught a 2nd bee dying in a wall not 5 minutes later. It might be localized to my setup, but I'm not really sure. I simply rolled back the version, and haven't had any issue since.

My suggestion would be to test it for yourself if no one else is having the issue. I saw the issue almost immediately, so just set up a box in creative for a couple of harvest cycles, and if none of the bees escape, then you should be good. There are definitely some work arounds to the issue if you're building a new setup, but I didn't want to rebuild my whole setup around the bug. I was just hoping someone would confirm it was a change in the latest version of the mod or something

**Comment by jeremiahwinsley** [comment]
After some testing on 1.8.14 the bee seems to go in and out of the correct side. There have been no changes to bees in any of the recent versions, including 1.8.10. So this could have been a mod interaction that was fixed.
