### ISSUE TITLE
Save won't load after 1.8.10 update.

### ISSUE THREAD

**Issue by Sajdix** [AllTheMods/ATM-6#2713]
World won't fully load after update - stuck at 100% loading screen and nothing happening for x-minutes (waited 30min). I have reloaded to previous version (worked) and back to 1.8.10 - still stops at 100%.

**Comment by zBasilioMaster** [comment]
Did it worked?

**Comment by Sajdix** [comment]
Nope, i started new game bcs this wont go :(

**Comment by thevortex** [comment]
please provide a copy of the files from the log folder, debug.log and latest.log, put them on pastebin or gist.github.com we cannot help a stuck loading state without logfiles

**Comment by Pdiddy973** [comment]
Also if you could provide the world as a zip, can be helpful aswell

**Comment by SongXia-NYU** [comment]
I have the same problem:
Log files: https://gist.github.com/SongXia-NYU/751af4005e28d12a9b35fa574d677876
World: https://drive.google.com/file/d/1bc3C6_3-Fhlv5RA3BH1p3dWjOp28PHfi/view?usp=sharing
Thanks!

**Comment by Sajdix** [comment]
Sorry for waiting:
Latest Log: https://github.com/AllTheMods/ATM-6/files/7604829/latest.log
World: https://drive.google.com/file/d/1lCl8zC4L87wvuXCAOFUiP3sJkDyhqXAP/view?usp=sharing
Logs: https://drive.google.com/file/d/1tsokxCZ_a5umLNur3Fd6ke2weK4LfDcK/view?usp=sharing
IDK where debug.log is

**Comment by jeremiahwinsley** [comment]
This should be fixed in 1.8.12.
