### ISSUE TITLE
[Crash]: Updating to 1.8.10 Crash

### ISSUE THREAD

**Issue by RobertPoston** [AllTheMods/ATM-6#2714]
### Possible Fixes

Yes

### Modpack Version

1.8.9

### What happened?

Updating the server to 1.8.10 from 1.8.9 results in a timeout when loading a previous world.

The last output of the console is: [Flux Networks/]: FluxNetworkData has been successfully loaded
Normal behavior would pass to corail tombstone loading contributors then to advancements.

The crash is caused by a single game tick taking longer than 60 seconds. Restarts all make it to the same point. Server doesn't respond to commands, but reports as online while frozen at the output mentioned above.

Reverting to 1.8.9 works. The world in question is rather large and while a new world/installation does work on the same machine, I would rather not lose the progress.

### Crash Log

https://gist.github.com/RobertPoston/2d274fc8acd3488e714696475f6ae9bb

**Comment by jpwanabe** [comment]
Same issue on my server as well. Server is over 25gb large at this point with the amount of players we have, even with a world border. My crash is as follows. I hope it helps as well. Our time out time is 10 min for this crash log.

https://pastebin.com/NH8NHNvq

**Comment by Xplodin** [comment]
Getting this issue and its damn near annoying.
is there any fix for this?
I cant load my world whatsoever and it has me thinking 1.8.10 corrupted the worlds

**Comment by jeremiahwinsley** [comment]
This is apparently a bug with Polymorph. As a workaround, you can edit `config/polymorph-integrations.toml` and set `refinedstorage` and `appliedenergistics2` to false.

**Comment by jpwanabe** [comment]
While that did work when trsting that also caused people to crash when opening their systems. I did manage to fix mine and update it. For me the issue was a wireless network transmitter that was not receiving any connection in the Twilight Forest. After destroying these blocks I was able to update properly.

**Comment by jeremiahwinsley** [comment]
This should be fixed in 1.8.12.
