### ISSUE TITLE
[Bug]: 1.8.10 - Holding a broken Silent Gear tool in hand causes major FPS lag

### ISSUE THREAD

**Issue by Tman7077** [AllTheMods/ATM-6#2715]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

When holding any Silent gear tool in hand (main hand or offhand), there's quite a large dip in FPS. Attached is a short video with the debug overlay, you can see the FPS dip as soon as I switch to the tool and work much better as soon as I switch off of it. This happens with any and every Silent's tool that breaks.

Steps to recreate:
1. Create any tool with Silent Gear
2. Use said tool until its durability reaches zero, "break"ing the tool
3. Experience lag spike
4. Switch selection off of tool
5. Experience no lag spike :)

I am in version 1.8.10, forge 36.2.8 (both in the debug screen), and I have not added, removed, or edited any mods or configs besides OptiFine.

https://user-images.githubusercontent.com/68248730/142750073-751194d2-8085-4c41-a814-f9e8045f2165.mp4

### latest.log

https://gist.github.com/Tman7077/431599e3733c1f5b909ef52af3701a46

**Comment by jeremiahwinsley** [comment]
Tested this and I don't have any observable lag from this. Can you test without Optifine and see if you still experience the lag?
