### ISSUE TITLE
1.8.10 Opening map crashes game[Crash]: 

### ISSUE THREAD

**Issue by bsovers** [AllTheMods/ATM-6#2719]
### Possible Fixes

Yes

### Modpack Version

1.8.10

### What happened?

Hit "m" to display the map (Also, the mini-map was not showing)

### Crash Log

https://gist.github.com/bsovers/7ca107840d34c4777c53cdec6db8d6b5

**Comment by jeremiahwinsley** [comment]
Typically this happens when the FTB Chunks map data is corrupted - try deleting or renaming the local/ftbchunks folder and see if that fixes the issue.
