### ISSUE TITLE
I cant install ATM 6 from the twitch app

### ISSUE THREAD

**Issue by Redwooddude** [AllTheMods/ATM-6#272]
Hey! I have been playing ATM since 3 and I tried to install ATM 6 from the twitch app but it says it cannot find the specified file.

Is anyone else having this issue or is it just me? I can install other mods, just not ATM 6 for some reason. 

Thanks in advance!

**Comment by NetMasterFlex** [comment]
Did you make sure the game was listed under installed profiles for Minecraft before launching?  Also an alternative is to use an app called Muti-MC.  I had hit or miss issues using the Twitch app for ATM6 modpacks.  Also you need to ramp up your RAM and allocate at least 8192MB in the Minecraft tab under settings, otherwise the pack will crash at load for lack of memory.
NMF

**Comment by Meey666** [comment]
Twitch has a problem with forge and will not install it with the modpack for newer minecraft versions. You can download it by hand, install it and then you can install the pack from twitch launcher. It must be the same version specified for the modpack, or it will not work. For ATM6 1.2.1 - Forge version is 34.1.25

How to get forge: http://files.minecraftforge.net/

How to install by hand for twitch: https://www.youtube.com/watch?v=xhriIUuzVxw

**Comment by Redeye123** [comment]
For everyone with this issue just make sure if you use twitch to check your install location of minecraft (check minecraft options in twitch options ) and make sure it doesnt have an space in it  . 

For example c:/minecraft worlds/twitch/ will get you that error
                      c:/minecraft/twitch/ will work great

**Comment by Thunder-Nova** [comment]
I'll keep this short, Twitch has way too many problems with minecraft at this date regarding a bug if you have multiple versions. Right now the official app that will take minecraft will soon be overwolf.

I recommend for now to use [GDLauncher](https://gdevs.io/) or [MultiMC](https://multimc.org/).

@Redeye123 
@NetMasterFlex 
@Redwooddude 
@Meey666

**Comment by WhitePhant0m** [comment]
As Nova said, It's just twitch being bad and not working with newer MC versions. Use a different launcher or fix the spaces in your filepath.
