### ISSUE TITLE
[Crash]: FTB Chunks map and Quests menu crashes game.

### ISSUE THREAD

**Issue by Mattimus123** [AllTheMods/ATM-6#2726]
### Possible Fixes

Yes

### Modpack Version

1.8.10

### What happened?

When I attempt to open the FTB Chunks full screen map it crashes my game. The same thing happens when I attempt to open the quest menu.

Also, the Journeymap minimap has disappeared.

### Crash Log

https://gist.github.com/Mattimus123/6047dd345d522b7b994b5d3b46273ac9

**Comment by jeremiahwinsley** [comment]
Occasionally the FTB chunks data gets corrupted - you can delete the local/ftbchunks folder to reset it, which should fix this issue.
