### ISSUE TITLE
[Bug]: Immersive Engineering's Engineer's Workbench can't craft with any blueprint

### ISSUE THREAD

**Issue by NanJack1998** [AllTheMods/ATM-6#2728]
### Possible Fixes

Yes

### Modpack Version

1.8.10

### What happened?

while upgraded to the latest 1.8.10 version of atm, i create a new world just for fun, after i make an Engineer's Workbench from the Immersive Engineering, i found that i can't craft anything through the workbench with any blueprint, even i tried it in a creative world created after i found the problem

### latest.log

https://gist.github.com/NanJack1998/80fbff6c921bca9c7f6e9a2bc5732755.js

**Comment by jeremiahwinsley** [comment]
Tested in 1.8.12 and crafting seems to work fine.

**Comment by NanJack1998** [comment]
> Tested in 1.8.12 and crafting seems to work fine.

still can't work in a fully new installed ATM 2.0.0 ver single world

Log:[https://gist.github.com/NanJack1998/4246934b2b1c098eb07c66cd3d0f8bf6](url)

Screenshot:[https://imgtu.com/i/o6umEn](url)

**Comment by jeremiahwinsley** [comment]
Yes, that's working. You need to put the ingredients into the table before you can craft them.
