### ISSUE TITLE
Blocking with a Phalanx I enchanted Steel Shield crashes my client

### ISSUE THREAD

**Issue by jackkenn** [AllTheMods/ATM-6#273]
**Describe the bug**
Blocking with a Phalanx I enchanted Steel Shield crashes my client

**To Reproduce**
Blocking with a Phalanx I enchanted Steel Shield crashes my client

**Expected behavior**
to not crash

**Screenshots**
![image](https://user-images.githubusercontent.com/55853855/98409389-5d451d00-2038-11eb-879c-a6e74d484e86.png)

**Additional context**
I am sorry if I did not follow guidelines for bug reporting, just wanted to help.

Error Code: The game crashed whilst ticking entity
Error: java.lang.IllegalArgumentException: Modifier is already applied on this attribute!
Exit Code: -1

[crash-2020-11-06_14.00.46-client.txt](https://github.com/AllTheMods/ATM-6/files/5503223/crash-2020-11-06_14.00.46-client.txt)

**Comment by razma417** [comment]
I just submitted a bug, it happens with any enchanted mekanism shield it seems like. Made 2 different refined obsidian shields and enchanted them to test, both crash server instantly.

**Comment by jeremiahwinsley** [comment]
Fixed in 1.3.9.
