### ISSUE TITLE
[Crash]: nether CRASH 

### ISSUE THREAD

**Issue by modald** [AllTheMods/ATM-6#2730]
### Possible Fixes

Yes

### Modpack Version

1.8.10

### What happened?

the game is running smoothly all the time but when I wanted to go to the nether for the first time it crashed my game I tried it again and the same thing happened and also it just took me out of the game and tell me that the game crashed

### Crash Log
[crash-2021-11-25_21.18.28-server.txt](https://github.com/AllTheMods/ATM-6/files/7604805/crash-2021-11-25_21.18.28-server.txt)

**Comment by jeremiahwinsley** [comment]
It looks like you removed Biomes O' Plenty. That will cause this crash unless you remove the BOP biomes from `config/byg/byg-nether-biomes.json` also.

**Comment by modald** [comment]
thank you so much it worked i removed it because when i want to load a world it takes 15 min in the reading world data screen and some one told me to remove it thank you
