### ISSUE TITLE
[Crash]: Clicking farmland with a hoe crashes the game.

### ISSUE THREAD

**Issue by NerdySpider** [AllTheMods/ATM-6#2734]
### Possible Fixes

Yes

### Modpack Version

1.8.10

### What happened?

Not sure why this happening, though for some reason, accidently right clicking on farmland causes the game to freeze and then crash. Makes it rather hard to fill out a large area when you got to be worried about accidently right clicking a already tilled farmland piece.

### Crash Log

https://gist.github.com/NerdySpider/1c9b3c13802e71b9f4f3f6e3e0b0f16d

**Comment by SoftGuardian** [comment]
Maybe the Forbidden & Arcanus hoe is buggy, try to use a vanilla hoe

**Comment by jeremiahwinsley** [comment]
The bone hoe was removed in 1.8.12, so this should fix the issue.
