### ISSUE TITLE
[Bug]: Keybind "Decrement Throttle" does not work (Iron Jetpacks)

### ISSUE THREAD

**Issue by Gronkelx** [AllTheMods/ATM-6#2737]
### Possible Fixes

Yes

### Modpack Version

1.8.10

### What happened?

https://user-images.githubusercontent.com/93834569/143771998-a0b5e1e0-181e-47ce-a0b2-4cfdd7d604c4.png

### latest.log

-

**Comment by jeremiahwinsley** [comment]
You likely have a conflicting keybind. I tested by assigning it to an unused key, and it worked fine.
