### ISSUE TITLE
Can't craft sand in a 2*2 grid

### ISSUE THREAD

**Issue by DeathOfTime** [AllTheMods/ATM-6#274]
**Describe the bug** v1.2.1 of ATM6
Crafting sand using two fire essences and two dirt essences from mystical agriculture won't work in a 2x2 grid. Even though it will fit in one. It will work just fine in a 3x3 grid
![2020-11-06_18 04 53](https://user-images.githubusercontent.com/15230368/98425453-c047ab80-205a-11eb-80d3-4cbbb76f0c3e.png)
![2020-11-06_18 05 08](https://user-images.githubusercontent.com/15230368/98425454-c0e04200-205a-11eb-8ca6-e2d7d568e91f.png)
![2020-11-06_18 05 23](https://user-images.githubusercontent.com/15230368/98425455-c178d880-205a-11eb-95c6-c2cfa91863e0.png)

**Comment by NetMasterFlex** [comment]
Has this ever worked pre 1.2.1?  Reason I ask is because this is a heavily modded pack so there may exist some small convenience losses as a result.  If this was working pre 1.2.1, then there is valid reason to call it a "bug".
