### ISSUE TITLE
[Bug]: Many redundant statistics for all food items

### ISSUE THREAD

**Issue by jacket430** [AllTheMods/ATM-6#2740]
### Possible Fixes

Yes

### Modpack Version

1.8.10

### What happened?

When you highlight any food item, you see the hunger in icons, 2 rows below you see hunger and saturation in text and below that you see hunger and saturation yet again represented with icons.

The way the tooltips are currently set up, there are 3 places to see hunger and 2 places to see saturation in the same tooltip. You can see an example [here](https://i.imgur.com/FlBorZk.png).

I definitely think this is a bit overkill and would love to see that remedied. There's no point in showing the same stats 5 times. 

### latest.log

https://gist.github.com/jacket430/6eca0f929580d0782f6bf49449f8f156

**Comment by jeremiahwinsley** [comment]
Removed the duplicate icon stat sections in 1.8.12.
