### ISSUE TITLE
[Crash]: Multiple client crashes

### ISSUE THREAD

**Issue by bobothehobo2** [AllTheMods/ATM-6#2741]
### Possible Fixes

Yes

### Modpack Version

1.8.9

### What happened?

This has happened randomly over the weeks with ProjectRedIllumination being the latest.  What happens is when I try to mine a block the client freezes for about 10 seconds, saves the world and exits.  So far it's happened on the ender tank (which when you load back in from the crash if you're looking at one it crashes immediately again) a building gadgets construction paste block & now the red inverted lamp.  It dawned on me today that the commonality was all of them happen when using mekanism's disassembler (all but the ender tank were ftb vein mined).  So when I got back in I reset the crash conditions and tried using a different pick and it worked fine.  I've attached 3 crashes associated to this behavior for some variety of examples.  Thanks!

### Crash Log

https://gist.github.com/bobothehobo2/c5f60feda0c50b1e46c9bdd03fb92e03

**Comment by jeremiahwinsley** [comment]
Looks like an Optifine crash, if you can reproduce this without Optifine please attach that crash report.
