### ISSUE TITLE
[Bug]: Environmental Tech, Crystal Lens

### ISSUE THREAD

**Issue by FishKn8** [AllTheMods/ATM-6#2742]
### Possible Fixes

Yes

### Modpack Version

1.8.10

### What happened?

So in the Version  1.8.10 in the mod Environmental Tech, you are not able to craft the laser crystal lens, nor configure it in the Lens Grinder.

### latest.log

https://gist.github.com/FishKn8/5e24275adaf054a2de5a61a251affa61#file-latest-log

**Comment by jeremiahwinsley** [comment]
Tested in 1.8.14 and I was able to succesfully craft a block of Litherite into a Litherite Lens.
