### ISSUE TITLE
[Bug]: Bigger Reactors not being cooled or regulated by any type of coolant/regulator. 

### ISSUE THREAD

**Issue by Solj1n** [AllTheMods/ATM-6#2744]
### Possible Fixes

Yes

### Modpack Version

1.8.10

### What happened?

So yeah, went from water to liquid starlight, no difference, tried diamond blocks, nothing... checked the JSON files in the mod folder for it and the data seems to be there, just not going into effect.  

{
    type: "registry",
    location: "astralsorcery:liquid_starlight",
    absorption: 0.85,
    efficiency: 0.8,
    moderation: 2.0,
    conductivity: 3.0,
}

{
    type: "tag",
    location: "forge:storage_blocks/diamond",
    absorption: 0.55,
    efficiency: 0.85,
    moderation: 1.5,
    conductivity: 3,
}

As you can see the data is there but yeah, no difference what-so-ever, however, control rods do work but no point in coolant if the coolant does nothing.

### latest.log

https://github.com/Solj1n/Latest-Log-2021-11-30/blob/main/latest.log

**Comment by RogueLogix** [comment]
Mod is working as intended. There were config default changes that make reactors run much hotter than they previously did.
