### ISSUE TITLE
[Bug]: Zinc sheet recipe missing from multiservo press

### ISSUE THREAD

**Issue by PORTB** [AllTheMods/ATM-6#2748]
### Possible Fixes

Yes

### Modpack Version

1.8.10

### What happened?

Brass sheet has a recipe in the multiservo press, and it would make sense that the zinc sheet has one too, but it doesn't 

### latest.log

https://gist.github.com/PORTB/30ef07c0caa2ddbc7f22d68f9de70696

**Comment by jeremiahwinsley** [comment]
This has been added in 1.8.15.
