### ISSUE TITLE
Can't make enriched materials in enrichment chamber (Mekanism)

### ISSUE THREAD

**Issue by razma417** [AllTheMods/ATM-6#275]
**Describe the bug**
There doesn't seem to be a working recipe for enriched materials such as enriched carbon, diamond, redstone in the pack. Trying to place any of these items in the enrichment chamber doesn't work and there's no other way to craft these materials.

**To Reproduce**
1. Create an enrichment chamber
2. Power the chamber
3. Attempt to put in any of the materials (coal, diamond, redstone, etc.) into the enrichment chamber
4. Materials cannot go in chamber, nothing happens.

**Expected behavior**
The chamber should start processing the materials, and then output the respective enriched version

**Screenshots**

**Additional context**
For ore processing the enrichment chamber is working fine, you put the ore in and get 2 dusts out. This issue breaks progression in the mekanism mod completely without being able to make refined obsidian because of it.

**Comment by NetMasterFlex** [comment]
What version of ATM6 are you running? 1.1.9b, 1.2.0, 1.2.1 or something else?

**Comment by razma417** [comment]
Sorry should have put that in, using 1.2.0 from Twitch

**Comment by razma417** [comment]
My mistake, I didn't realize there was an update and this fixed it. Closing issue.
