### ISSUE TITLE
[Crash]: Automating Potion Brewer crashed my game and now I can't play

### ISSUE THREAD

**Issue by GaborPalinkas** [AllTheMods/ATM-6#2751]
### Possible Fixes

Yes

### Modpack Version

1.8.10

### What happened?

So i wanted to automate making potions using the potion brewer from industrial foregoing and when i made the recipe for knowledge II potions and tried to put it in the crafter the game crashed and now i cant even enter my world, every time i try to load it in the game crashes with the same error message as in the crash log. I used Refined Storage for the autocrafting. 

### Crash Log

https://gist.github.com/GaborPalinkas/84059efdfea83a33f74247972bb85217

**Comment by jeremiahwinsley** [comment]
Seems like that pattern is not compatible with RS currently. One thing you can try is editing `saves/<save name>/serverconfig/refinedstorage-server.toml`, find the `[controller]` section and temporarily change capacity from `256000` to `1`. This should disable your RS system and let you get into the game and remove the pattern. 

If that doesn't work, another solution could be editing `saves/<save name>/data/refinedstorage_networks.dat` with NBTExplorer to enable redstone mode on the controller.

**Comment by GaborPalinkas** [comment]
The second solution worked thank you now I can play again.
