### ISSUE TITLE
[Bug]: Lagging after let game afk , Mahou Tsukai Fae issue?

### ISSUE THREAD

**Issue by martinegui** [AllTheMods/ATM-6#2758]
### Possible Fixes

No

### Modpack Version

1.8.10

### What happened?

Hi, I don’t know what is happening, but after let a long time afk, now when I start play, after a few minutes the game start to lagging, I notice at map a lote of mobs that I noticed that are Fae from mahou tsukai, I just start playing with this mod. My all base are chuck loaded.

any command to kill Al the Faes?

### latest.log

/

**Comment by stepsword** [comment]
/kill @e[type=mahoutsukai:fae]

And also you can make one faecake and eat it to stop them spawning (don't eat 2 or you'll reverse it). your base is probably right on a leypoint
