### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Cardel920** [AllTheMods/ATM-6#2760]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

Incomplete set of tags received from server.

![Screenshot 2021-12-03 210923](https://user-images.githubusercontent.com/95498075/144651860-b2b5c9ce-c44b-43b7-a4e8-9452ef2501d7.png)

### latest.log

https://gist.github.com/Cardel920/38c0b10d7b22878e282ebeedca597f8c

**Comment by jeremiahwinsley** [comment]
> [20:57:50] [Netty Client IO #4/INFO]: Connected to a vanilla server. Catching up missing behaviour.

you cannot connect this pack to a vanilla server, your server must be running the pack too.

**Comment by Cardel920** [comment]
but it's modpack server i download it from curseforge  website see
![Screenshot 2021-12-04 14481](https://user-images.githubusercontent.com/95498075/144708335-5a873133-e3b6-4221-9c40-39eb51f2e71b.png)

**Comment by Cardel920** [comment]
![Screenshot 2021-12-04 145141](https://user-images.githubusercontent.com/95498075/144708427-de2f93d3-ff89-4b32-aab8-ea785f892bc5.png)

**Comment by jeremiahwinsley** [comment]
Make sure you are connecting to the correct IP/port for it then, because the server listed in the logs was not running ATM6
