### ISSUE TITLE
[Bug]: Chemical Infuser Speed Upgrade

### ISSUE THREAD

**Issue by Shierufu** [AllTheMods/ATM-6#2762]
### Possible Fixes

Yes

### Modpack Version

1.8.10

### What happened?

When useing the chemical infuser the speed upgrade works up to 5 upgrades  but after taht it begins slowing down the machine to the point where at 8 upgrades it is as slow as 2

### latest.log

https://gist.github.com/Shierufu/3aff53185427bb872cd32a34919e88a3

**Comment by jeremiahwinsley** [comment]
Tested this on 1.8.14 and upgrades work properly, with 8 upgrades producing the expected 512mb per operation. Make sure you are supplying enough power, as 8 speed and 8 energy upgrades takes 204kFE/t to run at full speed.
