### ISSUE TITLE
[Crash] We've now lost two worlds, neither will boot onto the server.

### ISSUE THREAD

**Issue by comsnath** [AllTheMods/ATM-6#2763]
### Possible Fixes

Yes

### Modpack Version

1.8.10

### What happened?

After about a week on each world, the server refuses to boot into either world. It freezes up after loading the FluxNetworks.

Can provide world downloads if needed.

### Crash Log

https://gist.github.com/comsnath/7d59cf2adfb045ab0402330707e49bd7

**Comment by jeremiahwinsley** [comment]
This is fixed in 1.8.12, but as a workaround you can edit `config/polymorph-integrations.toml` and set `refinedstorage` and `appliedenergistics2` to false.

**Comment by comsnath** [comment]
We attempted a brand new server, freshly downloaded with no changes and it almost immediately crashed. Here is the new crashlog.
https://gist.github.com/comsnath/b83e8a0ceef91f4b804b1f025d6ce9c0

**Comment by jeremiahwinsley** [comment]
this is a known issue, edit `config/quark-common.toml` and set "Automatic Recipe Unlock" to false, or add https://www.curseforge.com/minecraft/mc-mods/no-recipe-advancements (only needed on server)
