### ISSUE TITLE
[Bug]:  Terra shatterer/Alf shatterer voids Unbtainium ore

### ISSUE THREAD

**Issue by LuciusV** [AllTheMods/ATM-6#2765]
### Possible Fixes

Yes

### Modpack Version

1.8.10

### What happened?

When Alf Shatterer (I assume terra shatterer as well) is in bulk-mining mode (activated by right click), it mines 5x5x2
It voids Vibranium/Unbotanium ores and if is extremely likely to happen if ore in second layer (far from player invisible behind firsh layer)

Terribly frustrating bug!

### latest.log

N/a

**Comment by jeremiahwinsley** [comment]
Looked into this and it seems to just be Botania's default behavior. Not sure we can do anything about it.
