### ISSUE TITLE
Ender Tanks from ender storage glitched

### ISSUE THREAD

**Issue by SoftGuardian** [AllTheMods/ATM-6#2770]
### Possible Fixes

Yes

### Modpack Version

1.8.12

### What happened?

When I hover my chrosshair into the EnderTank from the EnderStorage mod that they added all nearby tile entities gets xrayed

### latest.log

https://gist.github.com/SoftGuardian/d2dde846c5d876c1bfbdaa68cdb599
![2021-12-06_11 33 08](https://user-images.githubusercontent.com/73778546/144839079-560b4a8f-db3c-48a1-8750-1f118742bb38.png)
cd

**Comment by jeremiahwinsley** [comment]
Cannot reproduce this issue, do you have any additional mods installed like Optifine?

**Comment by SoftGuardian** [comment]
I had to disable fast render from optifine and it's fixed. Sorry if this is late
