### ISSUE TITLE
[Bug/Crash] Sophisticated Backpacks crash the game in single-player.

### ISSUE THREAD

**Issue by Ecluid** [AllTheMods/ATM-6#2775]
Possible Fixes
Yes

Modpack Version
1.8.11

What happened?
Sophisticated Backpacks crashing single-player, magnet upgrades, in particular, could be the issue.

Latest log
[crash-2021-12-08_07.42.06-server.txt](https://github.com/AllTheMods/ATM-6/files/7676400/crash-2021-12-08_07.42.06-server.txt)

**Comment by Aavar6802** [comment]
I have the same issue on a server. The error log is identical to the OP. The server is not able to start and continues in a crash loop.

**Comment by mjordan67** [comment]
Had same issue...Apex server tech said cause by sophisticated backpacks.

**Comment by P3pp3rF1y** [comment]
This is fixed in sophisticatedbackpacks-1.16.5-3.12.2.432 for some time already so updating to that version will fix the issue for you.

**Comment by jeremiahwinsley** [comment]
This should be fixed in 1.8.15.
