### ISSUE TITLE
[Crash]: host server

### ISSUE THREAD

**Issue by FamosoZe** [AllTheMods/ATM-6#2776]
### Possible Fixes

Yes

### Modpack Version

1.8.10

### What happened?

good morning, I'm trying to create a server by my host but when opening it crashes, but when I open it directly from my pc it works can someone help me?

### Crash Log

https://gist.github.com/FamosoZe/1647147cfce48f4cd3376e81aba8b6b6

**Comment by jeremiahwinsley** [comment]
There is no crash log in that gist.
