### ISSUE TITLE
[Crash]: Crash report in dedicated server

### ISSUE THREAD

**Issue by Koomplo** [AllTheMods/ATM-6#2777]
### Possible Fixes

Yes

### Modpack Version

1.8.12

### What happened?

I'm using the lastest version and used the server files, but when someone tries to enter in world in 1st time the server crashes

### Crash Log

https://gist.github.com/Koomplo/26c9eb40d04bff5156349447fe5fde89

**Comment by jeremiahwinsley** [comment]
This is fixed in 1.8.13.
