### ISSUE TITLE
[Crash]: RFTools Shield Projectors stopped working

### ISSUE THREAD

**Issue by fabrossmann** [AllTheMods/ATM-6#2778]
### Possible Fixes

Yes

### Modpack Version

1.8.12

### What happened?

Shield Projectors seem to be bugged and can crash the client, since the update. Reverting to the old version fixes the issue.

The crash posted in this issue is also printed to the console.

### Crash Log

https://gist.github.com/fabrossmann/b98d27164875b680ad34bdddaa22d717

Server Log:
https://gist.github.com/fabrossmann/12d26d545218b824c13b26374255807a

**Comment by Seniorendi** [comment]
I approve that message

**Comment by jeremiahwinsley** [comment]
This should be fixed in 1.8.15.
