### ISSUE TITLE
1.2.1 mine the other ore with a white and sharp light

### ISSUE THREAD

**Issue by FrostZFish** [AllTheMods/ATM-6#278]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by FrostZFish** [comment]
![Uploading image.png…]()

**Comment by FrostZFish** [comment]
[
![Uploading 1.jpg…]()
](url)

**Comment by thevortex** [comment]
?

**Comment by FrostZFish** [comment]
just mine the ore u will get that situation

**Comment by FrostZFish** [comment]
so hilarious

**Comment by Thunder-Nova** [comment]
the reason for the ? is that you left the sheet blank... and your screen shot isn't showing

**Comment by thevortex** [comment]
yes the question mark is because your issue makes absolutely no sense, please try again.

**Comment by WhitePhant0m** [comment]
No information provided in the issue.
