### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by DTATassius** [AllTheMods/ATM-6#2780]
### Possible Fixes

Yes

### Modpack Version

1.8.12

### What happened?

Launching ATM6 with Java17 makes the SolarFlux mod unable to load.

Fix by switching back to Java8.

### Crash Log

https://gist.github.com/DTATassius/d02985c4c7e4ba80a9d282a9d9a0d85a

**Comment by jeremiahwinsley** [comment]
Not a bug, Java 17 is not supported.
