### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by yesop2035** [AllTheMods/ATM-6#2781]
### What would you like to know?

Why wont it even let me connect to the server? No matter what I do or try to do it says that it cant connect to the server, or that the current version is outdated. Trying to host a server for me and my buddies and this problem keeps stumping

**Comment by jeremiahwinsley** [comment]
This sounds like network/firewall issues, which we can't diagnose/fix. You could check out vanilla server tutorials for that, all the network settings are done the same way as vanilla.
