### ISSUE TITLE
[Question]: Forbidden Arcanus Souls

### ISSUE THREAD

**Issue by legacyOTvoid24** [AllTheMods/ATM-6#2786]
### What would you like to know?

I'm currently playing ATM 6 version 1.8.9. How do you get souls from the mod? in JEI it doesn't show recipes but it shows that it is used for Dark Souls. Does the achievement line show me how to do this?

**Comment by jeremiahwinsley** [comment]
Might not be implemented yet, you'd have to ask the F&A devs.
