### ISSUE TITLE
Ice and Fire and Minecolonies

### ISSUE THREAD

**Issue by craigwatcher** [AllTheMods/ATM-6#279]
I'm hosting a server, and my friends and I have noticed a few issues. We haven't seen any Ice and Fire structures spawn, including the glacier biome. Then with Minecolonies, the villages simply won't eat anything, regardless of what kinds of food. We've been playing for over a few days and still haven't seen any ice and fire generated things. the best thing we managed was a cockatrice egg, and 3 manuscripts.

**Comment by WhitePhant0m** [comment]
Ice & Fire stuff spawns in **The Other** and update minecolonies to fix them not eating.

**Comment by craigwatcher** [comment]
Okay, so that explains Ice and fire, but what do you mean update minecolonies. I thought this has the newest version?

**Comment by Tatorah** [comment]
Hey, we are having the same issues. I read this yesterday here that Ice & Fire stuff spawns in the Other, but even there i couldnt find a single Dragon or Dragon cave. Not even other Mobs of Ice and Fire besides the Cockatrice (and we found Manuscripts).
I also checked all dimensions a Single Player world, i flew 3000 blocks in each direction underground in spectate mode. 
Do they even spawn in a Biomes O Plenty World? Did we set something wrong? Or are they just so rare that you will maybe find 1 dragon each 5000 blocks? Help would be much appreciated!

**Comment by Thunder-Nova** [comment]
@craigwatcher Minecolonies itself updated after the latest update.

@Tatorah The mobs of Ice and Fire have a whitelist for where they spawn, dragons do spawn past 5000 blocks from 0,0 which is mainly due to it's original spawn condition. But past 5000 it's shouldn't be that rare... I happened to find 3 dragons side by side once.

**Comment by Tatorah** [comment]
@Thunder-Nova I checked my whole single player world, ive been flying around in spectate in the other for like half an hr (if not longer) till the coords of 9000 8000 and i havent seen any dragon cavern nor a ice and fire mob.

Im starting to lose all hope,

**Comment by Thunder-Nova** [comment]
hmm... bizarre... the dragons usually spawn on top of the biomes which appears like dark circles spots on the minimap... and I checked the ice and fire config... and seems everything should be there.

**Comment by Thunder-Nova** [comment]
So looking into both biome and common config files the dragons should spawn.


`#How far away dangerous structures(dragon roosts, cyclops caves, etc.) must be from spawn(0, 0).
	#Range: 1 ~ 10000
	"Dangerous World Gen Dist From Spawn" = 1`

`"Generate Dragon Roost Chance" = 360`

`"Generate Dragon Roosts" = true`

Gotta check if a mod is interfering with I&F

@WhitePhant0m

**Comment by reececlarke** [comment]
Having the same issue with Minecolonies, tried giving them tons of different types of food to no avail.

**Comment by LloydSev** [comment]
The Minecolony issue is one with the Minecolony mod, and has already been fixed in a newer version that is not yet in the ATM6 pack.

https://github.com/ldtteam/minecolonies/issues/6033

**Comment by reececlarke** [comment]
> The Minecolony issue is one with the Minecolony mod, and has already been fixed in a newer version that is not yet in the ATM6 pack.
> 
> [ldtteam/minecolonies#6033](https://github.com/ldtteam/minecolonies/issues/6033)

Thanks, did not realise, will update it manually

**Comment by thevortex** [comment]
> So looking into both biome and common config files the dragons should spawn.
> 
> `#How far away dangerous structures(dragon roosts, cyclops caves, etc.) must be from spawn(0, 0). #Range: 1 ~ 10000 "Dangerous World Gen Dist From Spawn" = 1`
> 
> `"Generate Dragon Roost Chance" = 360`
> 
> `"Generate Dragon Roosts" = true`
> 
> Gotta check if a mod is interfering with I&F
> 
> I just went Single player and saw not a single mob of that mod
> 
> @WhitePhant0m
seems to be related to an update from I&F which has new configuration file alterations that our files are not compatible with, downgrade I&F to https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons/files/3077981 will resolve it, but we need to take a look at the fresh configs and compare them to ours for next update

**Comment by Tatorah** [comment]
Thank you alot @thevortex 
It actually Fixed the Issue, after 4 days of me just looking into this, it was such a simple fix in the end. Now its working properly.

(And the Dragons can spawn everywhere, not only 3000 blocks away, found 2 roosts next to the spawn not even 200 blocks away - people kept telling me im not searching far enough)

**Comment by minister61** [comment]
I am having the same issue but cannot use the the old file as its for 1.15 and I'm using 1.16 so it just crashes the game, is there any news when the new config for I&F will be fixed?

**Comment by jeremiahwinsley** [comment]
Fixed in 1.3.9.
