### ISSUE TITLE
[Bug]: Default Recipes missing, like for oak planks

### ISSUE THREAD

**Issue by BlackSkill88** [AllTheMods/ATM-6#2791]
### Possible Fixes

Yes

### Modpack Version

1.8.13

### What happened?

On the newest version are no recipes for oak planks and so on, use the older version and it works

### latest.log

a

**Comment by Ner0me** [comment]
Most recipes missing with newest release

**Comment by Ner0me** [comment]
Error is already fixed with latest release (30 min ago)

**Comment by jeremiahwinsley** [comment]
Fixed in 1.8.14.
