### ISSUE TITLE
[Crash]: refined storage pattern crashing game

### ISSUE THREAD

**Issue by qazzy23** [AllTheMods/ATM-6#2797]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

ATM6 crashes when rendering a not gate in refined storage crafter and in pattern form in an inventory.

### Crash Log

<script src="https://gist.github.com/qazzy23/ebd6df3ffdbaa5e7c4877f84cfea1816.js"></script>

**Comment by Solj1n** [comment]
I get this specifically with ProjectRedCore's comparator.

**Comment by jeremiahwinsley** [comment]
This is fixed in 1.8.14.
