### ISSUE TITLE
[Bug]: Networking Cable can't be crafted 

### ISSUE THREAD

**Issue by Blackspack** [AllTheMods/ATM-6#2799]
### Possible Fixes

No

### Modpack Version

1.8.14

### What happened?

I can't craft (switch the recipes to) Networking Cable from CC:Tweaked anymore in the ME Crafting Terminal from AE2.
It was possible in 1.8.10 but now switch button don't appear. I tried on nomal workbench and it work. 

### latest.log

https://gist.github.com/Blackspack/3a532f7d0fc48bc198a263002b637a81

**Comment by jeremiahwinsley** [comment]
Recipe has been changed in 1.8.15 to fix conflict.
