### ISSUE TITLE
[1.2.1 Server] Incorrect Data Check?

### ISSUE THREAD

**Issue by DaveJK** [AllTheMods/ATM-6#280]
Me and a Friend are trying to connect to a specific server and either get kicked back to the server list with error while loading, or disconnect several minutes later back to the server list with the error attached in image:  https://imgur.com/a/DogkQ7a

We can connect to a lot of other servers with no issue. But the server admin has restarted the server several times, and completely reinstalled the modpack too but still has issues. I also have a log from my game if that will help with any possible solutions to the issue? https://pastebin.com/xSXULdqb

**Comment by Scryrz** [comment]
To add to this - we've received a number of different errors, including:

- io.netty.handler.codec.DecoderException: java.util.zip.DataFormatException: incorrect header check
- io.netty.handler.codec.DecoderException: java.util.zip.DataFormatException: incorrect data check
- io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: unable to fit 3120430 into 3
- io.netty.handler.codec.DecoderException: Badly compressed packet - size of 34 is below server threshold of 256
- io.netty.handler.codec.DecoderException: Badly compressed packet - size of 47252889 is larger than protocol maximum of 16777216

As of right now, it seems like disconnects are inconsistent. After the server owner did a complete reset (fresh download of everything), it was happening approximately every 5 minutes for me, but not for Dave. Today, I'm not seeing any issues so far, but Dave can't join without getting one of the aforementioned errors.

We've tried 5 or so other servers and haven't had this issue, which leads me to believe that it isn't at all clientside. Additionally, we've both tried connecting to the server via ethernet, wifi, and at one point just to test, even phone hotspot.

According to the server owner, it's not being hosted by a company, it's being hosted a dedicated machine on his home network. He's updated Java, downloaded a fresh server pack from Curseforge, restarted his home network and server machine multiple times.

**Comment by ViRb3** [comment]
All of these errors sound like something is corrupting the communication between you and the server. The log you shared doesn't show anything useful, at least to me, which makes me believe that the error is not in Minecraft, but the connection between you and the server.

**Comment by DaveJK** [comment]
The server owner updated the network adapter for the server and everything seems fine for now. Thanks
