### ISSUE TITLE
[Bug]: Mystical Agriculture Essence shown as cratable but not functional with create mod

### ISSUE THREAD

**Issue by lyssar** [AllTheMods/ATM-6#2802]
### Possible Fixes

Yes

### Modpack Version

1.8.14

### What happened?

Hey,
I tried to craft clay with essences (2 water essence, 2 dirt essence). The JEI shows that it should work together with creates mechanical crafters but it doesn't. It spits out the 4 essences again instead of the clay. I guess this can't work with create because it just can spit out single items or at least all items from create itself are always single outputs.
Would be good if you can remove not craftable recipes from the create list or of course correct me if I am wrong.

Kind regards

### latest.log

https://gist.github.com/lyssar/9691872e9f56b1346b05d0109a4efb93

**Comment by jeremiahwinsley** [comment]
Tested this in 1.8.15 and it successfully crafted the clay with a 3x3 grid of crafters.
