### ISSUE TITLE
[Bug]: Pneumaticcraft Programmer doesn't accept drones

### ISSUE THREAD

**Issue by bobothehobo2** [AllTheMods/ATM-6#2803]
### Possible Fixes

Yes

### Modpack Version

1.8.12

### What happened?

When you try to insert a drone do program it, the slot won't accept it.  I've tried with all types of drones, all chest positions and in inventory puzzle pieces, and even tried in creative and multiple programmers.  The Name field also seems to not work as well.  Loving the pack guys thanks for all your hard work!

![image](https://user-images.githubusercontent.com/25537033/146016276-2cd13f97-0c8f-4aaf-86b8-de5c209174aa.png)

### latest.log

https://gist.github.com/bobothehobo2/3375ec022db1267845a997c5c8d66995

**Comment by jeremiahwinsley** [comment]
Tested on 1.8.14 and it seems to work ok here. Shouldn't be any major differences, but see if that fixes it?
![2021-12-14_21 38 50](https://user-images.githubusercontent.com/7946299/146113080-7026fb95-718f-4436-b9a1-3ff7460ef54f.png)

**Comment by bobothehobo2** [comment]
hmm ok I'll try to get it in today!

**Comment by bobothehobo2** [comment]
I did the update and I still can't insert anything.
