### ISSUE TITLE
[Question]: Potion Charms no longer indestructible

### ISSUE THREAD

**Issue by Jazriel** [AllTheMods/ATM-6#2806]
### What would you like to know?

Is the removal of the recipe to make potion charms indestructible a desired change of a bug?
(Potion charm +Eternal Stella)
Also they only allow up to unbreaking 3 which makes me think it was a bug introduced when making them non repairable

**Comment by jeremiahwinsley** [comment]
This was mentioned in the changelog for 1.8.11, it's a change from Apotheosis. You can still apply the enchant with Pedestals using the anvil upgrade.
