### ISSUE TITLE
[1.2.1] Server crash

### ISSUE THREAD

**Issue by 4lex0017** [AllTheMods/ATM-6#281]
Hi,
have been playing for a day atm6 server crashed regular.
some issue with moreRed?

commoble.morered.MoreRed.onPlayerStartWatchingChunk(MoreRed.java:222)

Logs inc.

[2020-11-07-1.log](https://github.com/AllTheMods/ATM-6/files/5505551/2020-11-07-1.log)
[debug-1.log](https://github.com/AllTheMods/ATM-6/files/5505552/debug-1.log)

**Comment by ViRb3** [comment]
Server is overloaded from bug in MoreRed mod, fixed in new version. #259
