### ISSUE TITLE
[Crash]: Crash on opening inventory, after killing a player

### ISSUE THREAD

**Issue by pokermanx** [AllTheMods/ATM-6#2812]
### Possible Fixes

Yes

### Modpack Version

1.8.14

### What happened?

Crash on opening inventory, after killing a player

### Crash Log

https://pastebin.com/iyT7Hf4F

**Comment by jeremiahwinsley** [comment]
Looks like it dropped a mob soul for a player, which shouldn't be happening. That can be blacklisted in the config.

**Comment by jeremiahwinsley** [comment]
Player souls have been added to the blacklist in 1.8.16.
