### ISSUE TITLE
[Crash]: Server crash with "waiting server"

### ISSUE THREAD

**Issue by popotte13** [AllTheMods/ATM-6#2814]
### Possible Fixes

Yes

### Modpack Version

1.8.15

### What happened?

there are many "waiting server" when i play and the server crash. I don't know why because i play once 15-20hour and i don't have many machine. I don't know what to do :( (sorry for my english but i'm french and i don't speak english very well :( )

ps: i start the game with allthemod 1.8.9 and after many hours, the game crash. I decide to change the version

### Crash Log

https://gist.github.com/popotte13/ab832e810865d0d5ff33336417e5d4b5

**Comment by jeremiahwinsley** [comment]
Looks like it's taking too long to save the world. If you have an SSD you could move the game to that, otherwise you can edit `server.properties` and increase `max-tick-time` so that it has more time to finish saving.
