### ISSUE TITLE
[Crash]: Crashes while starting the game

### ISSUE THREAD

**Issue by Jurand20012** [AllTheMods/ATM-6#2816]
### Possible Fixes

No

### Modpack Version

1.8.15

### What happened?

i just installed the pack wia MultiMC, and then hit start, and after a few minutes it randomly crashed due to a few of the mods, 
![image](https://user-images.githubusercontent.com/47210487/146684561-e1f55d2e-c7e0-44c9-8bee-2e231b834393.png)

### Crash Log

https://gist.github.com/Jurand20012/9a5b4908f3c7cf5e4a7a2546f895ca90

**Comment by radiomike** [comment]
You are using java 17. that's not compatible with this pack. Java 8 or 11 are recommended - see https://github.com/AllTheMods/ATM-6/wiki/Java-Versions for some download links
