### ISSUE TITLE
[Crash]: Server Files Missing Mods

### ISSUE THREAD

**Issue by ComradeCyka** [AllTheMods/ATM-6#2817]
### Possible Fixes

Yes

### Modpack Version

1.8.15

### What happened?

Downloaded extracted and ran the server installer, after it downloads files and i accept eula and try to actually boot the server, I receive and error due to dpanvil and mcjtylib not actually being installed.
I was able to fix this by simply copying over the above mods from my single player instance and moving them over to the server's mods folder.

### Crash Log

https://gist.github.com/ComradeCyka/1e017d7495fbc48914fc60e6b6bc93a3

**Comment by FallenPumpking** [comment]
I am also having this issue but cannot fix it with the method of transferring the mods folder

**Comment by jeremiahwinsley** [comment]
This was likely due to Curseforge instability at the time, as the pack downloads fine in testing.
