### ISSUE TITLE
[Bug]: Luminous Crafting Table and Startmetal Transmutation Not Working

### ISSUE THREAD

**Issue by wizzbangwa** [AllTheMods/ATM-6#2819]
### Possible Fixes

Yes

### Modpack Version

1.8.15

### What happened?

Astral Sorcery Luminuous Crafting Table and Startmetal transmutations are not working as documented in the Astral Tome.  

1. Find a crystal in a temple.
2. Expose the crystal to the sky.
3. Place a crafting table anywhere underneath the crystal.
4. Particles appear between the crystal and the crafting table, the crafting table never transmutes to a Luminous crafting table.
5. Place iron ore anywhere under the crystal.  Nothing happens.
6. Try to use the resonating wand to link the crystal to the iron ore/crafting table, nothing.
7. Do all this at night, no transmutation.

### latest.log

https://gist.github.com/wizzbangwa/e18c6d2783878574d87efefc5be31fc5

**Comment by jeremiahwinsley** [comment]
Tested this in 1.8.15, both day and night.
Exposed crystal to sky, placed vanilla crafting table underneath, and it converted to the astral table.
Used a linking tool to link the crystal to iron ore, the ore successfully converted to starmetal.

Seems to be working correctly. Did you add/remove any mods that could be affecting it?

**Comment by Aavar6802** [comment]
I can also confirm that I have tested this in 1.8.15 and it works as intended.

**Comment by olivia-mativi** [comment]
Confirming on my server that all players using astral sorcery progressed as intended.

For the crafting table, it converts fine. For the ore, you _need_ to use the linking tool. Resonating wand does not link AS blocks, as documented.
