### ISSUE TITLE
Trees not growing even when chunks are force loaded with FTB Chunks?

### ISSUE THREAD

**Issue by Revvilo** [AllTheMods/ATM-6#282]
I moved my "Orchard Tree" farm away from my draw distance due to that stupid problem of chunk redraws hitching the game and have found that the trees don't grow if I'm not standing there.

What's up with this?

The picture is what it looks like after I've been standing there for a few minutes, but if I leave and come back once the items have stopped flowing, the farm is entirely saplings, and will immediately grow tree after tree.

<img src="https://user-images.githubusercontent.com/13816212/98453189-509d0200-21bb-11eb-92dc-6482bb3cb197.png" width=500px>

**Comment by Revvilo** [comment]
I've added an automatic system for composting the excess saplings into bonemeal and feeding it into an IForegoing fertilizer and that seems to have taken up the slack. I'm not producing enough bonemeal to run the farm purely off of the fertilizer alone... but the farm has continued running overnight... so... something is working. Maybe the fertilizer just gives the blocks the updates they need to grow? I have no idea.
The issue still stands, though. Without the IF fertilizer, they don't grow.

**Comment by DeathOfTime** [comment]
I've heard that stuff won't grow without the player nearby. i can't find anything to back that up. i did find that my vanilla farms weren't growing without me nearby if i wasn't using anything to speed up their growth.

**Comment by Revvilo** [comment]
Guess that seems to be how it works now... It always just used to be keeping the chunks loaded, even in ATM5.
Would be nice to know what makes that change tho.

**Comment by Epicbaconflips** [comment]
I am also experiencing my crops not growing in claimed and loaded chunks when I exit the server. I have to be on and nearby for my sugar cane, vanilla crops, and PAM harvest crops to grow. I'm testing my tree farm now to see if it's in the same boat.

**Comment by WhitePhant0m** [comment]
FTB Chunks doesn't do random ticks, at least in the version we have, I believe it has had an update to include random ticks, you can try updating to that manually. I might be wrong tho.

**Comment by Revvilo** [comment]
Perfect! That's what I had suspected. Cheers for the info :)
