### ISSUE TITLE
[Crash]: On load 3 errors have occured during loading on installation

### ISSUE THREAD

**Issue by zoratoune** [AllTheMods/ATM-6#2820]
### Possible Fixes

Yes

### Modpack Version

1.8.15

### What happened?

I have just installed the version through zip, tried a fresh install twice. These are the logs and image of the load.
So it loads until it doesn't anymore. Message is on the screenshot
![image_377](https://user-images.githubusercontent.com/3108919/146764734-700181c7-63f6-46b7-bc63-4973daba3c94.png)
[latest.log](https://github.com/AllTheMods/ATM-6/files/7745079/latest.log)
Crash log : https://gist.github.com/zoratoune/a37add5d7218e3708a110dd1b2a38547

### Crash Log

https://gist.github.com/zoratoune/a37add5d7218e3708a110dd1b2a38547

**Comment by zoratoune** [comment]
![image_378](https://user-images.githubusercontent.com/3108919/146765296-2e26af9b-7c54-41e3-9df8-2e3c906c617c.png)
Weird graphical glitch while loading before the crashes

**Comment by jeremiahwinsley** [comment]
Java 17 is not supported, use Java 8-15.
