### ISSUE TITLE
Latency in singleplayer

### ISSUE THREAD

**Issue by FireSmashe** [AllTheMods/ATM-6#2821]
Im lagging in singleplayer, like there is lags when i break blocks i have to break 5 time the block to break it for real, items take a while to pickup, bees are slow and machines are slow and thats extremly annoying.

**Comment by jeremiahwinsley** [comment]
That sounds like TPS lag, usually due to something built incorrectly or large amounts of items on the ground somewhere. You can track down the cause with Observable or Spark profiling, both mods are included in the pack.
