### ISSUE TITLE
[Bug]: Silents Gear tools incorrect durability bar

### ISSUE THREAD

**Issue by Etroll780** [AllTheMods/ATM-6#2823]
### Possible Fixes

Yes

### Modpack Version

1.8.15

### What happened?

![image](https://user-images.githubusercontent.com/6495854/146839221-f4dc15e4-8550-46c6-89b0-d09c88b502e0.png)

this appears to affect all tools

### latest.log

na

**Comment by jeremiahwinsley** [comment]
Tested this on 1.8.15 and the durability bar works fine with a standard iron pick converted into a silent gear tool. Do you have any more details on when this happens, or how you're testing it?
