### ISSUE TITLE
[Crash]: java.lang.ExceptionInInitializerError: null

### ISSUE THREAD

**Issue by SnazyAlly** [AllTheMods/ATM-6#2824]
### Possible Fixes

Yes

### Modpack Version

1.8.15

### What happened?

I am trying to set up a multiplayer ATM6 server. I have no idea how to fix the current issue so any help would be appreciated. 

### Crash Log

https://gist.github.com/SnazyAlly/89a1a8e1cde2046a05dae9721e96447c#file-crash-2021-12-21_17-04-10-client-txt

**Comment by jeremiahwinsley** [comment]
Looks like Forbidden & Arcanus crashing while trying to render something, but I am not able to replicate it locally. Have you done anything with progression from that mod that might have triggered that?

**Comment by SnazyAlly** [comment]
After crashing once, I made sure to completely re-download the server and it crashed again with the exact same error. I will try again but I doubt that is the issue unless I am misunderstanding you. I have never successfully opened this world and I tried my best not to touch the files so I don't see how I'd progress in it.

**Comment by jeremiahwinsley** [comment]
Is the server crashing also, or just the client? Can you post the latest.log from the client?

**Comment by jeremiahwinsley** [comment]
Just noticed you have Optifine, can you try without optifine?

**Comment by SnazyAlly** [comment]
Ended up completely deleting ATM6 and redownloading it (w/o optifine). The server is now working, thank you!
