### ISSUE TITLE
[Crash]: Server Crash

### ISSUE THREAD

**Issue by OmAn94** [AllTheMods/ATM-6#2828]
### Possible Fixes

Yes

### Modpack Version

1.8.15

### What happened?

[crash-2021-12-23_23.33.09-fml.txt](https://github.com/AllTheMods/ATM-6/files/7771664/crash-2021-12-23_23.33.09-fml.txt)
Need help, I installed both versions from forge.
I want to play this in server.

### Crash Log

https://gist.github.com/OmAn94/22f3d32285c0e8c1c264c420d8c4258c

**Comment by Jappy007** [comment]
Use java 11 or 8 instead of 17
