### ISSUE TITLE
[Feature]: Increase Thermal Series Dynamo Output

### ISSUE THREAD

**Issue by ricepoly262** [AllTheMods/ATM-6#2829]
### Feature Details

Currently, the base power for all Thermal dynamos is 40 RF/T, and can be increased to 200 RF/t (At 66% fuel efficiency) using 4 Auxiliary Reaction Chamber upgrades.

I suggest increasing the base RF of some, such as the Lapidary, Numismatic, and Disenchantment, to 200, thus increasing the max RF/t output to 1000

My reasoning for this suggestion is that there is no reason to use any dynamo outside of the Stirling one early on as there are directly better sources of power, such as those from Powah, RFTools Coal Generator, and by the time you can really afford to use a Lapidary or Disenchantment, 200rf/t is outshined by a Mekanism Wind Generator, as it is completely passive and requires no fuel

**Comment by jeremiahwinsley** [comment]
You may want to try the Integral Components.
