### ISSUE TITLE
Vanilla MC launching from the FML loading screen before FML loading screen is done

### ISSUE THREAD

**Issue by kesin7** [AllTheMods/ATM-6#283]
Hello,

I launch from the twitch launcher the ALL THE MOD 6 mod pack, and it opens the FML loading screen. Before completion vanilla MC is launched and the FML loading screen stays open and moves very slowly and seems to never finish. When trying to connect to the server says that it requires forge. I am a little lost.

**Comment by Revvilo** [comment]
Have you tried closing vanilla MC and waiting for the modpack to finish loading?
Does the memory counter continue to count on the forge loading screen? If it does, that means the modpack is still loading.

**Comment by SamsasTraeumer** [comment]
Same Problem here, Closing Vanilla MC forces Closing the FML too.
Happens also to manual created 1.6.3 Modpack with the mods from ATM6 1.6.3

**Comment by ViRb3** [comment]
Try using [MultiMC](https://multimc.org/). There's been a lot of problems reported with Twitch Launcher.
