### ISSUE TITLE
[Bug]: Polymorph broken with refined storage

### ISSUE THREAD

**Issue by PORTB** [AllTheMods/ATM-6#2835]
### Possible Fixes

Yes

### Modpack Version

1.8.15

### What happened?

I'm not sure if to report this on this repo, polymorph repo, or rs repo, but the recpie cycle button no longer appears on the pattern grid (it did previously) but still works fine on the normal crafting grid.
E.g. with rainbow honey blocks:
pattern grid
![image](https://user-images.githubusercontent.com/34615701/147381359-9a9778a0-f7f7-4c72-8d0e-956b2ba7b12c.png)
normal crafting grid
![image](https://user-images.githubusercontent.com/34615701/147381376-031e9dac-5dc4-480c-97db-1e5a877a4e24.png)

### latest.log

https://gist.github.com/PORTB/30ef07c0caa2ddbc7f22d68f9de70696

**Comment by jeremiahwinsley** [comment]
That's the expected behavior in this version. There is a newer version that supports patterns, but it causes too much lag on servers, so we had to roll back to the old version.
