### ISSUE TITLE
[Question]: Is the inability to compress Glass intended? (No recipe for regular glass to 1x compressed)

### ISSUE THREAD

**Issue by timeconsumer06** [AllTheMods/ATM-6#2836]
### What would you like to know?

There are crafting recipes for compressed glass all the way up to 9x, but there is no way to get to 1x compressed glass from standard glass. From what I have seen, there is only a way to get to compressed glass by smelting a stack of compressed sand. Once you have that compressed glass, than any of the other multiples is possible, but its getting to that 1x that is necessary. 

Is this intended? Are we not supposed to be able to compress glass, and the recipes are only there so that if compressed sand is smelted than it has a possible output?

**Comment by jeremiahwinsley** [comment]
Fixed in 1.8.16.
