### ISSUE TITLE
[Bug]: universal crafting grid causing dupes and disconnects

### ISSUE THREAD

**Issue by Xplodin** [AllTheMods/ATM-6#2837]
### Possible Fixes

Yes

### Modpack Version

1.8.15

### What happened?

universal crafting grid doesnt show any crafting grid and lags heavily. Plus items dupe when its bugging out

### latest.log

https://gist.github.com/Xplodin/70359ab83169e820819f08795add2d8b

**Comment by SoftGuardian** [comment]
Since it's new it's a complete mess he said that he's rewriting the mod too make it stable

**Comment by KamiAso** [comment]
AFAIK the duped items are temporary and just a visual bug. Also I have found out that every time you access the universial grid it causes a massive increase in ping (from 2000ms~18000ms from my experience).

**Comment by Xplodin** [comment]
Yeah the ping spikes are also nuts. I thought it was me but wasnt sure

**Comment by jeremiahwinsley** [comment]
The mod has been updated in 1.8.21, this should fix these issues.
