### ISSUE TITLE
[Feature]: Mekanism quest tab in FTB Quests

### ISSUE THREAD

**Issue by omarfakhreddine** [AllTheMods/ATM-6#2838]
### Feature Details

I believe I've seen Mekanism quests in youtube videos of older versions of this pack or sometime else. However in the most recent version of this pack on curseforge, I am not seeing the Mekanism quests. Is there a way to add that back? How can I add it myself to the server I'm running for my friends?

**Comment by jeremiahwinsley** [comment]
We don't have a Mekanism chapter for this pack. However, we do accept contributions if you or someone else wanted to write one.
