### ISSUE TITLE
[Crash]: Crash when checking traits on Unobtainium and Vibranium Bees in the BeePedia

### ISSUE THREAD

**Issue by Afriqvist** [AllTheMods/ATM-6#2839]
### Possible Fixes

Yes

### Modpack Version

1.8.15

### What happened?

I opened the BeePedia and clicked on the traits tab on both of Vibranium and Unobtainium bees, multiple times, and crashed everytime.

### Crash Log

https://gist.github.com/Afriqvist/c2b9ca85b51ab87eb37fd9ad37d49d4f

**Comment by jeremiahwinsley** [comment]
Fixed in 1.8.16.
