### ISSUE TITLE
[Crash]: Inscribing a Blood Gem

### ISSUE THREAD

**Issue by Rainmaykr** [AllTheMods/ATM-6#2845]
### Possible Fixes

Yes

### Modpack Version

1.8.15

### What happened?

Attempting to inscribe the Blood Gem with a Blood Scroll (Blood Magic / Ars Noveau crossover) crashes server.

Tried inscribing 2 different ways. Using a Blood Scroll in Main hand and Blood Gem in off-hand. Also tried using a Blood Scroll on the Blood Gem with Scribes Table. Both resulted in a crash.

### Crash Log

https://gist.github.com/Rainmaykr/9c3c0250c7c63897b04a830dfc15a732

**Comment by jeremiahwinsley** [comment]
Might be fixed in 1.8.16 with the Tome of Blood update.
