### ISSUE TITLE
[Crash]: Using the build tool or supply camps from Minecolonies/Structurize crashes the client.

### ISSUE THREAD

**Issue by Fishreeee** [AllTheMods/ATM-6#2847]
### Possible Fixes

Yes

### Modpack Version

1.8.15

### What happened?

Modpack Version: **1.8.16**  (the drop down box doesn't list 16)

Using the build tool or supply camps from Minecolonies/Structurize crashes the client.  I've tested it both on a server and in singleplayer repeatedly and crashed every single time. 

No extra mods added.

### Crash Log

https://gist.github.com/Fishreeee/ea74aa0c167fec8b88a5219d35a164c9

**Comment by MarxminSD** [comment]
Can double confirm - recently updated two ATM6 servers to 1.8.16, and players have been able to replicate the issue in single and multiplayer.

**Comment by zenudas** [comment]
It seems Observable-0.2.0 causing the issue. Tested downgrading it back to 0.1.3 and build tool resumes usable in single player.

**Comment by DarTxeez** [comment]
I am having the same problem in both multiplayer and Single player.

**Comment by Fishreeee** [comment]
Observable has released a new update (0.2.1) to address an issue with Doubleslabs mod and that fixes the issue in Minecolonies as well.

Can confirm updating observable has fixed my issue.  Updating Observable to 0.2.1 client-side will still allow you to connect to a server with 0.2.0 as well.

**Comment by hurr1k4ne** [comment]
I can confirm the crash with a complete fresh install of client and server with 1.8.16 today.
Client crashes when using the wand or placing the supply hut.
Server continues.

**Comment by BuildingwithBob** [comment]
This is happening on my server as well.

**Comment by radiomike** [comment]
Update `observable` to `0.2.1-forge `

**Comment by jeremiahwinsley** [comment]
Fixed in 1.8.17.
