### ISSUE TITLE
[Bug]: Woot Ingredient Importer not importing items

### ISSUE THREAD

**Issue by jason96chung** [AllTheMods/ATM-6#2848]
### Possible Fixes

Yes

### Modpack Version

1.8.10

### What happened?

I have a tier 5 (Magister) woot multiblock and I have an Ender Dragon Mob Controller. I need to import in End Crystals which I have placed in a chest adjacent to the Ingredient Importer block. However this does not consume the End Crystals and does not produce any loot

### latest.log

no idea how this works, sorry

**Comment by jeremiahwinsley** [comment]
Tested in 1.8.17 and it works as intended. Make sure you are supplying Conatus fluid, as it will not import items if it doesn't have everything it needs to run.
