### ISSUE TITLE
Screen going white when using a tool on blocks like cobble

### ISSUE THREAD

**Issue by maize20** [AllTheMods/ATM-6#285]
Everytime im mining a block with any kind of pickaxe or any other tool a white screen thats showing the block break. So for example ill be mining stone with a stone pickaxe and a white screen will cover the screen with cracks going into it as its breaking. As soon as the block it goes away. Anyone know how to fix that?

**Comment by DeathOfTime** [comment]
i seen that while i was using internal shaders in optifine. not sure if its related

**Comment by maize20** [comment]
so is their a way i can fix that? without taking the shaders off?

**Comment by seanimusprime** [comment]
> so is their a way i can fix that? without taking the shaders off?

Open "cofh_core-client.toml" in your config folder and set "Render Area Effect Block Breaking" to false
