### ISSUE TITLE
Redstone P2P Tunnel Quest can't be completed

### ISSUE THREAD

**Issue by ShiningTrapez** [AllTheMods/ATM-6#2851]
In the AE2 section, there is a quest for the variants of the P2P tunnel, however, these cannot be crafted directly and are instead configured in world by [clicking different items](https://appliedenergistics.github.io/features/me-network/misc/p2p-tunnel) on the tunnel. They cannot be picked up, with silk touch or otherwise, as the tunnel reverts to the base ME P2P tunnel at that point; thus the quest cannot be completed.

**Comment by jeremiahwinsley** [comment]
Quest has been removed in 1.8.17.
