### ISSUE TITLE
[Bug]: Hostile Neural Networks Self Aware Prediction

### ISSUE THREAD

**Issue by LilDyl8** [AllTheMods/ATM-6#2852]
### Possible Fixes

Yes

### Modpack Version

1.8.16

### What happened?

Levelled up my Spider Model to self aware which should be a 99.5% chance of dropping a prediction each cycle, however it hasn't dropped one and i havent had one drop since being on this tier. Previous levels I was getting frequent drops.

### latest.log

https://gist.github.com/

**Comment by jeremiahwinsley** [comment]
Tested on 1.8.17 and this seems to work correctly.
