### ISSUE TITLE
[Question]: Any mods for better performance?

### ISSUE THREAD

**Issue by bulkasmakom1** [AllTheMods/ATM-6#2853]
Any mods for better performance?

I have this issue when playing almost any modpack and even vanilla when i have 1-4 fps. It is because of my graphics card and i used optifine to fix this problem (i was turning off all animations). 
I tried it with modpack aswell, but when i was loading to server client crashed. 
So do you know any other mods which can help with that?

**Comment by bobothehobo2** [comment]
you could try magnesium.  Or the trusty (not really) optiforge + optifine
