### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by BuildingwithBob** [AllTheMods/ATM-6#2854]
### Possible Fixes

Yes

### Modpack Version

1.8.16

### What happened?

i crash every time i use the build wand for Minecolanes 

### Crash Log

https://gist.github.com/BuildingwithBob/b76ac99cec7d5e251c0305c5be858364

**Comment by hurr1k4ne** [comment]
duplicate with:
#2847

**Comment by jeremiahwinsley** [comment]
Fixed in 1.8.17.
