### ISSUE TITLE
[Crash]: ATM6 Client crashes when placing cardboard box over Spawner

### ISSUE THREAD

**Issue by jblankenship30** [AllTheMods/ATM-6#2856]
### Possible Fixes

Yes

### Modpack Version

1.8.16

### What happened?

While in the nether I tried to place a cardboard box over a blaze spawner and at that moment the client crashed.
The ATM6 server still runs its just the client that crashes. Multiple people on my server report the same crash when they try the same thing.

### Crash Log

https://gist.github.com/jblankenship30/35fc8a737e88aee660192dc70a25bcc3

**Comment by patitow** [comment]
Having the same issue here. Exactly as described.

**Comment by radiomike** [comment]
It's a known issue. For now I'd suggest that you don't use cardboard boxes. There's a few other options available in the pack, like bag of yurting and even a silk touch pickaxe.

**Comment by patitow** [comment]
Thanks for the suggestion, I appreciate it.
