### ISSUE TITLE
[Question]: Valid Apiary Blocks

### ISSUE THREAD

**Issue by bobothehobo2** [AllTheMods/ATM-6#2858]
### What would you like to know?

So I was trying to build an apiary and found really nothing that had the tag so I looked in the kubejs/server_scripts/tags.js and found

`  e.add('resourcefulbees:valid_apiary', ['glassential:glass_dark_ethereal', 'glassential:glass_dark_ethereal_reverse', 'glassential:glass_ethereal', 'glassential:glass_ethereal_reverse', 'glassential:glass_ghostly'])`

I'm just curious if this was intentional and if so, why only glassential?  I'm on the latest iteration(.16) of the pack but I see the same in .15 & .14.  Thanks for your hard work!

**Comment by jeremiahwinsley** [comment]
Resourceful Bees doesn't use the tag anymore - instead, it allows any solid block.

**Comment by bobothehobo2** [comment]
Ok I played around more and figured out what was going on.  Even though you can still build it, the validation boxes are red unless you have those blocks in it. Kind of a low priority bug for them.  Thanks!
