### ISSUE TITLE
Modular router isn't working in claimed chunks

### ISSUE THREAD

**Issue by cornholio84** [AllTheMods/ATM-6#286]
Usage in private server

Modular router isn't working in claimed chunks
It is invited as an ally, still refuses to turn on
Other mods requiring invite works though

Works as expected outside of claimed chunks

**Comment by DeathOfTime** [comment]
This is fixed as of ATM6 1.3.4c

**Comment by ChadNedzlek** [comment]
I'm using version 1.6.14, and this behavior seems to be back?

**Comment by ChadNedzlek** [comment]
Nevermind, figured out how to "invite" them. :-D
