### ISSUE TITLE
[Question]: Time in a Bottle doesn't work on any crops.

### ISSUE THREAD

**Issue by DjNielth** [AllTheMods/ATM-6#2861]
### What would you like to know?

Hello guys,

the item "Time in a Bottle" doesn't work on crops in the modpack. Neither vanilla nor modded crops. I tried it on different states of growth, different crops, different soils and so on. 
Is there an option that prohibits the usage on crops?

Thanks for any answer!

**Comment by radiomike** [comment]
That's correct. Time in a bottle doesn't increase crop growth ticks.

There are several other methods in the pack to accelerate crop growth.
