### ISSUE TITLE
[Crash]: placing minecolonies supply camp or ship will crash client

### ISSUE THREAD

**Issue by TheMrCaveman** [AllTheMods/ATM-6#2862]
### Possible Fixes

No

### Modpack Version

1.8.16

### What happened?

try to place a supply camp or ship from minecolonies and client crashes.

https://pastebin.com/YJQ3be0b

### Crash Log

https://pastebin.com/YJQ3be0b

**Comment by TheMrCaveman** [comment]
caused by doubleslab mod
https://github.com/tasgon/observable/issues/23

**Comment by radiomike** [comment]
Duplicate of #2847

**Comment by jeremiahwinsley** [comment]
Fixed in 1.8.17.
