### ISSUE TITLE
[Bug]: "mismatched mod channel list" after update

### ISSUE THREAD

**Issue by Hodel1** [AllTheMods/ATM-6#2864]
### Possible Fixes

No

### Modpack Version

1.8.16

### What happened?

After updating from 1.8.14 to 1.8.16 i got client side an error by connecting: "mismatched mod channel list".

I don't know, but i think it's a serverside problem, look at log snippet on gist: https://gist.github.com/Hodel1/fb5369d0f5aa43788c9f7416a4904814

### latest.log

https://gist.github.com/Hodel1/fb5369d0f5aa43788c9f7416a4904814

**Comment by radiomike** [comment]
Which launcher are you using?

**Comment by Hodel1** [comment]
Solved.

The problem was the "simple" Update/Install tool ... That has skipped 2 mods by download them, so the server and client had a mismatch of mods ... 🤮 

Restarted the installer again for 2 times - now it has worked.
