### ISSUE TITLE
[Bug]: Duplication with Compacting Drawers

### ISSUE THREAD

**Issue by PierFelix** [AllTheMods/ATM-6#2865]
### Possible Fixes

Yes

### Modpack Version

1.8.16

### What happened?

While trying to add Ender Pearl Fragments, from Fobidden & Arcanus, to a Compacting Drawer thinking it would compact into Enderpearls, the Ender Pearl Fragment took the top slot and the Ender Pearl took the Nugget slot. This made the amount of Ender Pearls in the Compacting Drawer be equal to the amount of Ender Pearl Fragments (whcih would normally be 4 fragments for 1 pearl). 
When putting in more fragments it will create a new ender pearl for each fragment, while you are able to craft the ender pearls back into 4 fragments with your crafting grid. 

The Compacting Drawer does not always recognize the fragments and you will have to try putting it in a couple of times to have the Ender Pearl show up. 

### latest.log

https://gist.github.com/PierFelix/839e2e9d1d27d91ef5de2c7c56f4e793

**Comment by PierFelix** [comment]
I had this dupplication bug also appear with Diamonds and the Diamond Shards from Silent Gear, but I have no way to reproduce it...

**Comment by PierFelix** [comment]
New bug most likely linked to the same bug: 
Being able to transform items into a different item. 

Step 1: lock the drawer
![image](https://user-images.githubusercontent.com/97235091/149781375-2462ae17-1fc5-459e-99f6-fefd1f0c862d.png)

Step 2: add your item you want to transform it in (I used a diamond as example, easiest is to use an item that can fill 3 slots in the drawer)
![image](https://user-images.githubusercontent.com/97235091/149781609-44e9ee6b-b108-48a5-8d78-0e69efa93911.png)

Step 3: remove the item while it is locked 
(no image because I cannot show it being removed) 

Step 4: unlock the compacting drawer and it will seem like a normal compacting drawer
![image](https://user-images.githubusercontent.com/97235091/149781890-9d6192c6-13b6-46d1-be62-5bed6b3e62bd.png)

Step 5: add an item that only fills 1 or 2 slots (not 3!) to the top slot (for example a slimeball or grass block)
![image](https://user-images.githubusercontent.com/97235091/149782079-37f5073d-6324-4ff5-a303-008db9593753.png)
![image](https://user-images.githubusercontent.com/97235091/149782113-cef1728d-b072-4c66-8d42-5195c3972b94.png)

Step 6: remove the item again
![image](https://user-images.githubusercontent.com/97235091/149782183-26823118-a2c1-4324-b8b5-73202dd3f66e.png)

Step 6: place it back into the top slot
![image](https://user-images.githubusercontent.com/97235091/149782255-c78b1a0f-4c36-459f-adde-9219b0962006.png)
![image](https://user-images.githubusercontent.com/97235091/149782339-d88855a4-7d83-4c88-95a7-ca807504ad08.png)

and thats it, now you can turn 1 of the top slot items into 1 of the bottom right items!

you can also make this work with 2 different items in the bottom slot, as long as the second item does not fill the bottom right slot.
![image](https://user-images.githubusercontent.com/97235091/149782222-4eec3c47-fd2f-4dd3-9bca-56510ebe2d65.png)
![image](https://user-images.githubusercontent.com/97235091/149782656-f8df6e1f-0da6-4600-9b71-9a4b96514813.png)

**Comment by jeremiahwinsley** [comment]
Fixed in 1.8.18.
