### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by Pinata22** [AllTheMods/ATM-6#2866]
### Possible Fixes

Yes

### Modpack Version

1.8.16

### What happened?

everything is going fine until i change my texture pack, the game crash a few minutes later for no reason, my config is good, the problem is not there.

### Crash Log

<script src="https://gist.github.com/Pinata22/aa9ae56d7e8e537212b0e7eb9d8c99cf.js"></script>

**Comment by radiomike** [comment]
Try updating the observable mod to 0.2.1-forge.
