### ISSUE TITLE
Game crashes while raising an enchanted refined obsidian shield

### ISSUE THREAD

**Issue by razma417** [AllTheMods/ATM-6#287]
**Describe the bug**
I was using a refined obsidian shield, then enchanted it. It got enchanted with Displacement III, Phanlanx IV, Shield Bash II and Soulbound. When I went to raise the shield, the game instantly crashed. Tried 3x to raise again to confirm it was the raise that crashed it. Crafted a second shield and enchanted it with Bulwark only, and game crashes when it's raised as well.

**To Reproduce**
1. Raise a refined obsidian shield
2. Enchant the shield with any enchants
3. Put shield in offhand and right click to raise
4. Game crashes instantly.

**Expected behavior**
Shield raises and game doesn't crash

**Additional context**
I was using the shield fine before it was enchanted, I enchanted it, equipped it, and then tried to raise it and instant crash. Tried twice more to confirm it was shield raising and it is.

**Comment by ViRb3** [comment]
I used (and raised) a Refined Obsidian enchanted shield just yesterday and it worked without problems. It is probably a particular enchantment that causes the issue. Please provide crash logs.

**Comment by razma417** [comment]
[crash-2020-11-08_11.59.06-server.txt](https://github.com/AllTheMods/ATM-6/files/5507099/crash-2020-11-08_11.59.06-server.txt)
[crash-2020-11-08_12.08.10-server.txt](https://github.com/AllTheMods/ATM-6/files/5507100/crash-2020-11-08_12.08.10-server.txt)
[crash-2020-11-08_11.49.10-server.txt](https://github.com/AllTheMods/ATM-6/files/5507101/crash-2020-11-08_11.49.10-server.txt)

**Comment by ViRb3** [comment]
After a discussion with the COFH team, this turns out to be an issue with the Ensorcellation mod, which has been fixed in the new update. You can try updating the mod manually, or wait for next ATM6 update.
