### ISSUE TITLE
[Bug]: 1.8.17 Server Files result in crash - JEI Not included in server files. 

### ISSUE THREAD

**Issue by BeerHuntor** [AllTheMods/ATM-6#2873]
### Possible Fixes

Yes

### Modpack Version

1.8.17

### What happened?

Latest version of the server files, results in a crash upon load, JEI is missing from the server files.  

### latest.log

https://gist.github.com/BeerHuntor/676f32e09138611ef4c92516e376070e

**Comment by radiomike** [comment]
Probably issues downloading from curseforge. 

You could try grabbing it from your server, or download manually here https://www.curseforge.com/minecraft/mc-mods/jei/files/3486455

Also, double check the server mod folder as others may be missing. You should have 336 mods in the mod folder.
