### ISSUE TITLE
1.8.17 doesn’t launch with OpenJava 11.0.13.8 (latest)

### ISSUE THREAD

**Issue by officiallymarky** [AllTheMods/ATM-6#2874]
Took me a while to isolate this but when running 1.8.17 it will fail right after observables. 

If you downgrade to August release (11.0.12.7) it works fine.  

.16 loads fine using latest version though.

**Comment by olivia-mativi** [comment]
Confirming that I experienced the exact same issue with Eclipse Adoptium OpenJDK 11.0.13.8. 

I was able to launch the game successfully by rolling back as suggested.

**Comment by waybaker** [comment]
I can get it to run on Eclipse Adoptium OpenJDK 11.0.13.8, but it is so choppy its unplayable.  I bounce between 250+ fps to 10, just walking around the tiny hut I have, and in the mine I started.

**Comment by jeremiahwinsley** [comment]
I don't think there's anything we can do to fix the incompatibility, but I updated the wiki page to specify 11.0.12.
