### ISSUE TITLE
[Bug]: Duplication Glitch - Compacting Drawers

### ISSUE THREAD

**Issue by CannibalRat00** [AllTheMods/ATM-6#2877]
### Possible Fixes

Yes

### Modpack Version

1.8.17

### What happened?

When iron is put in compacting drawer the iron blocks are equal to the compressed blocks meaning you can withdraw 1 compressed block while only having 1 iron block effectively turning your 1 block into 9.

### latest.log

https://gist.github.com/CannibalRat00/eb50497d4c6de71c4f218404e8a379a7

**Comment by jaquadro** [comment]
Try this release https://www.curseforge.com/minecraft/mc-mods/storage-drawers/files/3611471

**Comment by jeremiahwinsley** [comment]
Fixed in 1.8.18.
