### ISSUE TITLE
Industrial foregoing Block Placer not placing blocks

### ISSUE THREAD

**Issue by Nidaelie** [AllTheMods/ATM-6#288]
I think since last update thei block refuses to place the blocks, it does the sound but no block is placed. Tried to remove de claim and still not working.

Was working before the last update

**Comment by Kris1432** [comment]
Are the chunks claimed by chance?

**Comment by Nidaelie** [comment]
Checked claimed and unclaimed, I got the sound of the machine trying but no
block being placed

**Comment by jeremiahwinsley** [comment]
Works in 1.3.9.
