### ISSUE TITLE
[Bug]: 1.8.16 - Inventory Tweaks item sorting deletes ores while using TC Smeltery

### ISSUE THREAD

**Issue by victoriarosetch** [AllTheMods/ATM-6#2882]
### Possible Fixes

Yes

### Modpack Version

1.8.16

### What happened?

I was putting some ores into my smeltery when I accidentally pressed the middle mouse button to sort the inventory while hovering over the smeltery inventory, this then deleted my ores to where there was only one of each in the smeltery (from 20 or so)  but they did not go into my inventory nor my backpack so must have been voided.

### latest.log

https://gist.github.com/victoriarosetch/0c23ba1e5b681494dd4ec9d40ffd3ee7

**Comment by jeremiahwinsley** [comment]
Sorting has been disabled for the smeltery in 1.8.19.
