### ISSUE TITLE
[Bug]: Diamond Ring crafting recipe doesn't work

### ISSUE THREAD

**Issue by kwang4** [AllTheMods/ATM-6#2883]
### Possible Fixes

Yes

### Modpack Version

1.8.17

### What happened?

When crafting the diamond ring from Angel Rings in ATM 6, the recipe does not produce an output, regardless of whether it was crafted in a vanilla crafting table or any other kind. 

Expected Behavior: 
![image](https://user-images.githubusercontent.com/52985771/149021788-415e0623-e03d-4b51-896d-0e128af7c5cc.png)

What shows up: 
![image](https://user-images.githubusercontent.com/52985771/149021960-6bd35653-8d5f-491a-90bc-be96e8c76b57.png)

### latest.log

https://gist.github.com/kwang4/098fb592fb428eb58cbfbe80cb2e609d

**Comment by radiomike** [comment]
Most likely your elytra has some nbt data associated with it. Also, if you've manually placed items, check that none of the other blocks is a 1x compressed block. They look very similar, especially when gui is small.
