### ISSUE TITLE
Campfires have no smoke particles

### ISSUE THREAD

**Issue by deigil** [AllTheMods/ATM-6#2884]
Campfires are not showing smoke particles. Have hay underneath to no avail. Little crackle fire particles are present though, just no smoke. Torches do have smoke particles.

**Comment by radiomike** [comment]
I think this is caused by the advanced chimneys mod.

Have a look in `config/adchimneys-client.toml` try setting `emitWithoutChimney` to true.

**Comment by deigil** [comment]
yupp that did the trick thank you
