### ISSUE TITLE
[Crash]: ArrayIndexOutOfBoundsException: -1

### ISSUE THREAD

**Issue by Parker8283** [AllTheMods/ATM-6#2885]
### Possible Fixes

Yes

### Modpack Version

1.8.17

### What happened?

From one of the people playing on my server. He told me he was just exploring a cave, turned around, and then the game crashed. Looks like an error rendering a Creeper, but I can't figure out what mod caused it from just looking at the crash report, so I'm reporting it here first to hopefully get some help deciphering this crashlog.

### Crash Log

https://gist.github.com/Parker8283/18086d73d24bc06e2e32e455b1564f28

**Comment by jeremiahwinsley** [comment]
Fixed in 1.8.19.
