### ISSUE TITLE
[Bug]: Error while trying to get URL from cursemeta

### ISSUE THREAD

**Issue by puma826** [AllTheMods/ATM-6#2887]
### Possible Fixes

Yes

### Modpack Version

1.8.17

### What happened?

Im trying to run the server installer .bat but i get so many errors and at the end the server just gets stuck boot looping

Example of error: [ERROR] Error while trying to get URL from cursemeta for mod ModEntryRaw(projectID=241721, fileID=3333980)

And at the end it only has about 150 mods in the mods folder and gives this error:
Invalid initial heap size: -Xms5G
The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

Java is up to date, latest version of atm6, ran as admin and tried several times.

Edit: I deleted the server lock and ran it again, it installed 329 mods but is still not starting, the contents of the terminal are below.

### latest.log

https://gist.github.com/puma826/0d2248a322f0c78f4caa35ad0b00beb9

**Comment by DesolatorX** [comment]
I have similar problems trying to instal atm6

**Comment by TakeyaSaito** [comment]
i'm getting the same exact problem, can't setup the server at all due to this

**Comment by puma826** [comment]
I fixed the heap size issue because i found that my java was 32 bit rather than 64 bit because the install page gives you 32 bit if your using a 32 bit browser, i had to go under all downloads and select 64 bit. I still have the issue of getting errors when the server tries to download the mods though.

**Comment by jeremiahwinsley** [comment]
This is just a curseforge outage, nothing we can do about it.
