### ISSUE TITLE
[Bug]: 1.8.17 startserver.sh/startserver.bat

### ISSUE THREAD

**Issue by Rehpicul** [AllTheMods/ATM-6#2888]
### Possible Fixes

No

### Modpack Version

1.8.17

### What happened?

There seems to be an issue with the serverstart. On Ubuntu I get ping failure's when not run with Sudo which may be unrelated. However even after multiple attempts a lot of mods are failing to download. I even tried a clean install of Ubuntu. I got the same result with windows 10 using the .bat as I did with the bash script. On a side note if it helps I was able to get an ATM 7 server up and running right after giving up on the ATM 6 server. The ATM 7 script did not need to be run as sudo to successfully ping. I did change versions of Java. I was initially using Java 11.0.13-tem. I tried multiple versions of Java as well including 8.0.312-tem.

### latest.log

https://gist.github.com/Rehpicul/b1a658644c6c02b95592e3545f1a0bcd

**Comment by MilleniumModsSources** [comment]
Can confirm on Windows 10 and Ubuntu 20.04, the same issue as @Rehpicul mentioned. Looks like simply the download links are incorrect

**Comment by Rehpicul** [comment]
Looks like the issue is resolved. This would suggest to me the #2887 may have been the underlying issue.
