### ISSUE TITLE
No Certus Quartz ore in Mining Dimension

### ISSUE THREAD

**Issue by ixanza** [AllTheMods/ATM-6#289]
Pack version: 1.2.1

I don’t seem to be getting certus quartz or charged certus quartz in the mining dimension in hours of mining. After testing with a digital miner it showed 0 to mine with max range. Is this an intended mechanic or is it a bug?

**Comment by rasm685p** [comment]
I got the same issue

**Comment by jeremiahwinsley** [comment]
Fixed in 1.3.9.
