### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by FoxTheUnicorn** [AllTheMods/ATM-6#2892]
### Possible Fixes

Yes

### Modpack Version

1.8.17

### What happened?

Quest Book  > Ars Nouveau Tab has 'Glyph of Slowfall' as child node of 'Magic Clay' but requires Marvelous Clay to craft.

![image](https://user-images.githubusercontent.com/27157603/149668171-415302da-55ca-4fad-911e-92e434b55764.png)
![image](https://user-images.githubusercontent.com/27157603/149668184-7bcf1500-1a45-4a4d-8199-b2566904b735.png)

### latest.log

Not needed

**Comment by jeremiahwinsley** [comment]
Fixed in 1.8.18.
