### ISSUE TITLE
[Crash]: Serwer crash Mekanism mod in All the mods 6 

### ISSUE THREAD

**Issue by Negariom** [AllTheMods/ATM-6#2893]
### Possible Fixes

No

### Modpack Version

1.8.17

### What happened?

I cant start serwer :/ 

### Crash Log

(https://gist.github.com/Negariom/9166141e42ac00c3f9b886f878d09066)

**Comment by jeremiahwinsley** [comment]
Looks like the server did not install correctly, you are missing Mekanism. Try reinstalling the server.
