### ISSUE TITLE
[Bug]: Cannot enchant Pedestals Advanced Books using Apotheosis enchanting table

### ISSUE THREAD

**Issue by iconmaster5326** [AllTheMods/ATM-6#2894]
### Possible Fixes

Yes

### Modpack Version

1.8.17

### What happened?

I have a maxed-out Apotheosis enchanting table, and I really want a Pedestals advanced enchantment from it. However, the book's enchantability is too low to obtain it even when the table is as good as can be. This screenshot should illustrate the problem:

![image](https://user-images.githubusercontent.com/3768458/149831354-94a6933d-c5e2-4490-b6fc-99f2eedf9a56.png)

### latest.log

https://gist.github.com/iconmaster5326/ee65fc5ff923cb4509b7d3d9c246cf3f

**Comment by jeremiahwinsley** [comment]
Not a bug, by design this can only be enchanted via Pedestals.
