### ISSUE TITLE
[1.8.17] Java crash on startup

### ISSUE THREAD

**Issue by memmons2k** [AllTheMods/ATM-6#2899]
I've been troubleshooting the pack for days now, I have manually set it to my Java 8 installation which I just updated to build 321, MultiMC memory allocation set to max 10112 MiB, but when I start the pack I get token recognition errors followed immediately by a -1 crash. 

Here's the log, it looks the same every time I try and launch. [https://pastebin.com/ehRd0Vcw](url)

**Comment by radiomike** [comment]
Looks like Java 8-321 breaks forge. While we wait for forge to be fixed, either downgrade your java or grab a different one from <https://github.com/AllTheMods/ATM-6/wiki/Java-Versions> - The versions here are currently good, but do double check in case they update to java 8-321+.

**Comment by memmons2k** [comment]
Thank you! Downgrading to the Java 11 on that page worked a charm.
