### ISSUE TITLE
Elemental Craft - Crash When looking at tank - 1.2.1

### ISSUE THREAD

**Issue by KlankSmash** [AllTheMods/ATM-6#290]
**Describe the bug**
java.lang.ArithmeticException: / by zero
Crash when looking at elemental craft tank in inventory. Sometimes will also crash when one is just in view in the world as well.

**To Reproduce**
Mouse over elemental craft tank in inventory.

**Additional context**
Crashlog
[https://pastebin.com/VrWFEZ4v](https://pastebin.com/VrWFEZ4v
)

**Comment by Sirttas** [comment]
It's fix in latest version of elemental craft
