### ISSUE TITLE
[BUG] ATM 6 1.8.17 ? Enderium/Lumium Essences without function, seeds also unplantable

### ISSUE THREAD

**Issue by fkempf78** [AllTheMods/ATM-6#2903]
Enderium Seeds and Lumium Seeds cannot be planted in Botany Pots, Seeds missing in JEI and Essences cannot be used anymore. Got the seeds and Essences still stored in Storage Drawer, but now unusable

**Comment by jeremiahwinsley** [comment]
That's intended, "alloy" type seeds are disabled in favor of other automation methods. They were not supposed to be craftable to begin with, but a mod update added them and we didn't catch it immediately.
