### ISSUE TITLE
hi my name is lars and i have a problem to get my server to work

### ISSUE THREAD

**Issue by crimsontora** [AllTheMods/ATM-6#2904]
### What would you like to know?

hi my is Lars and i have a problem to get my server to work it says 
invalid initial heap size: -Xms8g
the specified size exceeds the maximum representable size.
error: Could not create the Java Virtual Machine.
error: A fatal exeption has occured. Program will exit.
and i have 32g ram and have try to give it up too 15g ram still get the same thing what can be the problom.

**Comment by SlackerNet** [comment]
Xmx specifies the maximum heap size available to an application
    Xms specifies the minimum heap size available to an application

so Xms needs to be equal to or less than Xmx
Example:
Xms2G
Xmx8G

**Comment by crimsontora** [comment]
nothing chance say the same thing
![new error](https://user-images.githubusercontent.com/98280238/150694413-d0efc183-47ce-4af3-a35b-83071a78534e.png)

**Comment by Lavan** [comment]
You are most likely using a 32-bit java. Upgrade to Java 17.0.1 64-bit.

**Comment by jeremiahwinsley** [comment]
Links are provided here for 64-bit Java 8 and 11. https://github.com/AllTheMods/ATM-6/wiki/Java-Versions
