### ISSUE TITLE
[Crash]: Since yesterday my Server isn't starting anymore

### ISSUE THREAD

**Issue by Addy105** [AllTheMods/ATM-6#2905]
### Possible Fixes

Yes

### Modpack Version

1.8.18

### What happened?

Hello,

Since yesterday my Server is not starting anymore 

i get those messages you see in the screenshot
![2022-01-24 16_15_36-C__WINDOWS_system32_cmd](https://user-images.githubusercontent.com/98334296/150812587-589c52ac-4a9d-4e69-83eb-5910c36beabe.jpg)

### latest.log

https://gist.github.com/Addy105/967e40ecc3a0984b52b3a1c6b2a26f92

**Comment by jeremiahwinsley** [comment]
Java 8u321 is not compatible with Forge 36.2.23, you need 8u313 or older: https://github.com/AllTheMods/ATM-6/wiki/Java-Versions
