### ISSUE TITLE
[Question]: ATM 1.8.18 / Resourceful Bees crafting recipe and Beediddy

### ISSUE THREAD

**Issue by LDeschamps** [AllTheMods/ATM-6#2907]
### What would you like to know?

Hi,

I went from the 1.8.16 version to the 1.8.18 and notice that the recipe for [Tier 1 Beehive] from Resourceful Bees consisting of vanilla [Beehive] and 8 grass is now gone, is this intended ? I don't see any notice of that in the releases (neither atm or resourceful bees). Now the only recipe is the one with the nests found in nature with grass (there was the 2 recipes before that).

I also noticed that the Beediddy Bee is buggued as its textures are purple, they don't take any damage and yet continue their normal behaviour, aka one tapping players. (see image below).
![image](https://user-images.githubusercontent.com/26222666/150979345-8700f83b-5f08-4d56-8eea-acbb56003d4b.png)

**Comment by deigil** [comment]
I have the same issue, my auto crafter setup for the apiaries is now broken as the recipe for the tier 0 hive is now removed...

**Comment by deigil** [comment]
and I just confirmed on my world, beediddys are completely broken...

**Comment by deigil** [comment]
Beeddidy has a missing texture. Need to calm down angry bees now to put them in a jar. The recipe was removed intentionally by the resourcefulbees team.

**Comment by LDeschamps** [comment]
The Beeddidy doesn't seem to be capturable as their texture is still missing even not angry

**Comment by jeremiahwinsley** [comment]
Fixed in 1.8.19.
