### ISSUE TITLE
[Crash]: Placing Cyclic Doorbell on top of a dark oak leaf block crashes the game.

### ISSUE THREAD

**Issue by KoloXD** [AllTheMods/ATM-6#2908]
### Possible Fixes

Yes

### Modpack Version

1.8.18

### What happened?

Nothing really more I could add, as said in title doing so crashes the game. Luckily it does so without actually placing the item so the World is not corrupted. Was in singleplayer and creative mode.

### Crash Log

https://gist.github.com/KoloXD/0afc4d14fa5339ccabb66cd67b560ed2

**Comment by jeremiahwinsley** [comment]
Reported here: https://github.com/Lothrazar/Cyclic/issues/2057

**Comment by jeremiahwinsley** [comment]
Fixed in 1.8.23.
