### ISSUE TITLE
[Crash]: Crashes game due to pipes from refined storage

### ISSUE THREAD

**Issue by xTolo** [AllTheMods/ATM-6#2909]
### Possible Fixes

Yes

### Modpack Version

1.8.18

### What happened?

I know the reason as to why it crashed, I was using the builder gadget and I went to place cables from refined storage, in doing this they didn't necessarily want to connect and it ended up crashing my game.

The crash text shows this- The game crashed whilst ticking block entity
Error: java.lang.IllegalStateException: No network node present at BlockPos{x=-7349, y=7, z=599}, consider removing the block at this position
Exit Code: -1

Haven't done a crash report before, sorry if it's completely wrong.

### Crash Log

https://gist.github.com/xTolo/668025b9336b2bd99b586d0aa29c51ce#file-atm-6-crash-report-crashing-due-to-pipes-from-refined-storage

**Comment by jeremiahwinsley** [comment]
Blacklisted RS blocks from the building gadget in 1.8.19.
