### ISSUE TITLE
[1.2.1] Crash when using mining gadget on QuarryPlus frame

### ISSUE THREAD

**Issue by alexandrusendroni** [AllTheMods/ATM-6#291]
When mining a QuarryPlus frame with a Mining gadget, the game crashes.

**To Reproduce**
1. Create a new Quarry.
2. Let the Quarry create the frame
3. Attempt to mine a QuarryPlus frame block with a Mining Gadget.

**Expected behavior**
Do not change the QuarryPlus frame state OR mine/destroy the frame.

PS: if the crashlog is needed, please let me know.

**Comment by andrewsf** [comment]
Yes, the crash log is always beneficial.

Please file a bug @ https://github.com/Direwolf20-MC/MiningGadgets/issues

**Comment by alexandrusendroni** [comment]
Thank you for your comment.
I opened the issue here: https://github.com/Direwolf20-MC/MiningGadgets/issues/120

**Comment by jeremiahwinsley** [comment]
Fixed in 1.3.9.
