### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Cleareddrippp** [AllTheMods/ATM-6#2910]
### What would you like to know?

could someone please clear me a doubt, can i kubejs from a mod pack without installing the whole mod pack??

**Comment by jeremiahwinsley** [comment]
Not sure what you're asking here.

**Comment by KanyeMiddleEast** [comment]
I don't quite understand what you are asking, are you asking if you can install kubejs without installing a mod pack?

If that is what you are asking, then yes, you can. You can download the mod here https://www.curseforge.com/minecraft/mc-mods/kubejs-forge . I would install the curse forge launcher, click create a custom profile, and then add whatever mods you like that way, so curse forge will take care of any required supporting mods.
