### ISSUE TITLE
[Crash]: ATM6 - online dedicated 1.8.17 to 1.8.18

### ISSUE THREAD

**Issue by BAk99** [AllTheMods/ATM-6#2912]
### Possible Fixes

Yes

### Modpack Version

1.8.18

### What happened?

I have a very games OpenMod dedicated server.

When adding the 1.8.18 server files to update, the server goes haywire.  Java 8 serverstart-2.0.2.jar as launch config (potentially the issue).  If so how do I keep my current world and player's data while updating to latest version?  Also unsure what .jar I should launch with after this update.

Unable to gain crash log as I've reloaded a backup.

### Crash Log

na

**Comment by jeremiahwinsley** [comment]
https://github.com/AllTheMods/ATM-6/wiki/Pack-Upgrade-FAQ

In-place upgrades are not supported with the server starter.
