### ISSUE TITLE
[Question]: Unable to craft compressed Hay x1

### ISSUE THREAD

**Issue by RianaWolfy** [AllTheMods/ATM-6#2914]
### What would you like to know?

According to the crafting recipes, there is no way to make compressed x1 Hay
I'm assuming this is a bug? Is there a config change/update I can do?

![image](https://user-images.githubusercontent.com/67270927/151303638-a3cb5553-7df0-4bc6-9327-3d2fe40b5c9c.png)

**Comment by Pdiddy973** [comment]
Fixed for next update, you can update ATC yourself if you don't want to wait for a pack update.
