### ISSUE TITLE
Crash on Starting latest Server Downloaded from Curse

### ISSUE THREAD

**Issue by gothicdude1044** [AllTheMods/ATM-6#2915]
I have attached the latest log file and debug file because my server will not load
[debug.log](https://github.com/AllTheMods/ATM-6/files/7951939/debug.log)
[latest.log](https://github.com/AllTheMods/ATM-6/files/7951941/latest.log)

**Comment by SirFlopAlot** [comment]
uninstal the latest java version and download java 8 from the java oracle database that fixed it for me

**Comment by gothicdude1044** [comment]
Ok i will try that this weekend

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Tributary** [comment]
>uninstal the latest java version and download java 8 from the java oracle database that fixed it for me


[latest.txt](https://github.com/AllTheMods/ATM-6/files/7962068/latest.txt)
Crashed during install, and upon restart it would immediately crash, this is a log off the restarted crashing
The latest java 8 is 321

**Comment by Tributary** [comment]
>https://github.com/AllTheMods/ATM-6/issues/2899 

it's an issue with the latest version of java and forge

**Comment by jeremiahwinsley** [comment]
We have links to working versions on the wiki page: https://github.com/AllTheMods/ATM-6/wiki/Java-Versions
