### ISSUE TITLE
[Bug]:  RFtools builder quarry

### ISSUE THREAD

**Issue by blade0117** [AllTheMods/ATM-6#2918]
### Possible Fixes

Yes

### Modpack Version

1.8.17

### What happened?

im using the rftools builder quarry card clearing fortune it mines fine until it hits allthemodium ore which i know it cant mine so i switch the if not possible mode off and now it wont mine any ores it skips them all in the mining dimension
![mining photo](https://user-images.githubusercontent.com/1627513/151608813-0681d164-cc0a-41c0-9b7e-9da2deb7f2e6.png)

### latest.log

https://gist.github.com/blade0117/792473d4d46b0bb2e8143ccd76fb9258

**Comment by jeremiahwinsley** [comment]
Not a bug, just that your storage is filling up faster than you're emptying it. If the storage is full, it doesn't have room to mine, so it skips a block.
