### ISSUE TITLE
 For those using OpenJ9 please read

### ISSUE THREAD

**Issue by bobothehobo2** [AllTheMods/ATM-6#2922]
### Possible Fixes

Yes

### Modpack Version

1.8.18

### What happened?

This is **not** a bug with ATM6 so I'm not asking the team to give it any thought at all I just wasn't sure how to do it to warn the masses so it will save them time.  However, if you do use OJ9 for the server or client (or standalone fore that matter)  Oj9 version 11.0.14+ has had some re-work from .13 that breaks ATM6.  More specifically you will start getting a NoClassDefinition exception pointing to the cpw library.  I've tried many different modlauncher8.0.9 jar on many different ATM6 server installs and nothing works.  Also, you will get random failures on api calls to cursemeta that I've verified exist and are up.  Once I re-installed OJ9 11.0.13 (any patch number) it resolved.  I've attached a gist of what the error looks like.  Happy Mining!

### latest.log

https://gist.github.com/bobothehobo2/ef872cda8037e51d899728723c89bdfa

**Comment by jeremiahwinsley** [comment]
This is not specific to OpenJ9, we have a warning about that on our Java Version page: https://github.com/AllTheMods/ATM-6/wiki/Java-Versions

That said, OpenJ9 is known to cause issues and is not supported.
