### ISSUE TITLE
[Question]: Is Lumium MA Essence not supposed to craft Lumium?

### ISSUE THREAD

**Issue by timeconsumer06** [AllTheMods/ATM-6#2925]
### What would you like to know?

ATM6 V 1.8.18

I am able to make Lumium Mystical Agriculture seeds, and I have a stockpile of 100k Lumium MA Essences. 

I went to make a RS Pattern for Lumium utilizing the essences, and there is no crafting recipe for this. Is the lack of a crafting recipe for Lumium Essences intended? If so, Lumium MA Essences have zero use in the pack, but I  would love to see the addition of a recipe for this.

Edit: I have discovered that this is also the case for Enderium MA Essences, where it has no crafting recipe associated with the essences. I am looking at more of the Thermal metals and seeing if there are any further associated essence/lack of recipes out there.

**Comment by jeremiahwinsley** [comment]
The alloys are supposed to be disabled, yes. There was a few updates where they were accidentally re-enabled, which is probably where you crafted the seed.
