### ISSUE TITLE
[Question]: Why Vibranium Comb's wax produce weight is 1%?

### ISSUE THREAD

**Issue by MPThLee** [AllTheMods/ATM-6#2926]
### What would you like to know?

https://github.com/AllTheMods/ATM-6/blob/2d260d0ff7c0dacacd19c51c5a4b7da17cf9f053/config/resourcefulbees/bees/bred/bees_ingot/Vibranium.json#L65-L66

Compared to other ATM-specific bees
https://github.com/AllTheMods/ATM-6/blob/2d260d0ff7c0dacacd19c51c5a4b7da17cf9f053/config/resourcefulbees/bees/bred/bees_ingot/Allthemodium.json#L65-L66
https://github.com/AllTheMods/ATM-6/blob/2d260d0ff7c0dacacd19c51c5a4b7da17cf9f053/config/resourcefulbees/bees/bred/bees_ingot/Unobtainium.json#L60-L61

**Comment by jeremiahwinsley** [comment]
Fixed in 1.8.19.
