### ISSUE TITLE
[Question]: Are bee's supposed to be lost when upgrading Apiary?

### ISSUE THREAD

**Issue by timeconsumer06** [AllTheMods/ATM-6#2928]
### What would you like to know?

I had a full Tier 2 apiary (9 Bee's) and went to upgrade it to a Tier 3 Apiary. I was expecting to receive the Lost Bee Box with the 9 Bee's inside after the upgrade. This was not the case. All the bees that were inside the Tier 2 were lost. 

Is this an intended effect? If so, can this be relayed in some clarity on the tooltip that "Bee's inside will be lost on upgrade" or something?

**Comment by Xplodin** [comment]
that is a good reason I take all my bees out manually before upgrading their apiary

**Comment by jeremiahwinsley** [comment]
This would be a question for Resourceful Bees, rather than the modpack. We may be able to add a tooltip, though.

**Comment by Pdiddy973** [comment]
You should get a "bee box" in your inventory when you upgrade an apiary and that should have your bees, that said it is good practice just to make sure the apiary is empty before upgrading

**Comment by jeremiahwinsley** [comment]
Added tooltip in 1.8.19.
