### ISSUE TITLE
[Crash]: Can't get server to run

### ISSUE THREAD

**Issue by Caedus1990** [AllTheMods/ATM-6#2929]
### Possible Fixes

Yes

### Modpack Version

1.8.18

### What happened?

Honestly at my wit's end. Every time I attempt to launch the server file, I get the same error message. Not sure if it has something to do with java, as I recently factory reset my pc and installed a fresh java 8 file. I was able to get the server to launch before my factory reset, but wasn't able to connect despite proper port forwarding and firewall port allowance.

### Crash Log

[latest.log](https://github.com/AllTheMods/ATM-6/files/7992041/latest.log)

**Comment by jeremiahwinsley** [comment]
The latest version of Java 8 is not compatible with Forge 36.2.23 - see our wiki page here: https://github.com/AllTheMods/ATM-6/wiki/Java-Versions

Forge has a fix out for that in 36.2.26, which should be in the next pack update.
