### ISSUE TITLE
No Osmium OreGen?

### ISSUE THREAD

**Issue by TheL0ki** [AllTheMods/ATM-6#293]
**Describe the bug**
It seems that no Osmium ore is generated.
Also JEI does not show up that it would be generated.

**To Reproduce**
1. Create new world

**Expected behavior**
Find at least some Osmium ore and to JEI give indication where it's generated

**Screenshots**
![image](https://user-images.githubusercontent.com/14993611/98661612-fcbf2400-2346-11eb-9f86-10cb0f1022fd.png)

**Additional context**
Version: 1.2.1
Installed via TwitchApp

I've searched in the issue tracker, but couldn't find any answer to if this is intended or not.

**Comment by WhitePhant0m** [comment]
Do you have optifine? if yo you do, remove it, it breaks world gen. if not, then try installing the pack through MultiMC and see if it the world gen works.

**Comment by Sa-kai** [comment]
Question, how does optifine breaks world gen, and would it break it if you add optifine after you load the world for the first time without optifine?

**Comment by WhitePhant0m** [comment]
I don't know why it breaks world gen, I just know that it does break it, as for the 2nd question, I assume that it would break it. but, the chunks created without optifine would be fine, but the newer chunks after adding optifine would have broken world gen.

**Comment by TheL0ki** [comment]
Thank you for your quick reply.
I don't have OptiFine installed.

I've tested your suggestion with MultiMC and created a test world, there I could find Osmium ore. I checked with my save game and traveled some distance to force new chunks to generate and could find Osmium too. So sorry for the inconvenience, I simply was confused why, after hours of mining I hadn't find a single ore... maybe it's because I'm in an "Meadows" Biome.

Never the less, this issue is solved.

**Comment by uGuui** [comment]
@TheL0ki I have the same problem with Osmium gen, i tried to open the modpack with multiMC but anything change, what should i do? 
![image](https://user-images.githubusercontent.com/76677855/103193890-8e193400-48bc-11eb-9d8c-a43fc03b7f98.png)

**Comment by TheL0ki** [comment]
@uGuui it is strangely hard to come by osmium in the overworked, don't know why. But I had the most luck around Y Level 30. And try to get to the mining dimension asap. Once there, osmium is not an issue anymore (but still around Y Level 30).

**Comment by uGuui** [comment]
Ok, but when you look at JEI, there show the graph of osmium ore in world gen like other ores? And about this mining dimension, i am noob in some mods, can you say the name of this dimension or the name of the mod pls? I only know deep dark, its that?
(if i wrote something wrong, i apologize, im brazilian and im trying to solve my problem urgently xD) thank you for the fast reply, i wasnt expecting this.

**Comment by TheL0ki** [comment]
No worries, i'm from Austria, so my english isn't any better ;)

I know it's weird that it's not showing up in JEI, that baffled me also and the reason I opened this issue.

The mining dimension is added by AllTheMods team, if I remember correctly the portal to access it is simple labled "Portal" in JEI (an orangeish plate with an square ender pearl in the middle). To craft it you need AllTheModium tough. A super rare ore in the overworld. Can be found from Y level 48 below in the Ocean biome. Either stripmine in the ocean ore get water breathing potion and search the ocean floor. To mine it you need at least an Netherite Pickaxe (or Enderium from Silent Gear).

With this you can craft the portal and access the dimension by Shift+Rightclick it with an empty hand. The dimension itself is an flat world, always daylight, with no mob spawns and night vision. So ideal for mining. The ore gen is the same as in the overworld so Osmium can be found at around Y level 30 but more abundant.

Also a good advice: Check out OreSight Potion (AllTheModium Sight, Osmium Sight, etc...) it highlights the corresponding ore in a 16 Block radius. Makes it so much easy to find certain ores. All you need is one Ingot/Gem of the ore. Recipes are shown in JEI.

BR,
Loki

**Comment by uGuui** [comment]
Thank you so much, you really helped me, i created a new world in creative and went to Y 30, i found the osmium ore there, now i will try to search in my world, i understood about the dimension, thanks for the explanation, you helped me a lot, good 2021 for you bro.
