### ISSUE TITLE
[Bug]: When using a deep mob learning with a data model in it the data model wont level up at all 

### ISSUE THREAD

**Issue by Xearneas** [AllTheMods/ATM-6#2933]
### Possible Fixes

Yes

### Modpack Version

1.8.18

### What happened?

Hi i wanted to automate nether stars without having wither bees or nether star seeds so i saw that i could do it with hostile nueral networks and ive never done the mod so i said lets give it a shot after i learned what i needed i went to go kill mobs and it didnt work i tried with multiple different weapons (even a unenchanted diamond sword with no affixes) and nothing worked

### latest.log

https://gist.github.com/Xearneas/1c048ee18a323e2eaf1001154cf1c77f

**Comment by jeremiahwinsley** [comment]
Tested with a couple different models, including wither model, and it levels up fine. Tested in both offhand and inventory.
