### ISSUE TITLE
Witch Hunters causing crashes

### ISSUE THREAD

**Issue by Crashcraft** [AllTheMods/ATM-6#2936]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

Exploring the world and Minecraft suddenly crashes; report says it has to do with witch hunters. 
Modpack version 2.2.4, MC 1.16.5

### Crash Log

https://gist.github.com/Crashcraft/665b0e9c168bdd6676603577e1fdca80#file-crash-2022-02-04_21-14-41-client-txt

**Comment by jeremiahwinsley** [comment]
I think you meant to post this in https://github.com/AllTheMods/Spellbound/issues, but this is caused by https://github.com/Mithion/Mana-And-Artifice/issues/424. As a workaround, you can downgrade GeckoLib to .61.
