### ISSUE TITLE
[Question]: I make two types of Dirty Lead Slurry

### ISSUE THREAD

**Issue by LiChen** [AllTheMods/ATM-6#2937]
### What would you like to know?

I made a mekanism mod yesterday about a five-fold increase in mineral production, and then I tested it with lead ore. Among them, Chemical Dissolution Chamber produced The slurries are [Dirt Lead Slurry] of the alltheores mod, and when I came back online today, the newly input lead ore was processed into [Dirty Lead Slurry] of the mekanism mod, the two slurry cannot be mixed, for me production line has a certain impact.

Is there any solution please?

**Comment by wiloxe** [comment]
I'm having same issue with clean slurry. I'm running one refining line for each type of ore with 5 crystalizers after the washer but the washer can't decide on what type of slurry to produce, Either from Mekanism or from AllTheOres
![2022-02-09_02 12 55](https://user-images.githubusercontent.com/4078460/153103060-fb2fff42-2d87-45a1-8c54-41f6d37afa89.png)
![2022-02-09_02 12 58](https://user-images.githubusercontent.com/4078460/153103063-b2203912-44ba-46d6-98bb-430cbcaa4817.png)
.

**Comment by jeremiahwinsley** [comment]
Fixed in 1.8.20.
