### ISSUE TITLE
I cant even launch game

### ISSUE THREAD

**Issue by Temper126** [AllTheMods/ATM-6#294]
First off I wanna say that I'm on a mac, and every time that I load the pack up it crashes and gives this error every time. This happens right at the start of launching the pack.

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0
2020-11-10 07:56:44,655 main WARN Advanced terminal features are not available in this environment
[32m[07:56:44] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Temper126, --version, forge-34.1.25, --gameDir, /Users/private/Twitch/Minecraft/Instances/All the Mods 6 - ATM6 - 1.16.3, --assetsDir, /Users/private/Twitch/Minecraft/Install/assets, --assetIndex, 1.16, --uuid, 6ff986f19a704b329c985bcc599b86ff, --accessToken, ❄❄❄❄❄❄❄❄, --userType, mojang, --versionType, release, --width, 1024, --height, 768, --launchTarget, fmlclient, --fml.forgeVersion, 34.1.25, --fml.mcVersion, 1.16.3, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200911.084530]
[m[32m[07:56:44] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 7.0.1+78+master.e9771d8 starting: java version 1.8.0_271 by Oracle Corporation
[m[32m[07:56:45] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[m[32m[07:56:45] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/Users/private/Twitch/Minecraft/Install/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=CLIENT
[m[1;31m[07:56:46] [main/FATAL] [ne.mi.fm.lo.FMLCommonLaunchHandler/CORE]: Failed to find Minecraft resource version 1.16.3-20200911.084530 at /Users/private/Twitch/Minecraft/Install/libraries/net/minecraftforge/forge/1.16.3-34.1.25/forge-1.16.3-34.1.25-client.jar
[mException in thread "main" [32m[07:56:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: Missing minecraft resource!
[m[32m[07:56:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLCommonLaunchHandler.lambda$validatePaths$4(FMLCommonLaunchHandler.java:124)
[m[32m[07:56:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
[m[32m[07:56:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
[m[32m[07:56:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLCommonLaunchHandler.validatePaths(FMLCommonLaunchHandler.java:121)
[m[32m[07:56:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLLoader.setupLaunchHandler(FMLLoader.java:199)
[m[32m[07:56:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLServiceProvider.initialize(FMLServiceProvider.java:94)
[m[32m[07:56:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServiceDecorator.onInitialize(TransformationServiceDecorator.java:68)
[m[32m[07:56:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$initialiseTransformationServices$7(TransformationServicesHandler.java:107)
[m[32m[07:56:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.HashMap$Values.forEach(HashMap.java:981)
[m[32m[07:56:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initialiseTransformationServices(TransformationServicesHandler.java:107)
[m[32m[07:56:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:59)
[m[32m[07:56:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
[m[32m[07:56:46] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

**Comment by WhitePhant0m** [comment]
use a different launcher or change file path to something that doesn't have a space in it.

**Comment by Temper126** [comment]
huh?

**Comment by 04Slash** [comment]
> Failed to find Minecraft resource version 1.16.3-20200911.084530 at /Users/private/Twitch/Minecraft/Install/libraries/net/minecraftforge/forge/1.16.3-34.1.25/forge-1.16.3-34.1.25-client.jar

This is a common issue with the Twitch launcher. Twitch has a hard time installing 1.13+ forge and for a lot of people it will not install it correctly. You can either use a different launcher or you will have to manually install the listed forge version, in this case 1.16.3-34.1.25, into the 'Install' folder: /Users/private/Twitch/Minecraft/Install

If the manual install happens to fail, try deleting the install folder, relaunching Twitch and install minecraft again (it should prompt this when going to the modpacks section) then retry the forge installation.
