### ISSUE TITLE
Crash: failed to synchronize registry data

### ISSUE THREAD

**Issue by Centrical49** [AllTheMods/ATM-6#2941]
### Possible Fixes

Yes

### Modpack Version

1.8.18

### What happened?

Everthing was working fine until i updated my java. Now i cant join my server

### Crash Log

https://gist.github.com/Centrical49/5ce341e00eb1cbbb46d4c98263e68569

**Comment by jeremiahwinsley** [comment]
Gist is inaccessible, but usually that means extra mods or different versions on one side or the other.

**Comment by Xplodin** [comment]
if you're using gdlauncher it fails to download envrioenergy for some reason that I dont know
