### ISSUE TITLE
[Bug]: Bee hive crafting recipes broken

### ISSUE THREAD

**Issue by sharpskull2** [AllTheMods/ATM-6#2942]
### Possible Fixes

Yes

### Modpack Version

1.8.18

### What happened?

The resourceful bees tiered hive recipes are broken, this means that if you have the resource you can immediately craft a tier 1 apiary, or any of the other hives without having to craft up through the tiers. In addition to this the vanilla beehive to tier 1 beehive recipes no longer exists, I saw that in [another post](https://github.com/AllTheMods/ATM-6/issues/2907) a comment was made saying that that recipe was removed by the resourceful bees team, but I feel that it should be added back into the modpack due to it adding unnecessary grind to the bee process, and also leading to world file bloat due to having to explore to find hundreds, if not thousands of the bee nests around the world.

### latest.log

https://gist.github.com/sharpskull2/61c6401b9bc43d0652f6b0beb6766adc

**Comment by jeremiahwinsley** [comment]
The hive recipes seem to work as intended, they just show up incorrectly in JEI. The hive recipe was added back in 1.8.19.

**Comment by sharpskull2** [comment]
Thank you for letting me know 😃
