### ISSUE TITLE
[Bug]: Missing stone types in void ore miner

### ISSUE THREAD

**Issue by lyssar** [AllTheMods/ATM-6#2949]
### Possible Fixes

Yes

### Modpack Version

1.8.18

### What happened?

It seems that not all stone types, which are avaiable in the normal overworld, are mined by the void ore miner.
An example is Deepslate which is not minable with the Rocky Resource Miner.
For me it looks like a bug, if not explain why you not let all stones minable since they are just for looks.

No log required I think :)

Fix would be: Add all forge:stone items to the miner program and just exclude certain ones

Regards,
Lyssar

**Comment by jeremiahwinsley** [comment]
Guessing that's because deepslate does not have the forge:stone tag. If so, adding that tag should fix it. What other stones do not show up?

**Comment by lyssar** [comment]
Will look at it later today but as I recall correctly it doesn't have the forge:stone tag

**Comment by jeremiahwinsley** [comment]
Added the tag to deepslate in 1.8.20. If you do find any others, feel free to open another ticket and we can get them added as well.

**Comment by lyssar** [comment]
Cool thanks and sorry hadn't enough time yet to check for the rest :) But I will create a list for it
