### ISSUE TITLE
Pulverized Ore are missing

### ISSUE THREAD

**Issue by lagonnebula** [AllTheMods/ATM-6#295]
**Describe the bug**
Some ore don't go inside the Thermal pulverizer but goes inside the enrichement chamber.
For example : Zinc, Aluminium, Platinium from AllTheOre
The fluorite can't be too 
Some other can be doubled with the Ore purification chamber but not with the enrichement chamber or the pulverizer like the Iner crystal Ore

**Expected behavior**
To be able to pulverized the ore to double it like the mekanism enrichement chamber

**Screenshots**
https://files.meuhmeuh.fr/images/javaw_bQAQomuLQh.png

**Comment by Pdiddy973** [comment]
zinc an aluminium ar fixed in 1.3.9, platinium will be fixed in 1.4.0
