### ISSUE TITLE
[Bug] [1.8.19] Soul Soil Block x1 cannot be crafted from Soul Soil

### ISSUE THREAD

**Issue by vedalken254** [AllTheMods/ATM-6#2950]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

Soul Soil Block x1 can only be made by decompressing Soil Soul Block x2. It has no other recipes to allow Soul Soil to be turned into it. Present on 1.8.19 (github drop-down hasn't been updated with the 1.8.19 option), no outside mods installed. Image attached displaying the valid crafting recipes for Soul Soil Block x1.
![javaw_0001b1](https://user-images.githubusercontent.com/1041344/153474931-7595fb23-bdd0-488b-b127-a5f6074c66ce.png)

### latest.log

https://gist.github.com/vedalken254/aeb6c67615a6f3faba10f3767d7ffaa3

**Comment by jeremiahwinsley** [comment]
Should be fixed in 1.8.21 with the update to ATC.
