### ISSUE TITLE
[Feature]:  Immersive Engineering - Pam's Harvestcraft 2 crops: Garden Cloche Compatibility mod

### ISSUE THREAD

**Issue by Pillgar** [AllTheMods/ATM-6#2952]
### Feature Details

Just a feature request to include: Immersive Engineering - [Pam's Harvestcraft 2 crops: Garden Cloche Compatibility mod](https://www.curseforge.com/minecraft/customization/immersive-engineering-pams-harvestcraft-2-crops).

Looks like it's compatible with 1.16.5, and would be nice to include it with ATM6.

**Comment by jeremiahwinsley** [comment]
It's not a mod, just a datapack. So it can't be included in packs without repackaging it.
