### ISSUE TITLE
[Question]: Apply indestructible on charms

### ISSUE THREAD

**Issue by Sveaty145** [AllTheMods/ATM-6#2955]
### What would you like to know?

Is there any way I can re-enable indestructible on charms?
Version:1.8.18

**Comment by tankirules** [comment]
Try this : https://www.youtube.com/watch?v=XnQSgaO_xjI&feature=youtu.be
I can confirm it works

**Comment by xStayCurious** [comment]
> Try this : https://www.youtube.com/watch?v=XnQSgaO_xjI&feature=youtu.be I can confirm it works

No longer works for charms, unless I'm doing something wrong. Used the indestructible book on a shovel, worked just fine, but will not work on any of my sight charms.
