### ISSUE TITLE
What mining level is Other Redstone Ore?

### ISSUE THREAD

**Issue by Revvilo** [AllTheMods/ATM-6#296]
Seems kinda nuts that a vibranium (level 6) tool can't mine it...

<img src="https://user-images.githubusercontent.com/13816212/98731725-060dc680-2403-11eb-961c-5ac0972d6c12.png" width=500px>
<img src="https://user-images.githubusercontent.com/13816212/98731729-08702080-2403-11eb-8844-ee203c594921.png" width=500px>

**Comment by NeoSono1981** [comment]
From what I learned while playing the modpack the silent gear stuff does NOT get the mining level of allthemodium, vibranium or unobtainium. I mean your screenshot even shows it as mining level obsidian which is just diamond level. even the netherite pick has a level above that.

**Comment by thevortex** [comment]
other redstone ore is actually a tier higher than what even vibranium can mine, other redstone, diamond, platinum, uranium and lapis are all tier 7 ores
