### ISSUE TITLE
[Question]: some dense honey combs give "wrong" amount of items. Is this intentional?

### ISSUE THREAD

**Issue by Tlotro** [AllTheMods/ATM-6#2960]
### Feature Details

centrefuge recipes for nickel, osmium and copper dense honeycombs give amount of items different from usual

![Copper recipe](https://user-images.githubusercontent.com/50557602/154766229-7d0fb9c1-36aa-4a51-a5d1-04a7bbd77632.png)
![Nickel recipe](https://user-images.githubusercontent.com/50557602/154766233-eaa0f20e-aa23-4be2-a3bb-37c6ac5e012e.png)
![Osmium recipe](https://user-images.githubusercontent.com/50557602/154766235-d763d28a-02f5-4a75-8e1e-3fc09b3e78f5.png)

other recipes look similar to this:
![Most use these proportions](https://user-images.githubusercontent.com/50557602/154766356-f78afc2a-ffbc-4c03-bd69-af8eb8d86edb.png)

**Comment by jeremiahwinsley** [comment]
Fixed in 1.8.20.
