### ISSUE TITLE
[Question]: Are Thermal Series Augmentation not working correctly? 

### ISSUE THREAD

**Issue by SerenityFire** [AllTheMods/ATM-6#2962]
### What would you like to know?

Hi,

in the newest version I cann't put in more then 1 Augmentation in one of these 3 Items. 

- Tinker's Workbench
- Flux Capacitor
- Redstone Flux Cell

Augmentations:
- High-Flux RF Coil
- Stabilized RF Coil
- Expanded RF Coil

I can use the 3 different Coils but only one will go in.
![javaw_pfMbZW064N](https://user-images.githubusercontent.com/51133457/154818069-93089948-e59c-46e8-82ae-4a560aff872c.png)

I have here two Flux Capacitors before the last update where the Augmentations are still in. If I take one out I cann't get them back in.
![javaw_13UbYcr2Li](https://user-images.githubusercontent.com/51133457/154818157-d93765ec-0984-47cf-abb3-bf7247625ffd.png)
![javaw_WBrU2Zr063](https://user-images.githubusercontent.com/51133457/154818158-9e1c1320-14a7-4a7c-accf-13e70cbb008e.png)

My Pulverizer works fine.
![javaw_bBNJOI3bsB](https://user-images.githubusercontent.com/51133457/154818321-b3743b0b-48dc-48d1-9560-8ab50c2bef1e.png)

Did something chaged or is this a bug?

I am on version 1.8.19.
My server has no error messages or crashes.

Thanks
Serenity

**Comment by jeremiahwinsley** [comment]
What version did you update from? I think that was disabled a couple months back, not in the latest update. But yes, that is an intentional change from Thermal.
