### ISSUE TITLE
[Crash]: My game keeps randomly crashing about every 15 min.

### ISSUE THREAD

**Issue by pmw1997** [AllTheMods/ATM-6#2964]
### Possible Fixes

Yes

### Modpack Version

1.8.19

### What happened?

 It sometimes has trouble loading ATM6, but when I'm in my world it runs really smoothly. I have 9056 mb of RAM allocated to Minecraft in CurseForge. I can't determine what is causing it to crash because every crash has happened while doing something differently. Things include breaking blocks and walking in a straight line. I find this modpack really enjoyable, but find myself unable to play it because all the crashes. 

[hs_err_pid25120.log](https://github.com/AllTheMods/ATM-6/files/8104933/hs_err_pid25120.log)

### Crash Log

https://gist.github.com/pmw1997/dbf3698ea3d5641213f3fce654dc9126

**Comment by jeremiahwinsley** [comment]
Looks like your GPU does not support the shaders used by Draconic Evolution. You can try updating your GPU drivers, if that doesn't work you can disable the shaders in `config/brandon3055/DraconicEvolution.cfg`. 

In the client section, find the shaders options:
```
	# Set this to false to disable tool shaders.
	B:"toolShaders"=true

	# Set this to false to disable crystal shaders.
	B:"crystalShaders"=true

	# Set this to false to disable reactor shaders.
	B:"reactorShaders"=true

	# Set this to false to disable chaos guardian shaders. (May visually break some stuff but could be useful if you are experiencing gl crashes.)
	B:"guardianShaders"=true

	# Set this to false to disable all other shaders.
	B:"otherShaders"=true
```
and set them all to false.
