### ISSUE TITLE
Games is not loaded on the client, just says "loading terrain..." but the server said I was slain by a zombie.

### ISSUE THREAD

**Issue by bchow05** [AllTheMods/ATM-6#2967]
On the server, it says I was slain by a zombie so I know I am loaded in the game but on the client side it just says, "loading terrain". Is there something I need to turn on/off?

Client:
iMac running macOS Big Sur.
CurseForge loaded.

Server is hosted on a paid server.

Thanks..!

**Comment by radiomike** [comment]
Double check the contents of `config/logprot-common.toml` Maybe that has been reset? You can compare it against or replace it with <https://github.com/AllTheMods/ATM-6/blob/master/config/logprot-common.toml>.
It's also possible that the zombie moved you more that the default 10 blocks while you were joining the world, which would remove the login protection.

**Comment by bchow05** [comment]
Thanks for the reply. I was able to load it by boosting the default allocated memory from 4GB to 8GB.
