### ISSUE TITLE
[Crash]: All the Mods 6 V. 1.8.8  crashes when loading game

### ISSUE THREAD

**Issue by Keeper-Of-Secrets** [AllTheMods/ATM-6#2968]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

after launching All the Mods 6 when the modpack finishes loading it will immediately crash to the minecraft launcher with, up until this last crash with a java invalid runtime configuration message exit code 1 OR -1. with this most recent crash it game me a Java.lang.runtimeException : GL_FRAMEBUFFER_INCOMPLETE ATTACHMENT with exit code -1.   if necessary i can provide earlier crash logs as well. 

running All the Mods 6 V. 1.8.8 off the curseforge launcher

Thanks-
            Keeper

### Crash Log

https://gist.github.com/Keeper-Of-Secrets/9bd7dddc3c296561e19213a886f27696

**Comment by radiomike** [comment]
The current version of the pack is 1.8.19, try updating and see if that resolves your issue?

**Comment by Keeper-Of-Secrets** [comment]
the only reason i am using that version is because that was the version we started our server on and havnt updated to a newer version yet but it also happens with other modpacks such as seaopolis
using the most recent version did not help

crash log from that test:
[latest.log](https://github.com/AllTheMods/ATM-6/files/8128520/latest.log)

**Comment by Keeper-Of-Secrets** [comment]
decided to try it again to see if it would give me an actual crash log and it did. figured providing as much info as i can helps
[hs_err_pid16040.log](https://github.com/AllTheMods/ATM-6/files/8128585/hs_err_pid16040.log)
.

**Comment by radiomike** [comment]
Both of those suggest issues with outside of the modpack. I think curse has an option to repair/refresh the minecraft install, that should probably be the first thing to look at - either that or try an alternative launcher like multimc. To copy any worlds/settings across, see https://github.com/AllTheMods/ATM-6/wiki/Pack-Upgrade-FAQ. 
Then check your graphics and sound drivers, though your graphics drivers do appear to be fairly recent.

**Comment by radiomike** [comment]
Actually, the latest.log shows out of memory errors, though it looks like you've assigned ~9gb in the crash. You should probably add the recommended java arguments to help there.
```
-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=32M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true
```

**Comment by Keeper-Of-Secrets** [comment]
where am i adding these java arguments to?

**Comment by Keeper-Of-Secrets** [comment]
i can now load in to a world without crashing (so far) but it is incredibly laggy

**Comment by radiomike** [comment]
If you use curse launcher, they are in the Minecraft settings. Should be labelled `additional arguments`

**Comment by Keeper-Of-Secrets** [comment]
still experiencing the crash upon loading modpack finalization occasionally but also the above issues are still valid

**Comment by Keeper-Of-Secrets** [comment]
tried with multiMC and the 1.8.20 version and got another crash.
[hs_err_pid14808.log](https://github.com/AllTheMods/ATM-6/files/8147082/hs_err_pid14808.log)

**Comment by radiomike** [comment]
Your system ran out of memory. Try adding those java args in again and limit other things that you are running on your machine. You should also double check that you have a swapfile enabled and set to a suitable size.

**Comment by Keeper-Of-Secrets** [comment]
so i believe i turned swap file off becasue it messes with planetside 2 performance. i will see about re-enabling and trying again.

this is the crash log when using the java arguments: https://gist.github.com/Keeper-Of-Secrets/3232d7b514e7e94897f07216823f3892

**Comment by radiomike** [comment]
```
Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x000000071e000000, 33554432, 0) failed; error='The paging file is too small for this operation to complete' (DOS error/errno=1455)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 33554432 bytes for Failed to commit area from 0x000000071e000000 to 0x0000000720000000 of length 33554432.
```
Still an out of memory error, due to lack of swap space (paging file). You might want to also check task manager, to see if anything else is filling your memory.
