### ISSUE TITLE
[Bug]: Compact Machine dimension spawns no overworld mobs other than slime

### ISSUE THREAD

**Issue by changhe3** [AllTheMods/ATM-6#2973]
### Possible Fixes

Yes

### Modpack Version

1.8.19

### What happened?

Cursed earth in compact machine spawns nothing but slimes and lantern wraith.

### latest.log

https://gist.github.com/changhe3/9348b2d057ed1c265678336c046c6ab5

**Comment by jeremiahwinsley** [comment]
Compact Machines are in the void dimension, not the overworld. If you want overworld spawns, then put it in the overworld.
