### ISSUE TITLE
[Bug]: Zycraft invisible block glitch

### ISSUE THREAD

**Issue by Czarniak4** [AllTheMods/ATM-6#2974]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

Out of nostalgia, I tried to make Zycraft multiblock tank and everything was ok till I closed the game. The next day when I opened the game, the tank was not working, clicking on the valve did nothing and when I tried to destroy everything turned out that in a place where water should be, now is an Invisible block that I can't interact with. I can't put there any block nor I can't walk through it.

I did try to refresh chunks and I'm playing in single mode.

### latest.log

https://gist.github.com/Czarniak4/c87c69798ba332c5fb4a863380076d4b#file-czarniak-log-file

**Comment by radiomike** [comment]
Seems like it might be this issue https://github.com/nikita488/ZYCraft/issues/19

**Comment by jeremiahwinsley** [comment]
We have disabled `reducedChunkNBT` as mentioned in that issue in 1.8.21, this should fix the issue.
