### ISSUE TITLE
[Crash]: server and client crashes when redstone furnace connected to universal cables via piston

### ISSUE THREAD

**Issue by XBlueBeam** [AllTheMods/ATM-6#2977]
### Possible Fixes

No

### Modpack Version

1.8.20

### What happened?

this crashed both my client and server i was on in multiplayer. it also crashes in singleplayer. it happens when i move a redstone furnace (thermal series) with a sticky piston via a button so it connects to 2 elite universal cables (mekanism).
![2022-03-02_17 26 08](https://user-images.githubusercontent.com/100788889/156404117-6acda475-245b-48c3-b420-5fe99fcccc7c.png)

### Crash Log

https://gist.github.com/XBlueBeam/d63811decfba2f806b89fda758a9a34b.js

**Comment by radiomike** [comment]
I don't think this is a bug, more of a "Please don't do that". Moving tile entities with pistons is likely to cause issues. 
As an alternative you could make the universal cables redstone activated with wrench.

**Comment by jeremiahwinsley** [comment]
Thermal has been added to the piston movement blacklist in 1.8.21.
