### ISSUE TITLE
Back-ups can not be extracted

### ISSUE THREAD

**Issue by JWAOSTAR** [AllTheMods/ATM-6#2978]
My game kept crashing due to low space on my computer so I had to use back-ups to restore things like way stones. When every I try to extract the zip it throws two errors during the process: 

1. unexpected data end
2. Data error: 'save'\region\r.-12.15.mca

I suspect it is something linked to player data because my location bugs and changes to somewhere else within the area(probably from the last time saved or backed-up, may not be a concern), and then the majority of my achievements un-clear.

**Comment by radiomike** [comment]
Unfortunately, if you were crashing due to low disk space then it's likely it wasn't able to save the backups properly. If you have older backups you may want to try those.
