### ISSUE TITLE
[Bug]: Wrong input in farmland script

### ISSUE THREAD

**Issue by Presyon** [AllTheMods/ATM-6#2981]
### Possible Fixes

Yes

### Modpack Version

1.8.20

### What happened?

Hello noticed something wonky with the mystical agriculture farmland and looked into the configs. Someone added 1600 seconds instead of 600. This would make tier 4 farmland the most efficient instead of tier 7, making any farmland past tier 4 useless. Hopefully just a quick fix. Uploaded picture and path to script below. 
D:\Storage\Misc\Minecraft\Instances\All the Mods 6 - To the Sky - ATM6sky - Skyblock\kubejs\server_scripts\mod_specific\cloche

![Inferium](https://user-images.githubusercontent.com/76184727/156767422-aed53909-2b23-487a-8957-8c6210a0648a.png)

### latest.log

https://gist.github.com/Presyon/ced3a763b7cfba7a463ec253a1d6f137

**Comment by radiomike** [comment]
The script in your screenshot is not what is supposed to be in 1.8.20 see for the up to date version https://github.com/AllTheMods/ATM-6/blob/master/kubejs/server_scripts/mod_specific/immersive_engineering/cloche.js
Looks like you might need to do a fresh instal of the pack to make sure all the scripts are up to date. Use https://github.com/AllTheMods/ATM-6/wiki/Pack-Upgrade-FAQ as a guide for what to copy to to the new install.

**Comment by Presyon** [comment]
My apologies this is the All the Mods 6 - To the sky modpack, the skyblock version. I couldn't find it on github so I came here. Again, my bad. It may be a different script.

**Comment by radiomike** [comment]
The github link for sky issues is https://github.com/AllTheMods/atm6-sky/issues
