### ISSUE TITLE
[Bug]: The quest path after the withered bee won't clear

### ISSUE THREAD

**Issue by JWAOSTAR** [AllTheMods/ATM-6#2986]
### Possible Fixes

Yes

### Modpack Version

1.8.20

### What happened?

I have the Wither be which is the one after the Withered bee however the quest tree will not continue.

### latest.log

<script src="https://gist.github.com/JWAOSTAR/e4151f496766c7bd82c9fc12db4e386a.js"></script>

**Comment by radiomike** [comment]
Have you caught it in a bee jar?
