### ISSUE TITLE
Game crashes while coming near base - Ender Chest error?

### ISSUE THREAD

**Issue by razma417** [AllTheMods/ATM-6#299]
**Describe the bug**
Game crashes when walking towards base (ender chest is located there)

**To Reproduce**
Walk towards base, get in range of ender chest rendering.
Game crashes

**Expected behavior**
Game continues working

The ender chest was working completely fine when I was playing on the server all day with a friend. When I reloaded the server tonight this happens and makes it unplayable.

3 Crash reports from all 3 tries attached.

[crash-2020-11-11_16.11.32-client.txt](https://github.com/AllTheMods/ATM-6/files/5527031/crash-2020-11-11_16.11.32-client.txt)
[crash-2020-11-11_16.19.19-client.txt](https://github.com/AllTheMods/ATM-6/files/5527032/crash-2020-11-11_16.19.19-client.txt)
[crash-2020-11-11_17.10.12-client.txt](https://github.com/AllTheMods/ATM-6/files/5527034/crash-2020-11-11_17.10.12-client.txt)

**Comment by razma417** [comment]
![Minecraft Error](https://user-images.githubusercontent.com/74085218/98875552-70962500-244a-11eb-91f5-efc82fc66937.png)

**Comment by jeremiahwinsley** [comment]
Fixed in 1.3.9.
