### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by JWAOSTAR** [AllTheMods/ATM-6#2991]
### Possible Fixes

Yes

### Modpack Version

1.8.20

### What happened?

I tried playing today and the game crashed with an error from the Patchouli. Yesterday I saved an quit perfectly, the only unusual thing that happened yesterday was that I accidentally clicked the resource pack button and when it exited the resource pack screen the game reloaded.

### Crash Log

https://gist.github.com/JWAOSTAR/20a42599198b8d613e3b5774ffca47c6

**Comment by radiomike** [comment]
Try deleting the file `patchouli.json` from your atm6 instance/profile.
If that doesn't solve it, try posting the crash report that was created in the crash reports folder.
