### ISSUE TITLE
What do I use to connect the 'redstone ports' from the 'bigger reactors' mod?

### ISSUE THREAD

**Issue by Lord-Volkner** [AllTheMods/ATM-6#2992]
### What would you like to know?

In the old days, it was a rednet cable, but that doesn't exist in this modpack. I've tried just about every cable in the modpack, but nothing seems to work. Which cable is used now?

... which leads me to a second question:

In my exploration of cables, I found that I could no longer set JEI to let me 'cheat' items from the item list on the right. I could ONLY cheat items from the regular Minecraft window thing in the middle. This was a problem because many of the things on the right hand list don't show up when searching for them in the middle window thing. For instance, the xnet 'routing cable' doesn't show when typed in. How do I get JEI to let me cheat in items from the right hand list?

Thanks
Eric

**Comment by radiomike** [comment]
Did you try the project red cables?

To cheat things in with JEI, ctrl-click on the settings button. It should turn red and allow you to cheat in items. You may need to be opped/have cheats enabled for your world too.

**Comment by Lord-Volkner** [comment]
> Did you try the project red cables?
> 
> To cheat things in with JEI, ctrl-click on the settings button. It should turn red and allow you to cheat in items. You may need to be opped/have cheats enabled for your world too.

Much appreciation!!

Someone else told me about using redstone dust on the ports to connect them. Duh! I never would have thought of that, but it worked.

Thanks for the JEI tip. That's a big one to make things much easier in my test world.
