### ISSUE TITLE
[Crash]: Game crashes during launch

### ISSUE THREAD

**Issue by PrincessKumico** [AllTheMods/ATM-6#2993]
### Possible Fixes

Yes

### Modpack Version

1.8.20

### What happened?

Crashes on launch. I tried multimc and curse forge, both do it. The crashlog here is from the multimc crash. I've tried to reboot my pc and still does it. I had it working earlier and haven't done anything since.

### Crash Log

https://gist.github.com/PrincessKumico/392265f0bb25de2c8dc7c83c77e7721a

**Comment by radiomike** [comment]
Looks like the config `config/alltheores-common.toml` is faulty/corrupted. 
Try replacing it with [config/alltheores-common.toml](url)
