### ISSUE TITLE
[Bug]: Duplication with Projection Spell in Mahou Tsukai

### ISSUE THREAD

**Issue by StarWalker1** [AllTheMods/ATM-6#2995]
### Possible Fixes

Yes

### Modpack Version

1.8.20

### What happened?

I used the Projection spell on a morgan that has indestructible on it. Projection sets the dura to 5, and the item can't break with indestructible, effectively duplicating it. Also when i tried to put the item in the trash in my inventory, it dropped a duplicate item on the ground, and i could still take it out of the trash in my inventory. They can also be repaired in a diamond anvil without the use of an indestructible enchantment.

### latest.log

n/a

**Comment by stepsword** [comment]
from a config side of things, you can do this in mahou's configs (assuming this is the correct enchantment name) to prevent indestructible on projected weapons

PROJECTION_ENCHANTMENT_BLACKLIST = ["forbiddenarcanus:indestructible"]

Also, all projected weapons have a MAHOUTSUKAI_PROJECTION boolean NBT tag on them set to true, which may help with the diamond anvil thing.. but if there's something else I can add that would make it easier to nerf stuff like this, let me know. 

I don't know what's causing the trash thing though

**Comment by jeremiahwinsley** [comment]
That enchantment has been added to the blacklist in 1.8.21.
