### ISSUE TITLE
[Bug]: Environmental Tech Mods not functioning at all

### ISSUE THREAD

**Issue by macery12** [AllTheMods/ATM-6#2996]
### Possible Fixes

No

### Modpack Version

1.8.20

### What happened?

I have tried multiple times to build the tier 1 solar panel and void miner from ATM6 and have had no luck, nothing with work nor will anything show any signs that its even close to working, tested it on a dedicated server and single player game and it has never worked, cant tell if I'm doing something wrong from the hundreds of videos I have seen or if its bugged out in this new version, any help would be great thank you!

### latest.log

https://gist.github.com/macery12/5f4fa46eb3554b693c0076f81e5b8806

**Comment by jeremiahwinsley** [comment]
Tested in 1.8.20 and the multiblock seems to work fine. Have you tried using the preview to build it?

**Comment by macery12** [comment]
yes i have, it wont even input power, the RF input block is getting power but the void miner itself wont charge what so ever, im not sure what i could be doing wrong, i had my other friend try building it for me that is also on the server and got nothing out of it

**Comment by jeremiahwinsley** [comment]
Are you able to post screenshots of the broken machines? For comparison, here's my test solar panel which is working fine:
![2022-03-21_20 37 22](https://user-images.githubusercontent.com/7946299/159385058-dd25108f-b87d-471d-9317-4645d1dd8020.png)

Alternately, if you join the discord, people may be able to help walk you through it there.

**Comment by macery12** [comment]
ill see if i can get help with discord and see if they can show me what im doing wrong, thank you so much!
