### ISSUE TITLE
How do I turn off this unknown thing?

### ISSUE THREAD

**Issue by Lord-Volkner** [AllTheMods/ATM-6#2998]
### What would you like to know?

I pressed something but don't know what. Now there's an outline of a cube just to the right of my target reticle and every block I place faces south. I've tried literally everything in the keybindings, but none of them turn this off. I don't even know what mod it's part of.

Please help.

Thanks
Volkner
![2022-03-16_21 28 25](https://user-images.githubusercontent.com/71194571/158724735-18ba9d9d-594c-401c-bc9f-f5f846150c64.png)
r

**Comment by Crasherhd** [comment]
This is a part of Quark, pressing k to turn it off should work.

**Comment by Lord-Volkner** [comment]
Yes, thank you. That worked ... which surprises me as I thought I tried every key on the keyboard multiple times.
