### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by qwertyduck** [AllTheMods/ATM-6#2999]
### Possible Fixes

Yes

### Modpack Version

1.8.20

### What happened?

![image](https://user-images.githubusercontent.com/48092239/158910480-9c470603-c7b3-4586-97ae-23b706691a37.png)
Botania's Runic altar is not progressing. 

### latest.log

https://gist.github.com/qwertyduck/832ddb3d11f2ffd3b0efde08d71977c6

**Comment by jeremiahwinsley** [comment]
Tested with 1.8.20 and the runic altar works with that recipe. Do you have the spreader linked to the altar?

**Comment by qwertyduck** [comment]
Yea, it is linked. The Comparator shows that it is receiving mana.

**Comment by jeremiahwinsley** [comment]
Maybe try removing all other parts besides pool and spreader, see if something else is breaking it? For comparison, here's my test one:
![2022-03-21_20 39 28](https://user-images.githubusercontent.com/7946299/159385197-659e9bb9-9867-4178-ad5f-05fad5581b0a.png)
