### ISSUE TITLE
cannot open it

### ISSUE THREAD

**Issue by michaelhsw4316** [AllTheMods/ATM-6#3]
[crash-2020-07-09_15.00.32-client.txt](https://github.com/AllTheMods/ATM-6/files/4895104/crash-2020-07-09_15.00.32-client.txt)

**Comment by michaelhsw4316** [comment]
the crash report is here

**Comment by michaelhsw4316** [comment]
every time I opened it, it started to load the mods but after it showed "initializing forge version...", it will stay the same and do not start the game.

**Comment by michaelhsw4316** [comment]
Could someone help me solve this problem? Is this a system problem since I use a macOS system?

**Comment by whatthedrunk** [comment]
Are you using the new 0.9a version? I see you are using an older version of forge. 32.0.61 is the one to use.

**Comment by michaelhsw4316** [comment]
nope, I use the 0.7 version. But I tried to uninstall the 0.49 forge and install the 0.61 forge instead and the result was the same. Hope the newest version of the modpack will help.

**Comment by michaelhsw4316** [comment]
Also, I tried to create a new 1.16.1 game and install the 0.61 forge and then drag the 68 mods in the mods folder in the new game and the result was the same. But the game without the mods can start correctly. So maybe the problem is in the mods, I think.

**Comment by michaelhsw4316** [comment]
btw, I will try the newest version now, and see if that will help.

**Comment by michaelhsw4316** [comment]
oh, the newest version works. Thanks!
