### ISSUE TITLE
Work around Ice and Fire / Rats memory leak

### ISSUE THREAD

**Issue by ViRb3** [AllTheMods/ATM-6#300]
The underlying library used by Ice and Fire and Rats, Citadel, has a problem where it never releases entity data, slowly eating up all your RAM until the game crashes. Tracked here: https://github.com/Alex-the-666/Citadel/issues/12

To work that around, as suggested by the author himself, the config must be changed to `false`:

https://github.com/AllTheMods/ATM-6/blob/41ed8f44a38606bb6c7a357f70c30d14dd465023/config/citadel-common.toml#L2-L4

Please make this change in the next update.

**Comment by NetMasterFlex** [comment]
What version does this currently apply to.  Is the fix to be applied to the server or client or both?

**Comment by ViRb3** [comment]
Citadel is unfortunately close-sourced so I cannot verify if the issue has been patched. I was in talks with the developer 4 days ago and as of then he was aware of the bug but gave no ETA on fixing it. It should be a server-only config change, but I haven't verified whether it prevents the memory leak if not on the client as well. I can verify tomorrow if you would like.

**Comment by NetMasterFlex** [comment]
ViRb3.  Please do test.  In the meantime I will make the adjustment on the server only.  Now are are talking talking the latest ATM6? 1.3.0 MC 1.16.4?

**Comment by ViRb3** [comment]
I can confirm that the memory leak is prevented by just changing the config on the server. You should still ship the config in the modpack though, on both client and server, so that 3rd-party servers don't have to change it by hand. And yes, ATM6 1.3.0 MC 1.16.4.

**Comment by NetMasterFlex** [comment]
Thanks for the update.  I have disabled on the server side.  Hopefully the mod makers here will apply your findings to future versions on the modpack.

**Comment by ViRb3** [comment]
Unfortunately, while the fix above seems to delay the memory leak, it does not seem to prevent it. After about 6 hours of gameplay, the game starts spiking again, and surely enough Citadel is taking almost 2GB of RAM. Only the dev can help now I'm afraid.

**Comment by ViRb3** [comment]
This seems to be patched in latest Citadel release, to be released in next ATM6 update. I still haven't verified it, so I will leave this issue open.

**Comment by ViRb3** [comment]
Still not tested, but assuming fixed.
