### ISSUE TITLE
[Bug]: not all honey types have recipe uses

### ISSUE THREAD

**Issue by Xthinfinii** [AllTheMods/ATM-6#3001]
### Possible Fixes

Yes

### Modpack Version

1.8.20

### What happened?

one of the honey variants have no recipes for a bucket of honey variant and no longer possible to automate/work with most resourceful bee tanks/honey congealer from what i can tell i think its the CoFH core honey

![honeyissues](https://user-images.githubusercontent.com/101881375/159025117-538a5985-7220-4bbc-9d7e-18d0020a8546.jpg)
    
seems like cross mod issues
also tried updating resourceful bees to get it to work (seems they changed tags/ids) as their was issue on resourceful bees 
new version doesn't seem to support its honey ether 

### latest.log

N/A

**Comment by jeremiahwinsley** [comment]
The thermal recipe has been changed to produce RBees honey instead of Thermal honey in 1.8.21, this should fix that specific issue.
