### ISSUE TITLE
[Question]: Env tech blacklist

### ISSUE THREAD

**Issue by bobothehobo2** [AllTheMods/ATM-6#3003]
### What would you like to know?

Has inert Crystal Ore been added to the blacklist?  I can't seem to get any now. I know I was able to mine it previously and nothing as far as I see has been added to the change logs (I may have missed it if so sorry).  For the future where is that file so I can just confirm without bothering anyone.  Thanks!

**Comment by jeremiahwinsley** [comment]
This is the closest thing to a blacklist for the void miner: https://github.com/AllTheMods/ATM-6/blob/master/kubejs/data/envirotech/envirotech/void_miner_drops/ore/starmetal.json

We don't have any configs like that for inert crystal ore.
