### ISSUE TITLE
Crash on Launch, newly downloaded (never launched)

### ISSUE THREAD

**Issue by AnkaraSoulreaver** [AllTheMods/ATM-6#3009]
Downloaded the pack today for a new modded experience.  On launch (MultiMC) I'm receiving multiple "failed to load mod" errors.  The only one clearly defined is Solar Flux Reborn but would not launch even removing this mod.  Thanks.

I would also note that the loading texture does not work and might be related.

[crash-2022-03-25_10.45.25-fml.txt](https://github.com/AllTheMods/ATM-6/files/8351536/crash-2022-03-25_10.45.25-fml.txt)
![Capture](https://user-images.githubusercontent.com/33983960/160144242-9f387b41-12f1-4586-be86-22c33c42632e.PNG)
![Capture2](https://user-images.githubusercontent.com/33983960/160165703-8c58e01a-c4e0-451c-8176-3be676534e8b.PNG)

**Comment by jeremiahwinsley** [comment]
Java 17 is not supported, use Java 8-15.

**Comment by AnkaraSoulreaver** [comment]
Oh, I updated java, but I guess I didn't realize MultiMC required me to manually select the correct version.  I feel silly.  Thanks, that fixed it.
