### ISSUE TITLE
Netherite Gear missing recipes

### ISSUE THREAD

**Issue by maccrushington** [AllTheMods/ATM-6#301]
As of the latest update, Netherite no longer can be crafted into gear, i.e. no pickaxe, armor, etc.  Which I guess means no Allthemodium unless you cheat something in.  It was working just fine a couple days ago, but after several game reboots and a fresh download of the mod pack to make sure I am not nuts, the recipes are gone.

**To Reproduce**
Attempt to craft any netherite gear or look it up in JEI and you come up with nothing.  Also cannot use netherite as a component in Silent Gear items.

**Expected behavior**
I would expect standard vanilla recipes to work.

Thanks!

**Comment by GamerXD8991** [comment]
netherite was never an option as component for silent gears. It's listed as coating not as material.

reagarding the allthemodium gear. I'm not sure why you would need netherite for that. I have the option to use the default armor pieces recepie and the one with netherite. but this could also be a bug/remaining reciepe from older pack versions

**Comment by thevortex** [comment]
you have the option to create the modium chestplate using the netherite one as it allows you to transfer enchantments from one piece to the next, but it is not a required recipe, the additional recipe i wouldnt use unless you have a piece of armor you want upgraded but retain existing enchants

**Comment by NeoSono1981** [comment]
You complain about standard vanilla recipes not working but seem to have no idea how netherite gear is crafted in vanilla MC. You put diamond gear into the smithing table and combine it with netherite ingots which still works fine in the latest modpack version in my game.

**Comment by WhitePhant0m** [comment]
Use JEI....
