### ISSUE TITLE
[Bug]: World Generation bugged with Terraforged and Lost Cities

### ISSUE THREAD

**Issue by Aloore** [AllTheMods/ATM-6#3015]
### Possible Fixes

Yes

### Modpack Version

1.8.21

### What happened?

![image](https://user-images.githubusercontent.com/50784891/160485830-0710c232-2d4b-4180-8970-909c2c2205a2.png)
The terrain seems to be bugged, using the rare cities preset of lost cities. Using version 1.8.22 of the modpack, only adding a few performance mods (magnesium, sulfuric, ai improvements, out of sight, starlight) that should not affect world generation.

### latest.log

https://gist.github.com/Aloore/075eeab45335960bed9dad477630a915.js

**Comment by jeremiahwinsley** [comment]
Yes, the lost cities preset isn't compatible with Terraforged. We recommend just using the Lost Cities dimension instead, or default instead of Terraforged if you really want cities in the overworld.
