### ISSUE TITLE
[Bug]: two different types of Uranium Slurry clogging the Crystallizers after server reboots etc.

### ISSUE THREAD

**Issue by 0rbiter** [AllTheMods/ATM-6#3019]
### Possible Fixes

No

### Modpack Version

1.8.20

### What happened?

After server reboots/crashes etc. (not sure exactly - our servers reboot every 3 hours) the Crystallizers stop working. They are usually filled up with less than 200mb of Clean Uranium Slurry of 1 of two different types. One is from the Mekanism Mod and dark green, the other one if from the ATM modpack and bright.
Therefore the Chemical Washers in front are unable to input more Clean Uranium Slurry for the recipe (200mb needed).

After using two different gauge droppers (machines have one of the two mentioned inside) on the Crystallizers they start working again.

I'm not using any conduits - the Clean Uranium slurry is dumped directly from the Washer to the Crystallizer.

This only seems to affect Uranium since I isolated the quadrupling of Uranium I haven't had any problems with other ores.
![2022-04-01_09 13 56](https://user-images.githubusercontent.com/12478292/161214551-1e4d21d9-3320-4893-a4ab-1288bf06d406.png)
![2022-04-01_09 16 42](https://user-images.githubusercontent.com/12478292/161214553-8a397747-81a9-4265-8255-5c620e4b14cb.png)

### latest.log

https://gist.github.com/0rbiter/f45ac11c856c79709c289f958b8df6b1

**Comment by 0rbiter** [comment]
A bit of an update here: using XNet Controllers to limit the injection into the Crystallizers to 200millibuckets seems to be a workaround for the problem

**Comment by jeremiahwinsley** [comment]
Fixed in 1.8.23.
