### ISSUE TITLE
maessentials.toml still in config even though the mod was removed

### ISSUE THREAD

**Issue by razgriz5000** [AllTheMods/ATM-6#302]
Skimming through the configs after a new install it still has maessentials.toml in the config folder.

**Comment by Revvilo** [comment]
This is just kinda a side effect of how packs are distributed. The system that exports the pack for end-users can't really tell which config files should, or shouldn't be included, so it just does the whole config folder.

If one launches the pack with no configs at all and lets them generate, attempting to merge the original config folder into that newly generated config folder will only allow the redundant ones to be moved, as they were not generated, thus leaving a (theoretically) up to date version of the packs current configs. The question is, is it worth the effort xD
