### ISSUE TITLE
Allthemodium tier materials available from the beginning of the game[Bug]: 

### ISSUE THREAD

**Issue by DiamondMasterPl** [AllTheMods/ATM-6#3022]
### Possible Fixes

Yes

### Modpack Version

1.8.21

### What happened?

well, in the freshest build, flint sieve can get allthemodium from gravel, as well as other resources from other crushed materials, and i dont think this is supposed to happen

### latest.log

https://gist.github.com/DiamondMasterPl/fa9ab11f836754deed73ea2bc1ebe6b2

**Comment by jeremiahwinsley** [comment]
ATM6 doesn't have a sieve, maybe you meant to post this here? https://github.com/AllTheMods/atm6-sky/issues

**Comment by DiamondMasterPl** [comment]
oh yeah, im st00pid
