### ISSUE TITLE
[Bug]: Ice Dragon Baby Duplication

### ISSUE THREAD

**Issue by Tree4Free** [AllTheMods/ATM-6#3023]
### Possible Fixes

Yes

### Modpack Version

1.8.21

### What happened?

When using a Time in a bottle on an ice dragon egg tons of baby dragons spawn from the single egg.
I used the Sapphire version of the ice dragon egg but this bug probably happens with all of them.

![2022-04-05_21 25 35](https://user-images.githubusercontent.com/9843834/161854229-a7fc2e0f-517b-4181-95a3-3bdbd43b5283.png)

![2022-04-05_21 25 39](https://user-images.githubusercontent.com/9843834/161854242-563a46d4-19ad-429d-ab2c-b8f51c5a8e73.png)

Tested on Version 1.8.20 & 1.8.22

### latest.log

https://gist.github.com/Tree4Free/e4b95da28f4561db62251c61b7bdff42

**Comment by jeremiahwinsley** [comment]
This is a known issue, but there's currently nothing we can do about it. Ice and Fire would have to fix this on their end.
