### ISSUE TITLE
[Feature]: Creative Blood Magic Rune/Altar

### ISSUE THREAD

**Issue by zerogtyson** [AllTheMods/ATM-6#3024]
### Feature Details

I was looking for more things to do with the ATM star and since I've gotten to the end of the pack. After getting it and making it a couple more times I found it was kind of underwhelming considering I have basically infinite power already. 

I was thinking something along the lines of a creative blood altar/ rune stone that can have infinite LP and very fast or near instant processing speed. Maybe the processing speed isn't such a big deal but an ATM star with blood magic would be awesome considering we have creative stuff for the other magic mods. Would be a very nice addition to the mix if it's possible.

**Comment by jeremiahwinsley** [comment]
Our creative item recipes are for existing items in the mod - unfortunately, Blood Magic doesn't have a creative item like this. So we don't really have a way to do this.
