### ISSUE TITLE
[Bug]: Mekanism Cardboxes deletes Crafting Pattern at the Creative Crafter

### ISSUE THREAD

**Issue by Blutstein** [AllTheMods/ATM-6#3029]
### Possible Fixes

Yes

### Modpack Version

1.8.22

### What happened?

To move my Creative Crafters, i put them in a Cardbox from Mekanism with all Crafting Patterns stored at them. After replacing the Crafters wont Connect to the System without breaking and replacing. Additionally all the stored Patterns are vanished.

Fix: Ether make the storage with the Cardbox moveable or put it on the Blacklist.

### latest.log

https://gist.github.com/Blutstein/bdff820e3aaa91a06daa81cc68b71593

**Comment by starforcraft** [comment]
https://www.curseforge.com/minecraft/mc-mods/creative-crafter/files/3753665

**Comment by jeremiahwinsley** [comment]
Fixed in 1.8.23.
