### ISSUE TITLE
[Bug]: Lead Ore Tag Made in mekanism Combiner

### ISSUE THREAD

**Issue by ZandorSabino** [AllTheMods/ATM-6#3031]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

When processing the lead ore in the mekanism's machines and using the combiner to generate the ore again it comes with the makanism tag and not AlltheMods which hinders filtering.

Possible solution check if the combiner recipes are returning the correct tag.

### latest.log

nolog

**Comment by jeremiahwinsley** [comment]
Fixed in 1.8.23.
