### ISSUE TITLE
[Bug]: ice and fire

### ISSUE THREAD

**Issue by momococoa** [AllTheMods/ATM-6#3034]
### What would you like to know?

ice and fire：　I have never seen a dragon. There is no nest. I saw only a mermaid in the twilight forest.

**Comment by thevortex** [comment]
dragons are located in the other, there are 3 biomes you need to search in, they are not located in the twilight forest

**Comment by thevortex** [comment]
fire dragons are in the other basalt deltas, 
lightning dragons are in the other deserts and desert hills,
ice dragons are in the other mountains

**Comment by momococoa** [comment]
The probability seems very low😭

Thank you for letting me know!
I'll look for it.
