### ISSUE TITLE
[Bug]: MineColonies Composter cannot use Wheat or Carrots

### ISSUE THREAD

**Issue by nessthehero** [AllTheMods/ATM-6#3036]
### Possible Fixes

Yes

### Modpack Version

1.8.22

### What happened?

I built a Composter's Hut from MineColonies, which can use organic items like crops, seeds, fish, saplings, etc. to create Compost.

However, Wheat and Carrots are not in the list of Items to Compost. Even reducing the list with the search functionality produces nothing.

![image](https://user-images.githubusercontent.com/216666/163145559-6267e608-b417-4594-a08d-8c5bb613e1f3.png)

![image](https://user-images.githubusercontent.com/216666/163145953-2077005f-8d7e-4c94-9fb6-472e465e2c47.png)

![image](https://user-images.githubusercontent.com/216666/163145986-f6876bf3-e7fb-40b5-8a7e-a558cfd6fba2.png)

Posting on MineColonies' Discord, these items should be in the list, and their opinion is that something is affecting the tags of those items so that they don't appear in the list.

### latest.log

https://gist.github.com/nessthehero/4617aee5aad979e3e80a8ba23a63dc93

**Comment by jeremiahwinsley** [comment]
Fixed in 1.8.24.
