### ISSUE TITLE
[Bug]: Infinite loading screen again

### ISSUE THREAD

**Issue by EnzinhoGameplays** [AllTheMods/ATM-6#3037]
### Possible Fixes

Yes

### Modpack Version

1.8.22

### What happened?

(I'm using Google Translate, sorry for the english)
Hi! last week the same bug occurred to me as everyone who enters ATM6 the loading screen does not end and when I move the mouse the game crashes.
They responded and resolved it. The ServerConfig had corrupted and I just had to delete the folder and open the world for the folder to regenerate, but today the infinite loading screen happened again and practically the same crash report.
The solution that had worked before ended up not solving it and I would like to know what happened, how to solve it and how to prevent it from happening again.

Below crash files and world folder:

https://drive.google.com/file/d/1Hsf3Z_HRrAidvjFphkcD9pazfcrJaUU8/view?usp=sharing, https://drive.google.com/file/d/1hBgxxsX9zQhe9ctSv8ULmBusirAbjw1E/view?usp=sharing

https://drive.google.com/drive/folders/1lfJRa9ZmQeV1Tz8hpQY15_46WzPIScsT?usp=sharing

### latest.log

https://gist.github.com/EnzinhoGameplays/

**Comment by radiomike** [comment]
Looks like it's a config for mekanism in the `config` folder. It's probably simplest to do a fresh install of the pack into a new instance/profile and copy your world etc to the new one. See https://github.com/AllTheMods/ATM-6/wiki/Pack-Upgrade-FAQ for what to copy.
As far as what causes it, game crashes and bad shutdowns are probably most common. Things like 3rd party antivirus and file synchronisation tools and anything else that might access those folders while the game is running can also cause this. It's also possible that things like background windows updates could cause this.
