### ISSUE TITLE
Not spawning of any Oh The Biomes You'll Go biome

### ISSUE THREAD

**Issue by Abstractpuppet** [AllTheMods/ATM-6#304]
Hello ! I don't think it really is a bug but it could be.

**Describe the bug**
After hours of wandering in my world, first of all in survival then in spectator mode, I noticed that i haven't found any OTBYG biome.

**Expected behavior**
That biomes from OTBYG exist

**Additional context**
 At first I thought it was because of the Biome O Plenty generation but I have a custom modpack (in 1.15.2) with the two mods and both mods work fine. 
We didn't updated to ATM6 1.16.4, our server is still in 1.16.3 with ATM6 Version 1.2.1. I just wanted to know if it was a bug from this version, or if it was the bad generation settings or anything else.

Thank you !

**Comment by ViRb3** [comment]
Biomes O Plenty does not support other worldgen mods on 1.16 but it does on 1.15. That's why you're seeing this behavior. For now, you have to choose either BYG or BOP, but not both.

**Comment by Abstractpuppet** [comment]
okay thank you !
