### ISSUE TITLE
[Crash]: Joining world with blank screen.

### ISSUE THREAD

**Issue by FooterMan14** [AllTheMods/ATM-6#3041]
### Possible Fixes

Yes

### Modpack Version

1.8.22

### What happened?

So I have several hours on a world (around 3) and the pack was going great, absolutely no issues at all. Then the next time I logged in and tried to enter my world, I would get the Reading World Data text, and then after that just a blank screen with nothing on it. I tried several things: Restarted my PC, used the curseforge repair, and allocating more RAM. I checked the latest log and at the bottom and it said it was some kind of server thread error with java.lang.IllegalStateException: No server set. And I checked it while the game was running, I went over to task manager and saw it was still using RAM, but with no response. That's my story. I put both the latest log and the crash report in the gist for ya.

### Crash Log

https://gist.github.com/FooterMan14/1c7843fb16ba2768e5fdd54bc4a1f27d

**Comment by radiomike** [comment]
Looks like one of your configs has become corrupted. In this case it's `[saves]/<world>/serverconfig/rangedpumps-server.toml`
Try deleting that and restart the game.

It's very possible that other configs are also faulty, in which case clearing `[saves]/<world>/serverconfig/`and letting it repopulate may fix it. Worst case, if configs in `configs` are faulty, you may be better installing the pack into a fresh instance/profle and copying your worlds over. See https://github.com/AllTheMods/ATM-6/wiki/Pack-Upgrade-FAQ for what you should copy.

**Comment by FooterMan14** [comment]
Thank you for the response. I have not edited any of the configs, so I'm not really sure how it happened. I will try what you have suggested.

**Comment by FooterMan14** [comment]
![image](https://user-images.githubusercontent.com/71946346/163622549-04e919f4-b752-4827-ab63-7c2fe8eab24a.png)
Unfortunately clearing the serverconfig folder did not fix the issue, I will just copy over my world to a new save.

**Comment by FooterMan14** [comment]
![2022-04-15_15 30 12](https://user-images.githubusercontent.com/71946346/163624051-2a7b684a-577d-48ec-ba37-6b410cdfdb2b.png)
Now loaded into a new instance, with everything working properly. Thank you for the assistance!

**Comment by FooterMan14** [comment]
Unfortunately I will re-open this real quick as I've found an issue with the port. After porting over the world I noticed that I lost my /home, /sethome, /rtp etc commands. Any idea on how to fix?

**Comment by radiomike** [comment]
Those are set in `[saves]/<world>/serverconfig/ftbessentials.snbt`. They were recently disabled by default in the configs, but you can easily re-enable them.

**Comment by FooterMan14** [comment]
Ah okay, thank you for the confirmation.
