### ISSUE TITLE
[Feature]: Edit Anvil Melting.

### ISSUE THREAD

**Issue by FooterMan14** [AllTheMods/ATM-6#3042]
### Feature Details

![image](https://user-images.githubusercontent.com/71946346/163624595-334ae6d9-123e-43ae-8544-901ca6d32b1a.png)
![image](https://user-images.githubusercontent.com/71946346/163624557-5cf21dca-b55b-43d8-aee6-ac0adda122ab.png)
I have found the vanilla Anvil in it's "chipped" or "damaged" form can be melted in a Tinker's smeltery for the same amount used to craft the anvil. I suggest either removing both melting recipes or nerfing them, to prevent infinite anvil use with a little bit of manual work.

**Comment by jeremiahwinsley** [comment]
I am not sure if Tinkers would consider this a bug, but this seems fine to me, actually. Iron is not really limited in any way, and we do have other ways of doing all anvil operations in a way that doesn't break, so if you can spend some manual effort to do the same thing with a vanilla anvil, it's not really unbalanced. Thanks for the report!
