### ISSUE TITLE
[1.3.0]Nether Biome in the overworld

### ISSUE THREAD

**Issue by galfalek** [AllTheMods/ATM-6#305]
**Describe the bug**
I got the undergrowth biome from the nether in my base, and it should not be possible. Previously it was an halloween biome (autumn something)

**To Reproduce**
1. Go to the atm6 server2 at -1272,68,607

**Expected behavior**
No nether biome in the overworld

**Screenshots**
![Hell](https://user-images.githubusercontent.com/2273236/98972398-ae5e8080-2512-11eb-89d4-3b384d83799c.png)

**Additional context**
I love to see so many ghast, but they are spawning at an incredible rate...

**Comment by GamerXD8991** [comment]
Probably the same issue as #227

**Comment by rasm685p** [comment]
@GamerXD8991 It's on the server official ATM server. Optifine shouldn't effect how the server generates the world.

**Comment by NetMasterFlex** [comment]
I experienced the same thing in the “Pumpkin” Biome. Probably not the correct name. That Biome is crawling with ender enemies at all levels.  I’m not too worried, but it is a little concerning if it’s not supposed to be happening. 

Had a crazy kill fest tonight while there. LOL. 

Also I agree that Optifine is a client side mod. Should have no bearing on how a world generates.  I’m not running Optifine and had the same issue. 

NMF

**Comment by kythorn** [comment]
+1, can confirm. Happened on update from 1.2.1 to both 1.3.0 and straight to 1.3.1.

No additional mods of any type added, completely stock pack.

**Comment by iarspider** [comment]
Happened to me as well

**Comment by ViRb3** [comment]
Please check #437 for a solution.
