### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by GOBBIN23** [AllTheMods/ATM-6#3052]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

i click launch on all the mods 6, i get a red page show up it then disappears and i get a crash report but i have no idea how to read the report or why its happening.
![Capture](https://user-images.githubusercontent.com/104189389/164617936-d521a2a8-29cb-4a49-8a7b-5ced13bcce96.PNG)
![rfth](https://user-images.githubusercontent.com/104189389/164617945-81b96e3b-a304-4719-bffc-8079124eee27.PNG)
.

### Crash Log

https://gist.github.com/GOBBIN23/245bd10ada763dae290a277bac3bca29

**Comment by radiomike** [comment]
You are trying to run the pack using java 18, which isn't compatible. You should use one of java 8-15. Java 11, is usually recommended as it's more performant than java 8 and an lts version. so still receivihttps://github.com/AllTheMods/ATM-6/wiki/Java-Versionsng bug and security updates.

See https://github.com/AllTheMods/ATM-6/wiki/Java-Versions for some download links
