### ISSUE TITLE
[Bug]: Ethereal Circlet does not prevent "damage" on the MekaSuit

### ISSUE THREAD

**Issue by Ashetf2** [AllTheMods/ATM-6#3062]
### Possible Fixes

Yes

### Modpack Version

1.8.23

### What happened?

The Ethereal Circlet from Cyclic, that prevents elytra crash damage, does not prevent MekaSuit to "absorb" the crash damage. However, this is not the case with the Angelic Feather from Reliquary, that prevents fall damage, and it doesn't make the MekaSuit to consume energy.

Proof: https://youtu.be/GZttXudYVCI

### latest.log

https://gist.github.com/Ashetf2/d0cdd4cbd6268f3825fd71783227ba70

**Comment by jeremiahwinsley** [comment]
This would be more of the mod developer's choice, rather than a bug. You could put in a suggestion to Cyclic if you think it should work differently.
