### ISSUE TITLE
[Question]/[Bug]: Is the conversion of quartz blocks back to regular quartz correct? (Duplicate recipe ID with chests)

### ISSUE THREAD

**Issue by sharris40** [AllTheMods/ATM-6#3065]
### What would you like to know?

I noticed that at kubejs/server_scripts/mod_specific/_minecraft/minecraft.js line 14, there is a recipe for converting quartz blocks back into quartz without anything extra, but that recipe ID was accidentally copied into the next recipe (for converting any chest into a vanilla chest) on line 15. The chest recipe therefore replaces the quartz recipe. While the chest recipe ID should certainly be changed, is the quartz recipe supposed to exist, or should it be removed?

**Comment by jeremiahwinsley** [comment]
Removed in 1.8.24 and recipe ID fixed.
