### ISSUE TITLE
[Bug]: Mining dimension pad duping

### ISSUE THREAD

**Issue by MathiasMelk** [AllTheMods/ATM-6#3066]
### Possible Fixes

Yes

### Modpack Version

1.8.23

### What happened?

When you get in the mining dimension, break the pad, dig down, place the pad, go back do overworld, go back to mining dimension, you will be placed in the original position, with a new pad beneath your feet while the original pad stays where you placed it.

### latest.log

https://gist.github.com/MathiasMelk/9f3720bde6b6a3a033541ca6d2d663a1

**Comment by jeremiahwinsley** [comment]
This is a known issue, but has a fairly limited impact, and there is not really a good way of fixing it without introducing other issues.
