### ISSUE TITLE
Mekanism Personal Chest gives xp when broken.

### ISSUE THREAD

**Issue by Beano8U** [AllTheMods/ATM-6#307]
I have a netherite pick that happens to have Experience Boost 1, silk touch, unbreaking IV and Efficiency IV on it.
It may seem the EB1 may be causing the xp to drop but I only get the xp if I break the chest right after it was placed on the ground (within 10 secs maybe?) If it has been placed for maybe more than 10 sec I get no xp from it.
Not sure if it's a bug or not?
Seems I can repeat the results.

It also seems to give xp if the chest is broken right after it has been interacted with.
It contains some spawners, enchanted books/gear, various mob drops, a Mekanism jet pack, a waystone and various random stuff.

**Comment by WhitePhant0m** [comment]
Experience boost enchant basically makes everything give xp when broken
