### ISSUE TITLE
Having a problem with Modular Routers and FTB chunks

### ISSUE THREAD

**Issue by ThornyPickled** [AllTheMods/ATM-6#3078]
so two chunks side to side. Started a farm with modular routers for inferium, worked like a charm.
later on I claimed all the chunks of my base to force load for wireless rf.
later on tried to place modular routers inside an adjacent chunk... they dont work.
tried every way i could think of to invite modular routers to my ftbteam, still not working.\
other chunk still farming away just fine.

What is going on. why wont these new ones work.

**Comment by ThornyPickled** [comment]
It seems like any time I've played a modpack with FTB, there's been issues

**Comment by jeremiahwinsley** [comment]
Do you have fake players enabled in your FTB Chunks config? You don't invite them anymore, all fake players are either allowed (default) or not allowed.

**Comment by TronWoWGamer** [comment]
I know this is an old thread, but I am playing ATM8 and I have Fake Players set to allow in my FTB Chunks config for server config and I still cannot get modular routers to right click a botania runic altar with a wand of the forest using an activator module.  I had it working at one time and then a pack update broke it again.

**Comment by DerSkilly** [comment]
If you are the Serveradmin just use this command
/ftbteams party settings_for (Team_of_yours) ftbchunks:allow_fake_players true

fake players are not allowed by default
