### ISSUE TITLE
[Crash]: Using any Cable Tiers Disk Manipulators (ATM6 - 1.8.24)

### ISSUE THREAD

**Issue by SaltyHikari** [AllTheMods/ATM-6#3081]
### Possible Fixes

Yes

### Modpack Version

1.8.23

### What happened?

Crafting and placing the Disk Manipulators from Cable Tiers is possible but when you right click it, the Server and also client crashes.
both newest version from curseforge (ATM6 - 1.8.24)

### Crash Log

https://gist.github.com/SaltyHikari/5e2887428b7d79230661c9b1f5e02f4d

**Comment by starforcraft** [comment]
Update Cable Tiers mod for now but it will be fixed in the next ATM 6 Version

**Comment by jeremiahwinsley** [comment]
Mod has been updated in 1.8.25.
