### ISSUE TITLE
[Problem] Can't join my friend's personal server. "mismatched mod channel list"  [CLOSED CASE]

### ISSUE THREAD

**Issue by MEathy** [AllTheMods/ATM-6#3083]
### Possible Fixes

Yes

### Modpack Version

ATM 6
v1.8.24

### What happened?

**Atm 6 v1.8.24**
*I am currently using Overwolf with the curseforge app to play ATM 6*
**This may perhaps be an issue with curseforge app itself.**
The problem is that I can't join my friend's personal ATM 6 server.
The server list displays a red X by the server name, but If I try to join the server it say's this.

"Connection closed - mismatched mod channel list"
i.e: Means that server and client-side mods don't match each other.

I've reinstalled ATM 6 multiple times, I have reinstalled Overwolf with Curseforge app already, and I have deleted literally every related file, including backups, for me to then install everything again...
And the same red X will appear, no matter how many times I reinstall it.

FYI:
This issue is very recent, as I have joined this server countless time's and only now this problem is appearing, I don't believe the problem is complicated, more that I may have missed something crucial here.

If You have a question, just leave a comment here.

_Appreciations fellow humans!_

### Crash Log

Not applicable
![2022-05-16 - ATM 6{Server connect fail}](https://user-images.githubusercontent.com/105684174/168708037-4eb0c400-34e6-430e-92b0-01ad54d3fde9.png)
![2022-05-16_19 29 04](https://user-images.githubusercontent.com/105684174/168708997-92235dd2-d961-4e52-948c-dad8f9f6b737.png)
.

**Comment by MEathy** [comment]
Please god, someone help, its been 7 hours and it still dont work ;-;

**Comment by diogocorreia432** [comment]
Server modpack version is probably different than yours. You are on 1.8.24 and the server probably is on 1.8.23 or something like that.. Try using another version

**Comment by MEathy** [comment]
`Alright`.
I checked, and the server was running 1.8.24, the latest version.

So I started my game, but with v1.8.23 instead of the normal 1.8.24, and welp, still had the red X :/

Thanks for the suggestion though.

**Comment by MEathy** [comment]
THE FRACK< TY SIR 


apparently my friends server was 1.8.23 lol

**Comment by MEathy** [comment]
How do I close a bug report?

**Comment by MEathy** [comment]
ALL I HAD TO DO WAS CHANGE ONE SETTING??
![download](https://user-images.githubusercontent.com/105684174/168932272-5c7bd5e4-8856-4d44-9ebd-442b0247ea18.jpg)
?
