### ISSUE TITLE
[Bug]: Charcoal dupe with Chisel (upstream bug)

### ISSUE THREAD

**Issue by sharris40** [AllTheMods/ATM-6#3086]
### Possible Fixes

Yes

### Modpack Version

1.8.24

### What happened?

Charcoal can be duplicated by the following method:

1. Craft a charcoal by itself to get a Chisel raw charcoal block
2. Use a chisel to convert the raw charcoal to Thermal charcoal
3. Craft the Thermal charcoal by itself to get 9 charcoal

This is a bug with the Chisel recipe. It's fixed in the 1.18 branch, but it hasn't been backported yet. In any case, the Chisel recipe should probably be removed.

### latest.log

N/A

**Comment by jeremiahwinsley** [comment]
Fixed in 1.8.25.
