### ISSUE TITLE
[Crash]: Invalid Java Runtime Configuration Exit Code: 1 

### ISSUE THREAD

**Issue by froggyhognut** [AllTheMods/ATM-6#3087]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

This image is what I see anytime I attempt to run this mod pack through curseforge and open the launcher that way. I am not the most tech-savvy but I was able to go into Configure Java and see that the runtime is in fact how it needs to be based on other sources online. I have uninstalled the launcher and reinstalled it through curseforge as I had seem that recomended and that did not work either. I just would like for my mods to work and will take any help. 
![unknown](https://user-images.githubusercontent.com/105968219/169643167-48a26d2a-0bd0-40e0-847e-a5113c23eec1.png)
a

### Crash Log

https://gist.github.com/froggyhognut/e4e4bf3daab76af0cced36ca8702e1e4

**Comment by TinyPandas** [comment]
I would recommend checking out this [link](https://github.com/AllTheMods/ATM-6/wiki/Java-Versions), and making sure you have the appropriate version of Java for the associated version of Minecraft!

1.16.5 and lower: Java 8 or Java 11
1.17: Java 16+
1.18+: Java 17

Once you have installed the correct version, in your profile settings you can change the version of Java that is used when launching that profile.
