### ISSUE TITLE
[Bug]: Dragon Alloy Metals Recipe bugs

### ISSUE THREAD

**Issue by LalaithN** [AllTheMods/ATM-6#3088]
### Possible Fixes

Yes

### Modpack Version

1.8.24

### What happened?

Previous update (`1.8.23`) the Alloy metals: 
![image](https://user-images.githubusercontent.com/105981603/169657719-cc535771-e548-4024-aba2-12bb7132e212.png)
`Unobtanium - Allthemodium` 
`Ubobtainium - Vibranium` 
`Vibranium - Allthemodium` 

could be smelted by their respective dragon forge and dragon from the dust of the metals. This was tested in single player.

Upon updating to `1.8.24` and starting a server. These recipes simply produce ash or dragon ice.
However, now using ingots seems to work? 

Though it also appears the type of dragon used no longer matters. I just tested this by using my ice dragon on my lightning dragon and fire dragon forge and it did smelt the alloys for those (again, using ingots). I have not tried to see if you can make all alloys in 1 forge, regardless of type. Though this would be interesting to test.

Is this intended behavior?

When looking in JEI for how to craft these, the recipes are also missing from there. Unfortunately it does not appear that it is reporting anything in the logs, but I'll add them anyway.

### latest.log

https://gist.github.com/LalaithN/13c0d2f6d796dc1340f967b64be471e2

**Comment by jeremiahwinsley** [comment]
The recipes do not show up in JEI on servers due to a bug in I&F, but the dust recipes should still work fine. You can see them here: <https://github.com/AllTheMods/ATM-6/wiki/General-Gameplay-Guides>

It does need to be in a specific order - will be looking into making them work both directions

**Comment by jeremiahwinsley** [comment]
1.8.25 adds reversed recipes for all alloys, including dusts, ingots, and blocks.
