### ISSUE TITLE
[Bug]: Constant freezing every 7-8 seconds

### ISSUE THREAD

**Issue by tricii3rz** [AllTheMods/ATM-6#3089]
### Possible Fixes

Yes

### Modpack Version

1.8.24

### What happened?

I played on a server with my friend and the framerate was fine at like the first 7-8 hours. But then the game just started to freeze every 7-8 seconds for like 5-6 seconds and was like timed. I checked the MEM usage in f3 and saw that it slowly climbed up to 98% and then froze and just started over again. Have also tested with and without optifine

I have and i5 6500, RTX 3060, 24gb of ram, game installed on an ssd

### latest.log

https://gist.github.com/tricii3rz/460550ff794239135bf32341639932c6

**Comment by jeremiahwinsley** [comment]
After 7-8 hours that's pretty much to be expected - there are slow memory leaks present in the pack, you just have to restart when that happens.

**Comment by TinyPandas** [comment]
I can recommend using the following JVM args, as I was experience the same issues. The issues have either gone away completely, or are so minimal I do not notice them anymore, and my play sessions last anywhere from 12 - 16 hours.

`
-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=32M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true
`

**Comment by Cxjhg** [comment]
This happens to me but only after just 20-30 minutes of gameplay
