### ISSUE TITLE
[Crash]: Crash With Refined storage Export bus on mek

### ISSUE THREAD

**Issue by Vinney88** [AllTheMods/ATM-6#3097]
### Possible Fixes

no

### Modpack Version

1.8.24

### What happened?

i put a Ultra export on a mekanism crusher and crash the server and now the chunk is missing 
![2022-06-01_15 24 36](https://user-images.githubusercontent.com/106200928/171512029-49b021e9-d360-4c0c-8d49-ee8acfad8432.png)
 

### Crash Log

https://gist.github.com/Vinney88/ff3e87eef112b1be5cf47fae96cbb40e

**Comment by jeremiahwinsley** [comment]
You can try updating to 1.8.25, or just updating the cable tiers mod. I believe a similar issue was fixed already, not sure about this specific one.

**Comment by Vinney88** [comment]
what when did 1.8.25 came out

**Comment by TinyPandas** [comment]
Cannot reproduce in 1.8.25.
