### ISSUE TITLE
Rats Mod Breaks End Dimension Biome Generation

### ISSUE THREAD

**Issue by moolchand-danny** [AllTheMods/ATM-6#31]
I loaded up my world today and decided to go to the outer End Islands to explore. I had previously been to the end dimension to defeat the ender dragon, never went to the outer island before. When I defeated the ender dragon, I was running ATM v.6.0.20. Today, I downloaded and updated to ATM v.6.0.22. 

The Rats ghostly pirate ship structure spawns repeatedly with multiple structures overlapping each other. The biome is listed as the Ratlantis biome. You can see both of these in the screenshots I provided.

If you need any more information let me know. 
![2020-07-31_02 19 48](https://user-images.githubusercontent.com/42704944/88993293-84f74d00-d2b3-11ea-84a6-8ac18c251eaf.png)
![2020-07-31_02 19 58](https://user-images.githubusercontent.com/42704944/88993298-8759a700-d2b3-11ea-8af0-420307474659.png)

**Comment by oly2o6** [comment]
as far as i know this issue has been fixed, if not please report this to the rats github so that it can be solved
