### ISSUE TITLE
Im not sure if the Robit recipe was removed for the Digital Miner?

### ISSUE THREAD

**Issue by RockyRoads666** [AllTheMods/ATM-6#3103]
### What would you like to know?

I wanted to make a Digital Miner in my server but I realized that I couldn't craft it because of the Robit. I looked at the changelog and there was nothing about the Robit being removed. Was this intentional?

**Comment by tgrkzus** [comment]
Was just looking this up and found this.
On the ATM6 discord: https://discord.com/channels/254530689225981953/726665656854118481/982335095035809832

> ah, I see the issue, I removed the custom robit recipe but didn't re-enable the default one :hmmm:
you can remove this line: https://github.com/AllTheMods/ATM-6/blob/8e63854b21d92f566ed16f24bf5cba50b7fcf788/kubejs/server_scripts/mod_specific/mekanism/mekanism.js#L107 and /reload if you are in single player or have server access

So seems unintentional.

**Comment by RockyRoads666** [comment]
I removed the line. It worked on Singleplayer but not on my Server. The
Server is on Aternos.

Am So., 5. Juni 2022 um 02:35 Uhr schrieb Tom Richardson <
***@***.***>:

**Comment by TheNameIsRobin** [comment]
@RockyRoads666 Well you're f'd then, because Aternos loads it's files from a central storage where they all have the default configs like the modpacks are released (with maybe minor tweaks made, but probably not). They don't allow you to change server side configs on that level...

**Comment by Mitchell5200** [comment]
ATM6 version 1.8.27 fixes this issue

**Comment by ninko76** [comment]
How do I update the mod pack in my server. I'm hosting it locally
