### ISSUE TITLE
[Bug]: Growth enchantment can be stacked to grow seeds in seconds.

### ISSUE THREAD

**Issue by Uraxys** [AllTheMods/ATM-6#3104]
### Possible Fixes

Yes

### Modpack Version

1.8.26

### What happened?

The growth enchantment speeds up growth for every seed within 8 blocks, this also works if you put the item on an armor stand, this can then be stacked to grow unobtainium on dirt in seconds or any other crop of your liking.

To bypass the durability usage of the growth enchantment just add the Indestructible enchantment and then the growth enchantment lasts forever.

Example: https://gyazo.com/915d8b6d855c9c65a98e0b0be624af36

### latest.log

None

**Comment by jeremiahwinsley** [comment]
This has been disabled in 1.8.27.
