### ISSUE TITLE
[Bug]: Mekanism steel dust is replaced by steel grit

### ISSUE THREAD

**Issue by potpie123** [AllTheMods/ATM-6#3109]
### Possible Fixes

Yes

### Modpack Version

1.8.26

### What happened?

I tried to automate steel but in the jei steel dust can only be smelt in an arc furnace or tinkers construct foundry and smeltery.
![image](https://user-images.githubusercontent.com/73724870/173705523-748966a4-5189-4126-9a4d-8e8a9e985eb5.png)

### latest.log

s

**Comment by jeremiahwinsley** [comment]
That looks like you are on 1.8.25, because 1.8.26 was a hotfix for that issue.
