### ISSUE TITLE
Crops and trees wont grow offline

### ISSUE THREAD

**Issue by Epicbaconflips** [AllTheMods/ATM-6#311]
I have a crop farm and a tree farm, both in chunk loaded areas. However, each time I log off, they stop growing. I have to be in the area for any trees or crops to grow. Is this intentional or did I miss a setting somewhere? Thank you in advance for any guidance. I am running ATM6 version 1.3.0.

Sincerely,
EBF

**Comment by DeathOfTime** [comment]
FTB chunks doesn't do random ticks. All other chunk loading is disabled. I've heard that FTB Chunks will be adding a setting for random ticks. not sure it has made it in yet. Without those ticks things just won't grow unless you are nearby. The different types of growth accelerators will mitigate this

**Comment by Epicbaconflips** [comment]
> FTB chunks doesn't do random ticks. All other chunk loading is disabled. I've heard that FTB Chunks will be adding a setting for random ticks. not sure it has made it in yet. Without those ticks things just won't grow unless you are nearby. The different types of growth accelerators will mitigate this

Thanks for that workaround and information. I greatly appreciated and it makes sense. At first I thought it was something I wasn't doing right, nice to know it's intentional lol. Thank you again!
