### ISSUE TITLE
[Crash]: Won't load the world

### ISSUE THREAD

**Issue by RaijinNarukami** [AllTheMods/ATM-6#3110]
### Possible Fixes

Yes

### Modpack Version

1.8.26

### What happened?

I made a new world just starting the game no previous worlds and the world doesn't load and it crashes the game.

### Crash Log

-805306369

**Comment by jeremiahwinsley** [comment]
That exit code most likely means you are out of memory. You need to assign 8gb minimum for this pack
![2021-04-07 11_01_28-](https://user-images.githubusercontent.com/7946299/174926423-f85bbfc6-a6a5-43e5-b71f-067e7c1da868.png)
.

**Comment by RaijinNarukami** [comment]
> That exit code most likely means you are out of memory. You need to assign 8gb minimum for this pack ![2021-04-07 11_01_28-](https://user-images.githubusercontent.com/7946299/174926423-f85bbfc6-a6a5-43e5-b71f-067e7c1da868.png) .

I've done that but it didn't work
