### ISSUE TITLE
[Crash]: Crashes on "Loading Terrain" or "Joining World"

### ISSUE THREAD

**Issue by callmebigpasta** [AllTheMods/ATM-6#3111]
### Possible Fixes

Yes

### Modpack Version

1.8.26

### What happened?

When trying to join any multiplayer server, I consistently crash when the screen reaches "Joining World" or "Loading Terrain". I figured it was a rendering problem so I turned my render distance down to 3 but it didn't help. I checked a server's discord and it does show that I'm joining the server, but I just can't see it on my game's screen.

### Crash Log

https://gist.github.com/callmebigpasta/d70c215771cd56a22816e19c3ce32962

**Comment by jeremiahwinsley** [comment]
I think we helped you in Discord already, but if not, you need to assign more RAM.
