### ISSUE TITLE
[Bug]: XP level displays as 0 when using Allthemodium Teleport Pad

### ISSUE THREAD

**Issue by SedentaryMover** [AllTheMods/ATM-6#3118]
### Possible Fixes

Yes

### Modpack Version

1.8.27

### What happened?

When using the Teleport pad to travel between the Overworld and Mining Dimension, my XP bar displays 0 and functions as such until updating the value. This means that enchanting or renaming gear is impossible until I gain or lose any amount of XP.

### latest.log

https://gist.github.com/SedentaryMover/10ad1fa374f118e3299233ff1470a9bc

**Comment by jeremiahwinsley** [comment]
This is a vanilla bug, not really anything we can do to fix it.
