### ISSUE TITLE
[Crash]: Newest version of Ice and Fire Crashes On New World

### ISSUE THREAD

**Issue by oliverrook** [AllTheMods/ATM-6#3119]
### Possible Fixes

Yes

### Modpack Version

1.8.27

### What happened?

After updating Ice and Fire to the latest version (uploaded 3 days ago), the game now crashes when trying to make a new world.

### Crash Log

https://gist.github.com/oliverrook/3853cc62678e6f3f3a23f29bc2108e6e#file-2022-07-04-1-log

**Comment by thevortex** [comment]
it is not advisable to update ice and fire yet, wait for the pack to update
