### ISSUE TITLE
I cant open ATM6 

### ISSUE THREAD

**Issue by AlazTheKing** [AllTheMods/ATM-6#312]
I installed it on gdlauncher using twitch

![Adsız](https://user-images.githubusercontent.com/74427222/99107879-94e33480-25f7-11eb-8239-9f96fd796897.png)
[crash-2020-11-13_17.01.39-fml.txt](https://github.com/AllTheMods/ATM-6/files/5538698/crash-2020-11-13_17.01.39-fml.txt)

**Comment by NetMasterFlex** [comment]
For ATM6 I would avoid twitch altogether.  Preferred launcher personally per I've had the best success on both Windows and Mac would be Multi-MC.  The key is specifying a max of 8GB of RAM when first setting up Multi-MC.  Next you need to manually download the Client modpack file for the version you want to run.  When you create a new "Instance" you select import, then direct Multi-MC to the modpack file and the rest should be straight forward.

Sorry, but I can't help you with the GD Launcher/Twitch combo.  I've been reading from several ATM6 sources not to use Twitch if you want to avoid situations like what you posted here.  Just my biased 2 cents.

NMF

**Comment by GamerXD8991** [comment]
has the pack "installation" path some wired chararcters? (as stated in the Extra Storage exeption) if not try to redownload the pack (backup your saves obviously)

**Comment by ViRb3** [comment]
Use MultiMC. Check https://github.com/AllTheMods/ATM-6/issues/339#issuecomment-733016121.
