### ISSUE TITLE
[Question]: Chat disabled

### ISSUE THREAD

**Issue by Soapie02** [AllTheMods/ATM-6#3120]
### What would you like to know?

I think I accidentally disabled chat for myself in my server and I don't know how to bring it back. Trying to open chat brings the message that it is unable to send message, and my chat is put to show in chat settings.

**Comment by Panundrum** [comment]
I am also having this issue when I hit both T or /

**Comment by jeremiahwinsley** [comment]
Microsoft FAQ has the following to say about this:

>If you are experiencing this issue, it is most likely caused by one of the following:
>
>- You have disabled online chat in your Xbox Privacy settings. Go there and ensure that "You can communicate outside of >Xbox Live with voice & text" is enabled.
>- You have hidden Chat in your chat settings, or disabled all chat except for commands. To fix this, go to "Options → Chat >Settings → Chat" and set it to "Shown".

**Comment by Panundrum** [comment]
It was neither of these things, I rebooted the server and my client and it
worked. First time run seems to lock chat out for each person that joins
after. They rebooted their client and it works again.
