### ISSUE TITLE
[Bug]: 2 different raw fish tags.

### ISSUE THREAD

**Issue by Gmoney2123** [AllTheMods/ATM-6#3125]
### Possible Fixes

Yes

### Modpack Version

1.8.27

### What happened?

I was searching through JEI for recipes using raw fish and discovered 2 different tags for fish from UpgradeAquatic and AquaCulture - these 2 mods use `forge:raw_fishes` while some recipes use forge:rawfish.

I suggest a unification if possible, I don't have much KubeJS (or JS period) experience otherwise I'd push a fix myself XP

### latest.log

no log available

**Comment by jeremiahwinsley** [comment]
Fixed in 1.8.28.
