### ISSUE TITLE
[Crash]: MacOS Fails to launch due to missing/misnamed files

### ISSUE THREAD

**Issue by jordanburnam** [AllTheMods/ATM-6#3126]
### Possible Fixes

Yes

### Modpack Version

1.8.27

### What happened?

Pressing play in the luancher causes it to quickly fail with the following error: 

"Failed to find Minecraft resource version 1.16.5-20210115.111550 at ~/Documents/curseforge/minecraft/Install/libraries/net/minecraft/client/1.16.5-20210115.111550/client-1.16.5-20210115.111550-extra.jar"

The folder ~/Documents/curseforge/minecraft/Install/libraries/net/minecraft/ does not exist. I even tried reinstalling but still that folder does not exist.

In the folder ~/Documents/curseforge/minecraft/Install/libraries/net are the following folders:
sf
java
jodah
md-5
minecraftforge
minecrell

### Crash Log

https://gist.github.com/jordanburnam/23c96abdec6d1cd3af99c24ec6e93875

**Comment by jeremiahwinsley** [comment]
You can try using the "Repair installation" option from the three dot menu in Curseforge - if that doesn't work, you may need to ask Curseforge for support or use an alternate launcher like PolyMC. We can't fix Curseforge issues.

**Comment by jordanburnam** [comment]
For the next person to have this issue, I fixed it by reinstalling curse forge and then have it install the mod pack. Seems to be a bug with curse forge not downloading all the packages and libraries.
