### ISSUE TITLE
Artifacts mimic apotheosis

### ISSUE THREAD

**Issue by Rwby2018** [AllTheMods/ATM-6#3127]
Add Artifacts mimic egg back to apotheosis spawn egg list and mob grinding utils mob swap

**Comment by jeremiahwinsley** [comment]
Disabled for balance reasons

**Comment by Rwby2018** [comment]
How do re-enable for solo purposes?

**Comment by jeremiahwinsley** [comment]
You can remove it from this line:
https://github.com/AllTheMods/ATM-6/blob/486aaf351ff89da8bac16759cc9800389c3c5335/kubejs/server_scripts/tags.js#L242

**Comment by Rwby2018** [comment]
How do i re-enable gorgon temple spawns?
