### ISSUE TITLE
Unable to open chests

### ISSUE THREAD

**Issue by Neddykun123** [AllTheMods/ATM-6#3128]
### Possible Fixes

Yes

### Modpack Version

1.8.27

### What happened?

I was casually playing everyday with some friends in my Home hosted server and till there it was all fine we were having a good time and everything was working good until today, i logged in and i could acess the Crafting Grid from Refined Storage mod, neither chests or barrels (wooden), all i could open was crafting tables, backpacks and Wooden Storage crates from Immersive Engineering mod, here's a screenshot.

![image](https://user-images.githubusercontent.com/59710981/180072191-a995c45c-976e-49d1-b6da-3cf83d5b70c1.png)

### latest.log

https://gist.github.com/Neddykun123/e173cdaf70a47dcec830b3cbd7d08c4c

**Comment by jeremiahwinsley** [comment]
Looks like your server is running in offline mode, we don't support pirated copies of Minecraft.
