### ISSUE TITLE
[Bug]: multiple "dragon scale" items without unified forge dictionary

### ISSUE THREAD

**Issue by derpendary** [AllTheMods/ATM-6#3130]
### Possible Fixes

Yes

### Modpack Version

1.8.27

### What happened?

There are multiple items in the pack with the name "dragon scale" that interfere with each other and each other's crafting recipes.

### latest.log

https://gist.github.com/derpendary/6fe821a78feb1e84b7d7b89ebd3b841c#file-gistfile1-txt

**Comment by jeremiahwinsley** [comment]
Yes, there are a bunch of different dragon scales, but the recipes don't really overlap at all. I don't see any issues with a quick look over the recipes.

**Comment by derpendary** [comment]
I can't use a dragon scale from one mod for a crafting recipe from another. Sorry if I didn't make that clear, I don't exactly know the terminology.

**Comment by jeremiahwinsley** [comment]
yes, that's what I meant - as far as I see, there aren't really any that would be reasonable to unify.

**Comment by derpendary** [comment]
I just double checked to make sure I'm on the newest version, and yeah. There's 3-4 different items titled "Dragon scales" and the ones I want can't be used for the recipe I want.

**Comment by jeremiahwinsley** [comment]
I still don't know what recipe or scale you're talking about. There are 4 mods that have them.
- Forbidden & Arcanus: not really anything to do with dragons besides the name, just a craftable item used for crafting stuff from that mod
- Ice and Fire: harvested from ice and fire dragons, used for stuff from that mod
- Mystical Agriculture: 8 scales per ender dragon kill, used for making dragon seeds
- Quark: 1 scale per ender dragon kill, used for duping elytra

So the only ones that even could be unified are Quark and Mystical Agriculture. And the drop rates mean that the only thing unifying would do is make duping elytras easier - which isn't something we want.
