### ISSUE TITLE
[Bug]: Wrong recipe for mana regeneration II potion 

### ISSUE THREAD

**Issue by denaillc** [AllTheMods/ATM-6#3131]
### Modpack Version

1.8.22

### What happened?

It seems like we cannot make Mana Regeneration II potions. Me and some friends tried using a vanilla brewing stand, we can do awkward potion -> mana regeneration potion, but when adding glowstone (to get to tier II), it turns them into calming potions.

I haven't been able to find any similar issue so I'm opening one, also I didn't see anything about this bug in the changelog between 1.8.22 and latest.

**Comment by jeremiahwinsley** [comment]
I can reproduce this, and the other Ars Nouveau potion seems to have the same issue. Does not happen with any other potion that I tested, so this is probably an Ars Nouveau bug.
