### ISSUE TITLE
Slow Flight

### ISSUE THREAD

**Issue by TECHNORYX** [AllTheMods/ATM-6#3133]
im playing atm6 the skyblock one, i have no problem using a jetpack, but if i try to use any creative flight-type thing, like the flugel tiara, angel wings or the flight augment i fly with extremely slow speed

**Comment by jeremiahwinsley** [comment]
Cannot replicate this on current ATM6, might be due to something in your inventory or an effect on your player?

**Comment by TECHNORYX** [comment]
> 

So yea i tried to remove everything from my inventory and didnt have any effect on me, tried to restart the game it was still the same, but after like 3 hours in game it just randomly started working normally so ig just a bug
