### ISSUE TITLE
[Bug]: Duplication bug

### ISSUE THREAD

**Issue by TomasGnG** [AllTheMods/ATM-6#3134]
### Possible Fixes

Yes

### Modpack Version

1.8.27

### What happened?

If you place a Golden Hopper above the Inscriber from AE2 the Golden Hopper will insert the items in "Stack Mode" which is generally not possible because the Inscriber accepts only one.
![image](https://user-images.githubusercontent.com/78899725/183051913-2b14cb8a-dc91-40a2-9340-9c2ca1f8972f.png)

If you try to remove the inserted items it will go on till there are not items left.
![image](https://user-images.githubusercontent.com/78899725/183052645-c0a95ebd-37dd-489c-83c1-b9b5f670f35d.png)

### latest.log

https://gist.github.com/TomasGnG/9b5307bc45873b03699369a7b6f0989f

**Comment by jeremiahwinsley** [comment]
Thanks for reporting, Golden Hopper has been disabled in 1.8.28.

**Comment by TomasGnG** [comment]
No problem.
