### ISSUE TITLE
[Question]: Trying to host ATM6 server on home network. Receiving Mod Loading Error on server run.

### ISSUE THREAD

**Issue by dirkmate** [AllTheMods/ATM-6#3138]
### What would you like to know?

What can I do to fix this? Crash report below.

https://pastebin.com/jRZzS9T5

**Comment by TheOmegaSystem** [comment]
i also have the same issue

**Comment by jeremiahwinsley** [comment]
original question: use the server pack, not the client. 
@TheOmegaSystem you are using Java 17, which isn't supported for ATM6, use Java 8 or 11
