### ISSUE TITLE
Teleport pad 

### ISSUE THREAD

**Issue by tkdrulz** [AllTheMods/ATM-6#314]
I updated ATM 6 to the newest version and the teleport pad from allthemodium mod is not working.  How do I fix this.  Thank you

**Comment by thevortex** [comment]
try restarting the server first, sometimes the dimension does not generate on first launch, failing that, will need you to type /forge dimensions 
in game and see what dimensions are appearing for you

**Comment by tkdrulz** [comment]
I tried restarting the server all ready

Currently registered Dimensions by type:
allthemodium:mining: allthemodium:minig
woot:mobsimulator: woot:tartarus
Minecraft:overword: Minecraft:overworld
Rats:ratlantis: rat:ratlantis
mahoutsukaiLreality_marble:mahoutsukaiLreality_marble
Minecraft:the_end
Minecraft:the_neather
allthemodium: the_other

**Comment by thevortex** [comment]
are you sneaking and right clicking the pad with both hands empty?

**Comment by tkdrulz** [comment]
yeah, I had a torch in my off hand.  It works now thanks

**Comment by thevortex** [comment]
awesome!
