### ISSUE TITLE
[Bug]: Mystic Agriculture recipe for Inscriber Silicon Press is not possible

### ISSUE THREAD

**Issue by andrewsf** [AllTheMods/ATM-6#3141]
### Possible Fixes

Yes

### Modpack Version

1.8.28

### What happened?

Every crafting recipe using silicon wants `forge:silicon` except this one:

Inscriber Silicon Press: 6 Certus Quartz Essence + 1 Silicon (added by Mystic Agriculture)

Since the modpack removes AE2's silicon, please update this recipe to use `forge:silicon`

### latest.log

N/A

**Comment by jeremiahwinsley** [comment]
Fixed in 1.9.0.
