### ISSUE TITLE
[Bug]: Quark Sugar Cane Bundle has no recipe but gets crafted instead of Block of Sugar Cane; breaks recipe for Leafy Bee Spawn Egg

### ISSUE THREAD

**Issue by andrewsf** [AllTheMods/ATM-6#3142]
### Possible Fixes

Yes

### Modpack Version

1.8.28

### What happened?

Recipe: 3x3 grid of Sugar Cane

- JEI does not list Quark's *Sugar Cane Bundle* (`quark:sugar_cane_block`) as a valid item, but crafting 3x3 Sugar Cane will create it.
- JEI lists Thermal Series's *Block of Sugar Cane* (`thermal:sugar_cane_block`) as being craftable, but it is not actually craftable. The 3x3 recipe creates the Quark block instead.
- The recipe for Leafy Bee Spawn Egg requires `thermal:sugar_cane_block`, even though it is not obtainable.

### latest.log

N/A

**Comment by jeremiahwinsley** [comment]
Fixed in 1.9.0.
