### ISSUE TITLE
[Bug]: Not able to get "Hell Infusion" enchantment anymore

### ISSUE THREAD

**Issue by VakarTR** [AllTheMods/ATM-6#3143]
### Possible Fixes

Yes

### Modpack Version

1.8.28

### What happened?

I haven't played atm6 in a while, but it used to be possible to enchant "Hellshelf" and get "Hell Infusion" enchantment on the block, now you can only get Soulbound.

### latest.log

https://gist.github.com/VakarTR/7edef616edf1435902add8f13585968f

**Comment by jeremiahwinsley** [comment]
Not a bug, a recent Apotheosis update added extra requirements to get it. You now need to match the stats listed in JEI before Infusion will show up.
