### ISSUE TITLE
[Bug]: something missing in the zip folder? (server file)

### ISSUE THREAD

**Issue by Saltypeper** [AllTheMods/ATM-6#3145]
### Possible Fixes

Yes

### Modpack Version

1.8.28

### What happened?

I downloaded the latest server file from the forge website. But everytime i start the batch file, I see in cmd that something is going wrong but I don't know how any of this works.  Can someone help me with this?

### latest.log

https://gist.github.com/Saltypeper/6845c90b9618b3a2817d2cd23808a1a6

**Comment by jeremiahwinsley** [comment]
You cannot use Java 17 for ATM6, you need Java 8 or 11
