### ISSUE TITLE
I have a question about atm6 to the sky

### ISSUE THREAD

**Issue by dougug90** [AllTheMods/ATM-6#3146]
### What would you like to know?

so I was on the first section of the quest lists (skyblock tips) and i was saying check on all of them to get the heads and the rewards also the exp but i came across one about commands and i clicked it then it just went back to one tree and some grass i am a little bit upset because i have been working on this world for about 30 hours and i had just made netherite mesh not long ago witch took me hours to make now i only have the tree so my question is can i have my world back please.

**Comment by jeremiahwinsley** [comment]
I think it mentions it in the quest, but you just need to use `/skyblock spawn` to go back to the spawn island.

**Comment by dougug90** [comment]
yes but i have already tried that and it just spawns another tree

**Comment by dougug90** [comment]
i will try it once more

**Comment by dougug90** [comment]
thanks it worked i may have entered it in wrong
