### ISSUE TITLE
[Crash]: some mods wont load

### ISSUE THREAD

**Issue by zephwtf** [AllTheMods/ATM-6#3147]
### Possible Fixes

Yes

### Modpack Version

1.8.28

### What happened?

some mods wont load and even cant show what cant load
![unknown](https://user-images.githubusercontent.com/95918789/190666605-243600a0-66d3-44a0-9432-b9f87c490ebf.png)

### Crash Log

https://gist.github.com/zephwtf/58f17dc16288ecb3c111e88eac16767c#file-gistfile1-txt

**Comment by jeremiahwinsley** [comment]
You need to use Java 8 or 11, not 16.
