### ISSUE TITLE
Replace recipe

### ISSUE THREAD

**Issue by hayatsy** [AllTheMods/ATM-6#3148]
Could anyone tell me how to change the recipe for the unobtanium_vibranium_alloy and and the other alloys, I'm playing one modpack without nether and I can't go to the other to catch the dragons

**Comment by jeremiahwinsley** [comment]
You would have to add a new recipe with a datapack/kubejs/crafttweaker.

**Comment by hayatsy** [comment]
modpack already uses KubeJS, would it be a problem to use crafttweaker?

**Comment by jeremiahwinsley** [comment]
Not sure. Datapack is probably the easiest method as you can find all sorts of editors to make it easier.

**Comment by hayatsy** [comment]
ok thks
