### ISSUE TITLE
Rats are not working while owner is offline.

### ISSUE THREAD

**Issue by aricgerspacher** [AllTheMods/ATM-6#315]
My server wants rats working 24/7. However, when a rat has been trained for a job, and its owner logs off, the rat is observed to be getting no work done. As soon as their owner is logged on (owner identified by holding shift over a rat), the rats begin their jobs again.

**To Reproduce**
Have a tamed rat set to gather items to a chest. Have the owner log off, and a second person observe the rat. 

**Expected behavior**
Rats should pick up items, interact with environment whether owner is logged on or not.

**Additional context**
Rat may pick up an item, but will not deposit item into a chest or move from its spot to grab nearby items.
TRIED: placing force loaded claims, and removing all claims, from a rats area.
TRIED: vanilla chests, drawers

**Comment by ViRb3** [comment]
This looks better suited for [the Rats issue tracker](https://github.com/Alex-the-666/Rats/issues).

**Comment by whatthedrunk** [comment]
Not seeing an issue on the rats tracker after a couple months so I assume this has been fixed. Feel free to submit the issue to them if its still happening and we can reopen.
