### ISSUE TITLE
Recipes KubeJS

### ISSUE THREAD

**Issue by PedroN12** [AllTheMods/ATM-6#3150]
Can someone help me please, I managed to solve all the errors in my modpack except these two, they are related to the modified recipes
![image](https://user-images.githubusercontent.com/90482290/191846865-7b8cbda0-d113-44f8-87ba-cba83836903d.png)
![image](https://user-images.githubusercontent.com/90482290/191846931-2327ec57-bb1d-412e-aeaa-a25b10463dea.png)

**Comment by jeremiahwinsley** [comment]
is this atm6 or a custom pack? and if atm6, what mods did you remove? then, just search for modifyShaped and figure out which uses of it refer to one of the mods you removed, and remove that use.
