### ISSUE TITLE
[Bug]: its not crafting the beehive i want to craft

### ISSUE THREAD

**Issue by colbieK** [AllTheMods/ATM-6#3151]
### Possible Fixes

Yes

### Modpack Version

1.8.28

### What happened?

so I was going to create the tier 3 beehive but I looked up the recipe for it in the JEI I have all the materials I have and it would not craft it I was wondering why its not crafting it 
![Screenshot (21)](https://user-images.githubusercontent.com/116925863/198752161-435e93ef-0445-42be-815e-24cf09b5f794.png)
![Screenshot (22)](https://user-images.githubusercontent.com/116925863/198752168-36a74e9a-27c9-49c6-a600-16ba9cbb55a2.png)

is there any fix to this 

### latest.log

https://gist.github.com/colbieK/5454971cc28b6f6fa7be848f0f2f13c2

**Comment by jeremiahwinsley** [comment]
Note that hives are tiered - you must use the correct tier for crafting, you probably need a tier 2 hive here. You can see the current tier on the tooltip.

**Comment by colbieK** [comment]
let me see if your correct

**Comment by colbieK** [comment]
![Screenshot (23)](https://user-images.githubusercontent.com/116925863/198753025-a531bdd1-879f-424a-8fb5-c7ba16655c25.png)

It WORKED! let people know about this crafting issue because the beehive that you find in the wilderness are incorrect in the recipe
