### ISSUE TITLE
Help me Modpack not installing in MultiMC launcher

### ISSUE THREAD

**Issue by Hawk2811** [AllTheMods/ATM-6#3153]
I try install modpack in multiMC but crash

Screenshot

![image](https://user-images.githubusercontent.com/55853571/200186203-dd6b16bb-bccf-4efc-a325-8125e528b341.png)

Error: The file does not contain a readable modpack type

**Comment by jeremiahwinsley** [comment]
MultiMC does not support Curseforge packs. You can use Prism (https://prismlauncher.org/) instead.
