### ISSUE TITLE
[Question]:The Ender Dragon is invincible，it can not be attacked。

### ISSUE THREAD

**Issue by lxt1999625** [AllTheMods/ATM-6#3154]
### What would you like to know?

Bows and explosions can hurt it, but melee cannot , including interacting with it ，it is a bug or not ？  

（Version：AllTheMods 6-1.8.28）

**Comment by P0kys** [comment]
I remember there being some weird bugs with this fight when ATM6 was around. I think it had to do something with the dragon being in a different chunk than you and some wonky hitboxes.
This might honestly be a vanilla bug/weird mechanic. Try hitting it in different places or just use ranged attacks

**Comment by alekulyn** [comment]
Had the same problem a while ago. Disabling OptiFine did the trick for me.
