### ISSUE TITLE
[Crash]: the game just recently started crash on launch

### ISSUE THREAD

**Issue by EzakiHoshigami** [AllTheMods/ATM-6#3155]
### Possible Fixes

Yes

### Modpack Version

1.8.28

### What happened?

the launcher keeps giving me a code 1 crash i've reinstalled atm6 3 times and i have no clue what the problem is

### Crash Log

https://gist.github.com/EzakiHoshigami/a123d63ce3974aa2644e7c1287de5f65

**Comment by NightJbird** [comment]
I am having the exact same problem. Was working fine this morning but then came home from work poof Code 1

**Comment by EzakiHoshigami** [comment]
> 

same

**Comment by peaceofmind03** [comment]
I literally made an account to tell you how to fix this so you can play. Go into curseforge, right by create custom profile there are three dots. Click that and do repair installation. Then play atm, it'll download stuff and make you relogin to Microsoft. But it fixed it for me

**Comment by peaceofmind03** [comment]
I literally made an account to tell you how to fix this so you can play. Go into curseforge, right by create custom profile there are three dots. Click that and do repair installation. Then play atm, it'll download stuff and make you relogin to Microsoft. But it fixed it for me @EzakiHoshigami @NightJbird

**Comment by peaceofmind03** [comment]
> > 
> 
> same

I literally made an account to tell you how to fix this so you can play. Go into curseforge, right by create custom profile there are three dots. Click that and do repair installation. Then play atm, it'll download stuff and make you relogin to Microsoft. But it fixed it for me

**Comment by peaceofmind03** [comment]
> I am having the exact same problem. Was working fine this morning but then came home from work poof Code 1

I literally made an account to tell you how to fix this so you can play. Go into curseforge, right by create custom profile there are three dots. Click that and do repair installation. Then play atm, it'll download stuff and make you relogin to Microsoft. But it fixed it for me

**Comment by NightJbird** [comment]
> I literally made an account to tell you how to fix this so you can play. Go into curseforge, right by create custom profile there are three dots. Click that and do repair installation. Then play atm, it'll download stuff and make you relogin to Microsoft. But it fixed it for me @EzakiHoshigami @NightJbird

I'll try that, but that was the first thing I attempted before coming here

**Comment by NightJbird** [comment]
> > > 
> > 
> > 
> > same
> 
> I literally made an account to tell you how to fix this so you can play. Go into curseforge, right by create custom profile there are three dots. Click that and do repair installation. Then play atm, it'll download stuff and make you relogin to Microsoft. But it fixed it for me

I also did a fresh install and restart my rig and nothing at that time

**Comment by NightJbird** [comment]
I have also noticed the Memory Heap wouldn't go over 1k even though i do have 8gb allocated. I know a person on my server that also getting this. So something is amiss on Forge side or something

**Comment by EzakiHoshigami** [comment]
> > I am having the exact same problem. Was working fine this morning but then came home from work poof Code 1
> 
> I literally made an account to tell you how to fix this so you can play. Go into curseforge, right by create custom profile there are three dots. Click that and do repair installation. Then play atm, it'll download stuff and make you relogin to Microsoft. But it fixed it for me

thanks for the help

**Comment by EzakiHoshigami** [comment]
> > > I am having the exact same problem. Was working fine this morning but then came home from work poof Code 1
> > 
> > 
> > I literally made an account to tell you how to fix this so you can play. Go into curseforge, right by create custom profile there are three dots. Click that and do repair installation. Then play atm, it'll download stuff and make you relogin to Microsoft. But it fixed it for me
> 
> thanks for the help

i can in fact say that didn't work

**Comment by EzakiHoshigami** [comment]
> > I literally made an account to tell you how to fix this so you can play. Go into curseforge, right by create custom profile there are three dots. Click that and do repair installation. Then play atm, it'll download stuff and make you relogin to Microsoft. But it fixed it for me @EzakiHoshigami @NightJbird
> 
> I'll try that, but that was the first thing I attempted before coming here

@NightJbird it didn't work btw

**Comment by NightJbird** [comment]
Yeah just tried as well sadly didn't work

**Comment by EzakiHoshigami** [comment]
> Yeah just tried as well sadly didn't work

when i didnt allocate more than 4gb of ram the game starts to launch

**Comment by NightJbird** [comment]
> > Yeah just tried as well sadly didn't work
> 
> when i didnt allocate more than 4gb of ram the game starts to launch

That...That is quite weird

**Comment by EzakiHoshigami** [comment]
> > > Yeah just tried as well sadly didn't work
> > 
> > 
> > when i didnt allocate more than 4gb of ram the game starts to launch
> 
> That...That is quite weird

it actually launched with less than 4gb and i just updated the crash log

**Comment by NightJbird** [comment]
Did it stay launched after you had it less then 4gb if so it has to be laggy or something in actual play

**Comment by EzakiHoshigami** [comment]
> Did it stay launched after you had it less then 4gb if so it has to be laggy or something in actual play

no crashes i didnt open a world tho

**Comment by NightJbird** [comment]
Yeah tried to put it like you did but still crashed

**Comment by NightJbird** [comment]
Did that pretty much after every launch at this point

**Comment by EzakiHoshigami** [comment]
> Did that pretty much after every launch at this point

hopefully we'll get some kind of answer later

**Comment by NightJbird** [comment]
indeed

**Comment by EzakiHoshigami** [comment]
> indeed

i found a temp solution at least. so do that repair install then instead of trying to launch the game immediately change allocated ram in the launcher and then launch it

**Comment by enigmaquip** [comment]
you can try these instructions from curseforge discord
![image](https://user-images.githubusercontent.com/6134440/200437374-c2a905d6-0093-4f9f-b309-2082f04664c3.png)

**Comment by NightJbird** [comment]
> you can try these instructions from curseforge discord ![image](https://user-images.githubusercontent.com/6134440/200437374-c2a905d6-0093-4f9f-b309-2082f04664c3.png)

just about to try a fresh install of Curseforge. but will do that as well

**Comment by colbieK** [comment]
i have the same problem too this started today for me also yesterday it was fine until the game said exit code 1
![Screenshot (31)](https://user-images.githubusercontent.com/116925863/200446326-a676f17e-74bc-4bf4-968d-4acd973a7df8.png)

**Comment by legbeard** [comment]
> you can try these instructions from curseforge discord ![image](https://user-images.githubusercontent.com/6134440/200437374-c2a905d6-0093-4f9f-b309-2082f04664c3.png)

Chiming in to confirm that this seems to have fixed the problem for us on 2 machines.

For anyone reading thinking "I already did this, and it didn't work", notice that this is NOT "Repair Profile" under the specific modpack, but rather "Repair installation" in the drop-down menu accessed by hitting the 3 vertical dots in the top right, to the right of both "+ Create Custom Profile" and the search bar.
