### ISSUE TITLE
My game's ram is always ramping up to almost 100% then freezes

### ISSUE THREAD

**Issue by EzakiHoshigami** [AllTheMods/ATM-6#3157]
I just recently noticed that my game started doing this, whenever I open my world the ram usage is at 60% then starts to climb all the way up to max allocated and freeze for like 10 secs. I use the curseforge launcher

I've tried it in a new world its the same
I've checked to see if the same thing happens in other mod packs and its only present in atm6
I've done a fresh install of atm6 and I'm using the args from the discord

I cant seem to find an answer and here is spark link if it helps [https://spark.lucko.me/rhDLzxgL45]

**Comment by jeremiahwinsley** [comment]
By that spark profile, it looks like the process is not able to use all the ram you have allocated because you are running out of RAM on your PC. Physical memory is at 95%, 22.2 GB/23.4 GB. Maybe check Task Manager and see what else is using all your ram and try to close stuff?

**Comment by EzakiHoshigami** [comment]
> By that spark profile, it looks like the process is not able to use all the ram you have allocated because you are running out of RAM on your PC. Physical memory is at 95%, 22.2 GB/23.4 GB. Maybe check Task Manager and see what else is using all your ram and try to close stuff?

I'm talking about the ram that I allocated to the game, I'm aware of what's happening outside of the game itself. I didn't mention it before but I first allocated 8 then 10 and then 12. At 12 it uses 15gigs, but anything below 12 it does what I said above

**Comment by jeremiahwinsley** [comment]
So with the base modpack, 10gb is the recommended, and 12gb is not out of the ordinary for longer running worlds. So if it is working fine with 12gb, then just use that.  If you need to use less, or you are still getting spikes, you could try using Java 11 instead, but you need a 3rd party launcher like GDLauncher or Prism Launcher to use it.

**Comment by EzakiHoshigami** [comment]
> So with the base modpack, 10gb is the recommended, and 12gb is not out of the ordinary for longer running worlds. So if it is working fine with 12gb, then just use that. If you need to use less, or you are still getting spikes, you could try using Java 11 instead, but you need a 3rd party launcher like GDLauncher or Prism Launcher to use it.

Using 12 gigs fucks with my laptop, like my usage get close to 100% with my tabs open, so I'm thinking I'll try using the other launchers you suggested
