### ISSUE TITLE
[Crash]: Ticking Block entity; industrial foregoing plant fertilizer

### ISSUE THREAD

**Issue by Samuql** [AllTheMods/ATM-6#3158]
### Possible Fixes

Yes

### Modpack Version

1.8.28

### What happened?

Im running ATM6 on a Server.
Since yesterday it throws the ticking block entity error for a plant fertilizer when i try to join the server. 
My approaches:

### Enable removeErroringEntities and removeErroringTileEntities in the forge-server.toml
Tried to Join ~ 3 times, but the Server kept crashing when My Client loads the world

### Open the world in Amulet Editor
The Editor could only load some textures in the spawn area, and no textures in the area around 3969,98,7585.
Deletion didnt seem to work.

Here's the most important crash snippet:

-- Block entity being ticked --
Details:
        Name: industrialforegoing:plant_fertilizer // com.buuz135.industrial.block.agriculturehusbandry.tile.PlantFertilizerTile
        Block: Block{industrialforegoing:plant_fertilizer}[subfacing=north]
        Block location: World: (3969,98,7585), Chunk: (at 1,6,1 in 248,474; contains blocks 3968,0,7584 to 3983,255,7599), Region: (7,14; contains chunks 224,448 to 255,479, blocks 3584,0,7168 to 4095,255,7679)
        Block: Block{industrialforegoing:plant_fertilizer}[subfacing=north]
        Block location: World: (3969,98,7585), Chunk: (at 1,6,1 in 248,474; contains blocks 3968,0,7584 to 3983,255,7599), Region: (7,14; contains chunks 224,448 to 255,479, blocks 3584,0,7168 to 4095,255,7679)
Stacktrace:
        at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:twilightforest:hitbox,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransfor$
        at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:372) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:forge$

I hope someone can help me..... :(

### Crash Log

https://gist.github.com/Samuql/d976b1b88f2d5dbbc370031c1fdeb624

**Comment by jeremiahwinsley** [comment]
This is a known issue when bonemealing BYG grass blocks. For a workaround you can try editing `config/industrialforegoing/machine-agriculture-husbandry.toml` on the server, find `[MachineAgricultureHusbandryConfig.PlantFertilizerConfig]` section and change `powerPerOperation` to some amount higher than than the buffer size, like 20000, which should prevent the fertilizer from working.

**Comment by Samuql** [comment]
Thank you! Deactivating the fertilizer and activating it back worked, too.
