### ISSUE TITLE
[Bug]: Using more than two Thermal Evaporation Valves, or splitting the two valves apart, causes the Thermal Evaporation plant not to work.

### ISSUE THREAD

**Issue by StarstrikePrime** [AllTheMods/ATM-6#3164]
### Possible Fixes

Yes

### Modpack Version

1.8.28

### What happened?

Pretty much exactly what it says in the title. I'm working on setting up my ore quintupling rig, and when I'm crafting the TEP, it initially isn't working. I find out that, for some reason, I can't have more than two valves on it, and they HAVE to be together. Adding a third one causes it to be invalid. Putting the two valves on any non-center block causes it to be invalid. I don't know why it's doing this; it's a massive pain to not be able to make the brine I need due to not having the valves necessary.

### latest.log

https://gist.github.com/StarstrikePrime/5d7623f56941f3a86e5baa92eed55f3f

**Comment by jeremiahwinsley** [comment]
You cannot have it on the edges, but you should be able to put at least three valves in (input, output, heat). Can you add a screenshot of the build in question?

**Comment by StarstrikePrime** [comment]
![2022-12-20_05 47 02](https://user-images.githubusercontent.com/121068071/208649580-79e3f02e-804c-4eeb-98fd-b167b45ee8ac.png)
It seems you were correct. The plant was working when I had two, so I originally planned on showing it to you with just those until you told me. This screenshot is of the plant working, but with the third port.
