### ISSUE TITLE
[Question]: In  Your integration package. What is the module to display the item name information I see

### ISSUE THREAD

**Issue by KGOne-666** [AllTheMods/ATM-6#3166]
### What would you like to know?

[Question]: In  Your integration package. What is the module to display the item name information I see .I cannot find it according to the mod name. The modules (what are we looking at,here what you are looking at)I know can't be found  in the  package.

**Comment by jeremiahwinsley** [comment]
We are using [The One Probe](https://www.curseforge.com/minecraft/mc-mods/the-one-probe) for that.

**Comment by KGOne-666** [comment]
> We are using [The One Probe](https://www.curseforge.com/minecraft/mc-mods/the-one-probe) for that.

How to change its position to middletop.
I try to change this mod's config but failed.
And when I change the options-video setting , when I restart ,i turned out to be original , so is the language ,which changes  to Chinese

**Comment by KGOne-666** [comment]
> > We are using [The One Probe](https://www.curseforge.com/minecraft/mc-mods/the-one-probe) for that.
> 
> How to change its position to middletop.
> I try to change this mod's config but failed.
> And when I change the options-video setting , when I restart ,i turned out to be original , so is the language ,which changes  to Chinese

I have been studying this problem today

**Comment by jeremiahwinsley** [comment]
To change the position you can use the command `/top config`

**Comment by KGOne-666** [comment]
> To change the position you can use the command `/top config`

Thank you very much, I find it out already
