### ISSUE TITLE
[Bug]: Creative items have no recipes

### ISSUE THREAD

**Issue by suby0789** [AllTheMods/ATM-6#3167]
### Possible Fixes

Yes

### Modpack Version

1.8.28

### What happened?

Hosting a server with my mates from my computer but on the server creative items dont have a recipe
it works fine in single player but for some reason on the server there is no recipes
i added in a few of my own mods at first but switched to the normal version and still the same issue on a server but its fine in singleplayer 

thanks for the help :)

### latest.log

https://gist.github.com/suby0789/ea048cd0ff1d96ea583e157c2d1a7fb6

**Comment by jeremiahwinsley** [comment]
Did you copy all the kubejs scripts when installing the server? It works correctly in the released server pack

**Comment by suby0789** [comment]
That fixed the recipes but now i get more kubejs errors 

https://gist.github.com/suby0789/e54f51180649278c9637745c53d607ae

let em know if you want a different log

**Comment by suby0789** [comment]
> Did you copy all the kubejs scripts when installing the server? It works correctly in the released server
replaced it and the recipes work now but theres some new errors

**Comment by suby0789** [comment]
Never mind i fixed it i just replaced everything in the server files thanks for your help <3
