### ISSUE TITLE
Server not starting, was fine earlier in January.

### ISSUE THREAD

**Issue by maicol9608** [AllTheMods/ATM-6#3168]
So on January the 15th, I played on my ATM6 server with my bf and we haven't played since then until I tried to start the server yesterday, 3rd of February. For some reason the server just refuse to start, claiming "server not set"...
I decided today completely reinstall the server in a different folder and then just copy over to world, and the few extra mods we'd been using, nothing major, just "Configured", "Ultimine" (at least I think I added that one) and another I can't quite remember at the moment.
Anyway, the new server refuses to work as well.

Here's my crash report:
[crash-2023-02-03_23.46.16-server.txt](https://github.com/AllTheMods/ATM-6/files/10583468/crash-2023-02-03_23.46.16-server.txt)

Hopefully you can help me work this out, I am so confused. I hate these error codes, I can't read them...

**Comment by jeremiahwinsley** [comment]
You have some corrupted server configs. Delete or rename the `world/serverconfig` folder (it will regenerate from defaults), and then replace the `config` folder with a fresh copy from the server zip.

**Comment by maicol9608** [comment]
> You have some corrupted server configs. Delete or rename the `world/serverconfig` folder (it will regenerate from defaults), and then replace the `config` folder with a fresh copy from the server zip.

I did what you said and started the server, it now gave me this:
[Server start log.txt](https://github.com/AllTheMods/ATM-6/files/10585280/Server.start.log.txt)

**Comment by maicol9608** [comment]
> You have some corrupted server configs. Delete or rename the `world/serverconfig` folder (it will regenerate from defaults), and then replace the `config` folder with a fresh copy from the server zip.

I did this a second time and it worked, now the server starts properly. Thanks!
