### ISSUE TITLE
[Bug]: Every since I updated from 1.8.17 to 1.8.28, JEI and crafting stations are not working properly, among other issues

### ISSUE THREAD

**Issue by maicol9608** [AllTheMods/ATM-6#3169]
### Possible Fixes

Yes

### Modpack Version

1.8.28

### What happened?

So, it all started when I tried to run my old ATM6 server for me and my partner that had worked fine up until like mid-January.
It kept giving errors and wouldn't launch properly, and the only possible solution people kept mentioning when it came to anything modded server and the like was to update my server to the last version of said modpack, so I did.
And because I updated the server me and my partner had to update our client version to the lastest as well.
I only hav elike 1 or 2 extra mods, but those worked fine before the update and I highly doubt they are the kind of mods that would cause issues with two seperate unrelated mods. I can't remember which 1 or 2 are extra mods, and I haven't found a good list that shows the default mods of the pack, perhaps I'm blind.
Anyway the issue with JEI is that it doesn't appear at all for either of us when we join our server, however I found another person having a similar issue and fixed it by going into singleplayer world first then going into server and it's fixed. Annoying issue, but if there's no immediate fix, I guess we can live with it. Secondly, I can't check any recipes in JEI. The key is bound but for the vast majority of things I simply cannot check the recipes, which makes a heavily modded pack like this unplayable.
I can press U and see the use case for some items, but it doesn't actually show me any recipes just what some items are otherwise used for.

Now onto crafting stations. When we place stuff and try to craft something in there, the product is completely blank, and crafting doesn't work at all. Normal craftingtables work fine however.

Another issue I have is that lava in the cyclic fluid tanks doesn't look like lava. It looks like a weird red chain on the "glass" of the tanks but nothing inside.

I posted an issue earlier in the month about issues with my server not starting at all.
Well, even if it starts now, it keeps getting a bunch of errors while loading, and at the start it used to have a bunch of green text and other stuff, mentioning version and other things, but now it shows nothing, just an error about "unable to access jar file C:\Users\<username>\Desktop\Minecraft" and then it starts loading up the server.
I can't help but feel like these issues (except maybe the lava issue since my partner did not experience this) are somehow related to the server starting weirdly and a bunch of errors happening while loading.
I'm on a different computer than the server is on so can't really post a log from the server atm, but I'll try tomorrow if it's necessary.

Thanks in advance for any and all help.

### latest.log

https://gist.github.com/maicol9608/5b08d3da5a1974a0ed4521c6dd51b64b

**Comment by jeremiahwinsley** [comment]
It looks like you added Optifine, and that mod can definitely cause all sorts of issues like that. Try removing that and see if it fixes  the issues. 

An alternative to optifine if you are using it for shaders is Rubidium + Oculus with these settings:
1. Run command `/flywheel backend off`
2. edit config/rubidium-mixins.properties and add `mixin.features.chunk_rendering=false`

**Comment by maicol9608** [comment]
> It looks like you added Optifine, and that mod can definitely cause all sorts of issues like that. Try removing that and see if it fixes the issues.

I removed Optifine, I had it as a .jar file in the mods folder, dunno if there's anything else that needs doing to remove it properly.
But if removing the .jar file is enough, that did not fix all the issues. Only thing it fixed was the lava.

**Comment by jeremiahwinsley** [comment]
Try running a repair from the 3 dot menu in Curseforge, then run the game again and post an updated log?

**Comment by maicol9608** [comment]
[latest.log](https://github.com/AllTheMods/ATM-6/files/10787179/latest.log)
Here's an updated log.
When I clicked 'Repair Profile' it was so fast it's like it didn't do anything.

**Comment by jeremiahwinsley** [comment]
Do these errors only happen when connected to a server, or do they happen in a single player world as well? If they happen on the server, can you post the server log? I don't see any errors in this client log.

**Comment by maicol9608** [comment]
> Do these errors only happen when connected to a server, or do they happen in a single player world as well? If they happen on the server, can you post the server log? I don't see any errors in this client log.

I was just about to write about this. I did some testing now, even tested with adding Optifine again, and single player world works just fine. It's only in the server, which is probably why it's happening on BOTH me and my partners computers when connected to the same server.

Which log exactly is it you want? Not sure if the attached one is the correct one.
[latest.log](https://github.com/AllTheMods/ATM-6/files/10787342/latest.log)

**Comment by maicol9608** [comment]
Again, JEI appears if I join single player world first then switch to server, but I can't check any recipes.

**Comment by maicol9608** [comment]
Don't want to nag, but have you manged to figure out the issue with my server?
If you're busy, no rush :)

**Comment by jeremiahwinsley** [comment]
I also don't see any errors in that server log, with the problems you've mentioned they should definitely be putting an error somewhere - maybe in the debug.log? Can you also try creating a new server from scratch with a new world, and connect your client to it and see if things work properly there?

**Comment by maicol9608** [comment]
I'll try to set up a new one. A few problems I've been having with the installer file however.
When I updated the server the first time, it didn't workproperly, so I decided to make a new one, and then just copy over the world folder. But, when I first clicked the startserver.bat file it gave me the messages in this "Error start" txt file:
[Error start.txt](https://github.com/AllTheMods/ATM-6/files/10831610/Error.start.txt)
Now that I'm making a new server I'm going through the same events I did last time, and I'll try to describe the next issue of the process.
If I use the very same link that the server spat out to download forge, I am able to download forge.
So I did. and then I put it in the server folder. Next time I start it still says it can't find anything, so I renamed ALL my parent folders to remove spaces in between words. I'm guessing the code is missing citation marks ("") since it can't handle spaces properly.
So, now after I removed the spaces in the folder names, it started running fine. Just a heads up in case you made a mistake in the code.

**Comment by maicol9608** [comment]
Update. Created a completely new server, new world and all, and it works as expected.
Next I will try to copy over the world folder and see how that works, but without any extra mods.

**Comment by maicol9608** [comment]
Here's another txt file with what happened when I added the old world and tried to start it.
[Error start old world.txt](https://github.com/AllTheMods/ATM-6/files/10831718/Error.start.old.world.txt)
Is the world completely corrupt or just doesn't work on new version? Can it be fixed? How?

**Comment by jeremiahwinsley** [comment]
ok, that particular error is an easy fix, just delete the world/serverconfig folder and let it regenerate from defaults

**Comment by maicol9608** [comment]
> seems like the version of Windows you have doesn't support all the downloader options we're using (tested on Windows 10)
I have Windows 10 Pro edition build 19044.2604.
The rest of the modpack downloads perfectly fine after forge .jar file is present.

Will you backport it now to ATM6, or just add guide to fix it to the mod page?

> ok, that particular error is an easy fix, just delete the world/serverconfig folder and let it regenerate from defaults.
I'll try this, but I think I tried it last time when I filed an issue about my server crashing. I'll try again!

**Comment by maicol9608** [comment]
> ok, that particular error is an easy fix, just delete the world/serverconfig folder and let it regenerate from defaults.

I did as you said and voila! JEI appears to work as intended and crafting stations work too now!
Thank you so much for your patience and help! You do great work!
