### ISSUE TITLE
Overlays/Outlines of multiple addons stop working

### ISSUE THREAD

**Issue by DaveJK** [AllTheMods/ATM-6#317]
All The Mods 6 - v1.3.0

Outlines and overlays of addons stop working randomly. Botania's Assembly Halo overlay and Lexica Botania's Visualize outline disappears. Chisel & Bit's Tape Measure outline disappears. FTB Ultimine outline disappears. Just a few examples.

I'm not sure entirely what causes this behavior but I think I notice it after sleeping in a bed. In order to fix the issue I have to restart the game.

![AssemblyHalo](https://user-images.githubusercontent.com/24943733/99146953-96315300-2631-11eb-9072-a38f858c5b57.png)

![BotaniaVisualize](https://user-images.githubusercontent.com/24943733/99146947-8dd91800-2631-11eb-9f08-d402213d0385.png)

![TapeMeasure](https://user-images.githubusercontent.com/24943733/99146939-7c900b80-2631-11eb-8fd1-82e5fb3b34d7.png)
![Ultimine](https://user-images.githubusercontent.com/24943733/99146942-84e84680-2631-11eb-8724-048ca38fa50c.png)

**Comment by ViRb3** [comment]
Are you using Optifine by any chance?

**Comment by DaveJK** [comment]
I'm not using Optifine or any other mod not apart of the pack.

**Comment by thevortex** [comment]
well, it looks like it was my B :D ... resolved by updating Potions Master to https://www.curseforge.com/minecraft/mc-mods/potionsmaster/files/3133239

issue was with render overlay thread for potionsmaster potions(overlays will still disappear while the potions are active for the time being, but the thread will terminate correctly now when it is supposed to, so when the effect/charm is no longer in use, the overlays come back without requiring a restart. investigating this for a solution that will not involve any screen flickering/flashing) 

can you test the updated version of potionsmaster and let me know if it resolves it for you?

**Comment by DaveJK** [comment]
I'll be sure to let you know if I run into the issue again after the update. Thank you
