### ISSUE TITLE
Server Crash: java.lang.IllegalStateException

### ISSUE THREAD

**Issue by k8thekat** [AllTheMods/ATM-6#3170]
Hello!

Our server keeps experiencing this crash. Not sure if they are mod pack related or not.
[crash-2023-02-19_18.49.15-server.txt](https://github.com/AllTheMods/ATM-8/files/10779438/crash-2023-02-19_18.49.15-server.txt)
[crash-2023-02-18_12.18.15-server.txt](https://github.com/AllTheMods/ATM-8/files/10779439/crash-2023-02-18_12.18.15-server.txt)

**Comment by jeremiahwinsley** [comment]
Looks like this crash is being caused by Lithium, which is not in the pack by default. Try removing that and see if the server works without it.

**Comment by k8thekat** [comment]
Will do, I didn't even think to check the packs default mods. My apologies.
