### ISSUE TITLE
[Crash]: Crash when using the Beepedia

### ISSUE THREAD

**Issue by TonTonAsoX** [AllTheMods/ATM-6#3174]
### Possible Fixes

Yes

### Modpack Version

1.8.28

### What happened?

When right clicking with the Beepedia, game crash instantly.

### Crash Log

https://gist.github.com/TonTonAsoX/808238e39cb3aeda075cb64b05ec75b2

**Comment by jeremiahwinsley** [comment]
You have corrupted configs on either server or client. Delete the `config/resourcefulbees` folder on the server and client, and replace it with a fresh copy from the client or server zip.
