### ISSUE TITLE
Nether Portal Doesn't work after 1.3.0 update.

### ISSUE THREAD

**Issue by Thanoid1** [AllTheMods/ATM-6#318]
**Describe the bug**
I had a world where I made in the 1.2.1 version of ATM 6. I updated it to 1.3.0 today, and made a backup beforehand. I was playing normal, and I had to make an ender tank, which requires blaze rods. So I was going to the nether, and the portal never worked. The distortion just kept happening.
**To Reproduce**
1. Make world in 1.2.1
2. Make nether portal and go inside
3. Update to 1.3.0
4.Go to same nether portal and see it doesn't work.

**Expected behavior**
You go in the nether portal, and you get the usual purple portal distortion, and it keeps happening. No going in the nether.
**Screenshots**
A video.
[The video](https://www.kapwing.com/videos/5fb02fb3ba054d010d0f5cf5)
**Additional context**
I use optifine, don't know if that will affect anything.

**Comment by NetMasterFlex** [comment]
I experienced the same problem. I also upgraded from 1.2.1 to 1.3.0. When standing in the portal frame it continues to wave and make sound, but never transporting the player. 

NMF

**Comment by HalationEffect** [comment]
Stronghold portals to the End are also non-functional since updating from 1.2.1 to 1.3.0

Additionally, attempting to travel to Waystones I'd set up in the Nether and the End no longer works. Mining dimension and the Other dimension seem to be fine though.

**Comment by tonioss22** [comment]
The mod pack creator did mention that you should create a new world if you plan on updating, have you guys thought of deleting the nether and the end and having those regen?

**Comment by NetMasterFlex** [comment]
@tonioss22 How do I do that?  I'm fine with re-creating the nether, hadn't even made it to the end in my world during 1.2.1, but wouldn't mind taking a stab at removing the previously spawned Nether and End for good measure.  What files need to be deleted?

**Comment by HalationEffect** [comment]
Renaming (or deleting or moving to some other folder) the "DIM1" and "DIM-1" in your saves folder will usually force re-generation of a fresh Nether and End.

Not in this case. Tried it, made no difference. Nether portals and End portals are still not working.

**Comment by NetMasterFlex** [comment]
Have you tried creating a fresh new world? Like first backup your existing world, delete it then have it generate a new world.  God into creative mode, make a portal and test it?  This would rule out an issue with the game as a whole vs an existing world spawn issue.

**Comment by HalationEffect** [comment]
Yes, I created a fresh world and made a Nether portal, which works fine. Saved worlds are kept in separate folders, no need to delete your original world to try that.

**Comment by NetMasterFlex** [comment]
Well unless someone has an idea on how to fix this issue for existing world I think we may need to start over.  I'm researching on my end.  I run a ATM6 LAN server.  I deleted both the DIM1 and DIM-1 folders, re-started the server and same result after joining.  I don't think the ATM6 team is at any obligation to fix this since it works with a fresh game.

I'll keep looking and report any findings, please do the same.

NMF

**Comment by LloydSev** [comment]
To add to this - I had a waystone in the nether previous to the 1.3.0 update and it also fails to work.

**Comment by eliminat** [comment]
When doing a /forge tps the_nether doesn't appear.
It looks like the dimension isn't loaded with the world.

**Comment by NetMasterFlex** [comment]
Try this:  https://github.com/AllTheMods/ATM-6/issues/137#issuecomment-727296546

I'm going to see if the suggestion works.

NMF

**Comment by Thanoid1** [comment]
I'll try it as well.

**Comment by NetMasterFlex** [comment]
I had SUCCESS! Whew!  I followed the instructions from the link in my previous post.  Nether portal is working again.

NMF

**Comment by Thanoid1** [comment]
Works for me as well, but the solution is scuffed, devs should fix it before spam of complaints.

**Comment by NetMasterFlex** [comment]
Glad it worked for you as well.  I think they mentioned in being fixed in the next update.  In the meantime players will have to live with it or start over until the fix is implemented.  @thevortex ortex sums up the problem in the post I linked earlier.  He states the core issue near the bottom of the post.  I'm just glad there is a fix.

NMF

**Comment by Thanoid1** [comment]
Me as well.

**Comment by Thanoid1** [comment]
Solution:
As with last post #137 , the same problem happened with the 1.16.2 to 1.16.3 upgrade. We can say the same thing is happening with 1.16.3 to 1.16.4. Basically, there was no such thing as the nether when you upgraded it. So, to fix this, you need to make a new world in version 1.3.0. With an NBT editor, you can go in the level.dat file, and copy and paste the end and nether dimensions into your previous 1.2.1 dimensions sub-folder. After that, close and reopen ATM 6. Your nether should work.
Credits:
@NetMasterFlex 
@thevortex 
Sorry if other people contributed, don't know.
Post #137
