### ISSUE TITLE
[Crash]: server crashes when I go to one of my areas

### ISSUE THREAD

**Issue by Ozyrys500** [AllTheMods/ATM-6#3180]
### Possible Fixes

Yes

### Modpack Version

1.8.28

### What happened?

so I recently tried to migrate my single player world to a server, cause I don't play minecraft everyday but resources are not being farmed while I am not playing, and everything seemed nice and dandy but then I see that if I leave the server (as in I log out of it as a player and leave the server running) when I log onto the server again and go to one specific area the whole server crashes, the area is in mining dimension, and I have couple farms in that area, like resourceful bees farm as well as mystical agriculture one, now what's weird to me is that I can stay on the edge of that area without too many issues, and on that edge there is mekanism, the part that is problematic is the one where I have resourceful bees, mystical agriculture, botania and one ritual from astral sorcery to speed up ticks.

### Crash Log

https://gist.github.com/Ozyrys500/e51db1818dbf897ee74f194bc2f88c2e

**Comment by jeremiahwinsley** [comment]
Looks like you have too many dropped items on the ground. You can run `/cu entities find minecraft:item` to figure out where they are piling up, and `/cu entities remove minecraft:item` to clear them out. Or if you're ingame you can use the Ctrl + U menu to do it too.

**Comment by Ozyrys500** [comment]
ok so I think I found the problem, I wanted to just ask, can I specify coordinates at which to remove those dropped items? like after the second command add exact coordinates of the block on which there are so many dropped items

**Comment by jeremiahwinsley** [comment]
Not sure if you can with the command, but the Ctrl + U menu can. Click on the 2nd tab, then on the item entry in the list, then click on one of the listed coordinates and click delete

**Comment by Ozyrys500** [comment]
ok, I found the issue, and it was completely different than what I thought, apparently the crushing wheels I have set up are so efficient at doing their job the encased fan under them is not keeping up, or I didn't have it chunkloaded properly, well now I'm gonna brainstorm how get rid of that problem now, thank you very much for showing me this very useful commands and menu.
