### ISSUE TITLE
[Crash]: startserver.bat not working correctly

### ISSUE THREAD

**Issue by Nexud** [AllTheMods/ATM-6#3182]
### Possible Fixes

Yes

### Modpack Version

1.8.28

### What happened?

I'm trying to start the server by using startserver.bat inside the ATM6 server pack downloaded from Curseforge, but it's not working.

Contents of startserver.sh looks like this:
![obraz_2023-08-18_174643207](https://github.com/AllTheMods/ATM-6/assets/96995144/baabd121-b389-4bef-bbde-d13477476baa)

If I missed anything that would help you help me please do say so

### Crash Log

https://gist.github.com/Nexud/721454663a3c8ee909bdc671a3e23a06#file-startserver-bat

**Comment by jeremiahwinsley** [comment]
You are using Java 18, that's not supported. ATM6 requires Java 8 or 11. If you have multiple versions of Java installed, you can set an environment variable named ATM6_JAVA to the full path of your Java 8/11 java.exe and the script will use that instead of your default Java

**Comment by Nexud** [comment]
> You are using Java 18, that's not supported. ATM6 requires Java 8 or 11. If you have multiple versions of Java installed, you can set an environment variable named ATM6_JAVA to the full path of your Java 8/11 java.exe and the script will use that instead of your default Java

Could I ask you to show me exactly which part should I change? I'm not really good with code

**Comment by jeremiahwinsley** [comment]
Assuming you're using Windows 10 - open the start menu, start typing "environment" and it should find "Edit environment variables for your account.". Open that, click New on the top section. In "Variable name" put ATM6_JAVA, and then click browse file and find the java.exe for Java 8 or 11. Then hit ok twice to save. Then you should be able to rerun the script.

**Comment by Nexud** [comment]
> You are using Java 18, that's not supported. ATM6 requires Java 8 or 11. If you have multiple versions of Java installed, you can set an environment variable named ATM6_JAVA to the full path of your Java 8/11 java.exe and the script will use that instead of your default Java

Yup, that did it
Thank you very much
