### ISSUE TITLE
[Bug]: Incomplete server tags, disconnecting.

### ISSUE THREAD

**Issue by gold25chest** [AllTheMods/ATM-6#3184]
### Possible Fixes

Yes

### Modpack Version

1.8.28

### What happened?

Every time I want to go to the north it says Incomplete server tags

### latest.log

https://gist.github.com/gold25chest/da6de3e61220fa7433344877904052d1

**Comment by jeremiahwinsley** [comment]
The log says you are connecting to a vanilla server - make sure you have the correct IP/port entered?
