### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Withorcool** [AllTheMods/ATM-6#3187]
### Possible Fixes

Yes

### Modpack Version

1.8.28

### What happened?

Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: unable to fit 2104277 into 3

### latest.log

https://gist.github.com/Withorcool/74d7d2ecf873212c80e0ca5a215c674e

**Comment by jeremiahwinsley** [comment]
Magma/other bukkit hybrids are not supported, and are known to cause this sort of issue.
