### ISSUE TITLE
Portal not working

### ISSUE THREAD

**Issue by FrostZFish** [AllTheMods/ATM-6#319]
After update to 1.3.0, the nether portal and end portal are not working. my world originated from the 1.16.3 version.

**Comment by HalationEffect** [comment]
https://github.com/AllTheMods/ATM-6/issues/137

I had the same problem after updating to ATM6 v1.3.0, the fix suggested in the above topic worked for me.

**Comment by NetMasterFlex** [comment]
I performed the fix and it worked for me as well. 

NMF
