### ISSUE TITLE
[Bug]: Bigger Reactors JEI Moderator Stats missing

### ISSUE THREAD

**Issue by BillboardEric** [AllTheMods/ATM-6#3192]
### Possible Fixes

Yes

### Modpack Version

1.9.0

### What happened?

title

### latest.log

https://gist.github.com/BillboardEric/f91a18f8236dc630bcd0fc4903f7b2e2

**Comment by jeremiahwinsley** [comment]
Tested in 1.9.1 by checking the uses of the reactor controller in single player and modifiers show up correctly. Note that modifiers do not show up on servers unless you join a single player world first.
