### ISSUE TITLE
[Question]: Infinite Storage parts for Items and Fluids missing Why do you do that ?

### ISSUE THREAD

**Issue by BadassHD** [AllTheMods/ATM-6#3194]
### What would you like to know?

I wanna to know witch mod is blocking that recepies for infinite Storage and Fluid Disk from Extra Disk 

Here is an picture from the disks the older Modpack ATM 6 to the skys and thats what i am looking for :
![2023-11-22_19 19 16](https://github.com/AllTheMods/ATM-6/assets/151777728/36e5e9ad-2e40-4dd8-839d-33960b21af02)
![2023-11-22_19 19 26](https://github.com/AllTheMods/ATM-6/assets/151777728/eb822039-ab7b-4360-9849-87069b3fa531)

**Comment by jeremiahwinsley** [comment]
Those are disabled here: https://github.com/AllTheMods/ATM-6/blob/841b40731b7abfbc8c355f80284ab5c3c0e54e0e/kubejs/server_scripts/mod_specific/refinedstorage/refinedstorage.js#L143-L150 because the infinite disks overflow and delete the contents when you hit 2.1 billion items.

**Comment by BadassHD** [comment]
can i make this with Zip extrctor ?

**Comment by jeremiahwinsley** [comment]
It's not in a zip, it's just a file in your Minecraft instance folder. If you want to edit it, just open that file in notepad or vs code or other and delete those lines I highlighted.

**Comment by BadassHD** [comment]
i know i know but i have looking the hole evening yesterday and over yesterday for my disapointment they have it deletet the config for that and not exist in Curse Forge but thank you for the good help.

**Comment by jeremiahwinsley** [comment]
It is in there - click the 3 dot menu next to the Play button in Curseforge, and "Open Folder". In the folder that opens, go to kubejs > server_scripts > mod_specific > refinedstorage

**Comment by BadassHD** [comment]
[image: image.png]
it did not let me

Am Fr., 24. Nov. 2023 um 20:05 Uhr schrieb Jeremiah Winsley <
***@***.***>:
