### ISSUE TITLE
Quest "Ice Dragon Biome" Doesn't complete

### ISSUE THREAD

**Issue by DiscordedTree** [AllTheMods/ATM-6#3198]
In dimension The Other the quest relating to entering the biome _allthemodium:mountain_ doesn't complete, thus making later chained progressions around dragons impossible. Under the f3 debug menu, it would seem that the biome spelling uses an 's'. i.e "_allthemodium:mountain**s**_"

**Comment by jeremiahwinsley** [comment]
Fixed in 1.9.2
