### ISSUE TITLE
[1.3.0] Botania Terrestrial Agglomeration Plate made redundant?

### ISSUE THREAD

**Issue by HalationEffect** [AllTheMods/ATM-6#320]
After upgrading from 1.2.1 to 1.3.0 Botania's Terrestrial Agglomeration Plate no longer makes Terrasteel. It consumes the input items and half a pool of mana, and produces nothing.

JEI shows that Mythic Botany's Mana-Infuser has taken over this recipe, which is fine but it contradicts Botania's in-game guide, and leaves the Terrestrial Agglomeration Plate without a use.

Guessing this is a bug and not intentional?

**Comment by Lavassin** [comment]
Same issue, Terrestrial Agglomeration Plate does nothing and there is no way to make Terrasteel without the Mana-Infuser, which requires the Portal to Alfheim, which requires Terrasteel to make..

Definitely a bug

![image](https://user-images.githubusercontent.com/32739138/99283558-2d013980-2803-11eb-922e-9820b33a9be8.png)
![image](https://user-images.githubusercontent.com/32739138/99283804-7ea9c400-2803-11eb-8e04-adaec5c5fa84.png)

**Comment by jeremiahwinsley** [comment]
Working in 1.3.9.
