### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by Dissuade3826** [AllTheMods/ATM-6#3203]
### Possible Fixes

No

### Modpack Version

1.9.2

### What happened?

quando coloco o modpack no multiMC ele da esse crash, na versar do curse ele funciona. Alguém sabe me dizer o porque, e como faço para ler o crash log? 

### Crash Log

<script src="https://gist.github.com/Dissuade3826/43e2a9be57afbcf0b66d74c3c2c0fef0.js"></script>

**Comment by jeremiahwinsley** [comment]
Java 17 isn't supported, you need Java 8 or 11.

**Comment by Dissuade3826** [comment]
It worked with Java 11, but why does CurseForge work normally with Java 17? Does the error normally appear in the same part of the crash log? and could you tell me where?
thank you very much

**Comment by jeremiahwinsley** [comment]
Curseforge does not use Java 17, it uses the built-in Java from the vanilla launcher.

Error message is not always in the same spot, but this is where the error message is in your gist: https://gist.github.com/Dissuade3826/43e2a9be57afbcf0b66d74c3c2c0fef0#file-gistfile1-txt-L136

Exception message: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @c7443f

And that is an error we've seen before when using Java 17.
