### ISSUE TITLE
[Bug]: apiary not craftable

### ISSUE THREAD

**Issue by Neee32** [AllTheMods/ATM-6#3205]
### Possible Fixes

Yes

### Modpack Version

1.9.2

### What happened?

the apiery from resourcefulbees is not craftable in the latest version of the pack
![image](https://github.com/AllTheMods/ATM-6/assets/154700769/5e5f67cb-00be-4cfa-b0ea-39e71bb4b4ca)

### latest.log

https://gist.github.com/Neee32/a364cd31dfb76e573cdb18da9d4affd2

**Comment by jeremiahwinsley** [comment]
Check the tooltips, you need Tier 4 hives to craft it.
