### ISSUE TITLE
Freezing Problem

### ISSUE THREAD

**Issue by Kalec-N** [AllTheMods/ATM-6#3206]
### What would you like to know?

So the game launches fine, but as soon as I load into the world I get maybe 2.5 seconds before a freeze that lasts about 4-9 seconds. This loops forever. I set my ram to 8-9gb. I have tried updating mods, changing settings, more ram, less ram, idek anymore.
This happens no matter where in the world I am, as I can just barely teleport within these short windows. To be clear this is not an empty world, but one I've played in for awhile.

Please advise.

**Comment by jeremiahwinsley** [comment]
I suspect you may need to add a bit more RAM, it's not uncommon to need 10-12 on big worlds. Press F3 and check the ram percentage in the top right (and make sure the amount shown is actually what you put in). If it's going past 90% when the spike happens, that's your issue.

**Comment by Kalec-N** [comment]
Thank you. o/
