### ISSUE TITLE
[Crash]: the game freezes while loading

### ISSUE THREAD

**Issue by gel1use** [AllTheMods/ATM-6#3212]
### Possible Fixes

Yes

### Modpack Version

1.9.2

### What happened?

everything worked, I decided to log in a month later and the game just freezes at the loading stage (the disk is loaded at 0, the processor is at 0) I tried a bunch of different versions and different forges, reinstalled windows, launcher and java (sorry for my English, I'm from Russia)

### Crash Log

https://securelogger.net/files/8e57cd85-2502-4e4f-9529-3af781b2d8e1.txt

**Comment by jeremiahwinsley** [comment]
We do not support cracked launchers.
