### ISSUE TITLE
[Bug]: Incomplete set of tags

### ISSUE THREAD

**Issue by unnamedfurry** [AllTheMods/ATM-6#3213]
### Possible Fixes

Yes

### Modpack Version

1.9.2

### What happened?

(Note: the text has been translated from another language, so it may contain errors or strange phrases)

Hello
I am the creator of a small server based on ATM6 mods
When I tried to log in to the server, I get kicked from there for the reason: incomplete set of tags
I looked at the logs, and it turned out that most likely the client was missing some mod configs
Can you try to fix it?
And, can I use another site for logs, where IP addresses and folder names are hidden, and it is more convenient to watch?

https://mclo.gs/xsHRaEl - server logs
https://mclo.gs/WrkdTlm - client logs

### latest.log

https://mclo.gs/xsHRaEl  https://mclo.gs/WrkdTlm

**Comment by Mitchell5200** [comment]
That Server Log seems very short, and if that's the whole file, then it appears that the server is running at best, without any mods, and at worst, fully vanilla, I'd recommend you do a reinstall of the atm6 server files to the server.
