### ISSUE TITLE
1.3.0 Ice and Fire Manuscript are not consumed

### ISSUE THREAD

**Issue by GQuan1975** [AllTheMods/ATM-6#322]
Ice and Fire Manuscript are not consumed after add page to the Bestiary.

1) Open Bestiary lectern
2) Add page
3) Leave Lectern
4) go back to the lectern and manuscript are still there.

Expected behavior
Used manuscripts should be removed.

**Comment by Pdiddy973** [comment]
fixed in 1.3.9 pack version
