### ISSUE TITLE
Using Cylclic Item User for Mystical Agriculture

### ISSUE THREAD

**Issue by Kvikne** [AllTheMods/ATM-6#323]
As the title says i want to use the item user from Cyclic with seeds and watering cans from Mytsical Agriculture.
The Setup I've tried on a creative singleplayer world is with an item user set on 1 tick delay and set to ignore redstone (so its always active).
Then I've put in a Supremium Watering Can from Mystical Agriculture (filled with water).
![image](https://user-images.githubusercontent.com/74249666/99196717-7e231600-278e-11eb-93db-10c83cdff73b.png)
On my SP world it seems to be running perfectly fine.
If i try the exact same setup on my multiplayer server it won't work. Neither collecting, nor the watering effect happening.
I've looked through all the config files and just can't seem to find any setting to allow the item user to interact with Mystical Agriculture things.

Am I missing something? Or is there a reason for it not being able to work on multiplayer?
Pleas help thanks :)

**Comment by andrewsf** [comment]
If it works in single player and it doesn't work on a dedicated server, it's a Cyclic bug.

**Comment by KingsRoyalDragon** [comment]
yeah, im having this issue as well.
