### ISSUE TITLE
long wait to login to ATM6 Server.

### ISSUE THREAD

**Issue by demethan** [AllTheMods/ATM-6#324]
Hi, I am posting this here to see if someone else is having this issue and how did you fix it. 

We run multiple servers at Breakfastcraft and haven't encountered this issue before.  We pre-generated the world before putting it in the server and we had to fix the level.dat for the nether not working.  But other than that everything is good. 

We have one issue where the login time to the server is abnormally long.  10-30 seconds long.  Anyone have an idea where that issue is coming from? 

We are currently running ATM6 1.3.0

**Comment by NetMasterFlex** [comment]
I would be in heaven if joining my server world took between 10 and 30 seconds. Please tell me your secret. 

Seriously there have been at least 10 to 15 more mods added and if your clients on connecting via a WAN there could be a number that of reasons why it’s taking longer. 

When you say you pre-loaded the world are you saying it’s a brand new world?  I’ve been told that entering a world for the first time can take longer than normal, but then get better over time. 

IMHO there are too many variables to expect an answer here. Especially when there haven’t been an overwhelming number of complaints about this issue. 

I’m running a server in Southern CA and had. Couple users connect from Sacramento CA ~600 miles away, and load time was about 5-7 minutes. 

NMF

**Comment by demethan** [comment]
Hi,  let me add some details.  I don't mean the loading time of the pack.. Its modded Minecraft and are all too familiar with the huge loading times.  I am talking about the time it takes to get to play on the server after you click the connect button on that server.  usually between 5 -15 seconds.   Also, I said, pre-generated not preloaded.  Meaning we have generated all the chunks in single-player before copying the world folder to the server.  I agree that there are many variables and digging for an issue by myself would be almost impossible. This is why I posted it here. I would appreciate it if you leave the issue open. Maybe someone else will find this and have a solution.  Thanks and keep up the good work.

**Comment by eliminat** [comment]
My "Loading Terrain" screen stays up for more than a minute while joining server, during which time I'm in the game technically (been killed when I had logged off in an unsafe area) but nothing on the screen and no control.
I wasn't sure if it was just me or not.
 I believe this is similar to what you're describing.

**Comment by Retrodynen** [comment]
why was this closed? :/
