### ISSUE TITLE
Duping enchants in cyclic disenchanter with Quark tomes.

### ISSUE THREAD

**Issue by SigmaChi07** [AllTheMods/ATM-6#325]
As the description reads, when placing Quark enchanted "tomes" into a cyclic disenchanter it will "rip" the enchant off as intended, but does not remove the enchant or use up the tome. Obviously not working as intended because I just kept creating fortune 3 enchanted books via this method. 

Not sure if I should report it to cyclic or quark, or both. Advice?

**Comment by HsOhLiYt** [comment]
No advisement, but have confirmed issue. All "Ancient Tomes" seem to allow for infinite disenchantment @ cyclic disenchanter.

**Comment by jeremiahwinsley** [comment]
Reported here: https://github.com/Lothrazar/Cyclic/issues/1684

**Comment by jeremiahwinsley** [comment]
Fixed in 1.4.0.
