### ISSUE TITLE
Ars Nouvea Server Crash

### ISSUE THREAD

**Issue by Silverglare** [AllTheMods/ATM-6#326]
**Describe the bug**
When using the ars spell book to cast a projectile spell, If that spell hits a player the server will crash. 

**To Reproduce**
1. Create a projectile spell with Ars Nouvea. 
2. Hit another player with the spell while the pvp is disabled.
3. Server crashes. 

**Expected behavior**
Nothing to happen or what ever effect to apply that is eligible for the target. 

**Screenshots**

**Additional context**
There also seems to be a Server breaking bug when using the Whelp to harvest crops Im not sure if this is related but after summoning a whelp and teaching it Projectile, Harvest and Pickup it will crash the server the first time it harvests. This happened in my teams claimed chunks.

**Comment by ViRb3** [comment]
Please verify if this bug happens with _only_ Ars Nouvea installed and post the report at [the Ars Nouvea issue tracker](https://github.com/baileyholl/Ars-Nouveau/issues). Include logs if possible.
