### ISSUE TITLE
Modular Storage Duping/losing items Bug (ATM6 1.3.0)

### ISSUE THREAD

**Issue by FastHit** [AllTheMods/ATM-6#327]
when you try to sort modular storage it try to take all the items from the storage into your inv, and if you have over a certain amount it can delete the storage module that is there losing all the items
also if you have less items in it, it transfer all the items to your inv and give you the module with all the items still in it duping them.

**Steps to reproduce the behavior:**
just try to sort items in a modular storage

this is a clip showing it, first time duped the items and the second time losing the storage module.
https://imgur.com/a/I6gLOdn

**Comment by ViRb3** [comment]
Tracked at https://github.com/reo-ar/InvTweaksRenewed/issues/26
