### ISSUE TITLE
Different mods

### ISSUE THREAD

**Issue by Advocate13** [AllTheMods/ATM-6#328]
I looked at the mod list on curse forge and the mod list on twitch and the two are different.  Why are they different?  I would like to use the mods from ATM6 on curse forge, but don't know how to turn the zip file into a modpack.  Will the twitch modpack be updated with the mods that are listed on curse forge?  Twitch is easy to use.

**Comment by thevortex** [comment]
what are you talking about....

**Comment by Advocate13** [comment]
Example mods listed on curse forge but not on Twitch:

Blood Magic
bigger reactors
botany pots
chisel and bits
clean cut

and many more.

**Comment by thevortex** [comment]
AHHH now I understand. In the Twitch launcher, click the menu icon in the top left, should look like 3 horizontal bars. then select File -> Settings, then select Minecraft from the list of games. Under the 'Preferred release type' switch to 'beta' and you should see more versions of the modpack appear(some of these pack versions are betas and as such, Twitch will filter them if your defaults are set to the 'Release' option. See if that helps then let me know

**Comment by Advocate13** [comment]
I just noticed that the version on Twitch is .29 and the version on curseforge.com is 1.3.1.  I figured out how to turn the zip drive into an instance on the Twitch launcher.

**Comment by thevortex** [comment]
you are likely missing all the client side mods, that zip is the server pack(i believe) you are only seeing .29 because your Release type is set to 'Release' if you make the adjustment i mentioned then check the versions in the app again, you will see more
