### ISSUE TITLE
Botany Pots No Longer Accepts Magical Soil or Insanium Farmland

### ISSUE THREAD

**Issue by kode0001** [AllTheMods/ATM-6#329]
Cannot place Magical Soil or Insanium Farmland in a botany pot.

1. Start 1.3.0+
2. Place Botany Pot
3. Attempt to insert one of the two soils
4. Nothing happens

**Comment by Selbram** [comment]
All of my insanium botany pots and seeds were voided on upgrade.

**Comment by kode0001** [comment]
Looks like this is due to some changes when KubeJS went from 1.16.3 to 1.16.4 and started using Rhino. Downgrading to the 1.16.3 version allows the recipes to load, but I'm sure introduces more errors. Recipe scripts probably need to be updated somehow to be compatible with the new version.

**Comment by jwesely** [comment]
looks like Rhino doesn't support the spread syntax operator used in the growTree and growTreeSnowflake functions so modifying the script to use Object.assign instead would fix the issue

**Comment by jeremiahwinsley** [comment]
Fixed in 1.3.9.
