### ISSUE TITLE
BluePower

### ISSUE THREAD

**Issue by benjiben55** [AllTheMods/ATM-6#33]
Hey i found another bug that crash the game.

When i search in jei for "BluePower Mod" and hover on magma block the game crash immediately.

[crash-2020-07-31_15.12.19-server.txt](https://github.com/AllTheMods/ATM-6/files/5007170/crash-2020-07-31_15.12.19-server.txt)

**Comment by WhitePhant0m** [comment]
Not caused by hovering over magma block, caused by a vine growing on an mod block that got changed into air when a mod was removed, recommend checking #42 for more information on the same issue, but it had a mod change a block id instead of a mod removal, but the fix is the same.
