### ISSUE TITLE
Missing bees for resourceful bees

### ISSUE THREAD

**Issue by FlamingFlamingo42** [AllTheMods/ATM-6#332]
There is no certus quartz bee for resourceful bees. Osmium is unobtainable with bees as well

**Comment by ViRb3** [comment]
The Osmium bees work just fine here, I've produced more than a million ingots this way. Certuz Quartz bees haven't been added, perhaps that could be done.

**Comment by derrickmehaffy** [comment]
This can be closed as both crystal bees and Osmium bees exist in the latest update

**Comment by Pdiddy973** [comment]
certus quartz is not the same as quartz

**Comment by Pdiddy973** [comment]
added in https://github.com/AllTheMods/ATM-6/pull/815
