### ISSUE TITLE
1.3.1 unable to sethome

### ISSUE THREAD

**Issue by gbusrt** [AllTheMods/ATM-6#334]
deleted my previous world 1.3.0 and loaded 1.3.1 (1.16.4 ) cant seem to use the cmd /sethome
deleted the instance before adding newer release (related ?) 

get this 
Incorrect argument for command at position 8: /sethome<--[HERE]
and after pressing enter the chat say 
Home not found!
/delhome 
Home not found!

**Comment by gbusrt** [comment]
Humm /back not working either
cmd is there it just dose nothing

**Comment by Thunder-Nova** [comment]
Odd... the modpack usually doesn't have any home commands to encourage the use of other teleport methods such as the waystones, and now the Gravestone mods.

**Comment by gbusrt** [comment]
well /teleport works, guess the FTB stuff is switch off or borked

**Comment by tanknet** [comment]
You need to modify the FTB config files
defeaultconfigs\ftbessentials-server.toml
world\serverconfig\ftbessentials-server.toml

**Comment by gbusrt** [comment]
thanks for that did not know which file to change

set no of home to 10 
and changed all the other from  604800 to 0
restarted game 
no change 
:(

**Comment by tanknet** [comment]
this is mine
#Max number of times you can use /back
#Range: > 0
maxBack = 9999999
#Max homes
#Range: > 0
maxHomes = 25
#/back cooldown in seconds
#Range: 0 ~ 604800
backCooldown = 1
#/spawn cooldown in seconds
#Range: 0 ~ 604800
spawnCooldown = 1
#/warp cooldown in seconds
#Range: 0 ~ 604800
warpCooldown = 1
#/home cooldown in seconds
#Range: 0 ~ 604800
homeCooldown = 1
#/tpa cooldown in seconds
#Range: 0 ~ 604800
tpaCooldown = 1
#/rtp cooldown in seconds
#Range: 0 ~ 1
rtpCooldown = 600
#Number of tries before /rtp gives up
#Range: 1 ~ 1000
rtpMaxTries = 10
#/rtp min distance from spawn point
#Range: 0.0 ~ 3.0E7
rtpMinDistance = 1000.0
#/rtp max distance from spawn point
#Range: 0.0 ~ 3.0E7
rtpMaxDistance = 100000.0

**Comment by gbusrt** [comment]
:( must be my install
i copyed and pasted your config and same errors

**Comment by ViRb3** [comment]
#377. You can do `/ftbranks reload` to bring the new configuration into effect.

**Comment by gbusrt** [comment]
humm 
on All the Mods 6-1.3.2c
sethome not working
changed the config file coped tanknet file ran /ftbranks reload
still seeing Incorrect argument for command at position 8: /sethome<--[HERE]
something is getting stuck , i delete the instance and still have the issue
and the report  was closed to :(

**Comment by ViRb3** [comment]
I tested this on ATM6 1.3.2 and it worked just fine. Do you see an existing file `ftbessentials-server.toml` when making the changes? Do you see any error when doing `/ftbranks reload`, either in chat or console?

**Comment by gbusrt** [comment]
i am playing singleplayer so not using the server 
were do i find that file ?

**Comment by ViRb3** [comment]
`/save/serverconfig/ftbessentials-server.toml` I suppose.

**Comment by gbusrt** [comment]
great that was correct for the file 
i copied tanknet file ran /ftbranks reload
and it seams to be working 
i was adjusting the file in 
/defaultconfigs 
when i should have done the file in 
/saves/New World/serverconfig/ftbessentials-server.toml.
doh my bad
thanks for the help 
:)
