### ISSUE TITLE
Issue Opening Pack in Multi MC Launcher

### ISSUE THREAD

**Issue by LadyPort** [AllTheMods/ATM-6#335]
Hello, 
I downloaded the pack on Multi MC. It installed fine, but when I make a new world it loads to the 100% screen and just stays there.  I have dedicated a max of 9070MB of ram to the launcher, and it is on the latest version. I have even let the pack sit open for over an hour. Can anyone help me with this issue?

**Comment by NetMasterFlex** [comment]
Trying using either 8192MB or 9216MB. That memory.  Both values above are valid memory amount increments. 

See if that is your issue. 

NMF

**Comment by slebreton79** [comment]
I am also experiencing this.

**Comment by LadyPort** [comment]
Just to update, I deleted the  pack and reinstalled to the latest version. I used both of those ram values and it still only loads to 100% and stops.

**Comment by xNailgunx** [comment]
I am having the same problem

**Comment by fuelhauler** [comment]
Have a 24 hour old world that is experiencing this issue. Went to load it up to do some off stream work and it just freezes.

**Comment by Pdiddy973** [comment]
should be better in version 1.4.0
