### ISSUE TITLE
Unable to open chests

### ISSUE THREAD

**Issue by Merthew** [AllTheMods/ATM-6#336]
**Describe the bug**
Unable to open chests.

**To Reproduce**
1. right click on chest
2. wait
3. nothing happens

**Expected behavior**
The chest should open.

**Screenshots**
![2020-11-18_22 40 22](https://user-images.githubusercontent.com/23420800/99618379-37802680-29ef-11eb-90e7-632eea0d7a4e.png)
(sat there with the chest block open but no screen showing up for a while)
**Additional context**
Just downloaded the pack today, so it should be newest version.

**Comment by ViRb3** [comment]
Are you running a server? Have you added or removed any mods from the server? Does the console say anything? This happened to me when I removed the Rats mod and the console was full of errors.

**Comment by Merthew** [comment]
I have made no changes to the pack

**Comment by razma417** [comment]
Having the same issue on the newest release. Running a server with a friend and he can't open chests but I can. Neither of us were OP's, tried setting both of us to one and it didn't fix it.

**Comment by ViRb3** [comment]
Did you create a team, claim the chunk where the chest is, and forget to invite your friend to the same team? Claimed chunks will prevent outsiders from using any items in them.

**Comment by Thunder-Nova** [comment]
There are 2 claim systems, one from FTBteams and one from minecolonies.

FTBteams access: Inventory, upper left corner there is a map icon, and then access the ally icon and both you and your friend must ally each other

Minecolony: There is an option to add friends and enemies into claims, you have to add their name manually into a page (red notes on the left) in the Town Hall's main block

**Comment by razma417** [comment]
We setup claimed chunks through FTBteams after this issue was already occurring. He's not able to open any chests in the world such as in random villages or broken down nether portals. If he claims a chunk and builds a new chest and places it down it still doesn't work. It's only with wooden chests. An Iron chest works and so do barrels

**Comment by eggaroonie** [comment]
I'm currently having this issue, I've just downloaded the pack, and have made no changes to it. I'm playing on a singleplayer world with no claimed chunks.

**Comment by kniet** [comment]
I'm having the same issue right now
