### ISSUE TITLE
Idk how much ram do i need to play this modpack.

### ISSUE THREAD

**Issue by CalualaMic** [AllTheMods/ATM-6#337]
So...this modpack is awesome but i cant load it (i mean i stayed one hour then i closed the game cuz the class started) and i think my ram its the problem. I have 4gb ram. PLease tell me how much ram do i need!
Edit:If it works on 4gb ram and it need to load like 2 hours and run like 30 fps its okay but if it need more pls tell me.

**Comment by NoahHagberg** [comment]
4gb ram allocated to the pack or 4gb system total?

**Comment by CalualaMic** [comment]
4gb total and i allocate all of them to the pack

joi, 19 nov. 2020, 11:54 NoahHagberg <notifications@github.com> a scris:

**Comment by CalualaMic** [comment]
Soooo... my classes are done and i started the game i stayed frickin 2 hours and its remain at Remap Complete. Mod Load complete-218 mods loaded. THEN...IT FREEEEEEEEEEEEEEEEEEEZE

**Comment by Noobeld** [comment]
4GB total isn't enough, you'd want ideally 8GB.

You'll want even more if you want to use higher res texture packs too.

**Comment by CalualaMic** [comment]
Well i was planing to buy a pc with 8gb ram thats enough?

joi, 19 nov. 2020, 16:41 Noobeld <notifications@github.com> a scris:

**Comment by Noobeld** [comment]
If you can afford it I'd go for 16GB, that should last you a good long time.

But if money is tight then 8GB should do.

**Comment by CalualaMic** [comment]
Ok then i buy 8gb

joi, 19 nov. 2020, 16:49 Noobeld <notifications@github.com> a scris:

**Comment by ViRb3** [comment]
My players and I have been running with 6GB RAM allocated to Java on the client and there have been zero issues. Granting more memory will only really delay memory leaks, which also has a limit when your game will start stuttering anyway.

**Comment by NetMasterFlex** [comment]
@ViRb3 so are you saying that assigning 6144MB of RAM will and does work?  8192MB is not required to run the ATM6 v1.3.1 modpack also assuming no resource packs or Optifine is used?

**Comment by ViRb3** [comment]
@NetMasterFlex My players and I use Optifine, no shaders or resource packs, and we have had zero issues. I'm not aware of Optifine reducing memory usage, so I would say yes, 6GB should be enough for your use case.

**Comment by whatthedrunk** [comment]
I would use 8 for most modern large packs but if you have nice specs you can get away using less.
