### ISSUE TITLE
Game crashes from Twitch Launcher

### ISSUE THREAD

**Issue by NTMILO** [AllTheMods/ATM-6#339]
![image](https://user-images.githubusercontent.com/74712278/99657757-8aaeb380-2a99-11eb-8eb0-a9bef932b586.png)

**Comment by ViRb3** [comment]
Show logs please, or we can't help with anything.

**Comment by BassCannon13** [comment]
I have the same error as the OP with this error in the logs. Tried uninstalling and reinstalling the mod pack but the missing client.jar never gets made and I am unsure how to get it to appear.


![Forge error](https://user-images.githubusercontent.com/74789945/99834904-c2107500-2b18-11eb-8bc9-e8c5afd4c828.JPG)

**Comment by Jordash04** [comment]
im having the same exact problem. will u guys let us know how to fix in here?

**Comment by Jordash04** [comment]
![logs](https://user-images.githubusercontent.com/74799288/99861003-00765600-2b52-11eb-9479-a8c59bf78060.PNG)

**Comment by Jordash04** [comment]
thats the last part of the logs

**Comment by ViRb3** [comment]
Are you running through Twitch? There's a known problem with Twitch installing Forge on 1.15/1.16. Check below for workaround:
https://www.reddit.com/r/MinecraftForge/comments/hqmuty/failed_to_find_minecraft_resource_version/

**Comment by HiImCruor** [comment]
I am having this same problem and need help fast!

**Comment by ViRb3** [comment]
More details from the ATM6 discord bot:

> Twitch launcher is known for having multiple issues on anything above 1.12, and as an alternative we are officially supporting the MultiMC for ATM modpacks, download and update packs just like with twitch, but working on all minecraft versions and having a better overall user experience

### Download the MultiMC from their website here
https://multimc.org/#Download

### How to Install
https://gyazo.com/e2e56187a7e779f74df8f1d8586555b8
