### ISSUE TITLE
curse of breaking broke my world

### ISSUE THREAD

**Issue by goodmangammering** [AllTheMods/ATM-6#34]
while exploring one of the dungeons i got a golden shovel with a few enchantments and when i used it to collect some sand it worked at first but then it stopped giving me blocks, but whats even weirder is that even not using the shovel it stopped giving me blocks all together, even after removing it from my inventory 
![Screenshot_4](https://user-images.githubusercontent.com/12856850/89088974-f80ecb00-d368-11ea-956d-93b435bb6050.png)

**Comment by whatthedrunk** [comment]
We are currently on 1.16.3 so removing older issues to make way for new ones. If you want to test it out join the discord for an early beta. New update will be on Twitch / Curseforge once Mekanism pushes their update to the site.
