### ISSUE TITLE
Minecraft server

### ISSUE THREAD

**Issue by FrostZFish** [AllTheMods/ATM-6#340]
How to make the server more stable? The server is allocating 10GB memory. Is it enough? 
Also, sometimes I found "server overloaded? 40 ticks behind" in the server console. How to solve it?

**Comment by NoahHagberg** [comment]
One suggestion is to use a chunk pregenerator, it got rid of all the server overloaded messages for me but requires more disk space. Are you using an ssd or hdd?

**Comment by FrostZFish** [comment]
what is chunk pregenerator? also, the server is running in my ssd .

**Comment by NoahHagberg** [comment]
A chunk pregenerator is a tool which generated the world without a player actually travelling. I used this:
[https://www.curseforge.com/minecraft/mc-mods/world-pre-generator](url)
It's only required on the server and can be used overnight since playing with it running is probably a bad idea.

**Comment by ViRb3** [comment]
The server RAM is not that big of a big factor, unless you have _a lot_ of players. I have been hosting two servers for <10 people and 8GB RAM has been more than enough. Use a plugin like [Spark](https://github.com/lucko/spark) and run `/spark healthreport` - it will give you current TPS, used RAM, used CPU. Further, you can run `/spark profile` to generate a report which tells you why your server is lagging with `running 40 TPS behind`.

**Comment by FrostZFish** [comment]
Actually i don't know how to add plugin for the modded server
