### ISSUE TITLE
Nether does not work.

### ISSUE THREAD

**Issue by Bearman1989** [AllTheMods/ATM-6#341]
**Describe the bug**
After updating my server yesterday, I am unable to get to the nether via the portal or a waystone.  The portal will just do the animation but not port, and the waystone option is there but nothing happens when you click it.

**To Reproduce**

**Expected behavior**
I expected to be brought to the nether.
**Screenshots**

**Additional context**
The server was just updated to the newest version.

**Comment by NoMoreStars** [comment]
Just encountered the same problem, looks like it's a duplicate of #137.

**Comment by whatthedrunk** [comment]
https://github.com/AllTheMods/ATM-6/issues/137
