### ISSUE TITLE
Stuck on Stopping server

### ISSUE THREAD

**Issue by lilwilisjr** [AllTheMods/ATM-6#344]
**Describe the bug**
After Typing "stop" in the console, it gets stuck after it unloads fluxnetworkdata and then just sits there and nothing ends up happening

**Expected behavior**
i expected it to pause not freeze

**Additional context**
[https://pastebin.com/ZaLn22jh](url)

**Comment by ponduzn** [comment]
Same happens here. But i can still press CTRL + C, then Y to stop completely. 
It will not auto- restart though.

**Comment by ViRb3** [comment]
I can confirm this issue has been there from the very beginning. Seems like a mod is not unloading properly. I will try to track this down soon.

**Comment by lilwilisjr** [comment]
Stopped happening for me @ 1.3.0 but came back at 1.3.2c

**Comment by lstrobel** [comment]
This is happening to me on 1.3.6b
