### ISSUE TITLE
[Applied Energistics 2] Spatial IO feature not functioning

### ISSUE THREAD

**Issue by DaRandom** [AllTheMods/ATM-6#346]
I have a server that has been running 24/7 for a few weeks now and me and my friend decided to play around with the Spatial Storage feature from AE2 only to find out it doesn't function on the server. I have tested various things and it doesn't seem to work.

From my limited testing it appears to be some sort of conflict with the world generation of Biomes O' Plenty. This can easily be replicated by creating 2 different worlds, one with vanilla terrain generation and another with the "Biomes O' Plenty" preset. And once in the world, setting up a 2^3 simple setup consisting of a few Spatial Pylons, Spatial IO Port, Creative Energy Cell and any preferred cable. (Or go with the max size if you want, I won't judge :-) )

Any ideas as to how to fix this? I would prefer not to create a new world solely to make one feature work properly.

**Comment by kill05** [comment]
This is a compatibility issue, report it either on ae2's github or biome of plenty's

**Comment by bls220** [comment]
@DaRandom, I found a work around if you are a bit savy with NBTExplorer

https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4842

**Comment by DaRandom** [comment]
> 
> 
> This is a compatibility issue, report it either on ae2's github or biome of plenty's

It seems @bls220 beat me to it. But thanks anyway!

> 
> 
> @DaRandom, I found a work around if you are a bit savy with NBTExplorer
> 
> [AppliedEnergistics/Applied-Energistics-2#4842](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4842)

Okay I see, thanks for the suggestion! However do note that it simply changes the level generator settings and as such generating new chunks will cause them to not quite fit with the existing chunks. In any case it's not the end of the world to not have the spatial storage feature working. Not to undermine your suggestion though! I hope this can be resolved with the mod authors and get updated with the modpack. Thanks.

**Comment by Pdiddy973** [comment]
BOP worlds shouldn't be used, we use BYG for biomes. BOP is left in for legacy reasons when the team was trying to have BOP and BYG biomes, but only ended up using BYG.
