### ISSUE TITLE
Nether and The End dimension doesnt work.

### ISSUE THREAD

**Issue by Najiro11** [AllTheMods/ATM-6#347]
**Describe the bug**
I updated the pack to 1.3.1 today and when i try to go through the nether portal, it will infinitely spin my screen, but never load the Nether. And when i try to go through the end portal, i just fall through it, but never load The End either. I tried it on different world and it worked fine.

**Expected behavior**
I dont have any idea where is the problem.

**Screenshots**
![2020-11-20_23 03 07](https://user-images.githubusercontent.com/53948694/99854402-0c2f4000-2b85-11eb-96b2-3c764fc6d1d8.png)
![2020-11-20_23 03 27](https://user-images.githubusercontent.com/53948694/99854452-21a46a00-2b85-11eb-9fa1-3285f5db9150.png)
![2020-11-20_23 02 58](https://user-images.githubusercontent.com/53948694/99854379-0174ab00-2b85-11eb-907b-a87241d3fc94.png)

**Additional context**
I tried to completely reset my nether and End by removing the DIM file and replacing it with new one, but that doesnt help either. 

I dont know if these screenshots will help but i posted them anyway.

**Comment by whatthedrunk** [comment]
https://github.com/AllTheMods/ATM-6/issues/137
