### ISSUE TITLE
/back command issue

### ISSUE THREAD

**Issue by Treadish** [AllTheMods/ATM-6#350]
just wondering why /back cmd dont work? does any1 know how to fix this problem?

**Comment by ViRb3** [comment]
What do you mean by /back doesn't work? What happens when you type in the command? What do you expect to happen?

**Comment by tanknet** [comment]
You need to modify the FTB config files on the server
defeaultconfigs\ftbessentials-server.toml
world\serverconfig\ftbessentials-server.toml

**Comment by Treadish** [comment]
> You need to modify the FTB config files on the server
> defeaultconfigs\ftbessentials-server.toml
> world\serverconfig\ftbessentials-server.toml

It is on but the reply when you do /back is: teleportation history is empty

**Comment by ViRb3** [comment]
I reckon you need to die to be able to use `/back`. Not sure if any other events are supported.
