### ISSUE TITLE
ERROR Error processing element Queue ([Appenders: null]): CLASS_NOT_FOUND

### ISSUE THREAD

**Issue by Kahlui** [AllTheMods/ATM-6#352]
**Output at start   https://pastebin.com/wMJzgGFs **
Version 1.3.1

**To Reproduce**
Start a fresh server

**Expected behavior**
Server Installs and starts

**Additional context**
Most Recent Update of java Fails to start after install

[debug.log](https://github.com/AllTheMods/ATM-6/files/5578346/debug.log)
[debug-1.log.gz](https://github.com/AllTheMods/ATM-6/files/5578347/debug-1.log.gz)
[debug-2.log.gz](https://github.com/AllTheMods/ATM-6/files/5578348/debug-2.log.gz)
[latest.log](https://github.com/AllTheMods/ATM-6/files/5578349/latest.log)
[2020-11-21-1.log.gz](https://github.com/AllTheMods/ATM-6/files/5578350/2020-11-21-1.log.gz)
[2020-11-21-2.log.gz](https://github.com/AllTheMods/ATM-6/files/5578351/2020-11-21-2.log.gz)

**Comment by ViRb3** [comment]
What version of Java is that? Not all are supported by Forge. You'd have to ask on their Discord to get a definite answer, but I recall Java 14 and 15 __not__ being supported.

**Comment by Kahlui** [comment]
1.8.0_271

**Comment by ViRb3** [comment]
What launcher are you using? Please try #339.

**Comment by Kahlui** [comment]
This is the server. Direct download from curse

**Comment by Kahlui** [comment]
I have reinstalled java with no luck. when i copy the files to another computer they work.

**Comment by ViRb3** [comment]
Then there must be something different in your computer. Make sure you have the same version of Java and use MultiMC as suggested above. Try to make as clean install as possible. Apart from that, I can't help much more.

**Comment by monik3r** [comment]
This could be something to do with nogui & the UI attempting ot load on a headless server. Also seeing this with openjdk 8u.
