### ISSUE TITLE
Vanilla blocks are white on minimap(1.3.1)

### ISSUE THREAD

**Issue by LastBubka** [AllTheMods/ATM-6#353]
I played for a bit, didn't like the map I got, so decided to make a new one.
Once loaded all vanilla minecraft blocks on minimap were pure white. Dirt, stone, grass, snow :D 
On top of that I couldn't delete my old save, because the game was still using it.

When I restarted map was still the same, but at least I could delete the old save.
New maps I create have the same issue as well, so I have no idea how to recreate it or anything. It just happend.

**Comment by tanknet** [comment]
I had the same problem.  Resolved it by deleting atm6 install and doing clean install.

**Comment by akasia** [comment]
that is not bug is just setting on map setting just need open map and setting that set Noise to 0.05 and Shadows to 0.10 that shud settel the issuse

**Comment by jeremiahwinsley** [comment]
Fixed in 1.3.9.
