### ISSUE TITLE
Cyclic item user 

### ISSUE THREAD

**Issue by Sqelp** [AllTheMods/ATM-6#354]
I play on my server and i wanted to automated beehive but it just doesn't seem to be working for me. but it work fine in my test world

**Comment by DeathOfTime** [comment]
are you using a scraper? are you in a claim? shears don't work and some items don't work in claims

**Comment by Sqelp** [comment]
yeah i do use a scraper and my chunks are claim

**Comment by Sqelp** [comment]
well turn out that when i unclaim the chunk it work just fine

**Comment by DeathOfTime** [comment]
try unclaiming the chunk and possibly giving the block a redstone signal. like a lever. cyclic is kinda buggy about its interface and doesn't always show some stuff properly like radius and whether or not it needs redstone

**Comment by DeathOfTime** [comment]
known issue. you can try allying it, but it likely won't work properly. dispensers do work. just requires more of a setup

**Comment by DeathOfTime** [comment]
https://discord.com/channels/254530689225981953/718184093531242618/779653402447577118 this might help
