### ISSUE TITLE
Loading Save Crash

### ISSUE THREAD

**Issue by monsterma32** [AllTheMods/ATM-6#358]
After saving my world and logging off the next day I try to launch into my save and now it's not loading and just gets stuck, looking into the game output it appears to have crashed. If anyone can tell me why this is happening or how to fix it, I would much appreciate it.
These are the last lines in the game output before the crash if they help.
![crash](https://user-images.githubusercontent.com/56120368/99910261-ffad0380-2cba-11eb-8988-2f02adef83b7.PNG)
I can provide any additional info needed as well.

**Comment by ViRb3** [comment]
Same issue as #370. Try deleting your `travel_anchors-server.toml` and restarting server.
