### ISSUE TITLE
Blood Magic Features Missing/Not Working

### ISSUE THREAD

**Issue by KingPsychospud7** [AllTheMods/ATM-6#359]
Much of blood magic is currently unusable, including many alchemy arrays

**Comment by galfalek** [comment]
The mod is in developement for 1.16, so wait for update. For the array all of them work fine.

**Comment by KingPsychospud7** [comment]
I was unable to create several of the arrays, such as the teleport array, skeleton turret array, movement array, etc.

**Comment by galfalek** [comment]
I'm not familiar with everything in blood magic, but since none of the things you talk appear in JEI it means they are not ported to 1.16 yet, so wait for them to do so.

**Comment by ViRb3** [comment]
I believe @galfalek answered this question.
