### ISSUE TITLE
Server crash on startup

### ISSUE THREAD

**Issue by Someoneamzing** [AllTheMods/ATM-6#36]
Downloaded the latest server pack from curseforge but the server crashes immediately on startup.

The install went fine and it asked for the Eula agreement then crashed with the message:
```
kotlin.TypeCastException: null cannot be cast to non-null type kotlin.String
	at atm.bloodworkxgaming.serverstarter.ForgeManager.startServer(ForgeManager.kt:163)
	at atm.bloodworkxgaming.serverstarter.ForgeManager.handleServer(ForgeManager.kt:42)
	at atm.bloodworkxgaming.serverstarter.ServerStarter.startLoading(ServerStarter.kt:184)
	at atm.bloodworkxgaming.serverstarter.ServerStarterKt.main(ServerStarter.kt:195)
```

this crash happens on every startup.

would attach a crash log but it hasn't generated one.
Have the server starter log file although it's empty so cant attach that either.

**Comment by whatthedrunk** [comment]
We are currently on 1.16.3 so removing older issues to make way for new ones. If you want to test it out join the discord for an early beta. New update will be on Twitch / Curseforge once Mekanism pushes their update to the site.

**Comment by lancepioch** [comment]
Figured this one out with the latest version, posting the solution here for anybody that stumbles upon this thread...

Issues happens roughly here: https://github.com/BloodyMods/ServerStarter/blob/be94470e4b51e06660d9d973af5484632d31d355/src/main/kotlin/atm/bloodworkxgaming/serverstarter/LoaderManager.kt#L169

You need to add `level-name=something` to your `server.properties` file and the server boots right up.

**Comment by Rototu** [comment]
> Figured this one out with the latest version, posting the solution here for anybody that stumbles upon this thread...
> 
> Issues happens roughly here: https://github.com/BloodyMods/ServerStarter/blob/be94470e4b51e06660d9d973af5484632d31d355/src/main/kotlin/atm/bloodworkxgaming/serverstarter/LoaderManager.kt#L169
> 
> You need to add `level-name=something` to your `server.properties` file and the server boots right up.

Can confirm this works! Thanks a lot for the tip <3
