### ISSUE TITLE
Offline Chunk Loading

### ISSUE THREAD

**Issue by FlambeSk** [AllTheMods/ATM-6#360]
Can anyone help me, how to achieve offline chunk loading?
FTB chunks works only when player is online. I can't find any other mod in 1.16.4 version for offline chunk loading.

Thanks everyone for help.

**Comment by DeathOfTime** [comment]
isn't the really what you want. but as long as one chunk is force loaded in the overworld a 19*19 chunk area centered on spawn is always fully loaded

**Comment by FlambeSk** [comment]
Okay, so I made my server keep chunks loaded even I am offline. I did little change in FTB Chunks mod: [This change](https://github.com/FTBTeam/FTB-Chunks/pull/54), and now it's working.
