### ISSUE TITLE
Dank Duplication/ invtweaks 

### ISSUE THREAD

**Issue by dextris2** [AllTheMods/ATM-6#361]
**Describe the bug**
any item that is selected red in the dank will stay in the dank when the extract button is used and will duplicate the item to the player inventory 

**To Reproduce**
1. Move item to dank CTRL click an item to lock it 
2. Click on extract item using inventory tweaks. 

**Expected behavior**
Items will be duplicated 

**Screenshots**

**Additional context**

**Comment by Pdiddy973** [comment]
seems fixed in 1.3.9
