### ISSUE TITLE
[1.3.1] Certus Quartz and Fluix Essence Recipe Dupes

### ISSUE THREAD

**Issue by Sadumon** [AllTheMods/ATM-6#363]
Both Certus Quartz Essence and Fluix Essence have two recipes for a ring of 8 -- one for 6 of the resource, and one for 12.  In the crafting table you can switch between outputs but in things like AE2 crafting terminals you can only get the 6.

**Comment by jeremiahwinsley** [comment]
Fixed in 1.4.0.
