### ISSUE TITLE
DrawBridge Issue

### ISSUE THREAD

**Issue by xGitBlue** [AllTheMods/ATM-6#364]
Version: 1.3.1
Mod: Tinker's mechworks
Item: Drawbridge
Issue: When i try to place Down A drawbridge and Give it a redston signal, The bridge doesn't get builded.

**Comment by xGitBlue** [comment]
The problem is In Claimed Chunks. Even if i try to Ally the Fake Player it's not working

**Comment by kill05** [comment]
Can confirm, but this is a compatibility issue. You should report it on tmechworks' github.

**Comment by xGitBlue** [comment]
oh ok thanks you i will try to report. I am new to Github so i am trying to understand how to be helpful

**Comment by fuj1n** [comment]
The issue seems to be with FTBChunks itself, https://github.com/FTBTeam/FTB-Chunks/issues/58 https://github.com/FTBTeam/FTB-Chunks/issues/59 (in 59, check comment)

**Comment by fuj1n** [comment]
Update: should be fixed as of FTB Chunks 2.1.50

**Comment by Pdiddy973** [comment]
should be resolved in pack version 1.3.9
