### ISSUE TITLE
Loading world crash - Failed loading config file

### ISSUE THREAD

**Issue by Thomas12211** [AllTheMods/ATM-6#370]
I am playing All the Mods 6 with twitch launcher and I accidentally closed my game out without pressing save and quit, So idk if thats the problem with it but the game launches up fine its just when I try and load into the world it just loads and if I click on the screen it says its not responding so I do not know what to do. I've looked through the crash reports to try and find something in there so hopefully you guys could help me with it. 

[https://pastebin.com/qU8amMPu](https://pastebin.com/qU8amMPu) thats the link to the crash log

**Comment by ViRb3** [comment]
```
net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigLoadingException: Failed loading config file jumbofurnace-server.toml of type SERVER for modid jumbofurnace
```

Seems like your `jumbofurnace-server.toml` config got corrupted. Delete it from the server and restart.

**Comment by Thomas12211** [comment]
> ```
> net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigLoadingException: Failed loading config file jumbofurnace-server.toml of type SERVER for modid jumbofurnace
> ```
> 
> Seems like your `jumbofurnace-server.toml` config got corrupted. Delete it from the server and restart.

Okay so I got rid of the jumbo-furnace-server.toml and I read the crash log and then it says range-pumped-server.toml was corrupt so I deleted that and then it said another toml server file was corrupt so I don't know what is going on

**Comment by ViRb3** [comment]
Have you tried re-installing the modpack? I've never come across this issue before.

**Comment by Thomas12211** [comment]
> Have you tried re-installing the modpack? I've never come across this issue before.

Yeah, that actually worked for me thank you, but I saved the save and now the nether isnt working for some reason I don't know why I tried deleting DIM-1 to maybe it create a new nether but nothing happens I go into the portal it doesnt teleport me anywhere I just stay in the portal you think you can help me?

**Comment by ViRb3** [comment]
https://github.com/AllTheMods/ATM-6/issues/137
