### ISSUE TITLE
Multiple Jei Crashes possibly do to elemental craft

### ISSUE THREAD

**Issue by DeathOfTime** [AllTheMods/ATM-6#372]
Game crashes when clicking on stuff in jei. clicking on wither bee, dragon bee, information tab of red card. always references elemental craft in the crash log

**To Reproduce**
1. Go to jei
2. Click on dragon bee
[crash-2020-11-23_19.14.14-client.txt](https://github.com/AllTheMods/ATM-6/files/5587055/crash-2020-11-23_19.14.14-client.txt)
[crash-2020-11-23_20.18.50-client.txt](https://github.com/AllTheMods/ATM-6/files/5587056/crash-2020-11-23_20.18.50-client.txt)
[crash-2020-11-23_20.31.42-client.txt](https://github.com/AllTheMods/ATM-6/files/5587057/crash-2020-11-23_20.31.42-client.txt)

**Comment by Sirttas** [comment]
fixed in elementalcraft

**Comment by ViRb3** [comment]
Dupe of #371
