### ISSUE TITLE
Pilfering enchantment dupes minecolonies' guard armor

### ISSUE THREAD

**Issue by gatlinggun2003** [AllTheMods/ATM-6#376]
**When you fish guards with any kind of armor with a pilfering rod, it will give you the armor while they keep their set in their inventory**

**To Reproduce**
1. Find or fish a book/fishing rod with 'Pilfering' enchantment
2. Build a minecolonies guard tower and assign someone as a 'Knight/Archer'
3. Give them any kind of armor
4. When they wear it, hook them with the rod
5. And finally by right-clicking them and go to their inventory. Armor DUPED

**Screenshots**

![2020-11-24_13 30 58](https://user-images.githubusercontent.com/74948786/100053025-26557080-2e5a-11eb-9c40-c68a5f94a1ad.png)

![2020-11-24_13 32 58](https://user-images.githubusercontent.com/74948786/100053287-ac71b700-2e5a-11eb-8436-e84e16846a33.png)

![2020-11-24_13 33 56](https://user-images.githubusercontent.com/74948786/100053476-1722f280-2e5b-11eb-8134-6632186010c9.png)

**Additional context**
This will likely be used on OP gear.

**Comment by ladylexxie** [comment]
Finally fixed :thonk:
