### ISSUE TITLE
Sapling not working in BotanyPots

### ISSUE THREAD

**Issue by TheNeurotox** [AllTheMods/ATM-6#379]
This file don't seems to be loaded du to code error.
Problematic file: kubejs/server_scripts/botany_pots.js

What is probably causing the issue:
-KubeJs is now using rhino for javascript
-Rhino don't seems to support rest parameters.
-botany_pots.js use rest parameters in 2 functions growTree() (line 501 and 537) and growTreeSnowflake() (line 542 and 570) 

Possible quick partial fix:
Line 501:
`//    function growTree(mod, name, ...extra) {`
`    function growTree(mod, name) {`
Line 537:
`//                ...extra`

Line 542:
`//    function growTreeSnowflake(mod, name, ...extra) {`
`    function growTreeSnowflake(mod, name) {`
Line 570:
`//                ...extra`

Know issue with this fix:
-Extra item will not be created (like nether_banana for netherwood)
-Extra parameters will be ignored

**Comment by jeremiahwinsley** [comment]
Alternately this code could be removed, and the mod BotanyTrees added. Looks like it includes support for all the recipes currently defined: https://github.com/Darkhax-Minecraft/BotanyTrees/tree/1.16.4/src/main/resources/data/botanytrees/recipes

**Comment by TheNeurotox** [comment]
BotanyTrees look interesting.

We still need to keep kubejs/server_scripts/botany_pots.js for Soils, Mystical Agriculture and Ars Nouveau Crops.

If BotanyTrees is added, lines 500-951 from kubejs/server_scripts/botany_pots.js could probably be remove.

**Comment by Flattoptony** [comment]
Having the same issue.

**Comment by TheNeurotox** [comment]
1.3.3: same issue
Last working version: 1.2.1

The partial fix was working under 1.3.1 (except for extra items from trees)
Will I was trying to fix the file correctly, I notice that under 1.3.2c and 1.3.3 the partial fix permit to plant trees but not to harvest them.
For the moment, I don't understand why.

**Comment by Rithenar** [comment]
Has anyone checked if the new KubeJS version 1604.3.110 fixes this?

**Comment by lays24mc** [comment]
> 
> 
> Has anyone checked if the new KubeJS version 1604.3.110 fixes this?

Same issue with this version of KubeJS

**Comment by TheNeurotox** [comment]
Now working in 1.3.6 (probably 1.3.4)
Thanks
