### ISSUE TITLE
Potions Master allthemodium potion crashes game

### ISSUE THREAD

**Issue by Seegras** [AllTheMods/ATM-6#38]
Time: 02/08/2020, 13:45
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
        at com.thevortex.potionsmaster.items.potions.effect.oresight.AllthemodiumPotionEffect.func_76394_a(AllthemodiumPotionEffect.java:35) ~[?:0.1.12] {re:classloading}

**Comment by papavonfabian** [comment]
I had the same issue, resolved it by installing an older version of Potions Master, I took potionsmaster-0.1.11-1.16.1-32.0.88.jar

**Comment by thevortex** [comment]
0.1.13 resolves issue with this and brewing issues

**Comment by oly2o6** [comment]
fixed by mod developer
