### ISSUE TITLE
No Astral sorcery structures found after updating to 1.3.2

### ISSUE THREAD

**Issue by RickyvdBerg** [AllTheMods/ATM-6#380]
**Describe the bug**
Updated server to 1.3.2 from 1.3.1 no astral sorcery structures, while generating new chunks

**To Reproduce**
1. Update from 1.3.1 to 1.3.2
2. Keep old world folder
3. Generate new chunks using rtp and go far out
4. No structures have been found after 3 hours of searching

**Expected behavior**
Structures to be found while generating new chunks

**Additional context**
The aquamarine ore does spawn in rivers and oceans

**Comment by RickyvdBerg** [comment]
I'm also unable to find any rock crystal, thus making it impossible to start astral sorcery on an existing world

**Comment by RickyvdBerg** [comment]
Was able to find rock crystals, but it seems that there is no way to get a luminous crafting table without structures. So I'm lost. I looked at the configs and the world folder. Tried different dimensions that weren't generated yet but no dice.

**Comment by whatthedrunk** [comment]
They should be spawning just fine in new chunks. Sometimes it might take a while to find... If you are still having issues reach out the the astral devs and make a new issue here.

**Comment by RickyvdBerg** [comment]
Still having the issue, reached out to the AS team and they said wait for 1.16 to be fully ready, the current build isn't ready. We won't look into it.
