### ISSUE TITLE
Looking for breeding recipe for BEE make the game crash

### ISSUE THREAD

**Issue by MicaBloodless** [AllTheMods/ATM-6#381]
**Describe the bug**
The bug occur when we try to look for what kind of breeding a bee can do, we look for the recipe on the JEI and as soon as the recipe start loading, the game froze and finaly crash after a short time.

**Expected behavior**
We should be able to see the recipe without the game crashing.

**Comment by allout58** [comment]
Just ran into this too, appears to be a bug with ElementalCraft, see #371

**Comment by ViRb3** [comment]
Check above.
