### ISSUE TITLE
Critical error in Entangled 1.2.7

### ISSUE THREAD

**Issue by TheL0ki** [AllTheMods/ATM-6#382]
**Describe the bug**
Entangled 1.2.7 crashes the game when binding a block to it
https://github.com/SuperMartijn642/Entangled1.12/issues/8

**To Reproduce**
1. Entangle any block

**Additional context**
Has already been fixed by the author

**Comment by ViRb3** [comment]
Thanks for reporting. Will be added in next update.

**Comment by ViRb3** [comment]
Fixed in ATM6 1.3.2b.
