### ISSUE TITLE
1.3.2 stuck at 0% loading on 1.3.1 world

### ISSUE THREAD

**Issue by aschwartz2018** [AllTheMods/ATM-6#383]
**Describe the bug**
I just installed 1.3.2 version today. I loaded my world (created on 1.3.1) and it is stuck on 0% world loading. It's been like 10 minutes and no progress in the world loading process. Please show me any ways of recovering my world

**Comment by ViRb3** [comment]
What Operating System is this on? Are you running in Single Player or a dedicated server? In either case, please provide logs.

**Comment by aschwartz2018** [comment]
Windows 10, single player world (no server), will provide logs

**Comment by aschwartz2018** [comment]
Using the new curse launcher but I have doubt that is the issue since it worked on the last version

**Comment by aschwartz2018** [comment]
https://drive.google.com/file/d/1ZyUynspTPfH_pucyNOinAtFAS2pTqoEC/view?usp=sharing

**Comment by aschwartz2018** [comment]
https://drive.google.com/file/d/1tLw3CU0CHNbIjRiq2fcJjDJ5mmtXB15N/view?usp=sharing

**Comment by aschwartz2018** [comment]
Those 2 files above are the "latest.log" file and the log file for today's date in the /logs folder in the ATM6 instance

**Comment by ViRb3** [comment]
Interesting, there's literally no logs after starting to prepare the world. Is there any CPU usage from Minecraft (javaw.exe) when it gets stuck? You could always try creating a new profile (Preferably in MultiMC #339) and copy in your `saves` (world) folder.

**Comment by aschwartz2018** [comment]
I'll make a test world, and if that doesn't load, I'll copy the save to a new instance of the pack in curse client

**Comment by ViRb3** [comment]
Sorry, I had linked the wrong issue there, please check above for updated link.

**Comment by aschwartz2018** [comment]
So I crashed when making a new world, so I'm reinstalling the pack now. Saw there is a update to 1.3.2c though

**Comment by aschwartz2018** [comment]
Everything is working again with the reinstall
