### ISSUE TITLE
Game crashes on start using Twitch Launcher / GDLauncher; error code 0

### ISSUE THREAD

**Issue by ViRb3** [AllTheMods/ATM-6#384]
As stated in the ATM6 discord, Twitch Launcher and possibly GDLauncher have problems with ATM6. Please try using MultiMC instead.

Original message:

> Twitch launcher is known for having multiple issues on anything above 1.12, and as an alternative we are officially supporting the MultiMC for ATM modpacks, download and update packs just like with twitch, but working on all minecraft versions and having a better overall user experience

### Download the MultiMC from their website here
https://multimc.org/#Download

### How to Install
https://gyazo.com/e2e56187a7e779f74df8f1d8586555b8

### The latest Java version is not supported. Use Java 8 to minimize possible issues.

**Comment by HiImCruor** [comment]
It still crashes for me following the video you posted.
https://paste.ee/p/tmLsJ

**Comment by ViRb3** [comment]
From your paste:
>  java version 15.0.1

Java 15 is not supported. Use Java 8.

**Comment by Pdiddy973** [comment]
twitch launcher is known to have issues. if issue persist feel free to ask in our discord.

**Comment by DougStoker** [comment]
crashes on startup when installed on atlauncher

**Comment by DougStoker** [comment]
[latest.log](https://github.com/AllTheMods/ATM-6/files/5966418/latest.log)
