### ISSUE TITLE
Mining gadged void filter voids inventory items when sort button pressed

### ISSUE THREAD

**Issue by quasarea** [AllTheMods/ATM-6#385]
**Describe the bug**
Mining gadged filter entry, when sort pressed pulls items from inventory into the filter - they cannot be pulled back, just get voided.

Not sure if problem is on sorting mod side or mining gadgets

**To Reproduce**
1. Add voiding upgrade to mining gaded
2. Open filter setting
2. Click on sort 
3. Try to get items back from filter

**Expected behavior**
Items from inventory will not be moved into filter space

**Screenshots**
![image](https://user-images.githubusercontent.com/10334982/100112483-2e67dd00-2e67-11eb-86f2-49bd358beb5b.png)
![image](https://user-images.githubusercontent.com/10334982/100112457-260fa200-2e67-11eb-8a42-c90ad5dab59b.png)
![image](https://user-images.githubusercontent.com/10334982/100112985-c2d23f80-2e67-11eb-9828-5f4950854cc7.png)

**Comment by ViRb3** [comment]
Fixed in ATM6 1.3.2b. Ref: https://github.com/Direwolf20-MC/MiningGadgets/issues/123
