### ISSUE TITLE
Infection detected in startserver.bat

### ISSUE THREAD

**Issue by GD119** [AllTheMods/ATM-6#386]
Hi,

I decide to install the server from the curse page and when i want to unzip or launch the startserver.bat i got the message from bitdefender and im suprised that nobody has yet reported it:

"\SIMPLE-SERVER-FILES-1.3.2\startserver.bat is infected with Heur.BZC.ONG.Leopard.1.1D317965 and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean."
![2020-11-24 10_15_12](https://user-images.githubusercontent.com/71081983/100113117-fbf5ba00-2e3d-11eb-8b02-ea461e6e7980.png)

**Comment by ViRb3** [comment]
False positive. BitDefender loves to flag everything that downloads a remote file (in this case the server launcher).

**Comment by GD119** [comment]
> False positive. BitDefender loves to flag everything that downloads a remote file (in this case the server launcher). Feel free to report it as a false detection, hopefully they will fix it.
> 
> For the record, here is the content of the batch file in question: https://paste.gg/p/anonymous/94b5d3040ecf47e8aa77d4d4f82ef495

Thank you for taking the time to answer, i tried searching on the web and had only one case of false positive for something similar. Have a good day!
