### ISSUE TITLE
AllTheModium Mod Solar Panels have no recipe [1.3.2]

### ISSUE THREAD

**Issue by allout58** [AllTheMods/ATM-6#387]
**Describe the bug**
All the AllTheModium solar panels have no recipe other than the one meant to reset the panel.

**To Reproduce**
1. Search "solar panel" in JEI
2. Click on any of the solar panels from AllTheModium to see the recipe
3. See only panel-to-panel reset crafting recipe

**Expected behavior**
AllTheModium, Vibranium, and Unobtanium Solar Panels should have crafting recipes.

**Screenshots**
![image](https://user-images.githubusercontent.com/2939703/100113716-9ce47500-2e3e-11eb-9258-3179f8f729f1.png)

**Additional context**
I do not see any errors in the server logs related to anything solar, so I'm not sure what broke from 1.3.1

**Comment by whatthedrunk** [comment]
fixed thanks!
