### ISSUE TITLE
Solar Neutron Activator does not work in AllTheModium Mining Dimension

### ISSUE THREAD

**Issue by Sadumon** [AllTheMods/ATM-6#388]
**Describe the bug**
Mekanism's Solar Neutron Activator does not work in the AllTheModium Mining Dimension

**To Reproduce**
Build a Solar Neutron Activator, place it in the mining dimension, and put nuclear waste or deuterium into it...nothing happens.

**Expected behavior**
As it's an always sunny dimension, it should function.

**Additional context**
My guess is that one of these checks is failing:
`boolean seesSun = world.isDaytime() && world.canBlockSeeSky(pos.up()) && world.getDimensionType().hasSkyLight();`

**Comment by RedDragonRob** [comment]
Having Similar Problems with Powah Solar Panels in the Mining Dim as well. Does nothing, but place in Overworld or The Other dimensions and it works fine.

**Comment by thevortex** [comment]
that is very odd, you say it works in 'The Other' ? there is never daytime there....

**Comment by RedDragonRob** [comment]
Yeap, and working at night in overworld, at least niotic solar is.

**Comment by Nonsanity** [comment]
Looks like the AllTheModium mod needs to set its mining dimension's hasSkyLight to true.

It's problematic to set up the Solar Neutron Activator there and fill it with nuclear waste only to find it won't work there at all. Breaking pipes and blocks with nuclear waste in them will irradiate the whole area. There's no way to get the stuff out of the machine except to run it, and that's not possible without that flag set on the dimension.

**Comment by thevortex** [comment]
here is the dimension data file
```

 {

  "name": "allthemodium:mining",
  "type": "allthemodium:mining",
  "ultrawarm": false,
  "natural": false,
  "fixed_time": 9000,
  "shrunk": false,
  "piglin_safe": true,
  "respawn_anchor_works": false,
  "bed_works": true,
  "has_raids": false,
  "has_skylight": true,
  "has_ceiling": false,
  "ambient_light": 0.75,
  "logical_height": 256,
  "infiniburn": "minecraft:infiniburn_overworld",
  "coordinate_scale": 1
}

```

looks like it is,

**Comment by Dunkmania101** [comment]
I think I found the issue! It's the same thing that's been happening in my Daylight Dimension mod. I was looking at the isDaytime method and saw that it returns false if the fixed time value is set. How annoying! I think I'll remove that value from the json file and create an event subscriber that sets the time in my dimension to noon every tick.

**Comment by PvPsFinest** [comment]
How do I get to the dimension data file? I don't see it in datapacks in the server.
