### ISSUE TITLE
ATM6 crashes on launch

### ISSUE THREAD

**Issue by fieryotaku** [AllTheMods/ATM-6#39]
![image](https://user-images.githubusercontent.com/16654392/89141770-66cf5e00-d4fa-11ea-9c12-95aa8f9664f9.png)
my firend has this issue when trying to launch the ATM6 from the twitch launcher it immediately crashes.
![image](https://user-images.githubusercontent.com/16654392/89141802-81a1d280-d4fa-11ea-94e2-f2901d888ac2.png)

**Comment by oly2o6** [comment]
the twitch launcher is known for just not working for certain people, he can try uninstalling it and downloading it again, or checking out multimc or GDlauncher as an alaternative

**Comment by LeadAssimilator** [comment]
There is a pathing bug somewhere.  As a workaround, change your Minecraft Path in the Twitch app (Profile Picture -> Settings -> Minecraft -> Minecraft Path -> Change) to a path that does NOT contain spaces like D:\Twitch_Minecraft instead and rename/move your existing folder to match the new location.
