### ISSUE TITLE
Creating a new world gets stuck at 100%.

### ISSUE THREAD

**Issue by ariosos** [AllTheMods/ATM-6#390]
(ATM6 version is 1.3.1)
I have a world settings template that I'm recreating a world from (plus manually typed random seed), and after 5 attempts at finding a world I like, it will be stuck at 100%. I'm using the Biomes'O'Plenty worldgen (although, I tried default and Quark realistic, and those locked up at 100% on the first attempt). Attempting to create a world on the first attempt takes about 5-10 minutes from clicking "Create new world" to loading it.

EDIT: Tried again after reloading, and it froze at 100% after trying to create a world the 2nd time.

![image](https://user-images.githubusercontent.com/7917753/100165546-8105c100-2e88-11eb-9888-d7f6c2df202c.png)

I also noticed that my RAM usage (I have 12 gigs allocated) gradually increases with each new world I try and create.

![image](https://user-images.githubusercontent.com/7917753/100165573-967aeb00-2e88-11eb-8715-21d18996a98c.png)

PC Specs:
Intel Core i7 2600k (asrock z77 motherboard)
16 Gigs RAM (12 allocated to Minecraft)
Windows 10 Pro - 64 bit
Java version 1.8.0_191 64 bit
GTX 1070

**Comment by Colton-Slayden** [comment]
unless you are running a heavy texture pack running that much ram will cause more issues then help at max 6-8 with good settings for gc, personally i run -XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M, also your cpu is pretty old it might just be loading i have a 7700k and it hangs a bit on world creation

**Comment by ViRb3** [comment]
Have you tried using MultiMC with Java 8? #384

**Comment by ariosos** [comment]
Haven't tried MultiMC yet, but I'll test the latest instance on that one.

**Comment by ariosos** [comment]
Ok, just finished testing. 5th time, game is stuck at 100%.
1. Created Template save to copy from.
2. Re-created from template (new name was always "Template (1)".
3. Stay in the world for about 5 seconds, then exited and deleted world. Repeated steps 2 and 3. (took about 10-15 minutes for each cycle).

After the 5th one, it remains stuck at 100%.

[InstanceLogs.zip](https://github.com/AllTheMods/ATM-6/files/5611353/InstanceLogs.zip)

**Comment by EchoingZen** [comment]
Just wanted to chime in and say that I got the same stuck worlds, always the second world with in a single session. (I play hardcore, so I tend to make new ones.)

I just close the game when I am going to make a new world.

Behavior existed with no java args and with those in the atm discord.

**Comment by SolarSoul69** [comment]
Ok, I might have a solution, but I'm not sure is it the best way or not.

1. copied everything in the ATM 6 folder ( located inside the versions folder)
2.pasted it all in the ".minecraft", which will replace some file
3.launch the regular 1.16.4 forge version Minecraft. 

Now it won't be stuck at 100%, but the mode menu will glitch out.
