### ISSUE TITLE
[1.3.2b] No more Nether Star Block

### ISSUE THREAD

**Issue by Shashank329** [AllTheMods/ATM-6#391]
Previous versions had a Nether Star block that was used by Wither Bees from Resourceful Bees. Now the bees are essentially useless as their "flower" block has been removed. Not sure if this was intentional for balancing.

**Comment by DeathOfTime** [comment]
as far as i understand it the system that added the block isn't currently working. they are waiting on a update to it

**Comment by whatthedrunk** [comment]
should be good now
