### ISSUE TITLE
Crafting Tin and Steel with Mystical Agriculture

### ISSUE THREAD

**Issue by Fenoglio23** [AllTheMods/ATM-6#394]
Hi, 
since Patch 1.3.2c i have an issue in crafting Steel an Tin from Essences. 
There no recipe in JEI for crafting these ingots. 

Greetings from Germany

Fenoglio23

**Comment by cwandrey** [comment]
Hello,
 
the same problem exists with the Uranium Essence.

Greetings, 
Chris

**Comment by Flattoptony** [comment]
Noticed this issue today, seems to be everything from the Alltheores mod.
