### ISSUE TITLE
Resourceful Bees removed in version 6-1.3.2

### ISSUE THREAD

**Issue by JaisDK** [AllTheMods/ATM-6#395]
Resourceful Bees looks to be gone in version 1.3.2 from yesterday.

**Comment by iarspider** [comment]
Present in 1.3.2, 1.3.2c. Try redownloading the pack.

**Comment by JaisDK** [comment]
I can see it in the manifest but it does not download. It's the only one from the manifest file that's not downloaded.

**Comment by iarspider** [comment]
Are you using Twitch launcher? I have heard of it misbehaving in a similar way...

**Comment by JaisDK** [comment]
It's the same if I update to a new profile

**Comment by JaisDK** [comment]
It's there now, not sure what I did different
