### ISSUE TITLE
Constant server lagg | Fixing the lagg

### ISSUE THREAD

**Issue by AiJermain** [AllTheMods/ATM-6#397]
Hello fellow crafters,

I have been running a server for friends for the past 3 days and since launch of set server I have not been able to sort out any of the lagg that the server is experiencing. I have tried everything to fix it but yet fail. I remember that there was a mod to inspect chunks and see what chunk was causing lagg on the server but I can not find that mod anymore. 

I hope someone could assist me and bring me on the right path so I can sort this stuff out

regards,
Jermain

**Comment by Jutsch** [comment]
I had the same problem - in the Versions bevor my server ram perfect. But in 1.3.2c the lag is bad - depending on the biom: Alps are crashing all the time... till I discovered RAM-Disk in the "server-setup-config.yaml":
  # Use a RAMDisk for the world folder
  # case-sensitive; use only lowercase `yes` or `no`
  # NOTE: The server must have run once fully before switching to `yes`!
  ramDisk: no
switched it to "yes" and now the server runs smooth again.

**Comment by AiJermain** [comment]
> 
> 
> I had the same problem - in the Versions bevor my server ram perfect. But in 1.3.2c the lag is bad - depending on the biom: Alps are crashing all the time... till I discovered RAM-Disk in the "server-setup-config.yaml":
> Use a RAMDisk for the world folder
> case-sensitive; use only lowercase `yes` or `no`
> NOTE: The server must have run once fully before switching to `yes`!
> ramDisk: no
> switched it to "yes" and now the server runs smooth again.

I have googled a bit and seen that there is a risk for this setting. Since each restart will void all the saved files. Does the server-setup=config.yaml also setup a auto backup for ramdisk or not?

**Comment by glahera** [comment]
I wonder a bit about this "RAM-disk" option in server config. Is this any different than I setup tmpfs in Docker compose? Since using Docker tmpfs mounted at /srv/world is usually my preferred method to use RAM disk on Minecraft server.

**Comment by ViRb3** [comment]
#425

**Comment by schnifi** [comment]
Well i didn't experience any lag today even though i didn't change anything on the server except adding spark. Spark also didn't show that anything was lagging. Then I tried to recreate the problem by creating the server from scratch without spark and it still didn't lag.
