### ISSUE TITLE
Ladders cannot be crafted with non-vanilla wood variants

### ISSUE THREAD

**Issue by Gerdathlete** [AllTheMods/ATM-6#399]
**Describe the bug**
When crafting ladders, you cannot use any of the non-vanilla woods. By that I mean that any of the modded logs and planks you get cannot be used to make ladders. This is probably caused by Quark changing the ladder recipe and adding variants.

**To Reproduce**
Try to craft a ladder using modded woods like Baobab or Jacaranda planks

**Expected behavior**
Oak ladders should be craftable using modded planks in the center of the crafting table, with 3 sticks on both sides.
![image](https://user-images.githubusercontent.com/25123577/100286560-dba22a00-2f27-11eb-8f20-d0b0291b6da8.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/25123577/100286624-f5dc0800-2f27-11eb-8bbb-5cabbfa98626.png)

**Comment by jeremiahwinsley** [comment]
Reported here: https://github.com/Vazkii/Quark/issues/2862
