### ISSUE TITLE
Game Crash to Desktop

### ISSUE THREAD

**Issue by benjiben55** [AllTheMods/ATM-6#40]
Hey, the game crash all the time with the same error message log. 
I cant find the issue by my self.

I think torchslab Mod is the problem, they cant find a wall_torch_slab. 
I attach the log file below.
[crash-2020-08-03_11.37.28-server.txt](https://github.com/AllTheMods/ATM-6/files/5015126/crash-2020-08-03_11.37.28-server.txt)
[crash-2020-08-03_11.19.38-server.txt](https://github.com/AllTheMods/ATM-6/files/5015127/crash-2020-08-03_11.19.38-server.txt)
[crash-2020-08-03_10.56.05-server.txt](https://github.com/AllTheMods/ATM-6/files/5015128/crash-2020-08-03_10.56.05-server.txt)
[crash-2020-08-03_10.47.55-server.txt](https://github.com/AllTheMods/ATM-6/files/5015129/crash-2020-08-03_10.47.55-server.txt)

**Comment by benjiben55** [comment]
Update:

I reinstall torchslap and all my lantern's were still there. I removed all of them and try to play again. 
I hope thats all to fix the problem but when people use  more items from the mod then me, it's maybe a problem.
The issue is becase of the mod torchslap, the mod dont remove all item's in the world. Maybe only the value and the block is air or so.

so long

**Comment by oly2o6** [comment]
closing this, if the issue should arise again it can be reopened
