### ISSUE TITLE
Heard Astral Sorcery was getting added.

### ISSUE THREAD

**Issue by Thanoid1** [AllTheMods/ATM-6#401]
I heard that Astral Sorcery was going to get added in the 1.3.2 update. I planned to update my 1.3.1 world to get the astral sorcery items, but I thought since the world wasn't generated with Astral Sorcery, how would I even play it? I know that there is already marble, but what about the aquamarine. Will any of it spawn? Also, the update mentioned "Ice and Fire will hopefully be fixed when the mod updates again. If you want them in the overworld delete the Ice and Fire biomes and common config and let it generate a new one." How do I delete the Ice and Fire config? Thanks for any help.

**Comment by ariosos** [comment]
It should. The AS temples appeared in my upgraded world on nearby mountains.

**Comment by Thanoid1** [comment]
Thanks for the info, but I can't really see them anyways. I upgraded, but my loading world screen was stuck at 100%. I recently posted a bug about this. If you can help, please respond over there.

**Comment by NetMasterFlex** [comment]
Are you using Optifine by any chance?

**Comment by glahera** [comment]
I heard it and excited, but so far I have no luck in getting it working. I have the crystal and the crafting table but it doesn't seem to transmute. Also, I cannot find Rock Crystal Ore, I can confirm this by using Mekanism's Digital Miner and it detected 0 in 5*5 chunk range.

**Comment by Thanoid1** [comment]
Yes I am.

**Comment by NetMasterFlex** [comment]
Try loading without it.  There have been reports recently about optifine not working.  I experienced this myself and removed it.  No problems after.  Let me know what you find as I'm curious.

**Comment by Thanoid1** [comment]
I can’t really do that because I’m in bed right now. I’ll be sure to try tomorrow. But regardless, my laptop barely gets 25 fps without optifine. Hope it works. And thanks too.

**Comment by Thanoid1** [comment]
Alright so I removed Optifine and the world loaded perfectly. I deleted the config and I see Astral Sorcery and Ice and Fire structures. Really need Optifine for a good playthrough.

**Comment by NetMasterFlex** [comment]
I heard you could try to add something call optforge to help with compatability, but I don't know enough about it to advise you.  It sucks that optifine and forge have a love/hate relationship.

**Comment by Thanoid1** [comment]
Is optforge a mod? A datapack? And are there any other instructions to install it?

**Comment by NetMasterFlex** [comment]
Like I said previously, I don't know a lot about it.  I believe it's a mod just as optifine is a mod.  You would have to google it.  Sorry I can't be more help here.  I've settled on just using resource packs for now and checking optifine compat with each modpack update.  If it works, it work, if it doesn't it doesn't.

**Comment by Thanoid1** [comment]
Thanks for the help anyways. From what I see, it basically looks like Optifabric but for forge. But, after the  first load in 1.3.2, I closed Minecraft, added in optifine, and I loaded it again, and it worked fine.

**Comment by thevortex** [comment]
using optifine breaks things in singleplayer, if you want astral sorcery working optimally, optifine has to go

**Comment by Thanoid1** [comment]
I had to load the world first without optifine, then close it, then load it with optifine. Everything good after that.

**Comment by thevortex** [comment]
any chunks generated with optifine loaded in singleplayer run the risk of being broken as of current versions of optifine. pregenerate your expected world usage first would be the only way i would suggest using optifine

**Comment by Thanoid1** [comment]
What do you mean by "pregenerate your expected world usage first would be the only way I would suggest using optifine"? And how would I do that? Don't know too much about the technical side of mods.

**Comment by thevortex** [comment]
there may be a mod that will generate the map before you load into it, but if its at 1.16.4 i am unsure, we do not officially support using optifine, if it works it works, if not, we're sorry :(

**Comment by Thanoid1** [comment]
Thanks for the information, I quickly looked up something along the same lines, and I found this mod called "World Pre Generator" which pre generates Minecraft's dimensions. Curseforge link [](https://www.curseforge.com/minecraft/mc-mods/world-pre-generator). Don't think both are the same thing, but might as well look at it.
