### ISSUE TITLE
Stuck at 100%

### ISSUE THREAD

**Issue by Thanoid1** [AllTheMods/ATM-6#404]
**Describe the bug**

**To Reproduce**
1. Make world in 1.3.0
2. Update to 1.3.1, then 1.3.2 c
3. Load world
4. Observe that loading is stuck at 100%

**Expected behavior**
I thought that I would load the world normally. I made a question post on how to get astral sorcery structures/ aquamarine, and how I would delete ice and fire config. I didn't want to wait that long for an answer, so I tried to test it myself.
**Screenshots**

**Additional context**
I use optifine, don't know if that will do anything.

**Comment by ViRb3** [comment]
#390
