### ISSUE TITLE
Storage drawers cannot be crafted with non-vanilla wood variants

### ISSUE THREAD

**Issue by Gerdathlete** [AllTheMods/ATM-6#408]
**Describe the bug**
Storage drawers cannot be crafted using modded, non-vanilla wood variants.

**To Reproduce**
Try to craft a drawer with a non-vanilla wood like Baobab planks

**Expected behavior**
Oak wood storage drawers should be crafted when using non-vanilla wood variants

**Screenshots**
![image](https://user-images.githubusercontent.com/25123577/100311660-33ab5180-2f65-11eb-84e5-20427f711d00.png)

**Comment by glahera** [comment]
I think this is less of a bug than a feature request, due to the fact this depends on the modpack developer, not on the mods nor vanilla behavior. You can just add a custom recipe that allows any wood to be combined with chest to make oak drawer.

**Comment by Gerdathlete** [comment]
> I think this is less of a bug than a feature request, due to the fact this depends on the modpack developer, not on the mods nor vanilla behavior. You can just add a custom recipe that allows any wood to be combined with chest to make oak drawer.

That's why its on the modpack issues forum. This isn't an intended feature of the pack (or at least I would hope it isn't).

**Comment by oly2o6** [comment]
not sure how to go about this as usually either A: there are addon mods that add the different variants or B: drawers are intentionally made with their respective wood variants
