### ISSUE TITLE
Ice and Fire crash

### ISSUE THREAD

**Issue by outersight** [AllTheMods/ATM-6#413]
server crashing after some users encounter ice and fire creatures.

any help?
[crash-2020-11-26_15.42.32-server.txt](https://github.com/AllTheMods/ATM-6/files/5603971/crash-2020-11-26_15.42.32-server.txt)

**Comment by ViRb3** [comment]
Which ATM6 version is that? A similar issue was fixed in ATM6 1.3.2b and later.

**Comment by oly2o6** [comment]
this should be fixed already if not in the next version
