### ISSUE TITLE
can't launch the server

### ISSUE THREAD

**Issue by Andrei631** [AllTheMods/ATM-6#414]
When I try to launch the server it gives me this error:
Unrecognized option: -d64
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
My OS is Ubuntu Server 20.04.1 LTS
![image](https://user-images.githubusercontent.com/36139150/100372257-a70a9d00-3011-11eb-8dea-9818c276b75e.png)

**Comment by glahera** [comment]
Did you verify the version of your Java installed? As far as I know, -d64 is for 64-bit installation of Java. If you feel that it is confusing with Java versions, you can also use Docker image to run the server without caring of dependency.

**Comment by Andrei631** [comment]
I installed java x64 and it worked. Thanks!
