### ISSUE TITLE
Where can i send crash reports

### ISSUE THREAD

**Issue by Titanblade828** [AllTheMods/ATM-6#415]
[crash-2020-11-26_16.27.46-client.txt](https://github.com/AllTheMods/ATM-6/files/5604153/crash-2020-11-26_16.27.46-client.txt)
[crash-2020-11-25_23.46.59-client.txt](https://github.com/AllTheMods/ATM-6/files/5604155/crash-2020-11-25_23.46.59-client.txt)
[crash-2020-11-25_18.13.43-client.txt](https://github.com/AllTheMods/ATM-6/files/5604157/crash-2020-11-25_18.13.43-client.txt)

All of these in the last few days

**Comment by Titanblade828** [comment]
This is happening everytime i click on anything to do with the allthemods items

**Comment by ViRb3** [comment]
Fixed in 1.3.3. #371
