### ISSUE TITLE
100% Cpu core with only 8 players

### ISSUE THREAD

**Issue by lilwilisjr** [AllTheMods/ATM-6#416]
I have dynmap minimum chunk view to 1
the 8 players are not doing any kind of chunk generation and theres no quarries or rf builders or anything
and the server cpu is at 100% with a 10700k

**Comment by ViRb3** [comment]
Install the [Spark](https://ci.lucko.me/job/spark/lastSuccessfulBuild/artifact/spark-forge/build/libs/spark-forge.jar) mod on your client and server. Run `/spark healthreport` - it will give you current TPS, used RAM, used CPU. Further, you can run `/spark profile` to generate a report which tells you why your server is lagging. Feel free to drop it here if you need help.

**Comment by lilwilisjr** [comment]
https://spark.lucko.me/#AjXtlLGN6z
definitely need some help reading

**Comment by ViRb3** [comment]
It looks like your server's CPU is just weak. There's nothing special in the logs. If this is a VPS/rented server, you are probably only allowed one core of the 10700k and even then it's probably shared with other users. Switch hosts is what I would recommend.

**Comment by lilwilisjr** [comment]
> EDIT: If you have multiple cores allowed, make sure you are using the Java arguments from the SIMPLE_SERVER package, which will utilize more than 1 core.

replace -server to -simple_server in server-setup-config.yaml?

**Comment by ViRb3** [comment]
I meant just use the launcher script in the server package provided by ATM6, but that seems like what you're using anyway.

**Comment by lilwilisjr** [comment]
I have the entire 10700k and its not shared, still just 100% cpu on 1 core and then only a little on the others

**Comment by ViRb3** [comment]
What does `/spark healthreport` show?

**Comment by lilwilisjr** [comment]
![image](https://user-images.githubusercontent.com/51977562/100524367-a7af4a80-315b-11eb-8b4e-4c0081a0b9f0.png)

i can see the core @ 100% out of all 6 cores/threads while everything else just kinda doing nothing

**Comment by ViRb3** [comment]
This is really strange. I'm afraid I don't have any more ideas. I hope somebody else can help.

**Comment by NetMasterFlex** [comment]
> I meant just use the launcher script in the server package provided by ATM6, but that seems like what you're using anyway.

Two Questions...
What is the name of that file?  I simply run the StartServer.bat file and off it goes. I want to make sure I’m using multi-cores. I’m. It having any problems. Just want to make sure I’m running most efficient.

On my client how can I get it to use more than 1 CPU?

**Comment by whatthedrunk** [comment]
Monitoring newer versions I dont see this issue happening. If you are in 1.5.0 and still having issues let us know with a new spark profile and we will see if we can see anything.
