### ISSUE TITLE
SilentGear Arrows aren't working correctly

### ISSUE THREAD

**Issue by Hatsu-m** [AllTheMods/ATM-6#417]
**Describe the bug**
SilentGear arrows are not working currently. durability goes to 0 automatically. Contacted mod maker as well

**Expected behavior**
Silent Gear arrows to build and not lose durability,

**Comment by mkaito** [comment]
I made an arrow, and it got partial durability. 75 / 256. I can't repair or replenish it in any way. It will consume ingots at the anvil and some material from a repair kit, but the durability won't increase.
