### ISSUE TITLE
Lumium and Fluorite seeds missing from Botany Pots

### ISSUE THREAD

**Issue by Sadumon** [AllTheMods/ATM-6#418]
**Describe the bug**
Lumium and Fluorite seeds cannot be planted in botany pots, but work fine in the Garden Cloche.

**To Reproduce**
Recipe doesn't exist in JEI nor can you plant the seed.

**Expected behavior**
Both are listed in T3 in the botany_pots.js

**Additional context**
The script must be failing in the processing of Lumium, because it looks like it registers them in order for T3.  Zombie seeds are properly processed which is the third to last essence in the list of botany_pots.js, but the lumium and fluorite essences are not.

**Comment by Sadumon** [comment]
This might actually be due to #379

It looks like KubeJS is punting on the entire botany_pots.js script because of the issue described in #379.  Therefore Botany Pots is just processing whatever is being provided by the mods themselves, and Lumium and Fluorite must not be part of the default set.

**Comment by jeremiahwinsley** [comment]
Fixed in 1.3.9.
