### ISSUE TITLE
Mystical Agriculture Bronze essence Have No Use

### ISSUE THREAD

**Issue by TechTehTeek** [AllTheMods/ATM-6#419]
**Describe the bug**

The current version of All The Mods 6, Bronze essence has no use to craft bronze ingots.

**To Reproduce**

1. Craft bronze seeds
2. Grow bronze seeds
3. Press U on the essence
4. There is none, nor craftable in any shape.

**Expected behavior**

I expected them to have any kind of use.

**Screenshots**

**Additional context**

**Comment by lothpendragon** [comment]
**Copper Essence** seems to have no use either. The seeds can be made in MA without issue, grow and harvest correctly, **only the essence to ingot recipe seems to be missing**.

**Comment by EndlessEden** [comment]
Did you attempt to do a 4x grid of the essence to see if its just missing in JEI, but the recipe recognised by the crafting grid?(Just wondering)

**Comment by lothpendragon** [comment]
I've just tested with X-Cross, Plus, Plus with centre missing  Ring, Chest Armor pattern and rotated the space through all slots, Small Square, Tall and Wide Rectangles and lines of 3 rotated.

No recipes seems to be working for the essence at all.

**Comment by lothpendragon** [comment]
I've just checked a couple in the new 1.3.3 update and recipes aren't there still. So my testing so far has been in 1.3.2c and 1.3.3.

**Comment by darthtechnosage** [comment]
I also have checked and can confirm this is an issue in the 1.3.3 update. This is the case with Aluminum, Copper, Platinum, Iridium, Tin, Bronze, Zinc, Brass, Silver, Lead, Steel, Nickel, Constantan, Electrum, mithril, Tungsten, Titanium, Uranium, Chrome, air, and Rubber Essence.

**Comment by Wibias** [comment]
Also add silicon from Applied Energistics to this + printed silicon.
