### ISSUE TITLE
Super Lag and can't create world

### ISSUE THREAD

**Issue by Virdanis** [AllTheMods/ATM-6#420]
When I open the game through the Twitch launcher, the menus lag to the point where it's 10+ seconds between me clicking a menu option and the opening of whatever I clicked on. In addition, when I attempt to create a world so I can play, the screen says "Preparing for world generation" and then stops responding. I've tried twice to make a world so I can play, but these issues are preventing me. I'm really curious about this modpack, but I have no idea what to do about this.

![prep](https://user-images.githubusercontent.com/75109269/100413901-785ae980-3046-11eb-80b2-f25b9a7e19be.PNG)

**Comment by ViRb3** [comment]
The delay is normal, modded 1.16 takes __a long__ time to join a server. Also #384
