### ISSUE TITLE
Odd reoccurring texture mishaps

### ISSUE THREAD

**Issue by Gerdathlete** [AllTheMods/ATM-6#421]
**Describe the bug**
When launching this pack and loading into my singleplayer world, most of the time my Silent Gear armor will be missing its texture, as well as the Silent Gear tip upgrades. After reloading resources with F3 + T, the issue is resolved, but other textures seem to be having issues. I've noticed while mining that some ores have had their textures changed to random textures, like the experience ore and arcane crystal ore.

**To Reproduce**
I'm not sure if this will happen on another client, but give it a try yourself.

**Screenshots**
![image](https://user-images.githubusercontent.com/25123577/100414545-d24fb500-302e-11eb-8c24-08f4f1ab6c80.png)
![image](https://user-images.githubusercontent.com/25123577/100414844-96691f80-302f-11eb-9970-505dda2130ef.png)
![image](https://user-images.githubusercontent.com/25123577/100415147-4b034100-3030-11eb-977e-424753602284.png)

**Additional context**
I'm running on the latest version of Java 8, with updated Nvidia GeForce drivers.
Refreshing the textures again with F3 + T does not fix the issue.

**Comment by Gerdathlete** [comment]
Also, I'll add that the issue seems to be exclusive to the block textures, and does not effect the block items.
![image](https://user-images.githubusercontent.com/25123577/100414955-d8926100-302f-11eb-82ee-872ca9ab69b0.png)

**Comment by ariosos** [comment]
I saw this one a week ago when I accidently re-ordered texture packs in the texture pack list.

**Comment by Gerdathlete** [comment]
> I saw this one a week ago when I accidently re-ordered texture packs in the texture pack list.

![image](https://user-images.githubusercontent.com/25123577/100494295-4785bd80-30f5-11eb-91c6-d11e5d7b3d33.png)
Is this the default order? I may have accidentally hit one of the arrows at some point

**Comment by ariosos** [comment]
> > I saw this one a week ago when I accidently re-ordered texture packs in the texture pack list.
> 
> Is this the default order? I may have accidentally hit one of the arrows at some point

Mine has "Default" at the top instead of the bottom.

**Comment by Gerdathlete** [comment]
![image](https://user-images.githubusercontent.com/25123577/100530563-7c9f1800-31a8-11eb-82fc-95856d731664.png)
This arrangement results in the arcane ore being weird again, but now refined storage blocks are bugged.
![image](https://user-images.githubusercontent.com/25123577/100530582-9cced700-31a8-11eb-80e9-38e332efe4f0.png)
![image](https://user-images.githubusercontent.com/25123577/100530584-a6f0d580-31a8-11eb-94c8-8c8f1a72db20.png)

I noticed that when I went to change the order of the packs, it was different from before, so it definitely changes order, and I don't believe that's my doing. I think F3+T may rearrange them.

**Comment by Gerdathlete** [comment]
Without changing any settings, I restarted my client and checked the resource pack order. While the order was unchanged, all the blocks have the correct textures, and many of the Silent Gear items are untextured again. So the order of resource packs doesn't seem to be the issue, but reloading the textures causes textures to be assigned to the wrong blocks, and every time you change the order of the resource packs, it reloads the textures..

![image](https://user-images.githubusercontent.com/25123577/100530766-c0931c80-31aa-11eb-80b7-2f3f4b807831.png)

**Comment by Namoku** [comment]
It happens to me too, everytime when I log into my world the silent gear stuff is broken.
