### ISSUE TITLE
[1.3.3] AE2 causes crash when starting server for the first time!

### ISSUE THREAD

**Issue by TheGreyRaven** [AllTheMods/ATM-6#423]
Hi!

I'm trying to setup a ATM-6 server on my Linux machine and when I'm starting it for the first time it crashes when it gets to loading Applied Energetics 2.
Here is the full crash-log:
https://pastebin.com/ydnzZ0A7

Any idea what might be causing this issue?

**Comment by EndlessEden** [comment]
fyi, the problem is right in the log: "Java Version: 14.0.2, AdoptOpenJDK"

Minecraft Java Edition, is only supported on a Java Version 8.
