### ISSUE TITLE
Apotheosis common_setup event phase crash

### ISSUE THREAD

**Issue by ariosos** [AllTheMods/ATM-6#426]
I was able to run this version last night, but this morning, it gave this error:

![image](https://user-images.githubusercontent.com/7917753/100453849-b4fc0480-3089-11eb-8913-6201ed8379e1.png)

Pastebin: https://pastebin.com/htqFAZnp

**Comment by ViRb3** [comment]
Try again? Apotheosis seems to cause a lot of random crashes which don't usually repeat on second attempt.

**Comment by ariosos** [comment]
Yes, it worked the 2nd time.
