### ISSUE TITLE
ATM6 1.3.3 Crash when starting (Mystical Customization)

### ISSUE THREAD

**Issue by Wibias** [AllTheMods/ATM-6#428]
The Game crashes when starting it. But only crashes on the client not when starting my server.

Happened 4 times in a row.

![image](https://user-images.githubusercontent.com/37517432/100469530-a982fa80-30d6-11eb-964f-1d6755c720c9.png)

https://pastebin.com/zxtYrih3

**Comment by ViRb3** [comment]
Re-install your instance, sounds like the config got corrupted.

**Comment by Wibias** [comment]
Worked!
