### ISSUE TITLE
World using experimental settings!

### ISSUE THREAD

**Issue by benjiben55** [AllTheMods/ATM-6#43]
Hello i am really pissed with the "feature" or whatever it mean.
I cant create a world without this warning "The world using experimental settings".
I cant remove a mod... i get this error!
I cant joing my world anymore... i get this error.
I try to create a new world in default "not byg" and again i get this error.

Please tell me what i can do....

.... benjiben

**Comment by whatthedrunk** [comment]
https://www.curseforge.com/minecraft/mc-mods/shutup-experimental-settings
