### ISSUE TITLE
ATM6 Wont Load

### ISSUE THREAD

**Issue by KumaSamaVII** [AllTheMods/ATM-6#432]
I cant get ATM6 to load.  When I run it it says a bunch of mods arent present and some of the files arent jar files. This is a fresh install and I have changed nothing. I am not using optifine or any resource packs. Please help!

**Comment by KumaSamaVII** [comment]
I changed launchers and that solved the problem. I was previously using gdlauncher

**Comment by ViRb3** [comment]
For reference: #384.
