### ISSUE TITLE
Mekanism Anchor Upgrade Recipe Missing

### ISSUE THREAD

**Issue by waybaker** [AllTheMods/ATM-6#433]
**The Problem**
JEI does not show the recipe for the Anchor Upgrade for Mekanism.  Attempting to craft using the last known good recipe (1 Diamond Dust, 2 Infused Alloy, and 2 Glass) does not produce the item either. I have verified that allowChunkloading = true is set in the general config file for Mekanism.

**To Reproduce**
1. Install Server using Simple Server Files
2. Install ATM 6 from CurseForge or Twitch Client
3. Log in to server using client
4. Attempt to craft, or attempt to show recipe in JEI -> Error should be present.

**Expected behavior**
Should be able to craft the item.  Item is available in JEI, but no recipe exists.

**Screenshots**
N/A

**Additional context**
This was present on 1.3.0.  Just upgraded to 1.3.3, issue persists.

**Comment by Xenovalis** [comment]
This is not a bug, this is intended. ATM6 uses FTB Chunks for chunkloading.

If you would like to enable the anchor for your world/server you can remove it from `kubejs/server_scripts/removals.js`.
https://github.com/AllTheMods/ATM-6/blob/2443f171e3687b1ed0f0865f33fc217a595d1145/kubejs/server_scripts/removals.js#L36

Note: You will have to do this every update.

**Comment by waybaker** [comment]
Thanks.  I was not aware of what FTB Chunks was.  I looked it up and will be using that instead.

**Comment by lsalazarm99** [comment]
Just curious, is there any technical reason why FTB Chunks is preferred?

**Comment by jeremiahwinsley** [comment]
> Just curious, is there any technical reason why FTB Chunks is preferred?


It lets you manage chunk loads in one place, instead of having multiple different ways to chunkload. Additionally, server owners can more easily limit the number of loaded chunks if they only need to configure one mod.
