### ISSUE TITLE
Xray Bug with Builder Support Preview Blocks

### ISSUE THREAD

**Issue by Gerdathlete** [AllTheMods/ATM-6#435]
**Describe the bug**
The support preview blocks created by the RFTools Builder cause you to be able to see through the world

**To Reproduce**
1. Place any Quarry shape card in an RFTools Builder while underground
2. Select Support/preview mode
3. See through the world

**Screenshots**
![image](https://user-images.githubusercontent.com/25123577/100493220-f3c1a700-30e9-11eb-95eb-37da0c5e7097.png)

**Comment by Pdiddy973** [comment]
i think this is an issue with vanilla and transparent blocks, not really a mod issue.
