### ISSUE TITLE
Envirotech Crash

### ISSUE THREAD

**Issue by xd3nny** [AllTheMods/ATM-6#436]
**Describe the bug**

I build the Enviromental Tech Void miner about 2 min. later it crashed. I cant accses my wolrd now. 

**Expected behavior**
Fix
**Screenshots**

**Additional context**
[crash-2020-11-28_12.48.10-server.txt](https://github.com/AllTheMods/ATM-6/files/5610544/crash-2020-11-28_12.48.10-server.txt)

**Comment by jeremiahwinsley** [comment]
Fixed in 1.3.9.
