### ISSUE TITLE
Another Environmental Tech Crash (interacting with Refined Storage)

### ISSUE THREAD

**Issue by Treep3r** [AllTheMods/ATM-6#439]
So whenever I try to connect (not place) a Refined Storage Crafter that is attached to a Environmental Tech assembler to the main storage system, the entire server crashes and the world becomes unplayable.

I was unable to reproduce this in singleplayer, however whenever I loaded a backup of my world and tried again, it would always crash with the same error (attached to this report).
The order in which the setup is placed does not seem to matter, although I noticed that if I place the crafter first it would not crash immediatly, but rather after I try to open the crafters UI. 

**To Reproduce**
1. Create a fairly large RS system
2. Try to attach a crafter on an ET assembler to the system

**Expected behavior**
No crash

**Additional context**
I don't know if this bug is related to https://github.com/AllTheMods/ATM-6/issues/436, which is why I'm creating this one separately.
[crash-2020-11-28_16.52.55-server.txt](https://github.com/AllTheMods/ATM-6/files/5610938/crash-2020-11-28_16.52.55-server.txt)

**Comment by kill05** [comment]
i'd suggest reporting this bug to the devs of the mod too

**Comment by Gh3ttoboy** [comment]
i can vouch for this issue aswell happend to me on a server aswell only we had to remove the 5 mods related to Envirometal tech so the assembler would be unloaded for sure

**Comment by bbf** [comment]
This issue has been reported and fixed in dev:
https://github.com/ValkyrieofNight/EnvironmentalTech/issues/216

**Comment by ReillyBrogan** [comment]
This fix is part of the latest ValkyrieLib release (3.0.4.3)
