### ISSUE TITLE
Errors in Selected Datapacks

### ISSUE THREAD

**Issue by LittleRunt** [AllTheMods/ATM-6#44]
So... Some of the datapacks seem to not like each other. I can't load into a world and can't create a world without getting an error.

**"Errors in currently selected datapacks prevented the world from loading. You can either try to load only with vanilla datapack ("safe mode") or go back to the title screen and fix it manually"**

There's no way to remove the data packs or load into safe mode, so this modpack is basically unplayable.
I also keep seeing this runtime exception in the logs after trying to create a world:

> [16:17:24] [Render thread/WARN]: Couldn't get pack info for: java.nio.channels.ClosedChannelException
[16:17:24] [Render thread/WARN]: Failed to load datapacks, can't proceed with server load
java.lang.NullPointerException: null

**Comment by FnordMan** [comment]
Also ran into that, so far restarting Minecraft fixes that but it only works once. When you save & quit the issue shows up again, requiring another restart.
