### ISSUE TITLE
TPA cooldown and SetHome 

### ISSUE THREAD

**Issue by luka0033** [AllTheMods/ATM-6#440]
Dear dev Team!

We are having problems with the command /SetHome (Name). After you execute the command the line "You can't create more homes" appears, even if the player never set a home point.

With the tpa we get a 7 day cooldown on a tpa. So after you use it, you can't use it for 7 days.
We have a Server hosted at GPORTAL. I searched for any solution in the config files found nothing. 
I have even searched for it in the Server Files with FileZilla on the FTB Server. Can't find the Essentials files in any way.

Can you please help me with that?
Kind regards.

**Comment by xyrilth** [comment]
I also have the same problem with my server :(

**Comment by ViRb3** [comment]
https://github.com/AllTheMods/ATM-6/issues/334
There's `world\serverconfig\ftbessentials-server.toml`, where you can adjust all these settings. Do `/ftbranks reload` to apply them afterwards without restarting.

**Comment by xyrilth** [comment]
this doesnt work for me maybe the mod is broken?

**Comment by ViRb3** [comment]
What doesn't work? What did you do, what do you expect to happen, what happens instead? Please give some details or we can't help you.

**Comment by xyrilth** [comment]
I've tried the following and it's still not working:

/ftbranks reload
update ftbessentials-server.toml file on both the default config folder and the world config folder with lower cooldowns and increased max homes
reinstalled the mod completely
restarted the server after each of the above

The tp functions cooldown is 7 in-game days and you can't set homes at all. The cooldown numbers have been updated on the .toml files but the mods seem to just ignore whats in the file.

**Comment by xyrilth** [comment]
Here's what I have on the file:

#Max number of times you can use /back
#Range: > 0
maxBack = 10
#Max homes
#Range: > 0
maxHomes = 1
#/back cooldown in seconds
#Range: 0 ~ 604800
backCooldown = 30
#/spawn cooldown in seconds
#Range: 0 ~ 604800
spawnCooldown = 10
#/warp cooldown in seconds
#Range: 0 ~ 604800
warpCooldown = 10
#/home cooldown in seconds
#Range: 0 ~ 604800
homeCooldown = 10
#/tpa cooldown in seconds
#Range: 0 ~ 604800
tpaCooldown = 10
#/rtp cooldown in seconds
#Range: 0 ~ 604800
rtpCooldown = 600
#Number of tries before /rtp gives up
#Range: 1 ~ 1000
rtpMaxTries = 100
#/rtp min distance from spawn point
#Range: 0.0 ~ 3.0E7
rtpMinDistance = 1000.0
#/rtp max distance from spawn point
#Range: 0.0 ~ 3.0E7
rtpMaxDistance = 100000.0

**Comment by xyrilth** [comment]
What happens when we use the commands:
/back - "Teleportation history is empty!" (used after dying)
/spawn - Teleports you to spawn (7 in-game day cooldown)
/home [name] - "Home not found!"
/sethome <name> - "Can't add anymore homes!"
/tpa <player> - Teleports you to player (7 in-game day cooldown)

**Comment by WhitePhant0m** [comment]
Edit the file located in packfolder/defaultconfigs/ftbessentials-server.toml

**Comment by xyrilth** [comment]
thank you works now!

**Comment by luka0033** [comment]
Thanks for all of your replies, found the folder right away (searched in the complete different direction before).
I need to test it still but I'm confident that if works.

**Comment by Rocknryan55** [comment]
> Here's what I have on the file:
> 
> #Max number of times you can use /back
> #Range: > 0
> maxBack = 10
> #Max homes
> #Range: > 0
> maxHomes = 1
> #/back cooldown in seconds
> #Range: 0 ~ 604800
> backCooldown = 30
> #/spawn cooldown in seconds
> #Range: 0 ~ 604800
> spawnCooldown = 10
> #/warp cooldown in seconds
> #Range: 0 ~ 604800
> warpCooldown = 10
> #/home cooldown in seconds
> #Range: 0 ~ 604800
> homeCooldown = 10
> #/tpa cooldown in seconds
> #Range: 0 ~ 604800
> tpaCooldown = 10
> #/rtp cooldown in seconds
> #Range: 0 ~ 604800
> rtpCooldown = 600
> #Number of tries before /rtp gives up
> #Range: 1 ~ 1000
> rtpMaxTries = 100
> #/rtp min distance from spawn point
> #Range: 0.0 ~ 3.0E7
> rtpMinDistance = 1000.0
> #/rtp max distance from spawn point
> #Range: 0.0 ~ 3.0E7
> rtpMaxDistance = 100000.0

what values did you edit this to and did it work? im having the same issue ive tried to change the values above but no changes seem to have been applied. I have used /ftbranks reload and have simply tried restarting the server to get the changes to apply
