### ISSUE TITLE
Pedestal crash

### ISSUE THREAD

**Issue by Drcoconotz** [AllTheMods/ATM-6#441]
The crash happened when I placed down a pedestal and added 3x3 crafting upgrade. I then put a vanilla furnace in it / right clicked it while in my hand to showcase it, after I put a hopper that was going into the pedestal, then I added a stack of cobblestone to the hopper because I was testing how to use the auto crafting upgrade and the game crashed and I am unable to go into the world.

**To Reproduce**
1. Place down pedestal
2. Add a 3x3 pedestal upgrade
3. Right click on pedestal with vanilla furnace in hand
4. Place down vanilla hopper the was emptying into the pedestal
5. Add cobblestone to hopper
6. Crash occurs

**Expected behavior**
The game crashes and you are now unable to join the world

**Screenshots**
Impossible to get into world.

**Additional context**
It's in the latest version that is 1.3.1 ATM 6

**Comment by Lulloser** [comment]
Pedestrals seem to be really unstable, my game crashed when I placed down an Auto Attacker Pedestral.  I was able to load the map after 3 crashes and remove the Pedestral no crashes since.

**Comment by Drcoconotz** [comment]
> Pedestrals seem to be really unstable, my game crashed when I placed down an Auto Attacker Pedestral. I was able to load the map after 3 crashes and remove the Pedestral no crashes since.

I've tried to load in the world a few times but I haven't gotten a chance to get to the pedestal because of the immediate crash. I'm going to keep trying but I'm thinking I'm probably will have to wait till it gets fixed.

**Comment by Lulloser** [comment]
I joined the Pedestral Mod Authors Discord and he has an Update that has fixed my problem.  You could try and see if it fixes yours.

https://cdn.discordapp.com/attachments/725528892051554304/782144718791376906/pedestals-0.8i.jar

**Comment by Drcoconotz** [comment]
Where can I find the discord?

**Comment by Lulloser** [comment]
https://discord.gg/TGZSt7k

**Comment by jeremiahwinsley** [comment]
Fixed in 1.3.9.
