### ISSUE TITLE
Bigger Reactors Crash

### ISSUE THREAD

**Issue by Rihadist** [AllTheMods/ATM-6#442]
**Describe the bug**
Server crashes when attempting to place other reactor casing onto an already running reactor. 

**To Reproduce**
1. Create a reactor
2. Try to place casing onto the running reactor

**Expected behavior**
In my past experience with Big Reactors (1.12.2), it would stop the reactor and make it an unfinished reactor with the addition of the new piece that makes it ineligible for a working reactor. 

**Additional context**
Local server running version 1.3.2c
crash log: https://pastebin.com/phF0N7Ns

**Comment by RogueLogix** [comment]
That's still the correct behavior.

Patched in 0.2.6

**Comment by jeremiahwinsley** [comment]
Fixed in 1.3.9.
