### ISSUE TITLE
Cant access the nether of the end

### ISSUE THREAD

**Issue by Yeti231** [AllTheMods/ATM-6#443]
On my server, there is an issue where we cannot access the nether or the end. We have tried everything found online. We have tried taking the dim1 and dim-1 of another saved world and that did not work either. We don't want to restart our world after all the work we have put in and I don't want to restart just to have this happen again.
 
Any help would be greatly appreciated I have spent hours at this already and I'm very lost.

**Comment by ViRb3** [comment]
#437
