### ISSUE TITLE
[1.3.3] Rampant memory leaks

### ISSUE THREAD

**Issue by SkyeRise** [AllTheMods/ATM-6#444]
No matter if somebody is online, memory usage increases continuously. This is a server that is only 2 days old with 2 players.

**To Reproduce**
1. Let it run on a server for any amount of time and in under 12h 8GB of RAM are exceeded
**Expected behavior**
Constant or only slightly leaky behavior

**Screenshots**

**Additional context**

**Comment by ViRb3** [comment]
If you can, please create a heap dump ([JProfiler](https://www.ej-technologies.com/products/jprofiler/overview.html)) and upload a screenshot of the biggest object graph here. I will eventually get back to tracking and fixing memory leaks, but I'm a bit busy atm.

**Comment by SkyeRise** [comment]
I am not familiar with this tool at all nor do I believe that I would be able to install and run it on my rented server. For now I am having a stable experience with 12h reboot cycles and having increased RAM to 10GB. I guess I will just have to wait until whichever mod/s is causing it has/have been updated/fixed. Until then, you are at least made aware of the issue.

**Comment by anid2nice** [comment]
Give me some time I am working on getting some data since I am having exactly the same problem.

**Comment by andrewsf** [comment]
Using a lot of memory is not a symptom of a memory leak. Without some sort of data that points to memory not getting freed when it is no longer being used, it would be wiser to chalk this up to 

Minecraft, particular with heavy modding, would be perfectly happy to use 64GB of memory if you gave it 64GB of memory.

Now, writing mods/features to be slim is a different matter.

Are you sure this isn't a case where you should get more memory on your server, allow fewer simultaneous users, or enable fewer mods?

**Comment by anid2nice** [comment]
Actually with my 7gigs it should be enough and with his 10 gigs it should be enough. After trying a plugin to get a heap dump and going over it with my server support we figured out it was a hosting problem and not a pack issue. @SkyeRise I suggest you do the same, you said you third party host so I would get in touch and make sure there aren't problems on their end.
