### ISSUE TITLE
Teleport Pad duplicates

### ISSUE THREAD

**Issue by Rihadist** [AllTheMods/ATM-6#445]
**Describe the bug**
When you go through a teleport pad, break it, replace it again in a different spot, a new portal is created on the other side creating a duplicate one.

**To Reproduce**
1. Place teleport pad
2. Go through to mining dim, then go back to the overworld
3. Break portal
4. Place down in any different location
5. Go back through to mining dim
6. Two portals

**Expected behavior**
Pretty sure this isn't intended, it should not dupe portals.

**Additional context**
On version 1.3.3

**Comment by andrewsf** [comment]
This sounds very similar to the vanilla behavior of portals? You can generate obsidian just by repeatedly mining and regenerate them.

Given that teleport pads are not particularly expensive (yes, they are progression gated), it might not be worth the effort to try to prevent the duplicating.

The game's solution for this (in The End) is to make one-way portals, and then to have an immutable return portal. That seems less fun?

**Comment by whatthedrunk** [comment]
Seems we just have to deal with it. We might try something new in 1.17 though. Either way you still need the first.
