### ISSUE TITLE
Cyclic Disenchanter Book Duplication

### ISSUE THREAD

**Issue by MdBourg98** [AllTheMods/ATM-6#447]
Cyclic Disenchanter can pull unlimited enchanted books from 1 Quark Ancient Tome.

![image](https://user-images.githubusercontent.com/57682576/100555170-b8e57d80-3267-11eb-872d-ff8ef8458e1e.png)
![image](https://user-images.githubusercontent.com/57682576/100555196-d1559800-3267-11eb-9e18-8783e4e39dae.png)

**Comment by andrewsf** [comment]
I think Cyclic would need to build an exception for this.
https://github.com/Lothrazar/Cyclic/issues

**Comment by Pdiddy973** [comment]
fixed in 1.4.0 https://github.com/Lothrazar/Cyclic/issues/1684
