### ISSUE TITLE
Mekanism Digital Miner Filter useless

### ISSUE THREAD

**Issue by Seegras** [AllTheMods/ATM-6#45]
This might be a config setting on your side, but also might be upstream. 

It says it will filter "similar blocks". Well, "Stone" is in no way similar to "Redstone Ore", resulting in 60000 blocks to mine at radius 32, height 18. The inverse is 2000 blocks..

The only filter that remotely works is for ancient debris. Which also finds topaz, rubin and amethyst from blue power in ther overworld..

**Comment by FnordMan** [comment]
For ores you have to use the tag system. 

Like to do iron ore you set the tag to: "forge:ores/iron", f3+h should show the tags on the ores.
