### ISSUE TITLE
Mekanism Solar Panel reverted to original recipe

### ISSUE THREAD

**Issue by Darkkender** [AllTheMods/ATM-6#451]
I'm not certain if the Mekanism Solar Panel base panel was changed by accident IE a bug or if it was intentional.  I started playing ATM6 and was about to build a basic solar array when I found the base recipe no longer uses 3 glass panes for the base panel and now uses 3 of the "Powah" Starter Solar Panels.

A couple of thoughts this makes the entry point for this one particular type of power generation even more expensive on resources than it already is.  The Solar Panels are some of the more resource expensive units before you start getting into Fission reactors and the sort within this mod.  My second thought is that you are effectively building "Powahs" base solar panel cell to fill in the spot for 3 glass panes it's almost kind of like an inception moment for solar energy 3 solar panel cells too craft 1 solar panel cell in which you need 3 solar panel cells to craft 1 solar panel.

If your desire is too make Mekanism solar a higher entry point than it already is and use Powah might I suggest changing the recipe to use 3 Photoelectric Pane's from "Powah".  This would certainly increase the base resource cost and seem like a more logical replacement for a glass pane.

Alternatively if you would like to increase the entry without overly breaking Mekanism maybe require 3 "Blue Panes" of glass that would require getting lapis as well or some other source for blue dye.

Please whichever of my suggested choices if this was Intentional please scale it back some because it is overkill currently.

**Comment by andrewsf** [comment]
Please see #214 wherein a dev essentially said "we don't want you to play Mekanism as-is"

**Comment by Darkkender** [comment]
> Please see #214 wherein a dev essentially said "we don't want you to play Mekanism as-is"

I'm ok with intentional changes.  I was suggesting a change that makes better sense by using Powah's Photoelectric Pane which is a base component in the Solar Cell and eliminates the Inception type of feeling.

**Comment by andrewsf** [comment]
I saw the recommendation. I made essentially the same recommendation in #214.
