### ISSUE TITLE
crash when building Enviromental Tech void miner

### ISSUE THREAD

**Issue by Pdiddy973** [AllTheMods/ATM-6#452]
right after building Tier 1 void miner ATM6 Mining DIM, server crashed, and when Void miner was loaded /when i logged in, crashed again, how ever if it was not loaded, server would run fine.

Build tier 1 void mine in ATM6 mining DIM

[crash-2020-11-30_08.12.23-server.txt](https://github.com/AllTheMods/ATM-6/files/5614889/crash-2020-11-30_08.12.23-server.txt)
[crash-2020-11-30_08.13.17-server.txt](https://github.com/AllTheMods/ATM-6/files/5614890/crash-2020-11-30_08.13.17-server.txt)
[crash-2020-11-30_08.26.20-server.txt](https://github.com/AllTheMods/ATM-6/files/5614891/crash-2020-11-30_08.26.20-server.txt)
[crash-2020-11-30_08.27.13-server.txt](https://github.com/AllTheMods/ATM-6/files/5614892/crash-2020-11-30_08.27.13-server.txt)

**Comment by xd3nny** [comment]
#436
