### ISSUE TITLE
RGBee Despawning

### ISSUE THREAD

**Issue by NoMoreStars** [AllTheMods/ATM-6#455]
**Describe the bug**
The RGBee seems to occasionally de-spawn from the world. I can't know for sure if this is exactly what happens but I've had multiple instances of RGBees disappearing from enclosed bee farms with all other bees remaining unharmed. Only potential sources of harming the RGBees in the enclosure would potentially be campfires situated directly underneath closed trap doors. No other bee's are found to despawn.

**To Reproduce**
1. Collect an RGBee in the wild (either through silk-touching a bee hive or a capturing it in a bee jar, ender lead, etc.)
2. Put RGBee in enclosed space with no harmful blocks accessible to it
3. Wait

**Expected behavior**
RGBee is a neutral animal-type mob that should not despawn from the world unless killed.

**Screenshots**
Example of enclosure the most recent RGBee was kept in:
![2020-11-30_16 02 27](https://user-images.githubusercontent.com/38673759/100671462-2821a700-3326-11eb-97fd-b929be4a8edb.png)
![2020-11-30_16 02 41](https://user-images.githubusercontent.com/38673759/100671493-340d6900-3326-11eb-8c7e-b0489f387b86.png)
![2020-11-30_16 03 00](https://user-images.githubusercontent.com/38673759/100671520-3ec7fe00-3326-11eb-8814-cf758e51a2d0.png)

**Additional context**
I'm wondering if perhaps the RGBee and potentially other bees are somehow contributing to the hostile mob-cap and as a result sometimes de-spawning in a manner similar to hostile mobs. I admit that this only happened a couple of times but I thought I might as well report it as a bug since the same exact situation happened twice for the same bee type.

**Comment by ariosos** [comment]
Hmm, might explain why I haven't seen any Resourceful Bees in my area after awhile. I've been playing for maybe 20+ hours (estimate) and the only bees around are vanilla.

**Comment by oly2o6** [comment]
Please report this to the mod author, if this is on our end please open a new ticket and quote this one for reference
