### ISSUE TITLE
Crashing when launching using the CurseForge app 

### ISSUE THREAD

**Issue by SentientDarkness** [AllTheMods/ATM-6#456]
When I try to launch the modpack using the CurseForge app, the game starts loading, but shortly crashes and gives the following report. 
![image](https://user-images.githubusercontent.com/75282349/100676414-c29edc00-3360-11eb-93ca-af1a7647a2cd.png)

I tried reinstalling the modpack, tried reinstalling the CurseForge app, tried reinstalling Minecraft, updating Java, but nothing has worked.

**Comment by Xenovalis** [comment]
How much RAM have you allocated?

**Comment by SentientDarkness** [comment]
> How much RAM have you allocated?

12 GB, but I also tried higher values, same thing happened.

**Comment by RogueLogix** [comment]
#384

**Comment by SentientDarkness** [comment]
> #384

That helped, it's working now. Thank you!
