### ISSUE TITLE
Game gets stuck freezing data with a full loading bar

### ISSUE THREAD

**Issue by zhyza** [AllTheMods/ATM-6#457]
The game takes five minutes to load, then gets stuck here. It keeps doing this. The longest I've waited for it to load was about 20 minutes, but no matter how long I wait, it never loads. The only fix I found online was deleting Minecraft and re-downloading. I've tried this and it didn't work. What do I have to do to get past this?
Edit: Once I've gotten further than the "freezing data" screen and then it got stuck "remapping mod data."
Edit2: The fix was, apparently, to not move the Minecraft window while it was loading.
![image](https://user-images.githubusercontent.com/75283833/100679841-3c18d900-3325-11eb-8363-cce1cacde37c.png)

**Comment by Xenovalis** [comment]
2 GB is not enough to play ATM6
