### ISSUE TITLE
Missing Mystical Agriculture Uranium from Essence Crafting Recipe

### ISSUE THREAD

**Issue by jblankenship30** [AllTheMods/ATM-6#458]
You can create uranium seeds in Mystical Agriculture but when you go to craft uranium from the essence there is no recipe available.

**Comment by RogueLogix** [comment]
BlakeBr0/MysticalAgriculture#332
BlakeBr0/MysticalAgriculture#336

**Comment by jblankenship30** [comment]
I should mention I am running ATM6 version 1.3.3 with a world that was created with version 1.3.1

**Comment by andrewsf** [comment]
Not related to BlakeBr0/MysticalAgriculture#332 or BlakeBr0/MysticalAgriculture#336, which are very old.

This is a new issue, and I think it was introduced in 1.3.2c.
