### ISSUE TITLE
Plant texture glitch after using Mystical Agriculture watering can

### ISSUE THREAD

**Issue by Farkor123** [AllTheMods/ATM-6#462]
**Describe the bug**
When growing plants using Mystical Agriculture watering can textures are glitching, e.g. only 2 bottom layers of tree are visible, bamboo grow out of bamboo sapling texture with space between them, etc.

**To Reproduce**
1. Plant for example 2x2 dark oak saplings
2. Water one of them using Mystical Agriculture simplest watering can
3. Bug should be there

![image](https://user-images.githubusercontent.com/28457368/100766686-34c2ff80-33f9-11eb-8131-cec1727045e8.png)

**Comment by oly2o6** [comment]
potential mod issue but cannot replicate this myself so will close for now
