### ISSUE TITLE
Duplication Glitch with DimStorage Chest and Drawers

### ISSUE THREAD

**Issue by ElectricSweetPotato** [AllTheMods/ATM-6#463]
Description:
Placing a DimStorage Chest next to a drawer with items in it and setting the chest to "collecting" will pull the item into the chest without removing it from the drawer, duplicating the item(s) indefinitely.

Steps to Reproduce:
1. Place down a drawer.
2. Put any item in the drawer. Amount does not matter.
3. Place down a DimStorage Chest next to the drawer. (see Setup Screenshot)
4. Set the DimStorage Chest to "collecting" (see DimStorage Chest GUI Screenshot)
      - Open the menu for the chest by clicking on the arrow on the top right side of the chest's GUI
      - Clicking on the button that says "Idle" at the very bottom will change it to "collecting"

Expected Behavior:
When the DimStorage Chest collects from the drawer, it should remove the item(s) from the drawer's inventory and put it in its own.

Screenshots:
Setup:
![2020-12-01_21 28 06](https://user-images.githubusercontent.com/75094305/100820920-4b7b4d80-341d-11eb-8743-ef3096e85d16.png)
DimStorage Chest GUI:
![2020-12-01_21 28 35](https://user-images.githubusercontent.com/75094305/100820932-51712e80-341d-11eb-9d51-2e3e1bebc4ae.png)

**Comment by oly2o6** [comment]
please report these to both of the mod authors so they can work out which one of them would need to implement the fix, you can quote this issue directly on their githubs even though its closed
