### ISSUE TITLE
A couple of bugs with 1.3.3 version

### ISSUE THREAD

**Issue by MrStatman80** [AllTheMods/ATM-6#465]
First one is Mekanism as with Fission fuel

I try and make the anti matter and the plutonium pellets and with this current version it doesn't work as i have it all set up correctly but it doesn't work.

Second one is Resourceful bees

I placed 9 unique bees in a apiary and then after a few minutes they disappear

I know the mods are still in beta testing... so just wanted you to know

**Comment by oly2o6** [comment]
please make sure these are reported to the mod authors
