### ISSUE TITLE
[1.3.3] Teleport pad removes XP temporarily

### ISSUE THREAD

**Issue by Rihadist** [AllTheMods/ATM-6#468]
Going through a teleport pad removes XP levels. The only way I have found to get them back is to get XP from a new source and then the levels show up again.

**To Reproduce**
1. Get levels
2. Go through teleport pad

**Expected behavior**
Should not remove levels.

**Comment by zoratoune** [comment]
This is a common bug when you change dimension it's been around in modded minecraft for years.
