### ISSUE TITLE
[1.2.0] Server is not saving chunks to disk after typing save-all.

### ISSUE THREAD

**Issue by ovingiv** [AllTheMods/ATM-6#469]
So for a few days now I have been running into an issue where my server won't save chunks and days of progress is lost because of it. This is now the second time this has happened.
It happens when the server has been running for about 2 to 3 days and it would just stop saving. 

The command save-all would be ran and it says save successful but when a backup is made, only a handful of mb would be the difference after 24 hours. 
![image](https://user-images.githubusercontent.com/24558152/100889177-76e15500-347c-11eb-9650-41ef38b1a91b.png)

I have logs dating back to Nov 3rd so I'll share them in a Google Drive folder [Here](https://drive.google.com/drive/folders/1JSfr78i8PwQqNvKmWULNS1vYiPnyHZvF?usp=sharing)

Notable dates are 25th - 27th is when it happened the first time and Nov 29th to Dec 2nd.

This is for ATM6 - 1.2.0 
Forge: 1.16.3 - 34.1.25

Server: Dell T410
CPU: 2x Intel Xeon X5670s
RAM: 64GB (8x8gb) 1333MHz DDR3
SSD: Two Hitachi 200GB SAS SSD in Raid 0.
OS: Ubuntu Server 20.04 LTS running MineOS 2cd410a (Latest revision)

**Comment by oly2o6** [comment]
we can no longer support older versions of minecraft, if after updating to the latest this still happens please open a new ticket
