### ISSUE TITLE
HUMONGOUS JEI bookmark arrows in refined storage crafting grid

### ISSUE THREAD

**Issue by Farkor123** [AllTheMods/ATM-6#470]
Well...

![image](https://user-images.githubusercontent.com/28457368/100914968-0fef8a80-34d4-11eb-9df2-fe8b4c0c8e99.png)

**Comment by willownezz** [comment]
from what I noticed when you are inside the crafting grid from Refined Storage and you have something added to the bookmark the button size will increase every time you click to find a recipe with "r" for finding recipies

**Comment by oly2o6** [comment]
please report this to refined storage, if it is somehow on our end please open a new issue and we will look into it further
