### ISSUE TITLE
Missing Crafting recipe for Harvestcraft's Silken Tofu

### ISSUE THREAD

**Issue by jnamovic** [AllTheMods/ATM-6#472]
Silken tofu from Pam's Harvestcraft 2 Food Extended appears in the JEI, and has uses in other recipes but cannot be crafted itself.

I tried various combinations of harvest craft tools with Harvestcraft soybeans but the only craft-able items were Harvestcraft soy milk, Harvestcraft soy sauce, and cheese from the Rats mod.

**Comment by oly2o6** [comment]
please report this to the mod author directly
