### ISSUE TITLE
Nether star modifier in spawner doesn't work

### ISSUE THREAD

**Issue by Namoku** [AllTheMods/ATM-6#475]
I have a force load chunk and when I leave the mobs don't spawn. Is it disabled that option? Or just is a bug?

**Comment by HalationEffect** [comment]
Nether star won't prevent spawned mobs from instantly despawning if the player is too far away from the spawner. Try adding a spawner agitator from Pneumaticraft onto your spawner.

**Comment by Namoku** [comment]
I felt so dumb bro...
Thank you, it was 6 am and Idk what was I doing. I though I don't need it bc in PO3 I killed them instantly with the grinder from industrial foregoing.
