### ISSUE TITLE
 Environmental Tech Needs An Update

### ISSUE THREAD

**Issue by Bultjer** [AllTheMods/ATM-6#476]
If you want to build a multiblock structure from environmental tech, you do not know which blocks are needed.
In a newer Version of this mod tooltips were added, which indicate what is needed.

It would be nice, if you could update environmental tech and all it dependencies.

**Comment by oly2o6** [comment]
we are currently awaiting on a curse update before we can update our modpacks, as soon as its possible there will be an update out the same day with every mod up to date
