### ISSUE TITLE
Possible bug in solar panel tier 1 recipes

### ISSUE THREAD

**Issue by Farkor123** [AllTheMods/ATM-6#477]
I don't think these should give the same amount of solar panels per craft

![image](https://user-images.githubusercontent.com/28457368/101057536-6cae7c00-358c-11eb-886a-5e7f428abdf2.png)

**Comment by NetMasterFlex** [comment]
Is it uncommon to have multiple recipes for the same item?  Providing additional recipes allows for different paths to create the same item.

**Comment by 12lewisFTW** [comment]
> Is it uncommon to have multiple recipes for the same item? Providing additional recipes allows for different paths to create the same item.

why would you ever make the bottom recipe

**Comment by NetMasterFlex** [comment]
I don’t know man! Trying to understand it myself. LOL
