### ISSUE TITLE
End Biomes overlook?

### ISSUE THREAD

**Issue by Rithenar** [AllTheMods/ATM-6#478]
**Describe the bug**
It appears that there is no Ivis Fields biome in the End so there is no access to Ivis Phylium, yet it appears as a valid soil for Chorus Flower in a Botany Pot.

**Screenshots**
![image](https://user-images.githubusercontent.com/9939332/101071610-76bb8500-3562-11eb-84c4-b0ae628758b4.png)

**Comment by oly2o6** [comment]
i would hazard a guess the biome is not implemented yet
