### ISSUE TITLE
Game instantly crashes on launch.

### ISSUE THREAD

**Issue by PeachIceCreamy** [AllTheMods/ATM-6#48]
[latest.log](https://github.com/AllTheMods/ATM-6/files/5043676/latest.log)

**Comment by LeadAssimilator** [comment]
There is a pathing bug somewhere. As a workaround, change your Minecraft Path in the Twitch app (Profile Picture -> Settings -> Minecraft -> Minecraft Path -> Change) to a path that does NOT contain spaces like C:\Twitch\Minecraft instead and rename/move your existing folder to match the new location.
