### ISSUE TITLE
How do I run a server using this modpack?

### ISSUE THREAD

**Issue by alamb91** [AllTheMods/ATM-6#482]
I downloaded the simple server files 1.3.3 but I'm unsure of how to proceed from there.

**Comment by mkaito** [comment]
You run either the `.bat` if you are on Windows or the `.sh` if you are on Linux (`chmod +x` first). It will install the server and then start it for you.

**Comment by alamb91** [comment]
Alright, I can use the server now, but I can't type anything in for commands?

**Comment by embeddedt** [comment]
I also noticed that the console does not work. You might have to invoke the server JAR by hand to get access to the console.
