### ISSUE TITLE
Ice and Fire Mobs not spawning

### ISSUE THREAD

**Issue by Tristan324** [AllTheMods/ATM-6#483]
I have flown around for over an our in the other over 3000 blocks away from spawn, deleted region folder multiple times trying to reload and nothing fixed it. I also attempted to delete ice and fire biome.toml and it reset everything to overworld and the mobs spawned just fine however I changed the config back to "the other" biome and nothing spawns again.

**Comment by Tristan324** [comment]
This is all the mods 6 btw

**Comment by Tristan324** [comment]
Loaded up a single player world and didnt seem to have ice and fire spawns in "the other" on the single player world either

**Comment by NetMasterFlex** [comment]
Helps to state what version of ATM6 ie Version 1.2.1, 1.2.1c, 1.3.3, 1.3.0 etc.

**Comment by Tristan324** [comment]
The latest release, sorry!

**Comment by ViRb3** [comment]
Known issue, this is a bug in the mod. We are actively looking for a fix, either an update to the mod or a workaround. Will let you know when that's out.

**Comment by ViRb3** [comment]
#356

**Comment by kowani021** [comment]
its still a problem in 1.3.3 no ice and fire spawns or structures
