### ISSUE TITLE
ATM6 1.3.3 Skystone chest pulls inventory when sort button clicked

### ISSUE THREAD

**Issue by NetMasterFlex** [AllTheMods/ATM-6#484]
Just as the title reads.  

1.  Place Skystone Chest
2.  Add items from personal inventory
3.  Click Sort button right of chest grid.
4. All other items not previously moved currently in personal storage get sucked into the chest .

Is this normal for Skystone Chests?

Expected Behavior:

Items are sorted in Skystone Chest grid while leaving unmoved personal items on person.

**Comment by oly2o6** [comment]
will be looked into
