### ISSUE TITLE
Refined storage crashed with Environmental Tech

### ISSUE THREAD

**Issue by CQubed15** [AllTheMods/ATM-6#486]
*Description*
I was playing on a server in the most recent version of ATM 6 (1.3.3) and attempted to set up autocrafting for the newly added Environmental Tech mod, and placed a Refined Storage crafter on top of the Assembler block. This caused the entire server to crash, not just my client, and kicked the other player also playing.

*Steps*
Steps I followed that produced the behavior:
1. Placed down an Environmental Tech Assembler.
2. Filled the power reserve on the Assembler.
3. Shift right-clicked a Refined Storage crafter onto the top of the Assembler.
(Refined Storage crafter would have been connected to another crafter once placed, and therefore powered as part of my system.)

*Expected*
The ability to connect the Refined Storage crafter block to the Assembler from Environmental Tech.

*Additional*
I am not the server admin nor do I have any access to crash logs, but can probably supply them if needed by asking the admin. Luckily our server backed up right before this occurred so there was no loss on our end, but probably don't try to hook up the same sort of system on your own worlds. We have not yet attempted to restart and reconnect as the server crashed overnight, so I am not sure if the world has been corrupted or if it can be fixed by restarting the pack.

**Comment by BedrockLegends** [comment]
Has been fixed in this version of the mod https://www.curseforge.com/minecraft/mc-mods/valkyrielib/files/3126900
