### ISSUE TITLE
Tip upgrades do not carry harvest level increase for allthemodium, vibranium, unobtainium

### ISSUE THREAD

**Issue by mkaito** [AllTheMods/ATM-6#487]
**Describe the bug**
Silent Gear Tip Upgrades for Allthemodium, Vibranium, Unobtainium do not apply harvest level. They all apply +6 harvest _speed_, but do not modify harvest level. That means I have to craft a whole new pick with each level, which seems unnecessary.

**To Reproduce**
1. Look at SGear tooltip for the ingots
2. Observe lack of harvest level in "tip upgrade" section

**Expected behavior**
Expect the tip upgrade to carry the corresponding harvest level associated with the material.

**Screenshots**
https://imgur.com/a/2Z0amOS

**Additional context**
As Silent Gear has poor end user documentation, there might be a way around this that I am not aware of.

**Comment by thevortex** [comment]
resolved with https://www.curseforge.com/minecraft/mc-mods/allthemodium/files/3133150
