### ISSUE TITLE
Nether soil blocks not valid apiary blocks

### ISSUE THREAD

**Issue by mkaito** [AllTheMods/ATM-6#489]
Nether-native bees usually require nether flora to pollinate, such as nether wart. Nether wart in particular only grows on soul sand. Soul sand is not a valid apiary block, so it can not be placed in the apiary floor.

Other such blocks are Crimson Nylium and Warped Nylium, which can support Nether flora planted on them.

Search JEI for `$nether_flower` and see what blocks they can be planted on. All of them should be `valid_apiary`.

**To Reproduce**
1. Build apiary
2. Place one soul sand block in floor
3. Observe apiary refuses to form multiblock

**Expected behavior**
Being able to place nether soils in the apiary floor

**Comment by Treep3r** [comment]
You can just place the things you need inside the apiary, the only blocks that need to be valid are the ones that form the actual multiblock.

**Comment by mkaito** [comment]
True, but why not? The mod author is open to adding more blocks (https://github.com/Resourceful-Bees/ResourcefulBees/issues/82) and it makes sense to have any blocks that make sense at least in the floor. You wan to keep the ground flat and the room free of obstacles, because bees are stupid and get stuck on anything (https://github.com/Resourceful-Bees/ResourcefulBees/issues/79).

In particular, since you want bees to pollinate certain kinds of flowers, it makes sense to have the required soil be in the apiary floor, so you can place the flowers on top.

Plus, some of us like to make things pretty, and this gives us more tools to work with to that end.
