### ISSUE TITLE
Unbreakable Securitycraft Block (cannot be broken with a "Universal Block Breaker")

### ISSUE THREAD

**Issue by Halloxe** [AllTheMods/ATM-6#49]
securitycraft reinforced block placed by using wands from construction wand cannot be broken by the player who made it, it says "Onwer: onwer"

**Comment by WhitePhant0m** [comment]
Security craft blocks check who placed them, and if it can't find the one who placed the blocks, it will make the blocks have no owner, which in turn means that you will be unable to break them, place them by hand, the wand doesn't tell the blocks that you were the one placing the blocks

**Comment by oly2o6** [comment]
This is an issue for the mod author, there isn’t anything we can do to resolve this

**Comment by Theta-Dev** [comment]
I have fixed the issue in Construction Wand 1.17 after WiseHorror reported it to me.
https://github.com/Theta-Dev/ConstructionWand/issues/29

If you had reported it directly to me, it could have been fixed much sooner.
