### ISSUE TITLE
Backpacks lag the game in ATM6 1.3.3

### ISSUE THREAD

**Issue by Wululululu** [AllTheMods/ATM-6#490]
**Describe the bug**
If a backpack contains items with lots of NBT data, selecting the backpack (not even opening it) causes FPS drops and extreme stuttering. Opening it reduces FPS to a slideshow. 
I experienced this with Backpacks containing Spawners (from the Dungeons mod) or containing Resourceful bees in jars (and some beehives). 

**To Reproduce**
1. Craft a backpack (upgrade to a large one)
2. Fill it with bees in jars and some mob spawners
3. Watch the framerate drop. 
4. Unselect the backpack and watch FPS come back to normal.

**Expected behavior**
I expected the game to not lag, when I select a backpack in my hotbar.

**Additional context**
This lagging behavior of the backpacks wasn't present in the 1.2.1 version of the pack, where I migrated from. There was only lag, if extended item infos are shown (F3+h) and shift was pressed while hovering over the backpack, loading all NBT data from every item in the backpack. 
It seems that selecting the backpack in this version does some strange NBT loading and as I said, causes a huge amount of lag.

**Comment by oly2o6** [comment]
this issue is not on our end, please could you get this reported to the relevant mod author

**Comment by TheBrodsky** [comment]
Sorry for necro.

I ran into this issue also, but learned a bit more than is stated here.

Here's what I know:
 1. the storage medium doesn't matter. Backpacks, shulker boxes, reinforced chests, etc. All portable inventory items produce this bug.
 2. the item with lots of NBT tags doesn't matter. Spawners, jarred bees, monster balls with entities in them, etc. All produce fps drops to different extents.
 3. the item need not contain lots of NBT tags. You can also have a lot of items with few NBT tags. The effect is generally less significant this way, but it's still consistent and noticeable.
 4. this is not related to optifine. I tested with and without it and still produced the bug.
 5. the bug only occurs in multiplayer. Testing in singleplayer will not produce an effect.
