### ISSUE TITLE
Food Eaten Keeps Resetting

### ISSUE THREAD

**Issue by zazzypops** [AllTheMods/ATM-6#493]
On my all the mods server the count for what food you've eaten resets after a while and you lose all your hearts and all the food that you've eaten now says it hasn't been eaten yet

**Comment by Xenovalis** [comment]
Not a bug, this is intended.
If you would like them not to reset, change the following line in your config (`world/serverconfig/solcarrot-server.toml`) to `false`
https://github.com/AllTheMods/ATM-6/blob/75f30d79f0bc5fab3d79a25f6025420ac7ff8ff5/defaultconfigs/solcarrot-server.toml#L25
