### ISSUE TITLE
Steel and other ressources lacks recipe from Mystical agriculture

### ISSUE THREAD

**Issue by zoratoune** [AllTheMods/ATM-6#499]
![image_268](https://user-images.githubusercontent.com/3108919/101238903-b362ba00-36e3-11eb-901f-281c9401c852.png)
The **steel essence** exist but don't have any recipes associated
The same goes for 

1. Air essence
2. Rubber esence
3. Aluminum
4. Copper
5. Platinum
6. Iridium
7. Tin
8. Bronze
9. Zinc
10. Brass
11. Silver 
12. Lead
13. Nickel
14. Constantan
15. Electrum
16. Mithril
17. Tungsten
18. Titanium
19. Uranium
20. Chrome

**Comment by zoratoune** [comment]
This is in version 1.3.3

**Comment by zoratoune** [comment]
Now I've got a recipe that disappeared after crafting it I crafted an iron seed but by trying to automate it, I seem to have made it disappear the infusion crafting of the seed start with the animation but at the end there are no items in the infusion crafter. I tried picking the infusion crafting thingy and place it somewhere else still the same thing. Then I checked the seed recipe and it pointed to the infusion crafting recipe but it was empty, then I click on the iron seed again to see the recipe but the tab with infusion crafting was nowhere to be seen.

**Comment by Flicks116** [comment]
I have the same problem

Server Error
[Server thread/WARN] [KubeJS Server/]: Error parsing recipe mysticalagriculture:essence/common/steel_ingot[mysticalagriculture:tag]: {"type":"mysticalagriculture:tag","conditions":[{"type":"mysticalagriculture:crop_enabled","crop":"mysticalagriculture:steel"}],"pattern":["EEE","E E","EEE"],"key":{"E":{"item":"mysticalagriculture:steel_essence"}},"result":{"item":"mekanism:ingot_steel","count":1}}: com.google.gson.JsonSyntaxException: Missing tag, expected to find a string

**Comment by CaptainTemerin** [comment]
same problem since updating to 1.3.3 seems the pattens have been removed (just when i needed steel lol)

**Comment by patrick96** [comment]
Seems to be fixed in 1.3.6b (may earlier versions as well).

**Comment by Ta1ha** [comment]
Air essence still seems to not have recipes on ATM6 version 1.6.10
