### ISSUE TITLE
Oregen for multiple coppers enabled

### ISSUE THREAD

**Issue by FnordMan** [AllTheMods/ATM-6#5]
Bluepower and Mekanism both have copper gen enabled. Unsure if this is intentional but have a feeling it isn't. Running 0.10a

**Comment by whatthedrunk** [comment]
This should be fixed in 0.11 with the new added Immersive Engineering ores.  If you see any duplicates in new chunks let me know!

**Comment by Cavecanem** [comment]
I haven't seen any bluepower copper, but both IE copper and Mekanism copper have their ore gen enabled for me.
