### ISSUE TITLE
Buckets disappearing

### ISSUE THREAD

**Issue by Danielek0125** [AllTheMods/ATM-6#500]
**Describe the bug**
Sometimes buckets with fluids disappear. I only encountered it when I did an action while holding the bucket e.g. open the heat generator form mekanism with a lava bucket or i took coppersight fluid into a bucket and it disappears. This is very annoying because i have to get the fluids again.

**To Reproduce**
1. Get a bucket with a fluid
2. Click on an inventory with the bucket
3. Bucket is now gone (haven't tested it enough to see if it randomly happens. You may need to do this multiple times)

**Expected behavior**
I would expect to not lose my buckets when opening inventories.

**Screenshots**
Haven't got any

**Additional context**
I am running the version 1.3.3 on a server

**Comment by ViRb3** [comment]
If you right-click any Mekanism machine with a bucket of liquid, you'll submerge the machine In that liquid, i.e. they will share the block. This is an intended Mekanism mechanic. Is this what you mean?

**Comment by Danielek0125** [comment]
No nothing submerges or gets "waterlogged" if thats what you mean. The bucket just disappears and the machine has no fluid either in or around it.
