### ISSUE TITLE
Neither End or Nether portals work after upgrading to 1.3.3 from 1.2.1

### ISSUE THREAD

**Issue by Metaz78** [AllTheMods/ATM-6#501]
**Describe the bug**
Neither End or Nether portals work after upgrading to 1.3.3 from 1.2.1
(Local multiplayer server)

**To Reproduce**
Start server, log in, try to enter nether or the end.

**Expected behavior**
Enter the dimension

**Additional context**

**Comment by ViRb3** [comment]
#437
