### ISSUE TITLE
Waiting for Server crash

### ISSUE THREAD

**Issue by catkin63** [AllTheMods/ATM-6#505]
**Describe the bug**
Walking west of my base into a region the map says is blank, I encounter a Hobbit Hole I have already looted, one Minecraft bee nest with 3 bees, one Resourceful bee and nest. I catch the bees and break the Resourceful nest. Walking further west and across a lake, I find another Resourceful nest which I break. Up to this point, no issues. I then walk around the edge of the hill into a small pond area where the game "stops" I can't continue, I can't backtrack to a useable area and it won't save if I exit. This has happened 4 times in precicely the same manner. I am not even far from the base, maybe 10 minutes leisurely walking.

**To Reproduce**
Steps to reproduce the behavior: Detailed above.

**Expected behavior**
I expect the game to continue and allow me to walk past the small area into a region beyond it that the map is showing as explored.

**Screenshots**
![4) Showing Hobbit Hole and 1st nests](https://user-images.githubusercontent.com/32679297/101286467-4bc67080-37b0-11eb-8b21-6ef691a40adb.png)
![1) At my base](https://user-images.githubusercontent.com/32679297/101286484-64368b00-37b0-11eb-898d-5d85e4054084.png)
![2) Showing Base and Unmapped](https://user-images.githubusercontent.com/32679297/101286488-6993d580-37b0-11eb-8bb6-5de9a4a80e63.png)
![3) Showing full unmapped section](https://user-images.githubusercontent.com/32679297/101286497-73b5d400-37b0-11eb-8a08-eeb4fa14bbba.png)
![5) Showing 2nd nest area](https://user-images.githubusercontent.com/32679297/101286519-8f20df00-37b0-11eb-80f5-2e3252946737.png)
![6) Showing lock-up lake](https://user-images.githubusercontent.com/32679297/101286522-9647ed00-37b0-11eb-8b60-b9f66e7974ee.png)
![7) Looking back after lock-up at previous pov](https://user-images.githubusercontent.com/32679297/101286530-a233af00-37b0-11eb-980c-610569145834.png)
![Capture](https://user-images.githubusercontent.com/32679297/101286570-ce4f3000-37b0-11eb-8cee-c1c3e28be2eb.PNG)

**Additional context**
This is not a server, but a single-player game. These are the first bees I have captured and the first nests I have collected. While collecting these screenshots, I broke no nests and only captured the 3 Minecraft bees and collected the honeycombs from that nest.

**Comment by Pdiddy973** [comment]
if you still need help feel free to ask in our [discord](https://discord.gg/K5FBPYa)
