### ISSUE TITLE
Cannot create Terrasteel

### ISSUE THREAD

**Issue by jeremyramsey** [AllTheMods/ATM-6#506]
Creating Terrasteel requires the Mana Infuser which requires Elementium which requires Elven Trading which requires Terrasteel to create the Elven Core.

**Comment by DeathOfTime** [comment]
should be able to use a agglomeration plate. might be worth looking in the lexica botania for the specifics

**Comment by jeremyramsey** [comment]
That worked, thanks! I guess it just doesn't show in JEI.
