### ISSUE TITLE
Infinite Xp Bug

### ISSUE THREAD

**Issue by Shadowdragon019** [AllTheMods/ATM-6#507]
I'm not the best at talking in text so I decided to make a video of me talking instead, I hope this is alright.
https://www.youtube.com/watch?v=THaWOcZGGRs&feature=youtu.be

**Comment by DeathOfTime** [comment]
duplicate of #431 . though i did like the video

**Comment by Shadowdragon019** [comment]
Oh sorry I didn't look at that. Also thank you :D
