### ISSUE TITLE
Rats Replanter Upgrade Doesn't Work With Pam's Harvestcraft Crops

### ISSUE THREAD

**Issue by DatMudflap** [AllTheMods/ATM-6#510]
See Title

**To Reproduce**
1. Planter upgrade on a rat 
2. Set to harvest
3. ??????
4. Profit (Works with vanilla crops, anything else it doesn't.)

**Expected behavior**
For it to work like vanilla crops lol

**Comment by oly2o6** [comment]
i recommend reporting this to https://github.com/Alex-the-666/Rats/issues as there is minimal changes we can do on our end to add this.
