### ISSUE TITLE
Ice and fire mobs not spawning

### ISSUE THREAD

**Issue by AiJermain** [AllTheMods/ATM-6#519]
So we have now went through all dimension and have yet to find any of the mobs related to this mod. We are using the default config delivered by the server files so they should work fine. Is there any way I can fix this cuz my friends are getting pissed at me for "breaking" the mod

**Comment by AiJermain** [comment]
https://hastebin.com/paxejafewu.ini

**Comment by ViRb3** [comment]
#483
