### ISSUE TITLE
RFTools Storage voids all items

### ISSUE THREAD

**Issue by Doern** [AllTheMods/ATM-6#521]
**All items get voided**
If you have e.g. 100 stacks of items stored in the modular storage and press the 'AZ'-button that's located to the right of your inventory all items get pulled into your inventory. Because there isn't that much space (of course) all excess items get voided.

**To Reproduce**
1. Store e.g. 30 stacks of items in the modular storage (module tier 3)
2. Click on 'AZ' to the right of your inventory
3. All excess items are being voided

**Expected behavior**
Only as much stacks as inventory slots available should be pulled down.

**Comment by ViRb3** [comment]
#327
