### ISSUE TITLE
ATM 6 Object Reference Not Set To An Instance Of An Object.

### ISSUE THREAD

**Issue by BluePoisonFlames** [AllTheMods/ATM-6#527]
It doesn't let me Download All The Mods 6 it keeps saying  Object Reference Not Set To An Instance Of An Object.

**Comment by ViRb3** [comment]
What doesn't let you? How are you downloading? Please refer to #384.

**Comment by BluePoisonFlames** [comment]
im downloading it thru curse forge everytime i click install it pops up saying Object Reference Not Set To An Intsance Of An Object.
