### ISSUE TITLE
Environmental Tech assembler

### ISSUE THREAD

**Issue by keith1221** [AllTheMods/ATM-6#528]
does Environmental Tech still use assembler as i cant seem to find it in creative menu or in to many items I have even tried crafting it and it does not seem to be their if it does not use assembler what do I use?

**Comment by lucasvanhalst** [comment]
You craft the miner itself, then shift-rightclick on it, it will build it by itself (be sure you have the necessary items in your inventory). 
As to how much of each item you need, I don't know either. Except for the new version of the mod (which isn't in this modpack yet), this video is the only documentation I can find https://www.youtube.com/watch?v=GB7CvGQ7I40

**Comment by Nonsanity** [comment]
Hold shift when hovering over the core block of a machine to get a list of parts.
