### ISSUE TITLE
Potions Master OreSight Potions and Charms not showing ores.

### ISSUE THREAD

**Issue by DoomieWoomie** [AllTheMods/ATM-6#529]
With the latest update of Potions Master, it intended to fix the overlays not showing on certain mods. But after that update I can't see any ores showing up anymore. Tested with both potions and charms.

https://i.imgur.com/psK96QC.png

**Comment by xstarlin** [comment]
I too have noticed this issue

**Comment by thevortex** [comment]
oof my bad :) resolved with https://www.curseforge.com/minecraft/mc-mods/potionsmaster/files/3135244 version 0.1.28 has a fix for you can you please verify with a second set of eyes that its working again? :)

**Comment by DoomieWoomie** [comment]
It is working again but now its rendering other visuals very far away after using the OreSight effect. Example with Apiary of Resourceful Bees.
**https://i.imgur.com/QDck9NK.png**

**Comment by thevortex** [comment]
you are certain its fixed? lol you got me spooked now haha are you on version 0.1.28 of potionsmaster

**Comment by DoomieWoomie** [comment]
It is fixed! I tried with different ores and dimensions :)!  Other visuals are still not showing when the effect is active but it doesn't cause too much trouble so thanks for the update!
