### ISSUE TITLE
RFTools Builder mine AllTheOres

### ISSUE THREAD

**Issue by xstarlin** [AllTheMods/ATM-6#530]
Can the RFTools builder mine allthemodium ore when it is placed over an ocean?

**Comment by DeathOfTime** [comment]
it can't mine any ATM ore. everway to automine that stuff has been disabled. it is possible to use the quarry to clear out everything else to make the ore easier to see though. that is how i tend to find it in the mining dimension

**Comment by xstarlin** [comment]
I didn't even realize there was a mining dimension??? How do you get there

**Comment by xstarlin** [comment]
> it can't mine any ATM ore. every way to auto mine that stuff has been disabled. it is possible to use the quarry to clear out everything else to make the ore easier to see though. that is how i tend to find it in the mining dimension

I didn't even realize there was a mining dimension??? How do you get there

**Comment by NetMasterFlex** [comment]
You need to craft a teleport pad which requires 8 allthemodium nuggets and an Ender Pearl in the middle.  Once crafted, you place the pad on the ground or on a block and click the use button to teleport there.  You have to have both hands free and no shield in the box.  The easiest way to acquire allthemodium is by trading with the non-zombied piglins.  Offer them gold for a chance for them to drop either ingots or nuggets.  Hope this helps.  If not, for more help join the ATM channel on Discord, join the ATM6-Help or ATM6-General chat to get answers to your questions.

NMF

**Comment by bayerw** [comment]
To be honest I'm a bit upset about myself as I seem to be unable to find any config to re-enable the RFTools Builder to mine AllTheOres Blocks and AllTheModium Blocks.
I'd really like to know how to enable the RFTools Builder to harvest any block in the game. What is the Point in automating things with AE2 and Mekkanism if I have to mine those blocks by hand? From my point of view this is only time sink tactics to artificially slow down the progress.
Please let me know how to enable this again.

**Comment by jeremiahwinsley** [comment]
> To be honest I'm a bit upset about myself as I seem to be unable to find any config to re-enable the RFTools Builder to mine AllTheOres Blocks and AllTheModium Blocks.
> I'd really like to know how to enable the RFTools Builder to harvest any block in the game. What is the Point in automating things with AE2 and Mekkanism if I have to mine those blocks by hand? From my point of view this is only time sink tactics to artificially slow down the progress.
> Please let me know how to enable this again.

There is no way to enable it. There are several ways to automate it that do not require mining it, which you can find in JEI.

**Comment by bayerw** [comment]
> > To be honest I'm a bit upset about myself as I seem to be unable to find any config to re-enable the RFTools Builder to mine AllTheOres Blocks and AllTheModium Blocks.
> > I'd really like to know how to enable the RFTools Builder to harvest any block in the game. What is the Point in automating things with AE2 and Mekkanism if I have to mine those blocks by hand? From my point of view this is only time sink tactics to artificially slow down the progress.
> > Please let me know how to enable this again.
> 
> There is no way to enable it. There are several ways to automate it that do not require mining it, which you can find in JEI.
 Wow. Next time answer with http://letmegooglethat.com/
It's as helpful. I know that there are other mods like Mystical Agriculture which I highly dislike and leave it out as much as possible.
At least it should be up to the player / server admin to dis or enable it but whatever. Decisions have been made. Guess it's time to move on and find another pack then. Feels bad.
