### ISSUE TITLE
Illegal Packet recieved

### ISSUE THREAD

**Issue by foxdarts** [AllTheMods/ATM-6#532]
on joining a local server i get illegal packet received connection terminated.  never happened before but randomly started upon setting up the 4 times ore processing with mekanism.

**Comment by foxdarts** [comment]
upon investigation the kick happens when it becomes dark enough for the thermal evaporation tower to start cooling down. @mekanism

**Comment by whatthedrunk** [comment]
guessing this has been fixed. If its still around get me a log to look at.
