### ISSUE TITLE
Shaders Day & Night cycle broken.

### ISSUE THREAD

**Issue by Grootloops33** [AllTheMods/ATM-6#534]
Hello,
When using Shaders (Sildurs vibrant) The day/night cycle is broken.
I've disabled weakSkyRenders in the Astral Sorcery config.

`weakSkyRenders = ["minecraft:overworld"]`
However the problem persists. What other mods can be causing this issue to occur?

**Comment by DeathOfTime** [comment]
not really the place to ask. shaders aren't supported

i did notice that the vanilla minecraft clock also had issues. it would go at several times the speed the day was going at. for instance four cycles for each half the day. so not sure shaders is the only thing impacted
