### ISSUE TITLE
Copper Ore

### ISSUE THREAD

**Issue by BlackWolf101** [AllTheMods/ATM-6#535]
Hi everyone. Does anyone know how to get copper?

I see that All the Ores adds two copper ore variants, but I haven't found any while mining and it doesn't show up in Just Enough Resources.

**Comment by xstarlin** [comment]
I had no problem finding copper, might be a world generation bug or something else but copper is very prevalent

**Comment by BlackWolf101** [comment]
Does anyone know how to add the copper ore gen to JER? /profile doesn't show up as a valid command, and there is no JER config...
