### ISSUE TITLE
Industrial Forgoing Book Text

### ISSUE THREAD

**Issue by xstarlin** [AllTheMods/ATM-6#536]
![IF Book](https://user-images.githubusercontent.com/75756734/101870425-939e1c80-3b4f-11eb-9ee7-5b15891e3da9.PNG)
Text runs off the page

**Comment by Pdiddy973** [comment]
fixed in 1.4.0 https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues/942
