### ISSUE TITLE
PneumaticCraft: Repressurized drone are not able to interact with owner's claimed chucks 

### ISSUE THREAD

**Issue by TheNeurotox** [AllTheMods/ATM-6#537]
Drone can't dig or plant sapling(right clicking) in a claimed chunks (own by the same user who created and programmed the drone). 

**To Reproduce**
1. Claim chuck
2. Program a drone to dig the area or to plant sapling (right click)

**Expected behavior**
The drone should be able to interact with the owner's chuck

**Additional context**
-Drone can cut tree in a clamed chunks
-When drone is program to dig, it will just stay at the first block
-When drone is program to right-click, it will right click but nothing will append (except a dirt animation)
-Tested on 1.3.2c, I don't have access to a 1.3.3 server right now.

**Comment by Nonsanity** [comment]
If the Drone is like other user-style blocks (breakers, miners, etc) then you need to add it's user to your team so it can modify claimed chunks. Or use it in chunks that aren't claimed.
