### ISSUE TITLE
Server crash when using Rats for Mining

### ISSUE THREAD

**Issue by jblankenship30** [AllTheMods/ATM-6#539]
**Describe the bug**
Mining with Rats causes the server to crash

**Server Details**
Server version 1.3.3

**Crash Report**
[crash-2020-12-11_10.04.50-server.txt](https://github.com/AllTheMods/ATM-6/files/5680669/crash-2020-12-11_10.04.50-server.txt)

**Comment by ZachariBarnes** [comment]
Having the same issue
