### ISSUE TITLE
Lags 

### ISSUE THREAD

**Issue by BlackHoleTON618** [AllTheMods/ATM-6#540]
I am having intense lag on atm6

**Comment by pappawolfie** [comment]
same here previous versions i never had any issues this version seems to eat up cpu real quick memory usage seems ok but it runs cpu really high.

**Comment by DeathOfTime** [comment]
not certain it is related but read of similar with others and using java arguments helping. might be worth trying  https://discord.com/channels/254530689225981953/718184881628381284/784616335119482942 or https://discord.com/channels/254530689225981953/467557554113740803/642173283613016084

**Comment by ViRb3** [comment]
Please try #425.
