### ISSUE TITLE
Not entering nether

### ISSUE THREAD

**Issue by BlackHoleTON618** [AllTheMods/ATM-6#542]
i cant enter the nether i build portal activated but i waited for 2 mins still not transfering me to nether anyone knows how to solve this ?

**Comment by NexusNovaz** [comment]
#437

**Comment by BlackHoleTON618** [comment]
> #437

i tried the thing i am in singleplayer but still not working

**Comment by thevortex** [comment]
type /forge dimensions and take a screenshot of what you see, post to imgur.com or another image sharing site and leave us the link
