### ISSUE TITLE
Server crashing in certain biomes

### ISSUE THREAD

**Issue by friedensstifter84** [AllTheMods/ATM-6#543]
Hi ATM-6 Team, 

the mod is great work! But we have a big problem playing with this mod:
If one Player is exploring the map the server is crashing. This is reproducible. Not everywhere, but in certain biomes (one of this biomes is Seasonel Forest).
After the Server restarted we can teleport the player back to the base and everything is fine and we can play. If the player stays in the biome and is walking around, the server crashes again. If the player teleports back to the crashing position, the server crashes again. 
This makes it nearly impossible to play and explore the world. Is this a known issue? Do you need any files to see what is happening? The Server console only says that it restarts. If we set max-tick-time = -1 then the server don't crash but we can't connect any more.

Version: ATM6
Date: Nov. 27

Thanks for your help
friedensstifter84

**Comment by Harkole** [comment]
I'm seeing this too, crash logs show that the server tick took longer than 60 seconds before shutting down. Had it both in the Overworld and Nether, although I can't say it's related to key biomes

Both of these crashes are from trying to explorer the Nether

https://pastebin.com/N0psbkay
https://pastebin.com/AgCvkYnB

**Comment by whatthedrunk** [comment]
This was fixed a while back but if it came back let me know.
