### ISSUE TITLE
Quartz Enriched Iron Seeds Not Crafting  [Version 1.3.3]

### ISSUE THREAD

**Issue by Bubble0seven** [AllTheMods/ATM-6#546]
**Describe the bug**
When crafting the Quartz Enriched Iron Seeds in the Infusion crafter the craft animation occurs but does not give the seed after it.

**To Reproduce**
1. Place ingredients in infusion altar
2. Start the infusion 
3. No seed given after animation of crafting

**Expected behavior**
A Quartz Enriched Iron Seed is supposed to be left on the alter for you to collect

**Comment by whatthedrunk** [comment]
Is this still a issue for you in 1.5.0 we had a lot of seed fixes a while back.
