### ISSUE TITLE
ICE and Fire mod not working

### ISSUE THREAD

**Issue by dalduros** [AllTheMods/ATM-6#547]
I'm running all the mods 6 on a server hosted by Bisect, who have troubleshooting what they can on their end by re-installing the files for Fire and Ice, single and multiplayer is having the same issue where no creatures, structures, nests or anything from Ice and Fire generates. I restarted, re-installed, reset the over world, nether and 'Other', I travelled 3k blocks from 0,0 and still no creatures
I can manually spawn them in with their spawn eggs but that's it.

I noticed in the recent change log there's a reference to a config to whitelist dimensions but I can't locate how to access this configuration panel..what have I done wrong?

I have also logged a ticket with the IAF team on https://github.com/Alex-the-666/Ice_and_Fire/issues/3286

**Comment by thevortex** [comment]
there is a known issue with I&F mobs, they have not been working since the end of October, next update should have most functionality restored.
