### ISSUE TITLE
Thermal Hive Hopper w/ Resourceful Bees

### ISSUE THREAD

**Issue by MrTaco9001** [AllTheMods/ATM-6#548]
**Describe the bug**
The Hive Hopper from Thermal creates honeycombs and honey from thin air when interacting with Resourceful Bees hives. The combs are vanilla regardless of the expected combs. This also allows the Resourceful Bees hives to fill up with combs past their max limit.

**To Reproduce**
1. Place a Resourceful Bees hive of any kind
2. Place a hive hopper from Thermal below the hive
3. Wait for bees to fill the honey level of the hive to 5
4. The hopper will continue to create combs and honey while the hive stocks up on actual combs

**Expected behavior**
Hive hopper collects the correct combs from Resourceful Bees hives.

**Screenshots**
![image](https://user-images.githubusercontent.com/22112182/102004528-86179c80-3cdf-11eb-82cc-0f108122cd9c.png)
![image](https://user-images.githubusercontent.com/22112182/102004530-8c0d7d80-3cdf-11eb-926f-cf155327654d.png)

**Note/Additional Bug**
Attempting to collect honey from the hive hopper will void both the honey and the bucket. I recommend disabling the hive hopper until Thermal properly implements its features.

**Comment by DeathOfTime** [comment]
this sounds similar to another issue. not the same just similar. https://github.com/AllTheMods/ATM-6/issues/251
