### ISSUE TITLE
ATM 6 won't load

### ISSUE THREAD

**Issue by Thanoid1** [AllTheMods/ATM-6#551]
**Describe the bug**
I downloaded Atm 6 around 2-3 months ago. I have a world that I made a backup with. When I tried to open atm6, it won't open. I checked in task manager, there was no javaw task in details that was running. I deleted atm6, redownloaded it, and the same problem happened again. Pretty sure that Curseforge is to blame but I don't know what else to do.
**To Reproduce**
1. Download All the mods 6 on curseforge
2. Click play
3. See that nothing loads at all.

**Expected behavior**
I expected it to load fine
**Screenshots**
N/A
**Additional context**
I think Curseforge is to blame.

**Comment by ViRb3** [comment]
Please use MultiMC. #384
