### ISSUE TITLE
Infinite Enchant Levels

### ISSUE THREAD

**Issue by MrTaco9001** [AllTheMods/ATM-6#554]
**Describe the bug**
Using infusers from Elementalcraft and enchantment extractors you can raise the level of various enchants infinitely.

**To Reproduce**
1. Infuse an item with desired element
2. Move the resulting enchant onto a book
3. Infuse the item with a different element
4. Apply the book to the item
5. Infuse the item with the same original element

**Screenshots**
![image](https://user-images.githubusercontent.com/22112182/102025030-5a3dfa80-3d63-11eb-8dd1-a821d860f9ed.png)
![image](https://user-images.githubusercontent.com/22112182/102025036-6033db80-3d63-11eb-9f4c-6c2dd10567e8.png)
![image](https://user-images.githubusercontent.com/22112182/102025041-64f88f80-3d63-11eb-8382-b229c43626f0.png)

**Comment by ariosos** [comment]
This works with anvils, too - kinda. In my pre 1.3.6 world, I could keep combining enchantments in the anvil, but with 1.3.6, I can only enchant 1 level higher than normal (i.e., Fortune III to Fortune IV, and that's it - tried it in survival and creative). Granted, it didn't work the first time I tried it in a test world, then old pre 1.3.6 world, but worked after I shut down and reloaded the modpack (I have to do this if I've opened up 2 saves just to free up memory).
