### ISSUE TITLE
Players don't lose their Levels when there die

### ISSUE THREAD

**Issue by RealPwned** [AllTheMods/ATM-6#556]
Hi,
Players don't lose their Levels when there die, is there a solution for this issue?

ty

**Comment by kythorn** [comment]
But they do. Did you turn the "keepInventory" rule on? That has the side effect of preserving levels as well.

**Comment by RealPwned** [comment]
I haven't changed anything. Everything is set up by the installationprozess.

**Comment by RealPwned** [comment]
All Default Settings..

**Comment by RealPwned** [comment]
gamerule keepInventory is false
![image](https://user-images.githubusercontent.com/44307473/102088705-9339a600-3e1b-11eb-82f2-8365bf796036.png)

**Comment by RealPwned** [comment]
same thing in singleplayer.... i dont lose my levels when i die

![image](https://user-images.githubusercontent.com/44307473/102099190-545e1d00-3e28-11eb-938f-2cc52bf47368.png)

**Comment by RealPwned** [comment]
latest version btw.
on older ATM versions it works fine
