### ISSUE TITLE
Mekinism Crusher Makes Wrong Certus Dust

### ISSUE THREAD

**Issue by Pdiddy973** [AllTheMods/ATM-6#562]
the Mekinism Crusher makes the wrong type of Certus dust after updating form 1.3.3 to 1.3.4, should be making the Applied Energistics version, the JAOPCA version essentially has no use
![image](https://user-images.githubusercontent.com/68764896/102148535-a445df80-3e3a-11eb-83d8-27d69c507e5b.png)

**Comment by Pdiddy973** [comment]
also, JEI does show the correct recipe for using the mekinism crusher to make the correct dust

**Comment by NetMasterFlex** [comment]
Can the dust be converted to AE2 type by placing it in a crafting table?  Kind of like how you would convert a Quark Chest to a Minecraft chest?  Just curious. Not saying that your complaint isn’t valid.

**Comment by Pdiddy973** [comment]
no, the only recipe the JAOPCA dust has is to combine into the ore or enrich into a crystal

**Comment by NetMasterFlex** [comment]
Ok then this would be considered a bug that needs to be corrected in the next minor or major update.

**Comment by Pdiddy973** [comment]
Seems to be resolved after updating to 1.3.4b
