### ISSUE TITLE
1.3.4.c crashed when i try to use textures pureBDcraft 64 or 128 

### ISSUE THREAD

**Issue by gbusrt** [AllTheMods/ATM-6#566]
any one else got this issue

my install was new so clean

**Comment by gbusrt** [comment]
what other texture pack do people recommend ?

**Comment by gbusrt** [comment]
humm faithfull 1.16.4 causes a crash to

**Comment by NetMasterFlex** [comment]
Try this... as suggested by DeathOfTime.  Load the game to menu.  Go to Options > Resource Packs.  Move your Resource pack from the left side to the right, then click DONE.  Your game menu will be unresponsive for a minute or two.  As soon as you see the Mojang screen again with yellow progress bar, click the X in the upper left corner to force quit.  Now relaunch the game.  Hopefully your texturepack is applied as was mine when I used this method.  The Resource Pack I use is: Soartex_Fanver_Universal_1.16.x_2020_11_27.zip  Downloaded from curseforge, made for Modded MC version 1.16.4.  Good luck.

NMF

**Comment by gbusrt** [comment]
ooooo that works
thanks guys for the help :)
got optifine loaded but was playing the world so world was loaded, think i loaded world then remembered optifine so just as you said it was done

**Comment by NetMasterFlex** [comment]
If resolved please close your request.

**Comment by gbusrt** [comment]
well upgraded to 1.3.5 and its still happening 
work around works
closing as requested though the problem is still there
