### ISSUE TITLE
Server Files Crashing

### ISSUE THREAD

**Issue by Miyuukia1985** [AllTheMods/ATM-6#568]
The Server Files for 1.3.4c are crashing after i start my server the crash report https://pastebin.com/73pNUeV7 is telling me something from enviormental tech isnt reqistered how would i fix this.

**Comment by purestone9** [comment]
Ive come across this issue as well, from what i can tell the issue is actually caused by Psi, but they havnt posted the fix for it yet

**Comment by Miyuukia1985** [comment]
Ok thank you I got it handled and up after hours of fiddling with it
