### ISSUE TITLE
Any recipe additions/removal using KubeJS breaks all AE2 patterns that use KubeJS tagged recipes.

### ISSUE THREAD

**Issue by SlyScroll** [AllTheMods/ATM-6#569]
As the name suggests, whenever a new recipe is added or removed that has/had the KubeJS tag, all the other ME craft patterns become invalid and have to be replaced.

To reproduce the issue you simply have to put a 'craft' pattern into an ME system and then update the pack to a new version that has any recipe changes. (Such as yesterday when going from 1.3.3x to 1.3.4x)

It might not seem like much but when you have a few hundred patterns and out of those you have to go through and manually replace a hundred of them each and everytime the pack updates, include any new additions/removal of KubeJS tagged recipes, it can get very tedious. The server admin sometimes also goes in and will add a missing recipe or two sometimes and that will also break ALL the patterns with the KubeJS tag.

**Comment by Letoric** [comment]
You always have the option not to update until you've finished your current playthrough. This is not something we can/will change, recipes are going to be added, changed, removed as deemed appropriate for any given release. I know it sucks, but it is a part of modded MC life when you're playing a pack and updating.

**Comment by SlyScroll** [comment]
Im confused @Letoric ... So what your saying is that because KubeJS is screwing up the recipes because it changes their 'assignment' or whatever, affecting alot of the recipes any normal person would put in an AE2 autocrafting system, I along with any other person who plays the pack and uses AE2 because of personal preference or whatever has to suffer and be left behind?

If the reason that nothing can be done about it is because the way it's coded means the recipes can't be 'locked down' so to speak, then ignore the rest of what i've writtern but if it is because 'Oh we could maybe fix this issue but it's too much work', then feel free to keep reading.

I like the pack, I really do but your reasoning to me says: 'Thank you for telling us but not really. Even if we did know about it beforehand we arn't going to do anything about it and anyone who uses a mod WE put in the pack can be forced to no enjoy our pack by not updating AT ALL.' Even if that wasn't what you meant it is exactly what it comes across as. 

The pack is updated to add new content and fix bugs and anything like recipe issues, yes? So anyone who has this issue on their ATM6 server like the server I play on is forced to either keep dealing with this bug OR not update and face the fact that they won't get to enjoy the new content being added.

**Comment by Letoric** [comment]
It is an unfortunate effect, it's just not one we can work around other
than to not as or remove recipes which obviously isn't viable for a pack
that had to update, remove and change things as issues are discovered or
features are changed. I use RS and dealt with it too, and I make patterns
for things even if I'm only crafting once in case I need it again.
