### ISSUE TITLE
I cant launch ATM-6 V.1.3.4C

### ISSUE THREAD

**Issue by Vooxxel** [AllTheMods/ATM-6#572]
During Launch up, the game loads correctly until it says freezing data. After a few seconds the minecraft logo dissapears, and the game chrashes. 

I just launch the game via curseforge on overwolf and this happens. I tried to see if any others had the same problem but i atleast couldnt find any.

Before updating the game, it always started as normal, but now i cant launch in to the game.

I have no screenshots (Sorry)

 The error message is:
The game crashed whilst rendering overlay
Error: java.lang.NoSuchMethodError: com.valkyrieofnight.vlib.core.util.tooltip.QuickTooltips.shiftForInfoTooltip()Lnet/minecraft/util/text/IFormattableTextComponent;
Exit Code: -1

NB! I am running the game with 10GB of memory.

**Comment by Pdiddy973** [comment]
curse forge has issues, try using multi MC or GD launcher

**Comment by Jdman6** [comment]
I am using the native launcher and I am having the same error. The pack has never loaded on curse for me but it did on the native launcher until I updated the pack today.

**Comment by ViRb3** [comment]
#384
