### ISSUE TITLE
Sleeping don't pass the night

### ISSUE THREAD

**Issue by FrostZFish** [AllTheMods/ATM-6#573]
**Describe the bug**
A clear and concise description of what the bug is. sleep don't pass the night

**To Reproduce**
1. Go to '...' go to bed at night in 1.3.4c version
4. See error wake up still at night

**Expected behavior**
A clear and concise description of what you expected to happen. passed the night

**Screenshots**

**Additional context**

**Comment by Nonsanity** [comment]
Are you sleeping in a hammock? Those have the opposite effect (sleep the day away, wake up late evening.)

**Comment by Allalous** [comment]
The server I help run is having this issue with a few players. They click on their beds and lay down, but the night does not pass and someone else has to sleep. Chat even sometimes says 0/1 players asleep when it's just them on the server sleeping. Restarting the server doesn't help, relogging used to help that not too has stopped
