### ISSUE TITLE
[Cyclic] Harvester not rendering preview outline

### ISSUE THREAD

**Issue by DoomieWoomie** [AllTheMods/ATM-6#574]
**Describe the bug**
The harvester isn't showing any preview when clicking on the render button. The other machines however do work as intended.

**To Reproduce**
1. Place Harverster
2. Click on "Preview"
3. Nothing happends or shows up

**Expected behavior**
You are supposed to see a rendered outline of the range.

**Comment by thevortex** [comment]
do you have any potionmaster ore sight effects active? if you do try disabling them when you arent actively mining

**Comment by DoomieWoomie** [comment]
No, I don't have anythng active. Every other machine shows its visuals correctly, it is only the harvester that isn't showing anything. (The machines does operate but doesn't show the range with the button)

**Comment by Nonsanity** [comment]
I can confirm. This may be a Cyclic-specific issue.

**Comment by GizmoTheGreen** [comment]
Harvester preview doesn't work. however item collectors preview does work.
