### ISSUE TITLE
Game crashes on launch before main menu after updating to 1.3.4c

### ISSUE THREAD

**Issue by ceritelli** [AllTheMods/ATM-6#576]
**Describe the bug**
The game crashes on launch just before the main menu would normally be displayed after updating to 1.3.4c from 1.3.3. 

**To Reproduce**
1. Set CurseForge client version to 1.3.4c
2. Click Play from CurseForge
3. Click Play on Minecraft Launcher
4. Wait for failure before main menu would normally appear. See screen shots below

**Expected behavior**
The game launches without error

**Screenshots**
![aaaaaaaaaaaaaaaaaaaaaaaaaa](https://user-images.githubusercontent.com/22264800/102440288-98e2e780-3fe5-11eb-8c44-9d4986128395.JPG)
![aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa](https://user-images.githubusercontent.com/22264800/102440298-9bddd800-3fe5-11eb-989b-eb8193d0c9d3.JPG)
![aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa](https://user-images.githubusercontent.com/22264800/102440307-9ed8c880-3fe5-11eb-851f-46aa94c7e939.JPG)

[crash-2020-12-16_21.26.34-client.txt](https://github.com/AllTheMods/ATM-6/files/5706813/crash-2020-12-16_21.26.34-client.txt)

**Comment by Pdiddy973** [comment]
Curse forge has issues, try multi mc or GD launcher, also current version is 1.3.5

**Comment by ceritelli** [comment]
> Curse forge has issues, try multi mc or GD launcher, 

Ill look into this as a possible temporary workaround, but in the long term I would just prefer if it worked on CurseForge since its really easy to use and launch for friends. I can see that there is some issues, but that's the whole point of making a bug ticket, so here we are. 

> also current version is 1.3.5

That may be the official tips of the repository, but at the time of writing and reporting this issue, it is not officially our on curseforge or Akliz server quick install lists. So in the mean time it is the version that was selected because it is most easily accessible by the services I use.

**Comment by Pdiddy973** [comment]
It's not an issue with the pack, it's an issue with curse forge, if you use the other launcher likely they will show the latest as 1.3.5 aswell

**Comment by ViRb3** [comment]
Please try #384 as hinted above.
