### ISSUE TITLE
Impossible to craft sentient tools and arrays don't work

### ISSUE THREAD

**Issue by DirrtyBeans** [AllTheMods/ATM-6#577]
**Describe the bug**

**To Reproduce**
1. Put iron sword and gem in hellfire forge and add soul on the right to craft
2. Sword doesn't craft
3. All sentient items are missing recipes in jei
4. only the basic array to get the divination sigil works nothing else works

**Expected behavior**
A sentient sword should have crafted. The arrays should craft items too.

**Screenshots**

**Additional context**

**Comment by jhollowe** [comment]
This is a problem from KubeJS-Mods/KubeJS-Blood-Magic#1. The pack should update to v1.0.2 to fix this issue

**Comment by ViRb3** [comment]
Fixed with ATM6 1.3.7
