### ISSUE TITLE
Ender Hopper Recipe Broken

### ISSUE THREAD

**Issue by ZombGuy** [AllTheMods/ATM-6#578]
**Describe the bug**
Ender Hopper doesn't have a recipe in JEI

**To Reproduce**
1. Go to JEI and look up "Ender Hopper"
2. Click on it or press your recipe hotkey over it
3. Only shows the info of the block and no recipe

**Expected behavior**
A crafting recipe for the Ender Hopper

**Screenshots**
[Here's what I see on the latest version 1.3.5](https://gyazo.com/0619f5b3ed62a7282bf775ea7255b413)

**Comment by Pdiddy973** [comment]
looks like it was disabled on purpose because of excessive ticks, you can re enable in the kubejs/server_scripts/banned_items.js
