### ISSUE TITLE
Cyclop caves and cockatrices not respecting biomes inf config

### ISSUE THREAD

**Issue by willownezz** [AllTheMods/ATM-6#580]
**Describe the bug**

Cyclop caves and cockatrices not respecting biomes set in config to spawn

**To Reproduce**
1. Go to The Other dimension
2. Fly around there will be cockatrices everywhere and cyclops caves in the wrong biomes

**Screenshots**
![2020-12-17_00 29 05](https://user-images.githubusercontent.com/3631656/102463781-685c7700-4000-11eb-84e8-3292155a290e.png)
![2020-12-17_00 28 19](https://user-images.githubusercontent.com/3631656/102463784-698da400-4000-11eb-9e38-ebd80c7658f2.png)

**Comment by thevortex** [comment]
Ice And Fire configs dont work well for any dimension other than the overworld, we are working on workarounds, next update will have improvements
