### ISSUE TITLE
Mekanism crusher now outputs Mekanism dusts instead of AllTheOre dusts

### ISSUE THREAD

**Issue by dtupper** [AllTheMods/ATM-6#582]
As title. Previously, the Mekanism crusher outputted ATO dusts as the result of crushing an ingot. 

Now, it outputs Mekanism dusts. 

I believe this change occurred in 1.3.4.

This causes issues with RefinedStorage processing outputs, since you can't mark those as non-exact (tag match) outputs.

**Comment by dtupper** [comment]
This change appears to be reverted in 1.3.5. Closing.

**Comment by Amzd** [comment]
I updated to 1.3.5 and it still outputs Mekanism dusts
