### ISSUE TITLE
[1.3.5] Thermal Series pulverizing "Certus Quarts Crystal" leads to "JAOPCA Certus Quarts Dust"

### ISSUE THREAD

**Issue by fgoebel** [AllTheMods/ATM-6#586]
Hello, 
I tested this with a fresh install of ATM 6 1.3.5. 

This is a newer/more current Issue-duplicate of https://github.com/AllTheMods/ATM-6/issues/514, because i wanted to include the version in the heading. So please close this issue if desired  and i will add this information to the old issue!

This is something similar to this issue with certus dust and mekanism:  https://github.com/AllTheMods/ATM-6/issues/562

Using the Thermal Series Pulverizer to pulverize `AE2 Certus Quarts Crystal` to craft `AE2 Certus Quarts Seeds` this gives me `JAOPCA Certus Quarts Dust`. With this dust the `AE2 Certus Quarts Seed` is not craftable.

I think this is an issue with a missing KubeJS receipe. I had a look at the recipes already present, but I have no idea where to start creating a receipe for the Thermal Series Pulverizer to fix this. I have never used KubeJS before..

If someone is willing to pair programm this with me, maybe I am able to fix the next one.

Works with Nether Quartz:
![image](https://user-images.githubusercontent.com/3441598/102525211-3ac40c00-409a-11eb-9fe7-0db68d563100.png)

Does not work with `Certus Quartz`:
![image](https://user-images.githubusercontent.com/3441598/102525271-4fa09f80-409a-11eb-8587-082123896378.png)

**Comment by fgoebel** [comment]
Oh wow, just noticed now that there is  `Thermal Quartz Dust`, but this works for crafting the seeds:
![image](https://user-images.githubusercontent.com/3441598/102534350-e5422c00-40a6-11eb-8f1b-ad4a5fce59e7.png)

and the `JAOPCA Certus Quartz Dust` does not work:
![image](https://user-images.githubusercontent.com/3441598/102534431-07d44500-40a7-11eb-8b48-aef2f4ae7347.png)


What would be your solution in favour?

1.  change pulverizer recipe to: `AE2 - Certus Quartz dust` -> `AE2 - Certus Quartz Dust` 
2. change seed reciepe: 'JAOPCA Certus Quartz Dust' + 'Sand' -> 'AE2 Certus Quartz Seed`

I will have a look at KubeJS, if someone would like to pairprogram or something, I am quite interested to learn how this works.
(for Example, where to look up information, how to test/debug the code and so on)

**Comment by fgoebel** [comment]
saw some work on this, just wanted to link it here
- https://github.com/AllTheMods/ATM-6/pull/589
- https://github.com/AllTheMods/ATM-6/pull/590
Thank you @Letoric

**Comment by thevortex** [comment]
those recipes have been merged into the main configs, next update will take care of this
