### ISSUE TITLE
Space-Bosstools

### ISSUE THREAD

**Issue by MrScautHD** [AllTheMods/ATM-6#587]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Hey I developed a mod and found this cool modpack, maybe you could add space-bosstools?
https://www.curseforge.com/minecraft/mc-mods/space-bosstools

**Describe alternatives you've considered**

**Additional context**

**Comment by ViRb3** [comment]
Please suggest it here instead: #144
