### ISSUE TITLE
Can't install ATM6 from Twitch

### ISSUE THREAD

**Issue by BrittanyDilts** [AllTheMods/ATM-6#59]
It throws this error: 
"Cannot find file System.Linq.Enumerable+WhereSelectListIterator2[Curse.Radium.Minecraft.Models.ManifestResource,System.Int32] for addon 289310 in database. Aborting installation."

I tested a few times, and this same addon ID kept popping up, although I thought an earlier attempt which I did not record started with 2913xx. Periodically, it'll give me "Failed to get modloader" or some other error, but this is the one I've seen most often.

TIA.

**Comment by BrittanyDilts** [comment]
Earlier versions throw the same error with addon ID "231951", and the other alternate error I get is "Unable to get Addon: All the Mods 6 - ATM6 - 1.16 (381671) - File ID: 3024538"

**Comment by Florek81** [comment]
Yeah, same here. Couldn't install over Twitch or AT Launcher.
I tried it over MultiMC and it worked.

**Comment by haocorry** [comment]
Same unable to install client side through twitch. Server pack working fine.

**Comment by BrittanyDilts** [comment]
In my optimistic hopes, I periodically try again and have also gotten an "Object reference is not set to object" sort of error.

**Comment by oly2o6** [comment]
Curse have said they are working on it, until then multimc seems to be working
