### ISSUE TITLE
Mahou Tsukai - Strengthening doesn't strengthen sticks

### ISSUE THREAD

**Issue by kjchiamu** [AllTheMods/ATM-6#591]
**Describe the bug**

When casting strengthening, sticks don't show up as strengthened in my inventory. This prevents the Emrys from being created.

**To Reproduce**
1. Create a scroll of strengthening, then cast it.
2. Open inventory, and mouse over the stick, and it doesn't show as strengthened.

**Expected behavior**
Stick shows up as strengthened.

**Screenshots**
Non strengthened stick:
![image](https://user-images.githubusercontent.com/5725592/102643070-afe02180-412c-11eb-821b-18d96625972b.png)

Strengthened book:
![image](https://user-images.githubusercontent.com/5725592/102643000-93dc8000-412c-11eb-99ff-5899d2cede91.png)

**Comment by stepsword** [comment]
it'll strengthen the first thing on your hotbar. try holding the stick in your offhand instead

**Comment by kjchiamu** [comment]
Alright, yeah, that worked for strengthening the stick,

However, when being struck by the Lightning spell from Ars Nouveau, the Emrys still isn't being created.

I was struck with nothing but a backpack on.

**Comment by stepsword** [comment]
were you holding the strengthened stick in your offhand when you were struck? if so, its likely that ars nouveau isn't firing the lightning event when it strikes you

**Comment by kjchiamu** [comment]
Ah, that did it.. Book says to get struck while holding it, not holding it in the off hand.. 

Thanks for the help.
