### ISSUE TITLE
FTB Ultimine Broke

### ISSUE THREAD

**Issue by hasjdhaksdhakjdh** [AllTheMods/ATM-6#596]
I cannot change the shape in FTB Ultimine. It says to shift and scroll to do this but this doesn't work, please help.

**Comment by HalationEffect** [comment]
Not broken for me in v1.3.5
You're holding down whichever key you have bound for FTB Ultimine and also holding down shift, and then rolling your mouse wheel to change shapes, right?

**Comment by ZephyrWindSpirit** [comment]
They might have a macintosh, like I do. Ultimine has an issue filed for an enhancement to add keybinds so mac users can change shapes with ultimine, but haven't updated yet. I have the same problem, but I'm just dealing.

**Comment by desagas** [comment]
https://www.curseforge.com/minecraft/mc-mods/shift-n-scroll-on-mac/files

I made a mod for it, when install on anything forge 1.16.4..29 and above, it allows mac users to shift and scroll like ALL other PC users can. It fixes this and ALL other mods that require shift and scroll to be used together.

**Comment by desagas** [comment]
I have made a mod that fixes this entirely. Enjoy! It can be downloaded on Curse from the launcher or on the site.

https://www.curseforge.com/minecraft/mc-mods/shift-n-scroll-on-mac/files

It can be used on both servers and clients without any crashes, but only requires to be on the client side, server side does nothing at all.

**Comment by whatthedrunk** [comment]
neat fix ill suggest people give that a try
