### ISSUE TITLE
Resource Reloading Crashes Game

### ISSUE THREAD

**Issue by LimitedSalvation** [AllTheMods/ATM-6#599]
I don't really know if this is a ATM 6 side issue but I tried the resource pack reloading on a normal vanilla Minecraft launch and it worked perfectly fine. Looked through the crash file and it said something about a Loading Gui error (The loading bar overlay had some kind of failure or something that crashed the whole game). But if you have had this problem please help me with a solution.

**Comment by NetMasterFlex** [comment]
Try this and close out this issue if it works for you. 

Launch the game to the main menu. Click Options > Resource Packs. Move your resource pack from. Left to right side and click done. Wait until the screen shows Mojang loading. Click on the x in the upper left corner of the windows when the loading screen is no longer in an unresponsive state.   This will close your game.  Reload the game and your Resource Pack should be applied.  Click Options > Resource Packs to verify it worked. 

This work around has worked for me On ATM6 version 1.3.4 thru 1.3.5. 

Note: I have not tested with Optifine applied, just the RP. 

Also don’t wait too long to X out of the game. It will be unresponsive at first after clicking DONE and will freeze for a minute or two, but you should be able to close out of the game. 

NMF

**Comment by LimitedSalvation** [comment]
Oh that worked Thanks so much dude.
