### ISSUE TITLE
Crash by looking up a recipe with JEI

### ISSUE THREAD

**Issue by Drago5801** [AllTheMods/ATM-6#60]
In particular by looking up the uses of rotten flesh. 

I do not know if this happens with other recipes but I've tested it three times with rotten flesh and it still crashes.

--------------------------
ATM6 0.25a
Extract of the Log: [https://pastebin.com/GjMu9RH9](url)

**Comment by BayardoZelaya** [comment]
same here while searching on JEI I crash, I thought it had something to do with the typing in 'a' because it is also the assignment key from JEI, but changed it and it wasnt the case.

**Comment by CryptForce** [comment]
I have the same problem.
After I typed "Ga" it crashes instantly.

Log: https://pastebin.com/wVP7a63U

**Comment by Dartherez1234** [comment]
I have the exact same error as well https://paste.ee/p/8OYXo

**Comment by Dartherez1234** [comment]
So i  figured out that the glitch was due to OF and Botania, install optiforge  to fix the problem, it worked for me

**Comment by CryptForce** [comment]
> So i figured out that the glitch was due to OF and Botania, install optiforge to fix the problem, it worked for me

Worked for me too, thanks 👍

**Comment by Drago5801** [comment]
Also worked for me. Thank you very much!
