### ISSUE TITLE
Cyclic miner doesnt work

### ISSUE THREAD

**Issue by XxNWSxX** [AllTheMods/ATM-6#604]
The miner whenever is started will mine itself rather than mining the area shown no matter the size.

**To Reproduce**
1. Power the miner.
2. When the miner is activated, it mine itself.

**Expected behavior**
Turn on the miner, mine dirt sound and the block disappear .

**Comment by Nonsanity** [comment]
Is the Miner in a chunk that is claimed? If so, add the Miner to the team so that it has permission to modify blocks in that chunk.

**Comment by XxNWSxX** [comment]
Thx ill try
