### ISSUE TITLE
No recipes for Resourceful bees when on server.

### ISSUE THREAD

**Issue by Bazyliii** [AllTheMods/ATM-6#606]
Just like in title, there is no recipes for resourceful bees in JEI on my server. On single player everything is working.

I have clean install of server and pack.

**Comment by ViRb3** [comment]
Which ATM6 version is this? Are you using MultiMC (#384)? Are there any error/crash logs?

**Comment by Bazyliii** [comment]
I'm on latest version of pack. Game and server aren't crashing. Im using normal mc launcher. I'm hosting server on my PC using your simplyserver files and then we use hamachi to play together, and there is no problem here I think.

**Comment by ViRb3** [comment]
Please try using MultiMC.

**Comment by Bazyliii** [comment]
OMG, now it is working. THX a lot man <3
