### ISSUE TITLE
Lag inspection

### ISSUE THREAD

**Issue by AiJermain** [AllTheMods/ATM-6#607]
So our server is experiencing a lot of lag lately and I used to use a mod called LagGoggles to inspect for lag but since it's not 1.16 compatible, I cannot use it. Is there any way I could identify the issue on the server? I know it's something at 1 person base but we just can't find out what this could be. 

hope someone could help :)

**Comment by ViRb3** [comment]
Your best bet is to use Spark on 1.16: #425
