### ISSUE TITLE
RFTools Builder chunk loading change

### ISSUE THREAD

**Issue by SlyScroll** [AllTheMods/ATM-6#609]
Recently updated to 1.3.5 and happened to notice that a setting on the RFTools builder had been rolled out that made it so that it no longer loads the chunk it is currently mining, meaning it pauses whenever it runs into an unloaded chunk. Surely making it so players have to use alternate means to chunkload the quarry's area makes it so that more chunks are loaded overall at one time especially on a small/medium server.

On the server I play on, the admins were not aware of this change until notified and they immedietly reverted the change as it would cause people to load way more chunks overall. What was the reasoning behind this change because if the goal was to reduce peoples use of the builder as a quarry, it may be that it is having the unintended effect of causing more lag for servers because people are trying to chunkload massive areas to make sure their quarry is running.

**Comment by derrickmehaffy** [comment]
Still present in 1.3.7 as well, attempting to load chunks via FTB will result in the builder being unable to mine also. If that was the intended purpose it makes the builder useless unless your standing in a 9x9 chunk range.

**Comment by Pdiddy973** [comment]
make sure in \world\serverconfig\rftoolsbuilder.toml that the config is set correctly,
quarryChunkloads = true
and to let it mine in your chunks you need to add it to your team in the map

**Comment by derrickmehaffy** [comment]
I'm fine with swapping out the config, but I assume this change was made manually (not by the mod author) it would be nice to have changelogs in github along with curseforge to go alone with the commits so I'm digging through a ton of commits to see if some config was changed.

**Comment by SlyScroll** [comment]
The config was changed by whatthedrunk. It was done in this commit: https://github.com/AllTheMods/ATM-6/commit/bcc83aaafbd42db00a4e7de0bb695e3fa55c0936

**Comment by Pdiddy973** [comment]
It is a world config, and should only apply to world's made after that commit, if you copy world's over from previous updates it should still be true.

**Comment by SlyScroll** [comment]
Yeh but the point is that it makes the builder basically useless as a quarry which is the only thing most people use it for. I asked the question to begin with to hopefully get an answer from someone who's a part of the ATM team as to their reasoning behind the change. Cause someone who has no idea where to begin changing it might use the builder a s aquarry and find it doesnt work.

**Comment by derrickmehaffy** [comment]
I agree @SlyScroll it had good intentions to stick to one chunk loader but in the case with the builder the whole point is to not load 20 chunks to quarry, it only loads the chunk it needs to in order to mine then unloads it once it's mined out.

The request here is to enable it again by default, I've been playing ATM packs for quite a while and lately it seems like the config changes are just becoming annoying to revert every time you spin up a server.

**Comment by Pdiddy973** [comment]
Will be fixed next release, only for new world's. Old world's will need to enable in world configs
