### ISSUE TITLE
Game and server crashes when trying to export Acacia logs into an Supremium furnace from refined storage system

### ISSUE THREAD

**Issue by iedvance** [AllTheMods/ATM-6#612]
The game/server crash if you try to export Acacia logs from your refined storage system into a furnace from Mystical agriculture

**To Reproduce**
1. Make a refined storage system
2. Connect the system to an supremium furnace and put an exporter on top of the furnace
3. Filter Acacia wood on the exporter

**Comment by HalationEffect** [comment]
I've encountered what seems like the same bug when using Mekanism logistical transport pipes to feed edelwood logs into a supremium furnace. Crashed the game, crashed again when I tried to reload, had to restore from a backup.

**Comment by iedvance** [comment]
EDIT: It seems like the supremium furnace is in general bugged out, If you just place it down and manually place something in the smelting slot it crashes

**Comment by S0ckD0g** [comment]
Just adding to this bug report.
Existing world as soon as I interacted with supremium furnace the game crashed and will no longer load.
Started new world, same issue as soon as I interacted with a supremium furnace

On load minecraft crashes and is reported as "Exit Code: 0".

**Comment by Letoric** [comment]
Is this still occurring?
