### ISSUE TITLE
Mod Ice and Fire not wroking 

### ISSUE THREAD

**Issue by littlepacman** [AllTheMods/ATM-6#613]
None of the dragons for the Mod Ice and Fire are spawning for the world that i have. I started playing with this mod at 6.1.3.4.

**Comment by Opsord** [comment]
I have the same problem, in fact, anything except for the manuscritps on chest is spawning from I&F, and, have u ever encountered a waystone? i cant see any even on the villages

**Comment by thevortex** [comment]
dragons/cyclops/hydra/ghoul/thrall/lich/ghosts/ampitheres/cockatrice spawn in "the other" place an allthemodium teleport pad in the nether, sneak+right click with both hands empty and you will be transported there, a pad will be placed for you to return by on the other side. you will need to dig your way up to the surface, bring at least tier 5+ armor/tools, let me know if you find anything there

**Comment by littlepacman** [comment]
i didnt find anything there for dragons in the other world and also i did find waystones at villages.
