### ISSUE TITLE
Waystones & Dragons not spawning

### ISSUE THREAD

**Issue by Opsord** [AllTheMods/ATM-6#616]
Idk if it´s only me, but i have explored a significant ammount of map and i have not see any waystone or ice & fire creatures, like, nothing. i usually play both on other versions and they are far more common

**Comment by desagas** [comment]
you might want to state what version of the pack you are on, and what dimension you were exploring. I am on 1.3.6b, whatever the newest one is today, and in the OTHER, the only place dragons are meant to spawn, i ran into a few of them. i died, hard, but i still ran into them. And, in my first spawn, within viewing distance, there were two waystones, and in the overworld, a few less, but I have found I think 10 in my paths in about 5000 blocks.

**Comment by nov21903** [comment]
> you might want to state what version of the pack you are on, and what dimension you were exploring. I am on 1.3.6b, whatever the newest one is today, and in the OTHER, the only place dragons are meant to spawn, i ran into a few of them. i died, hard, but i still ran into them. And, in my first spawn, within viewing distance, there were two waystones, and in the overworld, a few less, but I have found I think 10 in my paths in about 5000 blocks.

Yeah I found a few in the other but why in the world do STAGE THREE dragons have 15-18K Hearts??? Not only that they straight one shot me through Vibranium armor.

**Comment by thevortex** [comment]
because stage 4-5 have between 24-32K Hearts. Recommend you upgrade to unobtainium and then enchant it or at least enchant your vibranium armor as best you can,. carry plenty of allthemodium apples/carrots (carrots if you need high saturation/food values, they also provide a regen 5 and absorption 5, apples dont fill saturation or hunger as much but you get regen X and absorption X so its definitely worth having a bunch, and you get them easily from piglins by trading)  *also, did you use a blueprint to craft that armor or the vanilla armor shape without the blueprint

**Comment by nov21903** [comment]
> because stage 4-5 have between 24-32K Hearts. Recommend you upgrade to unobtainium and then enchant it or at least enchant your vibranium armor as best you can,. carry plenty of allthemodium apples/carrots (carrots if you need high saturation/food values, they also provide a regen 5 and absorption 5, apples dont fill saturation or hunger as much but you get regen X and absorption X so its definitely worth having a bunch, and you get them easily from piglins by trading) *also, did you use a blueprint to craft that armor or the vanilla armor shape without the blueprint

It's the standard vibranium armor that you can craft, not the SGear version.

**Comment by thevortex** [comment]
if you are on current version of the mod allthemodium, 1.1.19, the three armor sets did get a buff for defense but you will still need to do enchants, dragon bites are dealing a lot of damage, breath weapons too, and those scale to the tier of dragon, so buffs buffs and more buffs, mahou tsukai and the other magic mods have ways of dishing out insane amounts of damage as well, players have reported accidentally killing dragons while digging tunnels with their spells, and if your armor is sufficiently enchanted you can take a lot of abuse, maybe not able to afk while he's chewing on you but could be close!
