### ISSUE TITLE
MalformedJsonException when I try to join a server

### ISSUE THREAD

**Issue by evon0x** [AllTheMods/ATM-6#617]
"Internal Exception: com.google.gson.JsonSyntaxException:com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenien(true) to accept malformed Json at line 1 column 1 path $"

Deleted all files and downloaded it again several times, same issue everytime

**Comment by ViRb3** [comment]
Could you send the full crash/error log? Something is trying to read malformed JSON.
