### ISSUE TITLE
1.16.4 Server joining issues

### ISSUE THREAD

**Issue by Peerius1701** [AllTheMods/ATM-6#618]
Hello,

I'm sorry for asking this question here, but I don't know where to do it otherwise.

So my girlfriend and me are playing the ATM 6 Modpack, but we removed some mods and added some others. If you know a better place to ask my question, please tell me. :)

On 1.16.3, we had no problems playing the modpack, except for a server crash sometimes because it hasn't enough RAM.

Today, we tried to update to 1.16.4 and downloaded the newest version of the modpack. We removed all mods that we didn't use on 1.16.3 except for chisels and bits and we added the mods that were missing for us.

The problem is the following: I could join the server without any problems, but my girlfriends screen freezes at the encryption stage and shortly after she gets a time-out message. We thought that maybe there are too many mods to handle for her computer, so we removed 10 or so, but the same problem occurs again.

The server is running on my computer via Hamachi. We had no comparable issues on 1.16.3.

I will attach the log files of 1.16.3 and 1.16.4 of both her and me and the server log file for the 1.16.4 server. I guess one can see in the log file of her for 1.16.4 that her game at some point just does nothing anymore.

Could you please help us to fix this problem? We would appreciate it and we thank you in advance for everything that helps.

Kind regards
[1.16.3.log](https://github.com/AllTheMods/ATM-6/files/5721405/1.16.3.log)
[1.16.4 me.log](https://github.com/AllTheMods/ATM-6/files/5721406/1.16.4.me.log)
[1.16.4.log](https://github.com/AllTheMods/ATM-6/files/5721407/1.16.4.log)
[Server Log 1.16.4.log](https://github.com/AllTheMods/ATM-6/files/5721408/Server.Log.1.16.4.log)
[1.16.3 me.log](https://github.com/AllTheMods/ATM-6/files/5721409/1.16.3.me.log)

**Comment by ViRb3** [comment]
How "shortly" is "shortly after"? By default Minecraft kicks any player if they fail to load within 30 seconds or so. RandomPatches allows you to alter this, and the config in ATM6 sets it to 10 minutes, which should be ample. However, there is currently a bug that resets  your RandomPatches config every now and then. Please check if the file `/config/RandomPatches.toml` and see if its empty. If yes, you need to fill it in like [here](https://github.com/AllTheMods/ATM-6/blob/master/config/randompatches.toml), save it, and restart the server. The config tends to reset every 2nd time you start the server, unfortunately, so you'll have to keep doing this. A fix is coming in the next RandomPatches update, which is currently being tested.

**Comment by Holyphoenix** [comment]
I am having this same issue.  Here are the values in my server, client is the same:
```
[timeouts]
	# The interval at which the server sends the KeepAlive packet.
	# Min: 1
	# Max: 2147483647
	# Default: 15
	keepAlivePacketInterval = 15
	# The read timeout in seconds.
	# This is the time it takes for a player to be disconnected after not responding to a KeepAlive packet.
	# This value is automatically rounded up to a product of keepAlivePacketInterval.
	# Min: 1
	# Max: 2147483647
	# Default: 90
	readTimeout = 90
	# The login timeout in ticks.
	# Min: 1
	# Max: 2147483647
	# Default: 1800
	loginTimeout = 12000
```

**Comment by lstrobel** [comment]
This is potentially related to https://github.com/TheRandomLabs/RandomPatches/issues/141 . RandomPatches seems to be ignoring config at the moment.

**Comment by Peerius1701** [comment]
Okay, i looked in the config and it looks basically the same as the one from Holyphoenix.
So I guess I have to try increasing the readTimeout and the loginTimeout times.
To answer your question, as you can see in the 1.16.4 log file, my girlfriend tried to join twice with a rounded 3 minute pause between the tries. I think it took 1,5-2 minutes before she got kicked by the server. I don't know if this is relevant, but her game had no response during that encryption time and there seems to be nothing happening in that time in the log file.
I will try increasing the mentioned times and tell here if it fixed the problem.

**Comment by GizmoTheGreen** [comment]
Try increase the ram in your loader. I had similar issue (stuck on encryption then time out/kicked off server) when I only had 4gb set in gdlauncher or multimc. increasing to ~5gb fixed this for me.

**Comment by Jim-Pickens** [comment]
was this resolved as i have run into the same issue. ive uninstalled minecraft and appdata, removed forge and the mod pack, port forwarded, changed to a static ip, reinstalled minecraft>forge>atm6 turned off firewall i join in hamachi and can see the server but when i go to join it i get stuck on encrypting and then timed out, my other computer connects just fine

**Comment by Kewons** [comment]
Im haing problems joining my friend that lives near me its sttuck on encrypting the time sme out but friends in other states or countries can join just fine

**Comment by CinnamonShaey** [comment]
same here, i can join, and a friend from germany but not the friend from belgium even tho he has been able to before
