### ISSUE TITLE
applied energistics 2 [ ae2 ] printed silicon recipe is broken

### ISSUE THREAD

**Issue by The-kodo** [AllTheMods/ATM-6#619]
the ae2 printed silicon recipe does not allow the use of the silicon from ae2

**Comment by fgoebel** [comment]
Just leaving my opinion or thoughts on this here...

I assume that the ae2 silicon is disabled in this modpack and the intended (?) path is via certus/nether quartz -> (smelting) -> Silicon (from refined storage) -> Use in Inscriber

In my 1.3.6b game the ae2 silicon does not even show up..

So maybe just try this way ;-)

**Comment by The-kodo** [comment]
no its not lol i literaly have like 5 stacks of the stuff :( and as it doesent have the forge:silicon tag it cant be used in any recipies

**Comment by HalationEffect** [comment]
Are you running the latest version of ATM6?

If so, there should be no recipe to make raw AE2 silicon, and the only recipe for making AE2 printed silicon uses RS silicon instead.
