### ISSUE TITLE
Server lag spiking every few seconds.

### ISSUE THREAD

**Issue by schnifi** [AllTheMods/ATM-6#621]
**Describe the bug**
The server feels unplayable and when we had the server on a paid server it just crashed because the server ticks were 60 secodns late and couldnt support a player loading chunks.

**To Reproduce**
1. Install server on a pc.
2. connect and lag

**Screenshots**
![image](https://user-images.githubusercontent.com/75147288/102727390-ab328d80-4325-11eb-8cd5-c784b0f80afc.png)

**Additional context**
We tried everything and we have no clue why this is happening.

**Comment by ViRb3** [comment]
Please try #425 and report back here.

**Comment by schnifi** [comment]
I tried to recreate the lagging issue with spark installed and it didn't lag the spikes were completely gone i have no clue what caused it. I even generated a new server and started it without spark just to try and see if it would lag again and it didn't.

**Comment by ViRb3** [comment]
Maybe ATM6 update fixed it. Feel free to reply here if you manage to reproduce it.
