### ISSUE TITLE
Elemental craft with Mekanisum Ore duplicasion 

### ISSUE THREAD

**Issue by talley05** [AllTheMods/ATM-6#622]
Is ore get 6 ores with elemental craft and mechanism intend?    
it is done by first ore doubling with elemental craft then ore tripling the doubled ore thus creating 6 ores

**Comment by MASACR99** [comment]
Sure why not, you can quintuple mekanism ores pretty easily

**Comment by Letoric** [comment]
It was intended by the mod author.
