### ISSUE TITLE
Constant freezing at random times

### ISSUE THREAD

**Issue by nov21903** [AllTheMods/ATM-6#626]
**Describe the bug**
At completely random times the game will just repeatedly freeze for anywhere in between 2 and 5 seconds then will randomly go away for maybe 10 minutes only to come back again. The freezes when they start are in about a 5-10 second interval from each other. Friend has also confirmed it has happened with them as well.

**Comment by ViRb3** [comment]
This is caused by your RAM becoming full and the JVM struggling to free space for more data. There are a couple of mods that cause memory leaks which slowly fill up your whole RAM. Restarting the game is the only solution.
