### ISSUE TITLE
[1.3.6b] Crash on respawn

### ISSUE THREAD

**Issue by PrinceFluffyBoi** [AllTheMods/ATM-6#627]
The game crashes on every death, but the world files don't get damaged and I can join the world after the crash.
Edit: The game actually crashes on respawn.
[crash-2020-12-20_21.32.18-client.txt](https://github.com/AllTheMods/ATM-6/files/5723987/crash-2020-12-20_21.32.18-client.txt)

**Comment by Sooperfish** [comment]
[Latest update of Potions Master](https://www.curseforge.com/minecraft/mc-mods/potionsmaster/files/3144843) fixed this.
