### ISSUE TITLE
Smelting Iron in supremium furnace crashes game

### ISSUE THREAD

**Issue by kaweepatinn1** [AllTheMods/ATM-6#628]
Did some research and it turns out the polymorph version (0.19) used in 1.3.6b has an issue with smelting iron. Please help by updating polymorph to 0.20 :)

**Comment by ViRb3** [comment]
Is this issue fixed in 0.20? The mod will be updated in next ATM6 release.

**Comment by kaweepatinn1** [comment]
I’d assume so. The change log for the mod states that 0.20 is a fix for the error, and after updating the mod, it seems to work fine.

**Comment by ViRb3** [comment]
Awesome, should be fixed in next ATM6 release then.

**Comment by ViRb3** [comment]
Fixed in ATM6 1.3.7
