### ISSUE TITLE
[0.25a] Random crashes.

### ISSUE THREAD

**Issue by Blackcatz1911** [AllTheMods/ATM-6#63]
I have no idea, what is causing these crashes. Does somebody has any ideas?

https://pastebin.com/ivf21wjG
https://pastebin.com/yfNcxnCq

**Comment by Blackcatz1911** [comment]
https://github.com/Vazkii/Botania/issues/3397

**Comment by coffeeordeath** [comment]
i was having this issue as well https://github.com/Vazkii/Quark/issues/2412

**Comment by whatthedrunk** [comment]
We are currently on 1.16.3 so removing older issues to make way for new ones. If you want to test it out join the discord for an early beta. New update will be on Twitch / Curseforge once Mekanism pushes their update to the site.
