### ISSUE TITLE
Optifine Opengl Error 1283 on Death in LAN World

### ISSUE THREAD

**Issue by shad0whuntr** [AllTheMods/ATM-6#632]
Whenever I die on a LAN world it gives the opengl 1283 error and then I can't see anything in my inventory or in any chest inventory.

1. Open LAN world
2. Get a few items
3. Die

I would expect to be able to see my inventory.

Sorry about bad quality.
![image](https://user-images.githubusercontent.com/76451848/102817215-5df20280-439d-11eb-94e1-4f0eb1520e09.png)

I think it might be some sort of issue with the corail tombstones mod.

**Comment by ViRb3** [comment]
Some logs please?

**Comment by TfREZkrn** [comment]
I get this same issue, and I believe it has to do with OptiFine. Unfortunately, OptiFine is the only way I am able to run the pack at a playable framerate. Just in case it's helpful, I've noticed
1. it only happens on servers (or on LAN).
2. it causes items to flicker between offset to the left side of the screen as shown in the screenshot, and their intended locations.
3. it makes certain hud elements invisible (basically everything except your hotbar) unless you have a container or your inventory open.
4. the only way to fix it is to restart the game.
I'm not sure how much help this will be, but it's annoying to restart the game every time I die.

**Comment by ViRb3** [comment]
Thanks for the follow-up. Unfortunately we do not support OptiFine, you'll find that it causes a lot of other random issues, including missing oregen. I'll leave this issue open hoping somebody will be able to assist, but I wouldn't keep my hopes up too much, unless the fix comes from OptiFine itself.
