### ISSUE TITLE
Netherite with Mystical Agriculture recipe conflict

### ISSUE THREAD

**Issue by madkingdiamond** [AllTheMods/ATM-6#633]
Can't craft Netherite ingot with Mystical agriculture because the recipe conflicts with Netherite scrap.

1. Put Netherite Essence in table in pattern of a furnace
2. Craft pops up as Netherite scrap

**Expected behavior**
Craft ingots
Ingot ![image](https://user-images.githubusercontent.com/25916817/102819126-e7570400-43a0-11eb-91ff-1ca3c9304c23.png)
Scrap ![image](https://user-images.githubusercontent.com/25916817/102819159-f8077a00-43a0-11eb-9798-26865d0a8f5a.png)

**Comment by jeremiahwinsley** [comment]
Fixed in 1.4.0.

**Comment by oliverab** [comment]
Related question but shouldn't there be a recipe for netherite scrap, perhaps using only 3 essence rather than 8. Some mods require the scrap and the only way I've found to get from ingot back to scrap is via mekanism
