### ISSUE TITLE
Diamond chest dupe glitch

### ISSUE THREAD

**Issue by Granitesoldier** [AllTheMods/ATM-6#634]
Right click armor in a diamond chest to dupe it to your character.
Running 1.3.5
![image](https://user-images.githubusercontent.com/66240902/102824364-8a078680-4391-11eb-8927-6ac2bffc6e0a.png)

**Comment by Granitesoldier** [comment]
The glitch appears to not be related to the container. Sorry and thank you.

**Comment by waybaker** [comment]
To add on to this... because I just experienced a big loss of an unobtainium chestplate with more enchants than I can remember - if you have armor on and right click a different piece of the same type of armor in a chest, it overwrites what you are wearing with a copy of what was in the chest.

**Comment by Darkelru** [comment]
Ran into this myself in the end, with a pair of iron leggings, first they replaced my god tier pants, then they replaced my mining laser with a pair of iron pants, you can do this yourself by putting a pair of armor in a chest and right clicking it.  It seems to pick whatever it wants in your inventory to replace with the copy of whatever is in the chest.  Very annoying.

**Comment by jeremiahwinsley** [comment]
This is caused by Quark's "Right Click Armor" feature, and is fixed in the latest Quark version (283). There is also a config option to disable the feature.

**Comment by jeremiahwinsley** [comment]
Fixed in pack version 1.3.9.
