### ISSUE TITLE
Stage 4 and 5 Dragon spawns in the other?

### ISSUE THREAD

**Issue by nov21903** [AllTheMods/ATM-6#635]
Does anyone know where Stage 4 and 5 dragons spawn in the other? I've only come across stage 3 dragons and they don't drop eggs so I've been trying to look for stage 4 and 5 but I can't seem to find them. I've heard they spawn underground but I don't know if they spawn in specific biomes.

Also whenever I crouch near a wild baby dragon it says "tameable" thought they couldn't be tamed?

**Comment by thevortex** [comment]
i am uncertain about the tameable info, that would be better directed to Ice and Fire devs, but the spawn locations are as follows: 
lightning dragon caves: the other : desert
lightning dragon roosts: the other : desert hills
fire dragon roosts and caves: the other : basalt deltas
ice dragon roosts & caves: the other: gravelly mountains, mountains, modified gravelly mountains, and the other(there is a biome named 'the other' as well)
