### ISSUE TITLE
Client crash when killed

### ISSUE THREAD

**Issue by avidgamer5918** [AllTheMods/ATM-6#636]
The pack version is 1.3.6b 
and it is on a multiplayer server

The issue I am having is whenever I die my game crashes to desktop
crash report: [https://pastebin.com/ABhN8Nfd](https://pastebin.com/ABhN8Nfd)

**Comment by ViRb3** [comment]
From Discord #help channel:
> if anyone is crashing after they die, please update potionsmaster to 0.1.33 and you will be back on track https://www.curseforge.com/minecraft/mc-mods/potionsmaster/files/3145514

Will be fixed in next ATM6 update.

**Comment by avidgamer5918** [comment]
Okay thank you

**Comment by ViRb3** [comment]
Fixed in ATM6 1.3.7
