### ISSUE TITLE
cyclic harvester

### ISSUE THREAD

**Issue by gigitypuff** [AllTheMods/ATM-6#638]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by gigitypuff** [comment]
get a cyclic harvester plant some crops it doesnt harvest like it did before and also doesnt show working area also

**Comment by Pdiddy973** [comment]
looks like it was possibly changed here 
https://github.com/Lothrazar/Cyclic/issues/1629

**Comment by Letoric** [comment]
Mod feature change, neither a mod issue or a pack issue.
