### ISSUE TITLE
Game Crash with search through JEI

### ISSUE THREAD

**Issue by Flumm87** [AllTheMods/ATM-6#64]
Hello, i just encountered a bug where your game crashes when you write " ex " in the jei 
 
the crash log states that he cant render a block from Botania as far as i can see it : 
-- Item being rendered --
Details:
	Item Type: corporea_index
	Registry Name: botania:corporea_index
	Item Damage: 0
	Item NBT: null
	Item Foil: false
[crash-2020-08-13_11.54.35-client.txt](https://github.com/AllTheMods/ATM-6/files/5068389/crash-2020-08-13_11.54.35-client.txt)

**Comment by Ecluid** [comment]
Same for me. Except my items rendered are 

Details:
Item Type: avatar
Registry Name: botania:avatar
Item Damage: 0
Item NBT: null
Item Foil: false
[crash-2020-08-13_07.53.25-client.txt](https://github.com/AllTheMods/ATM-6/files/5069139/crash-2020-08-13_07.53.25-client.txt)

I'm going to try load up without optifine installed to see if it fixes it.

**Comment by Ecluid** [comment]
Seems OptiFine is having some issues. It worked fine as soon as I took OptiFine off.
