### ISSUE TITLE
Unobtanium breading is not shown in JEI

### ISSUE THREAD

**Issue by Pdiddy973** [AllTheMods/ATM-6#640]
**Steps to reproduce the behavior:**
go on version 1.3.7 and look up unobtanium bee

**Expected behavior**
show how to bread the unobtanium bee

**Screenshots**
![image](https://user-images.githubusercontent.com/68764896/102851668-78060200-43ea-11eb-9edc-cbda6236e297.png)

**Additional context**
you can still bread the bee but it does not show up in JEI

**Comment by jeremiahwinsley** [comment]
Fixed in 1.3.9.

**Comment by Hermsmegerms** [comment]
this is an issue again in 1.51. There is no breeding tab for unobtanium, vibrainium, althemodium, refined obsidian, and osmium
