### ISSUE TITLE
Compact Machines Bug?

### ISSUE THREAD

**Issue by LimitedSalvation** [AllTheMods/ATM-6#641]
In the new ATM 6 1.3.7 update the Compact Machines recipes are not showing and I don't think they work at all.

**Comment by Grant-K** [comment]
This is not a bug a new mod called compact crafting is required to craft compact machines and seems as if it wasnt added tot he pack 
https://www.curseforge.com/minecraft/mc-mods/compact-crafting

**Comment by LimitedSalvation** [comment]
Ah I see
