### ISSUE TITLE
Minecraft World wont load.

### ISSUE THREAD

**Issue by Thomas12211** [AllTheMods/ATM-6#643]
Hey, If anyone could help me with this that would be great i've had problems with this minecraft world before but i just reinstalled the modpack and installed it again and it happened to work but this time I was exploring new chunks and the game crashed and now it wont load into the singleplayer world I will put the crash report into here and if anyone could help me that would be amazing! Thank you 

https://pastebin.com/yvD0mJJm

**Comment by ViRb3** [comment]
Please try #384.
