### ISSUE TITLE
Question about the installation

### ISSUE THREAD

**Issue by Clifly** [AllTheMods/ATM-6#644]
Hello,
I just downloaded the version 6-1.3.3 of All the Mods 6 in 1.16.4. I installed Forge 1.16.4. I extracted the .zip of All the Mods in the "mods" folder of .minecraft but when I launch Minecraft, Forge can't detect the mod.
Does anyone know chat I'm doing wrong ?
Thanks.

**Comment by ViRb3** [comment]
This is now how you install the modpack. Please refer to #384
