### ISSUE TITLE
Silent gear problem on new version?

### ISSUE THREAD

**Issue by Erikoloko** [AllTheMods/ATM-6#645]
Updated to new version 1.3.7. On curseforge and server. Trying to load the game shows this message:

**Failed to connect to the server**

Internal Exception: net.minecraft.util.ResourceLocationException: Non [a-z0-9_.-] character in namespace of location: EAV��G��� _EOT_ �� _DC4_ silentear:brilliant _ETB_ silentgear:simple_trait _SOH_ *{"translate":"t

![Issue](https://user-images.githubusercontent.com/74869998/102921857-66c20180-448d-11eb-84c2-d4bea23fe423.png)

**Comment by Ike-l** [comment]
Ye, I got this too and was about to open the same issue

**Comment by thevortex** [comment]
if you could provide some logs from the server, then please run the update process again

Updating your Server
1. BACKUP.
2. Run the server files.
3. Approve the EULA.
4. Turn off your server and access the files.
5. Delete the folders Mods, Configs, Scripts/kubejs, Libraries and the forge jar.
6. Upload the new generated Mods, Configs, Scripts, Libraries and the forge jar to your server.
7. Start Server.

**Comment by Erikoloko** [comment]
> if you could provide some logs from the server, then please run the update process again
> 
> Updating your Server
> 
> 1. BACKUP.
> 2. Run the server files.
> 3. Approve the EULA.
> 4. Turn off your server and access the files.
> 5. Delete the folders Mods, Configs, Scripts/kubejs, Libraries and the forge jar.
> 6. Upload the new generated Mods, Configs, Scripts, Libraries and the forge jar to your server.
> 7. Start Server.

Thanks for the reply.
I don't know what you mean by "run the server files" and I don't know of any EULA, does that pop up when I run the files?

All I've done to update the server is:

1. Backup
2. Update

**Comment by Erikoloko** [comment]
I should probably tell you I'm not the one hosting the server. So the update process is done semi-automatically.
