### ISSUE TITLE
ATM6 doesnt start

### ISSUE THREAD

**Issue by j4n3k2212** [AllTheMods/ATM-6#65]
Hello ATM Team,

i have a problem, when i try to start ATM6 on the twitch launcher, it opens the mod loading screen for a split second, then closes and this error pops up. 
![image](https://user-images.githubusercontent.com/69632297/90132083-7312b100-dd6d-11ea-8f55-ba2e6960a27f.png) 
I installed an older nvidia driver, I installed an older version of the modpack, nothing helped. The thing is every other Modpack works totaly fine, no crash, nothing. I hope u can maybe help me finding a solution for this problem.

Best regards 
Janek

**Comment by HonkingSpider** [comment]
similar issue, except it's a 30 min process that gets to the main menu, gets started on the world creation, then it shows no sign of activity past "preparing to create world" or something similar.  any ideas?

**Comment by Jens8i** [comment]
the error comes probably from twich app. Try using MultiMC, it worked perfectly, I had the same problem. just export the profile from twich and import it to MultiMC and it should work. MultiMC is more advanced than twich. but thats easy. just... dont use twich,

**Comment by WhitePhant0m** [comment]
Twitch launcher is known to have a lot of issues so the best choice would be to use another launcher like [MultiMC ](https://multimc.org/)or [GDLauncher](https://gdevs.io/). I'll close this for now but feel free to open it again if it still won't work.
