### ISSUE TITLE
Minecraft keeps exiting with exit code -1073740791

### ISSUE THREAD

**Issue by zhenil** [AllTheMods/ATM-6#652]
The game keeps exiting without crash logs and randomly. No pattern when/how it exits. Issue kept happening even in ATM5
I've tried the following:
-Updating drivers and uninstalling NVidia GeForce
-Restarting my computer
-Reinstalling the instance

Recent Log:
https://paste.ee/p/IOXHn

**Comment by ViRb3** [comment]
Please try #384.

**Comment by zhenil** [comment]
I'm already using the latest version of MultiMC and even tried the Dev version but this still happens
