### ISSUE TITLE
Environmental Tech Disassemble deletes blocks

### ISSUE THREAD

**Issue by Thund3rBolt** [AllTheMods/ATM-6#654]
When shift+right clicking the Tier 1 Solar block after the structure is already built, it will remove the blocks and attempt to rebuild the structure. It seems that when the blocks are removed, they are not added back into the player inventory and upon the rebuild attempt, nothing happens. Not sure if I am missing something or not.

**Comment by murdick** [comment]
ValkyrieofNight/EnvironmentalTech#229 there is a bug report for this on the mod's github page. It's status is fixed_pending_release

**Comment by jamie-34254** [comment]
This looks like it's been fixed now, any chance of a modpack update? It makes Environmental Tech pretty unusable. 3.0.6.1 also fixes Xerothium not being mined by t7 miner

**Comment by GizmoTheGreen** [comment]
yeah I -just- ran into this too... xD
hoping for pack update soon.

**Comment by jeremiahwinsley** [comment]
Fixed in pack version 1.3.9.
