### ISSUE TITLE
Resourceful Bees Bee breeding recipes and uses missing on server.

### ISSUE THREAD

**Issue by Crystalined** [AllTheMods/ATM-6#656]
So I host a server and I found out that for some reason all the bees recipes and uses are missing such as breeding or in world uses. But if I go into a single player world all the recipes are there. I hope it isn't just a bug for me so that I can get this fixed for my server. This is on 1.3.7

**Comment by Crystalined** [comment]
So just in case if anyone else encounters this problem I was able to solve it I think with taking the config from the actual client version and inserting into the server.

**Comment by Letoric** [comment]
If you update properly to 1.3.9b, does this still occur?

**Comment by KangyKSLG** [comment]
Hi, i'm on 1.4.0 and this also happens on my server

> If you update properly to 1.3.9b, does this still occur?

**Comment by Pdiddy973** [comment]
I can confirm that he bee recipes and breeding does work in 1.4.0, please try and make a new instance on your client. And make sure you are using a good client like Multimc or GD launcher. The curse/overwolf launcher can have issues upgrading.

**Comment by KangyKSLG** [comment]
It's only server side, it works in single player so don't think the client is the issue

**Comment by Pdiddy973** [comment]
Then the server wasn't updated properly, try a fresh server install and copy over the world and any custom cfgs

**Comment by KangyKSLG** [comment]
Who said I updated? This is a fresh install

**Comment by Pdiddy973** [comment]
Well something didn't install correctly, they work fine on my server...do you have a specific bee it doesn't work on? Or all of them

**Comment by KangyKSLG** [comment]
It's all the bees

I mean I'll try a fresh install and even download the server pack again just to eliminate if it helps the issue progress

**Comment by Pdiddy973** [comment]
did that resolve your issue?

**Comment by KangyKSLG** [comment]
Yes it did, you were indeed correct. It was a fresh install I started with though so not sure what went wrong

**Comment by Pdiddy973** [comment]
computers are weird man lol

**Comment by KangyKSLG** [comment]
I'll drink to that haha

**Comment by Fynxes** [comment]
Hello, I have the same problem. In the single player all information in the JEI is available for the bees. The bees are only sometimes displayed on the server, but then they are not clickable and the information is always missing.

Is there a fix for this?
