### ISSUE TITLE
[1.3.7] Crash on opening/creating world

### ISSUE THREAD

**Issue by user7564** [AllTheMods/ATM-6#659]
Hello, I have been trying to play all the mods 6, however it appears I always run into the same error.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the modpack with about 7GB of ram on 2060 gpu,
2. on title screen click single player,
3. create new world of any kind.

**Expected behaviour**
A world would be created and able to played on

**Screenshots**
https://user-images.githubusercontent.com/50976772/103061527-87ea3580-45e6-11eb-9d2c-414c3e6d71e9.png

**Additional context**
A pastebin log to the crash can be found here:
https://pastebin.com/nq4R5kzE

Thank You,
Glen Henderson

**Comment by user7564** [comment]
I have fixed the crashing by switching launchers to multimc, however the issue has now changed to being stuck at 100% world loaded

**Comment by ViRb3** [comment]
Please follow #384 closely. Create a new, clean installation, with a new world.
