### ISSUE TITLE
Lag in the nether with BYG-Beta World

### ISSUE THREAD

**Issue by AustinMReppert** [AllTheMods/ATM-6#66]
Steps to reproduce:
1. create a new world with the BYG-Beta world type and the seed 52596984844320044.
2. tp to 14875 63 1735
3. create a nether portal and enter it. Fly south a bit and try to generate some chunks.
4. game should lag out

Possible Fix:
Deleting the mekanism and jaopca config folders, restarting, and using the default seems to decrease the amount of lag. Make sure to delete the world and re-create it. After generating the nether with the default configs it may be laggy a bit, just re-log and it should be fine.

**Comment by mrdeadlocked** [comment]
I only seem to have this issue near Bastion remnants. Is that laggy area near one?

**Comment by AustinMReppert** [comment]
Deleting the config files did not actually work, well long term. The nearest one is 700 blocks away. It seems to have loaded in just fine. I am thinking it might be a mob. Have you tried /gamerule doMobSpawning false?
