### ISSUE TITLE
Uranium recipe conflicted

### ISSUE THREAD

**Issue by Azruine** [AllTheMods/ATM-6#660]
There are two conflicting recipes using uranium essence from Mystical Agriculture

EEE
E  E  => 2 Uranium ingots
EEE

EEE
E  E  => 6 Uranium ingots
EEE

E is uranium essence

**Comment by ArchieBeepBoop** [comment]
Can confirm.
![image](https://user-images.githubusercontent.com/53913550/103382743-da3bc280-4ace-11eb-8b20-dd793558ad52.png)

**Comment by jeremiahwinsley** [comment]
Fixed in 1.4.0.
