### ISSUE TITLE
Enchanting Table Conflict?

### ISSUE THREAD

**Issue by dwgeek** [AllTheMods/ATM-6#661]
While playing All The Mods 6 v1.3.7, the enchanting table would not show up in JEI. After crafting it from memory it was named "Air", and when placing it it had a glitched texture before becoming an invisible block that prevented me from walking or jumping on the space where I had attempted to place it. The invisible block issue resolved after restarting the server. I asked about this on the page for Apotheosis and the mod author said it was a conflict with another mod that also was also replacing the table. Can anyone tell me what mod(s) may be causing this conflict and how I can fix it?

**Comment by DivineChili** [comment]
I'm running a server as well, and have the same problem. The no amount of restarts solve the problem for me, and so all enchanting is gone from the server. I also want a fix for this.

**Comment by dwgeek** [comment]
Yeah I meant to say restarting didn't bring it back, it only solved the issue of rubberbanding when attempting to walk where I tried to place the enchanting table that turned invisible.

**Comment by UltraSargent** [comment]
Hey did you ever find a solution to this? Having the same issue.

**Comment by xanderr-s** [comment]
Got the same issue. Also had the same fix with the restart but still dont have the enchanting table

**Comment by jeremiahwinsley** [comment]
This is a bug with Quark's Matrix Enchanting feature, fixed in 1.4.0.
