### ISSUE TITLE
Tinkers Mechworks drawbridge does not work on chucks that have been claimed

### ISSUE THREAD

**Issue by jblankenship30** [AllTheMods/ATM-6#666]
**Describe the bug**
Tinkers Mechworks drawbridge does not work on chucks that have been claimed.

**To Reproduce**
1. On chunk thats not claimed, build drawbridge, then placing a Redstone signal test that it works.
2. On chunk that **is** claimed, build drawbridge, then placing a Redstone signal confirm that it  **does not** work.

**Additional context**
I used the instructions to use the drawbridge from the ingame book as well and the following vid, but neither works while the chunk is claimed (does work when on unclaimed chunk).

[https://www.youtube.com/watch?v=1MrRhn8KmIg](url)

This is an ATM6 1.3.6b server, I had multiple players test and confirm my findings.

**Comment by stefanlawr** [comment]
You have to add MechworksWorker as an ally to your team in FTB Chunks for it to work in a claimed chunk.

**Comment by jblankenship30** [comment]
Thanks, that fix my problem!
