### ISSUE TITLE
enable Create scoria generation?

### ISSUE THREAD

**Issue by boneskull** [AllTheMods/ATM-6#668]
**Is your feature request related to a problem? Please describe.**

The generation of Scoria is disabled in the default Create config.  

**Describe the solution you'd like**

Unless you're looking to eliminate all redundant stone, IMO Create's scoria is superior to that generated by BYG (and comes in two styles).  Please enable it by default.

**Describe alternatives you've considered**

- Disable BYG's scoria in lieu of Create's (instead of _in addition to_, which is what I am proposing)
- Also disable Quark's limestone in lieu of Create's (like with what was done for marble), if you want to reduce redundancies

* * *

Personally, I like having a huge variety of decorative blocks, so I don't really care about consolidation.  I'm not privy to how this pack wants to treat redundant (non-ore) blocks (e.g., BYG's Redwood vs. BoP's Redwood) in general, or if it's just a case-by-case basis--or if the modpack maintainers just don't like Create's scoria. 

This is not really a big deal at all, since I can just enable it manually, but just wanted to throw the idea out there.

**Comment by whatthedrunk** [comment]
I'll bring this up in the dev chat and close this.
