### ISSUE TITLE
Jer not showing

### ISSUE THREAD

**Issue by CivilNikolas** [AllTheMods/ATM-6#67]
I cannot seem to get  jer/jei to show me resources and where they spawn or mob drops/loot. It seems like it doesn't work at all. My world is a byg - beta generated world. Is this the problem? Jei works fine except for the jer part.

**Comment by have-a-boy** [comment]
JER for 1.16 is still extremely early in development and missing a lot of functionality. Mob drops aren't implemented yet afaik, neither is profiling for modded ore distribution. I'm not sure which features the mod actually adds in 1.16, since vanilla ores aren't showing up either.

**Comment by WhitePhant0m** [comment]
Yes, JER is still in alpha so not all features can be expected to work yet. For now it only has Villager trades and Enchants.
