### ISSUE TITLE
Certain Passive Mobs not respawning

### ISSUE THREAD

**Issue by ArchieBeepBoop** [AllTheMods/ATM-6#670]
**Describe the bug**
Recently we've been discussing on the ATM discord about how after the last update (it seems) passive mob generation was affected by something. 

Searching for terms like "cow, cows, pig, sheep" or other passive mobs in the ATM discord I could find many results about people having the same issue and we seemingly have the data to back it up.

Regular passive mob generation whenever a village/new chunk/structure is generated that spawns those mobs seems to be working, but specifically passive mob respawning is just not working at all. Instead, all we get on the surface are hostile mobs, bees and some modded mobs alongside the very occasional vanilla passive mob. (Excluding fish)

Personally in my case I had 6 players looking and looking for sheep, cows and pigs and they could only find a very small amount of those after going over 7-10k blocks searching for them, to the point that they turned them into a -rare commodity- in my server right now.

In Sprocket's case for example, there were over 200 hostile mobs but only 22 cows and sheep had UUIDs according to crash utilities. Removing the hostile mobs would cause them to almost instantly respawn but nothing would actually spawn new cows or sheep while testing.

**To Reproduce**
1. Create a dedicated server
2. Go around and generate the world.
3. Kill passive mobs
4. Watch as they do not respawn or become only 1-5% of all mobs generated according to Crash Utilities (ctrl+u)

**Expected behavior**
More passive mobs such as cows, pigs, foxes, wolves and other should be spawning.

**Screenshots**
![image](https://user-images.githubusercontent.com/53913550/103141118-63698880-46ce-11eb-90cb-a25b3872ca94.png)
![image](https://user-images.githubusercontent.com/53913550/103141123-7419fe80-46ce-11eb-9a00-41827906a676.png)
![image](https://user-images.githubusercontent.com/53913550/103141125-767c5880-46ce-11eb-9648-819766cc2611.png)

**Comment by Baltor34** [comment]
Also Having this issue. Removing Fish spawns from aquaculture helped ever so slightly. But now we realized we have no dragons either or any of the ice and fire creatures except for cockatrices in the other.

**Comment by V2LenKagamine** [comment]
Same issue

**Comment by Rithenar** [comment]
Same here, just had another conversation on Discord about it and asked the Helpers to advise if there are any known issues, mods, configs, or something else that may be contributing to the problem. No answers though so they may not be aware of it.

**Comment by ArchieBeepBoop** [comment]
Personally my server's configs are on default.

**Comment by Rithenar** [comment]
Update: we just rolled a new world in my server when updating to 1.4.0 and we are not having this issue any longer

**Comment by ArchieBeepBoop** [comment]
> Update: we just rolled a new world in my server when updating to 1.4.0 and we are not having this issue any longer

Are you sure? They generate fine when a chunk is first generated, the problem arises after regions are generated.

**Comment by whatthedrunk** [comment]
Seems to be resolved if you get this on 1.5.0 let me know.
