### ISSUE TITLE
1.3.7 Nether lag Embur Bog biome

### ISSUE THREAD

**Issue by pancake4me** [AllTheMods/ATM-6#674]
Whenever I get close enough to load or am in an embur bog biome in the nether my server starts lagging hard, running x many ticks behind and then crashes. I think the crash is just cuz the x many ticks behind thing restarts the server after 60 seconds. And in single player you get alot lag also. Not fps lag but like ping lag. U ant break anything and the commands and stuff don't register. You

go to nether and find embur bog biome. Lag present both in singleplayer and server.

**Comment by nobotious** [comment]
I too am getting this in 1.3.7, was getting it on 1.3.6 as well. if I run a profiler on the server while in embur bog, for some reason it shows bee entity pathing using up all the tick. hadn't associated it with embur bog before, but after testing last night I can only make it happen when I travel near an embur bog biome, newly generated or old.
also did an entity count, and there were about 30 bees, not really many more than what I see in other areas.

https://spark.lucko.me/#jVG37U9nYg

**Comment by allout58** [comment]
Just to give another Spark profile of this issue: https://spark.lucko.me/#LAUyP8Y7lS

**Comment by allout58** [comment]
I actually see Blazes having a bit of a hard time pathing too. Not quite as bad as the bees, but could also be contributing.

**Comment by allout58** [comment]
I think these issues are related https://github.com/CorgiTaco/BYG/issues/112

**Comment by THEJaxster** [comment]
I am too experiencing these issues in the embur bog biome in the Nether.  I cannot escape the biome to see if I will get different results.  I will try moving my portal and see if I can reach a new Nether biome.

**Comment by ArchieBeepBoop** [comment]
Same issue, it's outright crashing the server.

**Comment by JJCUBER** [comment]
I am also having this issue.  It lags hard to the point where I have to restart cycle the game multiple times to escape them.  It also causes the game to use more than the allocated amount of memory, along with using all of the cpu.

**Comment by ArchieBeepBoop** [comment]
I've unfortunately had to reset my nether while blacklisting this specific biome from spawning, which altered the entirety of the nether biome generation, sadly.

**Comment by jeremiahwinsley** [comment]
Fixed in 1.4.0.
