### ISSUE TITLE
[1.3.7] Issue installing modpack on Serverminer.com

### ISSUE THREAD

**Issue by sharddragonite** [AllTheMods/ATM-6#677]
When I attempt to install the pack on my server at Serverminer.com it keeps throwing errors saying unable to download a number of the mods in the packlist. I can't tell if it is a problem with the host or the pack files so I have dropped a ticket on both.

https://pastebin.com/GttMch4R

**Comment by ViRb3** [comment]
Definitely a problem with your host or the way you are installing the modpack there. The only server distribution we support is the [simple server](https://www.curseforge.com/minecraft/modpacks/all-the-mods-6/files/3145704) on Curse.
