### ISSUE TITLE
piglins not able to pick up or track gold 

### ISSUE THREAD

**Issue by CKY-** [AllTheMods/ATM-6#679]
Piglins dont track or pick up gold from the ground in a server environment

**To Reproduce**
1. Go to nether
2. toss gold at feet of piglin

**Comment by NetMasterFlex** [comment]
This is not a bug.  Gold is not given using that method. You have to have gold in hand, then press the use button while facing the piglin.

**Comment by Pdiddy973** [comment]
Seems that if mob greif is disabled you need to right click to trade, that should also apply in claimed chunks

**Comment by CKY-** [comment]
Claimed chunks are not the issue,  after our last server update  3 rules got changed in the overworld and nether  "daylight cycle", "mob griefing" and "mob spawning". its odd that they would be changed but if others are having these issue  have them check all 3 rules.. thank you for pointing out  the mob griefing
