### ISSUE TITLE
All The Mods 6, blocks after terrain generation, before joining world - OSX

### ISSUE THREAD

**Issue by psperneac** [AllTheMods/ATM-6#68]
ATM6, 025a (but happenned on 0.24 as well). MacBook, GDLauncher, 8GB given to jvm.

After generating the world, when the chunk gen is at 100% it just waits there forever without joining world. log file seems to indicate a problem with immersive engineering. If you need any other logs let me know.

Here's the log: https://pastebin.com/uzvxnVu8

**Comment by whatthedrunk** [comment]
We are currently on 1.16.3 so removing older issues to make way for new ones. If you want to test it out join the discord for an early beta. New update will be on Twitch / Curseforge once Mekanism pushes their update to the site.
