### ISSUE TITLE
Quarry Plus + Chunk loader

### ISSUE THREAD

**Issue by ImOnIce** [AllTheMods/ATM-6#682]
So im playing ATM6 with my friend on a nitrado server.

Im using the Quarry Plus and cant get it running if there is no one (no chunk loaded)
I know of the FTB Chunk Loader on the map but as soon as i claim the junk as my team, the quarry doesnt brake blocks anymore (even if im there). It moves normally but doesnt brake the blocks.

Does someone know what the problem could be?

Thx

**Comment by whatthedrunk** [comment]
In the mods config enable chunkloading to true. This has been fixed in newer versions.
