### ISSUE TITLE
Severe lag encountered with Chisels & Bits and pressure plates (1.3.7)

### ISSUE THREAD

**Issue by Perryman** [AllTheMods/ATM-6#683]
When exceeding 20-30 chiseled blocks in an area on a server, stepping on a pressure plate causes severe visible lag during walking.

1. Create a new empty server
2. Join the world with only 1 player
3. Change to creative
4. Pick any Chiselable block (e.g. marble bricks)
5. Chisel in a simple design (ex: removing a drawn region in the center of each face)
6. Shift-right-click with e Positive Chisel Design to get the written template
7. Use the written template to convert 30 or 40 blocks nearby to the design (e.g. floor or wall)
8. Place a wooden pressure plate on the floor
9. Walk over the pressure plate
10. Lag seems to scale based on number of chiseled bits present

Expected result: 
No lag visible or an error message indicating the problem.

Additional context:
Noticed on two hosting platforms.  No additional things causing lag appear to be present.  Going to a region with no chiseled bits placed in the world appears to remove the lag.  Please let me know if there's anything I've forgotten to include or anything else I can provide to be more helpful.  Thanks for your time!

**Comment by whatthedrunk** [comment]
Not hearing about this issue and it's been updated since. Let me know if this is happening on 1.5.0 and I'll try and replicate it.
