### ISSUE TITLE
Buy Minecraft

### ISSUE THREAD

**Issue by Jak2k** [AllTheMods/ATM-6#684]
**Describe the bug**
I've bought MINECRAFT a few years ago.
Now, a mod says:"You have to buy MINECRAFT."
If I click "Purchase Now!", I see the monjang-website.
If I click "Continue Playing!", I in Minecraft and can't set new blocks.

**To Reproduce**
1. Load a world
2. See error

**Screenshots**
*picture en*
![image](https://user-images.githubusercontent.com/76660118/103176708-5a1a2080-4874-11eb-9059-41522443a0ff.png)
*picture de*
![image](https://user-images.githubusercontent.com/76660118/103176600-5e920980-4873-11eb-8a29-c7e44b68f22c.png)

**Comment by Peach774** [comment]
That's not a mod - thats vanilla minecraft. Are you not logged in or playing bedrock edition somehow?

**Comment by ViRb3** [comment]
This looks like Minecraft Bedrock Edition / Windows 10 Edition, which is obtained from the Microsoft Store. This is different from the original Minecraft Java Edition. This modpack is only supported on the original Java Edition. Please download it from here: https://www.minecraft.net/en-us/download
