### ISSUE TITLE
Wither skeletons drop witherbones and not withered ribs - no way to get withered ribs currently

### ISSUE THREAD

**Issue by wolpoff** [AllTheMods/ATM-6#686]
Wither Skeletons do not seem to drop Withered Ribs.  They are dropping Witherbones.  

**To Reproduce**
1. Kill Wither Skeletons as player (or with machines that kill as player)
2. Receive many witherbones and no wither ribs

**Expected behavior**
Expect Wither Skeletons to drop wither ribs at ~10%

**Additional context**
I've confirmed in JEI that withered ribs should be a 10% drop for the wither skeletons and witherbones should drop from the Cockatrice.  But looks like it's overridden somewhere.  Wither Bees require withered ribs and you cannot substitute witherbones.  I don't see a way to get the ribs currently.  I've killed hundreds by hand and with machines and get the same results.

**Comment by Letoric** [comment]
The drops seem to work correctly. Sometimes the odds do not go your way.

**Comment by Letoric** [comment]
Glad you're enjoying it still in spite of some really awful luck.

**Comment by ahfuuu** [comment]
I think I figured it out, for anyone facing this issue in the future. Wither skeletons spawned from spawners from the Dungeon Crawl mod (they usually have iron/diamond armor) have an overridden loot table, and don't drop withered ribs. Normal wither skeletons spawned in the nether do.
