### ISSUE TITLE
Typo in Repurposed Structures config

### ISSUE THREAD

**Issue by CoconutThunder** [AllTheMods/ATM-6#688]
https://github.com/AllTheMods/ATM-6/blob/34987b109299c5ae02de847f29bf2d8102814439/config/repurposed_structures-strongholds.toml#L79

This line has quotes, which doesn't match the syntax of the rest of the file.  Is it a typo?

**Comment by mkaito** [comment]
No, this is a peculiarity of how Forge handles config files.

**Comment by TelepathicGrunt** [comment]
oh looks like i accidentally left a space on the end of that config file name lol. Will fix that (if you changed the value for that particular config before, it's gonna default back to true after my next update)
