### ISSUE TITLE
[1.3.7] Chunk lighting and block interaction issues (unknown cause)

### ISSUE THREAD

**Issue by Perryman** [AllTheMods/ATM-6#689]
**Describe the bug**
Occasionally certain chunks will be corrupted and not behave correctly.  For example, chunks with torches in them will not have the correct light level and certain blocks will not interact properly within the chunk.

**To Reproduce**
I am unsure the exact cause of the problem.  Primary mods in use have been mid-game Botania (endoflames and spreaders), Ars Noveau, and Elementalcraft.  

**Expected behavior**
Blocks function and update per their intended behavior and light levels stay correct

**Additional context**
Occurs on a hosted server to which I do not have access to the console logs

**Comment by whatthedrunk** [comment]
Not hearing anything about this issue so guessing it's fixed. If not let me know.
