### ISSUE TITLE
Server Crashing Bug with Ender Staves [1.3.7]

### ISSUE THREAD

**Issue by xQgamers** [AllTheMods/ATM-6#690]
**Describe the bug**
When using the ender staff from Cyclic with the Ender Orb (reuseable ender pearl) from cyclic, it brings down my entire server instantly, as well as crashes my client.

**To Reproduce**
1. Get yourself a Cyclic ender staff with a Cyclic ender orb.
2. Try to teleport with the ender staff and ender orb in your inventory.
3. Watch your server crash instantly and possibly client.

**Expected behavior**
I would teleport with the reusable pearl, thus being able to enchant it with indestructible and never have to worry about pearls again.

**Screenshots**
Not applicable

**Additional context**
This problem may occur with other ender staves, I have not tried it with them. I tried it twice with these circumstances to make sure it was what caused the crash.

**Comment by starforcraft** [comment]
I think that should be fixed
