### ISSUE TITLE
mod needs added

### ISSUE THREAD

**Issue by phantom1151** [AllTheMods/ATM-6#691]
i was wondering if you could add a mod called

More Dragon Eggs

So that you get an egg every time you kill the dragon. i dont see another way to eg another egg once someone else has killed the dragon

**Comment by TheNeurotox** [comment]
Currently to get more dragon eggs, you could use:
Dragon Egg Seeds -->  Dragon Egg Essence --> Dragon Egg Chunk --> Dragon Egg

**Comment by mkaito** [comment]
Please post mod suggestions in the dedicated issue: https://github.com/AllTheMods/ATM-6/issues/144
