### ISSUE TITLE
Putting on Blood Magic Living Armor causes client crash

### ISSUE THREAD

**Issue by audiomoddified** [AllTheMods/ATM-6#693]
Putting on the Blood Magic Armor causes a client error.

**To Reproduce**
1. Put on full set of Living Armor

**Expected behavior**
An achievement maybe?

[latest.log](https://github.com/AllTheMods/ATM-6/files/5752426/latest.log)

**Comment by audiomoddified** [comment]
To follow up: the armor must be removed server-side before the client can successfully connect again. Once removed, the client connected just fine.

**Comment by PapaBaal** [comment]
Hi! I'm having the exact same issue.
Could you tell me how can i remove the armor Server-side?

Thanks

**Comment by basbasbasbasbas** [comment]
i have tested this myself, and for me it only worked when i crafted the armor myself, when i got it out of the creative menu it just worked for me. but when crafted in suvival is chrashed my world

**Comment by mkaito** [comment]
This is almost certainly a mod bug. Did you report it upstream?
