### ISSUE TITLE
Elemental Craft v. 2.4.16 - laggy when extracting elements

### ISSUE THREAD

**Issue by lasiecz** [AllTheMods/ATM-6#697]
Hi there,

so I've set up this:
![2020-12-30_13 14 57](https://user-images.githubusercontent.com/12786747/103350688-1a844c00-4aa1-11eb-8021-57cc2393e789.png)

And my FPS dropped from 120FPS to 20FPS and I cant move aroud it. I dont think its because of my setup (GeForce RTX 2070 Super, 32GB RAM, AMD Ryzen 5 3600) because before i've started this mod i had 120FPS. All drivers are updated, windows and java too.

Ant ideas?

**Comment by whatthedrunk** [comment]
Can't replicate so guessing this was fixed a while ago. If you are still having the issue open an issue with the mod dev.
