### ISSUE TITLE
JEI + BEES

### ISSUE THREAD

**Issue by Kjrn1** [AllTheMods/ATM-6#699]
In a single player setting most if not all bees in JEI have a generating bee flower. However when checking JEI on my multiplayer server a few bees seem to be missing their bee flowers. One example would be the glowing bee, in config it says ' Glowing_Flowers', In single player JEI it shows Glowstone/s. The bees that seem to be affected are - Glowing, Lumbar, Ender, Magma, Slimy, Mason, Wither, Withered, Dragonic,Ghost. 3 Bees have no way to be bred or are natural, I assume you need an egg but they are Bismuth, Crimson iron, oratchalcum. I tempted to go into config's and change their bee flower to see if that works, but it's so odd that on single player it is fine but on my server so many are missing.

**Comment by mkaito** [comment]
Sounds like your server pack install might have gone sideways. I suggest you re-run the server files in an empty folder and see if that helps. Please ask for help on Discord if it doesn't.
