### ISSUE TITLE
(M) World map needs confirmation!

### ISSUE THREAD

**Issue by Ceillian** [AllTheMods/ATM-6#7]
This will not leave my screen. I press (m) and nothing comes up. Can't get this message to go away. This started after I updated the server.

**Comment by whatthedrunk** [comment]
Remap the the key to use something else like p rather then m for now.

**Comment by Ceillian** [comment]
actually, that worked. Thanks.

**Comment by akinnee** [comment]
Is there a way to make this not pop up every time I enter the dimension?
