### ISSUE TITLE
Botania Crash - basic setup

### ISSUE THREAD

**Issue by Dovahaak2** [AllTheMods/ATM-6#70]
While playing ATM 6 I created the most basic Botania setup consting of a Mana Pool, Mana Spreader and a Endoflame.
Once I feed the Endoflame (Oak Wood and Coal tested) the game crashes.
Looking at the timing, I believe the crash is caused by the animation of the mana beam.
I recreated the setup in a new world with the same result.
The chunk becomes unloadable for me.

 ![image](https://abload.de/img/2020-08-16_20.04.16p5kvg.png)

Here is the crash report, i failed to hide inside a spoiler.

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 8/16/20 8:04 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error 
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229086_a_(EntityRendererManager.java:237) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:quark:add-render,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:961) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:appliedenergistics2.mixins.json:SkyRenderMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorWorldRenderer,pl:mixin:APP:assets/botania/botania.mixins.json:MixinWorldRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:601) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:client.MixinGameRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:422) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:client.MixinGameRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:951) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:582) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.1-32.0.107.jar:32.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$470/1551660539.call(Unknown Source) [forge-1.16.1-32.0.107.jar:32.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-6.1.1.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-6.1.1.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229086_a_(EntityRendererManager.java:237)
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:961)
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:601)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Dovahaak'/3, l='ClientLevel', x=-130.81, y=4.00, z=-41.17]]
	Chunk stats: Client Chunk Cache: 289, 169
	Level dimension: minecraft:overworld
	Level spawn location: World: (-144,4,-48), Chunk: (at 0,0,0 in -9,-3; contains blocks -144,0,-48 to -129,255,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 2426 game time, 2426 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:446)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:603)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$470/1551660539.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1289786256 bytes (1230 MB) / 5166858240 bytes (4927 MB) up to 5965348864 bytes (5689 MB)
	CPUs: 4
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6400m -Xms256m -XX:PermSize=256m
	ModLauncher: 6.1.1+74+master.966c698
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.1-32.0.107.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.107.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.1-32.0.107.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.107.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.1-32.0.107.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap TRANSFORMATIONSERVICE 
	FML: 32.0
	Forge: net.minecraftforge:32.0.107
	FML Language Providers: 
		javafml@32.0
		minecraft@1
		kotori_scala@2.13.2-build-2
	Mod List: 
		AdditionalEnchantedMiner-1.16.1-16.0.7.jar QuarryPlus {quarryplus@16.0.7 DONE}
		NetherPortalFix_1.16.1-7.0.0.jar NetherPortalFix {netherportalfix@7.0.0 DONE}
		aiotbotania-1.16.1-1.3.jar AIOT Botania {aiotbotania@1.3 DONE}
		simplemagnets-1.0.3-mc1.16.jar Simple Magnets {simplemagnets@1.0.3 DONE}
		curiousshulkerboxes-FORGE-1.16.1-3.0.jar Curious Shulker Boxes {curiousshulkerboxes@FORGE-1.16.1-3.0 DONE}
		Uppers-0.3.0.jar Uppers {uppers@0.3.0 DONE}
		rad-1.16-4.0.1.jar Reload Audio Driver {rad@4.0.1 DONE}
		mcws-win-1.16.1-v1.0.2.jar Macaw's Windows {mcwwindows@1.0.2 DONE}
		SilentMechanisms-1.16.1-0.8.1+62.jar Silent's Mechanisms {silents_mechanisms@0.8.1+62 DONE}
		bambooeverything-1.16-1.0.0.jar Bamboo Everything {bambooeverything@1.16-1.0.0 DONE}
		modnametooltip_1.16.1-1.14.0.jar Mod Name Tooltip {modnametooltip@1.14.0 DONE}
		rsgauges-1.16.1-1.2.4-b2.jar Gauges and Switches {rsgauges@1.2.4-b2 DONE}
		IronJetpacks-1.16.1-4.0.0.jar Iron Jetpacks {ironjetpacks@4.0.0 DONE}
		BetterCaves-1.16.1-1.0.jar YUNG's Better Caves {bettercaves@1.16.1-1.0 DONE}
		ForgeEndertech-1.16.1-7.0.0.0-build.0006.jar Forge Endertech {forgeendertech@7.0.0.0 DONE}
		XaerosWorldMap_1.8.1_Forge_1.16.1.jar Xaero's World Map {xaeroworldmap@1.8.1 DONE}
		CookingForBlockheads_1.16.1-9.0.0.jar Cooking for Blockheads {cookingforblockheads@9.0.0 DONE}
		Controlling-7.0.0.3.jar Controlling {controlling@7.0.0.3 DONE}
		ReAuth-1.16-Forge-3.9.0.jar ReAuth {reauth@3.9.0 DONE}
		Placebo-1.16.1-4.1.2.jar Placebo {placebo@4.1.2 DONE}
		globaldatapack-1.16.1-1.4.2.jar Dark Roleplay - Global Datapacks {globaldatapack@1.16.1-1.4.1 DONE}
		dankstorage-3.7b.jar Dank Storage {dankstorage@3.7b DONE}
		citadel-1.2.0.jar Citadel {citadel@1.2.0 DONE}
		NoFog-1.16b1.jar NoFog {nofog@1.0.1 DONE}
		Powah-1.16.1-2.1.3.jar Powah {powah@2.1.3 DONE}
		ftb-gui-library-1.0.0.15.jar FTB GUI Library {ftbguilibrary@1.0.0.15 DONE}
		rangedpumps-0.8.jar Ranged Pumps {rangedpumps@0.8 DONE}
		potionsmaster-0.1.13-1.16.1-32.0.97.jar Potions Master {potionsmaster@0.1.13 DONE}
		potionofbees-1.16.1-1.0.1.0.jar Potion of Bees {potionofbees@1.16.1-1.0.1.0 DONE}
		culinaryconstruct-FORGE-1.16.1-3.0.0.1.jar Culinary Construct {culinaryconstruct@FORGE-1.16.1-3.0.0.1 DONE}
		WitherSkeletonTweaks-1.16.1-5.0.0.jar Wither Skeleton Tweaks {wstweaks@5.0.0 DONE}
		Bookshelf-1.16.1-6.3.20.jar Bookshelf {bookshelf@6.3.20 DONE}
		itemzoom-1.16.1-2.2.0.jar Item Zoom {itemzoom@2.2.0 DONE}
		u_team_core-1.16.1-3.1.3.168.jar U Team Core {uteamcore@3.1.3.168 DONE}
		randompatches-1.16.1-1.22.1.1.jar RandomPatches {randompatches@1.16.1-1.22.1.1 DONE}
		DarkUtilities-1.16.1-4.0.3.jar Dark Utilities {darkutils@4.0.3 DONE}
		Apotheosis-1.16.1-4.0.0.jar Apotheosis {apotheosis@4.0.0 DONE}
		mcw-doors-1.0.0-mc1.16.1.jar Macaw's Doors {mcwdoors@1.0.0 DONE}
		LightingWand-1.16.1-1.6.1.jar Lighting Wand {lightingwand@1.6.1 DONE}
		Morpheus-1.16.1-4.2.55.jar Morpheus {morpheus@version DONE}
		MekanismGenerators-1.16.1-10.0.8.431.jar Mekanism: Generators {mekanismgenerators@10.0.8 DONE}
		Ma-Essentials-1.16.1-3.2.4.jar Ma Essentials {maessentials@1.16.1-3.2.4 DONE}
		TMechworks-1.16.1-2.2.1.jar Tinkers' Mechworks {tmechworks@2.2.1 DONE}
		JustEnoughResources-1.16.1-0.11.1.93.jar Just Enough Resources {jeresources@0.11.1.93 DONE}
		ftb-teams-1.0.1.7.jar FTB Teams {ftbteams@1.0.1.7 DONE}
		MysticalAgradditions-1.16.1-4.0.0.jar Mystical Agradditions {mysticalagradditions@4.0.0 DONE}
		absentbydesign-1.16.1-1.1.0.jar Absent By Design Mod {absentbydesign@1.16.1-1.1.0 DONE}
		refinedstorage-1.9.2.jar Refined Storage {refinedstorage@1.9.2 DONE}
		structure-gel-api-1.16.1-1.2.1.jar Structure Gel API {structure_gel@1.2.1 DONE}
		PackMenu-1.16.1-2.1.2.jar Pack Menu {packmenu@2.1.2 DONE}
		mcw-bridges-1.0.4-mc1.16.1.jar Macaw's Bridges {mcwbridges@1.0.4 DONE}
		industrial-foregoing-1.16.1-3.0.4-eeeb31e.jar Industrial Foregoing {industrialforegoing@3.0.4 DONE}
		wetstone-1.5.2.jar Wetstone {wetstone@1.5.2 DONE}
		useful_backpacks-1.16.1-1.11.1.71.jar Useful Backpacks {usefulbackpacks@1.11.1.71 DONE}
		torchmaster-2.3.1-alpha.jar Torchmaster {torchmaster@2.3.1-alpha DONE}
		resourcefulbees-1.16.1-0.3.7a.jar Resourceful Bees {resourcefulbees@1.16.1-0.3.7a DONE}
		crashutilities-3.1.jar Crash Utilities {crashutilities@3.1 DONE}
		Compressium-1.0.22.jar Compressium {compressium@1.16.1-1.0.3 DONE}
		AdPoles-1.16.1-5.0.0.0-build.0006.jar To the Bat Poles! {adpoles@5.0.0.0 DONE}
		MekanismAdditions-1.16.1-10.0.8.431.jar Mekanism: Additions {mekanismadditions@10.0.8 DONE}
		Lollipop-1.16.1-2.1.3.jar Lollipop {lollipop@2.1.3 DONE}
		ftb-ranks-1.0.0.5.jar FTB Ranks {ftbranks@1.0.0.5 DONE}
		dungeons-plus-1.16.1-1.0.2.jar Dungeons Plus {dungeons_plus@1.0.2 DONE}
		SilentGear-1.16.1-2.0.7+157.jar Silent Gear {silentgear@2.0.7+157 DONE}
		portality-1.16.1-3.1.0.jar Portality {portality@3.1.0 DONE}
		curios-FORGE-1.16.1-3.0.0.2.jar Curios API {curios@FORGE-1.16.1-3.0.0.2 DONE}
		Botania-1.16-399.jar Botania {botania@1.16-399 DONE}
		managear-1.16.1-2.0.1.jar Mana Gear {managear@1.16.1-2.0.1 DONE}
		Patchouli-1.16-39.jar Patchouli {patchouli@1.16-39 DONE}
		collective-1.16.1-1.35.jar Collective {collective@1.35 DONE}
		camera-1.16.1-1.0.7.jar Camera Mod {camera@1.16.1-1.0.7 DONE}
		angelring-1.16.1-1.3.0.jar Angel Ring {angelring@1.3.0 DONE}
		MysticalCustomization-1.16.1-2.0.0.jar Mystical Customization {mysticalcustomization@2.0.0 DONE}
		elevatorid-1.16.1-1.7.3.jar Elevator Mod {elevatorid@1.16.1-1.7.3 DONE}
		ftb-ultimine-1.1.0.6.jar FTB Ultimine {ftbultimine@1.1.0.6 DONE}
		Runelic-1.16.1-1.0.6.jar Runelic {runelic@1.0.6 DONE}
		MekanismTools-1.16.1-10.0.8.431.jar Mekanism: Tools {mekanismtools@10.0.8 DONE}
		constructionwand-1.16-1.1.jar Construction Wand {constructionwand@1.16-1.1 DONE}
		mcws-roofs-1.16.1-v2.0.0.jar Macaw's Roofs {mcwroofs@2.0.0 DONE}
		curiouselytra-FORGE-1.16.1-3.0.jar Curious Elytra {curiouselytra@FORGE-1.16.1-3.0 DONE}
		cc-tweaked-1.16.1-1.90.3.jar CC: Tweaked {computercraft@1.90.3 DONE}
		AI-Improvements-1.16.1-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 DONE}
		globalxp-1.16.1-v1.4.13.jar Global XP {globalxp@v1.4.13 DONE}
		cherishedworlds-FORGE-1.16.1-4.0.0.1.jar Cherished Worlds {cherishedworlds@FORGE-1.16.1-4.0.0.1 DONE}
		Better Muffling-1.16.1-1.0.1.jar Better Muffling {bettermuffling@1.0.1 DONE}
		cloth-config-forge-4.0.2.jar Cloth Config v4 API {cloth-config@4.0 DONE}
		trashcans-1.0.2-mc1.16.jar Trash Cans {trashcans@1.0.2 DONE}
		tramplestopper-1.15.2-2.0.0.3-universal.jar Trample Stopper {tramplestopper@1.15.2-2.0.0.3-universal DONE}
		bwncr-1.16.1-3.6.15.jar Bad Wither No Cookie Reloaded {bwncr@1.16.1-3.6.15 DONE}
		FastLeafDecay-v23.jar FastLeafDecay {fastleafdecay@v23 DONE}
		ServerTabInfo-1.16.1-1.2.7-alpha.jar Server Tab Info {servertabinfo@1.2.7-alpha DONE}
		BetterMineshaftsForge-1.16.1-1.3.jar YUNG's Better Mineshafts {bettermineshafts@1.16.1-1.3 DONE}
		BetterAdvancements-1.16.1-0.1.0.100.jar Better Advancements {betteradvancements@0.1.0.100 DONE}
		QuarkOddities-1.15.2.jar Quark Oddities {quarkoddities@1.15.2 DONE}
		Ma-Enchants-1.16.1-3.2.1.jar Ma Enchants {ma-enchants@1.16.1-3.2.1 DONE}
		Cucumber-1.16.1-4.0.0.jar Cucumber Library {cucumber@4.0.0 DONE}
		TrashSlot_1.16.1-12.0.1.jar TrashSlot {trashslot@12.0.1 DONE}
		mining-helmet-1.16.1-1.0.8.jar Mining Helmet {mining_helmet@1.0.8 DONE}
		bagofyurting-1.16.1-1.0.0.1.jar Bag of Yurting {bagofyurting@1.16.1-1.0.0.1 DONE}
		jei-1.16.1-7.0.1.9.jar Just Enough Items {jei@7.0.1.9 DONE}
		metalbarrels-3.2b.jar Metal Barrels {metalbarrels@3.2b DONE}
		Abnormals-Core-1.16.1-2.0.2.jar Abnormals Core {abnormals_core@2.0.2 DONE}
		Buzzier-Bees-1.16.1-2.0.1.jar Buzzier Bees {buzzier_bees@2.0.1 DONE}
		Mekanism-1.16.1-10.0.8.431.jar Mekanism {mekanism@10.0.8 DONE}
		caelus-FORGE-1.16.1-2.0-beta7.jar Caelus API {caelus@FORGE-1.16.1-2.0-beta7 DONE}
		reap-1.16.1-1.0.3.jar Reap Mod {reap@1.16.1-1.0.3 DONE}
		invtweaks-1.16.1-1.0.6.jar Inventory Tweaks Renewed {invtweaks@1.16.1-1.0.6 DONE}
		Waystones_1.16.1-7.0.2.jar Waystones {waystones@7.0.2 DONE}
		Clumps-6.0.0.3.jar Clumps {clumps@6.0.0.3 DONE}
		light-overlay-5.4.1.jar Light Overlay Forge {lightoverlay-forge@NONE DONE}
		comforts-FORGE-1.16.1-3.0.jar Comforts {comforts@FORGE-1.16.1-3.0 DONE}
		appliedenergistics2-8.0.0-alpha.2.jar Applied Energistics 2 {appliedenergistics2@8.0.0-alpha.2 DONE}
		NaturesCompass-1.16.1-1.8.5.jar Nature's Compass {naturescompass@1.16.1-1.8.5 DONE}
		EnderBags-1.16.1-6.1.0.jar Ender Bags {ender_bags@6.1.0 DONE}
		[1.16.1]-additionalbars-1.5.1.jar Additional Bars {additionalbars@1.5.1 DONE}
		DimStorage-1.16.1-4.0.2.jar DimStorage {dimstorage@4.0.2 DONE}
		AdHooks-1.16.1-6.0.0.0-build.0006.jar Advanced Hook Launchers {adhooks@6.0.0.0 DONE}
		engineerstools-1.16.1-1.0.9-b3.jar Engineer's Tools {engineerstools@1.0.9-b3 DONE}
		DungeonCrawl-1.16.1-2.0.2.jar Dungeon Crawl {dungeoncrawl@2.0.2 DONE}
		curioofundying-FORGE-1.16.1-4.0.jar Curio of Undying {curioofundying@FORGE-1.16.1-4.0 DONE}
		FarmingForBlockheads_1.16.1-7.0.1.jar Farming for Blockheads {farmingforblockheads@7.0.1 DONE}
		pneumaticcraft-repressurized-1.16.1-2.0.1-7.jar PneumaticCraft: Repressurized {pneumaticcraft@1.16.1-2.0.1-7 DONE}
		mahoutsukai-1.16.1-v1.21.6.jar Mahou Tsukai {mahoutsukai@1.16.1-v1.21.6 DONE}
		environmentalcreepers-forge-1.16.1-1.6.1.jar Environmental Creepers {environmentalcreepers@1.6.1 DONE}
		ToastControl-1.16.1-4.1.1.jar Toast Control {toastcontrol@4.1.1 DONE}
		JEITweaker-1.16.1-1.0.1.2.jar JEI Tweaker {jeitweaker@1.0.1.2 DONE}
		PackingTape-1.16.1-0.9.6.jar Packing Tape {packingtape@0.9.6 DONE}
		mininggadgets-1.4.0.jar Mining Gadgets {mininggadgets@1.4.0 DONE}
		CraftTweaker-1.16.1-7.0.0.23.jar CraftTweaker {crafttweaker@7.0.0.23 DONE}
		extradisks-1.16.1-1.3.jar Extra Disks {extradisks@1.3 DONE}
		ftb-chunks-1.1.1.19.jar FTB Chunks {ftbchunks@1.1.1.19 DONE}
		forge-1.16.1-32.0.107-universal.jar Forge {forge@32.0.107 DONE}
		PassthroughSigns-1.16.1-2.3.5.jar Passthrough Signs {passthroughsigns@1.16.1-2.3.5 DONE}
		MysticalAgriculture-1.16.1-4.0.1.jar Mystical Agriculture {mysticalagriculture@4.0.1 DONE}
		ironchest-1.16.1-11.0.1.jar Iron Chests {ironchest@1.16.1-11.0.1 DONE}
		CraftingTweaks_1.16.1-12.0.4.jar Crafting Tweaks {craftingtweaks@12.0.4 DONE}
		forge-1.16.1-32.0.107-client.jar Minecraft {minecraft@1.16.1 DONE}
		The-Endergetic-Expansion-1.16.1-2.0.0.jar The Endergetic Expansion {endergetic@2.0.0 DONE}
		theoneprobe-1.16-3.0.1-beta.jar The One Probe {theoneprobe@1.16-3.0.1-beta DONE}
		MouseTweaks-2.13-mc1.16.1.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		ToolBelt-1.16.1-1.14.2.jar Tool Belt {toolbelt@1.14.2 DONE}
		titanium-1.16.1-3.0.4.jar Titanium {titanium@3.0.4 DONE}
		ImmersiveEngineering-1.16.1-3.1-112.jar Immersive Engineering {immersiveengineering@1.16.1-3.1-112 DONE}
		SilentLib-1.16.1-4.7.0+58.jar Silent Lib {silentlib@4.7.0+58 DONE}
		bluepower-1.16.1-0.5.213-alpha-universal.jar Blue Power {bluepower@0.5.213-alpha DONE}
		AzureDoom-Chunk-Loader-1.16.1-1.0.1.jar Azuredooms Chunk Loader Mod {chunk@1.16.1-1.0.1 DONE}
		nopotionshift_1.16.1-1.5.0.jar No Potion Shift {nopotionshift@1.5.0 DONE}
		allthemodium-1.0.3-1.16.1-32.0.98.jar Allthemodium {allthemodium@1.0.3 DONE}
		ExtraButtons-1.16.1-4.0.0.jar ExtraButtons {extrabuttons@1.16.1-4.0.0 DONE}
		forbidden_arcanus-1.16.1-1.0.1.jar Forbidden & Arcanus {forbidden_arcanus@1.16.1-1.0.1 DONE}
		Ding-1.16.1-1.1.0.jar Ding {ding@1.1.0 DONE}
		LargeFluidTank-16.0.2.jar FluidTank {fluidtank@16.0.2 DONE}
		Mantle-1.16.1-1.6.20.jar Mantle {mantle@1.6.20 DONE}
		Xaeros_Minimap_20.18.0.1_Forge_1.16.1.jar Xaero's Minimap {xaerominimap@20.18.0 DONE}
		JAOPCA-1.16.1-3.3.0.3.jar JAOPCA {jaopca@3.3.0.3 DONE}
		rats-6.0.5-1.16.1.jar Rats {rats@6.0.5 DONE}
		pamhc2foodcore-1.16.1-1.0.5.jar Pam's HarvestCraft 2 Food Core {pamhc2foodcore@version DONE}
		gravestone-1.16.1-1.0.6.jar Gravestone Mod {gravestone@1.16.1-1.0.6 DONE}
		ftb-backups-2.1.1.5.jar FTB Utilities: Backups {ftbbackups@2.1.1.5 DONE}
		serverconfigupdater-1.2.jar ServerConfig Updater {serverconfigupdater@1.2 DONE}
		FastWorkbench-1.16.1-4.2.0.jar FastWorkbench {fastbench@4.2.0 DONE}
		polymorph-FORGE-1.16.1-0.12.jar Polymorph {polymorph@FORGE-1.16.1-0.12 DONE}
		AutoRegLib-1.6-43.jar AutoRegLib {autoreglib@1.6-43 DONE}
		Quark-r2.2-260.jar Quark {quark@r2.2-260 DONE}
		[1.16.1] SecurityCraft v1.8.19.1-beta2.jar SecurityCraft {securitycraft@v1.8.19.1-beta2 DONE}
		StorageDrawers-1.16.1-8.0.0.jar Storage Drawers {storagedrawers@1.16.1-8.0.0 DONE}
		sit-1.16.1-v1.3.jar Sit {sit@v1.3 DONE}
		DoubleSlabs-1.16-3.3.3.jar Double Slabs {doubleslabs@3.3.3 DONE}
		tubesreloaded-1.16.1-1.4.0.0.jar Tubes Reloaded {tubesreloaded@1.16.1-1.4.0.0 DONE}
		FastFurnace-1.16.1-4.1.1.jar FastFurnace {fastfurnace@4.1.1 DONE}
		AppleSkin-mc1.16.1-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 DONE}
		engineersdecor-1.16.1-1.1.1-b6.jar Engineer's Decor {engineersdecor@1.1.1-b6 DONE}
		modular-routers-1.16.1-7.0.0-24.jar Modular Routers {modularrouters@1.16.1-7.0.0-24 DONE}
		allthetweaks-0.9.12-1.16.1-32.0.97.jar All The Tweaks {allthetweaks@0.9.12 DONE}
		byg-1.0.15.jar Oh The Biomes You'll Go {byg@1.0.15 DONE}
		Aquaculture-1.16.1-2.0.17.jar Aquaculture 2 {aquaculture@1.16.1-2.0.17 DONE}
		refinedstorageaddons-0.7.jar Refined Storage Addons {refinedstorageaddons@0.7 DONE}
		CosmeticArmorReworked-1.16.1-v1b.jar CosmeticArmorReworked {cosmeticarmorreworked@1.16.1-v1b DONE}
		EnderMail-1.16.1-1.1.2.jar Ender Mail {endermail@1.16.1-1.1.2 DONE}
		balancedenchanting-1.0.jar Balanced Enchanting {balancedenchanting@1.0 DONE}
		xptome-1.16.1-v1.1.6.jar XP Tome {xpbook@v1.1.6 DONE}
		DefaultOptions_1.16.1-12.0.1.jar Default Options {defaultoptions@12.0.1 DONE}
		bigbuckets-1.1.1.jar BigBuckets {bigbuckets@1.1.1 DONE}

**Comment by coffeeordeath** [comment]
this is fixed in 0.26a. I had the exact same issue https://github.com/AllTheMods/ATM-6/issues/57. 

loaded up 0.26a and experienced zero issue going back to that region

**Comment by Dovahaak2** [comment]
> 
> 
> this is fixed in 0.26a. I had the exact same issue #57.
> 
> loaded up 0.26a and experienced zero issue going back to that region

Damn looks like this is my bad. I even tried searching the Issues.

Thanks anyway,
