### ISSUE TITLE
Ticking Entity / Server Crash

### ISSUE THREAD

**Issue by nzminecraftDOTcom** [AllTheMods/ATM-6#702]
**Describe the bug**
Server crash, seems to be totally random entities causing it. Crash log posted at bottom of report. 

**To Reproduce**
Unknown how to reproduce as we are trying to figure out this ourselves as well. Seems to be either a player with armour with a teleporting enchant gets hit by a mob (endermite in one case) however the latest crash no teleporting enchantment is present and it is a Hoglin attacking the player that caused the crash. 

**Expected behavior**
No crash, gameplay as normal

**Screenshots**
N/A - unknown when crash will occur, it's totally random

**Additional context**
Here's he crash report.
https://pastebin.com/zQHYqDbJ

I've set the forge server config to remove erroring tile entities and erroring entities, seems to make no difference in this case weather those are set to true or false, a crash still occurs.

**Comment by jmac460** [comment]
I second this. My steps to repeat from my experience: Enter nether and load chunks in the Embur Bog biome. Ticking entity causes severe tps lag and something maxes out memory due to recurring function. I do not have a crash report (because my SP doesnt outright crash.. but a server will crash). The displacement enchantment is causing crashes when an endermite hits a player.

**Comment by huy08071997** [comment]
You must delete Dim-1 and go to patch config\byg
byg-world.toml 
Scroll to end[The_Nether] and add a blacklist "...,byg:embur_bog"
Rerun and enjoy your world again!!! 
30char!
![2021-01-01_02 23 18](https://user-images.githubusercontent.com/40495896/103424277-d64a9600-4bdd-11eb-9d29-4aa43d611c41.png)

**Comment by nzminecraftDOTcom** [comment]
> I second this. My steps to repeat from my experience: Enter nether and load chunks in the Embur Bog biome. Ticking entity causes severe tps lag and something maxes out memory due to recurring function. I do not have a crash report (because my SP doesnt outright crash.. but a server will crash). The displacement enchantment is causing crashes when an endermite hits a player.

This is totally different to the ember bog "freeze" the crash I am describing is instant. IE the server does not hang, stutter, lag, freeze etc before "stopping", moving away from an ember bog fast, results in the server actually recovering and running fine.

**Comment by huy08071997** [comment]
Now you can enable biome embur bog, but u must go to folder config "badmobs-common.toml" and find
[minecraft.endermite]
		#Should the entity be allowed to spawn normally?
		allowNormalSpawning = false <- default true
		#Should spawners be able to spawn the entity?
		allowSpawners = true
		#Should spawn eggs be able to spawn the entity?
		allowSpawnEggs = true
		#When enabled the entity type will be aggresively removed from worlds. This will bypass all other options.
		removeAggressively = true <- default false

I think endermite mob useless for this mod pack! 
![2021-01-01_20 41 37](https://user-images.githubusercontent.com/40495896/103439844-0c862500-4c73-11eb-9883-add8aafd767f.png)

**Comment by jmac460** [comment]
> > I second this. My steps to repeat from my experience: Enter nether and load chunks in the Embur Bog biome. Ticking entity causes severe tps lag and something maxes out memory due to recurring function. I do not have a crash report (because my SP doesnt outright crash.. but a server will crash). The displacement enchantment is causing crashes when an endermite hits a player.
> 
> This is totally different to the ember bog "freeze" the crash I am describing is instant. IE the server does not hang, stutter, lag, freeze etc before "stopping", moving away from an ember bog fast, results in the server actually recovering and running fine.

I meant to word my response better but my issue is exactly the same as yours, I just added another thing I could replicate as well. The displacement enchantment instantly crashes the server when hit by an endermite. Hope that clears up my mess of a response

**Comment by mkaito** [comment]
You say this is not related to the Embur Bog, but

> moving away from an ember bog fast, results in the server actually recovering and running fine.

Would suggest that it almost certainly is. Blacklist the biome in BYG config (or update your pack, we just blacklisted it) and regenerate the nether.
