### ISSUE TITLE
Drawbridge 

### ISSUE THREAD

**Issue by EmrisMage** [AllTheMods/ATM-6#704]
Drawbridge from Tinkers' Mechwarrior do not work in claimed/loaded chunks.

**Comment by Malexion** [comment]
I had this issue as well, with routers, builders, tinkers and more. 

Try adding them to allies, make sure it's the check mark symbol.

![image](https://user-images.githubusercontent.com/5237473/103431002-7b8a4d80-4b8f-11eb-96a1-b29ba4aecf3a.png)

![image](https://user-images.githubusercontent.com/5237473/103431007-8a710000-4b8f-11eb-9ab7-3e404f7fd289.png)

![image](https://user-images.githubusercontent.com/5237473/103431013-9eb4fd00-4b8f-11eb-8dce-344e38a0a840.png)
