### ISSUE TITLE
[1.3.7] Create Duplication

### ISSUE THREAD

**Issue by Jaymus3** [AllTheMods/ATM-6#705]
**Describe the bug**
Create mc1.16.3_v0.3a has a duplication glitch relating to stale contraptions.  Mod should be updated to the latest version which fixes said bug.

**Comment by CrooksyPlays** [comment]
Can you explain how this is done?

**Comment by Jaymus3** [comment]
I'd rather not explain it specifically since that would just lead to it being abused until fixed.  The Create devs were aware of it and patched it, and this issue isn't submitted to them for debugging.  The mod just needs to be updated to the latest version.

**Comment by Jaymus3** [comment]
Closing as issue is resolved in latest version.
