### ISSUE TITLE
ATM6 1.3.7 Server Crash

### ISSUE THREAD

**Issue by Volcanon-** [AllTheMods/ATM-6#708]
Looks like a ticklock where a tick takes more than 60s and the watchdog kills it.

Unknown whats causing it right now but it seems to be one player joining that starts it.

Crashlog: https://pastebin.com/ef7D2cxd

Server CLI when that player joins: https://pastebin.com/Vv92n6RU

**Comment by Volcanon-** [comment]
Here's logs from the server's CLI when the crash happens:

https://pastebin.com/Vv92n6RU

**Comment by Volcanon-** [comment]
Did some troubleshooting and it looks like it was corrupted chunks.  The player was around a village and when we teleported him away from that area and restarted the server, it didn't re-occur.  Obviously we can regen these chunks to fix the problem for now, but it may come back.  I have a copy of these chunks/world files and the coordinates handy if you all want it.

**Comment by mkaito** [comment]
These things happen. If it happens again, please open another issue.
