### ISSUE TITLE
Atm6 // waiting for server crash 

### ISSUE THREAD

**Issue by KoobeBryant** [AllTheMods/ATM-6#709]
when playing on singleplayer world, exploring an area I get a waiting for server message and I lag. I have to restart the game to fix.

**Comment by nzminecraftDOTcom** [comment]
Was it an Embur Bog by any chance, in the nether. Orange biome, trees etc.

**Comment by KoobeBryant** [comment]
> Was it an Embur Bog by any chance, in the nether. Orange biome, trees etc.

well I put down the nether portal and went in and left right away but then right after that i went exploring an area in the overworld and everytime I go to that spot It does that message and my game breaks so it might have something to do with that

**Comment by mkaito** [comment]
We're blacklisting the Embur Bog with the next release. You'll have to reset your nether to fix.
