### ISSUE TITLE
No Custom Biomes in Nether

### ISSUE THREAD

**Issue by AngelOfStars** [AllTheMods/ATM-6#710]
Nether generation in my world generates the vanilla 1.16.4 biomes instead of the ones from BYG and BOP. I made other worlds to test it and it seems to only happen when I select the BOP world generation in the world creation menu.  Is there a way to fix this/get the other Nether generation? 

I also tried deleting the DIM files for the nether but it didn't fix anything.

**Comment by huy08071997** [comment]
Goto patch All the Mods 6 - ATM6 - 1.16.4\config\byg byg-world.toml

[The_Nether]
	#Does BYG control The Nether?
	ControlNether = true  <- set false

**Comment by AngelOfStars** [comment]
> Goto patch All the Mods 6 - ATM6 - 1.16.4\config\byg byg-world.toml
> 
> [The_Nether]
> #Does BYG control The Nether?
> ControlNether = true <- set false

Tried this with both the Nether and End, it didn't work and still generates the basic chunks without the new/modded biomes.

**Comment by mkaito** [comment]
You should have picked default world generation. The other options are known to be broken. You can alter your `level.dat` using nbtexplorer or regenerate your world.
