### ISSUE TITLE
Crushed Platinum Ore from Create missing smelting and washing Recipes

### ISSUE THREAD

**Issue by ArsStarhawk** [AllTheMods/ATM-6#712]
User is able to crush any _forge:ores/platinum_ using the Crushing Wheels or Millstone from the Create mod. This produces a _create:crushing/platinum_ore_ item that has no further recipes, resulting in a dead end with a useless item. 

All other crushed ores from Create have recipes that enable it to be smelted into ingots in addition to being washed with Create's methods.

**Comment by NoMoreStars** [comment]
Anyone aware of if this bug has been fixed in the newest version? This doesn't seem to be fixed on 1.4.0., which was released after this bug report

**Comment by whatthedrunk** [comment]
I added a simple smelting recipe for now.
