### ISSUE TITLE
Ticktime increases until its unplayable even if nobody is online

### ISSUE THREAD

**Issue by deejaypro** [AllTheMods/ATM-6#714]
**Describe the bug**
After letting the server run for a few hours, with, the ticktime keeps and keeps increasing until the tps starts to dip below 20 even if no players are on the server:
![Lag_new](https://user-images.githubusercontent.com/18632159/103458363-76500e80-4d07-11eb-9536-87bfe832df6f.PNG)

We upgraded from 1.3.3 to 1.3.7 and thats when the problem started.
I also ran spark for a lag report (report only gathered ticks higher than 1400ms):
https://spark.lucko.me/#5Vawd9YeoO

**Comment by jeremiahwinsley** [comment]
According to the Spark profile, this specific issue seems to be a Marine Fisher and something in the loot table. You can try finding that machine and turning it off.

Bug in question seems to be a reoccurrence of this: https://github.com/TeamMetallurgy/Aquaculture/issues/113

**Comment by Letoric** [comment]
Does this occur in 1.3.9b?
