### ISSUE TITLE
Client overflow on elevator block with bit

### ISSUE THREAD

**Issue by PletPeter** [AllTheMods/ATM-6#716]
Elevators can get the appearance of blocks by right clicking with a block in hand. However this doesn't work with bits and leads to what is essentially a chunkban.

**To Reproduce**
1. Put an elevator block in the world
2. Rightclick the elevator with a bit from chisels and bits in hand
3. Your client will kick you and unless you are still in the area upon relogging it will keep kicking you.

**Expected behavior**
Either get the appearance of the bit or have nothing happen.

**Other notes**
This can lead to players chunkbanning and can be a pain for moderators to solve. This one is quite severe.

**Comment by mkaito** [comment]
Would you please report this upstream to the elevator mod?

**Comment by PletPeter** [comment]
VsnGamer/ElevatorMod#71

**Comment by PletPeter** [comment]
Mod author seems to have fixed this in a new release. Ball's in ATM6's court now.

**Comment by mkaito** [comment]
Will be updated in next release

**Comment by jeremiahwinsley** [comment]
Fixed in 1.4.0.
