### ISSUE TITLE
Quarry plus not mining all the mods specific ores

### ISSUE THREAD

**Issue by CJNiiva** [AllTheMods/ATM-6#717]
Quarry plus doesnt grab all the items, I'm guessing this is based on the diamond pickaxe, but this item is a quarry, not a diamond pickaxe, so I consider it a bug, hahah. also happens in the other:)

**Comment by jeremiahwinsley** [comment]
Not a bug. Allthemodium, Vibranium, Unobtanium, and Other ores cannot be mined by quarries. QuarryPlus deletes any ore it cannot mine. If you want the ores to stay, you can use an RFTools Builder with a clearing quarry card, which leaves any blocks it cannot mine.

**Comment by CJNiiva** [comment]
oh, okei, my bad, thanks anyways:)

**Comment by mkaito** [comment]
Working as intended.
