### ISSUE TITLE
Blood Magic Rituals

### ISSUE THREAD

**Issue by PapaBaal** [AllTheMods/ATM-6#718]
So I've been making my way through blood magic, and was wanting to make a well of suffering, So i made the ritual diviner but scrolling through the rituals stored on it, there seems to only be a few that you can use the diviner for? Is that because the other rituals are disabled or do I have to inscribe the stones myself?

**Comment by Psionicflea** [comment]
Is this a Tier 2 Diviner you are using? Well of Suffering is part of the T4 Blood Altar and requires Dawn and Dusk runes which is unlocked once you hit T4. You will then need to craft the Tier 2 Diviner which will have Well of Suffering included in the list.

**Comment by PapaBaal** [comment]
> Is this a Tier 2 Diviner you are using? Well of Suffering is part of the T4 Blood Altar and requires Dawn and Dusk runes which is unlocked once you hit T4. You will then need to craft the Tier 2 Diviner which will have Well of Suffering included in the list.

Yeah i never noticed it needed the dusk runes, Thanks!
Do you know if it's possible to get the higher level Rituals? I.e Convocation of the damned?

**Comment by Psionicflea** [comment]
I do not believe so. That required a T6 altar in the older Blood Magic days, and as of now we can only go up to T5 due to lack of demonic clusters that were needed for T6. 

This will provide information better than I can; https://bm.minecraftguides.net/

**Comment by jeremiahwinsley** [comment]
Most of the rituals, including Well of Suffering, are not yet implemented. Blood Magic is still in alpha.
