### ISSUE TITLE
Nether causes dedicated servers to crash

### ISSUE THREAD

**Issue by Ruchian** [AllTheMods/ATM-6#719]
The Nether causes a dedicated server to crash.
Precise reason, I don't know. (The server + client requires too much resources for me to personally test this. I am not an admin of the said server.)

To reproduce:
Use the ATM 6 Server pack to make a dedicated Server.
Log into this server.
Go to the nether.
Travel around there.

Expected: 
No problems

There are a couple of other things I have noticed:
Spawning of mobs causes severe load issues (lag), this includes the Vanilla Blaze Lamp Obsidian tower spawns.
The chunks are not generating properly. You can see on the FTB Teams map that the nether looks like a weird corrupted image of rectangle shaped chunks with perfect corners. 
Due to this I expect this to be a chunk generation issue / conflict. If so it involves both "Oh the biome's you'll go" and "Biomes O Plenty".

The crash is very chunk dependant. As literally you have this border chunk where you can stand in, and if you move even one chunk towards the problem, you crash the server.
Not just you, if you throw an item in that chunk it causes a crash or if you mine a block in the border.
I suspect entities spawning also causes this or them walking there. 
The problem seems to occur more severely the more chunks it needs to generate (meaning further away from the initial spawn). This is likely because it is very confused with chunks.

Other people, who'se issues I read, believe it maybe AI that causes this or a very specific biome, but from what I have seen is that there is a lot more going on.

If you can, please test it out and try to find the cause so mod devs can fix it. Currently server admins need to pull out players when they simply want some quartz or blaze rods.

The above issue is present in Pack version 1.3.7. (the current latest.)

**Comment by F0x06** [comment]
Hi, exact same issue on my server using ATM6 1.3.7

Config:
  CPU: i9 9900k @ 5Ghz
  Mem: 16G DDR4 @ 3200Mhz

Everytime someone explores the nether the server hangs then crashes

**Comment by Jaymus3** [comment]
Cannot reproduce on the latest version of the pack.  Generated hundreds of chunks on a dedicated server with no crashes.  Can you at least provide a crash log?  Not providing one makes trying to help nearly impossible.

**Comment by F0x06** [comment]
> Cannot reproduce on the latest version of the pack. Generated hundreds of chunks on a dedicated server with no crashes. Can you at least provide a crash log? Not providing one makes trying to help nearly impossible.

There is no crash logs, only messages saying (the server can't keep up) and after a short period a message that says: due to delay the server is considered as crashed and will be stopped, I can find the exact message later, maybe providing my map can help?

**Comment by Jaymus3** [comment]
You might be able to learn more by using a profiler like Spark.  If you provide the world seed I'll try generating it.

**Comment by F0x06** [comment]
> You might be able to learn more by using a profiler like Spark. If you provide the world seed I'll try generating it.

Seed: `-7935282952796891334` 

i'll try to test with Spark, issue is only server-side when using a dedicated server.

**Comment by F0x06** [comment]
> > You might be able to learn more by using a profiler like Spark. If you provide the world seed I'll try generating it.
> 
> Seed: `-7935282952796891334`
> 
> i'll try to test with Spark, issue is only server-side when using a dedicated server.

Here you go successfuly reproduced the freeze with SPark active, you can check here: https://spark.lucko.me/#bXDYIqPPsZ

Apparently the freezes are cauded by `com.resourcefulbees.resourcefulbees.entity.passive.CustomBeeEntity.livingTick() / 85.03% 38364ms`

![image](https://user-images.githubusercontent.com/7167311/103490892-2fedd300-4e1f-11eb-9725-236ea6c735f0.png)

**Comment by Jaymus3** [comment]
Can you expand that tree further? I'd like to see exactly what it boils down to

**Comment by Jaymus3** [comment]
It seems more specifically linked to the entity movement of said bee and as mentioned in the other issue another mod is likely to blame.  I'm not a maintainer of this pack so I'm not really gonna dig further into it, but the next stage would be swapping mods in and out until the issue goes away.

**Comment by mkaito** [comment]
The issue is almost certainly related to the Embur Bog biome, which we are blacklisting with the next release. You'll have to delete any existing Embur Bog chunks in your world, or nuke the nether entirely.

**Comment by Ruchian** [comment]
Cool, thanks for doing the sparky research. This enlights a lot for me at least.

**Comment by Ruchian** [comment]
In my observation, it looks like that the trigger maybe any entity that sets things on fire (has flame particle effects, or something)
The most pronount cause for crash issues seem to be either Lava bees (very specifically yes) or Blaze.
blaze randomly spawn everywhere due to Vazkii's programming (Quark). 
His Fox,Hound thing may also cause it, but other entities are completely fine in the Embur Bog biome and don't cause server issues.
e.g. On peaceful mode you can likely play at least and test things.

**Comment by Ruchian** [comment]
@mkaito https://github.com/CorgiTaco/BYG/issues/112#issuecomment-754957764
seems like BYG dev found a way to work around the issue. Maybe blacklisting won't be nessecary. Also, it seems like my observation was flawed, but then again I am a mere player that, doesn't truly understand code so yeah... e.e;
Just letting you know.
