### ISSUE TITLE
Cannot load into server or singleplayer

### ISSUE THREAD

**Issue by technicalrelic** [AllTheMods/ATM-6#720]
need some help here, i got a server with the mod pack so i downloaded forge and the mods and tried to play in singleplayer first, it loaded to %16 over the span of half an hour then crashed, happens every time, when i try to join my server it also crashes

**Comment by mthp1999** [comment]
Try increasing the amount of ram you have allocated to the pack, the 4GB default is not enough. On my laptop with 8GB I need 6GB to run it comfortably.

**Comment by mkaito** [comment]
If you are using the curseforge launcher, try GDLauncher or multimc. Curseforge is known to cause this issue. Ask for further support on Discord.

**Comment by technicalrelic** [comment]
> If you are using the curseforge launcher, try GDLauncher or multimc. Curseforge is known to cause this issue. Ask for further support on Discord.

it will not download on GDL
