### ISSUE TITLE
Config is not loading

### ISSUE THREAD

**Issue by Velajuel121** [AllTheMods/ATM-6#721]
Hi, I have a private minecraft server with the Simple-Server-Files-1.3.7 from https://www.curseforge.com/minecraft/modpacks/all-the-mods-6/files

I tried to change several config files both in the defaultoptions and in the TOML files for example iceandfire-common.toml

In there i changed the health of the dragons, disabled the spawn of cockatrice and saved it. Then I restarted the server.

In The Other Dimension the Cockatrice still spawns.
Other changes to config files like the sethome command in ftbessentials also dont work.

Am I doing something wrong?
![image](https://user-images.githubusercontent.com/32167792/103487462-f6f53480-4e05-11eb-953f-939765c95cf6.png)
![image](https://user-images.githubusercontent.com/32167792/103487503-48052880-4e06-11eb-8f29-40c5aa4dd6bd.png)

**Comment by mkaito** [comment]
`defaultconfig` only applies to newly generated worlds. The options for existing worlds are under `world/serverconfig`.

**Comment by Velajuel121** [comment]
And why do classic config files not work?

**Comment by mkaito** [comment]
I don't know what you mean by classic configs, sorry.

**Comment by Velajuel121** [comment]
![image](https://user-images.githubusercontent.com/32167792/103759468-11046200-5014-11eb-8270-01356aa25d2f.png)
I miss some config files in the world/serverconfig like "ice and fire" or "applied energistics".
On serverhosting sites I could change the config files. Now this is my first own server with ATM6. On Nitrado when I changed the config files in the config folder It worked after a restart.
