### ISSUE TITLE
Can't smelt Sand

### ISSUE THREAD

**Issue by DraGoNaHE** [AllTheMods/ATM-6#723]
Hey. 

So I was removing some Mods from the pack to get a better performance and the receipe for Glass has been altered/removed.
Right now, the only way to make Glass for me is to craft together Glass Shards from Quark in a 2x2, the vanilla way of making Glass has been totally removed. FastFurnace and Iron Furnaces are installed and up to date, so it cannot be neither of them. I don't know what else would remove such a simple vanilla mechanic.

Here is a list of the Mods I have removed: https://imgur.com/a/tjsOxZP

In before getting burned for altering the Modpack, yes, go on, I deserve it.

**Comment by murdick** [comment]
glass recipe is in recipes.js file, there are other recipes in this file for mods you have removed. I wonder if the entire file will be ignored if there are too many failures.

Take a look at your client log and see if there are any complaints from kube.js or recipes.js


https://github.com/AllTheMods/ATM-6/blob/862ba4056578da544c7a5416fc16bed4465fff6e/kubejs/server_scripts/recipes.js#L110

**Comment by mkaito** [comment]
We do not offer official support for altering the pack. The expectation is that if you are able and willing to modify the pack, you are also able and willing to do your own troubleshooting. Doesn't mean we won't try to answer questions if we're around on Discord, but this is not a pack issue.
