### ISSUE TITLE
[1.3.7] Some Mystical Agriculture seeds don't grow in garden cloches.

### ISSUE THREAD

**Issue by ashduino101** [AllTheMods/ATM-6#725]
If you try to grow the mystical agriculture seeds for signalum,  manasteel, elementium, terrasteel, blizz, blitz, basalz, signalum, energized steel, blazing crystal, niotic crystal, spirited crystal, or nitro crystal in a garden cloche with any farmland of its tier or above, it won't grow nor render the crop.

Reproduction:
Put insanium (or the seed's tier) farmland in a garden cloche with energy and water in it, and put a seed listed above in.

Expected behavior:
The seeds should grow like all other seeds of their tiers.

Screenshots:
![2021-01-03_19 14 19](https://user-images.githubusercontent.com/67023707/103497961-f8b7fb80-4df7-11eb-93e3-7a1271f48eb8.png)
![2021-01-03_19 14 36](https://user-images.githubusercontent.com/67023707/103497963-fa81bf00-4df7-11eb-97de-d8f3699b13e8.png)

Additional Context:
This also applies to the phytogenic insolator, but with a complete different set of seeds.

**Comment by BovineShaman** [comment]
All of the seeds you have listed are disabled in current versions.
