### ISSUE TITLE
ftb server file error

### ISSUE THREAD

**Issue by bradleydragon** [AllTheMods/ATM-6#726]
ftb server file has an error with all its values, the values are at max for no reason making tpa and other commands have 6 rl day cooldowns. also /home and /back are at zero.

**Comment by mkaito** [comment]
We are in no way related to anything FTB does.

**Comment by bradleydragon** [comment]
um? it has nothing to do with ftb. the MOD from ftb you put in your damn pack that allows tpa and other commands has a misconfigured server file for the SERVER pack you out up. it is 100% YOUR responsibility to configure it correctly.

**Comment by mkaito** [comment]
The mods we put in our "damn" pack are configured the way they are because we want them to be configured this way. This configuration is not "incorrect" simply because you disagree with it.

You can adjust this configuration to your own liking in any way you see fit.

**Comment by thevortex** [comment]
it's not configured incorrectly, this is to encourage you to use the other mods in the pack that provide means of transport, if you are feeling like doing bukkit things, go ahead an enable it for your server, or your damn server, as the case may be
