### ISSUE TITLE
Allthemodium Alloy Paxel unable to get Looting enchantment

### ISSUE THREAD

**Issue by Leyzr** [AllTheMods/ATM-6#728]
Basically title. It can pretty much get every other enchantment from what i've seen otherwise. Looting is just a huge one to lose, sadly...

![looting issue](https://user-images.githubusercontent.com/40078256/103522382-4c523580-4e48-11eb-996a-6c5a4545d11a.png)

**Comment by Smokeymaxamus** [comment]
Also can not Botania mana enchanter it, it doesn't register the book available for use but registers the other books I threw down

**Comment by Leyzr** [comment]
To bypass, you can force it to take the enchantment in creative mode, but that only works if you have access to creative mode.

**Comment by thevortex** [comment]
will look into this, i believe it is a tags issue, should be resolved with next update of allthemodium
