### ISSUE TITLE
Eidolon - Enchanted Ash Recipe Conflicts with Smelting Bone for Bonemeal

### ISSUE THREAD

**Issue by lauash** [AllTheMods/ATM-6#729]
**Describe the bug**
Enchanted ash, which is created by smelting down bones is only possible at the moment in the blast furnace as its the only thing that doesn't produce bonemeal when you put bones in. Every other machine gives bonemeal instead of the ash. Thankfully the one exception allows to get some enchanted ash for but I don't believe that should be the solution.

**To Reproduce**
1. Put bonemeal in any smelting machine
2. Get bonemeal
or
1. Look for the uses of bone in JEI
2. See that every smelter has two recipes for bone

**Expected behavior**
Smelting bone should give enchanted ash. I'm not sure what actually adds the recipe to smelt bone into bonemeal so I don't know what is conflicting.

**Comment by jeremiahwinsley** [comment]
Fixed in 1.4.0.
