### ISSUE TITLE
Sugar cane growth height

### ISSUE THREAD

**Issue by Bimmbamm** [AllTheMods/ATM-6#73]
Hello ATM-Team,
sugar cane and bamboo seem to grow indefinitely. I don't think that's by design. But that way I always find my home again :)

Version: All the Mods 6-0.26a

Greetings Bimmbamm

![sugar cane](https://user-images.githubusercontent.com/12891987/90659796-63034180-e245-11ea-8338-d836e88dca13.png)

**Comment by coffeeordeath** [comment]
this isnt an issue. this is a feature of apotheosis

**Comment by Bimmbamm** [comment]
Seems legit. Thanks for the answer :)

**Comment by WhitePhant0m** [comment]
Intended, Closing.
