### ISSUE TITLE
Save and Quit to Title Takes Me to Multiplayer Server List

### ISSUE THREAD

**Issue by lauash** [AllTheMods/ATM-6#730]
**Describe the bug**
Basically the title, whenever I quit to title it seems to put me in the server list menu.

**To Reproduce**
1. With a save open, click save and quit to title button

**Expected behavior**
Should take me back to main menu

**Comment by ariosos** [comment]
I think this is more of a Minecraft UI lag bug, as I've had this happen in other modpacks over the years. It usually happens if I move the mouse and doubleclick as just the right moment when the game is between shutting down the save and going to the menu.

**Comment by lauash** [comment]
Well I've only experienced since I updated to 1.3.8 and 1.3.9. It has never not happened since updating, even if I alt-tab as soon as I click the button and I've never clicked twice.
