### ISSUE TITLE
Biome ID's run amuck

### ISSUE THREAD

**Issue by Smokeymaxamus** [AllTheMods/ATM-6#731]
**Describe the bug**
Biomes Broke

A lot of custom biomes are mismatched in 
1.3.8, when updating from 1.3.7.

**To Reproduce**
Easy way to see is in Nether or Ratlantis.
1. update from 1.3.7 to 1.3.8
2. travel or nether/ratlantis .
3. see enemies from other biomes in it, and different biome names in the minimap/big map, or the natures compass.
4. profit?

**Expected behavior**
the biome names and mobs that spawn in them to be correct, the grass also changes color.

**Screenshots**
![2021-01-04_09 25 59](https://user-images.githubusercontent.com/38093139/103545340-6c491f80-4e6f-11eb-92fa-ba2ce61ba56f.png)

**Additional context**
lots of people were talking about it in the discord last night.

**Comment by Letoric** [comment]
We're looking into it, however we wouldn't be able to retroactively fix it so you either need to restore from backup and stay on 3.7 while it's diagnosed, or accept the change unfortunately.

**Comment by Smokeymaxamus** [comment]
Reverting even with the same world (not a backup just plopped the world back into 1.3.7) restored the biomes back ratlantis is no longer the other. I was looking into how to correct it and ran across this https://github.com/AllTheMods/ATM-6/issues/437.
