### ISSUE TITLE
1.3.9b - Bag of Yurting Mekanism Factories Crashes the Server

### ISSUE THREAD

**Issue by Xechorizo** [AllTheMods/ATM-6#733]
**Describe the bug**
When using Bag of Yurting on a Mekanism factory (Crusher, Infuser, Enricher, etc.), the server crashes when placing the block against a pipe, tube, or transporter.

**To Reproduce**
1. Use Bag of Yurting on a Mekanism machine (Basic through Ultimate)
2. Use Bag of Yurting to place the machine near a pipe, tube, or transporter.
3. Server crash.
4. Load server after restart and find the block placed as desired, functioning normally.

**Expected behavior**
1. Use Bag of Yurting on a Mekanism machine (Basic through Ultimate)
2. Use Bag of Yurting to place the machine near a pipe, tube, or transporter.
3. Find the block placed as desired, functioning normally.

**Logs**
1. https://pastebin.com/e69rmx5X
2. https://pastebin.com/RvidZjLb

**Update**
Still occurs on 1.3.9b. Seems to allow placement in its original spot, but possibly faces are not expecting the change specifically as it relates to logistical transporters.
https://pastebin.com/ADmgkxuv

**Comment by whatthedrunk** [comment]
If you are still having issues let them know here for it to be blacklisted. Thanks! https://github.com/Commoble/bagofyurting
