### ISSUE TITLE
Server Crashing at startup after 1.3.8

### ISSUE THREAD

**Issue by Andy3link** [AllTheMods/ATM-6#735]
Server will not startup after updating to 1.3.8

Tried to join once it was online, but timed out.

Set the timeout to 600000 ticks and still timed out

When updating i Deleted Jar, mod, config folder on my server. and the server update in multicraft did the hard work

Crash report 4/1 Mod Version 1.3.8
https://pastebin.com/i5KEekv2

***** UPDATE *******

Just updatet to the new 1.3.9b version hoping for the best.

but sadly looked good in the start, but crashed cos wait time it seems, hope that someone could help me with this issue.

Crash Report 5/1 Mod version 1.3.9b
https://pastebin.com/TdgwdmUn

**Comment by xstarlin** [comment]
I am also having a problem with my server starting up after trying to update to the new 1.3.8 version

**Comment by Andy3link** [comment]
> I am also having a problem with my server starting up after trying to update to the new 1.3.8 version

Do u have any crash report ?

**Comment by lessthanzach** [comment]
> 
> 
> -snip-
> https://pastebin.com/i5KEekv2

I'm no expert and I've not completed the update to my server yet, but looking at the crash logs it appears (to me) like 
Apotheosis is trying to parse an ingredient from Psi mod: 
>
>vazkii.psi.api.material.PsimetalToolMaterial.func_200924_f(PsimetalToolMaterial.java:44) ~[psi:1.16-88] {re:classloading}
>
which appears in line 37 of the Psi api at https://github.com/Vazkii/Psi/blob/master/src/main/java/vazkii/psi/api/PsiAPI.java

I know this doesn't offer much.  I hopped through the latest commits and couldn't find much that would seem to be an issue except line 22 from kubejs/server_scripts/u_recipes.js at https://github.com/AllTheMods/ATM-6/commit/62a60593e72699c99b9ab7211f51994827906a7d#diff-cf0e3eb6250c6b4eef8aa02b1684a97ddddd12e7d61af0920a59e9af9a5c287a 
Apologies, I'm pretty new to Github so I don't know if any of this actually helps the author find the cause or if this is even formatted in a helpful way.

**Comment by mkaito** [comment]
Seems like Apotheosis crashes on startup for some people, but only every other startup. Puzzling.

**Comment by derrickmehaffy** [comment]
Likely related, was an issue with Psi and not Apotheosis: https://github.com/Shadows-of-Fire/Apotheosis/issues/255

**Comment by Andy3link** [comment]
So could u just remove psi and it would work ?

**Comment by Andy3link** [comment]
Latest Error Msg : 05.01 11:35:21 [Server] Server Watchdog/FATAL A single server tick took 60.00 seconds (should be max 0.05)
05.01 11:35:21 [Server] Server Watchdog/FATAL Considering it to be crashed, server will forcibly shutdown.
05.01 11:35:22 [Server] Server Watchdog/FATAL [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 53417e90-574a-421a-8e13-c345096c6e42
