### ISSUE TITLE
No recipe for compact machine tunnels

### ISSUE THREAD

**Issue by ashduino101** [AllTheMods/ATM-6#736]
There is no recipe for any of the compact machine tunnels.

There should be a recipe, perhaps 4 Mekanism logistical transporters with a compact wall in the center, and that inverted for the other item tunnel. For the redstone tunnel, perhaps a compact wall surrounded with 4 redstone.

**Comment by Pdiddy973** [comment]
the tunnels do are not yet implemented 
 please see the [mod page](https://www.curseforge.com/minecraft/mc-mods/compact-machines)
