### ISSUE TITLE
Biome changes in 1.3.8 update

### ISSUE THREAD

**Issue by KaiHD** [AllTheMods/ATM-6#738]
_**Describe the bug**_
My base is located in the Guiana Clearing/Shield Biome. Following the most recent update, the Biome's have now changed from Guiana Clearing to Seasonal Deciduous Forest and Guiana Shield to Enchanted Grove.
Other vanilla biomes around look to be normal so possibly an issue with BYG Biome ID's.

_**To Reproduce**_
(Unsure if this will reproduce however have noted on discord that others have had the same issue however had no response as to what may cause this)
1. Locate Guiana Clearing/Shield in 1.3.7
2. Update to 1.3.8
3. Biome has now changed to Seasonal Deciduous Forest and Enchanted Grove

_**Expected behavior**_
Would not expect biome to change following update.

**Screenshots Attached**

**Version 1.3.8**
![ATM6 v1 3 8](https://user-images.githubusercontent.com/76951153/103580820-c29b7a00-4ed2-11eb-9bb2-907316c6d22b.png)

**Version 1.3.7**
![ATM6 v1 3 7](https://user-images.githubusercontent.com/76951153/103580829-c5966a80-4ed2-11eb-9c88-2db3ce35dc3e.png)

**Comment by Letoric** [comment]
Same issue as #731. We're looking into it, however we wouldn't be able to retroactively fix it so you either need to restore from backup and stay on 3.7 while it's diagnosed, or accept the change unfortunately.

**Comment by KaiHD** [comment]
No worries, I’ve back dated for the time being and will keep an eye out for an update

**Comment by mkaito** [comment]
Closing this as duplicate.
