### ISSUE TITLE
Server lag avrage 8 tps only when mobs enabled

### ISSUE THREAD

**Issue by codydbgt** [AllTheMods/ATM-6#742]
i have a few spark profiles and cant understand what mod could cause vnilla to have so much lag. when i disable mob spawning with the /gamerule doMobSpawning server tps goes to 20 no issues. i would prefer if i could keep mobs 👍 
these are over the corse of days of testing

https://spark.lucko.me/#mVP7kcKNub
https://spark.lucko.me/#87bXmzYW9q
https://spark.lucko.me/#JMl2iBSnvS

**Comment by ViRb3** [comment]
There isn't anything particular causing your lag, it's all the mobs collectively. Seems like your server is just not powerful enough.

**Comment by codydbgt** [comment]
this isnt good enough? i have 64gb of ram too? what do i need to run this pack an overclocked cpu on ice? 
![image](https://user-images.githubusercontent.com/1176479/104135066-a2007380-535b-11eb-9910-7e0573e17aff.png)

**Comment by ViRb3** [comment]
Liquid nitrogen will probably have a better effect ;)

Jokes aside, Minecraft doesn't really benefit from having many cores, most of the work is performed only on one thread on one core. What you need is a CPU with a very fast single-thread performance (high clock speed). Apart from that, there are many things you can do to improve the performance:
- Reduce mob spawns
- Remove all background running apps
- Have a dedicated server
- Play with JVM arguments

Unfortunately I can't help further than this, but if anybody else has something to add, feel free. Good luck!
