### ISSUE TITLE
World not loading

### ISSUE THREAD

**Issue by rique702** [AllTheMods/ATM-6#743]
So I can’t load back into a world I’ve been playing. Last time I remember playing I was in the end fighting the ender dragon. I had to leave so I alt f4 my way out and didn’t end up saving the game properly. Whenever I try to load the world it gets past the reading world data and then goes completely blank on the maroon background until it says not responding. In order to close it I have to use task manager. I get no error code when I close it.

**Comment by whatthedrunk** [comment]
If your still having the issue let us know your system specs and how much ram you are using. Newer versions should require less but it still takes a long time to load into worlds.

**Comment by RedRain2** [comment]
im having same problem
