### ISSUE TITLE
FTB Ultimine/ Cyclic Ore excavate crash

### ISSUE THREAD

**Issue by Bender8887** [AllTheMods/ATM-6#744]
**Describe the bug**
When mining red bituminous sand with a pickaxe one was a vanilla netherite pick and the other was a silent gear unobtanium pick one had ore excavate V from cyclic the other was ore excavate VIII from cyclic if you use the ATM excavate alongside it it will cause a crash

1. Apply cyclic ore excavate to pickaxe
2. Find/spawn in a vein of red bituminous sand
3. Hold ATM ore excavate key and mine the vein with previously mentioned pickaxe 
4. Game will hard crash with exit code 0

**Expected behavior**
Game crashes

**Edit**
Do not try and reproduce this bug on a world you want to save without backing up you have to roll back once attempting and crashing.

**Comment by Smokeymaxamus** [comment]
The button press excavate is from https://www.curseforge.com/minecraft/mc-mods/ftb-ultimine which is in the modpack.

**Comment by Bender8887** [comment]
yeah sorry that is correct

**Comment by jeremiahwinsley** [comment]
Fixed in Cyclic 1.1.1 which will be in the next pack update

**Comment by jeremiahwinsley** [comment]
Fixed in 1.4.0.
