### ISSUE TITLE
Mountains are flat

### ISSUE THREAD

**Issue by Smokeymaxamus** [AllTheMods/ATM-6#746]
**Describe the bug**
Mountains are flat. in a new and previous worlds newly generated chunks 1.3.9b

**To Reproduce**
1. load new world
2. use natures compass to find vanilla minecraft mountains
3. fly there, and find them flattened
4. profit?

**Expected behavior**
Not to be flat?

**Screenshots**
![2021-01-05_09 09 15](https://user-images.githubusercontent.com/38093139/103656237-5c484300-4f36-11eb-9220-11600d048204.png)

**Additional context**
Nope.

**Comment by ashduino101** [comment]
Did you load the world using shaders?

**Comment by DrSyndicate** [comment]
I can confirm this happened without shaders on the server my friends and I are running.

**Comment by InfidelGB** [comment]
I have also had the same issue brand new download of All the Mods 1.3.9b new world created with BOP and default generation in single player with no shaders.

**Comment by ashduino101** [comment]
I'm actually also having this issue
