### ISSUE TITLE
Most ores cant be processed with ore tripling, quadrupling and quintupling with Mekanism

### ISSUE THREAD

**Issue by pratnayake** [AllTheMods/ATM-6#747]
**Bug**
Ore shards, ore clumps and ore dust from All The Ores dont seem to have any recipes which leads to a lot of ore tripling, quadrupling and quintupling systems non-functional as processing doesnt occur anymore

**Comment by Dextryan** [comment]
The craft just doesn't show up, but the machines process it.
The bug is with JEI, not Meka

**Comment by pratnayake** [comment]
> The craft just doesn't show up, but the machines process it.
> The bug is with JEI, not Meka

When I got osmium crystals, it would not allow me to process it. Same thing happened with uranium.

**Comment by pratnayake** [comment]
I tested with uranium, placed uranium ore in a purifying factory and the result (Uranium Clump) cant be placed in a crushing factory anymore.

**Comment by Letoric** [comment]
This is closed in later versions of the pack that are properly updated.
