### ISSUE TITLE
[1.3.9] Many pulverizer recipes are missing since JAOPCA was removed.

### ISSUE THREAD

**Issue by GloriousAlpaca** [AllTheMods/ATM-6#748]
The Thermal Series Pulverizer is no longer able to pulverize Platinum, Zinc, Allthemodium, Unobtainium, Vibranium, Sky Stone, Ender Pearls, Fluix Crystals, Certus Quartz, Coal, Crimson Iron and Azure Silver.

**Comment by Dextryan** [comment]
This seems to be simmilar to #747, which doesn't have a recipe in JEI but machines are actually able to do. Have you tested it?

**Comment by GloriousAlpaca** [comment]
I have only tried Fluix Crystals so far, but they would not allow me to place them in the pulverizer.

**Comment by apeiou** [comment]
I have noticed the recipes for Bronze, Copper, Constantan are missing, don't know if any more are as well, tried checking it and didn't find any more irregularities.
