### ISSUE TITLE
Industrial Foregoing Plant Gatherer Recipe Issue

### ISSUE THREAD

**Issue by Rumaan3012** [AllTheMods/ATM-6#750]
**Description**
The Industrial Foregoing Plant Gatherer does not seem to accept a vanilla Iron Axe as a valid part of the recipe. Everything I can see in JEI points towards just needing a vanilla Iron Axe, but it does not complete the recipe, nor does manually making the recipe solve the issue. A new axe does not fix it either.

**To Reproduce**
Attempt to make a Plant Gatherer.
Will not accept Iron Axe as valid component.

**Expected behavior**
Recognizes the vanilla Iron Axe as a valid part.

**Comment by jeremiahwinsley** [comment]
Tested in 1.3.9 in vanilla crafting table and cannot reproduce, assuming fixed.

**Comment by Rumaan3012** [comment]
Issue not resolved in live ATM6 server. Vanilla crafting table used, Axe still not accepted.

**Comment by Rumaan3012** [comment]
Issue was resolved.
