### ISSUE TITLE
(1.3.9) Mekanism Clumps not processing 

### ISSUE THREAD

**Issue by Llama1100** [AllTheMods/ATM-6#751]
The clumps don't seem to be processing in the crusher for ore tripling, seems like it could have been from the removal of JAOPCA.
The clumps default to "alltheores" clumps and will not process.

**Comment by ariosos** [comment]
See https://github.com/AllTheMods/ATM-6/issues/739
I added a descriptive report on it - basically, finish the mekanism processing in a previous version so that all ores and fluids are gone, then copy your save to a new instance (or update).

**Comment by Rithenar** [comment]
That doesn't fix the issue. New ores being mined cannot be processed by Mekanism either. The clumps created on a X3 setup are ATM clumps except for Iron which is processed as a Mekanism clump.

**Comment by Letoric** [comment]
A properly updated system can process all of the ores through Mek 5x, 4x, 3x, 2x, and 1x. If they are not processing for you still, you have not followed the update process and need to revisit that.
