### ISSUE TITLE
Alltheores dont pulverize in the thermal pulverize 

### ISSUE THREAD

**Issue by Kyxlis** [AllTheMods/ATM-6#752]
**Describe the bug**
Previous versions allowed thermal series pulverizer to crush ores but longer contains any recipes to do so with alltheores
**Expected behavior**
Ore to pulverize
**Additional context**
running 1.3.9 not 1.3.9b

**Comment by whatthedrunk** [comment]
https://github.com/AllTheMods/ATM-6/issues/752
