### ISSUE TITLE
Server World not loading

### ISSUE THREAD

**Issue by craveful** [AllTheMods/ATM-6#755]
Hi, I updated to 1.3.9b last night and it worked fine and my server launched perfectly after the first load and me and my friend were good but after I used the black plague scythe and my server crashed and now we cannot log in to it even though it is up. The error code is "An unexpected issue occurred and the game has crashed. were sorry for the inconvenience. Exit code:0 Everytime I left click the server crashes not sure what it is but I will revert back to my previous version.

**Comment by craveful** [comment]
https://gist.github.com/craveful/e6869f21a2ffe637c9c591e58dc826a0

**Comment by mkaito** [comment]
This looks like a problem in the rats mod. Could you please report it to [their github](https://github.com/Alex-the-666/Rats/issues)? Check for duplicates.

**Comment by mkaito** [comment]
Looks related to this https://github.com/Alex-the-666/Rats/issues/514
