### ISSUE TITLE
[1.3.9] There are two Bronze Ingots 

### ISSUE THREAD

**Issue by GloriousAlpaca** [AllTheMods/ATM-6#756]
There are two Bronze Ingots from Mekanism and Thermal Series, the Thermal Series Induction furnace can only create Mekanism Bronze but you can't find the Mekanism Bronze in Jei, as it only shows the Thermal Series Bronze.

**Comment by Letoric** [comment]
You can modify unify.js and replace
unifyCraftMetal('bronze', 'mekanism:ingot_bronze', 'mekanism:dust_bronze', 'mekanism:block_bronze', 'mekanism:nugget_bronze');
with
unifyCraftMetal('bronze', 'thermal:bronze_ingot', 'thermal:bronze_dust', 'thermal:bronze_block', 'thermal:bronze_nugget');
