### ISSUE TITLE
Chunk Loading

### ISSUE THREAD

**Issue by PapaBaal** [AllTheMods/ATM-6#757]
So I just made a Big Reactor and have connected it to a flux point, but when i leave the area, it stops generating?
Any idea how to solve this?

**Comment by PapaBaal** [comment]
Or it seems that the Flux point stops sending power, but I've already connected it to places a fair distance away with no issue, then it all of a sudden stopped?

**Comment by Pdiddy973** [comment]
Is everything chunk loaded?

**Comment by Pdiddy973** [comment]
You need to claim chunks then shift click/drag to chunk load...you should have a red hash on the chunks that are loaded

**Comment by PapaBaal** [comment]
Brilliant! The guides i looked at said it was lft-ctrl, Thank you!
