### ISSUE TITLE
Error loading data packs since last update

### ISSUE THREAD

**Issue by Tomowori** [AllTheMods/ATM-6#758]
![image](https://user-images.githubusercontent.com/76424177/103705316-7f650800-4fb3-11eb-86c5-fd2d3527f84e.png)

**Comment by mkaito** [comment]
We can not do anything about this without full logs. Please post your `debug.log` as well as `latest.log`.

**Comment by Tomowori** [comment]
[2021-01-05-2.log](https://github.com/AllTheMods/ATM-6/files/5775792/2021-01-05-2.log)
[latest.log](https://github.com/AllTheMods/ATM-6/files/5775793/latest.log)

i'm not sure where to find the debug.log file, but these are the the 2 logs i found

**Comment by GordonHollow** [comment]
Has the same problem after updating to latest ATM.
 Here is the logs. Yes, it's with optifine enabled, but i try disable optifine\optiforge - the same logs goes anyway with the same loading datapacks error. I also try disable BoP - the same problem continue.

Also i try to create new world and after normally generates world, close it and try to open this again - has the same error and logs anyway.

**Comment by GordonHollow** [comment]
logs:

**Comment by Tomowori** [comment]
@GordonHollow do you mind telling me how you found the debug.log file? thanks!

**Comment by GordonHollow** [comment]
It just lays the same logs folder as a latest.log

**Comment by Tomowori** [comment]
it's not there for me
![image](https://user-images.githubusercontent.com/76424177/104094012-faba0880-5296-11eb-80a1-3dabae920a10.png)

**Comment by mkaito** [comment]
Almost certainly means your update/install went wrong, and you just need to do it again.

**Comment by Tomowori** [comment]
I uninstalled it and now when I try to install it back, I keep getting errors like this for different mods, while downloading
![image](https://user-images.githubusercontent.com/76424177/104226289-39df8980-5450-11eb-8757-4f5d0727e095.png)

**Comment by GordonHollow** [comment]
Well, i try to reinstall twice.

Also between this reinstalls, i change my PC and cause of that - install new clean windows...

So nothing changes

**Comment by thevortex** [comment]
make sure the jaopca mod has been removed from the mods folder. curse did not remove it during the update for some people it seems

**Comment by GordonHollow** [comment]
Checked JAOPCA - it's not here anymore, no this old files in mod folder

**Comment by Tomowori** [comment]
it finally worked after fully reinstalling the game 
![image](https://user-images.githubusercontent.com/76424177/104491746-56f49380-55db-11eb-8cff-fdc8f24c2719.png)
