### ISSUE TITLE
[1.3.9] ResourcefulBees - Bees wont enter Beehives greather than Tier 1 after collecting pollen

### ISSUE THREAD

**Issue by F0x06** [AllTheMods/ATM-6#761]
**Describe the bug**
Bees wont enter Beehives greather than Tier 1 after collecting pollen, i tested with the latest version of the mod `1.16.4-0.5.8b` released 8h ago and issue is still present, hovever using a clean minecraft instance with only JEI + ResourcefulBees everything is working fine.

**To Reproduce**
1. Place some flowers
2. Place any Beehive greather than Tier 1
3. Spawn some Bees
4. Wait for bees to collect pollen and they will fly around without enterning the Beehive

**Expected behavior**
Bees should enter Beehive after collecting pollen

**Related issues**
* https://github.com/Resourceful-Bees/ResourcefulBees/issues/110
* https://github.com/Resourceful-Bees/ResourcefulBees/issues/111

**Comment by F0x06** [comment]
Apparently after some time like 5-10m bees entered the beehive all all is working fine now, closing for now, however you need to update the mod to `1.16.4-0.5.8b` asap to fixe the issue.

**Comment by Jaymus3** [comment]
This issue should be reopened as it's still an issue with the bees.  They inconsistently enter/don't enter their apiaries due to a change in more recent versions of forge.

**Comment by fEdlbV9IdW50ZXJ8** [comment]
I am also having this issue. it happens when a beehive is broken while the bee inside has pollen
