### ISSUE TITLE
Please add Reload Audio Driver

### ISSUE THREAD

**Issue by ChaoticNonsense** [AllTheMods/ATM-6#762]
**Is your feature request related to a problem? Please describe.**
It is maddening to boot up your client with audio through your speakers, and then have to completely relaunch if you want to switch over to headphones; something that happens often when wanting to jump on a server discord.

**Describe the solution you'd like**
Add the mod "Reload Audio Driver (RAD) [Forge]" to the pack. It fixes the problem with a quick F3+R

**Describe alternatives you've considered**
Pretty sure it's clientside only, so I can just add it myself, but I think many players will appreciate its additon.

**Additional context**
Link to its curseforge page https://www.curseforge.com/minecraft/mc-mods/reload-audio-driver-rad

**Comment by ViRb3** [comment]
Since this is a mod, please add it to the [Mod suggestion issue](https://github.com/AllTheMods/ATM-6/issues/144).
