### ISSUE TITLE
Pure crystal seeds from AE2 despawn before fully growing

### ISSUE THREAD

**Issue by mkaito** [AllTheMods/ATM-6#765]
**Describe the bug**
When dropped into water without growth accelerators, growth takes a long time. The seeds despawn before this process is fully complete. I was not able to reproduce this on a clean instance with only AE2, so there's likely some mod interaction at work.

**To Reproduce**
1. Drop pure seeds in water
2. Wait

**Expected behavior**
Seeds should grow to completion after a (fairly long) time.

**Comment by mkaito** [comment]
Confirmed to be caused by https://www.curseforge.com/minecraft/mc-mods/configurable-despawn-timer

**Comment by jeremiahwinsley** [comment]
Fixed in 1.4.0.
