### ISSUE TITLE
Bulk item filter duplication bug

### ISSUE THREAD

**Issue by DraTrav** [AllTheMods/ATM-6#766]
**Describe the bug**
The bulk item filter from modular routers can be used to mass duplicate items

**To Reproduce**
1. Go to the bulk item filters inventory
2. put what ever item you want duplicated in
3. press extract
4. items are duplicated

**Expected behavior**
items should disappear and not be duplicated 

**Screenshots**
If applicable, add screenshots to help explain your problem
![2021-01-06_23 11 49](https://user-images.githubusercontent.com/42803478/103853830-97e92700-5074-11eb-81db-665ca22f8008.png)
![2021-01-06_23 11 56](https://user-images.githubusercontent.com/42803478/103853833-99b2ea80-5074-11eb-93f6-777f744c3706.png)

**Additional context**
the screenshots where taken fully in survival

**Comment by BovineShaman** [comment]
Extract button no longer exists.
