### ISSUE TITLE
integrated dynamics: cannot read list of recipes from crafting tables / machines

### ISSUE THREAD

**Issue by boneskull** [AllTheMods/ATM-6#768]
**Describe the bug**

A Machine Reader is unable to read recipes when facing a crafting table (or crafting machine of any sort).

**To Reproduce**

1. Create a Crafting Table
2. Place a Machine Reader targeting the Crafting Table
3. Right-click on Machine Reader and scroll down to "Recipes"

I can't get recipes from _any_ machine I've tried.

**Expected behavior**

I am not sure, but the list should not be empty. Importantly, "is recipe handler?" should _not_ be `false`.

This prevents ID from querying the ingredients for a crafting recipe; e.g., via a "recipe by output" aspect. 

**Screenshots**

The problem in the UI:

![2021-01-07_01 13 19](https://user-images.githubusercontent.com/924465/103874237-c91e2300-5085-11eb-9541-74596cd6945a.png)

Example setup:

![2021-01-07_01 14 14](https://user-images.githubusercontent.com/924465/103874243-cc191380-5085-11eb-992d-7d95554b6e5f.png)

**Additional context**

I found this while going through ID's tutorials.

Someone has reported something similar before: https://github.com/CyclopsMC/IntegratedDynamics/issues/936; but the mod author suggests it may be a conflict somewhere.

**Comment by whatthedrunk** [comment]
Dev says this should work. If its still broken let me know and ill reopen and try to reproduce it.
