### ISSUE TITLE
x.27 - U Keybound to a Chunk status/loader Window

### ISSUE THREAD

**Issue by Muxwizard** [AllTheMods/ATM-6#77]
There seems to be a universal keybind for U to bring up a chunkloader window, even when using JEI it will intercept U and load the chunkloader window. It will eventually cause a local kick if using the server.

I tried clearning all Control keybinds for U, but still unable to determine what addon this is.

**Comment by WhitePhant0m** [comment]
It's Crash Utilities, change its bind from Ctrl + U to something else you'll rarely use, mine is set to numpad 0

**Comment by Muxwizard** [comment]
![Annotation 2020-08-20 150020](https://user-images.githubusercontent.com/31088944/90819678-e2e8e480-e2f5-11ea-90f0-c0bdf2d79afa.png)

![Capture](https://user-images.githubusercontent.com/31088944/90819831-175ca080-e2f6-11ea-8395-ad2171a6a6e4.JPG)

I changed to to CTRL+U which works, but im also getting it with U still as well. This is happening both on server and local world.

**Comment by WhitePhant0m** [comment]
This seems to be fixed for the 1.16.2 version of crash utilities, so this will be fixed when we update to 1.16.2.
