### ISSUE TITLE
ElementalCraft Pure Chunks Can Only Be Smelted (Can't input in purification Mek machine to 3x)

### ISSUE THREAD

**Issue by lauash** [AllTheMods/ATM-6#771]
It seems the recipe to process the chunks from ElementalCraft through a purification chamber/factory is gone. I tried to do it as well and it wouldn't work. I've done a fresh install of the newest version and witnessed the same issue. Could be related to #751 or #748 but I'm not entirely sure.

**To Reproduce**
1. Look at the uses of any chunk from the ElementalCraft mod, no uses other than smelting it. 
2. Look at the uses of the purification factory from Mekanism, only shows ores and shards. 
3. Take a pure ore chunk from EC and try to put it into the purification factory.

**Expected behavior**
There was a way to take these chunks and put them into the purification block from Mekanism to get more output, the recipe is shown in this video which is from an older version : https://cdn.discordapp.com/attachments/726665656854118481/796794667295309864/path1.mp4

**Comment by TBoshoven** [comment]
Yeah seems this is related to the removal of JAOPCA.
I haven't updated yet, but I just built an ore sextupling plant using this so I guess I'll hold off for a little longer.
