### ISSUE TITLE
Rejoin-Crash

### ISSUE THREAD

**Issue by krabbbbe** [AllTheMods/ATM-6#772]
Microlags apperaing every 3-5 seconds then having a freeze Frame

 1. Start a Singleplayer World
 2. Play for a while then save and exit the game
 3. rejoin/reload the Singleplayer Game
  -> When playing microlags appear

Microlags disappear after restarting the game.

**Comment by whatthedrunk** [comment]
Which version are you playing and are you still having the issue?

**Comment by krabbbbe** [comment]
Version: 1.3.9b, yes the issue is still occuring

**Comment by krabbbbe** [comment]
Bug Fixed with V: 3.1.4
