### ISSUE TITLE
[1.3.9b] Silicon Seeds not craftable in Infusion Altar

### ISSUE THREAD

**Issue by Joly0** [AllTheMods/ATM-6#775]
**Describe the bug**
Silicon seeds are not created when placing the needed items in the Infusion Altar

**To Reproduce**
1. Place Infusion Altar and Infusion Pedestals
2. Place 4 Prudentium Essence in each direction on a Pedestal
3. Place Prosperity Seed Base in the middle
4. Activate by applying redstone signal

**Expected behavior**
Silicon Seed gets created

**Screenshots**
![grafik](https://user-images.githubusercontent.com/13993216/103969753-ef67bf80-5166-11eb-8886-a32a7d93bc21.png)

**Comment by Joly0** [comment]
In addition to that, it is craftable, but one have to place silicon in each corner aswell, which the recipe in jei is not showing. Maybe it might be good to look over the recipes that only need the base seed and some kind of essence to check, if something else is needed to create the seed thats supposed to be created and edit the recipe so jei shows the correct one.

**Comment by GizmoTheGreen** [comment]
Same issue with signalum. 
Tried recipe as shown in JEI (just prosperity seeds and imperium essence) which didn't work obviously.
it doesn't show the signalum (ingots or blocks) but I guessed it was needing ingots and it worked to craft.
![2021-01-10_12 20 32](https://user-images.githubusercontent.com/1146558/104121404-45db2680-533e-11eb-8d09-7d74a618bbe3.png)

**Comment by Segaja** [comment]
The same goes for Fluix seeds.

**Comment by WhitePhant0m** [comment]
As people have mentioned, it's a visual bug, use the material it SHOULD use, not just air...

**Comment by NightFallLegacy** [comment]
Does anyone know where I could reference the full recipes for the seeds that have partial recipes in JEI
