### ISSUE TITLE
[1.3.9] Quartz- and Fluix Seeds cannot be grown in the Phytogenic Insulator

### ISSUE THREAD

**Issue by GloriousAlpaca** [AllTheMods/ATM-6#776]
Most Mystical Agriculture Seeds are supported by the Thermal Series Phytogenic Insulator, would it be possible to add support for the Quartz- and Fluix Seeds?

**Comment by Smibbix** [comment]
Those aren't really plant seeds though. They're seed crystals. It wouldn't make sense for them to grow in a plant growing machine.
