### ISSUE TITLE
No recipe for Silken Tofu

### ISSUE THREAD

**Issue by ashduino101** [AllTheMods/ATM-6#779]
There is no recipe for silken tofu, disabling alternatives to meat, cheese, and cream (since those are harder to automate), it would make more sense to add KubeJS for it or just change the forgedictionary for it.

**Comment by Rithenar** [comment]
I spoke with some folks at Pam's Discord Server and was stated that this is a rare bug that comes up from time to time. It was recommended to try any of the following:

1- Use cooking for blockheads recipe table (confirmed it doesn't work)
2- Install Polymorph (we already have it)
3- Optifine bug (not in my case)
4- Update Forge to the latest version

The last option is the only one I haven't tried as I don't want to break something else.
