### ISSUE TITLE
Garden Cloche broken

### ISSUE THREAD

**Issue by GeYoo** [AllTheMods/ATM-6#78]
In the new Uptate the Garden Chloche doesn't work. I replaced it and it still doesn't work.

**Comment by Bimmbamm** [comment]
I have the same problem. All chloches stopped woking. There are also no recipes for the essences since 0.27 anymore.

**Comment by WhitePhant0m** [comment]
Since this issue was about Cloche recipes missing and that had been fixed, I'll be closing this.
