### ISSUE TITLE
Chisels and Bids place only evy othre pixel 

### ISSUE THREAD

**Issue by herniklanger** [AllTheMods/ATM-6#782]
whny I try to bild with bids from Chisels & Bids will it only place the bid evy othere layer.

To Reproduce
1. Get eany bids
2. Then try to plave them one by one or in blocks sheats
(This is in All the Mods 6)

Expected behavior
The bids whill be pleast evy pixels in instead of evy othere.

Images:
![Chisels   Bids Layer bug](https://user-images.githubusercontent.com/42315828/104076075-2a283100-5215-11eb-8958-66b5a557c9ea.png)

**Comment by whatthedrunk** [comment]
This seems to be fixed. Let me know if you are still having the issue on 1.5.0
