### ISSUE TITLE
[1.3.9b] Nether Loop

### ISSUE THREAD

**Issue by AAmingGaming** [AllTheMods/ATM-6#783]
**Describe the bug**
When leaving the nether (doesn't happen when entering) the player gets stuck in a loop of going through the portals and cannot leave. Often the Player dies from suffocation damage or burning in a lava lake when no lava is near the nether portal. While this is happening on a friend hosted dedicated server the player's ping temporarily spikes as they are stuck in the portal loop, returning to its usual low any other time playing.

**To Reproduce**
Steps to reproduce the behaviour:
1. Using All the Mods 6-1.3.9b
2. Enter the Nether
3. Leave the Nether

**Comment by WhitePhant0m** [comment]
Does the player happen to have a DarkUtils portal charm?
![image](https://user-images.githubusercontent.com/33400200/104110468-b0f61000-52e0-11eb-8afe-1edd25b15599.png)
I've had it cause the same issue sometimes.

**Comment by AAmingGaming** [comment]
Nope it happens when there is nothing in the Inventory at all

**Comment by thevortex** [comment]
This happened to me as well on 1.3.7 during the issue when player died the grave was set to the overworked coords but in the  nether no charms etc either

**Comment by AAmingGaming** [comment]
> This happened to me as well on 1.3.7 during the issue when player died the grave was set to the overworked coords but in the  nether no charms etc either

How did you manage to get past the issue or did it resolve itself when u updated?

**Comment by thevortex** [comment]
Haha it resolved itself when I finally died lol haven't experienced it since but had to travel pretty far to get my stuff back lol

**Comment by whatthedrunk** [comment]
Haven't seen this recently. If it's still happening in 1.16.5 let me know
