### ISSUE TITLE
[Last version] Dont to craft inferium seed tier 2

### ISSUE THREAD

**Issue by oatgh** [AllTheMods/ATM-6#785]
**Describe the bug**

**To Reproduce**
1. take a inferium tier 1 seed
2. Use in a crafting table eight prudentium and inferium tier 1 seed 
3. The craft dont have a result

**Expected behavior**
Is expected what this crafting give us a inferium seed tiers up

**Screenshots**
![2021-01-09_15 23 15](https://user-images.githubusercontent.com/41549075/104105712-c2aec780-528e-11eb-835e-45c17a53ed78.png)

**Additional context**

**Comment by Pdiddy973** [comment]
I don't believe MA uses tiered seeds anymore, they use the tired soil.either way this should go to the mods GitHub, not the packs.

**Comment by WhitePhant0m** [comment]
as @Pdiddy973 said, MA doesn't have tiered seeds anymore, soils give better outputs. Read the book.
