### ISSUE TITLE
Clock does not get added to crafting Terminal using AE2/JEI

### ISSUE THREAD

**Issue by jmac460** [AllTheMods/ATM-6#786]
**Describe the bug**

**To Reproduce**
1. Go to a recipe with a clock
2. Click on the + to add to crafting terminal
3. Clock does not get added

**Expected behavior**
Add clock to the crafting terminal as a part of recipe's

Version: LATEST

**Comment by jeremiahwinsley** [comment]
Cannot reproduce this on 1.3.9b. With a Crafting Terminal connected to an ME Drive containing one storage cell, as long as the materials are present in either player inventory or storage, JEI adds them to the AE2 crafting grid.

**Comment by jmac460** [comment]
https://user-images.githubusercontent.com/34420502/104139084-8fdc0080-536e-11eb-87dd-256537443cd3.mp4

Hey there, re-opening this with video of it not moving correctly.

**Comment by jeremiahwinsley** [comment]
Thanks for the video, I was able to reproduce this. Reported here: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4930

**Comment by jmac460** [comment]
Thank you for looking back at it, I appreciate the support and time taken to respond.

**Comment by jeremiahwinsley** [comment]
This Quark feature has been disabled in 1.4.0.
