### ISSUE TITLE
Get Nothing When Breaking a Mystical Agriculture Crux

### ISSUE THREAD

**Issue by lauash** [AllTheMods/ATM-6#796]
Title basically, if you go to break a crux from the Agradditions mod it just disappears. 

**To Reproduce**
1. Place crux, and mine it back up.

**Expected behavior**
Breaking a crux should drop it.

**Comment by jeremiahwinsley** [comment]
Confirmed for Nitro Crystal Crux, PR here: https://github.com/BlakeBr0/MysticalAgradditions/pull/63
