### ISSUE TITLE
Mod Suggestion: Shift n Scroll on Mac

### ISSUE THREAD

**Issue by desagas** [AllTheMods/ATM-6#797]
This mod allows MAC users to finally be able to shift and scroll together. This issue has prevent us Mac users from being able to use Dank Storage, FTB Ultimine, and every other mod that hard cords SHIFT as a way to alter some setting. So, it is finally fixed. Given the number of downloads your packs have, I would imagine a huge number are mac users.

A mod that a lot of people have been waiting for for a very long time. It has zero compat issues to my knowledge with anymods that currently exist on forge, and, it is client side only, but will work fine when install on the server, it just won't do anything there. Personally, I have tested on both MAC and PC servers and clients, and they all work perfectly fine, on ATM6 1.3.9b.

https://www.curseforge.com/minecraft/mc-mods/shift-n-scroll-on-mac/files

It can be used on both servers and clients without any crashes, but only requires to be on the client side, server side does nothing at all. ALSO, it can be installed on ALL systems, not just MACOS systems, with no issues.

**Comment by desagas** [comment]
I take that back, I clearly broke something. Ill mention it again after a bit more texting. It is stranged, it was working, and now it is now. Back to the drawings.

**Comment by desagas** [comment]
I have fixed the issue. It was related to obfuscation causing an issue. It will not fix ALL scroll related issues for MAC users! Including FTB Ultimine, and DAnk Storage.

https://www.curseforge.com/minecraft/mc-mods/shift-n-scroll-on-mac

**Comment by WhitePhant0m** [comment]
All mod suggestions should go into #144 but I'll forward this.

**Comment by desagas** [comment]
Thank you, sorry. I didn't see that. :)
