### ISSUE TITLE
Requesting a Fork without ATM ores / other

### ISSUE THREAD

**Issue by Sanguinely** [AllTheMods/ATM-6#798]
Requesting a fork

Currently the ATM ores unbalance the pack and make it un-fun. I happened upon some pigmen and by chance got some allthemodium boots from them. which essentially made me unkillable to all mobs. aside from dragons. which are only found in the other. which i found causes tps to lower on my server just having the other in my world/being inside it. also, potionmaster causes fps lag when used. I removed that as well which i can do without a problem but the main issue is that the ATM ores are permeating every other mod for no good reason. this isn't an expert pack, why are the recipes changed?

**Describe the solution you'd like**
A fork without the changes to recipes requiring the ATM ores, removal of the other and removal of Ice and Fire changes

**Describe alternatives you've considered**
Removal of the mods made by thevortex causes errors because recipes were changed

**Comment by thevortex** [comment]
bye Fm, we asked you to leave the discord we are not engaging any further with you.
