### ISSUE TITLE
Suggestions to server setup

### ISSUE THREAD

**Issue by have-a-boy** [AllTheMods/ATM-6#80]
The current server setup file includes ReAuth, which has no server-side functionality, but excludes Xaero's World Map, which does offer optional server-side functionality. Perhaps the two could be reversed? There may also be other client-only mods in the server setup, though I have not checked.

**Comment by WhitePhant0m** [comment]
I've added ReAuth to the blacklist for mod downloads on the server files, and removed Xaero's from it but Xaero's will probably be removed in favor for FTB Chunks map
