### ISSUE TITLE
Named level 5 dragon spawned under base in overworld

### ISSUE THREAD

**Issue by omarmartinez97** [AllTheMods/ATM-6#800]
I had a dragon named Bobe(rip) spawn under my base
![2021-01-10_15 12 54](https://user-images.githubusercontent.com/25911861/104135630-fa814200-5356-11eb-966c-5c9950912712.png)
![2021-01-10_15 07 51](https://user-images.githubusercontent.com/25911861/104135649-0cfb7b80-5357-11eb-8944-6031d552863b.png)

**Comment by thevortex** [comment]
what version of the pack are you on? this was an issue for one release and then the option was disabled once it was discovered the dragons were appearing on the overworld as well. this was only intended for "the other" dimension

**Comment by omarmartinez97** [comment]
latest version

**Comment by thevortex** [comment]
have you been restoring your configs after each update? if you created the world on the version with that config setting, you would have brought it back and overwritten our alteration, the configuration required for that to happen does not exist in the current version of the pack.

**Comment by omarmartinez97** [comment]
What's the config file that causes that? and Yeah I created the world a few updates ago.

**Comment by thevortex** [comment]
its the apotheosis/deadly.cfg

**Comment by omarmartinez97** [comment]
I see I have the new config. its weird since it spawned today because I heard a dragon in an area walk around alot. Thanks
