### ISSUE TITLE
Issue with minimap covering up status effects in top right corner

### ISSUE THREAD

**Issue by Vashta** [AllTheMods/ATM-6#803]
so the minimap is covering up the status effects in the top right corner of the screen and in the top left it will cover up the waila block info! i can only move the minimap but the best places for it are taken if possible could you either move the status effects in the top right? also a request would be to add the pams trees to the botany pot

**Comment by iarspider** [comment]
It's not WAILA, it's The One Probe. You can change it's position using chat command `/top config`

**Comment by Letoric** [comment]
The interface is user configurable. We'll consider Pam's trees, but I believe they were added to a later botany pots update, and you can always add botany trees.
