### ISSUE TITLE
Astral Sorcery Mineralis ritual seems to only produce Vanilla ores

### ISSUE THREAD

**Issue by SveetPickle** [AllTheMods/ATM-6#805]
This May be intentional, but The Astral Ritual only produces vanilla ores and none of the modded ores.

**Comment by jeremiahwinsley** [comment]
Astral Sorcery has a whitelist for these which you can see here, currently only contains vanilla ores.

 https://github.com/AllTheMods/ATM-6/blob/master/config/astralsorcery.toml#L706

This will likely be a low priority enhancement, but pull requests are welcome.

**Comment by ladylexxie** [comment]
Fixed in #1965
