### ISSUE TITLE
Default Autocrafting For Mystical Agriculture essences give low amounts

### ISSUE THREAD

**Issue by kaweepatinn1** [AllTheMods/ATM-6#806]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when my applied energistics 2 molecular assemblers are inefficient in crafting ores using essences. For example, the same recipe for uranium essence can be crafted in to either 2 or 6 uranium, fluix crystal changes from 12 to 6, and much much more. Everytime I autocraft, I lose many materials, as the lower crafting amount is usually the default.

**Describe the solution you'd like**
I would like the Kube JS recipes for mystical agriculture (the higher one usually) to be the default when autocrafted, or for the old and lower recipes to be removed altogether. This will allow for more easier autocrafting.

**Describe alternatives you've considered**
Well why don't you manually craft just the ores? Well you see, the numbers I'm using are in the tens of thousands, and I'd like to not sit in front of my computer everyday for 12 hours just left clicking crafting ores. Especially since the me system only lets you craft one stack at a time.

**Additional context**
No additional context, please consider what I've said :D

**Comment by WhitePhant0m** [comment]
It's just a recipe conflict, it will be fixed in the next update, removing the ones made with KubeJS

**Comment by kaweepatinn1** [comment]
Will we lose the better recipes? Or are we losing the worse ones?

**Comment by Letoric** [comment]
The recipes will be the MA provided recipes for anything that MA provides.
