### ISSUE TITLE
atlas stitching : minecraft:textures/atlas/beds.png

### ISSUE THREAD

**Issue by atsharke** [AllTheMods/ATM-6#808]
My girlfriend is currently having an issue launching "All the mods 6" everything loads fine until it reaches "atlas stitching : minecraft:textures/atlas/beds.png" at which point CPU usage drops below 1% and memory heap climbs very slowly and the game will still not open after 30 min of loading I have attempted to look into the issue myself and haven't found any solutions. to resolve the issues I have attempted the following to no avail:

- adjusting ram allocated
- uninstall and reinstall the game
- verified correct and updated java and forge versions

 pc specs are:

- CPU- Ryzen5 2600 6-core
- Ram- 16GB

Please let me know if there any files I can post to assist with resolving the issue and how to create/find them (still new to programming sorry.) If it helps I did see a few instances of similar errors in older modded versions of different packs with some mods having incompatibility with the forge version. But my gf and I played yesterday with no issues and nothing have been updated since and I can still launch fine and there are no reports from others regarding this issue so I doubt that is the problem?

**Comment by TBoshoven** [comment]
I had this exact thing happen to me once on version 1.3.7 of ATM6.
I killed it and restarted and it worked. It seems that the IT Crowd solution ("have you tried turning it off and on again?") didn't help you, however.

Do you have the log of these runs?

**Comment by atsharke** [comment]
where do I find the log files it is still doing it so I can boot it up and have it create a new one
?

**Comment by A-UNDERSCORE-D** [comment]
This continues to be an issue (at least for me) -- nothing suspicious or otherwise in logs. Smells like an infinite loop But no idea where.

**Comment by thevortex** [comment]
try going into config/allthetweaks-common.toml and change the rich prescence boolean to false and see if the issue resolves

**Comment by A-UNDERSCORE-D** [comment]
This did not resolve the issue.

**Comment by Cucmbr** [comment]
I had the same issue with Cave Factory modpack. I tried to turn off discord and after that minecraft loaded properly. Hope, this will help you.
