### ISSUE TITLE
[Ars nouveau] The worn notebook goes wrong

### ISSUE THREAD

**Issue by SipengXie** [AllTheMods/ATM-6#818]
When I checked the worn notebook, I found it's completely empty.
`Entry in file: ars_nouveau:patchouli_books/worn_notebook/en_us/entries_spells/touch.json does not have a valid category`
How can I fix it?

**Comment by jeremiahwinsley** [comment]
Cannot replicate this on 1.3.9b. A newly crafted worn book contains all entries. Which pack version do you have?

**Comment by SipengXie** [comment]
> Cannot replicate this on 1.3.9b. A newly crafted worn book contains all entries. Which pack version do you have?

It's exactly 1.3.9b, maybe I should try reinstalling the pack, thank you.
