### ISSUE TITLE
server stops responding after a bit of time

### ISSUE THREAD

**Issue by coffeeordeath** [AllTheMods/ATM-6#82]
so we are getting memory spikes according to crash Utils and then after a little while, the server stops responding. There is no crash, just freezes up

debug.log - https://gist.github.com/coffeeordeath/560cfdf6740fe55ced14fed830b71722
latest.log - https://gist.github.com/coffeeordeath/289a8aeaec2cc70c723b0c77813e7b27

**Comment by whatthedrunk** [comment]
We are currently on 1.16.3 so removing older issues to make way for new ones. If you want to test it out join the discord for an early beta. New update will be on Twitch / Curseforge once Mekanism pushes their update to the site.
