### ISSUE TITLE
Resourceful Bees: Bees not entering upgraded tier hive

### ISSUE THREAD

**Issue by Oudoum** [AllTheMods/ATM-6#820]
The Resourceful Bees version 1.16.4-0.5.7b had a bug that bees will not enter upgraded bee hives.

Please update ATM-6 to the Resourceful Bees 1.16.4-0.5.8b where the bug is fixed.

**Comment by Pdiddy973** [comment]
This is not really an issue, we already know about it. And we update the mods every time we update the pack.
