### ISSUE TITLE
Add Better than Mending mod (or an alternative)

### ISSUE THREAD

**Issue by Joly0** [AllTheMods/ATM-6#821]
**Is your feature request related to a problem? Please describe.**
Mending in minecraft is often frustrating to use, as its not comprehensible.

**Describe the solution you'd like**
It would be great to have a mod, that would give a bit more control over the mending enchantment and how it works, like better than mending, which makes it able to shift-rightclick with an item with mending in your hand, to give a bit of your experience, to repair the item.

**Comment by jeremiahwinsley** [comment]
Please add mod suggestions to the existing issue: https://github.com/AllTheMods/ATM-6/issues/144
