### ISSUE TITLE
drop not released when breaking a block

### ISSUE THREAD

**Issue by domenicop-1991** [AllTheMods/ATM-6#825]
it is not possible to take the purple shroomlight in the end with any tool

**Comment by NetMasterFlex** [comment]
Does this block exist in Vanilla MC and is breakable?  Have you tried silk touch enchantment on your pick?

**Comment by domenicop-1991** [comment]
the block is part of the mod BYG and is a modification of the classic shoroomlight, I tried to take it with a hoe, by hand, with picks (both luck and velvet touch) and with the axe, but nothing, it doesn't drop anything
