### ISSUE TITLE
Looking at a painting causes GUI to blank

### ISSUE THREAD

**Issue by JDLENL** [AllTheMods/ATM-6#828]
**Describe the bug**
Looking at any painting and opening your inventory causes all of your UI to glitch out until the inventory is closed.

**To Reproduce**
1. Place any painting of any size
2. Look at the painting (notice The One Probe and potential jetpack charge UIs blanking out)
3. Press the Open Inventory key
4. Observe strangeness

**Expected behavior**
The player's inventory should be opened as normal.

**Screenshots**
Before inventory opened: https://i.imgur.com/fGTbpiP.png
After opening inventory: https://i.imgur.com/orQYQ17.png

**Additional context**
Changes have been made to the modpack; the FTB chunks minimap has been disabled and replaced with Xaero's Minimap and Xaero's World Map, and OptiFine is installed (on the latest version, OptiFine HD U G6 pre12

**Comment by WhitePhant0m** [comment]
Do you have optiforge?
if not, [here](https://www.curseforge.com/minecraft/mc-mods/optiforge/files/3165083)

**Comment by JDLENL** [comment]
I'll try optiforge first, and if that doesn't fix it, I'll get one of my friends to log onto the server and see if they have the same issue, since I'm the only one who has modified my version.

**Comment by JDLENL** [comment]
Well, I couldn't get any 1.16.4 version of OptiForge to actually work. Either the Forge version of the pack is too outdated and it simply unloads OptiFine and itself entirely, or attempting to use an earlier version of OptiForge crashes the pack during load. I will have one of my friends tonight attempt to replicate the UI issue.
