### ISSUE TITLE
Server crash when FTB ultimate is used with Any tool with the excavate enchantment. 

### ISSUE THREAD

**Issue by samuel22212** [AllTheMods/ATM-6#832]
**Describe the bug**

**To Reproduce**
1. take any tool with the "excavate enchantment (1 2 3 etc.)
2. Hold down the ~ key to toggle "FTB ULTIMATE" (ore miner/treefeller mode)
3. Mine any block
**Expected behavior**
i'm not sure what i expected It's triggering the excavate enchantment for the number of blocks mined with FTB ultimate which is up to 128 times. which just crashes the server. 
**Screenshots**

**Additional context**

**Comment by jeremiahwinsley** [comment]
Duplicate of #744
