### ISSUE TITLE
Failed to synchronize data from server

### ISSUE THREAD

**Issue by TrueAsGames** [AllTheMods/ATM-6#834]
Nobody can join the server and gives this error: "Failed to synchronize data from server, closing connection"
On the server side: 
`[net.minecraft.network.login.ServerLoginNetHandler/]: com.mojang.authlib.GameProfile@3cf14ebb[id=e2905a44-858e-4408-ba07-ccb0ea8da4dc,name=CobaltDragon_,properties={textures=[com.mojang.authlib.properties.Property@495de0f]},legacy=false] (/85.90.15.146:51931) lost connection: Disconnected`

I redid a fresh installation of forge and the mods from my own mod folder (maybe is it the issue ?) and it redid this error right from the start.

Mod issue, me issue, server issue ?

**Comment by Letoric** [comment]
Please follow the proper server installation process by downloading simple-server-files from curseforge.
Then follow the proper client installation process for whatever launcher you're using, ensuring that you are pulling the same version of the modpack down.
