### ISSUE TITLE
[1.3.9b] Resourceful bees not working on MP server

### ISSUE THREAD

**Issue by jsawatzky** [AllTheMods/ATM-6#836]
Resourceful bees do not seem to be working on my multiplayer server anymore. The bees appear to pollinate, but then do not enter the hives or apiary. The bees still seem to be working in single-player worlds. The bees were working prior to updating the server to 1.3.9b

**Comment by Pdiddy973** [comment]
This was an issue with the version of bees in 1.3.9, bees have An update you can apply manually to resolve this. You may need to break and replace hives after updating
