### ISSUE TITLE
[AE2][1.3.9] Unable to create Quantum Entangled Singularity

### ISSUE THREAD

**Issue by F0x06** [AllTheMods/ATM-6#837]
**Describe the bug**
Like described in the recipe this should create a Quantum Entangled Singularity: `To create drop 1 Singularity and 1 Ender Dust and cause an explosion within range of the items` See: https://ae-mod.info/Quantum-Entangled-Singularity/

**To Reproduce**
1. Place TNT
2. Drop 1 SIngularity + 1 Ender dust (The one from AE2 !)
3. Detonate TNT

**Expected behavior**
A pair of Quantum Entangled Singularity should be created

**Screenshots**
![2021-01-13_20 35 45](https://user-images.githubusercontent.com/7167311/104501194-a9d04a00-55df-11eb-87d1-fcb2ae41b97b.png)

**Additional context**
I tried both TNT and Tiny TNT, and i'm sure i used the right ender dust from AE2

**Comment by Pdiddy973** [comment]
seems to work fine in 1.3.9 even in a claimed chunk

**Comment by F0x06** [comment]
> seems to work fine in 1.3.9 even in a claimed chunk, may want to make an issue on AE github

I'll try also in singleplayer to see, the issue is present on my 1.3.9 server

**Comment by F0x06** [comment]
Apparently it works in singleplayer, the issue is only present on my 1.3.9 server, @Pdiddy973 did you tried on a server or SP ?

**Comment by Pdiddy973** [comment]
I tested in 1.3.9 SP but I made a few on 1.3.7 on my server

**Comment by F0x06** [comment]
> I tested in 1.3.9 SP but I made a few on 1.3.7 on my server

Ok, i'll deploy a fresh 1.3.9 server to test this.

**Comment by F0x06** [comment]
So, i successfuly created a pair of it on my server by going far away from my base, there is someting in my base that prevents the reaction to happen, any idea ?

**Comment by Pdiddy973** [comment]
Not sure, but if you had something that would block an explosion that would prob do it
