### ISSUE TITLE
Refined Storage Dupe >?

### ISSUE THREAD

**Issue by idnthvn** [AllTheMods/ATM-6#843]
-->
Using All The Mods 6 1.3.9b on my own little server (not single player). Nothing else BUT the "ATM 6" mods.
While using Refined Storage, and pushing items into the Interface, the items double.

**To Reproduce**
1. Setup Refined Storage system.
2. Place down Interface.
3. put an item or so into the interface. Example 32 apples
4. While looking at grid you see the 32 Apples in inventory
5. Grab the Apples as if your going to grab all 32.
6. Poof. There is magically 64 in your hand.

This also happens when you LEFT click the stack to grab items.  I can Duplicated WITHOUT the interface as well.
**Expected behavior**
Obviously we dont want duplications in game :P

edit: Rebooted server and tried again. No issues. Assume its a Sync issue?
edit #2: After 5 minutes, can dupe again with the Interface and crafting terminal again.

**Comment by BovineShaman** [comment]
Dupe is no longer happening.
