### ISSUE TITLE
Environmental T8 crystals need T8 miner to get?

### ISSUE THREAD

**Issue by OptionalInformation** [AllTheMods/ATM-6#844]
> Have T7 void miner on crystals
> Expect T8 (xerothium) from mining end

Actual: Only acquiring T7 crystals.

Looking at the xerothium file (envirotech > data > envirotech > envirotech > void_miner_drops > 8xerothium) it shows
<...>
	"config": [
		{"weight": 200, "dimensions": ["minecraft:the_end"], "tiers": [8]},
<...>

as compared to the T7 crystals, 	
<...>
"config": [
		{"weight": 100, "dimensions": ["minecraft:the_end"], "tiers": [6]},
		{"weight": 200, "dimensions": ["minecraft:the_end"], "tiers": [7, 8]},
<...>
wherein they show up on the t6+ drop tables, as expected, to upgrade.

**Comment by Pdiddy973** [comment]
This was a big with ET and was fixed in the mods update, feel free to manually update or wait for the pack to update

**Comment by Letoric** [comment]
Is this still an issue if you update to 1.4.0 pack release?

**Comment by Pdiddy973** [comment]
confirmed T7 miner will get T8 crystals in 1.4.0
