### ISSUE TITLE
Resourceful Bees not returning to Hive/Apiary

### ISSUE THREAD

**Issue by CalcUp** [AllTheMods/ATM-6#847]
Please update Resourceful Bees to 1.16.4-0.5.8b, as stated in the latest Modupdate:
"This update includes CRITICAL fixes for bees!!
Due to changes in forge version 35.1.20 POIs stopped working for bees preventing them from going in Hives/Apiaries - this is fixed 
[...]"

**Comment by Letoric** [comment]
This is already included in the planned release. Thanks.
