### ISSUE TITLE
Immortality Bug

### ISSUE THREAD

**Issue by crzynuggets** [AllTheMods/ATM-6#849]
I'm playing on the latest version 1.3.9 and a quark boss spawned and hit me, when he hit me my hearts disappeared and now I am immortal. Not even kill command will kill me 

I'm not sure how to reproduce a randomly spawned quark boss.

Normally all other quark bosses are fine just this one with its abilities did it.

![2021-01-14_13 41 42](https://user-images.githubusercontent.com/77460397/104636833-f6fcfc00-5671-11eb-998d-e3b7572f1a9c.png)
![2021-01-14_13 42 52](https://user-images.githubusercontent.com/77460397/104636857-fe240a00-5671-11eb-96a6-eedb9ec325d8.png)
.

The axe is the item that dropped upon killing, and as you can see I'm in survival. Please help I don't want to lose my progress.

**Comment by crzynuggets** [comment]
I managed to load a backup, so just the bug problem.

**Comment by Letoric** [comment]
There are no Quark bosses currently. If you can't reproduce it, with as little information as we have it'll have to be considered a 1 off.
