### ISSUE TITLE
Pumpjack uncraftable

### ISSUE THREAD

**Issue by klercke** [AllTheMods/ATM-6#851]
The Immersive Petroleum pumpjack multiblock requires Immersive Engineering steel blocks to create. Due to the fact that these seem to be disabled in the pack in favor of Mekanism blocks, the multiblock cannot be finished.

**Comment by Letoric** [comment]
What pack version? Does it occur if you upgrade to 1.4.0?

**Comment by klercke** [comment]
My apolologies for not including the version. I believe it's 6-1.3.6b. I will be updating my server to 6-1.4.0 and reporting back.

**Comment by klercke** [comment]
Just checked, still not working on 6-1.4.0.

**Comment by Letoric** [comment]
I don't see an immersive petroleum pumpjack, and we haven't removed it. If it was a recipe issue, it should still show up in JEI. Can you provide more information?

**Comment by klercke** [comment]
It's a multiblock. Two steel blocks are required in addition to the other components. The multiblock expects these to be IE steel blocks, so it won't form.

**Comment by Letoric** [comment]
Got it. I've posted to the author asking if they can update to accept forge steel rather than only immersive.

**Comment by Marker248** [comment]
I used the projector and placed the Mekanism steel blocks. They were highlighted in red but I pressed on and whacking the appropriate block with the engineers hammer formed the pump Jack as expected

**Comment by klercke** [comment]
I tried making it again and spammed right click and it worked this time.

**Comment by Krutontar** [comment]
I'm on 1.6.1 and it's not working.

**Comment by Achie72** [comment]
Can cofirm that this issue still stands on `1.6.3c`. There isn't even a `Block of Steel` in the game, nor Immersive Engineering type of steel. I guess this is the main issue, as the Mekanism Steel Block does not seem to work.
