### ISSUE TITLE
Normal crafting recipe for chests

### ISSUE THREAD

**Issue by TBoshoven** [AllTheMods/ATM-6#853]
**ATM 6 version 1.4.0** seems to be missing the normal crafting recipe for chests (8 planks).
It is missing both in JEI and when I try using a crafting table.
A recipe using logs for four chests exists.

Did I mess up my upgrade? Was this intentional?

**Comment by jeremiahwinsley** [comment]
Trapped chest recipe is also missing.

**Comment by jeremiahwinsley** [comment]
As a workaround for this, mixing plank types still works.
![2021-01-15 20_20_16-Window](https://user-images.githubusercontent.com/7946299/104793143-3eb57d80-576f-11eb-96b1-f05b0bbe1ec7.png)
