### ISSUE TITLE
Infinite duplication using Mekanism Combiner

### ISSUE THREAD

**Issue by TBoshoven** [AllTheMods/ATM-6#856]
ATM6 1.4.0

Using the Mekanism combiner, ores can be rebuilt from their materials.
By using the following setup, it's possible to infinitely duplicate certain materials using this:

1. Ore goes in Elementalcraft Ore Purifier (with a constant supply of earth element, single node is enough) resulting in two chunks
1. Chunks go into the Mekanism Enrichment Chamber, resulting in varying numbers of items per chunk
1. Items are fed into a Mekanism Crusher, overflow goes into a chest
1. Dust is fed into a Mekanism combiner which is also fed with the base material (typically cobblestone)
1. See step 1

This contraption is not very expensive to build and is inexpensive in terms of energy.

As far as I could find, this is only possible with the following:
* Emeralds (single ore yields four emeralds, three are needed for combining)
* Diamonds (single ore yields four diamonds, three are needed for combining)
* Nether Quartz (single ore yields ten quartz, eight are needed for combining)
* Fluorite (single ore yields ten fluorite, eight are needed for combining)

I'm not sure if this is a huge issue since you can get infinite diamonds through other means but I figured I'd report this since it seems unintended.
Easy fix is probably to increase the required items for the Combiner.

**Comment by cosmoderp** [comment]
so normally how it would happen:
1. diamond ore makes 2 diamond chunks
2. Enrichment makes 2 diamonds out of each chunk (now 4 diamonds)
3. crusher makes 4 dust
4. combiner takes 3 dust and 1 cobblestone to make another ore


you have only one dust that creates a single diamond each time in the enrichment chamber.
sure its infinite but really it people using different mods to do it.
neither by itself is broken.

Also its easier to just craft one of the site charms from apotheosis mod and go crazy getting diamonds.  should be able to get stacks of them in a few minutes.

**Comment by TBoshoven** [comment]
As I said I know there are other ways.
However, the recipes in the combiner seem to be laid out such that it always requires a little more than it gives you (one ore gives at most 7.5 ingots, but 8 are needed for combining), so I figured this may be an oversight.
I definitely doubt that the ability to create a system like this was intentional.

**Comment by Sirttas** [comment]
fixed in elemental craft 2.5.12
