### ISSUE TITLE
Cannot craft Workbench plus Additional Enchanted Miner(quarry plus) 

### ISSUE THREAD

**Issue by Colton-Slayden** [AllTheMods/ATM-6#86]
in version 0.29 You cannot craft the workbench plus, there is not a recipe. Making all quarry inaccessible

**Comment by WhitePhant0m** [comment]
![image](https://user-images.githubusercontent.com/33400200/91363078-7776a980-e804-11ea-9ade-07f1bcf02cba.png)
On 0.29 and it works

**Comment by Colton-Slayden** [comment]
Very weird my jei has no recipe when i click on it

**Comment by Colton-Slayden** [comment]
I have no idea what is going on a lot of stuff is missing recipes when i launch server on my host but when launched on local machine they have recipes

**Comment by Colton-Slayden** [comment]
Removing PolyMorph has fixed my issue

**Comment by WhitePhant0m** [comment]
polymorph shouldn't cause that issue, does your host have up to date KubeJS folders? all of the custom recipes for the pack are in there

**Comment by Colton-Slayden** [comment]
After removing plymorph it worked for about 20 min. It has the latest KubeJS i have re-downloaded the server a few times. What is weird i downloaded the exact server files from my host and ran it on my local machine and the server has recipes but it does not once uploaded. I looked in kubejs and they are in the folder
