### ISSUE TITLE
Vibranium Not spawning (Bug)

### ISSUE THREAD

**Issue by Dobby0** [AllTheMods/ATM-6#862]
I noticed in the server I played that none was spawning so I went to confirm on single player. I've checked multiple biomes and confirmed that there isn't any spawning in any world created on the latest patch.

**Comment by krabbbbe** [comment]
Vibranium Spawns exclusevly in the layers 87-127 and in the Crimson and Warped Forest

**Comment by Dobby0** [comment]
I know where it spawns. But it isn't there. Make a world and take a look

**Comment by krabbbbe** [comment]
I serached for 30mins now, I have to confirm the Bug. There is no Vibranium Spaning in Nether since V:3.1.4

**Comment by thevortex** [comment]
resolved in version 1.1.27 https://www.curseforge.com/minecraft/mc-mods/allthemodium/files/3171997
