### ISSUE TITLE
Dragons in mining world

### ISSUE THREAD

**Issue by KyubeX** [AllTheMods/ATM-6#865]
Switched from 1.3.9 to 1.4

Thousands of dragons spawning in the Mining World, causeing the world to lag out, making the world unusable.

Yesterday i put a dragon in the mining world to test out something. (v. 1.3.9 [not b])
Today after version update to v.1.4 going to this world spawns around 8000 dragons. (used the entity kill commands to try to clear the world, but they almost instantly spawn back)
The biome also changed to The Other: Desert Hills
https://imgur.com/IMbvTET

**Comment by thevortex** [comment]
Have you tried regenerating the dimension?

**Comment by KyubeX** [comment]
Deleting and then generating the world again solved the problem. 👍
