### ISSUE TITLE
Infinite Items Dupe Bug using the Dank Storage

### ISSUE THREAD

**Issue by DasOschi** [AllTheMods/ATM-6#867]
Pack version 1.4.0

I was clearing my Dank Storage, to be excact the Dank Storage Tier 3 (Gold) trying to get rid of the Darkstone from Forbidden & Arcanus.

**To Reproduce**
1. Put Darkstone into the Dank Storage
2. CTRL + Q the whole stack out of the dank storage onto the ground
3. Exit the Dank Storage
4. CTRL + Q the stacks in your inventory
5. You might notice your inventory won't pick up items - that's because the seemingly empty spots are already full of stacks again. Just put one of the visible stacks in your inventory into one of the "empty" spaces and all of the stacks appear.
6. Repeat step 4 as often as you like
7. Put one of the stacks into the Dank Storage again
8. Voila

I've only had this bug with Darkstone until now, don't know if it is possible with other items aswell.

Screenshots:

Before duping:
![2021-01-16_14 30 05](https://user-images.githubusercontent.com/77536794/104813117-6821e800-5807-11eb-9491-78e0f12e77c3.png)

After duping:
![2021-01-16_14 33 21](https://user-images.githubusercontent.com/77536794/104813192-d23a8d00-5807-11eb-95ac-1e685617c7b9.png)

I hope I can help improving this awsome pack ^~^
Have a nice day =)

**Comment by DasOschi** [comment]
Edit: Just tried it with cobblestone, works aswell. Gonna try it with other modded items e.g. Mystical essences aswell

**Comment by DasOschi** [comment]
New edit: Works with mystical aggriculture aswell.

I think the reason is the limited capacity of your inventory, since there's not enough space to fit in all items they just end up getting duped somehow.

Gonna try it with less open inventory slots aswell.

**Comment by DasOschi** [comment]
Edit: It works with every item in the game.

**Comment by DasOschi** [comment]
Edit: New bug: Don't know how to explain, just watch this clip of me doing it on stream:
You can dupe INDEFINETLY if you connect to your ME System.

https://clips.twitch.tv/InterestingBlitheJuiceTheThing

**Comment by DasOschi** [comment]
Edit: I've posted this on the Dank Storage curse forge issue page aswell, since I believe this is not a ATM6 related issue

**Comment by Tfarcenim** [comment]
Mod author checking in here, the bug is not possible with only Dank and JEI.  Something else is breaking item transfer.

**Comment by ChillerBoi** [comment]
Im confused can you show a video on how to do it ?

**Comment by ladylexxie** [comment]
Doesn't seem to be the case anymore.
