### ISSUE TITLE
Mod List between Server and Client not correct

### ISSUE THREAD

**Issue by ThePixelaxt** [AllTheMods/ATM-6#87]
Terminating connection with client, mismatched mod list

Tested with a fresh install of v0.29, both client and server

**Comment by ThePixelaxt** [comment]
Found this in the client log: The server is likely to require channel [[crafttweaker:main]] to be present, yet we don't have it

**Comment by ThePixelaxt** [comment]
And CraftingTweaks is contained in the modlist.html, which is downloaded by the server starter, so it seems to be an error of the modpack configuration

**Comment by Bimmbamm** [comment]
I updated client and server from 0.28a with no problems.
