### ISSUE TITLE
Could you add this mods?

### ISSUE THREAD

**Issue by derabzockerHD** [AllTheMods/ATM-6#874]
Hello Guys, could you add this three cool mods:

- Serene Seasons (https://www.curseforge.com/minecraft/mc-mods/serene-seasons)?
- Upgraded Netherite (https://www.curseforge.com/minecraft/mc-mods/upgraded-netherite)?
- Enderite Mod (for Forge) (https://www.curseforge.com/minecraft/mc-mods/enderite-mod-for-forge)?

**Comment by jeremiahwinsley** [comment]
Please post mod suggestions in the existing suggestion thread.
