### ISSUE TITLE
integrated dynamics network crashes server

### ISSUE THREAD

**Issue by GleoLP** [AllTheMods/ATM-6#878]
**Describe the bug**
Server crashes everytime after breaking/ placing something in the integrated dynamics network.
**To Reproduce**
1. Build an integrated dynamics network with item storage, exporter item/energy/fluid, importeritem/energy/fluid. Energy and storage is the main component. Energy is connectet to Mekanism, Immersive Engineering and Applied Energistics 2. Energy is getting produced with an Ethylene gas-burning setup --> energy import.
2. Place down a Applied Energistics 2 controller
3. Place down a Energy interface from integrated dynamics on top of the controller connect it to the rest of the network
4. server crash
5. after restart the whole network does not transfer any items/fluids or energy.
6. if I break any integrated dynamics blocks in the network -> server crash

**Screenshots**
My network setup:

https://imgur.com/a/NQOL7XU
couldnt take a screenshot from the terminals, because I broke a cable of the network and it crashed

**Additional context**
Crash report
https://paste.feed-the-beast.com/view/28133d05

**Comment by whatthedrunk** [comment]
Old issues seems fixed but if you are having this still after all this time submit here. Thanks! 
https://github.com/CyclopsMC/IntegratedDynamics
