### ISSUE TITLE
I can't create a world

### ISSUE THREAD

**Issue by R4pel** [AllTheMods/ATM-6#880]
I can't create or enter a world
Everytime I create a world it stops at 100%

**To Reproduce**
1. Go to 'Singleplayer'
2. Click on 'New World'
3. Click on 'Create new world'

![Minecraft](https://user-images.githubusercontent.com/77572661/104839554-c9a28f00-58b9-11eb-8323-5d83adf0b677.PNG)

**Comment by Pdiddy973** [comment]
mod pack version and launcher?

**Comment by R4pel** [comment]
> versão do mod pack e lançador?

Version:6.1.3.2.c and launcher:Tlauncher

**Comment by Pdiddy973** [comment]
Update to version 1.4.0, and I'm not sure what launcher TLauncher is, but we recommend Multimc or GD launcher
