### ISSUE TITLE
Mod Conflict: Dank Storage and Integrated Dynamics

### ISSUE THREAD

**Issue by Momo-Git** [AllTheMods/ATM-6#883]
I have discovered a conflict whilst the Dank 7 in in my inventory I am unable to place anything into the Integrated Dynamics Squeezer. Simply removing the Dank Storage from your inventory or placing into a bag resolves this issue.

**Comment by Segaja** [comment]
I can confirm this on 1.4.0 on a private server.

**Comment by elbim** [comment]
Same here on 1.4.1
