### ISSUE TITLE
[1.4.0] Rock Crystal Seed recipe doesn't work

### ISSUE THREAD

**Issue by indygwyn** [AllTheMods/ATM-6#884]
**Describe the bug**
Been trying to make a Mystical Agriculture seed for Astral Sorcery Rock Crystals but the recipe in JEI doesn't work: 4 rock crystal, 4 supremium in the MA infusion ritual

**To Reproduce**
1. Setup MA infusion altar
2. Insert rock crystals in 4 pedestals, Supremium in 4 pedestals, Prosperity Seed in the altar
3. Press button to activate Infusion
4. Nothing happens

**Comment by Sindenky** [comment]
I can confirm the exact same issue.

**Comment by Prob1ematic** [comment]
Me too
