### ISSUE TITLE
[ATM 6] Can’t create world after updating to 1.4, Optifine is installed. 

### ISSUE THREAD

**Issue by MaverickLime** [AllTheMods/ATM-6#885]
[<!---](url
![E0A0EE58-8FEA-47B6-BB94-27325FBE44DD](https://user-images.githubusercontent.com/77599935/104869895-c5ec2800-590c-11eb-9702-303b7ac7606d.png)
) 
I load into the mod pack, so I make it past the title screen. But once I go to load into a world it crashes (like all the way back to launcher), I have 10gb allocated but I played 1.3.9 with 10gb so I don’t think that’s the issue. I do have optifine which I was fighting with before I updated to 1.4 but I don’t see optifine in the crash screen. I also was having an issue with Quarry not having a recipe, is that normal? Thank you in advance,,, :)

**Comment by jeremiahwinsley** [comment]
Optifine is not supported. If the issue occurs without Optifine, feel free to reopen or ask for support on the Discord.
