### ISSUE TITLE
Dragons swarmed my Mining Dimension

### ISSUE THREAD

**Issue by SmibbyDibbler** [AllTheMods/ATM-6#886]
I didn't get any screenshots but while in the mining dimension on my my server I noticed dragons coming in from the distance. There were a ton of them and they started insta killing me every time I went in. In creative mode I was able to go where they were coming from and it was just a huge horde of dragons big and small of every type. It bogged the fps down to like 10. Weird bug. Thought you should know about it.

**Comment by Sralez** [comment]
Same issues as OP.  It appears the update converted my previously existing mining dimension into The Other.
![2021_01_18_11_57_18_javaw](https://user-images.githubusercontent.com/77639391/104954595-c07ef400-5985-11eb-8242-2b3788bbe495.png)  It's like pouring a bowl of "Oops! All Dragons" for breakfast.  For me, this was an update from an existing 1.3.9 to 1.4.0.  Will roll back to backup for now.

**Comment by thevortex** [comment]
Regenerate your mining dimension

**Comment by SmibbyDibbler** [comment]
Already did. Just thought I would bring it to someone’s attention  Sent from Mail for Windows 10 From: thevortexSent: Monday, January 18, 2021 11:20 AMTo: AllTheMods/ATM-6Cc: SmibbyDibbler; AuthorSubject: Re: [AllTheMods/ATM-6] Dragons swarmed my Mining Dimension (#886) Regenerate your mining dimension—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe. 

	
        
		Virus-free. www.avast.com

**Comment by Sralez** [comment]
Regenerating fixes it, thank you.
