### ISSUE TITLE
ATM[1.4.0] No longer able to download a pack due to a missing dependency

### ISSUE THREAD

**Issue by LTenshi** [AllTheMods/ATM-6#888]
**Describe the bug**
The pack is no longer installable, whenever an attempt is made to download it the following error toast appears in CurseForge:
"This modpack requires a dependency that is missing or no longer available. Missing Addon ID: 227083"
I checked the Addon ID and it seems to be the baubles mod.

**To Reproduce**
1. Launch CurseForge
2. Attempt to install pack
3. Look at the bottom of CurseForge

**Screenshots**
![image](https://user-images.githubusercontent.com/24688899/104961648-a9b0bf80-59ce-11eb-974e-ee0dc85cc1a7.png)

**Additional context**
No further context.

**Comment by jeremiahwinsley** [comment]
This is a CurseForge launcher bug. You can use MultiMC or GDLauncher instead.

**Comment by LTenshi** [comment]
Thanks, it indeed seems so.
