### ISSUE TITLE
Missing Textures for some items

### ISSUE THREAD

**Issue by BagiGa** [AllTheMods/ATM-6#89]
Some texturtes are missing from mekanism, botaniam, the facades from applied energistics and more others there are no extra textures just optifine, and no resource packs that arent in the pack help plzz

![2020-08-26_15 59 34](https://user-images.githubusercontent.com/58560338/91313118-4c189e00-e7b5-11ea-9e49-5e100126b331.png)
![2020-08-26_15 59 58](https://user-images.githubusercontent.com/58560338/91313127-4de26180-e7b5-11ea-9d95-9b1ebc95c060.png)
![2020-08-26_16 00 01](https://user-images.githubusercontent.com/58560338/91313132-4fac2500-e7b5-11ea-8741-832c928c84a0.png)
![2020-08-26_16 00 06](https://user-images.githubusercontent.com/58560338/91313141-50dd5200-e7b5-11ea-9282-f36541d25cf8.png)
![2020-08-26_16 00 14](https://user-images.githubusercontent.com/58560338/91313148-520e7f00-e7b5-11ea-8e84-c86bfc9077d9.png)
![2020-08-26_16 00 15](https://user-images.githubusercontent.com/58560338/91313151-533fac00-e7b5-11ea-98b0-c9eecc1ed2d8.png)
![2020-08-26_16 00 18](https://user-images.githubusercontent.com/58560338/91313155-5470d900-e7b5-11ea-9798-434294d2253e.png)

![2020-08-26_15 59 21](https://user-images.githubusercontent.com/58560338/91313097-4622bd00-e7b5-11ea-8b87-e9302dd02f00.png)
![2020-08-26_15 59 26](https://user-images.githubusercontent.com/58560338/91313105-48851700-e7b5-11ea-82dc-c1822d43d82c.png)
![2020-08-26_15 59 29](https://user-images.githubusercontent.com/58560338/91313114-4a4eda80-e7b5-11ea-8088-7e421cc8cb28.png)

**Comment by WhitePhant0m** [comment]
It's caused by optifine, install [optiforge](https://www.curseforge.com/minecraft/mc-mods/optiforge), it will fix it.
