### ISSUE TITLE
All the ores block gets destroyed

### ISSUE THREAD

**Issue by Bender8887** [AllTheMods/ATM-6#890]
All the ore's blocks once placed in the world get destroyed when you try to retrieve them with any pickaxe.

**Pack version 1.4.0**

**To Reproduce**
1. Craft a all the ore's block 
2. Place block in world
3. Use pickaxe on it
4. Block destroys instead of harvest

**Comment by ariosos** [comment]
Did you try the Mining Laser? I've noticed this too, but figured the ores (Vibranium and Unobtanium) were gated behind needing to use the mining laser..

**Comment by thevortex** [comment]
resolved with ATO 1.1.20 https://www.curseforge.com/minecraft/mc-mods/ato/files/3173269
