### ISSUE TITLE
v1.4.0 "Loading Terrain" takes a few minutes to load, during which I'm sitting Idle on the server and can be killed by mobs

### ISSUE THREAD

**Issue by Forsak3nBacon** [AllTheMods/ATM-6#891]
Have seen this issue on ATM6 just from googling, but all were closed off without a fix. Example, https://github.com/AllTheMods/ATM-6/issues/324

Currently when I click connect on a server, and takes a moment on Encrypting, then sits on Loading Terrain for a few minutes. During the loading terrain, I'm actually connected to the server and vulnerable to mobs.

Is there anyway to speed this up?

Server is hosted on Creeperhost, with 4.5GB allocated and only 1 or 2 people playing. RAM usage only sitting at 4GB. Haven't had an issue like this with these hosters, they're normally the best of the bunch.

ATM 6 is v1.4.0.

**Comment by P0LarBeaR1** [comment]
We've had the same issue on our server. We haven't found a fix but just ensure we always log off somewhere safe. Its no longer an issue for me personally as I've now got unobtanium armour so pretty much can't die

**Comment by vedalken254** [comment]
The RAM allocated to the server actually doesn't matter it seems in terms of this. I have a local server with 24GB of RAM assigned to it and this also happens on it. The time might be reduced (usually it's less than 30 seconds that I'm stuck at Loading Terrain) by having more RAM, but it's definitely not perfect even at 24GB. Then again, pretty much all the commercial hosts run newer hardware than that machine has. I set up a fence to make sure mobs couldn't get in for my area on my server, but that's a mere workaround.
