### ISSUE TITLE
No Stronghold in 1.4.0

### ISSUE THREAD

**Issue by Seegras** [AllTheMods/ATM-6#892]
**Describe the bug**
Stronghold and End Portal don't get generated. 
/locate stronhold says "could not find that structure nearby"
The ender eye leads you to a location some thousand blocks away, where there is no end portal. 

**To Reproduce**
Create new world in ATM6 1.4.0, type default.

**Comment by WhitePhant0m** [comment]
Not a bug, [repurposed structures](https://www.curseforge.com/minecraft/mc-mods/repurposed-structures) replaces the stronghold
![image](https://user-images.githubusercontent.com/33400200/105036551-4c1b8200-5a65-11eb-88ee-f80568ba1404.png)

**Comment by Seegras** [comment]
then repurposed structures breaks the ender eye functionality.
