### ISSUE TITLE
Crashing the game after 5-10 secs into the world

### ISSUE THREAD

**Issue by Andy3link** [AllTheMods/ATM-6#893]
ATM 6 1.4.0
**Describe the bug**
I load the world, after 5-10 secs it crashes the game.

**To Reproduce**
1. Start the game
2. Click on Load world
3. Wait for world to load, and crash

**Additional context**
Crash log  : https://pastebin.com/B7wFyPjE

Tried refreshing most files, and a backup with the same outcome when i enter the town. the backup was not in town but when i got back it did the same again

**Comment by starforcraft** [comment]
Should be fixed in newest Version
