### ISSUE TITLE
Id like to grow a pot farm and have more bee stuff on my ATM server. 

### ISSUE THREAD

**Issue by Bee-farming-pothead** [AllTheMods/ATM-6#894]
https://www.curseforge.com/minecraft/mc-mods/cannabiscraft 

Best 1.16.4 pot mod I could find ^^^

https://www.curseforge.com/minecraft/mc-mods/buzzier-bees
https://www.curseforge.com/minecraft/mc-mods/the-bumblezone-forge
https://www.curseforge.com/minecraft/mc-mods/productivebees

Compatible bee upgrades ^^^

**Comment by jeremiahwinsley** [comment]
Please use the pinned thread for mod suggestions.
