### ISSUE TITLE
[1.4.0] Crushed Platinum Ore can't be washed (Create)

### ISSUE THREAD

**Issue by Kris1432** [AllTheMods/ATM-6#896]
Hi Guys! 

Platinum Ore can be crushed, but it can't be washed (Create), I have a filter set up to not let through any items through that can be washed and the Platinum Crushed Ore just goes straight through (blocking the system up).

Any further questions let me know!

**Comment by SmuleChez** [comment]
I'm on 1.4.1 and I also experience this. The crushed platnium ore does not get washed and turned into nuggets despite the fact that there are platinum nuggets.

**Comment by NoMoreStars** [comment]
I believe this is the same bug as was documented in #712

**Comment by whatthedrunk** [comment]
This is a duplicate as said above. Well look into it.
