### ISSUE TITLE
Resourceful Bees Hives beyond Tier 1 are non-functional in ATM6 1.4.0

### ISSUE THREAD

**Issue by Xeddius** [AllTheMods/ATM-6#897]
Pack Version 1.4.0

**To Reproduce**
Have resourceful bees, place tier 2+ hives, watch as they never use them and fly around forever. Place a tier 1 and they swarm to it.

This doesn't occur with just resourceful bees and forge standalone.

**Additional context**
I've spoken with others who have the same issue, we've been unable to determine the cause other than it being specific to ATM6.

**Comment by ilops-tester** [comment]
And its The same with apiary multiblock tier 1-4 dont work

**Comment by Pdiddy973** [comment]
Once you update, make sure you pick up the bees and hives/apiaries and replace them. Should work then

**Comment by Rumaan3012** [comment]
> Once you update, make sure you pick up the bees and hives/apiaries and replace them. Should work then

Seconded. Had to break and re-place any hives or apiaries originally placed in v1.3.9b in order for them to work properly once updated to 1.4.0.
