### ISSUE TITLE
Game crashes upon world start. Missing an entity from the Rats mod.

### ISSUE THREAD

**Issue by jacquesco07** [AllTheMods/ATM-6#899]
Running version 1.4.0. on curseforge and it was working just fine before. For some reason, when starting it up today, this error message pops up when I load into my world: 
"The game crashed whilst rendering entity in world
Error: java.lang.NoClassDefFoundError: com/github/alexthe666/rats/client/model/ModelSantaHat
Exit Code: -1"

**To Reproduce**
1. Open the AllTheMods6 client through curseforge
2. Wait for the game to startup
3. Click single-player
4. Click on the world that I'm playing
5. Game crash after loading.

**Crash log**
[crash-2021-01-19_18.32.35-client.txt](https://github.com/AllTheMods/ATM-6/files/5839805/crash-2021-01-19_18.32.35-client.txt)

**Comment by jeremiahwinsley** [comment]
You can update Rats to 7.0.5 or newer to fix this. Otherwise, it should be in the next major pack update.

**Comment by jacquesco07** [comment]
> You can update Rats to 7.0.5 or newer to fix this. Otherwise, it should be in the next major pack update.

Just tried this, still getting the same crash message.

**Comment by doroku** [comment]
Any fix on this?

**Comment by jacquesco07** [comment]
> Any fix on this?

So far, none. I haven't been able to play that world since posting about it. There's a similar thread on this issue in the Rat Mods GitHub page too. Here's the link to that: https://github.com/Alex-the-666/Rats/issues/521

**Comment by jacquesco07** [comment]
Current workaround is just deleting the rats mod and ratlantis mod entirely. Obviously, this will stop any automation that you might have, but it at least allows you to get into your world and fix things.

**Comment by starforcraft** [comment]
Should be fixed in newest Version
