### ISSUE TITLE
controls not showing up

### ISSUE THREAD

**Issue by blackwing12344** [AllTheMods/ATM-6#900]
pack version 1.4.1
**Describe the bug**
if you go into the controls menu, all of the descriptions are too far to the left to be seen.

**Comment by jeremiahwinsley** [comment]
Not a pack bug, you will need to resize the window larger than the default 854x480 to see all the descriptions.

**Comment by blackwing12344** [comment]
it is full screen at 1440x1080

**Comment by jeremiahwinsley** [comment]
Then you might need to adjust your gui scale in video settings.

**Comment by blackwing12344** [comment]
it was at 4, which is where I like it, but it requires it to be 3 for me to see it
