### ISSUE TITLE
Refined storage exporters, importers, constructors and destructors redstone mode cannot be changed

### ISSUE THREAD

**Issue by P0LarBeaR1** [AllTheMods/ATM-6#902]
Version 1.4.0

When trying to change redstone mode on any constructor, destructor, importer or exporter from refined storage the mode cannot be changed. And clicking on the redstone mode icon in the GUI will instead change the module from items mode to fluids mode. However, clicking the redstone mode button a second time will not return the module to items mode and you must click on the actual fluids/items button. This means that non of these modules can be used with redstone interaction.

**Comment by Krutontar** [comment]
I submitted this to the Refined Storage Git and they are saying it's something in the pack that's messing with it.
https://github.com/refinedmods/refinedstorage/issues/2847

**Comment by Krutontar** [comment]
Fixed with 1.5.0 preview version.
