### ISSUE TITLE
Chest vanilla recipe has been replaced by logs varient

### ISSUE THREAD

**Issue by P0LarBeaR1** [AllTheMods/ATM-6#903]
Version 1.4.0

The vanilla recipe for crafting chests with planks has been replaced by the logs recipe, leading to duplicate recipes. This can be seen by going to JEI and looking at chest crafting recipes, as evidenced in the screenshot. Attempting to craft a chest with planks will also fail.
![image](https://user-images.githubusercontent.com/77748285/105219539-7ac15780-5b4e-11eb-9f5f-3dadaebd5c2f.png)

**Comment by icha-senpai** [comment]
why was this closed?

**Comment by Pdiddy973** [comment]
it was fixed in 1.4.1
