### ISSUE TITLE
Every time you walk into an IE wire that is live on a server, you get kicked from the server and cannot rejoin (1.4.1, maybe 1.4.0)

### ISSUE THREAD

**Issue by ashduino101** [AllTheMods/ATM-6#904]
If you walk into live wiring while on a server, you get kicked. When you try to rejoin, you repeatedly get kicked with the error, "Internal server error".

**Comment by Benzination** [comment]
Having an identical issue with Immersive Engineering, but not from walking into one of the cables. Someone else on the server tried to place down an LV capacitor in the world, and had a CTD. I tried to teleport to the area to have a look, and about half a second of loading later also had a CTD. Server log shows absolutely nothing out of the ordinary. Attempting to rejoin the server however causes a CTD almost immediately after fully loading in. 

Client log of trying to log into the server in the affected area; https://paste.ee/p/LSJ3n
