### ISSUE TITLE
Witch Hat Duped crafting use

### ISSUE THREAD

**Issue by EvilEtho** [AllTheMods/ATM-6#906]
The 3 Witch hats can be use to craft Gunpowder, Glow stone, or redstone. But they all have the same crafting so you can only get gunpowder.
![MCbug1](https://user-images.githubusercontent.com/6267767/105250911-65890080-5b2f-11eb-9edf-5c3322dbc6f2.JPG)
![mcbug2](https://user-images.githubusercontent.com/6267767/105250912-66219700-5b2f-11eb-90fb-990bcb17653d.JPG)
![mcbug3](https://user-images.githubusercontent.com/6267767/105250913-66ba2d80-5b2f-11eb-9f18-312157916cb0.JPG)

**Comment by Dextryan** [comment]
It seems like a bug indeed, but you probably can switch the output to the one you want if you craft them in a normal crafting table while it is not fixed

**Comment by jeremiahwinsley** [comment]
Tracked here: https://github.com/P3pp3rF1y/Reliquary/issues/488
