### ISSUE TITLE
Creative mana pool

### ISSUE THREAD

**Issue by Noxally** [AllTheMods/ATM-6#907]
Creative mana pool can be crafted shapelessly using just a mana tablet, making infinite mana cost essentially nothing.

**Comment by Pdiddy973** [comment]
are you able to tell what version you are on? and a screen shot? im not able to in version 1.4.1 with any of the mana tablets

**Comment by Noxally** [comment]
Im on 1.4.1 aswell, heres a screenshot
![image](https://user-images.githubusercontent.com/22868168/105330876-75f6b500-5bdb-11eb-8c3b-b6f837b08e3e.png)

**Comment by Pdiddy973** [comment]
are you actually able to craft it? i tried and it did not work. its probably due to the fact they are all the same item with different NBT tags that make them different. so the creative tablet can be crafted into the creative pool. but the normal ones cannot.

**Comment by Noxally** [comment]
Yup. have a pool sitting on the ground now. recipe comes from kube.js.

ID: minecraft:kube.js_generated_881_botania_mana_tablet

maybe Kube update? uh version im using is 1605.3.4.151.

Possibly some sorcery with an update? not sure if i manually updated kube

**Comment by Noxally** [comment]
![image](https://user-images.githubusercontent.com/22868168/105331523-39778900-5bdc-11eb-92d9-f36ec79c6838.png)

works for me no matter the fill level

**Comment by Pdiddy973** [comment]
it is an issue with that updated version. the pack is currently on version 1604.3.4.144 of kube JS. not sure why you updated it but its not an issue with the pack, its an issue with how you modified it

**Comment by Noxally** [comment]
What im struggling to work out is why. if i use config and kube files from the pack, and use new version kube and all botania related things it isnt causing it in my testing instance. Aight will try caht to Latvian and find out how.
