### ISSUE TITLE
Mods "Failed To Load Correctly"

### ISSUE THREAD

**Issue by LimitedSalvation** [AllTheMods/ATM-6#908]
These mods were not loaded correctly and I don't really know why. No reason's were given either.
![error](https://user-images.githubusercontent.com/64234463/105374065-48a70880-5bd5-11eb-837d-491bd6f50987.PNG)

**Comment by Pdiddy973** [comment]
try and re install your instance, and make sure you are using a good launcher like Multi MC or GD launcher.

**Comment by Cntrldfusion** [comment]
only think I can think of off the top of my head is check the mods folder and make sure those mods are not ZERO byte files
