### ISSUE TITLE
Solar Panel

### ISSUE THREAD

**Issue by vitalisk79** [AllTheMods/ATM-6#91]
There is no recipe for crafting solar panels. Is it just me or everyone? 0.29

**Comment by WhitePhant0m** [comment]
It's intended for mekanism solars

**Comment by vitalisk79** [comment]
> It's intended for mekanism solars


Not understood. How to craft solar generators to warm up Thermal Evaporation Plant if you cannot craft a generator component (solar panel).

**Comment by vitalisk79** [comment]
I will add that in Immersive Engineering Redstone connectors do not work, input - output modes do not switch.

**Comment by coffeeordeath** [comment]
use a resistive heater or fuelwood heater to warm up your plant. 

IE redstone connectors DO switch, i have used them myself in 0.28 and 0.29. have u tried using the screwdriver?
