### ISSUE TITLE
ATM6 Config/gameplay change suggestion

### ISSUE THREAD

**Issue by Sindenky** [AllTheMods/ATM-6#910]
**Suggesting:** Disable speed duplication for all Mystical Agriculture seeds. This includes planting them as well as botany pots. 

**Reason:** Every time a seed splits its duplicating several essence worth of resources (item items used to make the seed) as well as the raw essence itself. Higher tier seeds are the biggest offenders, but no other infinite resource generator in the pack self dupes its crafting materials, and auto crafts the new version. Once the new seed is planted, you have decreased the time till your next seed split as well, creating an exponential growth in resource production. 

not only do you need to simply craft/plant 1 single seed of any given type to inevitably (and quickly) have and entire field of them, you  eventually are left with so many in excess that they can become cumbersome. The seed re-processor becomes a source of voiding them while slightly boosting yield, but the exponential growth of the crops leads to many simply piping them into a trash can. 

By disabling seed splitting as default you bring MA in line with the effort to yield ratio of other resource generation methods, and bring value to the seeds themselves, as each and every one is hand crafted with intent.

**Comment by whatthedrunk** [comment]
Ill bring this up in dev chat and close the issue for now thanks!
