### ISSUE TITLE
1.4.1 Void Miner not working properly

### ISSUE THREAD

**Issue by DizzyKid** [AllTheMods/ATM-6#913]
ATM6 1.4.1
**Describe the bug**
When I have all the materials for a void miner, as well as enough room for it to be autobuilt, shift+right clicking on the void miner doesn't make the multiblock

**To Reproduce**
1. Place a Litherite Void Miner facing the a void with sufficient space to form a multiblock
2. Have enough materials in your inventory to form the multiblock (see litherite void miner item)
3. Shift+right click on the void miner to attempt to create the multiblock
4. Nothing happens

**Comment by WhitePhant0m** [comment]
open the GUI of the miner, there are buttons in there that build it.
