### ISSUE TITLE
Industrial Foregoing Range Tier 4 and 5 too big

### ISSUE THREAD

**Issue by Gimics** [AllTheMods/ATM-6#914]
Pack Version 1.3.9

**Describe the bug**
Industrial Foregoing Addon: Range Tier 4 and Range Tier 5 range upgrades for Plant Gatherer cause harvesting outside of the expected range. The gatherer is harvesting woodblocks from trees over 50 blocks away, and 30+ blocks up. My beautiful cherry tree forest surrounding my base and crops has nearly been leveled!

**To Reproduce**
Not sure - I have a Block Placer facing a small Infernium farm (6x6), surrounded by a row of water and a couple of "Lilypad of Fertility"s. Also using a Sower under the farm to plant, and a User with a watering can above the farm to increase growth.

_Edit: Originally posted as Cyclic - had my wires crossed with the Harvester not working_

**Comment by Slaymeister** [comment]
Lol. I also ran into this issue. I harvested outside the range of my infernium farm and destroyed a cherry tree forest I planted around my base. I haven't tested it outside the range for other plants.  I didn't have any other active components in the mix (no sower, lily pads, user, or watering can). Hopefully that helps any repro efforts.

**Comment by starforcraft** [comment]
There isn't a config from Industrial Foregoing to change the Range.
