### ISSUE TITLE
Cannot access the Nether

### ISSUE THREAD

**Issue by MushuPlatypus** [AllTheMods/ATM-6#916]
**Describe the bug**
Cannot access the Nether in the 1.16.5 version

**To Reproduce**
Create a Nether portal
Try to go through
Nothing happens

This is an existing world that was created in the last version

**Comment by jeremiahwinsley** [comment]
This is a known bug with the 1.5.0 alpha. You can rollback to 1.4.1, or use the pinned fix.

**Comment by TechniumUnlimited** [comment]
What mod is causing it?
