### ISSUE TITLE
Pam's Harvest Craft Fixes

### ISSUE THREAD

**Issue by krabbbbe** [AllTheMods/ATM-6#917]
V: 1.4.1 and 1.4.0

Pam's Harvest Craft:
- Soy Adds No Hunger (usually 3 Hunger, 3.6 saturation)
- No use for Soy in industrialForegoing:CulinaryMycelialGenerator (usually t=480;rf/t=48;rf=23040)
- No use for Soy in mekanism:Crusher (usually 4 Bio Fuel)
- No recepie for Soy in mekanism:NutritionalLiquifier (150mb)
- No recepie for Soy in pneumaticcraft_repressurised:ThermopneumaticProcessingPlant (usually 20mb Vegetable Oil at 2.0bar)
- No recepie for Olives in botanypots
- Wrong item Name for Maplesyrup (currently: item.pamhc2trees:maplesyrupitem)
- No recepie for gathering Maplesyrup
- No recepie for planting/growing Maplesyrup
- Missing recepie for pamhc2trees:paperbark_sapling and pamhc2trees:olive_sapling in thermal:machine_insolator (usually: 6Log;1Sapling;4Cropoutput)

No plant drop recepie for:
[ ]
- Windy garden
1. pamhc2crops:amaranthitem
2. pamhc2crops:artichokeitem
3. pamhc2crops:barleyitem
4. pamhc2crops:bellpepperitem
5. pamhc2crops:chilipepperitem
6. pamhc2crops:cucumberitem
7. pamhc2crops:elderberryitem
8. pamhc2crops:flaxitem
9. pamhc2crops:mustardseedsitem
10. pamhc2crops:onionitem
11. pamhc2crops:parsnipitem
12. pamhc2crops:peanutitem
13. pamhc2crops:strawberryitem
14. pamhc2crops:wintersquashitem

[ ]
- Tropical Garden
1. pamhc2crops:arrowrootitem
2. pamhc2crops:cantaloupeitem
3. pamhc2crops:coffeebeanitem
4. pamhc2crops:eggplantitem
5. pamhc2crops:gingeritem
6. pamhc2crops:grapeitem
7. pamhc2crops:kenafitem
8. pamhc2crops:kiwiitem
9. pamhc2crops:pineappleitem
10. pamhc2crops:soyitem
11. pamhc2crops:taroitem

[ ]
- Arid Garden
1. pamhc2crops:agaveitem
2. pamhc2crops:cactusitem
3. pamhc2crops:cactusfruititem
4. pamhc2crops:cassavaitem
5. pamhc2crops:chickpeaitem
6. pamhc2crops:lentilitem
7. pamhc2crops:sisalitem

[ ]
-Frosty Garden
1. pamhc2crops:broccoliitem
2. pamhc2crops:cabbageitem
3. pamhc2crops:caulifloweritem
4. pamhc2crops:celeryitem
5. pamhc2crops:cottonitem
6. pamhc2crops:huckleberryitem
7. pamhc2crops:juniperberryitem
8. pamhc2crops:kohlrabiitem
9. pamhc2crops:oatsitem
10. pamhc2crops:peasitem
11. pamhc2crops:raspberryitem
12. pamhc2crops:rutabagaitem
13. pamhc2crops:ryeitem
14. pamhc2crops:spinachitem

[ ]
-Shadded Garden
1. pamhc2crops:beansitem
2. pamhc2crops:blackberryitem
3. pamhc2crops:garlicitem
4. pamhc2crops:juteitem
5. pamhc2crops:leekitem
6. pamhc2crops:radishitem
7. pamhc2crops:rhubarbitem
8. pamhc2crops:spiceleafitem
9. pamhc2crops:sweetpotatoitem
10. pamhc2crops:tealeafitem
11. pamhc2crops:tomatoitem
12. pamhc2crops:turnipitem
13. pamhc2crops:whitemushroomitem
14. pamhc2crops:zucciniitem

[ ]
- Soggy Garden
1. pamhc2crops:asparagusitem
2. pamhc2crops:blueberryitem
3. pamhc2crops:cottonitem
4. pamhc2crops:cranberryitem
5. pamhc2crops:greengrapeitem
6. pamhc2crops:jicamaitem
7. pamhc2crops:kaleitem
8. pamhc2crops:milletitem
9. pamhc2crops:mulberryitem
10. pamhc2crops:okraitem
11. pamhc2crops:riceitem
12. pamhc2crops:spiceleafitem
13. pamhc2crops:sweetpotato item
14. pamhc2crops:tomatilloitem

**Comment by jeremiahwinsley** [comment]
You can suggest these to the Pam's Harvestcraft dev, we won't be adding these since we do not customize the recipes for this mod. The mod is still in active development and adding recipes themselves.
