### ISSUE TITLE
[1.41] Metal Plates variations missing from JEI recipes

### ISSUE THREAD

**Issue by Blooder14** [AllTheMods/ATM-6#918]
Only Themal Series metal plates (iron plate, lead plate etc.) are displayed in JEI

Most notably Immersive Engeneering Iron plates are hidden from JEI but can be retreived by looking for the recipe with the engineer hammer

![image](https://user-images.githubusercontent.com/77853084/105526390-a412ec80-5ce2-11eb-9125-2dbd208953c7.png)

recipes which will accept IE iron plates won't show them like the IE Lantern

![image](https://user-images.githubusercontent.com/77853084/105526468-c1e05180-5ce2-11eb-88e5-85e09450dadf.png)

They CAN be crafted with the engineer hammer or the press so most probably they are hidden in JEI 

they are correctly tagged as forge:plates/iron so they can still be used everywhere, just hidden by default

![image](https://user-images.githubusercontent.com/77853084/105526924-5480f080-5ce3-11eb-9d46-3d2ca3a954d4.png)

**Comment by krabbbbe** [comment]
pls repost in KubeJS - not a "bug"

**Comment by jeremiahwinsley** [comment]
This is intentional, not a bug.

**Comment by Blooder14** [comment]
Is it intentional that if you search for iron plates they don't show up and all the recipes are hidden?
![image](https://user-images.githubusercontent.com/77853084/105542236-4a69ec80-5cf9-11eb-9d98-757dc31d1acc.png)

only the multiservo press recipe is available in JEI
![image](https://user-images.githubusercontent.com/77853084/105542297-666d8e00-5cf9-11eb-937a-927100806ef2.png)

all those i posted above are hidden
