### ISSUE TITLE
Fluxbore not changing modes when I added a radial enchacement

### ISSUE THREAD

**Issue by GalacticTurtle01** [AllTheMods/ATM-6#919]
Fluxbore not turning into 3x3 mode

**Screenshots**

![image](https://user-images.githubusercontent.com/72573516/105560974-58ecdf80-5cca-11eb-9742-399b1bfcf288.png)
I added a Radial Enchancement and pressed V and nothing happened.

**Comment by Pdiddy973** [comment]
This is likely a issue with multiple things using v, go into controls a search by key and change/remove things using it...or change the flux bore keybind.
