### ISSUE TITLE
Solar Panel

### ISSUE THREAD

**Issue by vitalisk79** [AllTheMods/ATM-6#92]
I'm sorry for repeating.

vitalisk79 commented 7 hours ago
There is no recipe for crafting solar panels. Is it just me or everyone? 0.29

@WhitePhant0m
 
Collaborator
WhitePhant0m commented 4 hours ago
It's intended for mekanism solars

@WhitePhant0m WhitePhant0m closed this 4 hours ago
@vitalisk79
 
Author
vitalisk79 commented 3 hours ago
It's intended for mekanism solars

Not understood. How to craft solar generators to warm up Thermal Evaporation Plant if you cannot craft a generator component (solar panel).

**Comment by vitalisk79** [comment]
I will add that in Immersive Engineering Redstone connectors do not work, input - output modes do not switch.

**Comment by coffeeordeath** [comment]
use a resistive heater or fuelwood heater to warm up your plant.

IE redstone connectors DO switch, i have used them myself in 0.28 and 0.29. have u tried using the screwdriver?

also its bad form to try and add separate issues onto one, especially if they are completely unrelated and ESPECIALLY if the issue has been closed.

**Comment by WhitePhant0m** [comment]
Since this was originally about the solars and that was answered, I'll close it. Make a separate issue for the redstone connectors if needed.
