### ISSUE TITLE
IntegratedDynamics Energy Battery Crashes Client

### ISSUE THREAD

**Issue by NULLProtogen** [AllTheMods/ATM-6#920]
Client crashes and player can not log back in till they have been rolled back when they hold an Energy Battery in their hand and shift right click.

**To Reproduce**
1. Hold an Energy Battery in your hand.
2. Shift right click
3. 
**Screenshots**
N/A

**Additional context**
This action is supposed to allow the Energy Battery to recharge other items in your inventory but instead it crashes the client and they are unable to log in till someone has rolled back their player data or removed the item from their inventory through the user data.

**Comment by FuzzyFoxe** [comment]
Integrated dynamics has fixed this bug now, I think:
https://github.com/CyclopsMC/IntegratedDynamics/issues/970
