### ISSUE TITLE
The Digital Miner form mekanism doesn't mine Allthemodium ore

### ISSUE THREAD

**Issue by TrueAsGames** [AllTheMods/ATM-6#922]
Version 1.4.0
**Describe the bug**
The Digital Miner form mekanism doesn't mine Allthemodium ore

**To Reproduce**
1. Go to 'Overworld or mining dimension'
2. Setup Digital miner to mine allthemodium ore
3. After starting the machine, the number of ores to mine goes up and then stops to go back to zero

**Comment by Pdiddy973** [comment]
This is intended, all of the allthemodium ores can not be automatically mined.
