### ISSUE TITLE
Botany tools consume mana (mostly visible when using Ultimine) even tho they have Indestructible

### ISSUE THREAD

**Issue by Prob1ematic** [AllTheMods/ATM-6#923]
Botany tools consume mana from containers from your inventory even with Indestructible. But when you take them out it works fine. Its huge drag when you have to hide all your mana containers into backpack when you mine so your tools with Indestructible enchantment wont eat up all your mana.

**To Reproduce**
1. Have any Botany tool (best works for pickaxe) that repairs with mana
2. Have mana container in your inventory (not empty)
3. Mine some blocks (use Ultimine for easy to seee change)
4. Now put away mana container
5. Mine again (now it works properly)

**Proposed fix**
Disable mana drain for tools with Indestructible enchantment.

**Comment by thevortex** [comment]
If there is a config option to do that sure, the only fix we can implement otherwise would be to stop indestructible from being applied to botania tools by removing the recipes

**Comment by Prob1ematic** [comment]
Ok, i was thinking you can do changes in code as well. I will check for config for that if i wont find it you can mark it as resolved.
