### ISSUE TITLE
Ice and Fire dragons not spawning in atm6

### ISSUE THREAD

**Issue by turbogamer23** [AllTheMods/ATM-6#925]
I've been on a server for a bit, read up on some other issues with dragons not spawning in atm6, been in spectator for quite some time (3k+ blocks from spawn, in the other, changed config to make dragons try to spawn more per chunk, etc), but none of these seem to work, should I downgrade ice and fire? it's pretty frustrating.

**Comment by mkarpoff** [comment]
I ran into this problem too. Dragons no longer spawn in the over world. You need to make a teleporter in the nether to get to the dragon realm.

**Comment by thevortex** [comment]
dragons do spawn, but they are rare, the rates have been increased in 1.5.0 which is available now.they spawn in the other and i verified all 3 dragon types were spawning in their respective areas during testing
Fire Dragons: The Other Basalt Deltas
Lightning Dragons: The Other Deserts/Desert Hills
Ice Dragons: The Other Mountains and Mountain Edges
