### ISSUE TITLE
Cyclic Non Drop

### ISSUE THREAD

**Issue by krabbbbe** [AllTheMods/ATM-6#926]
V: 1.4.1

1. Get a Block from Cyclic that can Hold Items (like Disenchanter)
2. Put Items in the Block
3. Destroy the Block w/ Items inside
4. replace the Block
5. No items in the Block/Items are lost

Expected Behaviour:
- either Drop on Block destroy
- else items stay in Block

**Comment by Salamance73** [comment]
This sounds like a problem for Cyclic to handle and should probably be reported to them.
