### ISSUE TITLE
Eidolon doesn't accept Lead ingots from AllTheOres [ATM6 1.4.1]

### ISSUE THREAD

**Issue by Benzination** [AllTheMods/ATM-6#928]
ATM6 1.4.1

**Describe the bug**
Trying to craft items, such as the Mind-Shielding Plate, using Lead ingots from AllTheOres doesn't work. It only accepts Lead ingots from Eidolon itself, which cannot be crafted in the modpack.

**To Reproduce**
1. Access a Magic Workbench from Eidolon
2. Attempt to craft an Eidolon recipie using Lead ingots from AllTheOres

**Screenshots**

**Additional context**
Eidolon Lead ingots work fine, but as stated, are unobtainable outside of cheats.

**Comment by Salamance73** [comment]
Eidolon dev is aware of this.
[(Enigmatica6 issues)](https://github.com/NillerMedDild/Enigmatica6/issues/794#issue-780814509)

**Comment by ladylexxie** [comment]
Seems like the mod author forgot to update everything. Needs to be reported again to Eidolon.
