### ISSUE TITLE
[1.4.1] Allthemodium Armor recipes are broken

### ISSUE THREAD

**Issue by EnderT5** [AllTheMods/ATM-6#929]
First issue: All Allthemodium armor pieces has a recipe for both with or without Netherite recipes.

Second issue: All Allthemodium armor piece recipes with Netherite armor pieces are shapeless recipes.

Example. https://imgur.com/a/IWJ7mPQ

**Comment by Pdiddy973** [comment]
It is intended, so you can transfer the enchants from the netherite to the new allthemodium.
