### ISSUE TITLE
Altered recipes

### ISSUE THREAD

**Issue by HalJordan** [AllTheMods/ATM-6#93]
How do we revert the changes by allthemodium/allthetweaks to get back to the mod default recipes?

**Comment by WhitePhant0m** [comment]
All the Mods 6\kubejs\data\atm6\kubejs\ct_recipes.js
That has most of the recipe changes, you might not want to delete it tho since it does fix some recipes, but remove parts you don't want.

**Comment by Cleareddrippp** [comment]
could someone please clear me a doubt, can i kubejs from a mod pack without installing the whole mod pack??
