### ISSUE TITLE
Server crash after few minutes. 1.3.8

### ISSUE THREAD

**Issue by Darrath** [AllTheMods/ATM-6#930]
Server version 1.3.8, running on VM on a Dell R720. 6 cores and 64gb allocated to VM.

Was running fine for weeks with 3 players, constant behind on ticks errors while exploring new areas but always caught up. Just had a 4th join towards the end of a 10 hour session yesterday and now server crashes after about 5 minutes of anyone joining, even if it is just one person. Seems to be a lot of duplicate entity errors with strings of numbers for them so I do not know what it is. A few were Piglin entities so I went to the nether and killed them, was something like 150 or so entities removed. Here is the last few crash reports, 2 with all 4 of us in and 1 with just me. The only major things that have changed on the server have been starting Applied Energistics and Powah reactors.

[crash-2021-01-23_22.13.13-server.txt](https://github.com/AllTheMods/ATM-6/files/5863288/crash-2021-01-23_22.13.13-server.txt)
[crash-2021-01-23_23.12.55-server.txt](https://github.com/AllTheMods/ATM-6/files/5863289/crash-2021-01-23_23.12.55-server.txt)
[crash-2021-01-24_13.28.16-server.txt](https://github.com/AllTheMods/ATM-6/files/5863290/crash-2021-01-24_13.28.16-server.txt)

**Comment by iarspider** [comment]
Stop the server, add this to the server.properties: `max-tick-time=-1`, start the server.

**Comment by Darrath** [comment]
I tried this, it seems to have stopped the crashing but the server would freeze every few minutes, for a few minutes, then resume.

I ended up just upgrading to 1.4.1 and it seems fixed.
