### ISSUE TITLE
Oil incompatable

### ISSUE THREAD

**Issue by warderbrad** [AllTheMods/ATM-6#933]
While playing I found oil and was wanting to process it with Thermal's Fractionating Still. It would not accept it as an input. After looking for a while I believe I have concluded that it is a fluid dictionary issue as described in this reddit post (https://www.reddit.com/r/feedthebeast/comments/a0r3u0/is_there_still_no_way_to_convert_thermal/eajzfvl?utm_source=share&utm_medium=web2x&context=3).

There are a few options given for fixing. I am not the owner of the server so I cannot implement the crafttweaker options to give more info.

**Comment by warderbrad** [comment]
Why was this closed with no explanation? This is a repeatable issue. If it is intended to work this way please say so and help me understand why.

**Comment by Letoric** [comment]
It helps to read the requirements for information when posting an issue.
We're no longer chasing that down, as it says in the template.
