### ISSUE TITLE
Refined-Storage Pattern Crafting

### ISSUE THREAD

**Issue by krabbbbe** [AllTheMods/ATM-6#937]
V.1.4.1
Crafting patterns(assembling a recepie to Patterns) works only once
in the Pattern Grid. For multiple patterns to be crafted you have to leave the Grid every time.

1. Place Pattern Grid
2. Fill it w/ patterns 
3. craft one pattern
4. try to craft second item
5. nothing happens/cant craft it only on exiting an going in the grid again

Issue wasn't present in V.1.3.9b or earlier

**Comment by elbim** [comment]
Known problem, when polymorph is installed (https://github.com/TheIllusiveC4/Polymorph/issues/56).
