### ISSUE TITLE
Coral Tombstones, Familiars and voodoo puppet's not craftable  

### ISSUE THREAD

**Issue by CKY-** [AllTheMods/ATM-6#938]
Version: 1.4.1

corail tombstones; 
Familiar Receptacle not craftable
Voodoo Puppet: can't be modified in a crafting table. 

**To Reproduce**
1. make a bone needle  stab anything with it  
2. craft that into a impregnated diamond 
3. craft that into a familiar receptacle 

1. craft a voodoo puppet 
2. try to change what it can do 
3. See error

**Screenshots**
![2021-01-26_12 02 30](https://user-images.githubusercontent.com/8982158/105892037-8ab5bd00-5fce-11eb-880e-abc448501d40.png)
![2021-01-26_12 03 17](https://user-images.githubusercontent.com/8982158/105892083-97d2ac00-5fce-11eb-9a6b-4a067c97d172.png)

![2021-01-26_12 02 37](https://user-images.githubusercontent.com/8982158/105892071-943f2500-5fce-11eb-9430-994982ddc091.png)
![2021-01-26_12 03 09](https://user-images.githubusercontent.com/8982158/105892051-8f7a7100-5fce-11eb-8bec-3581dcefd85c.png)

**Additional context**

**Comment by Corail31** [comment]
@CKY- theses recipes have pre-requites : the voodoo poppet requires to spend points in the perk with the same name and the familiar receptacle requires the lvl 10 in knowledge of death (configurable).
