### ISSUE TITLE
cant even get into the game without it crashing

### ISSUE THREAD

**Issue by kyalll** [AllTheMods/ATM-6#940]
**Describe the bug**

**To Reproduce**

**Screenshots**
<img width="1019" alt="Screen Shot 2021-01-26 at 3 27 45 PM" src="https://user-images.githubusercontent.com/78053065/105914218-4389f500-5feb-11eb-9cec-82f21e3d34cd.png">

**Additional context**

**Comment by icha-senpai** [comment]
update your minecraft launcher 1.6.39 was released on September 8, 2015

**Comment by whatthedrunk** [comment]
I am not familiar with Macs but this is the old MC launcher. Take a look here to see if this helps. https://github.com/AllTheMods/ATM-6/issues/384
