### ISSUE TITLE
Private server - Experience not dropping

### ISSUE THREAD

**Issue by NoAltrerEgo** [AllTheMods/ATM-6#95]
I updated the server to 0.29 today, and the client. From 30 minutes on a enderman farm in the end I got barely 2 or 3 levels.
I mined quartz and the experience drop rate was too low, same for nether gold.
In the Over world, the mobs had the same issues, but the ores on the over world (redstone, lapis, etc) gave experience normally.

**Comment by whatthedrunk** [comment]
We are currently on 1.16.3 so removing older issues to make way for new ones. If you want to test it out join the discord for an early beta. New update will be on Twitch / Curseforge once Mekanism pushes their update to the site.
