### ISSUE TITLE
1.3.9 Only Tier 1 Hive Works - Resourceful Bees

### ISSUE THREAD

**Issue by Gimics** [AllTheMods/ATM-6#950]
**Describe the bug**
I was trying to build an apiary (hadn't really used bees yet) and noticed that bees would only produce one stack of honeycomb in the apiary, after being inserted, and then wouldn't produce anymore. So I pulled them all out and started creating individual hive rooms and none of my bees would enter the tier 3 or tier 4 hives I created. Drop a couple of tier 1's down and they entered immediately.

Still can't get them apiary or the other tier hives to work.

**Comment by Pdiddy973** [comment]
This is fixed in 1.4.0+
