### ISSUE TITLE
ATO Ores not being made with Mineralis Ritual from Astral Sorcery in Pack version 1.4.1

### ISSUE THREAD

**Issue by BlackStone5677** [AllTheMods/ATM-6#951]
Not sure if that's intended or not but title says all

**Comment by iarspider** [comment]
See #805

**Comment by BlackStone5677** [comment]
I made a change in the astral sorcery mineralis ritual config so it supports it 'cause I can't upload toml files here I am gonna document it.
[registries.mineralis_ritual_ore]
		#Format: '<tagName>;<integerWeight>' Defines random-weighted ore-selection data. Define block-tags to select from here with associated weight. Specific mods can be blacklisted in the general AstralSorcery config in 'modidOreBlacklist'.
		mineralis_ritual_ore = ["forge:ores/coal;5200", "forge:ores/iron;2500", "forge:ores/gold;550", "forge:ores/lapis;360", "forge:ores/redstone;700", "forge:ores/diamond;120", "forge:ores/emerald;100", "forge:ores/osmium;150", "forge:ores/nickel;180", "forge:ores/platinum;100", "forge:ores/tin;220", "forge:ores/copper;220", "forge:ores/silver;180", "forge:ores/aluminum;220", "forge:ores/uranium;130", "forge:ores/zinc;220", "forge:ores/lead;150"]
It's the change made in the astralsorcery.toml file in the directories : instancefolder/saves/save/serverconfig and instancefolder/config

If you wanna know how the numbers are acquired it is :
(((max_y - min_y)+1)* deposit_size) round up to 10 for the different ores in the ATO config folder as it seemed like diamonds are kinda the same (e.g. : ((20 - 40)+1)*7 for osmium and lead)
I thought it's a good change if noone want's to go through the math

**Comment by whatthedrunk** [comment]
ill close this issue as its a duplicate and share the information to the dev team.
