### ISSUE TITLE
ATM 6 Linux Server "Incomplete Set of Tags received from Server"

### ISSUE THREAD

**Issue by RFA81** [AllTheMods/ATM-6#952]
ATM6 1.4.1  Forge 35.1.36
when i connect to the server i will get following error

> Connection Lost
Incomplete set of tags from server
please contact server operator

I m running the server on a HP ELITEBOOK 820 G3 with 16GB RAM on a debian 10.7 system. 
Start script with following command "java -Xmx8192M -jar minecraft_server.1.16.4.jar"

Server and Client are without changes. 
Server installed with installer.jar
Client installed via Curseforge on Windows 10 

Attached the debug.log and latest.log
[debug.log](https://github.com/AllTheMods/ATM-6/files/5889284/debug.log)
[latest.log](https://github.com/AllTheMods/ATM-6/files/5889287/latest.log)

**Comment by GAJ3T** [comment]
Same problem here only differences are the server OS (Ubuntu 20.04 LTS) and Memory allocation (-Xmx16G) in command

**Comment by whatthedrunk** [comment]
You need to edit the start script to target the forge jar not the minecraft server jar. It should look like forge-1.16.4-36.0.9.jar on the newest version.

**Comment by GAJ3T** [comment]
> You need to edit the start script to target the forge jar not the minecraft server jar. It should look like forge-1.16.4-36.0.9.jar on the newest version.

Even if we're trying to host a 24/7 server on a remote machine?
