### ISSUE TITLE
1.5.0 server needs 2 versions of forge?

### ISSUE THREAD

**Issue by MaDJaMeS89** [AllTheMods/ATM-6#955]
**Describe the bug**

Running ATM 6 on Akliz when i update the world from 1.4 and try to launch the console is throwing missing forge 1.16.5-36-6-01. 

Error: Unable to access jarfile forge-1.16.5-36.0.1.jar

**To Reproduce**

**Screenshots**

**Additional context**

**Comment by whatthedrunk** [comment]
I sent them a message to see what might of happened. It should be using Forge 36.0.9

**Comment by whatthedrunk** [comment]
If you can open a ticket with them they can take a look and help fix it for you.

**Comment by whatthedrunk** [comment]
I was also just informed to make sure you are using the current hotfixed 1.5.0 their system was on an older test version we had that had some issues.
