### ISSUE TITLE
Fluix seed missing recipe

### ISSUE THREAD

**Issue by fledermaus101** [AllTheMods/ATM-6#956]
1.4.0

Currently the recipe for **fluix** isn't working and not correct.

![grafik](https://user-images.githubusercontent.com/73125184/106276036-2f3a3800-6237-11eb-89c2-7320bfa0a514.png)

**Comment by WhitePhant0m** [comment]
It's a visual bug, the recipe is there, and works, just fluix crystals don't show up in it

**Comment by WhitePhant0m** [comment]
also, seems to be a dublicate of #775
