### ISSUE TITLE
ATM minedim missing

### ISSUE THREAD

**Issue by gbusrt** [AllTheMods/ATM-6#957]
All the Mods 6-1.5.0
ATM mineing dim missing 
oversight ?
issue ?
by design?

**Comment by gbusrt** [comment]
upgraded, dim gone
cant use pad to get to dim

**Comment by gbusrt** [comment]
made a new pad still not working

**Comment by whatthedrunk** [comment]
Try restarting your game and if you're on a server restart it.

**Comment by gbusrt** [comment]
yup that worked 
thx
