### ISSUE TITLE
Server not launching

### ISSUE THREAD

**Issue by Liwixion** [AllTheMods/ATM-6#958]
When i start my server, it shows me this error https://pastebin.com/Q4N2ZwSS
Can someone help me ?

**Comment by whatthedrunk** [comment]
This seems to be loading an old version of forge. Try updating to 1.5.0 using the newest forge and open a new issue if you cannot launch thanks!

**Comment by Liwixion** [comment]
It's not working, i am with the curseforge server (the one we can install easily with curseforge)
