### ISSUE TITLE
Remove Quark from all versions of All The Mods that have BLM Propaganda

### ISSUE THREAD

**Issue by SephirothWS** [AllTheMods/ATM-6#96]
![Image](https://i.imgur.com/a7EqvKF.png)

Updated my client instance to 0.29, been playing the pack on previous versions. Loaded up the pack and clicked Multiplayer to join the server I usually play on, only to be greeted by this trash.

The mod author of Quark refuses to remove this propaganda from the mod, and all issues made on Quark's github gets immediately locked and limited as Vazkii wants to continue shoving this drama into our faces. I'm sorry, this crap belongs on Social Media where it should stay, not in a Minecraft Mod, not in a game. Thank you.

**Comment by oly2o6** [comment]
i am not at liberty to discuss the quark BLM screen as we do not have any more power than you do to do anything about it, whilst i do believe this is not the correct way to promote the movement as the concept of death to children is either unknown or frightening, you should take this up with the mod author not us as we will not be removing quark at this time.

**Comment by SephirothWS** [comment]
@oly2o6 As I mentioned before:
https://github.com/Vazkii/Quark/issues/2466
https://github.com/Vazkii/Quark/issues/2432
https://github.com/Vazkii/Quark/issues/2424
https://github.com/Vazkii/Quark/issues/2417
The mod author refuses to remove it from the mod.

**Comment by coffeeordeath** [comment]
Then I guess you just gotta deal with it. Once. That’s seriously it. Once. Then you press escape twice when it pops up. It literally lasts a whole second. 

Find other shit to complain about.

**Comment by SephirothWS** [comment]
I did, several months ago, then Quark went and updated and extended the
stupid garbage which brought it back despite having already played leap
frog through his godawful fucking hoops.
