### ISSUE TITLE
Curseforge ATM6 Server not launching

### ISSUE THREAD

**Issue by Liwixion** [AllTheMods/ATM-6#960]
When i start my server its start to launch, then it show me that and stops https://pastebin.com/Q4N2ZwSS
Can someone help me ?I tried to change the forge version but it didn't worked

**Comment by whatthedrunk** [comment]
If its 1.5.0 its a wrong forge issue. Look into your curseforge install folder that should look something like "\Install\libraries\net\minecraftforge\forge\1.16.5-36.0.9"
In that folder let me know if you see "forge-1.16.5-36.0.9-client"

If that file is missing you will need to install forge manually and add that file into that folder and then select that forge version again and it should work.

**Comment by Liwixion** [comment]
No, it's forge-1.16.4-35.1.37. How do i change it ?

**Comment by whatthedrunk** [comment]
If you download the new server files and run them it will fetch all the new forge files. You can then copy your current world into the new server files. 
If the files are hosted remotely then also download and run the files locally. One the server delete the mods, configs, libraries and kubejs folders and then copy newly generated files to the remote server. Also delete the current forge jar and upload the new one.
