### ISSUE TITLE
Teleport from Allthemodium

### ISSUE THREAD

**Issue by RickyGeo** [AllTheMods/ATM-6#961]
The teleport dost work and i cant use Waystone to mining dimension or the Other Dimension 
i use ATM 1.16.5 
for Screenshot i thing it dosnt need that cause just teleport

**Comment by MerimaDev** [comment]
> The teleport dost work and i cant use Waystone to mining dimension or the Other Dimension
> i use ATM 1.16.5
> for Screenshot i thing it dosnt need that cause just teleport

For me restarting the server worked out, after 1 restart everything worked fine.

**Comment by whatthedrunk** [comment]
Duplicate of https://github.com/AllTheMods/ATM-6/issues/957
