### ISSUE TITLE
Extreme lag openng AE2 pattern terminal

### ISSUE THREAD

**Issue by Nidaelie** [AllTheMods/ATM-6#962]
After a while i get inase lag when opening the ae2 pattern terminal, the memory goes crazy.

If i close it all goes fine but no way opening the terminal. The rest of terminals works fine, looms somthing concerning the recipes cache

**Comment by EchKLLP** [comment]
This is happening to me too on v1.5.0

**Comment by alphaomega21** [comment]
I can confirm this issue is also happening on v1.5.1. My game also freezes if I try to overwrite an existing recipe without first clearing the pattern.

**Comment by EchKLLP** [comment]
Seems like this is caused by Performant. I have been playing for a few days with that mod removed and this hasn't happened for me anymore (yet).

**Comment by whatthedrunk** [comment]
Next update we plan to remove performant until we test it with a few other issues more. Right now it's causing issues with a few other things.

**Comment by whatthedrunk** [comment]
should be good in 1.5.2 now. If there is still issues let me know.
