### ISSUE TITLE
ATM 6 1.16.4 pack

### ISSUE THREAD

**Issue by DragonKing810** [AllTheMods/ATM-6#963]
Is there a way to reduce the traveling plague doctor? I have been playing for several days and have not seen not 1 traveling merchant in all my time playing it myself in single player. ( this was over the course of a week of playing )

**Comment by whatthedrunk** [comment]
I don't currently see a config for that but try asking the Rats dev to see if he wants to add the feature.

**Comment by DragonKing810** [comment]
it seems he did a fix > https://github.com/Alex-the-666/Rats/commit/bbaa01af8cbccfa6c88f042a5898149f0d6e906f
