### ISSUE TITLE
Passive Mobs Not Spawning (1.5)

### ISSUE THREAD

**Issue by qooq8poop** [AllTheMods/ATM-6#964]
I have been having this issue for both 1.3.7 and after I've updated to 1.5. I've used two worlds, both on default generation settings. Mobs spawn in new chunks but I haven't been having new passive mobs spawn. Hostile mobs have been spawning just fine. I've seen others have similar issues and I haven't found any solutions.

**Comment by whatthedrunk** [comment]
If you want you can give this mod a shot. https://www.curseforge.com/minecraft/mc-mods/respawnable-animals
