### ISSUE TITLE
[1.4.1] Mystical agriculture rubber seeds have no crafting recipe

### ISSUE THREAD

**Issue by P0LarBeaR1** [AllTheMods/ATM-6#965]
As in the title, rubber seeds do not have a crafting recipe with infusion crafting

**Comment by Slaymeister** [comment]
Repeat of [](https://github.com/AllTheMods/ATM-6/issues/905)  There are a lot of them that are missing the crafting or the crafting recipe is broken. I'm not sure if it's intentional.

**Comment by whatthedrunk** [comment]
Closing as it's a duplicate.
