### ISSUE TITLE
Putting any mana tablet in a crafting table by itself crafts an everlasting guilty pool

### ISSUE THREAD

**Issue by dumbomb** [AllTheMods/ATM-6#967]
1.5.0 with optifine and newest industrial foregoing

**Comment by taj1994** [comment]
Screenshot to confirm
![image](https://user-images.githubusercontent.com/1844822/106362999-15562f00-62e3-11eb-80be-2242252121e8.png)

This seems like a pretty big problem, since once you have a couple white mystical flowers, it'll only take a few minutes to get infinite mana

**Comment by whatthedrunk** [comment]
This seems to be fixed if you update KubeJS and Rhino. This fix will be added in 1.5.1 out later today.
