### ISSUE TITLE
You can't chisle some of the blocks, for ex. Gold block

### ISSUE THREAD

**Issue by Prob1ematic** [AllTheMods/ATM-6#968]
V. 1.4.1

**Describe the bug**
You can't use chisle on some of the blocks like Gold block

**To Reproduce**
1. Get chisle (i was using netherrite one)
2. Place gold block (or Emerald block, may be some more didnt tested all)
3. Left click chisle on it (it doesnt chisle, other materials work fine)

**Comment by whatthedrunk** [comment]
This seems to work in my current 1.5.1 build that will be out later today. After you update if you are still having issues let me know.
