### ISSUE TITLE
Thermal foundation Hammers 

### ISSUE THREAD

**Issue by Th3lonehunter** [AllTheMods/ATM-6#969]
Hi,
not sure if this is set intentionally but i can seem to find the thermal foundation Hammers when in game, im not sure if this a bug or a setting and if possible can i please have help with re-enabling them.

many thanks

**Comment by jeremiahwinsley** [comment]
Hammers have not been added to 1.16 Thermal yet.

**Comment by Th3lonehunter** [comment]
Ah thank you very much i didnt know this :)
