### ISSUE TITLE
Animal Rancher not collecting milk 1.5.0

### ISSUE THREAD

**Issue by geeee785** [AllTheMods/ATM-6#971]
Just updated to 1.5.0, and my Animal Rancher from Industrial Foregoing, is not storing the milk.  The sounds of the cows being milked is being made, but nothing shows up in the rancher.  Prior to upgrading it had worked fine.

**Comment by WhiteLionATX** [comment]
Same issue for me. The rancher makes the "milking sound" but does not collect milk.

**Comment by geeee785** [comment]
It looks like it is an error on Industrial Foregoing's end and they have already patched the issue on an update that came after ATM 1.5.0.  I guess this will be resolved on the next update.

**Comment by whatthedrunk** [comment]
Verified this is fixed if you update the mod. 1.5.1 will be out later today with the fix.
