### ISSUE TITLE
Eidolon/MineColonies clash with Cracked Stone Bricks recipie 1.4.1

### ISSUE THREAD

**Issue by Benzination** [AllTheMods/ATM-6#972]
When trying to teach the recipie to a MineColonies Stone Smeltery for Cracked Stone Bricks (Putting regular Stone Bricks into a furnace) it gives the recipie for Smooth Stone Bricks from Eidolon. As a player you can choose the little swap-recipie button in the furnace, but there is no way to teach the Smeltery NPC to do that themselves and thus they can only ever cook up Smooth Stone Bricks and not the required Cracked Stone Bricks.

**Comment by sgehtn** [comment]
Can confirm, we ran into the same issue on our server within valhelsia 3 modpack (3.3.3). Using minecolonies version 0.14.206-ALPHA.

**Comment by ladylexxie** [comment]
Will be fixed in the next version. #1965
