### ISSUE TITLE
[1.5.0] Crash with Pixie Villages

### ISSUE THREAD

**Issue by jeremiahwinsley** [AllTheMods/ATM-6#973]
**Describe the bug**
Pixie village crashes, multiple reports in Discord#atm6-help

Crash log: https://pastebin.com/NTt2Es36

Seems to be related to village size, default of 5 fixes it for some reports

**Comment by whatthedrunk** [comment]
config changed to default for 1.5.1 coming out later today.

**Comment by cosmoderp** [comment]
I changed it from 25 to 20 and flew around an hour in creative.  No crash so far.  So you can consider that later.
