### ISSUE TITLE
1.5.0 Crash - Upon placing Silent Gear machete in anvil

### ISSUE THREAD

**Issue by csuarezmtz** [AllTheMods/ATM-6#974]
Game crashes  when placing Silent Gear in anvil for enchanting. 

**To Reproduce**
Place an enchanted Silent Gear item in an anvil.

**Additional context**
Crash Log: https://pastebin.com/ue1kfC66

**Comment by whatthedrunk** [comment]
Seems to work in my 1.5.1 update that will be out later today. Let me know if you are still having the issue when you update.
