### ISSUE TITLE
[1.5.0] Allthemodium Teleport Pad Not Working

### ISSUE THREAD

**Issue by kronoize** [AllTheMods/ATM-6#976]
**Describe the bug**
Trying to go to the mining dimension using the teleport pad does not work. I've tried breaking and replacing the block and it still didn't fix it. I don't have anything in my off hand nor main hand.

**To Reproduce**
1. Place down a Teleport Pad
2. Try to teleport to the mining dimension

**Screenshots**
![2021-01-30_18 49 38](https://user-images.githubusercontent.com/22014991/106373180-d0a2b600-632b-11eb-8140-34a7dc6afd35.png)

Picture of me in my test world trying to teleport to mining dim.

**Comment by Gh0stl0rd** [comment]
Same for me.

**Comment by elbim** [comment]
Relogin/Restart helps. Saw this solution somewhere on reddit an this fixed it for me.
This happens both crafting it and cheating it in, in the overworld as well as in the nether.

**Comment by QingShuiMuYang** [comment]
Same for me. And Its just happened in server, I had tried to use that in singleplayeys and its working.

**Comment by kronoize** [comment]
Restarting the server seems to have worked for me. If the issue persists even after a restart for anyone else, I would say create a new issue.

**Comment by Defender57557** [comment]
It doesn't work for me at all(
