### ISSUE TITLE
Suggestions That could be game changing for ATM 6

### ISSUE THREAD

**Issue by BlackStone5677** [AllTheMods/ATM-6#978]
1- UU-Matter is pretty naff currently so let's notch it up a bit and instead the boring old stuff it gives make it give some of the mystical agriculture essences. Like stone, nature, water, fire, etc. could be useful if you need some stone quickly, etc.
2a- ATM Star's Crafting recipe will use mechanical crafting from Create in the future(My Favorite option)
2b- ATM Star's Crafting recipe will use Compact Crafting from the Compact Crafting mod
3- Make apotheotic mob spawner(It's a spawn egg for the boss mobs that spawn) craftable: The recipe I have in mind is a normal spawn egg wrapped up with 4 insanium/creative essence

**Comment by whatthedrunk** [comment]
ATM Start and Endgame items are all currently being worked on for ATM6. The UU Matter was just testing out some stuff early on but decided to keep it to help with end game automation. Thanks for the feedback/suggestions.
