### ISSUE TITLE
Mobs from mod-placed spawners seem to be immune to lava.

### ISSUE THREAD

**Issue by xenoflot** [AllTheMods/ATM-6#98]
Hi folks,

Twice now I've encountered mobs that were able to swim in lava without taking any damage. In both cases they were spawned by vanilla spawners that had been placed by a mod (not the Quark 1-shot type). Illustration: https://i.imgur.com/UdcGJNu.png

Cheers

**Comment by whatthedrunk** [comment]
Let me know if this is happening for you on the version below. Trying to clean stuff up to only 1.16.3

We are currently on 1.16.3 so removing older issues to make way for new ones. If you want to test it out join the discord for an early beta. New update will be on Twitch / Curseforge once Mekanism pushes their update to the site.
