### ISSUE TITLE
Pulvirezer_osmium_ingot_to_dust.json missing

### ISSUE THREAD

**Issue by Armorjin** [AllTheMods/ATM-6#980]
Pulverizer can't make osmium dust from alltheores osmium. JEI shows recipe for mekanism osmium to dust.
I suggest add json file for osmium dust recipe to pulverizer

**Comment by Armorjin** [comment]
Made fix myself. Path: ATM6\mods\alltheores-1.1.20-1.16.4-35.1.13.jar\data\alltheores\recipes\thermal_pulverize\

[pulverizer_osmium_ingot_to_dust.zip](https://github.com/AllTheMods/ATM-6/files/5900120/pulverizer_osmium_ingot_to_dust.zip)

**Comment by Letoric** [comment]
Can you name any non Mekanism recipe that uses Osmium?

**Comment by Armorjin** [comment]
No, but it's not related to this issue. JEI shows recipe for osmium dust in pulverizer, but using mekanism osmium, not alltheores osmium

**Comment by Armorjin** [comment]
And of course you can pulverize osmium ore to dust, but not ingots to dust. So this it

**Comment by Letoric** [comment]
If there is no use for the ore except for in Mekanism, there's not really any reason to have other mods handling it. It would be different if Osmium was used in more than 1 mod.

**Comment by Armorjin** [comment]
Ok. But I disagree. Mekanism and Thermal dust mechanics identical and this issue with alltheores, not mekanism or thermal itself. If you put mekanism:osmium ingot in pulverizer it will be turned to dust. This issue might be with ore dictionary but ether way I fix it and I think that it's should be fixed in next update.
