### ISSUE TITLE
Tps Lag and constant "Waiting for server" after 2 / 3 hours gametime (server)

### ISSUE THREAD

**Issue by MiagoMeowsome** [AllTheMods/ATM-6#982]
Two days ago we installed version 1.5.0 of ATM6 on a fresh server and started experiencing lag spikes after 2 / 3 hours of being on the server. A server restart fixes it but the more the server is online the worse it gets.

There is three players on the server on two different bases with not much built

I installed spark and generated this report 
https://spark.lucko.me/#KTKBuC71sA

If nothing seems out of the ordinary I'll try to reinstall the server and transfer the map to see if it will fix anything

**Comment by MrEssex** [comment]
Just a heads up, upgrading to the latest version of Forge has fixed all server tps issues for me
