### ISSUE TITLE
RFtoolsutility : Missing Recipe(s)

### ISSUE THREAD

**Issue by StrayCargo** [AllTheMods/ATM-6#984]
Pack Version 6-1.5.0
<!
Missing Recipes for some items for RFtoolsutlity such as the elevator button module
!>
![evidance2021](https://user-images.githubusercontent.com/8396060/106395496-288efa80-63c8-11eb-8bec-1c84219b8bb5.PNG)
![evidance2021-2](https://user-images.githubusercontent.com/8396060/106395498-29279100-63c8-11eb-9d89-16d333cf530c.PNG)

**Comment by Letoric** [comment]
Are they present with only RFTools Utility and required libraries?

**Comment by jeremiahwinsley** [comment]
Not a bug, these items (and other RFTools items without recipes) are not implemented yet.
