### ISSUE TITLE
Terraforged + ATM6

### ISSUE THREAD

**Issue by turbogamer23** [AllTheMods/ATM-6#987]
I've played atm6 on a server without terraforged (it ran fine), made a new world and added terraforged (made a single player world and moved it to server files), server tps immediately suffered, I've been told it's most likely due to terraforged being incompatible with the pack, is this true?

**Comment by whatthedrunk** [comment]
I don't see why it would not be compatible. Maybe you can try removing BOP or BYG to see if maybe one of them is conflicting with it.
