### ISSUE TITLE
Ftbchunks issue causing game to crash

### ISSUE THREAD

**Issue by BHGHOST5257** [AllTheMods/ATM-6#995]
**Describe the bug**
A most recent crash on All the mods 6 Released version 1.5.0

So when I open the claiming map and claim the chunks I want tends to be multiple at a time, when I try and exit the map after claiming some chunks it causes my game to crash. I've
 attached the crash-log 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'chunk claiming map'
2. Claim a few chunks 
3. Try to exit the chunks map
4. See the error

**Screenshots**
[crash-2021-01-31_11.36.54-client.txt](https://github.com/AllTheMods/ATM-6/files/5908355/crash-2021-01-31_11.36.54-client.txt)
**Additional context**
I've tried multiple Releases of the pack and tried different worlds

**Comment by Letoric** [comment]
You are in an unsupported configuration. We do not have worldedit or the client UI in the pack.
java.lang.NullPointerException: keyPressed event handler
	at com.github.hexomod.worldeditcuife3.aN.a(KeyBinderManager.java:122) ~[?:3.0.8] {re:classloading}
