### ISSUE TITLE
Serverstarter Script problems on Ubuntu 18.04.5

### ISSUE THREAD

**Issue by scorewinner** [AllTheMods/ATM-6#998]
**Describe the bug**
I tried to run the serverstarter.sh script (pack version 1.4.1 AND 1.5.0) downloaded from the curseforge page on my Ubuntu server. I ran into an issue with several faulty / unknown Java args and it wasn't able to create the Java VM. Because of that, the server was not able to start.

**To Reproduce**
1. Create empty folder on Ubuntu
2. download SIMPLE-SERVER-FILES into that folder
3. execute serverstarter.sh

**Additional context**
I was able to run the script after removing multiple java args from the `serverstarter.sh` and `server-setup-config.yaml`.

**Following args needed to be removed:**
*In the serverstarter.sh*
- removed `-d64` from all java execute commands

*In the server-setup-config.yaml*
- removed `-d64` from `javaArgs`
- removed `-XX:+UseParNewGC` from `javaArgs`
- removed `-XX:+UseFastAccessorMethods` from `javaArgs`

**Comment by jeremiahwinsley** [comment]
Not a bug, we do not officially support Java 11 yet.
