### ISSUE TITLE
No unobtanium with BetterEnd installed?

### ISSUE THREAD

**Issue by GordonHollow** [AllTheMods/ATM-6#999]
ATM6-1.4.1 minecraft 1.16.4
Totally no unobtanium with betterend generation in the end. I swithc to creative and fly around 5k blocks with UnobtaniumSightPotion - can't see any unobtanium ore

1)Install ATM
2)Add BetterEnd and enable it's generation
3)No unobtanium

**Comment by Pdiddy973** [comment]
Can't support the pack if you modify it esp if you change something like world gen and then something doesn't work.

Please play as provided and see if you still get the issue.

**Comment by GordonHollow** [comment]
Possibly adding BetterEnd to modlist in some ATM6 updates?

**Comment by Pdiddy973** [comment]
We already have BYG not sure what better end exactly does, but feel free to add it to the suggestions

**Comment by thevortex** [comment]
if BetterEnd removes the vanilla biomes (specifically the biome that unobtainium does spawn in(End Highlands)) there isn't much we can do for that

**Comment by GordonHollow** [comment]
Nope, end highlands still here. But can't find any unobtanium in this little islands, even with creative and potion of sight. Another mod generation biome and ores/trees/blocks, include BYG also is here. So maybe it's just extremely lower the chances of EndHighlands...

**Comment by GordonHollow** [comment]
Well, totally after regenerate End with latest version of BetterEnd fix that problem
So ATM6 compatible with this mod nicely)
Feel free to add this, i go to suggestion
